---
layout: sig
title: "User Experience"
section: sigs
sigId: "ux"
logo: /images/sigs/ux/logo.svg
opengraph:
  image: /images/sigs/ux/opengraph.svg
tags:
  - ux
  - ui
  - user_experience
  - user_interface
leads:
- "notmyfault"
- "janfaracik"
- "uhafner"
- "timja"
links:
  gitter: "jenkinsci/ux-sig:matrix.org"
  meetings: "https://docs.google.com/document/d/1QttPwdimNP_120JukigKsRuBvMr34KZhVfsbgq1HFLM/edit?usp=sharing"
  forum: "ux-sig"
overview: >
  This special interest group focuses on improving the Jenkins' user interface and user experience.
  The SIG seeks regular feedback from the community on the current UI and UX and new designs proposed by SIG members and others.
  We will discuss alternatives, identify compromises, and test implementations to improve the Jenkins UI / UX.
---

An overview of previous results of the Jenkins UX SIG is available in an link:https://docs.google.com/document/d/1J3HsxYdNPDZpFzCz6HWGcIhsY3urOXOZmiMiGR1D-ew/edit?usp=sharing[external document].
Most of these results have been integrated into Jenkins core in the meantime.

== Topics

* Reviewing new UI proposals
* Discussing UI frameworks, libraries and assets
* Discussing impact of UI changes to existing plugins

== Gitter Channel
The UX SIG uses a link:https://app.gitter.im/#/room/#jenkinsci/ux-sig:matrix.org[Gitter room] and the
link:https://community.jenkins.io[Jenkins community] to discuss any relevant topics.

== Contributing
If you want to contribute we recommend that you join the Jenkins UX SIG. You can find details of when the next meetings are planned in the Jenkins Calendar or via the link:https://app.gitter.im/#/room/#jenkinsci/ux-sig:matrix.org[jenkinsci/ux-sig Gitter room].

[[ongoing-projects]]
== Projects

The special interest group drives a number of initiatives within the link:/project/roadmap/[Jenkins roadmap].
Here are the most important ones:

[[project-ui-look-and-feel]]
=== UI/UX: Jenkins Look and Feel updates

One UX SIG project is revamping the Jenkins UI look and feel.
This is an ongoing effort, new features will be integrated step by step into the Jenkins weekly releases.

[[project-ui-accessibility]]
=== UI/UX: Accessibility

We would like to make Jenkins usable by as many people as possible.
It includes multiple groups of users: people with disabilities, ones using mobile devices, or those with slow network connections.
In general, all Jenkins users would benefit from better navigation and layouts.

See the jira:JENKINS-62268[] EPIC for more details about the scope.

[[design-library]]
=== UI/UX: Jenkins Design Library

The UX SIG has released the updated link:https://weekly.ci.jenkins.io/design-library[Jenkins Design Library 3].
This release provides an enhanced experience for developers looking to create and customize their Jenkins UI.
Read more and explore the Jenkins Design Library 3 link:/blog/2025/01/10/design-library/[in our announcement blog post].

== Meetings
We have regular meetings on Wednesday every four weeks, at *4PM UTC*.
See the link:/event-calendar[Jenkins Event Calendar] for the schedule.
At these meetings we discuss projects, share presentations, and demonstrate new capabilities.
Meetings are conducted and recorded using Zoom and are archived to the link:https://www.youtube.com/user/jenkinsci[Jenkins YouTube channel] in the link:https://www.youtube.com/playlist?list=PLN7ajX_VdyaOnsIIsZHsv_fM9QhOcajWe[Jenkins UX SIG YouTube playlist].

=== Meeting Agendas
Meeting agendas and meeting notes for the SIG are posted in link:https://docs.google.com/document/d/1QttPwdimNP_120JukigKsRuBvMr34KZhVfsbgq1HFLM/edit?usp=sharing[this Google Document].
Anyone is welcome to add a topic for an upcoming meeting by suggesting a change in the link:https://docs.google.com/document/d/1QttPwdimNP_120JukigKsRuBvMr34KZhVfsbgq1HFLM/edit?usp=sharing[agenda].

++++
<iframe src="https://docs.google.com/document/d/1QttPwdimNP_120JukigKsRuBvMr34KZhVfsbgq1HFLM?embedded=true" width="100%" height="600px"></iframe>
++++
