---
layout: gsocprojectidea
title: "Automatic git cache maintenance on the controller"
goal: "Automate the maintenance of cached git repositories on the Jenkins controller"
category: Tools
year: 2022
status: published
sig: platform
skills:
- Java
mentors:
- "markewaite"
- "rishabhbudhouliya"
- "krisstern"
links:
  emailThread: https://community.jenkins.io/t/google-summer-of-code-gsoc-2022-call-for-organizers-mentors-and-project-ideas/1010/7
---

Recent versions of command line git (since 2.30.0) have a set of commands for "git maintenance" that can be used to regularly update and maintain the contents of a git repository.

=== Background

Git caches that exist on the controller can become slower and larger than necessary during use.
Command line git focuses on high performance for frequent operations.
Command line git relies on end users to perform most repository maintenance.
Garbage collection, removal of deleted branches, and other operations are not performed by default on most cached repositories.

=== Quick Start

Review the features available from "git maintenance" and identify ways that the Jenkins controller could use those features or implement similar capabilities to manage the cached copies of git repositories.
Review issues in the Jenkins issue tracker that may indicate other areas where git plugin repository maintenance could help the Jenkins controller.

=== Skills to Study and Improve

* Java
* Git

=== Project Size

175 hours

=== Newbie Friendly Issues

* link:https://issues.jenkins.io/issues/?jql=labels%20%3D%20newbie-friendly%20AND%20status%20not%20in%20(Closed%2C%20Done%2C%20Resolved%2C%20%22Fixed%20but%20Unreleased%22)%20AND%20component%20%3D%20git-plugin%20AND%20project%20%3D%20JENKINS[Git plugin issues] friendly to a new contributor
* link:https://issues.jenkins.io/issues/?jql=labels%20%3D%20newbie-friendly%20AND%20status%20not%20in%20(Closed%2C%20Done%2C%20Resolved%2C%20%22Fixed%20but%20Unreleased%22)%20AND%20component%20%3D%20git-client-plugin%20AND%20project%20%3D%20JENKINS[Git client plugin issues] friendly to a new contributor
