---
layout: gsocprojectidea
title: "Jenkinsfile Runner Action for GitHub Actions"
goal: "(Goal to be described)"
category: Tools
year: 2022
status: draft
sig: platform
skills:
- Java
mentors:
- "oleg_nenashev"
- "kris_stern"

// links:
//   gitter: "jenkinsci/plugin-installation-manager-cli-tool"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---

=== Main ideas

This project's description is based on the previous POC work that can be found link:https://github.com/jenkinsci/jenkinsfile-runner-github-actions[here]

* link:https://jenkins.io/blog/2018/10/16/custom-war-packager/#jenkinsfile-runner-packaging[Automate] the creation of the pre-packaged Jenkins Docker container
* Populate Jenkins environmental variables based on the link:https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#environment-variables[GitHub Actions context]
* Find a better way to populate the job workspace with the content of `/github/workspace` other than manually copying the files over as part of your `Jenkinsfile`
* Find a better way to package `maven` binaries and additional plugins
* Find a better way to share `maven` plugins other than manually mapping the local `maven` repo to `/github/workspace/.m2` in your `Jenkinsfile`
* Find a better way to cache the lazy-loaded Jenkins as `/github/workspace/.jenkinsfile-runner-cache` as specified link:https://github.com/jonico/jenkinsfile-runner-github-actions/blob/master/jenkinsfile-runner-lazyloaded/Dockerfile#L19[here]
* Add examples of how to work with link:https://github.com/ndeloof/jenkinsfile-runner#sensitive-data[Jenkins secrets], as additional documentation
* Provide examples how to copy parts of the Jenkins results to an external storage, perhaps as additional documentation

// === Background
// TBD

// === Quick Start
// TBD

// === Skills to Study and Improve
// * TBD

// === Newbie Friendly Issues
