---
layout: gsocprojectidea
title: "Plugin Installation Manager Tool Improvements"
goal: "Introduce new features and improvements in the plugin installation manager"
category: Tools
year: 2022
status: published
sig: platform
skills:
- Java
- YAML
- Command line tools
- Package management tool theory
mentors:
- "markewaite"
- "abhyudayasharma"
links:
  gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
  draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---
=== Background

In 2019 there was a Jenkins Google Summer of Code project to create a tool to automatically install plugins from the command line based on a provided input.
This is meant to help with creating reproducible environments and other places where you would want to install a certain set of plugins.
The project was successful in creating a useable tool to install plugins with a 1.0 release.
Over time, the plugin installation manager was improved and added to other components like official Jenkins Docker images.

As a part of this project,
students are invited to introduce new features and improvements in the plugin installation manager.
The list of enhancements is a subject for discovery as a part of the application process.
Some of the ideas are available in the link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues[project tracker].

=== Quick Start

Visit the project page at https://github.com/jenkinsci/plugin-installation-manager-tool

1. Clone the project
2. Run the tests; there are several different lists of plugins
3. Run the Plugin Installation Manager for various combinations of plugins with a real Jenkins instance.
   See how the downloads and caching work.
4. Try out some edge cases to see what could be improved.

=== Skills to Study and Improve

* Java
* YAML/data structures/package management tools
* Writing command line interfaces
* How the Jenkins Docker image and Configuration as Code (CasC) work


=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours

=== Expected outcomes

Improvements to existing tool

Key improvements for the plugin installation manager tool will be identified, prioritized, and planned.
Google Summer of Code contributor will propose the areas for improvement and work with mentors to plan those improvements.

=== Newbie Friendly Issues

Some good first issues are available in the link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[issue tracker].
For information about how to contribute to and what to work on, please use the link:https://app.gitter.im/#/room/#jenkinsci_plugin-installation-manager-cli-tool:gitter.im[gitter channel].
