---
layout: section
title: Best Practices
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Continuous Integration (CI) with automated test execution and trends has changed the way companies look at build management, release management, deployment automation, and test orchestration.
This section describes best practices to provide executives, business managers, software developers, and architects with a better sense of what Jenkins can contribute throughout the project lifecycle.

== Automate job definition

Jenkins can automatically create, update, and delete jobs based on the repositories it detects in your software configuration management system.
Structure your job definitions to get the most benefit from automatic job management by Jenkins.

There are multiple alternatives for automatic job management, including:

* <<Use organization folders>> - create, update, and delete multibranch Pipeline folders and Pipeline jobs automatically (preferred)
* <<Use multibranch Pipelines>> - create, update and deleted Pipeline jobs automatically
* <<Use Pipeline>> - manually defined Pipeline jobs

=== Use organization folders

Organization Folders offer a convenient way to allow Jenkins to automatically create and delete jobs as repositories and branches are created and deleted.
If you use GitHub organizations, Bitbucket teams, GitLab groups, or Gitea organizations, then Jenkins can automatically detect the creation of a new repository and create a Multibranch Pipeline project for it.

Refer to the link:/doc/book/pipeline/pipeline-as-code/#organization-folders[organization folders] documentation for more details.

.GitHub organization folders
video::LbXKUKQ24T8[youtube,width=800,height=420]

.GitLab group folders
video::it6TOeQ6EHg[youtube,width=800,height=420]

.Bitbucket project folders
video::85b6fiVolfk[youtube,width=800,height=420]

.Gitea organization folders
video::NO3sZWRxgQM[youtube,width=800,height=420]

=== Use multibranch Pipelines

If something prevents you from using organization folders, then use multibranch Pipelines.
Organization folders are preferred over multibranch Pipelines because they will automatically create and delete multibranch projects when repositories are created or deleted.

.GitHub multibranch Pipelines
video::aDmeeVDrp0o[youtube,width=800,height=420]

.GitLab group folders
video::y4XGFluzPHY[youtube,width=800,height=420]

.Bitbucket project folders
video::LNfthmZuRDI[youtube,width=800,height=420]

Refer to the link:/doc/book/pipeline/pipeline-as-code/#multibranch-pipeline-projects[multibranch Pipelines] documentation for more details.

=== Use Pipeline

If something prevents you from using organization folders and multibranch Pipelines, use Pipeline jobs.
Organization folders and multibranch Pipelines are preferred over Pipeline jobs because they will automatically create and delete multibranch projects when repositories are created or deleted.

Refer to the link:/doc/book/pipeline/[Pipeline] documentation for more details.

.Differences between Freestyle and Pipeline in Jenkins
video::IOUm1lw7F58[youtube,width=800,height=420]

== Don't use the Maven job type

Jenkins has provided the plugin:maven-plugin[Maven integration plugin] for many years.
Jobs created with the Maven integration plugin are created with the "Maven project" selection from the Jenkins "New item" menu.
The Maven job type provides a higher level of integration with maven builds, but creates unnecessary complications due to that higher level of integration.

Use organization folders, multibranch Pipeline, or Pipeline jobs instead of the Maven job type.

The Jenkins project uses organization folders to build link:https://ci.jenkins.io/job/Core/[Jenkins core] and link:https://ci.jenkins.io/job/Plugins/[Jenkins plugins] on ci.jenkins.io.
A Jenkins Pipeline builds Maven projects easily and provides much better control for Maven users.

Refer to the link:https://plugins.jenkins.io/maven-plugin/#plugin-content-risks[Maven plugin documentation] for more details.

== Report build results

Charts and graphs show trends and patterns that can highlight project status and progress.
Automated test results for unit tests, integration tests, and end-to-end tests can highlight brittleness or instability.
Coverage reports can illustrate areas where automated tests are not executing.
Compiler warning messages can be the first indication of a problem.
Static analysis tools can report risky code or code that may have security risks.
Performance test results can identify delays or problem areas.

The plugin:warnings-ng[Warnings Next Generation] plugin provides convenient access to many reports, including:

* Compiler warnnings and errors (like gcc, clang, javac, or  golang)
* Static analysis warnings and errors (spotbugs, checkstyle, pmd, lint, cpd, or Simian)
* Code coverage reports

.How to use the Warnings Next Generation plugin
video::tj3xYFA6Q2o[youtube,width=800,height=420]

=== Show failures to the right people

Configure the notifications from failing and unstable jobs so the notifications reach the right people without distracting others.
Many Jenkins users prefer to only be notified when a failure is likely their fault.
They correctly assume that if they did not cause the failure, they are not the best person to investigate the failure.

Refine your notification system so that new test failures first notify the most recent committers, since they are the most likely cause of the issue.

.Sending Slack notifications
video::EDVZli8GdUM[youtube,width=800,height=420]

== Manage your jobs

Jenkins jobs

=== Build on agents

Use agents to perform builds instead of running builds on the controller.
It is much safer and more scalable to use agents.

More details are available in the link:/doc/book/security/controller-isolation/[controller isolation] documentation.

=== Use simple project names

Jenkins uses project names for folders related to the project.
Many tools cannot handle spaces, dollar signs, or similar characters in file paths.
Limit yourself to alphanumeric characters [a-zA-Z0-9_-]+ in project names.
Use the *Display Name* feature to make them look nice.
The "Restrict project naming" setting in the system configuration can enforce naming restrictions for all projects.

=== Fingerprint your dependencies

When you have interdependent projects, it often becomes hard to keep track of which version of this is used by which version of that.
Jenkins supports "file fingerprinting" to simplify this.

More information is available on the link:/doc/book/using/fingerprints/[fingerprinting page].

== Manage your controller

The Jenkins controller is a central resource that needs to be managed for best results.
These practices can help your controller provide the best experience for users.

=== Secure the controller

Jenkins installations have security enabled by default.
However, it is possible to disable security.
Do **not** disable security.

Details are in the link:/doc/book/security/securing-jenkins/[securing Jenkins] chapter of the User Handbook.

=== Back up regularly

Even the most reliable of systems will have failures.
Prepare and regularly check the health of your backups.

More details can be found in the link:/doc/book/system-administration/backing-up/[backup documentation].

=== Avoid scheduling overload

Schedule jobs to balance the number of jobs running concurrently.
If you're using timer triggers or are periodically polling, use the `H` syntax in the cron expression to introduce scheduing jitter.
The predefined tokens such as `@hourly` can also be used to distribute job starting times more evenly.

=== Avoid resource collisions

Multiple jobs running at the same time often cause collisions if they set up a service or need exclusive access.
If your builds involve the use of databases or other networked services, you need to ensure that they don't interfere with each other.
The plugin:lockable-resources[lockable resources plugin] provides fine grained resource locking for Jenkins jobs.
If resource locking with the lockable resources plugin is not sufficient, you can prevent builds from running at the same time using the plugin:throttle-concurrent-builds[Throttle Concurrent Builds] plugin.

.How to use lockable resources
video::y_z8mqV8G68[youtube,width=800,height=420]
