---
layout: chapter
---
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

= Using Jenkins

This chapter describes how to work with Jenkins as a Jenkins user who does not
link:/doc/book/managing[administer or manage their Jenkins instance].

The topics in this chapter are applicable to anyone using Jenkins (of all skill
levels) on a day-to-day basis. However, there are separate chapters for using
the main features of Jenkins - link:/doc/book/pipeline[Pipeline] and
link:/doc/book/blueocean[Blue Ocean].

If you want to create and configure a Pipeline project from a `Jenkinsfile` or
using Blue Ocean, refer to the relevant topics within the
link:/doc/book/pipeline[Pipeline] and link:/doc/book/blueocean[Blue Ocean]
chapters, respectively.

Any other "Using Jenkins" topics beyond the scope of Pipeline or Blue Ocean can
be found in this chapter.

If you are not yet familiar with basic Jenkins terminology and features, start
with <<getting-started#,Getting Started with Jenkins>>.

If you are a Jenkins administrator and want to know more about managing Jenkins
nodes and instances, see <<managing#,Managing Jenkins>>.

If you are a system administrator and want learn how to back-up, restore,
maintain as Jenkins servers and nodes, see <<system-administration#,Jenkins
System Administration>>.

[WARNING]
====
*To Contributors*:
This chapter functions as a continuation of "<<getting-started#,Getting Started with Jenkins>>",
but the format will be slightly different - see the description above.  We need to balance between providing a
feature reference for experienced users with providing a continuing on-ramp for beginners. Sections should
be written and ordered to only assume knowledge from "Getting Started" or from previous sections in this chapter.
====
