---
layout: chapter
---
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

= Using Jenkins

This chapter describes how to work with Jenkins as a Jenkins user who does not
link:administer or manage their Jenkins instance.
It will cover topics applicable to anyone using Jenkins on a day-to-day basis.
This includes basic topics such as selecting, running, and monitoring existing jobs,
and how to find and review jobs results.
It will continue on to discussing a number of topics around designing and creating projects.

This chapter is intended to be used by Jenkins users of all skill levels.
The sections are structured in a feature-centric way for easier searching and reference by experienced users.
At the same time, to help beginners, we've attempted to order sections in the chapter from simpler to
progressively more complex feature areas.  Also, topics within each section will progress
from basic to advanced, with expert-level considerations and corner-cases at the end or in a
separate section later in the chapter.

If you are not yet familiar with basic Jenkins terminology and features, start with
<<getting-started#,Getting Started with Jenkins>>.

If you are a Jenkins administrator and want to know more about managing Jenkins nodes and instances, see
<<managing#,Managing Jenkins>>.

If you are a system administrator and want learn how to back-up, restore, maintain as Jenkins servers and nodes, see
<<system-administration#,Jenkins System Administration>>.

[WARNING]
====
*To Contributors*:
This chapter functions as a continuation of "<<getting-started#,Getting Started with Jenkins>>",
but the format will be slightly different - see the description above.  We need to balance between providing a
feature reference for experienced users with providing a continuing on-ramp for beginners. Sections should
be written and ordered to only assume knowledge from "Getting Started" or from previous sections in this chapter.
====
