---
layout: chapter
---
ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]


= Using Jenkins

This chapter contains topics for typical Jenkins users (of all skill levels)
about Jenkins usage which is outside the scope of the core Jenkins features:
Pipeline and Blue Ocean.

If you want to create and configure a Pipeline project through a `Jenkinsfile`
or through Blue Ocean, or you wish to find out more about these core Jenkins
features, refer to the relevant topics within the respective
link:../pipeline[Pipeline] and link:../blueocean[Blue Ocean] chapters.

If you are a Jenkins administrator and want to know more about managing Jenkins
nodes and instances, see link:../managing[Managing Jenkins].

If you are a system administrator and want to learn how to back-up, restore,
maintain as Jenkins servers and nodes, see
link:../system-administration[Jenkins System Administration].

If you are a Jenkins user looking for some troubleshooting tips, 
see link:../troubleshooting[Troubleshooting Jenkins]

For an overview of content in the Jenkins User Handbook, see
link:../getting-started[User Handbook Overview].
