---
layout: section
title: Long running agent process
---

= Long running agent process

To reliably kill processes spawned by a job during a build, Jenkins
contains a bit of native code to manage processes, including listing them and stopping them.
This is tested on several platforms and architectures, but if you find a show-stopper problem because of this, you can disable this feature by setting a Java property named "hudson.util.ProcessTree.disable" to the value "true".

This can be done as a parameter to the "java" binary when starting Jenkins:

[source,groovy]
----
 java -Dhudson.util.ProcessTree.disable=true -jar jenkins.war
----

Depending on how you run your container, this can be different. In the distributed build environment, this system property needs to be set on agent JVMs.

[[ProcessTreeKiller-Howitworks]]
== How it works

The ProcessTreeKiller takes advantage of the fact that by default a new process gets a copy of the environment variables of its
spawning/creating process.

It sets a specific environment variable in the process executing the
build job. Later, when the user requests to stop the build job's process it gets a list of all processes running on the computer and their environment variables and looks for the environment variable that it initially set for the build job's process.

Every job with that environment variable in its environment is then
terminated.

[[ProcessTreeKiller-Ifyourbuildwantstoleaveadaemonrunningbehind...]]
== If your build wants to leave a daemon running behind...

A convenient way to achieve that is to change the environment variable `BUILD_ID` which Jenkins's ProcessTreeKiller is looking for. This will cause Jenkins to assume that your daemon is not spawned by the Jenkins build. For example:

[source,groovy]
----
BUILD_ID=dontKillMe /usr/apache/bin/httpd
----

In case of Jenkins Pipeline use `+JENKINS_NODE_COOKIE+` instead of `+BUILD_ID+`.
Parallel stages of the Jenkins Pipeline may run on the same agent and will use the same `+BUILD_ID+` within a specific Pipeline run.
If `+BUILD_ID+` is set instead of `+JENKINS_NODE_COOKIE+`, then parallel Pipeline stages running on the same agent may stop processes from other stages of the same build.
Use `+JENKINS_NODE_COOKIE+` instead of `+BUILD_ID+` so that processes in parallel Pipeline stages are not unexpectedly stopped by the completion of other stages on that agent.
