---
layout: section
title: Working with projects
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
endif::[]

Jenkins uses projects (also known as "jobs") to perform its work.
Projects are defined and run by Jenkins users.
Jenkins offers several different types of projects, including:

* link:/doc/book/pipeline/[Pipeline]
* link:/doc/book/pipeline/multibranch/[Multibranch Pipeline]
* link:/doc/book/pipeline/multibranch/#organization-folders[Organization folders]
* Freestyle
* plugin:matrix-project[Multi-configuration (matrix)]
* plugin:maven-plugin[Maven]
* plugin:external-monitor-job[External job]

Darin Pope provides a summary of the differences between Pipeline projects and freestyle projects in this video.

.Comparing Pipeline and freestyle projects
video::IOUm1lw7F58[youtube,width=800,height=420]

== Copying projects

Copy an existing project by clicking the "New Item" link on the side panel.
Enter the name of the destination project in the  "Item name" field.
Insert the name of the source project into the "Copy from" field.
The existing project will be copied to a new project with the name that was entered in the "Item name" field.

.Copy a project
video::MNzNPCJJqaI[youtube,width=800,height=420]

== Renaming projects

Rename an existing project by clicking the "Rename" action on the project page.
When a job is renamed, other jobs that refer to the job by name must be updated to match the new name.

.Rename a project
video::zO3xnCwbv_c[youtube,width=800,height=420]

== Moving projects

Move an existing project to another folder by clicking the "Move" action on the project page.
When a job is moved, other jobs that refer to the job by name must be updated to match the new name.

.Move a project
video::Mof_YRGZLd8[youtube,width=800,height=420]
