---
layout: subsection
---

ifdef::backend-html5[]
ifndef::env-github[:imagesdir: ../../../resources/managing]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]

= Reverse proxy - Nginx

In situations where you have existing web sites on your server, you may
find it useful to run Jenkins (or the servlet container that Jenkins
runs in) behind https://nginx.org/[Nginx], so that you can bind Jenkins
to the part of a bigger website that you may have.
This section discusses some of the approaches for doing this.

When a request arrives for certain URLs, Nginx becomes a proxy and forwards that request to Jenkins, then it forwards the response back to the client.

=== HTTP Reverse Proxy with NGINX

This 9 minute video tutorial from Darin Pope configures Nginx as a reverse proxy.

.Configuring Nginx as a reverse proxy
video::yixMeJGtLFk[youtube, width=640, height=360]

The Nginx configuration fragment below provides an example Nginx reverse proxy configuration.
It assumes the Jenkins controller and the Nginx reverse proxy are running on the same computer.

[source]
----
upstream jenkins {
  keepalive 32; # keepalive connections
  server 127.0.0.1:8080; # jenkins ip and port
}

# Required for Jenkins websocket agents
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  listen          80;       # Listen on port 80 for IPv4 requests

  server_name     jenkins.example.com;  # replace 'jenkins.example.com' with your server domain name

  # this is the jenkins web root directory
  # (mentioned in the output of "systemctl cat jenkins")
  root            /var/run/jenkins/war/;

  access_log      /var/log/nginx/jenkins.access.log;
  error_log       /var/log/nginx/jenkins.error.log;
  
  # pass through headers from Jenkins that Nginx considers invalid
  ignore_invalid_headers off;

  location ~ "^\/static\/[0-9a-fA-F]{8}\/(.*)$" {
    # rewrite all static files into requests to the root
    # E.g /static/12345678/css/something.css will become /css/something.css
    rewrite "^\/static\/[0-9a-fA-F]{8}\/(.*)" /$1 last;
  }

  location /userContent {
    # have nginx handle all the static requests to userContent folder
    # note : This is the $JENKINS_HOME dir
    root /var/lib/jenkins/;
    if (!-f $request_filename){
      # this file does not exist, might be a directory or a /**view** url
      rewrite (.*) /$1 last;
      break;
    }
    sendfile on;
  }

  location / {
      sendfile off;
      proxy_pass         http://jenkins;
      proxy_redirect     default;
      proxy_http_version 1.1;

      # Required for Jenkins websocket agents
      proxy_set_header   Connection        $connection_upgrade;
      proxy_set_header   Upgrade           $http_upgrade;

      proxy_set_header   Host              $http_host;
      proxy_set_header   X-Real-IP         $remote_addr;
      proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header   X-Forwarded-Proto $scheme;
      proxy_max_temp_file_size 0;

      #this is the maximum upload size
      client_max_body_size       10m;
      client_body_buffer_size    128k;

      proxy_connect_timeout      90;
      proxy_send_timeout         90;
      proxy_read_timeout         90;
      proxy_request_buffering    off; # Required for HTTP CLI commands
  }

}
----

This assumes that you run Jenkins on port 8080.
Remember to create the folder /var/log/nginx/jenkins.

Make sure you do not end the `proxy_pass` value with a slash, as it will cause problems like those described in link:https://community.jenkins.io/t/reverse-proxy-test-does-not-handle-url-correctly/1294/16[this discussion].

=== UDS Reverse Proxy with NGINX

This guide sets up Jenkins with NGINX as a reverse proxy using a UNIX socket and HTTP.

To avoid repetitive use of `sudo` in the commands below, switch to a root shell first by running:

[source,bash]
----
sudo -i
----

[source,bash]
----
# Edit Jenkins systemd service
systemctl edit jenkins

# Override Jenkins service to use UNIX socket instead of HTTP port
[Service]
ExecStart=
ExecStart=/usr/bin/jenkins --pluginroot=/var/cache/jenkins/plugins --httpPort=-1 --httpUnixDomainPath=/var/run/jenkins/jenkins.socket

# Ensure Jenkins owns the socket and restrict access
chown jenkins:jenkins /var/run/jenkins/jenkins.socket
chmod 700 /var/run/jenkins/jenkins.socket

# Update package list and install NGINX (Debian-based systems)
apt update
apt install nginx

# Create NGINX site config for Jenkins
nano /etc/nginx/sites-available/jenkins

# NGINX server block: proxies to Jenkins UNIX socket
server {
    listen 80;
    server_name localhost;

    access_log /var/log/nginx/jenkins_access.log;
    error_log /var/log/nginx/jenkins_error.log;

    location / {
        proxy_pass http://unix:/var/run/jenkins/jenkins.socket;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Jenkins-specific settings
        proxy_max_temp_file_size 0;
        client_max_body_size 10m;
        client_body_buffer_size 128k;
        
        proxy_connect_timeout 90;
        proxy_send_timeout 90;
        proxy_read_timeout 90;
        
        # Support Jenkins WebSocket agents
        proxy_http_version 1.1;
        proxy_request_buffering off;
        proxy_buffering off;
        
        # Enable HTTP CLI commands
        proxy_set_header Connection "";
    }
}

# Link config to sites-enabled and restart NGINX
ln -s /etc/nginx/sites-available/jenkins /etc/nginx/sites-enabled/
systemctl restart nginx

# Allow HTTP/HTTPS traffic and verify firewall status
ufw allow http
ufw allow https
ufw reload
ufw status

# Edit NGINX config to run as jenkins user
nano /etc/nginx/nginx.conf
# Add or modify this line at the top
user jenkins jenkins;

# Restart NGINX to apply changes
systemctl restart nginx

# Remove default NGINX site
unlink /etc/nginx/sites-enabled/default
----

Once you have finished your configuration, access `http://localhost/` in a browser.

include::doc/book/system-administration/reverse-proxy-configuration-with-jenkins/_context_path.adoc[]

If you are having problems with some paths (eg folders) with *Blue
Ocean*, you may need to add the following snippet to your proxy
configuration:

[source]
----
if ($request_uri ~* "/blue(/.*)") {
    proxy_pass http://YOUR_SERVER_IP:YOUR_JENKINS_PORT/blue$1;
    break;
}
----

== Permissions

To give Nginx permission to read Jenkins web root folder, add the `nginx` user to
the Jenkins group:

[source,sh]
----
usermod -aG jenkins nginx
----

If the last command failed because the `nginx` user is not defined in the system,
then you can try adding the `www-data` user to the Jenkins group:

[source,sh]
----
usermod -aG jenkins www-data
----

If you are experiencing timeouts when attempting to run long CLI
commands through a proxy in Jenkins, you can increase the
`+proxy_read_timeout+` setting as necessary.
Older versions of Jenkins may not respect the `+proxy_read_timeout+` setting.

If you are experiencing the following error when attempting to run long
CLI commands in Jenkins and Jenkins is running behind Nginx, it
is probably due to Nginx timing out the CLI connection.
You can increase the `+proxy_read_timeout+` setting as necessary so the command will
complete successfully.

[source]
----
WARNING: null
hudson.cli.DiagnosedStreamCorruptionException
Read back: 0x00 0x00 0x00 0x1e 0x07
           'Started reverse-proxy-test #68'
           0x00 0x00 0x00 0x01 0x07 0x0a
Read ahead:
Diagnosis problem:
    java.io.IOException: Premature EOF
        at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
        ...
    at hudson.cli.FlightRecorderInputStream.analyzeCrash(FlightRecorderInputStream.java:82)
    at hudson.cli.PlainCLIProtocol$EitherSide$Reader.run(PlainCLIProtocol.java:153)
Caused by: java.io.IOException: Premature EOF
    at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
    ...
    at java.io.DataInputStream.readInt(DataInputStream.java:387)
    at hudson.cli.PlainCLIProtocol$EitherSide$Reader.run(PlainCLIProtocol.java:111)
----
