---
:layout: post
:title: 'Jenkins 2.0 Proposal: Split Groovy out of "core"'
:nodeid: 637
:created: 1445969896
:tags:
  - general
  - core
  - feedback
:author: rtyler
---
As I mentioned in link:/content/jenkins-20-proposal-introduce-policy-api-deprecation[yesterday's post], there's been a lot of discussion recently about what "https://wiki.jenkins.io/display/JENKINS/Jenkins+2.0[Jenkins
2.0]" means. In a recent "Office Hours" session, https://github.com/kohsuke[Kohsuke Kawaguchi] presented his
vision for *Jenkins 2.0* in a https://www.youtube.com/watch?v=2eVyc_n8i1c[office
hours] session, the slides for
which can be found https://docs.google.com/presentation/d/12ikbbQoMvus_l_q23BxXhYXnW9S5zsVNwIKZ9N8udg4[in this Google
Presentation].
Roughly paraphrasing Kohsuke's vision, 2.0 is primarily about making things
better for the thousands of users out there.

This week, we'll be reviewing some _key areas_ of the "Jenkins 2.0" proposal.
Asking you, the user community, to provide feedback on these proposals, going
from Jenkins internals to user interface.

Thus far we've covered:

* link:/content/jenkins-20-proposal-introduce-policy-api-deprecation[Introducing a policy for API deprecation]

Today's post involves a proposal originally from community member https://github.com/jglick[Jesse Glick] who has proposed in *https://issue-redirect.jenkins.io/issue/29068[JENKINS-29068]* that http://groovy-lang.org[Groovy] be split out from the "core" Jenkins distribution. The linked issue expands on what the problem is here:

____
Currently Jenkins embeds a distribution of Groovy into "core" for a variety of scripting and management tasks. This version of Groovy is locked into core in such a way that users cannot upgrade Groovy independently from Jenkins itself. If the Jenkins-bundled version were upgraded to a different major version, it may break users' custom scripts as well as plugins that use Groovy due to API changes.
____

The proposal is relatively straight-forward and affects the many different users and use-cases for the embedded Groovy scripting support in Jenkins:

____
For ease of maintenance and modularity it would be useful to split Jenkins' use of Groovy into a library plugin; different clients could request 1.x and 2.x simultaneously by using different versions of the library, etc.

Stuff in core using Groovy that would need to either be put in this library (if infrastructure for other features) or put in another plugin depending on it (if first-class features themselves):
____

I selected this proposal to feature on this blog, despite its rather technical underpinnings, it will affect core developers, plugin developers, power and casual users alike. I encourage everybody to read through the proposal and its potential impact https://issue-redirect.jenkins.io/issue/29068[on the issue tracker].

=== Providing Feedback

We're asking you to read the proposal in
https://issue-redirect.jenkins.io/issue/29068[JENKINS-29068] and provide
feedback if you have it.

If you have ever logged in to the https://issues.jenkins.io[issue
tracker] or the
https://wiki.jenkins.io/[wiki], you have a "Jenkins user account" which
means you'll be able to log into the issue tracker and vote for, or comment on
the issue linked above.

(_note_: if you have forgotten your password, use https://jenkins-ci.org/account/[the account
app] to reset it.)

We're going to review feedback, make any necessary adjustments and either
approve or reject the proposal two weeks from today.

Stay tuned for the rest of the week as we keep with our theme of going "from the inside out" and help us make Jenkins 2.0 great!
