---
:layout: post
:title: 'Jenkins 2.0 Proposal: Improved "Out of the box" user experience'
:nodeid: 641
:created: 1446226604
:tags:
  - general
  - core
  - feedback
:author: rtyler
---
This week we have featured a number of proposals for what we would like to see in "https://wiki.jenkins.io/display/JENKINS/Jenkins+2.0[Jenkins
2.0]", the vision of which is to make Jenkins users more efficient, productive and happy. We started with some more internally facing changes and have slowly progressed from the "inside-out" to today's topic: improving the out of the box user experience. That is to say, the experience that a brand-new Jenkins user has when getting started with the server.

Just to recap, so far we've reviewed:

* link:/content/jenkins-20-proposal-introduce-policy-api-deprecation[Introducing a policy for API deprecation]
* link:/content/jenkins-20-proposal-split-groovy-out-core[Splitting Groovy out of 'core']
* link:/content/jenkins-20-proposal-pipeline-code-front-and-center[Pipeline as code front and center]
* link:/content/jenkins-20-proposal-ux-improvements-part-one[User experience improvements (part one)]

The subject of today's proposal is captured in *https://issue-redirect.jenkins.io/issue/31157[JENKINS-31157]*, which, like yesterday's link:/content/jenkins-20-proposal-ux-improvements-part-one[proposal], contains a few issues linked from it with more details.

At a high level, the problem aiming to be solved is:

____
When a new user installs Jenkins, they are greeted with the main, empty, dashboard which suggests that they "create jobs." This makes no mention of plugins or the configuration options that are relevant to helping the user make Jenkins match their needs.
____

In past and current versions of Jenkins, if you know what you're looking for it's relatively easy to move around the interface. If you've never used Jenkins before, it can be very challenging to find your way around or even know _what it is possible_ to do with Jenkins.

The proposed changes aim to address this initial confusion:

____
Instead of changing the post-install defaults, which may not properly represent the user's needs, the first-time user experience should help guide the user through configuration and plugin installation quickly so they can use Jenkins for their needs. Effectively it should be as easy as possible for a user to arrive at a good configuration for their usage.
____

Jenkins contributor https://github.com/tfennelly[Tom Fennelly], who has led this discussion on the mailing lists in the past, has posted a good prototype screencast of what some of this might entail:+++<center>++++++<iframe width="480" height="360" src="https://www.youtube-nocookie.com/embed/kzRR8XR8hu4?rel=0" frameborder="0" allowfullscreen="">++++++</iframe>++++++</center>+++

=== Providing Feedback

We're asking you to read the issues linked from https://issue-redirect.jenkins.io/issue/31157[JENKINS-31157] and comment and vote on those issues accordingly.

If you have ever logged in to the https://issues.jenkins.io[issue
tracker] or the
https://wiki.jenkins.io/[wiki], you have a "Jenkins user account" which
means you'll be able to log into the issue tracker and vote for, or comment on
the issue linked above.

(_note_: if you have forgotten your password, use https://jenkins-ci.org/account/[the account
app] to reset it.)

We're going to review feedback, make any necessary adjustments and either
approve or reject the proposal two weeks from today.

This concludes this week's blog series highlighting some of the Jenkins 2.0 proposals we felt were important to discuss with the broader Jenkins user audience. Many of these, and other minor proposals, can be found on the https://wiki.jenkins.io/display/JENKINS/Jenkins+2.0[Jenkins 2.0 wiki page].
