---
:layout: post
:title: "Jenkins 2.0 Proposal: Introduce a policy for API deprecation"
:nodeid: 636
:created: 1445833065
:tags:
  - general
  - core
  - feedback
:author: rtyler
---
Over the past few weeks there has been a vibrant discussion happening on the
https://groups.google.com/group/jenkinsci-dev/topics[jenkinsci-dev@] mailing
list as to what "https://wiki.jenkins.io/display/JENKINS/Jenkins+2.0[Jenkins 2.0]" means.  While
Jenkins does not currently adhere to https://semver.org/[semantic versioning],
the change of a major version number does indicate a major milestone for the community.

Project founder, https://github.com/kohsuke[Kohsuke Kawaguchi] presented his
vision for *Jenkins 2.0* in a https://www.youtube.com/watch?v=2eVyc_n8i1c[office
hours] session, the slides for
which can be found https://docs.google.com/presentation/d/12ikbbQoMvus_l_q23BxXhYXnW9S5zsVNwIKZ9N8udg4[in this Google
Presentation].
Roughly paraphrasing Kohsuke's vision, 2.0 is primarily about making things
better for the thousands of users out there.

This week, we'll be reviewing some _key areas_ of the "Jenkins 2.0" proposal.
Asking you, the user community, to provide feedback on these proposals, going
from Jenkins internals to user interface.

Today's post involves a proposal to introduce a policy for *API
deprecation* from community members https://github.com/olivergondza[Oliver
Gondža] and https://github.com/daniel-beck[Daniel
Beck]. Extensibility is the heart of Jenkins, but over the past ten
years we've not had a proper API deprecation policy other than "try not to
break plugins, ever."

Daniel, expanding more on the problem wrote:

____
We have no backward compatibility policy besides "compatibility matters".
With 1000+ plugins and basically the entire core being available to
plugins, a lot of difficult or impossible to remove cruft has accumulated over
the last ten years. This limits both what can be changed in core, and makes
documentation difficult to use for plugin developers.
____

The two have put together a detailed proposal under
*https://issue-redirect.jenkins.io/issue/31035[JENKINS-31035]* which
suggests we:

____
limit the availability in APIs (classes, methods, fields, ...) provided by core
to a number of releases. Depending on the feature, this can range from a few
months, to a few years (e.g. two years being about 100 releases of Jenkins and
eight LTS baselines).

&#91;...&#93;
____

I highly encourage you to read the entire proposal https://issue-redirect.jenkins.io/issue/31035[on the issue
tracker], where we are
trying to collect feedback/history.

=== Providing Feedback

We're asking you to read the proposal in
https://issue-redirect.jenkins.io/issue/31035[JENKINS-31035] and provide
feedback if you have it.

If you have ever logged in to the https://issues.jenkins.io[issue
tracker] or the
https://wiki.jenkins.io/[wiki], you have a "Jenkins user account" which
means you'll be able to log into the issue tracker and vote for, or comment on
the issue linked above.

(_note_: if you have forgotten your password, use https://jenkins-ci.org/account/[the account
app] to reset it.)

We're going to review feedback, make any necessary adjustments and either
approve or reject the proposal two weeks from today.

Stay tuned, and help make Jenkins 2.0 great!
