---
:layout: post
:title: "Jenkins 2.0 Proposal: UX Improvements (Part One)"
:nodeid: 639
:created: 1446143062
:tags:
  - general
  - core
  - feedback
:author: rtyler
---
We have been featuring a few proposals this week for what "https://wiki.jenkins.io/display/JENKINS/Jenkins+2.0[Jenkins
2.0]" is going to include. Today we'll be diving into the most noticeable changes being proposed for Jenkins 2.0: the User Experience (UX) improvements

Thus far in this blog series we have reviewed proposals covering:

* link:/content/jenkins-20-proposal-introduce-policy-api-deprecation[Introducing a policy for API deprecation]
* link:/content/jenkins-20-proposal-split-groovy-out-core[Splitting Groovy out of 'core']
* link:/content/jenkins-20-proposal-pipeline-code-front-and-center[Pipeline as code front and center]

The UX improvements being proposed aren't necessarily as uniform as the proposals from earlier in the week but represent a large amount of prototype and exploratory work done by folks like https://github.com/tfennelly[Tom Fennelly], https://github.com/gusreiber[Gus Reiber] and a few others. Those following the dev list may have already seen some of these proposals in some of the "mega threads" that we have had discussing potential UI/UX improvements previously.

The improvements proposed for 2.0 can be found under *https://issue-redirect.jenkins.io/issue/31156[JENKINS-31156]*. The most promising proposal under this issue is to update the https://issue-redirect.jenkins.io/issue/9802[plugin manager experience].+++<center>++++++<iframe width="480" height="360" src="https://www.youtube-nocookie.com/embed/9vPUMe3lzfo?rel=0" frameborder="0" allowfullscreen="">++++++</iframe>+++ +
+++<iframe width="480" height="360" src="https://www.youtube-nocookie.com/embed/jf5s0sqIYBY?rel=0" frameborder="0" allowfullscreen="">++++++</iframe>++++++</center>+++

Another very important proposal for 2.0 worth mentioning is the proposal to https://issue-redirect.jenkins.io/issue/21092[update UI work well on mobile devices].

=== Providing Feedback

We're asking you to read the issues linked from https://issue-redirect.jenkins.io/issue/31156[JENKINS-31156] and comment and vote on those issues accordingly.

If you have ever logged in to the https://issues.jenkins.io[issue
tracker] or the
https://wiki.jenkins.io/[wiki], you have a "Jenkins user account" which
means you'll be able to log into the issue tracker and vote for, or comment on
the issue linked above.

(_note_: if you have forgotten your password, use https://jenkins-ci.org/account/[the account
app] to reset it.)

We're going to review feedback, make any necessary adjustments and either
approve or reject the proposal two weeks from today.

Stay tuned for tomorrow's post covering the remainder of the proposed user experience changes!
