---
layout: developer
title: Create a Plugin
---

- link:../prepare[Step 1: Preparing for Plugin Development]
- link:../create[*Step 2: Create a Plugin*]
- link:../run[Step 2: Build and Run the Plugin]
- link:../extend[Step 3: Extend the Plugin]

After link:../prepare[preparing your environment], the next step is to create a new plugin.

NOTE: If your intention is to publish your plugin on the Jenkins update site, now is a good time to look for plugins that already do something similar.
See link:https://wiki.jenkins-ci.org/display/JENKINS/Before+starting+a+new+plugin[this wiki page] for more information.

== Create the Project Layout with Sample Plugin

Open a command prompt and run the following command:

[source]
mvn -U hpi:create

It will download dependencies needed to create the project, and then ask for `groupId` (similar to Java packages) and `artifactId` (the name of your plugin).

// http://asciidoctor.org/docs/user-manual/#applying-substitutions
[source,subs="verbatim,quotes"]
----
Enter the groupId of your plugin [org.jenkins-ci.plugins]: // <1>
Enter the artifactId of your plugin (normally without \'-plugin' suffix): *demo* // <2>
[INFO] Defaulting package to group ID + artifact ID: org.jenkins-ci.plugins.demo // <3>
[WARNING] Package name contains invalid characters. Replacing it with \'org.jenkinsci.plugins.demo' // <4>
----
<1> You can leave this empty, as shown here, and it will use the default of `org.jenkins-ci.plugins`.
<2> This is mandatory and uniquely identifies your plugin in Jenkins.
    This plugin tutorial uses the name `demo` (user input highlighted in bold).
    If you want to publish your plugin, make sure the name is not already taken, and that the name you choose is future-proof: The `artifactId` cannot be changed after you've published your first release.
<3> This is the default Java package for classes in your plugin.
    Class names (including package) also need to be unique, so using package names that identify the plugin is strongly recommended.
<4> This warning is expected, and due to the default `groupId`.
    It is nothing to worry about.

This creates a directory with the same name as the plugin's `artifactId` (`demo` in this case), and add the basic structure for a working plugin. Let’s make sure we can build the plugin:

[source]
----
$ cd demo // <1>
$ mvn verify
----
<1> Maven has created the project structure in a directory with the same name as you chose for your plugin.

Maven will download several more dependencies, and then go through the configured build lifecycle, including static analysis (FindBugs) and tests, until it shows something like this:

[source]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:11 min
[INFO] Finished at: 2017-03-02T14:14:34+01:00
[INFO] Final Memory: 73M/872M
[INFO] ------------------------------------------------------------------------

Not the output you're seeing? See the <<Troubleshooting>> section below.

Let's link:../run[run the plugin] and see what it does.

== Troubleshooting

NOTE: Anything not working for you? Ask for help in link:/chat[chat] or link:/mailing-lists[on the jenkinsci-dev mailing list].
