---
layout: developer
title: Preparing for Plugin Development
references:
- url: https://adoptium.net/
  title: Eclipse Temurin Java
- url: https://maven.apache.org # TODO redundant?
  title: Apache Maven website
---

ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:notitle:
endif::[]

- link:../prepare[*Step 1: Preparing for Plugin Development*]
- link:../create[Step 2: Create a Plugin]
- link:../run[Step 3: Build and Run the Plugin]
- link:../extend[Step 4: Extend the Plugin]

== Download and install a JDK

// TIMEBASED
Jenkins is based on Java, so to build Jenkins plugins you need to install a Java Development Kit (JDK).
Java 17 is the version we recommend to users, so that's what we're using in this tutorial.

You can download and install Java 17 from the link:https://adoptium.net/[Eclipse Temurin website].

NOTE: Many Linux distributions provide packages for Java for an easier install and upgrade experience.
Consult your distribution's documentation for details.
To check if you have Java already installed, run `java -version` on a command prompt.

== Download and install Maven

Jenkins plugins mostly use Maven to build, so that's what we're going to use in this tutorial.

Download Maven from link:https://maven.apache.org/download.cgi[Apache Maven website]. 
Make sure to download one of the binary archives (with `bin` in their name). 


// TODO: Include subsections for every OS
NOTE: Many Linux distributions provide packages for Maven for an easier install and upgrade experience.
Consult your distribution's documentation for details.
On macOS, the link:https://brew.sh/[Homebrew] package manager offers Maven packages.
Make sure a recent version of Maven 3, ideally 3.8.3 or newer, is provided if you decide to go this route.
// TIMEBASED

Next you will need to extract Maven, and take note of its location. When you extract the Maven files, make sure you extract them directly into the target directory (e.g. extract straight into C:\Program Files (x86)\Maven ) - do not extract the files to a different location then copy the files.

Then, add the full path of the `bin/` subdirectory extracted (for example, `~/Applications/apache-maven/bin` or `C:\Program files\Maven\bin`) to the `PATH` variable in your OS.
This will let you invoke Maven using `mvn`.

The rest of the tutorial assumes that Maven is on your `PATH` environment variable.

Add the following to your `~/.m2/settings.xml` (Windows users will find them in `%USERPROFILE%\.m2\settings.xml`):

[source,xml]
----
<settings>
  <profiles>
    <profile>
      <id>jenkins</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
</settings>
----

To verify that Maven is installed, run the following command:

[source,bash]
----
mvn -version
----
This command prints some diagnostic output, including the versions of Java and Maven, and which Java installation was found by Maven.
It should indicate a _17_ version of Java, and list the path to where Java is located.
If you don't see this information, see <<Troubleshooting>>.

== Setting up a productive environment with your IDE
=== IntelliJ IDEA

IntelliJ users just need to open the project and all should work out of the box.

You are advised to use the link:https://plugins.jetbrains.com/plugin/1885-jenkins-development-support/[IntelliJ IDEA plugin for Jenkins Development], features it provides can be found in its link:https://github.com/jenkinsci/idea-stapler-plugin#stapler[documentation].

You can create a new plugin using one of the Jenkins plugin link:https://github.com/jenkinsci/archetypes/[archetypes]. 
Create a new Maven project using **Create from archetype** and **Add an Archetype**.
Select the GroupId and ArtifactId as above, and choose RELEASE as version.
On the next screen, select io.jenkins.plugins as groupID and choose an artifactId (Project name) and Version to your liking.
This will automatically create a maven project based on the specified artifact (for example, `empty-plugin`).

=== NetBeans

NetBeans users can use the IDE's Maven support to open the project directly.

As you navigate through the code, you can tell NetBeans to attach source code JAR files by clicking the "Attach" button that appears in the top of the main content window. This allows you to read the Jenkins core source code as you develop plugins. (Or just select Download Sources on the Dependencies node.)

You are advised to use the link:https://github.com/stapler/netbeans-stapler-plugin[NetBeans plugin for Jenkins/Stapler development]. This offers many Jenkins-specific features. Most visibly, create a new plugin using New Project » Maven » Jenkins Plugin, and use Run project to test it.

=== Eclipse

// Any eclipse users around who know more?

Open the project as an existing Maven Project.


== Next step

link:../create[Create and build your first Jenkins plugin].

== Troubleshooting

NOTE: Anything not working for you? Ask for help on our community forum link:https://community.jenkins.io[community.jenkins.io] or link:/mailing-lists[on the jenkinsci-dev mailing list].
