---
layout: developer
title: Preparing for Plugin Development
references:
- url: http://www.oracle.com/technetwork/java/javase/downloads/index.html # TODO redundant?
  title: Oracle Java downloads site
- url: https://maven.apache.org # TODO redundant?
  title: Apache Maven website
---

- link:../prepare[*Step 1: Preparing for Plugin Development*]
- link:../create[Step 2: Create a Plugin]
- link:../run[Step 3: Build and Run the Plugin]
- link:../extend[Step 4: Extend the Plugin]

== Download and install a JDK

// TIMEBASED
Jenkins is based on Java, and to build Jenkins plugins, you need to install a Java Development Kit, or JDK.
Recent Jenkins releases require JDK 8 to run, so that's what we're using here.

Download JDK 8 for free from link:http://www.oracle.com/technetwork/java/javase/downloads/[the Oracle website] and install it.

NOTE: Many Linux distributions provide packages for Oracle JDK or OpenJDK JDK for an easier install and upgrade experience.
Consult your distribution's documentation for details.
It may even be installed already.
To find out, type `javac -version` on a command prompt.

== Download and install Maven

Jenkins plugins overwhelmingly use Maven to build, so that's what we're going to use in this tutorial.

Download Maven from link:https://maven.apache.org[its website].
Make sure to download one of the files with `bin` in their name.
`src` indicates a source distribution.

// TODO: Include subsections for every OS
NOTE: Many Linux distributions provide packages for Maven for an easier install and upgrade experience.
Consult your distribution's documentation for details.
On macOS, the link:https://brew.sh/[Homebrew] package manager offers Maven packages.
Make sure a recent version of Maven 3, ideally 3.3.9 or newer, is provided if you decide to go this route.
// TIMEBASED

Download and extract Maven, and note its location.
You now have the following options:

. Add the `bin/` subdirectory of the extracted directory to your `PATH`.
  This will let you invoke Maven using `mvn`.
  How this works is dependent on your OS and command shell.
. Always use the full path to the `mvn` executable, for example `~/Applications/apache-maven/bin/mvn` or `C:\Program files\Maven\bin\mvn`

The rest of the tutorial assumes that Maven is on your `PATH`, but you can also just type the full path.

Once downloaded and extracted somewhere, let's make sure everything works as expected by typing the following in a command prompt:

NOTE: This is `Terminal.app` on macOS, `cmd.exe` on Windows, and any shell on Linux.

[listing]
mvn -version

This prints some diagnostic output, including the versions of Java and Maven, and which Java installation was found by Maven.
This should indicate a _1.8_ version of Java, and list the path to the JDK.
If either of these is not the case, see <<Troubleshooting>>.

Next step: link:../create[Create and build your first Jenkins plugin].

== Troubleshooting

NOTE: Anything not working for you? Ask for help in link:/chat[IRC] or link:/mailing-lists[on the jenkinsci-dev mailing list].
