---
layout: project
title: "GSoC 2018 Project Ideas"
tags:
- gsoc
- gsoc2018
---

This page aggregates project ideas for Google Summer of Code 2018.
See more information about this project and applications at link:/projects/gsoc/[the project's page].

:toc:

== Project Ideas

Below you can find project ideas proposed by potential mentors.
Other ideas may be proposed by students (e.g. new features in the core, "write a plugin for MY_TOOL_OR_SERVICE", etc.).
Such project applications will be considered though applicants may need to work
with the community and GSoC admins to find potential mentors.

[NOTE]
====
All project ideas below are in the draft state now,
the contents will be extended and polished.
====

=== Jenkins Configuration as Code

link:https://github.com/jenkinsci/configuration-as-code-plugin[Configuration-as-Code] plugin has been designed
as an opinionated way to configure Jenkins based on human-readable declarative configuration files (YAML).
Plugin should be easy to use regardless of previous Jenkins experience or Jenkins model expert knowledge.

This will allow to fully automate Jenkins deployment process and manage Jenkins (one or multiple instances) configuration.

Skills:

* java
* docker (nice to have)

Potential mentors:
link:https://github.com/ewelinawilkosz[Ewelina Wilkosz],
link:https://github.com/hoegertn[Thorsten Höger]

=== Remoting. Message Bus/Queue - powered implementation

Current versions of link:/projects/remoting[Jenkins Remoting] are based on the TCP protocol.
If it fails, the agent connection and the build fails as well.
There are also issues with traffic prioritization and multi-agent communications,
which impact Jenkins stability and scalability.

This project aims an update of Remoting and Jenkins in order to add support of a popular message queue/bus technology (RabbitMQ, ActiveMQ, etc.)
as a fault-tolerant communication layer in Jenkins.

Skills:

* Java
* Networking
* Message queues

Potential mentors: link:https://github.com/oleg-nenashev/[Oleg Nenashev]

=== Cloud Features for External Workspace Manager Plugin

We wish to add Cloud features to the Jenkins External Workspace Manager Plugin.

This would allow Jenkins workspaces to be cloud based or located remotely, rather than being local.
These features include:

* Cloud-based storage support (link:https://groups.google.com/d/msg/jenkinsci-dev/z40kn8IqFb8/YkdgbuScCgAJ[discussion])
* Integration with the core's “Discard old builds” feature
* Improvements to data retention policies (e.g. link:https://issues.jenkins-ci.org/browse/JENKINS-48715[JENKINS-48715])
workspace usage statistics
* Improvements to workspace usage statistics

Skills

* Java
* Cloud based storage

Potential mentors:
link:https://github.com/martinda[Martin d'Anjou],
link:https://github.com/oleg-nenashev/[Oleg Nenashev]

=== Role Strategy Plugin performance and/or user experience

link:https://wiki.jenkins.io/display/JENKINS/Role+Strategy+Plugin[Role Strategy Plugin] is widely used in Jenkins as an authorization engine,
but it has known performance limitations for large-scale setups.
In this project the proposal is to improve the plugin's performance and to create a proper testing framework for Jenkins security plugins.
Web interfaces of this plugin can be also improved.

Skills:

* Java
* Performance testing and profiling tools
* For UX projects - Javascript is a plus

Potential mentors:
link:https://github.com/oleg-nenashev/[Oleg Nenashev],
link:https://github.com/christ66[Steven Christou]


=== Integration plugin(s) for Electronic Design Automation tools

The idea is to create a Jenkins plugin for one of widely used EDA tools.
Both ASIC or FPGA design flow are acceptable, the tool should be proposed by the potential student.
Open-source EDA tools would be preferable (e.g. Yosys, FuseSoC, ArachnePnR, icetools), but we also consider
conditionally-free tools (like FPGA design EDAs).

For example such plugin could report FPGA resource utilization per build as well as the project trend.
Other example: timing report trend.

Integrating UVM reports into Jenkins build and project pages is also an example of such plugin.

Prerequisites:

* Basic knowledge of Jenkins (as a user)
* Basic knowledge of Java programming language
* Hands-on experience with the selected EDA tool.
In the case of FPGA flows it would be useful to have a prototyping board as well.

Potential mentors:
link:https://github.com/martinda[Martin d'Anjou],
link:https://github.com/oleg-nenashev/[Oleg Nenashev]

=== Code Coverage API Plugin

There are a lot of plugins which currently implement code coverage (clover plugin, cobertura plugin, clover php plugin, etc),
however they all are using similar charts and similar content.
Instead of having one plugin for each code coverage result it would be best if we could merge them all into one plugin which will handle code coverage.

Most code coverage results display similar content like:

* File Name
* Lines covered
* Methods covered
* Branches covered
* Red/Green/Yellow statuses
* Coverage over multiple builds

Skills:

* Java
* HTML/CSS (possibly)

Potential mentors:
link:https://github.com/christ66[Steven Christou],
link:https://github.com/Jeff-Symphony[Jeff Knurek]

=== Improvements to the Jenkins Acceptance Test Harness

The link:https://github.com/jenkinsci/acceptance-test-harness[Jenkins Acceptance Test Harness (ATH)] is a great vehicle
to test Jenkinsfiles and custom DSL libraries ahead of deploying them to production servers.
However, it has couple of drawbacks.

* it can be quite slow as it needs to bootstrap an entire Jenkins instance for each test method.
* real production environments typically need to use a very specific plugin list of pre-defined plugins and plugin versions

Improving these two areas would make the ATH more efficient and easy to use for Jenkinsfile and custom DSL library testing.

For example, instead of dynamically creating a Jenkins instance for each test, an instance could be built as a docker image,
loaded as a java link:https://github.com/testcontainers/testcontainers-java[testcontainers], and injected with the DSL to be tested.

Potential mentors:
link:https://github.com/martinda[Martin d'Anjou],
link:https://github.com/christ66[Steven Christou]

== Draft project ideas

In addition to the finalized project ideas, we also have some draft ones in
link:https://docs.google.com/document/d/1q2p_XZEdbkcVDMpEPTtjPS15i2Oq3CQgH_geJjPhofY/edit#[this document].
If you are interested, feel free to comment in the document or to add your own ideas there.

Draft ideas under discussion:

* Pipeline Step Documentation generator improvements
** link:https://github.com/martinda[Martin d'Anjou], link:https://github.com/kwhetstone[Kristin Whetstone]
* Rework the Script Security Administration UX
** link:https://github.com/oleg-nenashev/[Oleg Nenashev]
* link:https://plugins.jenkins.io/summary_report[Summary Report plugin] Pipeline compatibility and other improvements
** link:https://github.com/martinda[Martin d'Anjou]
* Jenkins UI Test Automation
** Mohan Krishna Gundala
* Simple Pull-Request Plugin
** link:https://github.com/martinda[Martin d'Anjou]
