---
layout: project
title: "Proposing new project ideas"
tags:
- gsoc
links:
  gitter: jenkinsci/gsoc-sig
  googlegroup: jenkinsci-gsoc-all-public
  sig: gsoc
---

:toc:

New ideas for GSoC can be proposed by mentors, students and/or anyone in the Jenkins
community with an idea they'd like to see implemented.

== Proposal quick start

If you have an interesting project that meets our requirements, you can kick off
the process by:

. Making a copy of the
  link:https://docs.google.com/document/d/1l5SdcLnlCwWA6qH8FKT9XC714Dl1XJ9lyy1CKDdKKAU[project proposal template]
  and create a new Google Document describing the project proposal. Make sure to set the permissions so
  members of the community can comment on it.
. When the project is ready for consideration, contact the GSoC org admins via the
  link:https://gitter.im/jenkinsci/gsoc-sig[Jenkins GSoC gitter channel] or the
  link:mailto://jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list].

The full proposal process is link:#acceptance-process[documented here].

== Requirements

* GSoC is about code (though it may and likely should include some documentation)
* Projects should be about Jenkins (plugins, core, infrastructure, integrations, test frameworks, etc.)
* Projects should be potentially doable by a student in 3-4 months

You can find more information about requirements and practices in the
link:https://google.github.io/gsocguides/mentor/[GSoC Mentor Guide].

== Examples

Need some hints? Here are examples of project ideas:

* A new plugin for integration with various development tools or services
* link:https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin[Adopting an existing plugin],
extending it by adding new features like link:/doc/book/pipeline/[Jenkins Pipeline]
* Working on major feature requests from the link:https://issues.jenkins-ci.org/secure/Dashboard.jspa[Jenkins bugtracker]
* Creating new demo and reference setups,
powered by various "-as-Code" engines (e.g. Jenkins Pipeline, JobDSL, Docker, link:/projects/gsoc/gsoc2018-project-ideas/#jenkins-configuration-as-code[Configuration-as-Code plugin], etc.)

== Notes for students

Although we encourage students to propose their own project ideas, we cannot guarantee
that will find potential mentors for every proposal, especially for narrow areas.
During the selection phase we won't be able to accept proposals without mentors, so
we highly recommend getting initial feedback in the mailing lists before spending too much
time on such proposals.

[#acceptance-process]
== Acceptance process for new project proposals

Project proposals are tracked in two places. When first proposed they are added to
the link:https://docs.google.com/document/d/14N6kCShmxy4SumT0khuEFxXYZE4v1_bimK66PJuBHzM/edit#heading=h.o5kqo7p5rgto[project
  table in the projects doc]. Once a project is accepted as a draft, it is also published to
  link:/projects/gsoc/2019/project-ideas[jenkins.io].

Projects are proposed by a project champion who is a potential mentor or interested student.
Please see
link:/projects/gsoc/2019/roles-and-responsibilities[this list of roles] for
more information about the different project roles.
The champion will be responsible for shepherding the
proposal through the process. The acceptance process includes the following steps:

. The project champion makes a copy of the
  link:https://docs.google.com/document/d/1l5SdcLnlCwWA6qH8FKT9XC714Dl1XJ9lyy1CKDdKKAU[project proposal template]
  and creates a new Google Document describing the project proposal.
. When the project is ready for consideration, the project champion contacts GSoC org admins via the
  link:https://gitter.im/jenkinsci/gsoc-sig[Jenkins GSoC gitter channel] or the
  link:mailto://jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list].
. An org admin will add the proposal to the
  link:https://docs.google.com/document/d/14N6kCShmxy4SumT0khuEFxXYZE4v1_bimK66PJuBHzM/edit#heading=h.o5kqo7p5rgto[project
    table in the projects doc],
  giving it a status of "NEW"
. The link:/projects/gsoc/2019/#org-admins[GSoC org admins] and other mentors discuss the the proposal with the champion and provide initial feedback via the link:https://gitter.im/jenkinsci/gsoc-sig[gitter chat] and as comments to the proposal document.
. Once the proposal is consistent with the GSoC template requirements, a GSoC org admin will change the status to "DRAFT"
. An org admin publishes the draft project idea on link:/projects/gsoc/2019/project-ideas/#draft-project-ideas[jenkins.io]
. The project champion reaches out to the community to get additional feedback about the proposal
  (Community channels include chats, mailing lists, and the SIG meetings).
  NOTE: The champion should try to recruit one or more mentors from the community. Having
  multiple mentors is crucial to the success of the project.
  The proposal document should
  be updated to reflect any changes suggested by the community.
. Once the champion and org admins feel the proposal has been developed enough to be viable:
  . The org admins change the status of the proposal to "ACCEPTED" in the summary table
  . Contact Org admin publishes the current state of the document to the Jenkins website
  . After this change, champions/mentors should synchronize the google doc with jenkins.io
. The contact org admin updates the project at link:https://jenkins.io/projects/gsoc/2019/project-ideas[jenkins.io],
  moving from the drafts table to the accepted table, and updates the status to "PUBLISHED"

Project statuses:

* NEW - a google doc exists for the project, but it is sill under development, and not not yet formally correct.
* DRAFT - the proposal meets GSoC standards, and is ready for feeback from the community
* ACCEPTED - the project has been accepted, but is not yet on jenkins.io
* PUBLISHED - the project has been published to jenkins.io
* REJECTED - project is not compliant with GSoC rules. Can be reworked and reconsidered as Draft
* STALLED

** champion cancels it or abandons it (becomes unresponsive). Anyone can pick up the
    idea and become a new Champion.
** The student leaves the project before the end of GSoC.

* ARCHIVED - The project has been removed from jenkins.io. It can be picked up by a new champion.
* DONE - The project is completed by the end of the program.
