---
layout: project
title: "Proposing new project ideas"
tags:
- gsoc
project: gsoc
---

:toc:

New project ideas for GSoC can be proposed by mentors, students, or anyone in the Jenkins
community with an idea they'd like to see implemented.

Note: Project ideas should not be confused with link:../students#student-proposals[student proposals].

Students: to browse the existing project ideas offered by the Jenkins Organisation,
please read the instructions on the link:../students/[students page].

== Proposal quick start

If you would like to propose a project idea to the Jenkins community for the GSoC program:

. share your idea on the
link:mailto:jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list]
. use `[GSOC 2020 PROJECT IDEA] Title of idea` as the subject
. if your idea gets good feedback, create a pull-request:
.. fork and clone the link:https://github.com/jenkins-infra/jenkins.io[jenkins.io] repository
.. create a new `.adoc` file under the
link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/projects/gsoc/2020/project-ideas[project-ideas]
folder with your project idea
.. look at existing idea files for the format you should follow (many existing ideas contain a link to a google doc but this is optional)
.. in the pull-request comment box
... add `CC @jenkins-infra/gsoc` so we get a notification
... add a link to the related mailing list thread
.. post the pull-request link to the
link:https://gitter.im/jenkinsci/gsoc-sig[Jenkins GSoC gitter channel] and to the
link:mailto:jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list] as a follow up to your original thread.

The goal when you submit a project idea is to attract attention and feedback from the community.

== Requirements

* GSoC is about code (though it may and likely should include some documentation)
* Projects should be about Jenkins (plugins, core, infrastructure, integrations, test frameworks, etc.)
* Projects should be potentially doable by a student in 3-4 months

You can find more information about requirements and practices in the
link:https://google.github.io/gsocguides/mentor/[GSoC Mentor Guide].

== Examples

Need some hints? Here are examples of project ideas:

* A new plugin for integration with various development tools or services
* link:/doc/developer/plugin-governance/adopt-a-plugin/[Adopting an existing plugin],
extending it by adding new features like link:/doc/book/pipeline/[Jenkins Pipeline]
* Working on major feature requests from the link:https://issues.jenkins-ci.org/secure/Dashboard.jspa[Jenkins bugtracker]
* Creating new demo and reference setups,
powered by various "-as-Code" engines (e.g. Jenkins Pipeline, JobDSL, Docker, link:/projects/gsoc/gsoc2018-project-ideas/#jenkins-configuration-as-code[Configuration-as-Code plugin], etc.)

== Notes for students

Although we encourage students to propose their own project ideas, we cannot guarantee
that will find potential mentors for every proposal, especially for narrow areas.
During the selection phase we won't be able to accept proposals without mentors, so
we highly recommend getting initial feedback in the mailing lists before spending too much
time on such proposals.

== Template

Below is an `adoc` template for submitting a project idea to jenkins.io.
For more on `adoc` see link:https://asciidoctor.org/[asciidoctor.org].


```
---
layout: gsocprojectidea
title: "Specify the project idea title"
goal: "One sentence summarizing the goal of your idea"
category: Plugins
year: 2020
status: published
mentors:
- "userid1"   # This userid must exist under /content/_data/authors/userid.adoc on jenkins.io
- "userid2"   # You can have multiple mentors (and remove these comments when submitting)
skills:
- skills_go_here
- add_more_if_needed
links:
  gitter: "jenkinsci/gsoc-sig"
---

Write your project idea here. Sometimes an abstract is enough, but you should include:

* A short description of the project
* The benefits to the community
* A list of comparable solutions, and why your idea is better
* Anything you want to say about your project idea
* Students will read this when they look to participate in the program, so make sure you catch their attention!
* Have a look at other project ideas for inspiration to improve the way you present your idea

==== Quickstart

You may have quick start instructions for students, e.g. how to get started on your proposal. Provide this information here.

==== Links

You may have additional links to the ideas here, including related discussions on
the Jenkins Dev or Jenkins User mailing list, blogposts, Jiras, etc.

Links looks like this:

# Absolute link
link:https://plugins.jenkins.io/role-strategy[Role Strategy Plugin]

# Relative links within jenkins.io
link:../../students[Information page for students]


==== Newbie-friendly issues

If you are a potential mentor, propose examples of tickets the applicants could
study while preparing their project proposals.
We do NOT require students to make contributions before applying,
but such tasks may help to select students who are interested to work on the project.

```

== More examples of how to write project ideas

Refer to the following files on Github for additional example to format your project idea submission:

* link:https://github.com/jenkins-infra/jenkins.io/blob/master/content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin.adoc[Project idea with link to a google doc]
* link:https://github.com/jenkins-infra/jenkins.io/blob/master/content/projects/gsoc/2019/project-ideas/role-strategy-ux.adoc[Project idea with no link to google doc]
