---
layout: project
title: "Proposing new project ideas"
tags:
- gsoc
project: gsoc
---

:toc:

New ideas for GSoC can be proposed by mentors, students and/or anyone in the Jenkins
community with an idea they'd like to see implemented.

Note: Project ideas should not be confused with link:../students#student-proposals[student proposals].

== Proposal quick start

If you would like to propose a project idea to the Jenkins community for the GSoC program:

. share your idea on the
link:mailto:jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list]
. use `[GSOC 2020 PROJECT IDEA] Title of idea` as the subject
. if you idea gets good feedback, create a pull-request:
.. fork and clone the link:https://github.com/jenkins-infra/jenkins.io[jenkins.io] repository
.. create a new `.adoc` file under the
link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/projects/gsoc/2020/project-ideas[project-ideas]
folder with your project idea
.. look at existing idea files for the format you should follow (many existing ideas contain a link to a google doc but this is optional)
.. in the pull-request comment box
... add `CC @jenkins-infra/gsoc` so we get a notification
... add a link to the related mailing list thread
.. post the pull-request link to the
link:https://gitter.im/jenkinsci/gsoc-sig[Jenkins GSoC gitter channel] and to the
link:mailto:jenkinsci-gsoc-all-public@googlegroups.com[GSoC mailing list] as a follow up to your original thread.

The goal when you submit a project idea is to attract attention and feedback from the community.

== Requirements

* GSoC is about code (though it may and likely should include some documentation)
* Projects should be about Jenkins (plugins, core, infrastructure, integrations, test frameworks, etc.)
* Projects should be potentially doable by a student in 3-4 months

You can find more information about requirements and practices in the
link:https://google.github.io/gsocguides/mentor/[GSoC Mentor Guide].

== Examples

Need some hints? Here are examples of project ideas:

* A new plugin for integration with various development tools or services
* link:/doc/developer/plugin-governance/adopt-a-plugin/[Adopting an existing plugin],
extending it by adding new features like link:/doc/book/pipeline/[Jenkins Pipeline]
* Working on major feature requests from the link:https://issues.jenkins-ci.org/secure/Dashboard.jspa[Jenkins bugtracker]
* Creating new demo and reference setups,
powered by various "-as-Code" engines (e.g. Jenkins Pipeline, JobDSL, Docker, link:/projects/gsoc/gsoc2018-project-ideas/#jenkins-configuration-as-code[Configuration-as-Code plugin], etc.)

== Notes for students

Although we encourage students to propose their own project ideas, we cannot guarantee
that will find potential mentors for every proposal, especially for narrow areas.
During the selection phase we won't be able to accept proposals without mentors, so
we highly recommend getting initial feedback in the mailing lists before spending too much
time on such proposals.
