---
layout: project
title: "Proposing new project ideas"
tags:
- gsoc
---

:toc:

If you are interested in proposing a project or joining an existing one,
please start a thread in the GSoC SIG mailing list and describe your idea there.
New ideas can be proposed by mentors and/or students.
In order to propose a new project idea, create a draft description and start a new thread in the
link:https://groups.google.com/forum/#!forum/jenkinsci-gsoc-all-public[GSoC SIG mailing list]
(use the _[GSoC]_ prefix in the email subject).

== Requirements

* GSoC is about code (though it may and likely should include some documentation and testing work)
* Projects should be about Jenkins (plugins, core, infrastructure, integrations, etc.)
* Projects should be potentially doable by a student in 3-4 months

You can find more information about requirements and practices in the
link:https://google.github.io/gsocguides/mentor/[GSoC Mentor Guide].

== Examples

Need some hints? Here are examples of project ideas:

* A new plugin for integration with various development tools or services
* link:https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin[Adopting an existing plugin],
extending it by adding new features like link:/doc/book/pipeline/[Jenkins Pipeline]
* Working on major feature requests from the link:https://issues.jenkins-ci.org/secure/Dashboard.jspa[Jenkins bugtracker]
* Creating new demo and reference setups,
powered by various "-as-Code" engines (e.g. Jenkins Pipeline, JobDSL, Docker, link:/projects/gsoc/gsoc2018-project-ideas/#jenkins-configuration-as-code[Configuration-as-Code plugin], etc.)

== Notes for students

Although we encourage students to propose their own project ideas, we cannot guarantee
that will find potential mentors for every proposal, especially for narrow areas.
During the selection phase we won't be able to accept proposals without mentors, so
we highly recommend getting initial feedback in the mailing lists before spending too much
time on such proposals.

== Acceptance process for new project proposals

Project proposals are tracked in two places. When first proposed they are added to
the link:https://docs.google.com/document/d/14N6kCShmxy4SumT0khuEFxXYZE4v1_bimK66PJuBHzM/edit#heading=h.o5kqo7p5rgto[project
  table in the projects doc]. Once a project has been deemed viable, it is also published to
  link:https://jenkins.io/projects/gsoc/2019/project-ideas[jenkins.io].

Projects are proposed by the project champion. The champion will be responsible for shepherding the
proposal through the process. The acceptance process includes the following steps:

. The project champion creates a project proposal and adds the proposal to the
  link:https://docs.google.com/document/d/14N6kCShmxy4SumT0khuEFxXYZE4v1_bimK66PJuBHzM/edit#heading=h.o5kqo7p5rgto[project
    table in the projects doc],
  giving it a status of "NEW"
. The link:/projects/gsoc/#mentors-and-org-admins[GSoC org admins] discuss the the proposal with the champion and provide initial feedback
. Once the proposal is formally correct, a GSoC org admin will change the status to "DRAFT"
. An org admin publishes the draft project idea on link:https://jenkins.io/projects/gsoc/2019/project-ideas/#draft-project-ideas[jenkins.io]
. The project champion reaches out to the community to get additional feedback about the proposal
  (Community channels include chats, mailing lists, and the SIG meetings).
  NOTE: The champion should try to recruit one or more mentors from the community. Having
  multiple mentors is crucial to the success of the project.
  The proposal document should
  be updated to reflect any changes suggested by the community.
. Once the champion and org admins feel the proposal has been developed enough to be viable:
  .  The org admins change the status of the proposal to "ACCEPTED" in the summary table
  .  Champions/mentors should synchronize the google doc with jenkins.io
. The org admin update the project at link:https://jenkins.io/projects/gsoc/2019/project-ideas[jenkins.io],
  moving from the drafts table to the accepted table, and updates the status to "PUBLISHED"

Project statuses:

* NEW - a google doc exists for the project, but it is sill under development, and not not yet formally correct.
* DRAFT - the proposal meets GSoC standards, and is ready for feeback from the community
* ACCEPTED - the project has been accepted, but is not yet on jenkins.io
* PUBLISHED - the project has been published to jenkins.io
* REJECTED - project is not compliant with GSoC rules. Can be reworked and reconsidered as Draft
* STALLED
  * champion cancels it or abandons it (becomes unresponsive). Anyone can pick up the
    idea and become a new Champion.
  * The student leaves the project before the end of GSoC.
* ARCHIVED - The project has been removed from jenkins.io. It can be picked up by a new champion.
* DONE - The project is completed by the end of the program.
