---
layout: project
title: "Proposing new project ideas"
tags:
- gsoc
---

:toc:

If you are interested in proposing a new Google Summer of Code project or joining an existing one,
please start a new thread in the
link:https://groups.google.com/forum/#!forum/jenkinsci-gsoc-all-public[GSoC SIG mailing list]
describe your idea there.
New ideas can be proposed by mentors and/or students.
(use the _[NEW PROJECT:]_ prefix in the email subject).

== Requirements

* GSoC is about code (though it may and likely should include some documentation)
* Projects should be about Jenkins (plugins, core, infrastructure, integrations, test frameworks, etc.)
* Projects should be potentially doable by a student in 3-4 months

You can find more information about requirements and practices in the
link:https://google.github.io/gsocguides/mentor/[GSoC Mentor Guide].

== Examples

Need some hints? Here are examples of project ideas:

* A new plugin for integration with various development tools or services
* link:https://wiki.jenkins.io/display/JENKINS/Adopt+a+Plugin[Adopting an existing plugin],
extending it by adding new features like link:/doc/book/pipeline/[Jenkins Pipeline]
* Working on major feature requests from the link:https://issues.jenkins-ci.org/secure/Dashboard.jspa[Jenkins bugtracker]
* Creating new demo and reference setups,
powered by various "-as-Code" engines (e.g. Jenkins Pipeline, JobDSL, Docker, link:/projects/gsoc/gsoc2018-project-ideas/#jenkins-configuration-as-code[Configuration-as-Code plugin], etc.)

Once the project idea is proposed in the mailing list,
link:/projects/gsoc/#mentors-and-org-admins[GSoC org admins] will help to finalize the idea and to reach out to potential mentors/co-mentors.

== Notes for students

Although we encourage students to propose their own project ideas, we cannot guarantee
that will find potential mentors for every proposal, especially for narrow areas.
During the selection phase we won't be able to accept proposals without mentors, so
we highly recommend getting initial feedback in the mailing lists before spending too much
time on such proposals.
