---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2012"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingArchive2012-December12thMeeting]]
== December 12th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20121212T11&p1=224&ah=1&sort=1[December
12th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's items
* Authorizing SSL certificate renewal
(link:/blog/authors/kohsuke/[(kohsuke)])
* Renewing jenkins-ci.org domain
(link:/blog/authors/rtyler/[(rtyler)])
* Website banner usage guideline for people in the events list.
(link:/blog/authors/kohsuke/[(kohsuke)])
** like maybe giving automatic 1 week access to future events
* Donation status and what can we do more?
(link:/blog/authors/kohsuke/[(kohsuke)])
* Adding https://wiki.jenkins.io/display/~larrys[(larrys)]
to the admin to combat spam.

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-12-12-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-12-12-19.01.log.html[raw]

[[GovernanceMeetingArchive2012-November14thMeeting]]
== November 14th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20121114T11&p1=224&ah=1&sort=1[November
14th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's items
* Balancing personal information of JUC attendees vs cost
(link:/blog/authors/kohsuke/[(kohsuke)])
** https://docs.google.com/spreadsheet/ccc?key=0ApE2WVyiXL0hdGZSRTZVQmdTN2VnVWdJMWZCNEJqa1E[financial
report of past JUCs]
* Forming the Events subgroup in the community for the purpose of
coordinating and running event
(link:/blog/authors/lisawells[
(lisawells)]/link:/blog/authors/kohsuke/[
(kohsuke)])
** Initial task – define model for user events so we can attract others
to run them
** Improve oversight of JUC – define conditions, expectations, involve
community
** Streamline approvals for event publications on Jenkins-ci.org, blog,
& Twitter
** let this group handle CIA program
* Status of moving Jenkins to java 6 as minimal runtime
(link:/blog/authors/ndeloof[(ndeloof)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-11-14-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-11-14-19.01.log.html[raw]

[[GovernanceMeetingArchive2012-October31thMeeting]]
== October 31th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20121031T11&p1=224&ah=1&sort=1[October
31th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's items
* Take over http://www.meetup.com/jenkinsmeetup/["Jenkins users and
developers" group] at meetup.com? (costs $144 per year)
* Check on budget for buying stickers for next year's SCaLE11x and
FOSDEM conferences (link:/blog/authors/rtyler/[
(rtyler)])
* Accepting donations in Europe
(link:/blog/authors/orrc[(orrc)])
** I spoke to the
http://www.ffis.de/Verein/spi-en.html[Euro-friends-of-SPI] and it seems
we could become affiliated. Would be nice to get working before FOSDEM

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-10-31-18.03.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-10-31-18.03.log.html[raw]

[[GovernanceMeetingArchive2012-October17thMeeting]]
== October 17th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20121017T11&p1=224&ah=1&sort=1[October
17th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's items
* Picking next LTS (https://wiki.jenkins.io/display/~vjuranek[(vjuranek)])
* Advertising http://jenkins-ci.org/survey[survey] on
http://jenkins-ci.org/ (for 2 more weeks until it closes)
(link:/blog/authors/kohsuke/[(kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-10-17-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-10-17-18.02.log.html[raw]

[[GovernanceMeetingArchive2012-JenkinsUserConferenceMeeting@SanFrancisco]]
== Jenkins User Conference Meeting @ San Francisco

We'll have the project meeting in the meat-space at
http://www.cloudbees.com/jenkins-user-conference-2012-san-francisco.cb[Jenkins
User Conference San Francisco]. While we are still working on logistics,
the event will be transcribed to IRC and
http://www.ustream.tv/channel/jenkins-ci[get broadcasted live]. So if
you aren't physically in the event, please join us in our usual IRC
channel.

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120930T18&p1=224&ah=1[September
30th 18:00 PDT], which should be 9pm EDT, Oct 1st 1am UTC, Oct 1st 10am
Tokyo.

Please suggest your agenda. Unlike regular project meetings, order here
is irrelevant because we'll decide what to cover before the meeting.
Please try to come up with the agenda items that take advantages of
unusual audience demographic.

* Discussion about future funding source/plan / fiance report
* What are the pain points? (from 10000ft perspective, not individual
bugs or features.)
* What should the development team focus on? Are we working on the right
things? (from 10000ft perspective, not individual bugs or features.)
* What are the barriers to participation?

Topic suggestions

[width="100%",cols="34%,33%,33%",options="header",]
|===
|who + |suggestion + |first thoughts +
|link:/blog/authors/rtyler/[(rtyler)]
|Decommissioning "cabbage" and migrating some new services to OSUOSL VMs
|

|Domi + |There are to many plugins doing (nearly) the same, its really
hard for users to decide which one fits his need the best |_- although
we want to keep the barriers for new participants low, we should not
blindly clone every repo._ +
_- The ones allowed to do this, should act as some kind of gatekeepers,
I know this sounds hard but I really think we should encourage people to
enhance/improve existing plugins._ +
_- I'd rather have more people working on the same plugin then adding a
new one which looses its maintainer afar the first couple releases._

|Domi + |Think bigger… many features are implemented in a way they work
with small to midrange side installations, but when you have 100+
Salves, 1000+ Users, 1000+ Jobs - things get more complicated. e.g.: +
|_- which plugins are actually in use? how many times? where?_ +
_- listing of all users in the security config gets too big_ +
_- plugins should think about what is really a global config what should
be on job level. (e.g. global acts as default only)_

|Domi + |Think security… plugin developers should think about what
features compromise security. |_- e.g. blindly providing groovy access
to Jenkins internals is a security hole_ +
_- maybe it makes sense for an administrator to disable single features
in a plugin or he should be the one to decide whether his users are
allowed to configure something instead of him._ +
_- also keep the size of an installation in mind_

|Domi + |There is more work done to improve the UI (separate branch):
[https://github.com/jenkinsci/jenkins/tree/ui-changes +
] |_- we should reactivate that work_

|Tonylampada + |Speaking of funding, please don't forget mention
http://www.freedomsponsors.org/[FreedomSponsors] |_- If people there
have any feedback about the JIRA plugin, or the platform in general, I'm
very interested!_ +
_- Also, if Kohsuke is planning to mention FreedomSponsors in a slide,
could someone please take a picture?_
image:https://wiki.jenkins.io/s/en_GB/8100/5084f018d64a97dc638ca9a178856f851ea353ff/_/images/icons/emoticons/smile.svg[(smile)]
|===

[[GovernanceMeetingArchive2012-September19thMeeting]]
== September 19th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120919T11&p1=224&ah=1&sort=1[September
19th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's items
* Discussion about future funding source/plan
* Add more hackers to the SECURITY project to give more
visibility/opportunity for security issues to be addressed
(link:/blog/authors/rtyler/[(rtyler)])
* Review survey questions for JUC San Francisco (Lisa Wells)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-09-19-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-09-19-18.00.log.html[raw]

[[GovernanceMeetingArchive2012-September5thMeeting]]
== September 5th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120905T11&p1=224&ah=1&sort=1[September
5th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Should the "Sponsor this issue" link be
https://github.com/freedomsponsors/freedomsponsors-jira-plugin/issues/4[ommited
for closed issues]?
(https://wiki.jenkins.io/display/~tonylampada[
(tonylampada)])
* Discussion about the
https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[Board
Election Process] (link:/blog/authors/kohsuke/[
(kohsuke)])
* Help wanted: spams are on the rise
(link:/blog/authors/kohsuke/[(kohsuke)])
* FOSDEM travel grant

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-09-05-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-09-05-18.00.log.html[raw]

[[GovernanceMeetingArchive2012-August22thMeeting]]
== August 22th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120822T11&p1=224&ah=1&sort=1[August
22nd 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-08-18.01.html[action
items]
* Travel grant for FOSDEM?
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-08-18.01.html[context]
(link:/blog/authors/rtyler/[(rtyler)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-22-18.06.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-22-18.06.log.html[raw]

[[GovernanceMeetingArchive2012-August8thMeeting]]
== August 8th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120822T11&p1=224&ah=1&sort=1[August
8th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* http://itunes.apple.com/us/app/jenkins-ci-speak/id533789857?mt=12[Commercial
use of the name "Jenkins"]. Do we need to take any actions?
(link:/blog/authors/kohsuke/[(kohsuke)])
* Demoing the
http://www.freedomsponsors.org/core/issue/12/jira-plugin-to-link-from-tickets-to-freedomsponsors[FreedomSponsors
JIRA plugin] - http://ambtest.freedomsponsors.org:8080/browse/TLM-1[live
demo] /
https://github.com/freedomsponsors/freedomsponsors-jira-plugin[installation
instructions] (https://wiki.jenkins.io/display/~tonylampada[
(tonylampada)])
* Upcoming event planning and brainstorming
https://groups.google.com/forum/?fromgroups#!topic/jenkinsci-dev/bokUEoheAAs%5B1-25%5D[link1]
https://groups.google.com/forum/?fromgroups#!topic/jenkinsci-dev/eFawHz1JWYg%5B1-25%5D[link2]
(link:/blog/authors/kohsuke/[(kohsuke)]).
* Documentation of jenkins-admin IRC-bot infra, so that community can
manage restart. (link:/blog/authors/ndeloof[
(ndeloof)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-08-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-08-08-18.01.log.html[raw]

[[GovernanceMeetingArchive2012-July25thMeeting]]
== July 25th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120725T11&p1=224&ah=1&sort=1[July
25th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* http://itunes.apple.com/us/app/jenkins-ci-speak/id533789857?mt=12[Commercial
use of the name "Jenkins"]. Do we need to take any actions?
(link:/blog/authors/kohsuke/[(kohsuke)])
* Installing the
http://www.freedomsponsors.org/core/issue/12/jira-plugin-to-link-from-tickets-to-freedomsponsors[FreedomSponsors
JIRA plugin] - when it's finished development.
(https://wiki.jenkins.io/display/~tonylampada[
(tonylampada)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-07-25-18.05.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-07-25-18.05.log.html[raw]

[[GovernanceMeetingArchive2012-July11thMeeting]]
== July 11th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120711T11&p1=224&ah=1&sort=1[July
11th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-06-27-18.01.html[action
items]
* How much if any advertisement is acceptable on plugin pages (ex.
https://wiki.jenkins.io/display/JENKINS/Warnings+Plugin[Warnings
Plugin]) (link:/blog/authors/rtyler/[
(rtyler)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-07-11-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-07-11-18.02.log.html[raw]

[[GovernanceMeetingArchive2012-June27thMeeting]]
== June 27th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120627T11&p1=224&ah=1&sort=1[June
27th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Baseline for next major LTS release
(https://wiki.jenkins.io/display/~vjuranek[vjuranek]) 

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-06-27-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-06-27-18.01.log.html[raw]

[[GovernanceMeetingArchive2012-June13thMeeting]]
== June 13th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120613T11&p1=224&ah=1&sort=1[June
13th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Selenium tests, switch to Cucumber/Capybara (vjuranek)
* New home for wiki.jenkins-ci.org
(link:/blog/authors/kohsuke/[(kohsuke)])
* maven.jenkins-ci.org to repo.jenkins-ci.org switch voer
(link:/blog/authors/kohsuke/[(kohsuke)])

[[GovernanceMeetingArchive2012-May30thMeeting]]
== May 30th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120530T11&p1=224&ah=1&sort=1[May
30th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Moving Subversion repository to GitHub
link:/blog/authors/kohsuke/[(kohsuke)]
* Improving JonJ and IRC bot stability - JonJ gets stuck very often
recently, IRC bot also seems to get stuck when forking repo (vjuranek,
unfortunately cannot attend but can offer some help) 
* Plugin JonJ on DEV@ or BuildHive
https://wiki.jenkins.io/display/~jieryn[(jieryn)]

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-05-30-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-05-30-18.01.log.html[raw]

[[GovernanceMeetingArchive2012-May2ndMeeting]]
== May 2nd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120502T11&p1=224&ah=1&sort=1[May
2nd 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-04-14-04.02.html[action
items]

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-05-02-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-05-02-18.01.log.html[raw]

[[GovernanceMeetingArchive2012-Apr14thMeeting]]
== Apr 14th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120414T21&p1=224&ah=1&sort=1[April
14th 04:00 UTC], which should be 13th Fri 9pm PDT, 13th Fri midnight
EDT, 14th Sat 5am CEST, 14th Sat 1pm Tokyo. +
*This is a one off time different from the usual schedule*

* Recap last meeting's action items
* JUC Tokyo status updates
(https://wiki.jenkins.io/display/~ikikko[(ikikko)],
link:/blog/authors/kohsuke/[(kohsuke)], and
others)
* Anything we can do for bridging the Japanese community?

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-04-14-04.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-04-14-04.02.log.html[raw]

[[GovernanceMeetingArchive2012-Apr4thMeeting]]
== Apr 4th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120404T11&p1=224&ah=1&sort=1[April
4th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's action items
* Move plugin CI jobs to jenkins.ci.cloudbees.com
(link:/blog/authors/ndeloof[(ndeloof)])
* Proposal : ask for FOSS JProfiler licenses ->
http://www.ej-technologies.com/buy/jprofiler/openSource
(link:/blog/authors/ndeloof[(ndeloof)])
* Migrate plugins to get rid of glassfish repo
(link:/blog/authors/ndeloof[(ndeloof)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-04-04-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-04-04-18.01.log.html[raw]

[[GovernanceMeetingArchive2012-Mar21stMeeting]]
== Mar 21st Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120321T11&p1=224&ah=1&sort=1[March
21st 18:00 UTC], which should be 11am PDT, 2pm EDT, 7pm CET, 3am Tokyo.

* Recap last meeting's action items
* Please sign CLAs (link:/blog/authors/kohsuke/[(kohsuke)])
* Officially launching
https://wiki.jenkins.io/display/JENKINS/Jenkins+CIA+Program[Jenkins CIA
Program] (link:/blog/authors/kohsuke/[
(kohsuke)])
* "Jenkins@cloud for GitHub" and "Jenkins@cloud by CloudBees" name usage
approval (link:/blog/authors/kohsuke/[
(kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-03-21-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-03-21-18.00.log.html[raw]

[[GovernanceMeetingArchive2012-Mar7thMeeting]]
== Mar 7th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120307T11&p1=224&ah=1&sort=1[March
7th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's action items
* Review current status and plans for
https://wiki.jenkins.io/display/JENKINS/The+new+EMailer[The new EMailer]
(link:/blog/authors/slide_o_mix[
(slide.o.mix@gmail.com)])
* Last-minute discussion on Google SoC mentors
(link:/blog/authors/rtyler/[(rtyler)])
* Baseline for next major LTS release
(https://wiki.jenkins.io/display/~vjuranek[vjuranek])
* Cut-over from http://maven.jenkins-ci.org/ to
http://repo.jenkins-ci.org/ : PoC demo
(link:/blog/authors/kohsuke/[(kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-03-07-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-03-07-19.01.log.html[raw]

[[GovernanceMeetingArchive2012-Feb22ndMeeting]]
== Feb 22nd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120222T11&p1=224&ah=1&sort=1[Feburary
22nd 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's action items
* Proposal: Move away from Drupal to a Git repository powered by Jekyll
for the community site (link:/blog/authors/rtyler/[(rtyler)])
* It's been a year, should we elect a new board, how/when/etc?
(link:/blog/authors/rtyler/[(rtyler)])
* JUC promotion ideas

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-02-22-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-02-22-19.00.log.html[raw]

[[GovernanceMeetingArchive2012-Feb8thMeeting]]
== Feb 8th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120208T11&p1=224&ah=1&sort=1[Feburary
8th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's action items
* Pull requests and inbound contributor funnel discussion

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-02-08-19.03.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-02-08-19.03.log.html[raw]

[[GovernanceMeetingArchive2012-Jan25thMeeting]]
== Jan 25th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120125T11&p1=224&ah=1&sort=1[January
25th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's action items
* #jenkins IRC status update - @jieryn
** please review Cloaks section of
https://wiki.jenkins-ci.org/display/JENKINS/IRC+Channel
* Consider using cloudbees FOSS, http://www.cloudbees.com/foss/ -
@jieryn

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-01-25-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-01-25-19.00.log.html[raw]

[[GovernanceMeetingArchive2012-Jan11thMeeting]]
== Jan 11th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20120111T11&p1=224&ah=1&sort=1[January
11th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's action items
* Would it make sense to populate the *Affects Version/s* and *Fix
Version/s* fields in the Jenkins JIRA (automatically)? (Might include
talking about the long pending plan of separating core and plugins in
JIRA) (https://wiki.jenkins.io/display/~fredg[(fredg)])
* Funding for give-aways in events (stickers and T-shirts)
* Start collecting CLAs

MINUTES
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-01-11-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2012/jenkins.2012-01-11-19.00.log.html[raw]
