---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2019"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingArchive2013-Dec11thMeeting]]
== Dec 11th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20131211T11&p1=224&ah=1&sort=1[Dec
11th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Advertisements on jenkins-ci.org?
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* JUC 2014 brainstorming (Alyssa Tong)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-12-11-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-12-11-19.01.log.html[raw]



[[GovernanceMeetingArchive2013-Nov13thMeeting]]
== Nov 13th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20131113T11&p1=224&ah=1&sort=1[Nov
13th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Name approval request take 2 "Jenkins Operations Center by CloudBees"
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* LTS status

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-11-13-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-11-13-19.01.log.html[raw]



[[GovernanceMeetingArchive2013-Oct30thMeeting]]
== Oct 30th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20131030T11&p1=224&ah=1&sort=1[Oct
30th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* LTS status (https://wiki.jenkins.io/display/~jglick[Unknown User
(jglick)])
* Name approval request for "Jenkins Multi-master by CloudBees"
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Jenkins User Conference Recap (autojack)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-30-18.05.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-30-18.05.log.html[raw]



[[GovernanceMeetingArchive2013-Oct16thMeeting]]
== Oct 16th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20131016T11&p1=224&ah=1&sort=1[Oct
16th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-16-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-16-18.01.log.html[raw]



[[GovernanceMeetingArchive2013-Sep18thMeeting]]
== Sep 18th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130918T11&p1=224&ah=1&sort=1[Sep
18th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* JUC Palo Alto discussion and feedback (Alyssa)
* Event coordination for winter — SCALE? FOSDEM?
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-02-18.04.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-10-02-18.04.log.html[raw]



[[GovernanceMeetingArchive2013-Sep4thMeeting]]
== Sep 4th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130904T11&p1=224&ah=1&sort=1[Sep
4th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

(Cancelled)

[[GovernanceMeetingArchive2013-Aug21thMeeting]]
== Aug 21th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130821T11&p1=224&ah=1&sort=1[Aug
21th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

[[GovernanceMeetingArchive2013-Aug7thMeeting]]
== Aug 7th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130807T11&p1=224&ah=1&sort=1[Aug
7th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Backporting of support for Maven 3.1 into upcoming  LTS release
(vjuranek)
* Schedule Credentials:1.6, SSH Credentials 1.0, SSH Slaves 1.0 for
integration in 1.509.4 if there is one (stephenconnolly)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-08-07-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-08-07-18.01.log.html[raw]

[[GovernanceMeetingArchive2013-Jul24thMeeting]]
== Jul 24th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130724T11&p1=224&ah=1&sort=1[Jul
24th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Next LTS plan and start lifting Java 6 dependency
https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)]

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-07-24-18.05.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-07-24-18.05.log.html[raw]

[[GovernanceMeetingArchive2013-Jul10thMeeting]]
== Jul 10th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130710T11&p1=224&ah=1&sort=1[Jul
10th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Improving out of the box experience: bundle more plugins
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Pull request greeting bot rollout
(https://github.com/jenkinsci/throttle-concurrent-builds-plugin/pull/5[example])
(https://github.com/jenkinsci/nant-plugin/pull/2[why we need it])
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-07-10-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-07-10-18.00.log.html[raw]

[[GovernanceMeetingArchive2013-Jun26thMeeting]]
== Jun 26th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130626T11&p1=224&ah=1&sort=1[Jun
26th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Highlighting LTS releases more
(https://wiki.jenkins.io/display/~domi[Unknown User (domi)])
* Travel grant to JUC (https://wiki.jenkins.io/display/~kohsuke[Unknown
User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-06-26-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-06-26-18.01.log.html[raw]

[[GovernanceMeetingArchive2013-Jun12thMeeting]]
== Jun 12th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130612T11&p1=224&ah=1&sort=1[Jun
12th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions
* Jenkins certification from the Japanese community
https://docs.google.com/file/d/18sXYsZJrvkSECZKYfxLFkyDKlnlQTCvpaigY9BW_PTX4pJeEWu2iJyBBQ90S/edit?usp=sharing

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-06-12-18.14.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-06-12-18.14.log.html[raw]

[[GovernanceMeetingArchive2013-May29thMeeting]]
== May 29th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130529T11&p1=224&ah=1&sort=1[May
29th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions

[[GovernanceMeetingArchive2013-May15thMeeting]]
== May 15th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130515T11&p1=224&ah=1&sort=1[May
15th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions
* LTS 1.509.2 (vjuranek)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-05-15-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-05-15-18.00.log.html[raw]

[[GovernanceMeetingArchive2013-May1stMeeting]]
== May 1st Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130501T11&p1=224&ah=1&sort=1[May
1st 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions
* mirroring artifacts to Central (jglick)
* 1.509.1 status update (jglick)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-05-01-18.03.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-05-01-18.03.log.html[raw]

[[GovernanceMeetingArchive2013-April17thMeeting]]
== April 17th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130417T11&p1=224&ah=1&sort=1[April
17th 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions

This meeting was kipped

[[GovernanceMeetingArchive2013-April3rdMeeting]]
== April 3rd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130403T11&p1=224&ah=1&sort=1[April
3rd 18:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CEST, 3am Tokyo.

* Recap last meeting's actions
* https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[Board
Election Process]
* next LTS candidate
* problem with granting commit access to plugin devs

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-04-03-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-04-03-18.01.log.html[raw]

[[GovernanceMeetingArchive2013-March20thMeeting]]
== March 20th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130320T11&p1=224&ah=1&sort=1[March
20th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's actions
* Clean up changelog handling (jglick)

* Meeting did not take place; agenda moved to April 3rd.

[[GovernanceMeetingArchive2013-March6thMeeting]]
== March 6th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130306T11&p1=224&ah=1&sort=1[March
6th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's actions
* Change LTS backport procedure: use labeling
as http://groups.google.com/group/jenkinsci-dev/msg/6f513f00c607eed0[proposed] https://groups.google.com/d/msg/jenkinsci-dev/aUAd_QwbAdE/0O4HxgA_UW8J[(alt)]by
Jesse (vjuranek)
* Notification of issues included in a release and Use of release
numbers in JIRA (mc1arke)
* Next LTS rebump?

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-03-06-19.13.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-03-06-19.13.log.html[raw]

[[GovernanceMeetingArchive2013-Feburary20thMeeting]]
== Feburary 20th Meeting

WHEN http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130220T11&p1=224&ah=1&sort=1[Feburary
20th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's actions
* SCALE 11x prep
* Change LTS backport procedure: use labeling
as http://groups.google.com/group/jenkinsci-dev/msg/6f513f00c607eed0[proposed] https://groups.google.com/d/msg/jenkinsci-dev/aUAd_QwbAdE/0O4HxgA_UW8J[(alt)]by
Jesse (vjuranek)
* Notification of issues included in a release and Use of release
numbers in JIRA (mc1arke)
* Failed to achieve quorum to hold meeting. Agenda moved to 3/6.

[[GovernanceMeetingArchive2013-Feburary6thMeeting]]
== Feburary 6th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130206T11&p1=224&ah=1&sort=1[Feburary
6th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Failed to achieve quorum to hold meeting. Agenda moved to 2/20.

[[GovernanceMeetingArchive2013-January23rdMeeting]]
== January 23rd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130123T11&p1=224&ah=1&sort=1[January
23rd 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Recap last meeting's actions
* FOSDEM prep discussion?
* Confirm European donation status (would be good to mention in all our
talks/stands/flyers at FOSDEM)
(https://wiki.jenkins.io/display/~orrc[Unknown User (orrc)])
* Authorize another sticker batch purchase of $500
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* SSL certificate renewal
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-01-23-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2013/jenkins.2013-01-23-19.01.log.html[raw]

[[GovernanceMeetingArchive2013-January9thMeeting]]
== January 9th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20130109T11&p1=224&ah=1&sort=1[January
9th 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Meeting canceled per IRC discussion due to lack of agenda items.
