---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2019"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingArchive2014-Dec24meeting]]
== Dec 24 meeting

* Cancelled. Happy holidays!

[[GovernanceMeetingArchive2014-Dec10meeting]]
== Dec 10 meeting

* 1.580.2 status check
(https://wiki.jenkins.io/display/~olivergondza[Unknown User
(olivergondza)])

[[GovernanceMeetingArchive2014-Nov26meeting]]
== Nov 26 meeting

* 1.580.2 RC status check
(https://wiki.jenkins.io/display/~olivergondza[Unknown User
(olivergondza)])
* https://groups.google.com/d/msg/jenkinsci-dev/rzNetnrhPRI/7rRfyshG9bEJ[Mark
usage request from CloudBees]
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Can we improve the Jenkins release process?
(https://wiki.jenkins.io/display/~danielbeck[Unknown User (danielbeck)])
* INFRA components
(https://wiki.jenkins.io/display/~oleg_nenashev[Unknown User
(oleg_nenashev)])
** Migration of repositories to https://github.com/jenkins-infra/
(INFRA-169)
** Test environment: Confluence clone for plugins testing (macros, etc.)
** Guidelines describing current INFRA permissions and contacts
*** Currently, INFRA activities require much time/efforts due to unknown
contacts (or 1-person bottlenecks)
*** Example 1: Access to TEST project on JIRA for IRCBot testing
(INFRA-170)
*** Example 2: Confluence plugin update for components renaming
(INFRA-147)
* https://github.com/jenkinsci/patron/pull/2/files[Patron message
changes from CloudBees]
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

[[GovernanceMeetingArchive2014-Nov12meeting]]
== Nov 12 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20141112T11&p1=224&ah=1&sort=1[Nov
12th 11:00 Pacific], which should be 6pm UTC, 2pm Eastern, 8pm Central
Europe, 4am Tokyo.

[.aui-icon .aui-icon-small .aui-iconfont-warning .confluence-information-macro-icon]#
#

It's DST change season: Make sure you're not
https://en.wikipedia.org/wiki/Off-by-one_error[off by one] (hour)!

* https://groups.google.com/d/msg/jenkinsci-dev/rzNetnrhPRI/7rRfyshG9bEJ[Mark
usage request from CloudBees]
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Decision on further component renames in Jira
(https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk[https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk|https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk])
(https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk[https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk|https://groups.google.com/forum/#!topic/jenkinsci-dev/T_V9Z71rbPk])
(https://wiki.jenkins.io/display/~danielbeck[Unknown User (danielbeck)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-11-12-19.04.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-11-12-19.04.log.html[raw]

[[GovernanceMeetingArchive2014-Oct29meeting]]
== Oct 29 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20141029T11&p1=224&ah=1&sort=1[Oct
29th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 7pm Central
Europe, 3am Tokyo.

* LTS release status check
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

[[GovernanceMeetingArchive2014-Oct15meeting]]
== Oct 15 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20141015T11&p1=224&ah=1&sort=1[Oct
15th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* Using `+stable+` vs `+stable-+`__x__ branch for core LTS.  
** Using `+stable+` provides convenient way to access latest stable
commit for client but requires either force pushing or ours merging.
`+stable-+`__x__ requires neither, though someone have to remember
updating all automation.
* Update on plugins not getting forked into jenkinsci, or not getting
released from there (https://wiki.jenkins.io/display/~danielbeck[Unknown
User (danielbeck)])

[[GovernanceMeetingArchive2014-Oct1meeting]]
== Oct 1 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20141001T11&p1=224&ah=1&sort=1[Oct
1st 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* Q4 patron ads on Jenkins Wiki
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Plugins not getting forked into jenkinsci, or not getting released
from there (https://wiki.jenkins.io/display/~danielbeck[Unknown User
(danielbeck)])
* GitHub private repositories for security work
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* New LTS base line (https://wiki.jenkins.io/display/~kohsuke[Unknown
User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-10-01-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-10-01-18.01.log.html[raw]

[[GovernanceMeetingArchive2014-Sep17meeting]]
== Sep 17 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140917T11&p1=224&ah=1&sort=1[Sep
17th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* Travel grant for JUC Tokyo 2015
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)]). As
of Jun 30th we have
http://www.spi-inc.org/meetings/minutes/2014/2014-07-10/[$14K+ in the
bank]. Can we spend some of it (proposal:$2K) to send spekaers to the
upcoming JUC Tokyo?
* Cease support for native Solaris packages
(https://wiki.jenkins.io/display/~rtyler[Unknown User (rtyler)])
* Improvements to JENKINS project in JIRA
(https://wiki.jenkins.io/display/~danielbeck[Unknown User
(danielbeck)]):
** Set the default priority to 'Minor'
** Remove the 'Patch' issue type
** Make closed issues editable
** Already implemented (but can be reversed): Hide 'Due Date, 'Affects
Version' and 'Fix Version' fields, add specific instructions for some
fields when creating an issue.
* Can we improve the Jenkins release process?
(https://wiki.jenkins.io/display/~danielbeck[Unknown User (danielbeck)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-09-17-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-09-17-18.00.log.html[raw]

[[GovernanceMeetingArchive2014-Sep3meeting]]
== Sep 3 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140903T11&p1=224&ah=1&sort=1[Sep
3rd 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* LTS status check (https://wiki.jenkins.io/display/~kohsuke[Unknown
User (kohsuke)])
* How do we run the "Ask the Experts" section in JUC?
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Decision on implementing
https://wiki.jenkins.io/display/JENKINS/Browser+Compatibility+Matrix[Browser
Compatibility Matrix]
(https://wiki.jenkins.io/display/~danielbeck[Unknown User (danielbeck)])
* https://wiki.jenkins.io/display/JENKINS/2014+JIRA+Components+Refactoring[2014
JIRA Components Refactoring]
(https://wiki.jenkins.io/display/~danielbeck[Unknown User (danielbeck)])
** Decision on adding `+-plugin+` suffix and rename/merge of other
components (table in _Modification of existing components_)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-09-03-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-09-03-18.01.log.html[raw]

[[GovernanceMeetingArchive2014-Aug20meeting]]
== Aug 20 meeting

Canceled.

[[GovernanceMeetingArchive2014-Aug06meeting]]
== Aug 06 meeting

Canceled.

[[GovernanceMeetingArchive2014-Jul23thMeeting]]
== Jul 23th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140723T11&p1=224&ah=1&sort=1[Jul
23rd 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* JUC
** Date set: Oct 23, Hyatt Burlingame by San Francisco Airport
** Schedule a Jenkins meet-up around same time?
** CD Summit scheduled for Oct 22nd in San Francisco
** Sponsor contact details - ok to also share "job title" details with
Gold & Platinum sponsors? Their sales teams will care about this.

(No Kohsuke; jglick will try to drive the bot.)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-07-23-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-07-23-18.02.log.html[raw]

[[GovernanceMeetingArchive2014-Jul9thMeeting]]
== Jul 9th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140709T11&p1=224&ah=1&sort=1[Jul
9th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* Brainstorming on improving the sponsor contact opt-in ratio: only 20%
of the attendees opted in to the sponsor contact. What can we do to
improve that (or make it up in another way)?
* Next Jenkins newsletter - Call for Content
* 1.565.1 RC status check

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-07-09-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-07-09-18.02.log.html[raw]

[[GovernanceMeetingArchive2014-Jun25thMeeting]]
== Jun 25th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140625T11&p1=224&ah=1&sort=1[Jun
25th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* 1.554.3 release status check
* What's the next LTS baseline?

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-06-25-18.11.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-06-25-18.11.log.html[raw]

[[GovernanceMeetingArchive2014-Jun11thMeeting]]
== Jun 11th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140611T11&p1=224&ah=1&sort=1[Jun
11th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* 1.554.3 RC status check
* JUC (https://wiki.jenkins.io/display/~lisawells[Unknown User
(lisawells)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-06-11-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-06-11-18.00.log.html[raw]

[[GovernanceMeetingArchive2014-May28thMeeting]]
== May 28th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140528T11&p1=224&ah=1&sort=1[May
28th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* comission to build 3D model of Mr.Jenkins?
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* 1.554.2 LTS release status check
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* JUC

[[GovernanceMeetingArchive2014-May14thMeeting]]
== May 14th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140514T11&p1=224&ah=1&sort=1[May
14th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

[[GovernanceMeetingArchive2014-Apr30thMeeting]]
== Apr 30th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140430T11&p1=224&ah=1&sort=1[Apr
30th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* 1.554.1 release status
* Jenkins joining http://www.openinventionnetwork.com/[the software
patent non-aggression community]?
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Permanently switch to acceptance-tests for LTS testing. (ogondza)

[[GovernanceMeetingArchive2014-Apr16thMeeting]]
== Apr 16th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140416T11&p1=224&ah=1&sort=1[Apr
16th 18:00 UTC], which should be 11am Pacific, 2pm Eastern, 8pm Central
Europe, 3am Tokyo.

* JUC status update / travel grant?
(https://wiki.jenkins.io/display/~lisawells[Unknown User
(lisawells)]/Alyssa)
** how to reach German Jenkins community?
* 1.554.1 RC status (https://wiki.jenkins.io/display/~jglick[Unknown
User (jglick)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-04-16-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-04-16-18.00.log.html[raw]

[[GovernanceMeetingArchive2014-Apr2ndMeeting]]
== Apr 2nd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140402T11&p1=224&ah=1&sort=1[Apr
2nd 18:00 UTC], which should be 11am PDT, 2pm EDT, 9pm CEST, 4am Tokyo.

* 1.554 go or no-go (https://wiki.jenkins.io/display/~kohsuke[Unknown
User (kohsuke)])
* https://wiki.jenkins.io/display/JENKINS/Patron+of+Jenkins+program[Patron
of Jenkins program] approval
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* JIRA Versions backend application
(https://wiki.jenkins.io/display/~slide_o_mix[slide_o_mix])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-04-02-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-04-02-18.02.log.html[raw]



[[GovernanceMeetingArchive2014-Mar19thMeeting]]
== Mar 19th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140319T11&p1=224&ah=1&sort=1[Mar
19th 19:00 UTC], which should be 11am PDT, 2pm EDT, 8pm CET, 4am Tokyo.

* Pick new LTS baseline
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])
* Review of the
https://wiki.jenkins.io/display/JENKINS/2014+Jenkins+Infrastructure+Roadmap[2014
Jenkins Infrastructure Roadmap]
(https://wiki.jenkins.io/display/~rtyler[Unknown User (rtyler)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-03-19-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-03-19-18.01.log.html[raw]



[[GovernanceMeetingArchive2014-Mar5thMeeting]]
== Mar 5th Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140305T11&p1=224&ah=1&sort=1[Mar
5h 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* Moving cucumber from Contegix to the OSUOSL data centers
* Moving Confluence to a new VM
* Switching from masterless Puppet to a Puppet master.
* Approval to order more stickers
(https://wiki.jenkins.io/display/~kohsuke[Unknown User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-03-05-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-03-05-19.00.log.html[raw]



[[GovernanceMeetingArchive2014-Jan22ndMeeting]]
== Jan 22nd Meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20140122T11&p1=224&ah=1&sort=1[Jan
22nd 19:00 UTC], which should be 11am PST, 2pm EST, 8pm CET, 4am Tokyo.

* FOSDEM planning
* LTS.next planning and its scheduled cadence
(https://wiki.jenkins.io/display/~olivergondza[Unknown User
(olivergondza)])
* https://wiki.jenkins.io/pages/viewpage.action?pageId=71435396["Patron
of Jenkins" proposal] (https://wiki.jenkins.io/display/~kohsuke[Unknown
User (kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-01-22-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-01-22-19.01.log.html[raw]
