---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2015"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingArchive2015-Dec23meeting]]
== Dec 23 meeting

*This meeting will be skipped.*

[[GovernanceMeetingArchive2015-Dec9meeting]]
== Dec 9 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20151209T11&p1=224&ah=1&sort=1[Dec
9 11:00 Pacific].

* Recap last meeting's actions
* LTS status check
* Next LTS baseline selection
* (*hopefully*) Final review/adoption of
https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[Board
Election Process] (link:/blog/authors/rtyler/[
(rtyler)])
* Review/adopt a
https://wiki.jenkins.io/display/JENKINS/Code+of+Conduct[Code of Conduct]
(link:/blog/authors/rtyler/[(rtyler)])
* *NOT* tweet anymore plugins w/o a wiki page
(link:/blog/authors/batmat[(batmat)]) (for
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-dev/qR8WqJZmNZs/1a9Zd3F0DAAJ[reference])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-12-09-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-12-09-19.01.log.html[raw]

[[GovernanceMeetingArchive2015-Nov25meeting]]
== Nov 25 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20151125T11&p1=224&ah=1&sort=1[Nov
25 11:00 Pacific].

* Recap last meeting's actions
* LTS RC status check
* Announce Security Officer
(link:/blog/authors/rtyler/[(rtyler)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-11-25-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-11-25-19.00.log.html[raw]

[[GovernanceMeetingArchive2015-Nov11meeting]]
== Nov 11 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20151111T11&p1=224&ah=1&sort=1[Nov
11 11:00 Pacific].

* Recap last meeting's actions
* Review proposed www site change from Drupal to static site generation
(current https://github.com/rtyler/jenkins.io[repo] and
http://jenkins.lasagna.io/[generated version of site])
(link:/blog/authors/rtyler/[(rtyler)])
* CERT membership requests from
https://groups.google.com/forum/#!msg/jenkinsci-dev/TachZG6zw44/UMBz91HMAgAJ[Ivan
Meredith] and
https://groups.google.com/forum/#!msg/jenkinsci-dev/TachZG6zw44/v2sG6UvPAgAJ[Ben
Walding] (link:/blog/authors/daniel-beck/[
(danielbeck)])
* Review
https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[Board
Election Process] and either move forward with the proposal or take
feedback so we can have elections next year
(link:/blog/authors/rtyler/[(rtyler)])
* Jenkins 2.0 proposal recap
(link:/blog/authors/rtyler/[(rtyler)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-11-11-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-11-11-19.01.log.html[raw]

[[GovernanceMeetingArchive2015-Oct28meeting]]
== Oct 28 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20151028T11&p1=224&ah=1&sort=1[Oct
28 11:00 Pacific].


*It is the end of daylight savings time season. The meeting will be held
at 11 am Pacific time, adjust accordingly.*

* Recap last meeting's actions
** https://wiki.jenkins.io/display/JENKINS/Rewards+for+reporting+security+issues[Rewards
for reporting security issues]
* LTS status check
* https://wiki.jenkins.io/display/JENKINS/Proposal+-+Revisiting+JUC+in+2016[Proposal
- Revisiting JUC in 2016]
(link:/blog/authors/kohsuke/[(kohsuke)])
* Sticker purchase approval
(link:/blog/authors/kohsuke/[(kohsuke)])
* Voting: Should we require squashing commits in the core?
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
** Related discussion:
https://groups.google.com/forum/#\!searchin/jenkinsci-dev/squash/jenkinsci-dev/kqvuDqXwPZw/oF-KMdNbCwAJ

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-10-28-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-10-28-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Oct14meeting]]
== Oct 14 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20151014T11&p1=224&ah=1&sort=1[Oct
14th 11:00 Pacific].

* Recap last meeting's actions
** https://wiki.jenkins.io/display/JENKINS/Approved+Trademark+Usage[Approved
Trademark Usage] has been updated.
* Quick announcement of `+#jenkins-community+`
(link:/blog/authors/rtyler/[(rtyler)])
* LTS status check
** https://github.com/jenkinsci/jenkins/pull/1812/files#diff-600376dffeb79835ede4a0b285078036R850[Link
to changelog-stable when building]?
* New Website JIRA project to organize website efforts under
(link:/blog/authors/rtyler/[(rtyler)])
* Approval of new Q4 patron messages by CloudBees
(link:/blog/authors/daniel-beck/[(danielbeck)])
* https://wiki.jenkins.io/display/JENKINS/Proposal+-+Project+sub-teams[Proposal
- Project sub-teams] (link:/blog/authors/rtyler/[(rtyler)])
* https://wiki.jenkins.io/display/JENKINS/Governance+Meeting+Archive+2015#[Permission
request] - Admin access to jenkinsci org
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
* JIRA project for plugin hosting (and possibly similar) requests
(link:/blog/authors/daniel-beck/[(danielbeck)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-10-14-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-10-14-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Sep30meeting]]
== Sep 30 meeting

*This is the first meeting to be held in #jenkins-meeting.*

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150930T11&p1=224&ah=1&sort=1[Sep
30th 11:00 Pacific].

* Recap last meeting's actions
* LTS status check
** No RC posted two weeks ago?
** https://issue-redirect.jenkins.io/issue/29876[JENKINS-29876]
* Q4
https://wiki.jenkins.io/display/JENKINS/Patron+of+Jenkins+program[patron
program] messages (link:/blog/authors/daniel-beck/[(danielbeck)])
** Same as for Q3, with same pre-approved message pending:
https://github.com/jenkinsci/patron/pull/4
* Time to think about Jenkins board elections?
link:/blog/authors/orrc[(orrc)]
** This was vaguely discussed in the 100k podcast in February, and soon
2/3 of the board will be CloudBees employees
** The most recent proposal seems to be
https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[proposal
from April 2013]
* Time to move to Java 8 and servlet 3.1?
(teilo) for core?

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-09-30-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2015/jenkins-meeting.2015-09-30-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Sep16meeting]]
== Sep 16 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150916T11&p1=224&ah=1&sort=1[Sep
16th 11:00 Pacific].

* Recap last meeting's actions
* LTS backporting status check
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Protect master branches of repositories
(link:/blog/authors/olivergondza[
(olivergondza)])
** https://groups.google.com/forum/#!topic/jenkinsci-dev/0ciUju7raOA[https://groups.google.com/forum/#!topic/jenkinsci-dev/0ciUju7raOA|https://groups.google.com/forum/#!topic/jenkinsci-dev/0ciUju7raOA]

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-16-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-16-18.02.log.html[raw]

[[GovernanceMeetingArchive2015-Sep2meeting]]
== Sep 2 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150902T11&p1=224&ah=1&sort=1[Sep
2nd 11:00 Pacific].

* Recap last meeting's actions
** Travel grant blog post:
http://jenkins-ci.org/content/announcing-travel-grant-program
** Botbot.me logging for #jenkins: https://botbot.me/freenode/jenkins/
** #jenkins-meeting: Waiting for
https://github.com/jenkins-infra/jenkins-infra/pull/152 to be merged
into prod
** Infra access list:
https://wiki.jenkins.io/display/JENKINS/Infrastructure+Admins[Infrastructure
Admins] (still missing Artifactory)
* LTS RC status check
(link:/blog/authors/daniel-beck/[(danielbeck)])
* LTS baseline selection
(link:/blog/authors/daniel-beck/[(danielbeck)])
* https://wiki.jenkins-ci.org/display/JENKINS/Travel+Grant+Program[Travel
grant program] blessing
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Process for merging PRs with multiple commits
(link:/blog/authors/daniel-beck/[(danielbeck)]
but it was really (integer) and (tfennelly) who brought it up)
* Clarification what requires a CLA and what does not
(link:/blog/authors/daniel-beck/[(danielbeck)])
* CERT Team membership request for
link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)],
(vlatombe) and
(varmenise) (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-02-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-09-02-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Aug19meeting]]
== Aug 19 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150819T11&p1=224&ah=1&sort=1[Aug
19th 11:00 Pacific].

* Recap last meeting's actions
** https://wiki.jenkins-ci.org/display/JENKINS/Travel+Grant+Program[Travel
grant program draft]
(link:/blog/authors/daniel-beck/[(danielbeck)])
* LTS RC status check / LTS baseline selection
(link:/blog/authors/daniel-beck/[(danielbeck)])
** What about
https://issue-redirect.jenkins.io/issue/29936[JENKINS-29936]?
* Revisiting bundled plugins
(link:/blog/authors/kohsuke/[(kohsuke)])
** See
https://groups.google.com/forum/#!topic/jenkinsci-dev/kRobm-cxFw8[mailing
list post]
* Allow file browsing in artifactory for ability view javadocs, add link
in confluence macros live link, send request to jfrog support to get
newer artifactory
version. (integer)
* Provide public list of JIRA/confluence/artifactory admins in wiki
(integer)]
* https://github.com/jenkinsci/jenkins/pull/1774[HTMLUnit update]
(link:/blog/authors/daniel-beck/[(danielbeck)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-08-19-18.03.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-08-19-18.03.log.html[raw]

[[GovernanceMeetingArchive2015-Aug5meeting]]
== Aug 5 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150805T11&p1=224&ah=1&sort=1[Aug
5th 11:00 Pacific].

* Recap last meeting's actions
* Jenkins certification
(link:/blog/authors/kohsuke/[(kohsuke)])
* Approval of new
https://wiki.jenkins-ci.org/display/JENKINS/Patron+of+Jenkins+program[Patron
program] messages (link:/blog/authors/daniel-beck/[(danielbeck)])
* JUC travel grant (link:/blog/authors/daniel-beck/[(danielbeck)])
** (http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-09-17-18.00.log.html[previous
discussion])
** The Jenkins project currently has
~http://permalink.gmane.org/gmane.org.spi.general/1507[$24k] in the bank

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-08-05-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-08-05-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Jul22meeting]]
== Jul 22 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=201507022T11&p1=224&ah=1&sort=1[Jul
22th 11:00 Pacific].

* LTS 1.609 RC status check
(link:/blog/authors/olivergondza[
(olivergondza)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-07-22-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-07-22-18.01.log.html[raw]

[[GovernanceMeetingArchive2015-Jul8meeting]]
== Jul 8 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150708T11&p1=224&ah=1&sort=1[Jul
8th 11:00 Pacific].

* Recap last meeting's actions
* LTS 1.609.2 RC status check
(link:/blog/authors/olivergondza[
(olivergondza)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-07-08-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-07-08-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-June10meeting]]
== June 10 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150610T11&p1=224&ah=1&sort=1[June
10th 11:00 Pacific].

* Recap last meeting's actions
* Can we start to look at fixing the
https://issues.jenkins.io/issues/?jql=project%20%3D%20INFRA%20AND%20component%20%3D%20spof%20ORDER%20BY%20updated%20DESC%2C%20priority%20DESC%2C%20created%20ASC[single
points of failure]? (link:/blog/authors/orrc[
(orrc)])
** e.g. https://issues.jenkins.io/browse/INFRA-225[INFRA-225] was
recently broken for a month; related
https://issues.jenkins.io/browse/INFRA-75[INFRA-75] is one year old
* Using labels for pull requests to core (instead of renaming to
something like "[WIP] [JENKINS-12345] Foo").
(link:/blog/authors/daniel-beck/[(danielbeck)])
* "Action items are https://issues.jenkins.io/browse/MEETING[tracked
in JIRA]" — can we agree to do this?
(link:/blog/authors/orrc[(orrc)])
** People miss meetings or forget action items, and there's usually no
follow-up and the actions never get done
* Time to move to Servlet 3.0 (3.1?) as
http://jenkins-ci.org/content/good-bye-java6[announced]?
(teilo)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-06-10-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-06-10-18.01.log.html[raw]

[[GovernanceMeetingArchive2015-May27meeting]]
== May 27 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150527T11&p1=224&ah=1&sort=1[May
27th 11:00 Pacific].

* Recap last meeting's actions
* LTS RC status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* When to flip the switch on
https://github.com/jenkinsci/backend-update-center2/pull/20[plugins
without wiki pages]? (link:/blog/authors/orrc[
(orrc)])
** https://groups.google.com/forum/#!msg/jenkinsci-dev/dfvRxvCv7Mg/jIailHDwY2EJ[Mailing
list thread]
* Can we start to look at fixing the
https://issues.jenkins.io/issues/?jql=project%20%3D%20INFRA%20AND%20component%20%3D%20spof%20ORDER%20BY%20updated%20DESC%2C%20priority%20DESC%2C%20created%20ASC[single
points of failure]? (link:/blog/authors/orrc[
(orrc)])
** e.g. https://issues.jenkins.io/browse/INFRA-225[INFRA-225] is
currently (again) a visible problem; related
https://issues.jenkins.io/browse/INFRA-75[INFRA-75] is one year old
today

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-05-27-18.19.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-05-27-18.19.log.html[raw]

[[GovernanceMeetingArchive2015-May13meeting]]
== May 13 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150513T11&p1=224&ah=1&sort=1[May
13th 11:00 Pacific].

* Recap last meeting's actions
* LTS RC status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* #jenkins-meeting (link:/blog/authors/daniel-beck/[(danielbeck)])
* Should we only include plugins in the Update Centre if they have a
wiki page? (link:/blog/authors/orrc[(orrc)],
(evernat)
** https://groups.google.com/forum/#!msg/jenkinsci-dev/oEHEjKo08yA/_z2GEtcUfz0J[ML
discussion];
https://groups.google.com/forum/#!msg/jenkinsci-dev/oEHEjKo08yA/S_uQ_C_7NMQJ[more
details]
** 47+ POMs have no `+url+` value, or a value with typos (which we can
https://github.com/jenkinsci/backend-update-center2/pull/14/files[override]
for now)
** 60+ plugins https://gist.github.com/orrc/2995a31028a27f9765d1[have no
wiki page at all] (not including workflow-*)
** 20+ plugins have no source code in github.com/jenkinsci (or at all);
at least 1 is closed-source
(http://maven.jenkins-ci.org/content/repositories/releases/com/antelink/reporter/jenkins/plugin/AntepediaReporter-CI-plugin/1.8/AntepediaReporter-CI-plugin-1.8.pom[private
repo, Java source excluded from release]: AntepediaReporter — orrc
contacted them and they're considering open-sourcing)
* Infra training/handover/expansion? (Was mentioned a while back and
more recently, but can't find the link)
(link:/blog/authors/orrc[(orrc)])
* Using a CDN with HTTPS / removing need for mirrorbrain?
(link:/blog/authors/orrc[(orrc)])
** https://issues.jenkins.io/browse/INFRA-266?focusedCommentId=226524#comment-226524[Comments
on INFRA-266]
* Further requirements for plugins published in the community update
center (link:/blog/authors/daniel-beck/[
(danielbeck)])
** To allow review, inspection and collaboration:
*** Require a valid SCM URL for new plugin releases inside
@jenkinsci/svn.jenkins-ci.org (that must exist) – needs to handle
plugins not bundled with Gradle
** To protect users:
*** Require that the uploader of the binary is the same user who created
the tag (we have the data in LDAP, see jenkins-ci.org/account)
*** Remove the commit permissions from 'everyone', it's reckless

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-05-13-18.07.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-05-13-18.07.log.html[raw]

[[GovernanceMeetingArchive2015-Apr29meeting]]
== Apr 29 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150429T11&p1=224&ah=1&sort=1[Apr
29th 11:00 Pacific].

* Recap last meeting's actions
* Carryover from last meeting w.r.t. SECURITY bounties. Anything for
historical submitters? Who has the action item?
* Trademark usage approval for "CloudBees Jenkins Platform"
(link:/blog/authors/kohsuke/[(kohsuke)])
* We only allow OSS plugins to be distributed via the update center, but
what about closed source plugins which are documented on our wiki? (e.g.
https://wiki.jenkins.io/display/JENKINS/Governance+Meeting+Archive+2015#[CxSuite
Jenkins Plugin])
* Should we only include plugins in the Update Centre if they have a
wiki page? (link:/blog/authors/orrc[(orrc)])
** https://groups.google.com/forum/#!msg/jenkinsci-dev/oEHEjKo08yA/_z2GEtcUfz0J[ML
discussion]
* #jenkins-meeting (link:/blog/authors/daniel-beck/[(danielbeck)])
* LTS.next (link:/blog/authors/olivergondza[
(olivergondza)])
* Infra training? (Was mentioned a while back and more recently, but
can't find the link) (link:/blog/authors/orrc[
(orrc)])
* Using a CDN with HTTPS / removing need for mirrorbrain?
(link:/blog/authors/orrc[(orrc)])
** https://issues.jenkins.io/browse/INFRA-266?focusedCommentId=226524#comment-226524[Comments
on INFRA-266]

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-29-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-29-18.00.log.html[raw]

[[GovernanceMeetingArchive2015-Apr15meeting]]
== Apr 15 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150415T11&p1=224&ah=1&sort=1[Apr
15th 11:00 Pacific].

* Recap last meeting's actions
* Migrate Jenkins-on-Jenkins jobs onto jenkins.ci.cloudbees.com
(link:/blog/authors/rtyler/[(rtyler)])
* Carryover from last meeting w.r.t. SECURITY bounties. Anything for
historical submitters? Who has the action item?

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-15-18.05.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-15-18.05.log.html[raw]

[[GovernanceMeetingArchive2015-Apr1meeting]]
== Apr 1 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150401T11&p1=224&ah=1&sort=1[Apr
1st 11:00 Pacific].


It's DST change season: Make sure you're not
https://en.wikipedia.org/wiki/Off-by-one_error[off by one] (hour)!

* Recap last meeting's actions
* JUC 2015 - obtain approval for a Mobile Morning mini-track that focus
on Jenkins mobile development (Alyssa)
* Build/publisher steps & AbortException
handling (integer)
** https://github.com/jenkinsci/jenkins/pull/1577
* Defining guidelines on expected behavior and/or structure for plugins?
If so, should we enforce them?
(link:/blog/authors/daniel-beck/[(danielbeck)])
** https://groups.google.com/d/msg/jenkinsci-dev/OHjuxTD1W9k/d4dRBtR_vFQJ
** http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-10-01-18.01.html
Item 3
** http://meetings.jenkins-ci.org/jenkins/2014/jenkins.2014-10-15-18.02.html
Item 3
* Would changing the meeting time to 10 AM PST/PDT allow overruns?
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Who gets voice on IRC? "Committers"... to any plugin? To core?
(link:/blog/authors/daniel-beck/[(danielbeck)])
* https://issue-redirect.jenkins.io/issue/27268[JENKINS-27268]
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Bug bounties/rewards for security issues?
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Resurrecting the MEETING Jira project (maybe even have the bot create
issues for action items automatically)
(link:/blog/authors/daniel-beck/[(danielbeck)])
* The important content of the Wiki is difficult to find (between
outdated or even empty pages), and there's no real introduction to
Jenkins – What can we do about it?
(link:/blog/authors/daniel-beck/[(danielbeck)])
* Proposal: move Jenkins
https://github.com/cloudbees/jenkins-ci.org-docker[official image
repo] to jenkinsci org so enhancement / version updates can be managed
by the community (link:/blog/authors/ndeloof[
(ndeloof)])
* Disabling "Clone" feature in JIRA
(link:/blog/authors/daniel-beck/[(danielbeck)])
* The Chinese mirror is a mess
(link:/blog/authors/daniel-beck/[(danielbeck)])
** http://mirrors.jenkins-ci.org/status.html
** https://issues.jenkins.io/browse/INFRA-260

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-01-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-04-01-18.02.log.html[raw]

[[GovernanceMeetingArchive2015-Mar18meeting]]
== Mar 18 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150318T11&p1=224&ah=1&sort=1[Mar
18th 11:00 Pacific].

Canceled.

[[GovernanceMeetingArchive2015-Mar4meeting]]
== Mar 4 meeting

WHEN
https://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150304T11&p1=224&ah=1&sort=1[Mar
4th 11:00 Pacific].

* LTS RC status check
* Recap last meeting's actions
* Are there new "Patron of Jenkins" sponsors? No messages have been
shown in 2015. (link:/blog/authors/orrc[
(orrc)])
** Maybe there was supposed to be one in Q1?
https://groups.google.com/forum/#!topic/jenkinsci-patrons/GQZwr5tQMyQ[https://groups.google.com/forum/#!topic/jenkinsci-patrons/GQZwr5tQMyQ|https://groups.google.com/forum/#!topic/jenkinsci-patrons/GQZwr5tQMyQ]
** Also, the wiki states that
"https://wiki.jenkins-ci.org/display/JENKINS/Patron+of+Jenkins+program[the
program will be reviewed and changes might be made]" in March 2015
* Workflow specific mailing lists
(https://wiki.jenkins-ci.org/display/~dty[Dean Yu])
* New release process? (i.e. release from master; no more RC branch)
(discussed by link:/blog/authors/kohsuke/[
(kohsuke)], link:/blog/authors/jglick[
(jglick)] & link:/blog/authors/daniel-beck/[
(danielbeck)] in IRC)
* Governance Document Updates
(link:/blog/authors/orrc[(orrc)])
** As per the Jenkins 100K podcast, we now have a trademark?
** More information about the board; there appears to be no information
about _who_ that is, how to "contact the board", and if/when the board
changes (see also: the podcast)
** Release process needs updating, if we decide to kill off RCs
** Broken or no-longer-updated links, e.g. Sun coding style, GitHub repo
wiki page, pull request wiki page
** Other stuff we want to review, that's changed in the past three
years? e.g. at least simple text updates like "500+ repos" is now
"1000+"...
* Build/publisher steps & AbortException
handling (integer)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-03-04-19.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-03-04-19.00.log.html[raw]

[[GovernanceMeetingArchive2015-Feb18meeting]]
== Feb 18 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150218T11&p1=224&ah=1&sort=1[Feb
18th 11:00 Pacific].

* Approving another batch of stickers
(link:/blog/authors/kohsuke/[(kohsuke)])
* https://groups.google.com/forum/?hl=en#!topic/jenkinsci-dev/oDXLTVcy56Y[IDEA
licenses] (integer)
* Should we have an "ops lead"? Adding more infra team members?
Moderator teams?
https://groups.google.com/forum/#!topic/jenkinsci-dev/046RwHh3Nko[mailing
list discussion] (link:/blog/authors/orrc[
(orrc)])
* Who should we reach out for JUC speakers?
(link:/blog/authors/kohsuke/[(kohsuke)])
* LTS status check (link:/blog/authors/kohsuke/[(kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-02-18-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-02-18-19.01.log.html[raw]

[[GovernanceMeetingArchive2015-Feb4meeting]]
== Feb 4 meeting

WHEN
http://www.timeanddate.com/worldclock/fixedtime.html?msg=Jenkins+Governance+Meeting&iso=20150204T11&p1=224&ah=1&sort=1[Feb
4th 11:00 Pacific].

* Jenkins 100K PR planning (hgilmore)
* LTS RC status (link:/blog/authors/kohsuke/[
(kohsuke)]/https://wiki.jenkins.io/display/JENKINS/Governance+Meeting+Archive+2015#[~ogondza])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-02-04-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-02-04-19.01.log.html[raw]

[[GovernanceMeetingArchive2015-Jan21meeting]]
== Jan 21 meeting

* Releases of Windows libraries: winp and winsw
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
** winp: https://github.com/kohsuke/winp/pull/12 - option to disable the
DLL unpacking
** winsw:
https://issue-redirect.jenkins.io/issue/10547[JENKINS-10547],
https://issue-redirect.jenkins.io/issue/22685[JENKINS-22685]
correct properties handling, log rotation fix
** A decision on MVS version would be useful for both projects. Proposed
version - *Visual Studio Community 2013* (free for FOSS projects)
* Jenkins at 100K active users (Heidi Gilmore)
* INFRA (integer)

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-01-21-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-01-21-19.01.log.html[raw]

[[GovernanceMeetingArchive2015-Jan7meeting]]
== Jan 7 meeting

* JUC post-mortem (link:/blog/authors/alyssat[
(atong)]/link:/blog/authors/kohsuke/[
(kohsuke)])

MINUTES
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-01-07-19.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-01-07-19.01.log.html[raw]
