---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2017"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingArchive2017-December20thmeeting]]
== [line-through]*December 20th meeting*

[line-through]**https://groups.google.com/d/msg/jenkinsci-dev/LmzleFNKecY/IBokx8ZwCAAJ[Skipped
due to lack of agenda items and revised LTS schedule.]**

[line-through]*WHEN: December 20th 18:00 UTC*

* [line-through]*Recap last meeting's actions*
* [line-through]*No LTS status check due to holiday schedule change*

[[GovernanceMeetingArchive2017-December6thmeeting]]
== December 6th meeting

WHEN: December 6th 18:00 UTC

* Recap last meeting's actions
* LTS status check

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-12-06-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-12-06-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-November22ndmeeting]]
== November 22nd meeting

WHEN: November 22nd 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])
* Planned release schedule for holiday season (topic for discussion
proposed by (andresrc)

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-11-22-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-11-22-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-November8thmeeting]]
== November 8th meeting

Note that the meeting time is in UTC, due to daylight savings time the
start time for you may have changed recently.

WHEN November 8th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])
* LTS baseline selection
* Jenkins Enhancement Proposals
(https://github.com/jenkinsci/jep/tree/jep-1/jep/1[JEP-1])
( link:/blog/authors/rtyler/[
(rtyler)] and link:/blog/authors/lnewman[
(bitwiseman)] )

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-11-08-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-11-08-18.00.log.html[raw]

 

[[GovernanceMeetingArchive2017-October25thmeeting]]
== October 25th meeting

WHEN October 25th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])
* Q4 patron messages (Daniel) +


MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-10-25-17.59.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-10-25-17.59.log.html[raw]

 

[[GovernanceMeetingArchive2017-October11thmeeting]]
== October 11th meeting

WHEN October 11th 18:00 UTC

 

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-10-11-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-10-11-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-September27thmeeting]]
== September 27th meeting

WHEN September 27th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])
* Huayou Tech request for mark usage for events "Jenkins User Conference
China" (Forest Jing)

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-09-27-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-09-27-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-September13thmeeting]]
== September 13th meeting

WHEN September 13th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)])
* CloudBees request for mark usage for events  “Jenkins Days by
CloudBees” (https://github.com/alyssat[Alyssa Tong])
* TechMatrix request for mark usage for events "Jenkins Day Japan"
(Kohsuke)
* Introduction to Forest Jing - JAM Shanghai & Beijing organizer  +


MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-09-13-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-09-13-18.00.log.html[raw]

 

[[GovernanceMeetingArchive2017-August16thmeeting]]
== August 16th meeting

WHEN August 16th 18:00 UTC

* Recap last meeting's actions
* [line-through]*LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] will not make it to the meeting)*
* next LTS baseline selection
(link:/blog/authors/jglick[(jglick)])
* Vote on proposal:[.F0XO1GC-mb-Y]# Add optional "Released as" and
"Stage Release" states to JIRA#
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
** JIRA ticket:
https://issues.jenkins.io/browse/INFRA-1301[INFRA-1301]

** https://groups.google.com/forum/#%21topic/jenkinsci-dev/wzc4VLplHvs[https://groups.google.com/forum/#!topic/jenkinsci-dev/wzc4VLplHvs]
** Proposal Text with
Edits: https://docs.google.com/document/d/1EIRuCMOjmPgpxybkWRPHfx1f1yglcuYlqPWN8K1Ni28/edit?usp=sharing

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-08-16-17.59.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-08-16-17.59.log.html[raw]

[[GovernanceMeetingArchive2017-August2meeting]]
== August 2 meeting

WHEN August 2nd 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )
* Jenkins World organization update (https://github.com/alyssat[Alyssa
Tong])
* Infra status update (link:/blog/authors/rtyler/[(rtyler)])
* https://groups.google.com/d/msg/jenkinsci-dev/PoxnVCKa9NM/2F2iLlDuBwAJ[Jenkins
mark usage request from CloudBees]
(link:/blog/authors/kohsuke/[(kohsuke)] but
 link:/blog/authors/rtyler/[(rtyler)] will
proxy)
* Deprecate Remoting CLI1/JNLP1/JNLP2/JNLP3 protocol - sign-off
https://issues.jenkins.io/browse/JENKINS-45841[JENKINS-45841]
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)]) +
** https://groups.google.com/forum/#!topic/jenkinsci-dev/sN2wHHFOJPg[Discussion
in the Mailing List] (see compatibility notes and the rollout plan)
** https://github.com/jenkinsci/jenkins/pull/2950[Main pull-request]

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-08-02-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-08-02-18.00.log.html[raw]

 

[[GovernanceMeetingArchive2017-July19meeting]]
== July 19 meeting

WHEN July 19th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )
* https://github.com/docker-library/docs/pull/948[Deprecate] "jenkins"
official docker image (that we don't control) and "jenkinsci/*" and
start deploying our own stuff under
"https://hub.docker.com/r/jenkins/[jenkins]/*" docker registry (ndeloof)

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-07-19-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-07-19-18.01.log.html[raw]

 

[[GovernanceMeetingArchive2017-July5meeting]]
== July 5 meeting

WHEN July 5th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-07-05-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-07-05-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-June21stmeeting]]
== June 21st meeting

WHEN June 21st 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-06-21-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-06-21-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-June7thmeeting]]
== June 7th meeting

WHEN June 7th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-06-07-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-06-07-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-May24thmeeting]]
== May 24th meeting

WHEN May 24th 18:00 UTC

* Recap last meeting's actions
* LTS status check
( link:/blog/authors/olivergondza[
(olivergondza)] )
** Next LTS baseline selection ([~olivergondza])
* Purchasing a SendGrid account to send project emails from Azure-based
applications - link:/blog/authors/rtyler/[
(rtyler)], link:/blog/authors/olblak[
(olblak)]
* Adding link:/blog/authors/olblak[
(olblak)] as an admin in LDAP and provide access to jenkins-keys
(provides puppet dashboard, account admin access, ability to encrypt
secrets, etc)

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-05-24-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-05-24-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-May10thmeeting]]
== May 10th meeting

WHEN: May 10th 18:00 UTC

* Recap last meeting's actions
* LTS status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* Infrastructure update (JIRA, Confluence, accounts, etc) (
link:/blog/authors/rtyler/[(rtyler)],
link:/blog/authors/olblak[(olblak)])

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-05-10-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-05-10-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-April26thmeeting]]
== April 26th meeting

WHEN: April 12th 18:00 UTC

* Recap last meeting's actions
* LTS status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* Jenkins Ambassador program heads up (https://github.com/alyssat[Alyssa
Tong])

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-04-26-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-04-26-18.01.log.html[raw]

 

[[GovernanceMeetingArchive2017-April12thmeeting]]
== April 12th meeting

WHEN: April 12th 18:00 UTC

* Recap last meeting's actions
* LTS status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* Google Groups issues (link:/blog/authors/rtyler/[(rtyler)])

 

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-04-12-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-04-12-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-March29meeting]]
== March 29 meeting

WHEN: March 29 18:00 UTC

* Recap last meeting's actions
* LTS Status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* Sublicense request, on behalf of JFrog, "Jenkins Community Day" event
in Paris (Alyssa Tong)
* Java 8 baseline bump heads up
(link:/blog/authors/batmat[(batmat)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-29-18.02.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-29-18.02.log.html[raw]

[[GovernanceMeetingArchive2017-March15meeting]]
== March 15 meeting

WHEN: March 15 18:00 UTC

* Recap last meeting's actions
* LTS Status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* The "Day of Jenkins" events (in
http://www.code-conf.com/doj/doj-gbg/[GOT] and
http://www.code-conf.com/doj/doj-osl/[OSL]) needs a sub license
(https://wiki.jenkins-ci.org/display/~lars_kruse[Lars Kruse])
* Obtain sub license for "DevOps Connect & Jenkins Days" events (Alyssa
Tong)

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-15-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-15-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-March1meeting]]
== March 1 meeting

WHEN: March 1 18:00 UTC

* Recap last meeting's actions
* LTS Status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* Pick new LTS line
(link:/blog/authors/olivergondza[
(olivergondza)])
** link:/changelog/[changelog]
* The future of the patron program
(link:/blog/authors/daniel-beck/[(danielbeck)])
** It doesn't make sense in its current form with the wiki slowly
getting replaced
** Do we want to just end it (for now), or implement e.g. on the site,
on JIRA, …?
* Obtain clearance on trademark usage "CloudBees Jenkins X" (Alyssa
Tong)
* GSoC 2017 update
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-01-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-03-01-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-Feb15meeting]]
== Feb 15 meeting

WHEN: Feb 15 18:00 UTC

* Recap last meeting's actions
* LTS Status check
(link:/blog/authors/olivergondza[
(olivergondza)])
* GSoC update (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)])
* Infrastructure update (link:/blog/authors/rtyler/[(rtyler)])
* Should we host plugins with closed-source dependencies?
(link:/blog/authors/batmat[(batmat)],
link:/blog/authors/orrc[(orrc)])
** link:/blog/authors/batmat[(batmat)]
brought up the point after
https://issues.jenkins.io/browse/HOSTING-271[HOSTING-271]
** Closed-source plugins are explicitly banned in the
https://wiki.jenkins.io/display/JENKINS/Governance+Document[Governance
Document] ("But no such [proprietary] plugins will be hosted by the
Jenkins project.") and on
https://wiki.jenkins.io/display/JENKINS/Hosting+Plugins[Hosting Plugins]
** Should we add a clarification that the source of all dependencies
(which implies transient?) must also be open source? Or are binary blobs
(so long as they're accessible) ok?

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-15-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-15-18.00.log.html[raw]

[[GovernanceMeetingArchive2017-Feb1meeting]]
== Feb 1 meeting

WHEN: Feb 01 18:00 UTC

* Recap last meeting's actions
* LTS Status check
* GSoC update
** https://groups.google.com/forum/#!topic/jenkinsci-dev/cPN7IZHGDWE[Status
update]
** https://docs.google.com/document/d/13mkt5DBjVAnr7dSiJ0oO4R5-nn80kGQ5OFhBoUzInIU/edit#heading=h.w10hxu7oxi77[Application
draf]
* Infrastructure update (link:/blog/authors/rtyler/[(rtyler)])
* https://groups.google.com/forum/#!topic/jenkinsci-dev/1jZmjgSDcqM[Trademark
usage approval] for upcoming "CloudBees Jenkins" product names
(link:/blog/authors/rtyler/[(rtyler)])
* Request for 50 private repos in the jenkinsci-cert GitHub org (1200
USD/year, up from 20 repos for 600 USD/year)
(link:/blog/authors/daniel-beck/[(danielbeck)])

Part 1:

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-01-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-01-18.00.log.html[raw]


Part 2:

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-01-18.27.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-02-01-18.27.log.html[raw]

[[GovernanceMeetingArchive2017-Jan18meeting]]
== Jan 18 meeting

WHEN Jan 18 18:00 UTC

* Recap last meeting's actions
* LTS status check
* Review GSoC project application status'
** https://groups.google.com/forum/#!topic/jenkinsci-dev/cPN7IZHGDWE[Status
update]
** https://docs.google.com/document/d/13mkt5DBjVAnr7dSiJ0oO4R5-nn80kGQ5OFhBoUzInIU/edit#heading=h.w10hxu7oxi77[Application
draf]
* Bug Triage Team Idea
(link:/blog/authors/slide_o_mix[
(slide_o_mix)])
* JDK8 baseline upgrade news
(link:/blog/authors/batmat[(batmat)])
** Jenkins https://github.com/jenkinsci/jenkins/pull/2698[core now
builds on Windows] and is green \o/ (err, blue)
** https://github.com/jenkins-infra/jenkins.io/pull/545[PR] for the
public announcement is up for review
* FOSDEM planning update

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-01-18-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-01-18-18.01.log.html[raw]

[[GovernanceMeetingArchive2017-Jan4meeting]]
== Jan 4 meeting

WHEN Jan 4 18:00 UTC

* Recap last meeting's actions
* LTS status check
** This should be quick as we postponed the .2 release
image:https://wiki.jenkins.io/s/en_GB/8100/5084f018d64a97dc638ca9a178856f851ea353ff/_/images/icons/emoticons/smile.svg[(smile)]

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-01-04-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2017/jenkins-meeting.2017-01-04-18.00.log.html[raw]
