---
layout: simplepage
title: "Jenkins Governance Meeting Archive 2019"
section: project
---

This page is an archive of past meeting agendas, their minutes and IRC logs, for the year shown above.
For current information, see the link:/project/governance-meeting[Governance Meeting] page.

[[GovernanceMeetingAgenda-November20]]
=== November 20

* LTS status check
* Event updates: FOSDEM, Jenkins World, etc.
* Trademark usage request: Jenkins Master Class (Parker Ennis)
** https://groups.google.com/forum/#!topic/jenkinsci-dev/Cq_NQwyLD5s
* Budget request: Hacktoberfest swag
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
** https://groups.google.com/forum/#!topic/jenkinsci-dev/k5KICbRDoz4
* Approving Browser Support Policy update
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
** https://groups.google.com/forum/#!topic/jenkinsci-dev/TV_pLEah9B4
** https://github.com/jenkins-infra/jenkins.io/pull/2659
* Approving the OS X packaging deprecation
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
** https://groups.google.com/forum/#!topic/jenkinsci-dev/xc-lDVsr0bQ

[[GovernanceMeetingAgenda-September25]]
=== September 25

* Last meeting actions
* Motions to vote on:
** Request for trademark approval to use the name "Jenkins Health
Advisor by CloudBees" instead of "CloudBees Jenkins Advisor".

[[GovernanceMeetingAgenda-September11]]
=== September 11

* Last meeting actions
* LTS status check
* Jenkins Board & Officer Elections 2019
(link:/blog/authors/tracymiranda[(tmiranda)])
** Dev list
thread: https://groups.google.com/d/msg/jenkinsci-dev/vKi9JpxTQxY/pBidPImHAQAJ
** Links:
*** https://wiki.jenkins.io/display/JENKINS/Board+Election+Process[Board
Election Process] (2015 base edition)
*** https://wiki.jenkins.io/display/JENKINS/Governance+Board[Governance
Board]
** Motions to vote on: +
*** All officer positions will be voted on in 2019
(https://wiki.jenkins.io/display/JENKINS/Team+Leads[Team Leads])
*** 3 Board positions instead of 2 in the proposal will be voted on in
2019 (Dean Yu's seat + 2 new seats). 2 will be voted on in 2020
*** CDF will supervise the election and run the voting
using https://civs.cs.cornell.edu/[The Condorcet Internet voting
system] instead
of https://en.wikipedia.org/wiki/Single_transferable_vote[Single
Transferable Vote]
*** The election cut-off date for valid jenkins.io accounts for the 2019
election is 1st September 2019
*** The proposed election schedule will start on 13 September 2019 and
conclude on 4 November 2019 with intermediate dates as per dev list
thread
*** Adding new officer role: Documentation officer (content officer from
the
2015 https://wiki.jenkins.io/display/JENKINS/Proposal+-+Project+sub-teams[Proposal
- Project sub-teams])
** Voting on a final proposal

[[GovernanceMeetingAgenda-August28]]
=== August 28

* Last meeting actions
* LTS status check

[[GovernanceMeetingAgenda-July31]]
=== July 31

* Weekly Release delay
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
* LTS status check
* GSoC update (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] )
** Part 1 demos: https://www.youtube.com/watch?v=tnoObQqGhyM
** Part 2 demos:  https://www.youtube.com/watch?v=HlENuZZq7zc
* GSoC budgeting (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] )
** Blanket approval for using GSoC budget for GSoC in 2019
*** https://groups.google.com/forum/#!topic/jenkinsci-dev/MaFMYoo8Nxg
*** https://github.com/jenkinsci/jep/tree/master/jep/8
** If not approved, Budget approvals for GSoC: Swag and Travel grants
(link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] link:/blog/authors/markjacksonfishing[(markyjackson5)] (deepchip)
*** Earmarking swag, swag shipping budget and community/contributors
poster
requests: https://groups.google.com/forum/#!topic/jenkinsci-dev/4OUrH562INQ
*** Dev list
thread: https://groups.google.com/forum/#!topic/jenkinsci-dev/4OUrH562INQ
* Budget approvals for the Community Bridge dry-run
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
** Dev List
thread: https://groups.google.com/forum/#!topic/jenkinsci-dev/ZyLV-FTPbcM
* SIG status reports
( link:/blog/authors/markewaite[
(markewaite)])
** Process change - use e-mail or blog posts for
https://github.com/jenkinsci/jep/tree/master/jep/4#specification[JEP-4
status reports]
** Platform SIG status
** Docs SIG status

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-07-31-18.01.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-07-31-18.01.log.html[raw]

[[GovernanceMeetingAgenda-June05]]
=== June 05

* Recap last meeting actions
* LTS status check
* GSoC update (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] )
* Platform SIG and Java 11 support status update
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
** https://github.com/jenkinsci/jep/tree/master/jep/211
* Introducing global configurations in jenkinsci GitHub org
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] )
** https://groups.google.com/forum/#!topic/jenkinsci-dev/dOs8YRQwQiI
* Docs SIG update ( link:/blog/authors/markewaite[(markewaite)])

[[GovernanceMeetingAgenda-May22]]
=== May 22

* Recap last meeting actions
* LTS status check
* Docs SIG update (link:/blog/authors/markewaite[(markewaite)])

[[GovernanceMeetingAgenda-May8]]
=== May 8

* Recap last meeting actions
* LTS status check
* LTS baseline selection
* GSoC Update (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] )
* Outreachy update (link:/blog/authors/tracymiranda[(tmiranda)])
* CDF update (link:/blog/authors/tracymiranda[(tmiranda)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-05-08-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-05-08-18.00.log.html[raw]

[[GovernanceMeetingAgenda-April24]]
=== April 24

* Recap last meeting actions
* LTS status check
* Google Summer of Code update (as needed)
* Google Season of Docs update
(link:/blog/authors/markewaite[(markewaite)]
)
* Outreachy update (link:/blog/authors/tracymiranda[(tmiranda)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-04-24-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-04-24-18.00.log.html[raw]

[[GovernanceMeetingAgenda-April10]]
=== April 10

* Recap last meeting actions
* LTS status check
* Outreachy update (link:/blog/authors/tracymiranda[(tmiranda)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-04-10-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-04-10-18.00.log.html[raw]

[[GovernanceMeetingAgenda-Mar27]]
=== Mar 27

* Recap last meeting actions
* LTS status checks
* Google Season of Docs discussion +

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-03-27-18.24.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-03-27-18.24.log.html[raw]

[[GovernanceMeetingAgenda-Feb13]]
=== Feb 13

* Recap last meeting actions
* LTS status check and baseline selection
* Java 11 Support Update && GA support in the new LTS baseline
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
* Outreachy update & next application period
(link:/blog/authors/tracymiranda[(tmiranda)])
** https://groups.google.com/d/msg/jenkinsci-dev/yaPrguId_sY/lSs7mHaxAAAJ
* GSoC update (link:/blog/authors/oleg_nenashev/[(oleg_nenashev)] )

Meeting bot was unavailable during the meeting, so minutes are here:
https://wiki.jenkins.io/display/JENKINS/Governance+Meeting+2019-02-13+Notes+and+Log[Governance
Meeting 2019-02-13 Notes and Log]

[[GovernanceMeetingAgenda-Jan30]]
=== [line-through]*Jan 30*

[line-through]*WHEN January 30, 18:00 UTC*

* [line-through]*Recap last meeting actions*

[[GovernanceMeetingAgenda-Jan16]]
=== Jan 16

WHEN January 16, 18:00 UTC

* Recap last meeting actions
* LTS status check
* Platform SIG status report - Java 11 and more
(link:/blog/authors/markewaite[(markewaite)])
* GSoC status report
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
* Status report: Advocacy and Outreach SIG
(link:/blog/authors/lnewman[
(bitwiseman)] or link:/blog/authors/oleg_nenashev/[(oleg_nenashev)])
** https://groups.google.com/forum/#!topic/jenkinsci-dev/84vjWz_Ho1k
* Update: Hardware&EDA and Embedded SIGs
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)])
** https://groups.google.com/forum/#!topic/jenkinsci-dev/a69DXm6qQms
* Request for https://github.com/LinuxSuRen[Rick] to be listed as
Jenkins press contact for China
(link:/blog/authors/tracymiranda[(tmiranda)])

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-01-16-18.00.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-01-16-18.00.log.html[raw]

[[GovernanceMeetingAgenda-Jan2]]
=== Jan 2

WHEN January 2, 18:00 UTC

* Recap last meeting actions
* LTS status check
* Jenkins GSoC: 500USD budget approval for swag
(link:/blog/authors/oleg_nenashev/[
(oleg_nenashev)] or link:/blog/authors/lloydchang[(lloydchang)] or [.fabric]#@deepchip#)
** https://groups.google.com/forum/#!topic/jenkinsci-dev/p_hRMKfQuJw

MINUTES
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-01-02-18.06.html[summary]
and
http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-01-02-18.06.log.html[raw]
