---
title: Web Framework
layout: developer
summary: How Jenkins uses the Stapler framework
---

== Request Handling

Jenkins classes are bound to URLs by using https://github.com/stapler[Stapler].
The singleton `jenkinsdoc:jenkins.model.Jenkins[]` instance is bound to the context root (most of the time "/") URL, and the rest of the objects are bound according to their reachability from this root object.
Stapler uses reflection to recursively determine how to process any given URL.
A few examples of how the URL `/foo/bar` could be processed:

* A `getFoo(String)` is defined on the `Jenkins` object, and Stapler passes `bar` as a parameter.
  The object returned has a method called `doIndex(…)` that gets called and renders the response.
* `getFoo()` is defined and returns an object that has a `getBar` or `doBar` method.
  The object returned from that has an associated `index.jelly` or `index.groovy` view.
* `getFoo()` is defined and the returned object has a view named `bar.jelly` or `bar.groovy` defined.
* `doFoo()` is defined.

As a real-world example, in `jenkinsdoc:jenkins.model.Jenkins#getItem(java.lang.String)[Jenkins#getItem(String)]` (or `jenkinsdoc:hudson.model.Hudson#getJob(java.lang.String)[Hudson#getJob(String)]`), the URL `/job/foo/` is bound to the object returned by `Jenkins.get().getItem("foo")`, which is typically a `jenkinsdoc:hudson.model.Project[Project]` named `foo`.

A number of additional ways to handle requests exist, but these are the most common.

Additionally, objects can implement interfaces to further control how Stapler processes URLs:

* `staplerdoc:org.kohsuke.stapler.StaplerProxy[]` allows delegating URL processing to another object. If a getter returns an object that implements `StaplerProxy`, Stapler calls `getTarget()` and continues processing the rest of the URL on that target. This has the *highest priority* among URL processing options.
* `staplerdoc:org.kohsuke.stapler.StaplerFallback[]` allows delegating URL processing to another object as a fallback when no standard routing match is found. This has the *lowest priority* among URL processing options.

link:/doc/developer/handling-requests/routing/[Learn more about routing requests in Jenkins.]

link:/doc/developer/handling-requests/[Learn more about request handling in Jenkins.]

== Views

Jenkins' model objects have multiple _views_ that are used to render HTML pages about each object.
Views are written in https://jakarta.apache.org/commons/jelly/[Jelly] or http://groovy-lang.org/[Groovy] and can be composed of a number of different partial views (or view fragments).

Views are like methods and each of them works against a particular class.
Views are organized in resource directories corresponding to the classes they belong to (e.g. under `src/main/resources/` mirroring the package and class name).
Just like methods are defined on classes, views are defined on model classes to render different representations (such as `index.jelly` for the main view or `configure.jelly` for the configuration page).

=== Tag Libraries

Jenkins defines several Jelly tag libraries to encourage views to have a consistent look and feel and shared structure:

* *Layout tags* define the basic page layout of Jenkins, including headers, navigation sidepanels, task links, and page footers.
* *Form tags* define form controls, input fields, and validation behaviors used in configuration pages.

See link:/doc/developer/development-environment/taglibs/[Taglibs] for references to the available Jelly tag libraries.

link:/doc/developer/views/[Learn more about views in Jenkins.]
