---
layout: sig
title: "Documentation"
section: sigs
sigId: "docs"
logo: /images/logos/needs-you/Jenkins_Needs_You-02.png
tags:
  - docs
  - docs_sig
  - docs-sig
  - documentation
leads:
- name: "Mark Waite"
  id: "markewaite"
  github: "markewaite"
  irc: "markewaite"
  twitter: "MarkEWaite"
participants:
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
  irc: "oleg_nenashev"
  twitter: "oleg_nenashev"
- name: "Tracy Miranda"
  id: "tracymiranda"
  github: "tracymiranda"
  irc: "tracymiranda"
  twitter: "tracymiranda"
- name: "Tammy Fox"
  id: "tfoxnc"
  github: "tfoxnc"
- name: "Kristin Whetstone"
  id: "kwhetstone"
  github: "kwhetstone"
  twitter: "lighteningdrake"
- name: "Radek Antoniuk"
  id: "warden"
  github: "warden"
  irc: "warden"
- name: "John Ha"
  id: "jha-cloudbees"
  github: "jha-cloudbees"
- name: "Petra Sargent"
  id: "petra-sargent"
  github: "petra-sargent"
  twitter: "momsthatcode"
- name: "Owen Mehegan"
  id: "omehegan"
  github: "omehegan"
  twitter: "literatesavant"
- name: "Meg McRoberts"
  id: "stackscribe"
  github: "stackscribe"
- name: "Zhao Xiaojie (Rick)"
  id: "surenpi"
  github: "LinuxSuRen"
links:
  gitter: "jenkinsci/docs"
  googlegroup: "jenkinsci-docs"
  meetings: "https://docs.google.com/document/d/1uNNo0QJKPHnNp8PGr_jLI8p3K_94ZYD-M0evZOEZ93c/edit#"
overview: >
  This special interest group improves Jenkins use and adoption through documentation.
  The SIG encourages, creates, and reviews documentation contributions and improves documentation with contributors and external communities.
---

The SIG offers a venue for all kinds of documentation creation, improvement, and delivery.

The group focuses on documentation for Jenkins and Jenkins X, including:

* link:/doc/[User documentation] - Using Jenkins
** link:/doc/tutorials[Tutorials]
** link:/doc/book/[User Handbook]
** References like link:/doc/book/pipeline/syntax/[Pipeline Syntax] and link:/doc/pipeline/steps/[Pipeline Steps]
** How-to Guides
* link:/doc/developer/[Extension documentation] - Extending Jenkins
** link:/doc/developer/tutorial/[Tutorials]
** link:/doc/developer/book/[Developer Reference]
** link:/doc/developer/guides/[How-To Guides]
* Solution documentation - Specific Solutions with Jenkins
** Language solutions like link:/solutions/c/[C/C++], link:/solutions/java/[Java], link:/solutions/php/[PHP], link:/solutions/python/[Python], and link:/solutions/c/[Ruby]
** Platform solutions like link:/solutions/android/[Android], link:/solutions/docker[Docker], and link:/solutions/embedded[Embedded]
** Implementation solutions like link:/solutions/pipeline[Pipeline]

Documentation SIG may cooperate with other groups.
For example, we will be cooperating with the link:/sigs/cloud-native[Cloud-Native Jenkins SIG]
on topics related to Cloud-Native documentation efforts and
with the link:/sigs/platform[Platform SIG].
on platform topics.

=== Topics

* Creating new documentation
* Improving existing documentation
* Reviewing documentation contributions
* Coordinating documentation initiatives
* Reviewing Jenkins Enhancement Proposals (JEPs) related to documentation

=== Ongoing projects

* Reviewing Jenkins documentation link:https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=18640[bug reports]
* Identifying link:https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20%22Jenkins%20Website%22%20and%20status%20!%3D%20done%20and%20labels%20%3D%20newbie-friendly%20ORDER%20BY%20%20%20type%20asc%2C%20status%2C%20updatedDate[newbie-friendly documentation bug reports]
* Reviewing Jenkins documentation link:https://github.com/jenkins-infra/jenkins.io/pulls[pull requests]
* Reviewing Jenkins X documentation link:https://github.com/jenkins-x/jx-docs/pulls[pull requests]
* link:https://plugins.jenkins.io/[Plugins site] improvements

See the link:https://docs.google.com/document/d/1uNNo0QJKPHnNp8PGr_jLI8p3K_94ZYD-M0evZOEZ93c/edit?usp=sharing[SIG meeting notes] for more information about ongoing projects.

=== Meetings

We have regular meetings on Fridays every two weeks, at *1PM UTC*.
See the link:/event-calendar/[Jenkins Event Calendar] for the schedule.
At these meetings we discuss projects and do presentations/demos.
You can find and contribute to the agenda for the incoming meetings
link:https://docs.google.com/document/d/1uNNo0QJKPHnNp8PGr_jLI8p3K_94ZYD-M0evZOEZ93c/edit?usp=sharing[here].

Meetings are conducted and recorded using Zoom.
Participant links are posted in the link:https://gitter.im/jenkinsci/docs[SIG Gitter Chat] 10 minutes before the meeting starts.

==== 2019-05-10

Initial organizing meeting

* link:https://docs.google.com/document/d/1uNNo0QJKPHnNp8PGr_jLI8p3K_94ZYD-M0evZOEZ93c/edit#heading=h.g4afeqolzwpj[Meeting notes]
* Youtube recording to be added later
