---
title: How to use the Jenkins Security Scan
layout: developer
references:
- title: Introductory blog post (2020)
  url: https://www.jenkins.io/blog/2020/11/04/codeql/
- title: GitHub CodeQL Repository
  url: https://github.com/github/codeql
- title: Jenkins CodeQL Repository
  url: https://github.com/jenkins-infra/jenkins-codeql
- title: Jenkins Security Scan Repository
  url: https://github.com/jenkins-infra/jenkins-security-scan
---

== Motivation

Jenkins uses the https://github.com/jenkinsci/stapler[Stapler web framework], instead of a more common framework.
As a result, generic static analysis tools are often unable to find common vulnerabilities in Jenkins core and plugins.

The link:/security/team/[Jenkins security team] created custom code scanning rules built with GitHub's https://github.com/github/codeql[CodeQL].
They are capable of finding vulnerabilities common in Jenkins plugins.

This page explains how to set up code scanning with these rules.
This can be accomplished in multiple ways:

* Use the reusable Jenkins Security Scan workflow.
  This requires less configuration but is less flexible.
* Use the CodeQL security scanning workflow and add the Jenkins-specific rules.
  This requires more configuration, but is more flexible.
* Use the 

See the instructions below for further instructions.

== Jenkins Security Scan workflow

=== Usage in a Jenkins project-hosted plugin

In your GitHub repository, select the "Actions" link on top.
If you already have some workflows in your repository, click "New Workflow".
In the section "By Jenkins", select "Jenkins Security Scan".

Configure the YAML workflow file in your repository.
You can use it without changes.
We recommend committing to the default branch instead of adding this file via a pull request.
This way, the code scanning findings will not be visible in a pull request check.
Once saved, you should be able to see findings for branches in the "Security" tab under "Code scanning alerts".
Pull requests will have a new check that shows findings added in it.

////
TODO Decide whether we want to continue to support this.
== Usage in a Jenkins project-hosted plugin (GitHub topic)

Add the topic `jenkins-security-scan-enabled` to your repository.
Within 24 hours, the first code scanning results should appear.
Unlike the GitHub Action, feedback is not immediate, as scans are only running periodically.
////

=== Usage outside the Jenkins project

You can use the same GitHub workflow in your Jenkins plugin project as long as it's hosted on GitHub.
Copy the https://github.com/jenkinsci/.github/blob/master/workflow-templates/jenkins-security-scan.yaml[YAML workflow template] into your repository's `.github/workflows` directory.
You need to replace the `$default-branch` placeholder as appropriate.

[NOTE]
====
Your repository needs to be public or you need https://docs.github.com/en/get-started/learning-about-github/about-github-advanced-security[GitHub Advanced Security].
Uploading the report will fail with an error otherwise:

> `Error: Advanced Security must be enabled for this repository to use code scanning.`

This happens for private repositories that do not have GitHub Advanced Security enabled.
Review _Settings » Security » Code security and analysis » GitHub Advanced Security_ in your repository and ensure that it is enabled.
This section of the configuration is only visible if you have an appropriate GitHub paid plan.
====

=== Common problems

Rate limiting::
The scan fails to execute with the following error message:
+
> `Called workflows cannot be queued onto self-hosted runners across organisations/enterprises. Failed to queue this job. Labels: 'ubuntu-latest'.`
+
As of March 2022, https://github.community/t/called-workflows-cannot-be-queued-onto-self-hosted-runners-across-organisations-enterprises-failed-to-queue-this-job-labels-ubuntu-latest/229355/10[GitHub seems to rate limit actions].
If this error message appears, you are being rate-limited.
You can manually restart the scan.
Action permissions::
+
The workflow has a _startup failure_ with an error message like this:
+
> `jenkins-infra/fetch-codeql-action@v1 is not allowed to be used in jenkinsci/your-plugin.`
+
In cases of errors like this, review _Settings » Code and automation » Actions » General » Action permissions_ in your repository.
Select either _Allow all actions and workflows_ or _Allow jenkinsci, and select non-jenkinsci, actions and workflows_.
If you select the latter, add `jenkins-infra/*` to the list of specified actions and workflows being allowed.
Workflow permissions::
+
The workflow has a _startup failure_ with an error message like this:
+
> `The workflow is not valid. .github/workflows/jenkins-security-scan.yml (Line: 11, Col: 3): Error calling workflow 'jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2'. The workflow 'jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v2' is requesting 'actions: read, security_events: write', but is only allowed 'actions: none, security_events: none'.`
+
This can happen if your repository is configured to limit workflow permissions to read-only access by default, and you're using an older version of the workflow that does not declare the permissions it requires.
Compare with the https://github.com/jenkinsci/.github/blob/master/workflow-templates/jenkins-security-scan.yaml[template file] and ensure you have the same `permissions` element in your workflow.
Error in Dependabot commits::
+
The _Upload Scan Results_ step in the workflow fails with the error:
+
> `Error: Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events.`
+
You're using an older version of the workflow that does not declare the permissions it requires.
Compare with the https://github.com/jenkinsci/.github/blob/master/workflow-templates/jenkins-security-scan.yaml[template file] and ensure you have the same `permissions` element in your workflow (https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#changing-github_token-permissions[see documentation]).
Pull request check is unexpectedly successful::
+
The _Jenkins Security Scan_ check is successful even though the pull request introduces new issues.
+
Only some findings mark the check as failed.
The behavior can be customized in the repository configuration.
Go to _Settings » Security » Code security and analysis » Code scanning » Check Failure_ and select the behavior you want.

== Usage within CodeQL workflow

In your GitHub repository, select the "Security" link on top and select "Code scanning" on the left.
// TODO This UI might change some over time, so this is potentially awkward to describe in detail.
If no tool has been set up so far, select "Configure scanning tool" and choose the advanced setup, otherwise select "Add tool".

These instructions have been written for a base workflow that contains the steps `actions/checkout@v3`, `github/codeql-action/init@v2`, `github/codeql-action/autobuild@v2`, and `github/codeql-action/analyze@v2`.
To add the Jenkins-specific rules, you need to change the configuration of `github/codeql-action/init@v2` as follows:


[source,diff]
----
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -53,6 +52,12 @@ jobs:
       uses: github/codeql-action/init@v2
       with:
         languages: ${{ matrix.language }}
+        config: |
+          disable-default-queries: true // <1>
+          packs:
+          - jenkins-infra/jenkins-codeql // <2>
+          - codeql/java-queries:AlertSuppression.ql // <3>
+          - codeql/java-queries:AlertSuppressionAnnotations.ql // <4>
----
<1> Optionally disable the generic Java CodeQL security scanning rules. Generally only recommended if there's another general-purpose security scanner set up.
<2> This directive adds the Jenkins-specific queries.
<3> Optionally add support for programmatic alert suppression using source code comments as an alternative to dismiss findings through the GitHub UI.
<4> Optionally add support for programmatic alert suppression using source code annotations as an alternative to dismiss findings through the GitHub UI.

The CodeQL UI on GitHub does not support alert suppression through source code comments or annotations, see https://github.com/github/codeql/issues/11427[github/codeql#11427].
In addition to the official option https://github.com/advanced-security/dismiss-alerts/[advanced-security/dismiss-alert], it's also possible to suppress alerts by stripping them from the code scanning results before uploading.
To do that, a change like the following is also needed:

[source,diff]
----
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -80,3 +85,9 @@ jobs:
       uses: github/codeql-action/analyze@v2
       with:
         category: "/language:${{matrix.language}}"
+        upload: failure-only // <1>
+    - name: Remove Suppressed Alerts // <2>
+      uses: daniel-beck-org/remove-suppressed-findings-action@main
+    - name: Upload CodeQL Result // <3>
+      uses: github/codeql-action/upload-sarif@v2
----
<1> Instruct `github/codeql-action/analyze@v2` to not upload the report unless an error occurred.
<2> This action strips all suppressed findings from the code scanning result.
<3> Upload the code scanning result.
// TODO Publish daniel-beck-org/remove-suppressed-findings-action in jenkins-infra

NOTE: As a side effect, the GitHub UI will never show alerts that have been suppressed in code (unlike those marked as ignored on GitHub).
This may make it more cumbersome to review existing suppressions.

=== Standalone use

CodeQL with the Jenkins-specific rules can be run as part of a Jenkins pipeline and can upload the scan results to GitHub.

The CodeQL CLI can be downloaded from https://github.com/github/codeql-cli-binaries[its GitHub repository].

The following shell script creates a database by running the specified build command, analyzes the database with the specified queries only, and then uploads the results, excluding any suppressed findings, to GitHub.

[source,bash]
----
#!/usr/bin/env bash
set -e errexit
set -e nounset
set -e pipefail
[[ -v "GITHUB_TOKEN" ]] || { echo "GITHUB_TOKEN is undefined. " ; exit 1 ; } // <1>
[[ -v "GH_REPO" ]] || { echo "GH_REPO is undefined" ; exit 1 ; } // <2>
[[ -v "GH_REF" ]] || { echo "GH_REF is undefined." ; exit 1 ; } // <3>
[[ -v "GH_SHA" ]] || { echo "GH_SHA is undefined." ; exit 1 ; } // <4>
for TOOL in codeql jq mvn ; do
    which "$TOOL" >/dev/null || { echo "$TOOL not found on PATH" ; exit 1 ; }
done
codeql database create ./codeql-java-database \
  --language=java \
  --command='mvn clean verify -Pquick-build' // <5>
codeql database analyze ./codeql-java-database \
  --sarif-add-query-help \
  --format=sarif-latest \
  --output=./result.sarif \
  --download \
  jenkins-infra/jenkins-codeql \
  codeql/java-queries:AlertSuppression.ql \
  codeql/java-queries:AlertSuppressionAnnotations.ql \
  || { echo "Failed to analyze database" ; exit 1 ; }
jq 'del(.runs[].results[] | select( .suppressions | length != 0 ))' \
  ./result.sarif > ./result-filtered.sarif // <6>
codeql github upload-results \
  --repository="$GH_REPO" \
  --ref="$GH_REF" --commit="$GH_SHA" \
  --sarif=./result-filtered.sarif
----
<1> `GITHUB_TOKEN` is used by `codeql github upload`. Alternatively, a token can be passed into standard input with `--github-auth-` argument.
<2> `GH_REPO` must be in the format `owner/repo` (e.g., `jenkinsci/matrix-auth-plugin`).
<3> `GH_REF` must be in the format `refs/heads/branchname` (e.g., `refs/heads/develop`, when analyzing a branch) or `refs/pull/1234/head` (when analyzing a pull request's HEAD commit).
<4> `GH_SHA` is the SHA-1 of the analyzed commit.
<5> Optionally, `--command` specifies how the Jenkins component is built. This is useful if a custom build command should be used.
<6> Optionally, this invocation of `jq` removes all results from the report that have suppressions applied (through comments or annotations).

== Feedback and Contributing

The custom GitHub workflow is hosted in https://github.com/jenkins-infra/jenkins-security-scan[`jenkins-infra/jenkins-security-scan`], alongside the wrapper script that invokes the CodeQL CLI.
Please file an issue there to provide feedback for the workflow and its use of actions.

To provide feedback about the findings, please file an issue in https://github.com/jenkins-infra/jenkins-codeql[`jenkins-infra/jenkins-codeql`].
Improvements to the code scanning rules are also welcome.
