---
layout: simplepage
title:  Trademark and Attribution
section: project
---

The name "Jenkins" is a registered trademark in the USA
(link:https://trademarks.justia.com/854/47/jenkins-85447465.html[#4664929],
held by
link:https://spi-inc.org[Software in the Public Interest, Inc.])
in order to protect the project and users from confusing use of the term. To
reduce the process overhead and uphold our open-source spirit, we adopt the
Linux kernel policy on trademark usage.

You need to apply for a link:sublicense[sublicense] if you are using the term "Jenkins" as part of your own trademark or brand identifier for Jenkins-based software goods or services. It doesn’t matter if your trademark is unregistered, or if you do not plan to make any money using the mark.

Answering the following questions (which break out each of the key issues) may help you determine if you need a sublicense. If you are still in doubt, please contact the board and we will work with you to determine whether you need to apply for a sublicense.

If the answer to all three of the following questions is "yes," then you need to apply for a sublicense. If the answer to any of these questions is "no," then you do not need to apply for a sublicense.

- Is my mark a trademark (see how the Linux Foundation defines "trademark" in link:https://www.linuxfoundation.org/programs/legal/trademark/faq[FAQ])?
- Does my mark contain the following string of adjacent letters, in this order: "Jenkins"? These letters may or may not be capitalized, and in the case of foreign characters, phonetic translations also apply.
- Do I use my mark to identify software-related goods or services (see how that phrase is link:https://www.linuxfoundation.org/programs/legal/trademark/faq[defined] again in LF)?

A list of trademark usages approved by the project can be found on the link:approved-usage[Approved Trademark Usage] page.


=== Trademark Attribution

These trademark attribution guidelines are largely derived from the Linux Foundation's
link:https://lmi.linuxfoundation.org/programs/legal/trademark/attribution[trademark attribution]
guidelines.

==== Attribution is For Everyone

Even if your use of the Jenkins trademark doesn't fall under the scope of the
Jenkins Sublicense Agreement, you should still attribute ownership of the mark to
Software in the Public Interest, Inc. in two ways:

1. For each web page, advertisement, or publication, the first prominent
   appearance of "Jenkins" should feature the "circle R" character adjacent to the "s",
   as follows:
+
**Jenkins(R)**

2. At the end of your web page, advertisement, publication or media broadcast,
   include the following text in a legible font and size:
+
[quote]
____
Jenkins(R) is a registered trademark of Software in the Public Interest, Inc.
____

==== Attribution for Sublicensees

The link:sublicense[Jenkins Sublicense Agreement] sets forth how the mark should be attributed by
sublicensees. Sublicensees are required to place the following legend
conspicuously on each piece of authorized goods, and at least once in the area
of the title page of any documentation or sales literature accompanying each
authorized good or service:

[quote]
____
The registered trademark Jenkins(R) is used pursuant to a sublicense from the
Jenkins project and Software in the Public Interest, Inc.
____


The Jenkins project understands that space limitations can make including these
attributions difficult. When made necessary by space limitations, any
reasonable facsimile of these attributions may be used. In case of doubt as to
the proper shortened form, examples may be submitted to the Jenkins project for
approval.
