---
layout: simplepage
title:  Trademark and Attribution
section: project
---

The name "Jenkins" is a registered trademark in the USA to protect the project and users from confusing use of the term: 
link:https://trademarks.justia.com/854/47/jenkins-85447465.html[#4664929],
held by LF CHARITIES, Inc. (a 501(c)(3) nonprofit charity associated with the Linux Foundation).
The Jenkins Community has adopted the link:https://www.linuxfoundation.org/trademark-usage/[Linux Foundation policy on trademark usage] for use of the Jenkins trademark.

== When to apply for a trademark usage approval?

You need to comply with the Trademark Usage Policy if you are using the term "Jenkins" as part of your own trademark or brand identifier for Jenkins-based software goods or services.
It doesn’t matter if your trademark is unregistered, or if you do not plan to make any money using the mark.

Answering the following questions (which break out each of the key issues) may help you determine if you need to follow the policy.
If the answer to all three of the following questions is "yes," then you need to follow the trademark usage policy.

- Is my mark a trademark (see how the Linux Foundation defines "trademark" in link:https://www.linuxfoundation.org/legal/the-linux-mark#faq[FAQ])?
- Does my mark contain the following string of adjacent letters, in this order: "Jenkins"? These letters may or may not be capitalized, and in the case of foreign characters, phonetic translations also apply.
- Do I use my mark to identify software-related goods or services (see how that phrase is link:https://www.linuxfoundation.org/legal/the-linux-mark#faq[defined] again in the Linux Foundation)?

If you are still in doubt, please contact the Jenkins Governance Board.

== Naming guidelines

Starting from Feb 2021, the Jenkins project strictly follows the
link:https://www.linuxfoundation.org/trademark-usage/[Linux Foundation Trademark Usage Guidelines]
when reviewing new trademark usage requests.
The referenced page provides examples of the correct naming patterns,
and we urge trademark usage applicants to follow one of these or similar patterns:

* `<your product name>` for `<The Jenkins mark>`
* `<your product/company name>` plug-in for `<The Jenkins mark>`
* `<your product name>` compatible with `<The Jenkins mark>`
* `<your product name>` for use with `<The Jenkins mark>`
* Quick Start for `<The Jenkins mark>` by `<your company name>`
* `<non-trademarked industry term>` Day featuring `<The Jenkins mark>`
* `<non-trademarked industry term>` Day with `<The Jenkins mark>`
* `<non-trademarked industry term>` Day including `<The Jenkins mark>`

== Previously approved trademark usages

Before the new policy was introduced in February, 2021.
Before that Jenkins Governance meeting used to approve trademark usage requests.
These historically approved names remain approved after the trademark transition to the Linux Foundation.
A list of trademark usages approved by the project can be found on the link:approved-usage[Approved Trademark Usage] page.

== Trademark Attribution

These trademark attribution guidelines are derived from the Linux Foundation's
link:https://www.linuxfoundation.org/legal/the-linux-mark[trademark attribution]
guidelines.

Even if your use of the Jenkins trademark does not fall under the scope of the
Jenkins Sublicense Agreement, you should still attribute ownership of the mark to
Linux Foundation in two ways:

1. For each web page, advertisement, or publication, the first prominent
   appearance of "Jenkins" should feature the "circle R" character adjacent to the "s",
   as follows: **Jenkins(R)**

2. At the end of your web page, advertisement, publication or media broadcast,
   include the following text in a legible font and size:
+
[quote]
____
Jenkins(R) is a registered trademark of LF Charities Inc.
____

The Jenkins project understands that space limitations can make including these
attributions difficult. When made necessary by space limitations, any
reasonable facsimile of these attributions may be used. In case of doubt as to
the proper shortened form, examples may be submitted to the Jenkins project for
approval.

== References

* link:https://trademarks.justia.com/854/47/jenkins-85447465.html[Jenkins - Trademark Details #4664929]
* https://www.linuxfoundation.org/trademarks/[Linux Foundation Trademarks]
* https://www.linuxfoundation.org/legal/trademark-usage/[Linux Foundation Trademark Usage Guidelines]
* link:approved-usage[Approved Trademark Usage (before Feb 24, 2021)]

== Change History

=== Feb 24, 2021

The Jenkins Trademark was officially transferred from 
link:https://spi-inc.org[Software in the Public Interest, Inc.] 
to the Linux Foundation (its "LF Charities, Inc." subsidiary).

* link:https://www.linuxfoundation.org/legal/trademark-usage/[Linux Foundation trademark usage guidelines]
are now strictly followed by the project.
* There is no longer a sublicense process since it is not available for non-Linux trademarks in the Linux Foundation.

=== Oct 14, 2020

The link:/project/governance-meeting[Jenkins Governance Meeting] reviewed the trademark usage policy
and voted for closer alignment with the link:https://www.linuxfoundation.org/trademark-usage/[trademark usage guidelines] defined by The Linux Foundation.

* We adopt Linux Foundation pre-approved trademark patterns and usage guidelines.
  As long as the naming patterns are followed, no approval from the project is needed.
* We are not applying requirements retrospectively, all link:approved-usage[previously approved trademark usages] remains approved.
* Until the transition to CDF is over, we may make exceptions in the naming policy,
  subject to approval at the Jenkins Governance Meeting.

link:https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#bookmark=id.gx5dqgmbnq9g[meeting notes],
link:https://youtu.be/XvV58bjUBsk?t=366[recording]
