---
layout: simplepage
title:  Trademark and Attribution
section: project
---

The name "Jenkins" is a registered trademark in the USA
(link:https://trademarks.justia.com/854/47/jenkins-85447465.html[#4664929],
held by
link:https://spi-inc.org[Software in the Public Interest, Inc.])
in order to protect the project and users from confusing use of the term. To
reduce the process overhead and uphold our open-source spirit, we adopt the
link:https://www.linuxfoundation.org/trademark-usage/[Linux Foundation policy on trademark usage].

You need to apply for a link:sublicense[sublicense] if you are using the term "Jenkins" as part of your own trademark or brand identifier for Jenkins-based software goods or services. It doesn’t matter if your trademark is unregistered, or if you do not plan to make any money using the mark.

== When to apply for a trademark sublicense?

Answering the following questions (which break out each of the key issues) may help you determine if you need a sublicense. If you are still in doubt, please contact the board and we will work with you to determine whether you need to apply for a sublicense.

If the answer to all three of the following questions is "yes," then you need to apply for a sublicense. If the answer to any of these questions is "no," then you do not need to apply for a sublicense.

- Is my mark a trademark (see how the Linux Foundation defines "trademark" in link:https://www.linuxfoundation.org/programs/legal/trademark/faq[FAQ])?
- Does my mark contain the following string of adjacent letters, in this order: "Jenkins"? These letters may or may not be capitalized, and in the case of foreign characters, phonetic translations also apply.
- Do I use my mark to identify software-related goods or services (see how that phrase is link:https://www.linuxfoundation.org/programs/legal/trademark/faq[defined] again in LF)?

== Naming guidelines

Starting from Oct 2020, the Jenkins project intends to follow the
link:https://www.linuxfoundation.org/trademark-usage/[Linux Foundation Trademark Usage Guidelines]
when approving new trademark sublicense requests.
The referenced page provides examples of the correct naming patterns,
and we urge trademark sublicense applicants to follow one of these or similar patterns:

* `<your product name>` for `<The Jenkins mark>`
* `<your product/company name>` plug-in for `<The Jenkins mark>`
* `<your product name>` compatible with `<The Jenkins mark>`
* `<your product name>` for use with `<The Jenkins mark>`
* Quick Start for `<The Jenkins mark>` by `<your company name>`
* `<non-trademarked industry term>` Day featuring `<The Jenkins mark>`
* `<non-trademarked industry term>` Day with `<The Jenkins mark>`
* `<non-trademarked industry term>` Day including `<The Jenkins mark>`

Alternative naming patterns **may** be approved as an exception if there is a precedent of a similar trademark approval in the past.
This is considered as one-off approval by the Jenkins community,
and it is up to the sublicense applicant to justify such an exception.

== Previously approved trademark usages

A list of trademark usages approved by the project can be found on the link:approved-usage[Approved Trademark Usage] page.

== Trademark Attribution

These trademark attribution guidelines are largely derived from the Linux Foundation's
link:https://lmi.linuxfoundation.org/programs/legal/trademark/attribution[trademark attribution]
guidelines.

=== Attribution is For Everyone

Even if your use of the Jenkins trademark doesn't fall under the scope of the
Jenkins Sublicense Agreement, you should still attribute ownership of the mark to
Software in the Public Interest, Inc. in two ways:

1. For each web page, advertisement, or publication, the first prominent
   appearance of "Jenkins" should feature the "circle R" character adjacent to the "s",
   as follows:
+
**Jenkins(R)**

2. At the end of your web page, advertisement, publication or media broadcast,
   include the following text in a legible font and size:
+
[quote]
____
Jenkins(R) is a registered trademark of Software in the Public Interest, Inc.
____

=== Attribution for Sublicensees

The link:sublicense[Jenkins Sublicense Agreement] sets forth how the mark should be attributed by
sublicensees. Sublicensees are required to place the following legend
conspicuously on each piece of authorized goods, and at least once in the area
of the title page of any documentation or sales literature accompanying each
authorized good or service:

[quote]
____
The registered trademark Jenkins(R) is used pursuant to a sublicense from the
Jenkins project and Software in the Public Interest, Inc.
____


The Jenkins project understands that space limitations can make including these
attributions difficult. When made necessary by space limitations, any
reasonable facsimile of these attributions may be used. In case of doubt as to
the proper shortened form, examples may be submitted to the Jenkins project for
approval.

== References

* link:https://trademarks.justia.com/854/47/jenkins-85447465.html[Jenkins - Trademark Details #4664929]
* link:https://www.linuxfoundation.org/trademark-usage/[trademark usage guidelines] by The Linux Foundation
* link:approved-usage[Approved Trademark Usage]
* link:sublicense[Trademark Sublicense Agreement]

== Change History

=== Oct 14, 2020

The link:/project/governance-meeting[Jenkins Governance Meeting] reviewed the trademark usage policy
and voted for closer alignment with the link:https://www.linuxfoundation.org/trademark-usage/[trademark usage guidelines] defined by The Linux Foundation.

* We adopt Linux Foundation pre-approved trademark patterns and usage guidelines.
  As long as the naming patterns are followed, no approval from the project is needed.
* We are not applying requirements retrospectively, all link:approved-usage[previously approved trademark usages] remains approved.
* Until the transition to CDF is over, we may make exceptions in the naming policy.
  Example: precedent in already approved trademarks.

link:https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#bookmark=id.gx5dqgmbnq9g[meeting notes],
link:https://youtu.be/XvV58bjUBsk?t=366[recording]
