---
layout: gsocprojectidea
title: "Custom Jenkins distribution build service"
goal: "Provide an out of the box solution for packaging Jenkins distributions as WAR files or Docker images"
category: Tools
year: 2020
status: draft
skills:
- Java
- Web Development
- Docker
mentors:
- "linuxsuren"
links:
  gitter: "jenkinsci/platform-sig"
---

For many users, they download Jenkins first, then select some plugins and configure them. 
It might take a lot of time, like hours. But if we can get a perfect Jenkins distribution which contains all we need, 
it can save that time for us.

The service could be in the form of a website offered as https://customize.jenkins.io.
Plus, it should support self-hosting by Jenkins users who want to run it internally. 
People can select the following configuration items:

* Jenkins core version
* plugins
* common configuration, user/password, update-center site e.g.
* plugin based configuration, Kubernetes, Sonarqube plugin config e.g.
* backup/restore solution
* data storage solution
* multi-form package, jenkins.war or docker image
* configuration should be scenario-based
* other things

The project is expected to have a backend and a frontend parts.
Thanks to link:https://github.com/jenkinsci/custom-war-packager[Custom WAR Packager for Jenkins], 
it already did a lot of works. It can be the main library for the backend project. 

The backend should provide a modern Restful API.
We can develop different clients based on it, e.g. a Command Line Interface or a Desktop GUI application.. 
A readable API documentation is
necessary. Like many projects, the Swagger UI is a good example.
We can start the backend project with SpringBoot, it might save a lot of time.

== Quickstart

The link:https://github.com/jenkinsci/custom-war-packager[Custom WAR Packager for Jenkins] is a good starting point.

* Clone the repository and build the project, Try using the `all-latest-core` folder inside the demo folder and generate your own war.
*  Change the input by modifying the plugins used in the sample yml files.
*  Run the war.

Points to note about the WAR Packager:

* How is the war generated.
* Different methods of inputs eg: JCasC

The link:https://spring.io/projects/spring-boot[Spring Boot Documentation] is a good reference to have a look at, which can give you a fair idea about the services that could be incorporarted via a REST API Interface into the project.



## References

Below you can find a list of existing plugins and libraries which can be used for inspiration:

* link:https://github.com/jenkinsci/custom-war-packager[Custom WAR Packager for Jenkins]
* link:https://github.com/jenkinsci/configuration-as-code-plugin[Jenkins Configuration as Code Plugin]
* link:https://jenkins.io/sigs/cloud-native/pluggable-storage/[Pluggable Storage]
