---
layout: gsocprojectidea
title: "Template for submitting a project idea"
goal: "One sentence summarizing the goal of your idea"
category: Plugins
year: 2020
status: published
mentors:
- "martinda"
skills:
- skills_go_here
- add_more_if_needed
links:
  gitter: "jenkinsci/gsoc-sig"
---

Write your project idea here. Sometimes an abstract is enough, but you should include:

Note: Project ideas are not the same as Project Proposals made by students.
Anyone including students can submit ideas, but only eligible students can link:../../../students/#application-steps[submit proposals].

* A short description of the project
* The benefits to the community
* A list of comparable solutions, and why your idea is better
* Anything you want to say about your project
* Students will read this when they look to participate in the program, so make sure you catch their attention!
* Have a look at other project ideas for inspiration to improve the way you present your idea

==== Quickstart

You may have quick start instructions for students, e.g. how to get started on your proposal. Provide this information here.

==== Links

You may have additional links to the ideas here, including related discussions on
the Jenkins Dev or Jenkins User mailing list, blogposts, Jiras, etc.

Links looks like this:
```
link:https://plugins.jenkins.io/role-strategy[Role Strategy Plugin]
link:../../students[Information page for students]
```

And are rendered like this:

link:https://plugins.jenkins.io/role-strategy[Role Strategy Plugin]

link:../../students[Information page for students]

==== Newbie-friendly issues

If you are potential mentor, propose examples of tickets the applicants could
handle to study the area while working on the application proposals. We do NOT
require students to make contributions before applying, but such tasks may help
to select students who are interested to work on the project.

==== Other examples

Refer to the following files on Github for additional example to format your project idea submission:

* link:https://github.com/jenkins-infra/jenkins.io/blob/master/content/projects/gsoc/2019/project-ideas/artifactory-rest-plugin.adoc[Project idea with link to a google doc]
* link:https://github.com/jenkins-infra/jenkins.io/blob/master/content/projects/gsoc/2019/project-ideas/role-strategy-ux.adoc[Project idea with no link to google doc]
