---
layout: developersection
title: IDE Configuration
references:
- url: https://wiki.jenkins.io/display/JENKINS/Developing+with+JRebel
  title: Developing with JRebel (external wiki; plugin enables hot reload of Java classes without full restarts)
---

== IntelliJ IDEA

link:https://plugins.jetbrains.com/plugin/1885-jenkins-development-support/[Jenkins Development Support] (source code https://github.com/jenkinsci/idea-stapler-plugin)

This IDEA plugin makes it easy to develop Jenkins and its plugins on IntelliJ IDEA

This plugin has the following features:

* Cmd/Ctrl+B navigation from the Jelly tags to their definitions
* Error checks and auto completion on attributes and elements of taglibs
* Syntax error checks on JEXL expressions
* "Go to stapler view" to jump from a Java class to its views (Cmd/Ctrl+Shift+P)
* Select a string expression, then "Refactor" > "i18n for Stapler" to create a message resource

== NetBeans
The previously referenced NetBeans plugin is no longer available.
For Java and Maven support, use the built-in NetBeans tooling and run the plugin with `mvn hpi:run` from the project root.

== Visual Studio Code
See link:https://code.visualstudio.com/docs/languages/java[Visual Studio Code Java documentation] for recommended extensions (e.g. Extension Pack for Java, Debugger for Java).

Create the following 2 files in your project:

`.vscode/tasks.json`:
[source, json]
----
{
    "version" : "2.0.0",
    "tasks": [
        {
            "label": "mvnDebug",
            "type": "shell",
            "command": "mvnDebug hpi:run",
            "isBackground": true,
            "problemMatcher": [{
                "pattern": [{
                    "regexp": "\\b\\B",
                    "file": 1,
                    "location": 2,
                    "message": 3
                }],
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^.*Preparing to execute Maven in debug mode.*",
                    "endsPattern": "^.*Listening for transport dt_socket at address.*"
                }
            }]
        }
    ]
}
----

`.vscode/launch.json`:
[source, json]
----
{
    "configurations": [
        {
            "type": "java",
            "name": "Debug (Attach)",
            "request": "attach",
            "hostName": "localhost",
            "port": "8000",
            "preLaunchTask": "mvnDebug"
        }
    ]
}
----

`F5` to start your debug session.

== XSD configuration
If there isn't a plugin available for your IDE you can manually add the taglib to your IDE.

XML schemas for tag libraries defined in Jelly, stapler, and Jenkins are available. Most modern IDEs and other XML editors can use them to provide auto-completion, which improves your productivity.
See link:/doc/developer/development-environment/taglibs[Taglibs] for links to the up-to date schemas.
