---
layout: developersection
title: IDE Configuration
references:
- url: https://wiki.jenkins.io/display/JENKINS/Developing+with+JRebel
  title: Developing with JRebel # TODO find someone who can write actual documentation for this
---

== IntelliJ
https://plugins.jetbrains.com/plugin/1885-stapler-plugin-for-intellij-idea

This IDEA plugin makes it easy to develop Jenkins and its plugins on IntelliJ IDEA

This plugin has the following features:

* Cmd+B navigation from the Jelly tags to their definitions
* Error checks and auto completion on attributes and elements of taglibs; also see Writing Jelly views with IDE assistance
* Syntax error checks on JEXL expressions
* "Go to stapler view" to jump from a Java class to its views (Cmd+Shift+P)
* Select a string expression, then "Refactor" > "i18n for Stapler" to create a message resource

== Netbeans
http://plugins.netbeans.org/plugin/43938/?show=true

== XSD configuration
If there isn't a plugin available for your IDE you can manually add the taglib to your IDE.

XML schemas for tag libraries defined in Jelly, stapler, and Jenkins are available. Most modern IDEs and other XML editors can use them to provide auto-completion, which improves your productivity.
See link:/doc/developer/development-environment/taglibs[Taglibs] for links to the up-to date schemas.
