artwork: ["/content/artwork/", "content/_data/logo/"]
blogpost: ["content/blog"]
changelog: ["content/changelog", "content/changelog-stable", "content/_data/changelogs", "*changelog*", "content/_data/upgrades"]
documentation: ["content/doc", "content/solutions"]
chore: [".github", "Jenkinsfile", "Gemfile", "package.json", "Makefile", "scripts"]
events: ["content/_data/events/"]
gsoc: ["content/projects/gsoc/"]
governance: ["content/project/", "content/conduct.adoc"]
