---
layout: developersection
title: Adopt a Plugin
---

*We're looking for new maintainers of existing plugins!*

== A plugin I'm (planning on) using shows up as looking for a maintainer. Does that mean I shouldn't use it?

*No.* Jenkins is designed with backward compatibility in mind, so it's rare that a plugin stops working.
And even then there's often someone who can fix the bug and release a new version even if they wouldn't be considered a maintainer of the plugin.
So if you're happy with what a plugin is offering, there's no reason not to use it just because it's up for adoption.

== I want to help! How can I find a plugin to maintain?

Check out the list of plugins up for adoption at the bottom of this page.
If you see a plugin you like, visit its wiki page as it may contain additional information about the adoption request.

== I know which plugin I want to help with, what should I do now?

Once you've chosen a plugin, review the documentation on plugin maintainership in the Jenkins project. 
This is especially important if you're not currently a plugin developer.

As a new maintainer of a new plugin, you'll inherit its existing users, so be careful with breaking changes.
https://wiki.jenkins-ci.org/display/JENKINS/Governance+Document#GovernanceDocument-Compatibilitymatters[We
value data compatibility highly], so any new releases should remain compatible with previous data and upgrade smoothly. 
If you need help with this, don't hesitate to ask other Jenkins developers for help.
And if all else fails,
https://wiki.jenkins-ci.org/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions[you can mark a new version as being incompatible with older releases] to warn users before they update.

=== Request commit access

Email the http://jenkins-ci.org/content/mailing-lists[Jenkins Developers mailing list] and request to be made a maintainer 
(which usually means commit access to the plugin repository and being made default assignee for newly reported issues in JIRA).
To that purpose, it's expected to try and reach out to existing maintainer(s) using a best effort.
So, the typical way to do that is to put her/his/their email addresses in CC (hint: Git commits should have this information).

We typically wait for about 2 weeks in normal work periods before proceeding, so please be patient.
Hence, if you can prove the existing maintainer already agrees and you explicitly asked about taking over (e.g. in a PR discussion), the process can be fast-looped.

*IMPORTANT: To speed up and ease the process, please provide the two following things:*

* Your GitHub username/id (e.g. oleg-nenashev for https://github.com/oleg-nenashev/)
* Your Jenkins infrastructure account id. Create https://jenkins-ci.org/account/[your account if you don't have one].

Once granted access, you can file a PR (with your Jenkins infrastructure account id) against
https://github.com/jenkins-infra/repository-permissions-updater to be
able to deploy snapshots and releases for your plugin.
You're generally expected to start slowly, by filing PRs, and not commit directly.
Even more for plugins with a big number of installations for obvious reasons.

== How can I mark a plugin for adoption?

First, *make sure the plugin is not being actively maintained*.
Even in actively maintained plugins, there may be periods of lower developer activity.
Don't misinterpret failures to respond to questions or requests as the plugin being unmaintained!

To mark a plugin for adoption, add the `+adopt-this-plugin+` label to the plugin's wiki page.
This will cause the note to appear below the plugin info box.

IMPORTANT: please use the _Comment:_ textfield of Confluence page edition to explain why you're marking that plugin as up for adoption.
Ideally, link to a thread on the mailing-lists, GitHub or somewhere else with a message from the current maintainer(s) confirming that the plugin is indeed not maintained anymore.

If you want to customize the message, use the `+adopt-message+` parameter to the `+jenkins-plugin-info+` macro, e.g. like this:

```
{jenkins-plugin-info:myplugin|adopt-message=The maintainer is looking
for a co-maintainer.}
```

This message will replace the default _Want to help improve this plugin?_ text in the note.

== I'm a plugin maintainer and my plugin shows as up for adoption, why?

This status is based on the `+adopt-this-plugin+` label on the plugin wiki page.
Plugin pages are labeled `+adopt-this-plugin+` manually, so it's likely a mistaken assumption that your plugin is unmaintained.
If you remove the label from its wiki page, it'll disappear from the list again.

== Which plugins are currently up for adoption?

See the list of plugin pages with the `+adopt-this-plugin+` label.

* link:https://wiki.jenkins.io/dosearchsite.action?cql=type%20in%20(%22page%22)%20AND%20label%20in%20(%22adopt-this-plugin%22)&includeArchivedSpaces=false[Jenkins Wiki Query]

