---
layout: developersection
title: Managing plugin permissions
references:
- url: https://github.com/jenkins-infra/repository-permissions-updater
  title: Repository Permissions Updater
- url: ../adopt-a-plugin
  title: Adopting a plugin
---

This page documents managing permissions for plugin maintainers.
There are 2 main permissions available to plugin contributors:

* **GitHub permissions**. 
  It includes merging pull requests, push to the repositories, managing GitHub applications, etc.
  The effective list of permissions depends on the link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization[permission levels], see below.
* **Release Permissions** which are needed to deploy releases to the link:/doc/developer/publishing/artifact-repository/[Jenkins artifact repository].
  Snapshots can be deployed by contributors without this permission.

NOTE: If you want to adopt a plugin, please see link:../adopt-a-plugin[Adopt a Plugin] instead.

== GitHub Permissions

GitHub permissions in Jenkins are managed by GitHub teams.
Almost every plugin has a `<pluginId> Developers` team created specifically for this plugin.
This team may have a different link:https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization[permission level] depending on time of creation.
For all new repositories we tend to grant `Admin` permissions at the moment, and other plugin teams can get permissions elevated upon a request.

=== Changing GitHub permissions as a maintainer

Any active maintainer is eligible to add more contributors to the GitHub repository.
There are multiple ways to do that:

. Via GitHub Web Interface, if you have admin permissions in the `<pluginId> Developers` team
** It is possible to also add collaborators to repositories
. Via a request in the link:https://github.com/jenkins-infra/helpdesk/issues/new?labels=triage,github-permissions&template=3-github-permissions.yml[Infrastructure help desk]
. Via a request in the link:/mailing-lists[developer mailing list]
. Via the ChatOps command in the `#jenkins` IRC channel, if you have voice permissions there (see the link:/projects/infrastructure/ircbot/[IRCBot])

=== Getting GitHub permissions as a non-maintainer

You will need to send a permission transfer request and to specify the permission recipient's GitHub account and Jenkins LDAP (aka Jenkins Jira) account there.
An explicit approval by an active maintainer will be required before the permission transfer happens.
If there no response from a maintainer, a link:../adopt-a-plugin[Plugin Adoption Process] might be used to request ownership of the plugin.

There are two following ways to do that:

. Via ChatOps command in the `#jenkins` IRC channel, if you have voice permissions there (see the link:/projects/infrastructure/ircbot/[IRCBot])
. Via a request in the link:/mailing-lists[developer mailing list].

The following approvals are generally recognized as valid:

* Confirmation in a Jenkins Jira ticket (permission request or other ticket)
* Explicit approval in a GitHub pull request or issue
** The reply should be sent from a GitHub account associated with a maintainer's Jenkins LDAP account
* Confirmation in the link:https://groups.google.com/g/jenkinsci-dev[developer mailing list].
** The reply should be sent from the email listed in the Jenkins LDAP account

Other types of approval (emails from different addresses, email forwards by requesters, etc.) will be reviewed and verified by `jenkinsci` GitHub administrators.

== Release Permissions

Release Permissions are needed to deploy releases to the link:/doc/developer/publishing/artifact-repository/[Jenkins artifact repository].
Permissions to upload plugin releases are independent of GitHub push access and maintained in the link:https://github.com/jenkins-infra/repository-permissions-updater[Repository Permissions Updater] repository.

To request upload permissions for a new maintainer:

. If you have never done it before, 
  you log in at least in once with your Jenkins account into the link:https://repo.jenkins-ci.org/webapp/#/home[Jenkins artifact repository].
  Any modification to the permission files will be ineffective until then.
. File a PR in the link:https://github.com/jenkins-infra/repository-permissions-updater[Repository Permissions Updater] for the specific plugin repository which needs the permission change.
  Refer to the link:https://github.com/jenkins-infra/repository-permissions-updater/blob/master/README.md[Repository Permissions Updater README] for more detailed instructions. 
  Once the permissions are updated, you'll be able to release your plugin.

//TODO(oleg-nenashev): Add CoC violations and so on?

Permission removal can be requested in the same way, e.g. during link:../adopt-a-plugin[plugin adoption].
Such requests are subject for explicit approval by contributors being removed or by `jenkinsci` GitHub administrators.
