---
layout: post
title: "Declarative Pipeline Syntax Beta 2 release"
tags:
- plugins
- pipeline
author: abayer
---

This week, we released the second beta of the new
link:https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Model+Definition+Plugin[Declarative Pipeline syntax],
available in the Update Center now as version 0.8.1 of _Pipeline: Model Definition_.
You can read more about Declarative Pipeline
link:/blog/2016/12/19/declarative-pipeline-beta/[in the blog post introducing the first beta]
from December, but we wanted to update you all on the syntax changes in the
second beta. These syntax changes are the last compatibility-breaking changes to
the syntax for the 1.0 release planned for February, so you can safely start
using the 0.8.1 syntax now without needing to change it when 1.0 is released.

== Syntax Changes

=== Agent
In order to support more detailed and clear configuration of agents, as well as
making agent syntax more consistent with the rest of the Declarative Pipeline
syntax, we've moved the agent configuration into blocks. The `agent any` and
`agent none` configurations work the same as previously, but `label`, `docker`
and `dockerfile` now look like the following:

[pipeline]
----
// Just specifying a label is simple.
agent {
    label "some-label"
}

// If you're just specifying a Docker image, you can use this simple syntax.
agent {
    docker "ubuntu:lts"
}

// When you are specifying a label or other arguments, docker looks like this:
agent {
    docker {
        image "ubuntu:lts"
        label "docker-label"
        args "-v /tmp:/tmp -p 8000:8000"
    }
}

// When you're building an image from "Dockerfile" in your repository and
// don't care what node is used or have additional arguments, you can again
// use a simple syntax.
agent {
    dockerfile true
}

// When you're building an image from a differnt file, or have a label or other
// arguments, use the following syntax:
agent {
    dockerfile {
        filename "OtherDockerfile"
        label "docker-label"
        args "-v /tmp:/tmp -p 8000:8000"
    }
}
----

=== `when` - conditional stage execution
We introduced the `when` section a couple releases ago, but have made some
changes to its syntax here in 0.8.1. We wanted to add some simpler ways to
specify common conditions, and that required we re-work the syntax accordingly.
Here's what `when` looks like now:

[pipeline]
----
// One of the most common conditions is running a stage only if you're on a
// specific branch. You can also use wildcards like "*/master".
when {
    branch "master"
}

// Another built-in condition is the environment condition, which checks to see
// if a given environment variable is set to a given value.
when {
    environment name: "SOME_ENV_VAR", value: "SOME_VALUE"
}

// Lastly, there's the expression condition, which resolves an arbitrary
// Pipeline expression. If the return value of that expression isn't false or
// null, the stage will execute.
when {
    expression {
        echo "Should I run?"
        return "foo" == "bar"
    }
}
----

=== Properties, options and wrappers
We've renamed the old `properties` section to `options`. The `options` section
is now where you'll put job properties, like `buildDiscarder`, Declarative-specific
options like `skipDefaultCheckout`, and block-scoped steps that should wrap
around the execution of the entire build, like `timeout` or `timestamps`.

[pipeline]
----
options {
    buildDiscarder(logRotator(numToKeepStr:'1'))
    skipDefaultCheckout()
    timeout(time: 5, unit: 'MINUTES')
}
----

== Heading towards 1.0!
While we may still add more functionality to the Declarative Pipeline syntax
before the 1.0 release, we won't be changing any existing syntax until, at the
earliest, a future 2.0 release. This means that any pipelines you write against
the 0.8.1 syntax will keep working for the foreseeable future without any
changes. So if you're already using Declarative Pipelines, make sure to update
your `Jenkinsfile`s after upgrading to 0.8.1, and if you haven't been using
Declarative Pipelines yet, install the _Pipeline: Model Definition_ plugin and
give them a try!