---
layout: project
title: Document
section: participate
tags:
  - help
  - documentation
  - docs-sig
  - docs
sig: docs
---

Jenkins has lots of documentation, and we appreciate any contributions to it:
new docs, design and styling, copy-editing, reviews, etc.

We coordinate and discuss documentation efforts in the link:/sigs/docs[Documentation Special Interest Group].
You can reach out to us in the mailing list or on link:https://app.gitter.im/#/room/#jenkins/docs:matrix.org[Gitter], and you can also join our link:/sigs/docs/#meetings[regular meetings].
See the contacts on the right sidebar.

== Where to find documentation?

There are many documentation sources in Jenkins.
This website and the link:https://plugins.jenkins.io/[plugins site] are the most notable ones,
but we also have docs in other places (GitHub repositories, various sites like link:https://github.com/jenkins-infra/javadoc[javadoc.jenkins.io] or the link:https://wiki.jenkins.io/[deprecated Jenkins Wiki]).
For the most of the repositories we try to follow the documentation-as-code approach.

[%header]
|===
| Documentation type | Repository | Comments and links

| link:/doc/[User documentation]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/doc[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc[Contributing guidelines].

| link:/doc/developer[Developer documentation]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/doc/developer[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc[Contributing guidelines].

| link:/solutions/[Solution pages]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/solutions[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-a-solution-page[Contributing guidelines]

| link:https://plugins.jenkins.io/[Plugin documentation]
| Plugin repositories or Jenkins Wiki
| See link:/doc/developer/publishing/documentation/[Developer documentation] for more information about plugin docs and the ongoing migration from Wiki to GitHub.

|===

== Newcomers

If you are a newcomer, documentation is a great place to contribute.
A lot of small patches can be done from the GitHub's web interface even without forking repositories and cloning them locally.
You can open any GitHub Markdown or Asciidoc page in any Jenkins repo, click _Edit_ on the page, modify and preview changes in the web interface, and then propose a change.

Useful links:

* link:https://github.com/jenkins-infra/jenkins.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22[Newbie-friendly documentation tasks]
* link:https://github.com/jenkins-infra/jenkins.io/issues?q=is%3Aopen+is%3Aissue[More advanced documentation tasks] (no `good first issue` label set)
* link:/sigs/docs/[Documentation SIG Page] with links to the Jenkins documentation
* link:https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github[Writing and Formatting on GitHub] (applies to Github Markdown documentation)

== Featured projects

=== Good first issues

The documentation issue list includes issues that are good for first time contributors.
See the link:https://github.com/jenkins-infra/jenkins.io/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22["good first issues"] list.

If you decide to work on an issue, add a comment to the issue that tells others you are working on it.
For example, add the comment "I'm working on this issue".
You do not need to wait for someone to assign you an issue.
Choose an issue, add a comment, and start writing.

=== Migrating Plugin Documentation to GitHub

Currently we are working on migrating the documentation from Jenkins Wiki to GitHub and jenkins.io.
See link:/blog/2019/10/21/plugin-docs-on-github/[this blog post] for more information about the reasons why we do this migration.
This migration involves modification of hundreds of pages and repositories, and we invite everyone to contribute.

link:/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github[**Migrating plugin documentation to GitHub**]

video::GseBgDOaa0A[youtube,width=640,height=360,start=317]

=== Migrating Other Documentation to www.jenkins.io

Jenkins user documentation was initially created in the link:https://wiki.jenkins.io[Jenkins Wiki].
The Jenkins wiki was made read-only in 2019.
Jenkins documentation improvements are now made on the Jenkins documentation site at www.jenkins.io.

Some of the documentation on the deprecated link:https://wiki.jenkins.io[Jenkins Wiki] is still useful.
Skilled Jenkins users and administrators may find Wiki information that is still accurate and can be added to www.jenkins.io.
They are encouraged to submit pull requests for those cases.

This is **not** a task for new contributors or for those who are not experienced with Jenkins.
New contributors and inexperienced Jenkins users should assist with other documentation tasks rather than attempting to migrate documentation from the wiki to www.jenkins.io.

link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#moving-documentation-from-jenkins-wiki[**Moving other documentation from wiki to www.jenkins.io**]

video::KB-NPlRvLoY[youtube,width=640,height=360]

There are also other ongoing projects which you can find on the link:/sigs/docs/#ongoing-projects[Documentation SIG page] and in the link:/project/roadmap[project roadmap].
