---
layout: project
title: Document
section: participate
tags:
  - help
  - documentation
  - docs-sig
  - docs
sig: docs
---

Jenkins has lots of documentation, and we appreciate any contributions to it:
new docs, design and styling, copy-editing, reviews, etc.

We coordinate and discuss documentaton efforts in the link:/sigs/docs[Documentation Special Interest Group].
You can reach out to us in the mailing list or on link:[https://gitter.im/jenkinsci/docs[Gitter, and you can also join our link:/sigs/docs/#meetings[regular meetings.
See the contacts on the right sidebar.

== Where to find documentation?

There are many documentation sources in Jenkins.
This website and the link:https://plugins.jenkins.io/[plugins site] are the most notable ones,
but we also have docs in other places (GitHub repositories, various sites like link:https://github.com/jenkins-infra/javadoc[javadoc.jenkins.io] or link:https://wiki.jenkins.io/[Jenkins Wiki] which is currently being deprecated).
For the most of the repositories we try to follow the documentation-as-code approach.

[%header]
|===
| Documentation type | Repository | Comments and links 

| link:/doc/[User documentation]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/doc[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc[Contributing guidelines].

| link:/doc/developer[Developer documentation]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/doc/developer[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc[Contributing guidelines].

| link:/solutions/[Solution pages]
| link:https://github.com/jenkins-infra/jenkins.io/tree/master/content/solutions[jenkins-infra/jenkins.io]
| link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#adding-a-solution-page[Contributing guidelines]

| link:https://plugins.jenkins.io/[Plugin documentation]
| Plugin repositories or Jenkins Wiki
| See link:https://jenkins.io/doc/developer/publishing/documentation/[Developer documentation] for more information about plugin docs and the ongoing migration from Wiki to GitHub.

|===

== Newcomers

If you are a newcomer, documentation is a great place to contribute.
A lot of small patches can be done from the GitHub's web interface even without forking repositories and cloning them locally.
You can open any GitHub Markdown or Asciidoc page in any Jenkins repo, click _Edit_ on the page, modify and preview changes in the web interface, and then propose a change.

Useful links:

* link:https://issues.jenkins-ci.org/issues/?filter=18650&jql=(project%20%3D%20WEBSITE%20or%20labels%20in%20(documentation%2C%20docs-sig))%20AND%20labels%20%3D%20newbie-friendly%20and%20status%20in%20(Open%2C%20Reopened%2C%20%22To%20Do%22)[Newbie-friendly documentation tasks]
* https://issues.jenkins-ci.org/issues/?filter=18650&jql=((project%20%3D%20WEBSITE%20and%20component%20%3D%20content)%20or%20labels%20in%20(documentation%2C%20docs-sig))%20and%20status%20in%20(Open%2C%20Reopened%2C%20%22To%20Do%22)[More advanced documentation tasks] (no `newbie-friendly` label set)
* link:/sigs/docs/[Documentation SIG Page] with links to the Jenkins documentation
* link:https://help.github.com/en/github/writing-on-github/about-writing-and-formatting-on-github[Writing and Formatting on GitHub] (applies to Github Markdown documentation)

== Featured projects

Currently we are working on migrating the documentation from Jenkins Wiki to GitHub and jenkins.io.
See link:/blog/2019/10/21/plugin-docs-on-github/[this blogpost] for more information about the reasons why we do this migration.
This migration involves modification of hundreds of pages and repositories, and we invite everyone to contribute.

* link:/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github[Migrating plugin documentation from Wiki to GitHub]
* link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc#moving-documentation-from-jenkins-wiki[Moving documentation from Jenkins Wiki to jenkins.io]
* jira:JENKINS-59467[Template issue for plugin docs migration]
