---
layout: project
title: Meet
section: participate
tags:
  - events
---

There are many Jenkins-related events happening around the world: meetups, conferences, contributor summits, etc.
You are welcome to join any of these events and meet other Jenkins contributors and users there.

We publish events on the link:/events/[Events page] and in our link:/event-calendar/[event calendar], but not all events are listed there.
Below you can find links to some of Jenkins-related events you can attend.

=== Online events

* link:https://www.meetup.com/Jenkins-online-meetup/[Jenkins Online Meetup]
* link:/sigs[Special Interest Group] and link:/projects[sub-project] meetings
* Webinars organized by different communities and companies, just use Google!

=== Local events

* link:/projects/jam[Jenkins Area Meetups]
* link:https://www.meetup.com/pro/cicd-cdf/[Continuous Delivery Foundation CI/CD Meetups]
* link:https://www.cloudbees.com/devops-world[DevOps World | Jenkins World conferences]
* Conferences and summits organized by Continuous Delivery Foundation: link:https://cd.foundation/events/list/[events list]
* https://www.socallinuxexpo.org[Southern California Linux Expo (SCALE)], https://fosdem.org[Free and Open source Software Developers' European Meeting (FOSDEM)], and other community-focused conferences

=== Organizing events

If you are interested in organizing an event, please reach out to the link:/sigs/advocacy-and-outreach/[Advocacy and Outreach SIG].
There are also link:/projects/jam[Jenkins Area Meetup] and link:https://www.meetup.com/pro/cicd-cdf/[Continuous Delivery Foundation CI/CD Meetup] programs which include more than 100 local meetups in total.
You can organize a meetup in your city or help with organizing existing meetups.
