---
layout: project
title: Review Changes
section: participate
tags:
  - developer
  - contributing
  - review
---

NOTE: This page is under development, there will be more content added soon.
See the jira:WEBSITE-662[] EPIC for tasks related to this page, contributions are welcome!

Help us to review changes to code or documentation!

== Code Reviews and Copy Editing

You can help review changes to the code and the documentation through following lists:

- link:https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+team%3Ajenkinsci%2Fcode-reviewers[Open pull requests for code reviews]
- link:https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+team%3Ajenkins-infra%2Fcopy-editors[Open pull requests for copy editing]

*NOTE:* You will only be able to see the open pull requests linked above if you belong to the corresponding GitHub Team.

== Reviewer team membership

If you are interested to join the link:https://[*Copy Editors team*] or link:https://[*Code Reviewers team*], you can request membership in the link:https://groups.google.com/forum/#!forum/jenkinsci-dev[Jenkins Developer mailing list].
Such membership requires a track of contributions to Jenkins, and also a signed link:https://github.com/jenkinsci/infra-cla[Contributor License Agreement].
