---
layout: project
title: Review Changes
section: participate
tags:
  - developer
  - contributing
  - review
---

Help us to review changes to code or documentation!
All pull requests within Jenkins GitHub organizations are publicly open for reviews and any reviews are much appreciated.

== Code Reviews and Copy Editing

Contributors and component maintainers may explicitly request reviews from other community members.
Below there are some queries which can help to find open pull requests where help is needed:

- link:https://github.com/search?q=org%3Ajenkinsci+org%3Ajenkins-infra+is%3Aopen+is%3Apr+team-review-requested%3Ajenkins-infra%2Fcopy-editors[Open pull requests for copy editing], mostly for Jenkins website
- link:https://github.com/search?q=org%3Ajenkinsci+org%3Ajenkins-infra+is%3Aopen+is%3Apr+%22jenkinsci%2Fcode-reviewers%22&type=Issues[Open pull requests for code reviews] (https://github.com/orgs/jenkinsci/teams/code-reviewers[@jenkinsci/code-reviewers] team is mentioned)
- link:https://github.com/jenkinsci/jenkins/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+-label%3Astalled+-label%3Awork-in-progress+-label%3Aneeds-fix[Open pull requests for code reviews in the Jenkins Core] which would benefit from reviews

*NOTE:* You will only be able to see the linked teams if you belong to the corresponding GitHub Team.

== Reviewer team membership

If you are interested to join a reviewers team,
you can request membership in the link:https://groups.google.com/g/jenkinsci-dev[Jenkins Developer mailing list].
You can also request membership in the GitHub web interface if you are already a member of the respective GitHub organization.

Reviewer team links (GitHub permissions required to view teams):

* link:https://github.com/orgs/jenkins-infra/teams/copy-editors[Copy Editors team] - Jenkins website and documentation hosted there
* link:https://github.com/orgs/jenkinsci/teams/code-reviewers[Code Reviewers team] - Jenkins plugins and other components
* link:https://github.com/orgs/jenkinsci/teams/core-pr-reviewers[Core Reviewers team] - Jenkins Core and its modules/libraries

Membership in all teams requires a track of contributions to Jenkins, and also a signed link:https://github.com/jenkinsci/infra-cla[Contributor License Agreement].
