---
layout: project
title: Issue Tracking
section: participate
tags:
  - developer
  - testing
  - contributing
---

== How-To Track an Issue

The Jenkins JIRA is not a support site. If you need assistance or have
general questions, visit us link:/chat/[in chat], or email
one of the link:/mailing-lists[mailing lists].

[[IssueTracking-Lifecycleofanissue]]
== Lifecycle of an issue

[[IssueTracking-IssueStates]]
=== Issue States

Developers don't use the various issue states consistently. The
following description just gives a broad overview.
http://issues.jenkins.io/secure/ShowConstantsHelp.jspa#StatusTypes[See
here for a description of states in JIRA].

* Issues start out as *Open*.
* When work has begun but not finished, the *Assignee* will often mark
the issue *In progress*.
* When finished and a solution is checked in, the *Assignee* (or a bot
responding to commit messages) will mark the issue *Resolved*
* Some users also mark issues *Closed* after a fix is confirmed by
others.
* When an issue was resolved or closed before, but users still
experience the same problem, they may set the issue to *Reopened*.

[[IssueTracking-Issuesnotrequiringachange]]
=== Issues not requiring a change

If an issue is considered to be a *Duplicate*, it will be marked as
resolved, and the original issue will be linked. It's not always the
newer issue that gets closed as duplicate, sometimes it's the older one,
e.g. when the description in the new one is better, or the new one has
more watchers. This depends on the developer resolving as duplicate.
Duplicate issues should only be reopened when you have determined that
they are not actually a duplicate of the linked issue, and for no other
reason.

Issues may be found to be *Won't Fix* or *Not a Defect* for various
reasons, e.g. when a developer determines that the issue isn't actually
a problem with Jenkins.

Issues may be resolved as *Cannot Reproduce* when the developer is
unable to reproduce the issue as described, e.g. because it may have
been resolved since it was reported, or it is believed the issue is not
with Jenkins.

Issues resolved as *Incomplete* do not provide a sufficient description
of the problem.

[[IssueTracking-Issuesrequiringachange]]
=== Issues requiring a change

When a developer decides to work on such an issue, the *Assignee* field
is changed to that developer. It may be set to *In progress* while it's
being worked on.

When a fix has been integrated, the issue is usually marked *Resolved*
(using the resolution *Fixed*), and sometimes marked *Closed* after the
fix has been verified.

[[IssueTracking-QuickLinks]]
== Quick Links

If you want to link to a Jenkins bug with a short URL, use e.g.:
https://jenkins-ci.org/issue/1234 instead of
https://issue-redirect.jenkins.io/issue/1234
