---
layout: post
title: "Who is Flat Jenkins?"
tags:
- Jenkins World
author: hinman
---

[NOTE]
====
This is a guest post by Hannah Inman, Social Media and Content Manager at CloudBees.
====

CloudBees is hosting a new, fun Jenkins World project - Flat Jenkins.

Have you heard of link:https://en.wikipedia.org/wiki/Flat_Stanley[Flat Stanley], the popular children’s book? When a link:http://www.dalehubert.com/[teacher] in Canada read this book to his students, he was inspired to create a program where his students would mail their own Flat Stanleys in envelopes to children around the world and in doing so, become pen pals! Flat Stanley has traveled the world thousands of times over, has met several presidents, has played with (...or link:http://www.flatstanleyproject.com/pictures.html[been eaten by]?) penguins and much more. 

Now, the Flat Stanley idea has evolved into Flat Jenkins! Jenkins is a pervasive technology that changes lives behind the scenes, but now you have the opportunity to really show that Jenkins literally can be EVERYWHERE! Print out Flat Jenkins in his “Summer of Love” outfit, bring him around to your favorite spots in your hometown or your travels, snap a picture of him and post it on social media with #FlatJenkins17. Then, bring him to link:https://www.cloudbees.com/jenkinsworld/home[Jenkins World] - to the sites you see around San Francisco, California, to your favorite sessions and maybe even to the Jenkins World 2017 Summer of Love after party.

How far can Flat Jenkins go? Attendees are traveling to San Francisco, CA from all around the globe to link:https://www.cloudbees.com/jenkinsworld/home[Jenkins World]. You could bring Flat Jenkins to your local Jenkins Area Meetup, to your work and then finally in your suitcase where we will all meet at Jenkins World.

It's easy: snap your pic of Flat Jenkins wherever you are, post on social media and add #FlatJenkins17 to see Flat Jenkins travel everywhere.

link:https://www.cloudbees.com/sites/default/files/flat-jenkins.pdf[CLICK HERE TO DOWNLOAD YOUR FLAT JENKINS]
