---
layout: post
title: "Declarative Pipelines at Jenkins World"
tags:
- plugins
- pipeline
author: abayer
---

[NOTE]
====
This is a guest post by link:https://github.com/abayer[Andrew Bayer], who is
one of the authors of the
link:https://plugins.jenkins.io/pipeline-model-definition[Declarative Pipeline plugin],
and is a software engineer on the Pipelines team at
link:http://cloudbees.com[CloudBees, Inc.]
====

A year ago at Jenkins World 2016, we unveiled Declarative Pipelines, a
structured way to define your Pipelines. It's been a great year for Declarative
and Pipelines in general, with the release of Declarative Pipelines 1.0 in
February, multiple releases since then, the introduction of
link:https://jenkins.io/doc/book/pipeline/[documentation on Pipelines at jenkins.io],
with a focus on Declarative, and more. Given everything that's happened over
the last year, we thought it'd be good to let you all know what you can expect
to see and hear about Declarative Pipelines at this year's Jenkins World.

First, on Thursday, August 31, I'll be giving a talk on Declarative Pipelines
with link:https://github.com/rsandell[Robert Sandell], one of my coworkers
here at CloudBees and another author of Declarative Pipelines. We'll be
covering what's happened with Declarative over the last year, new features
added since the 1.0 release, such as the `libraries` directive and more `when`
conditions, what's planned for the upcoming 1.2 release (which is planned for
shortly after Jenkins World!), including parallel `stage`s, and what's on the
roadmap for the future. In addition, we'll be demoing some of the features in
1.2, and providing some pointers on best practices for writing your Declarative
Pipelines.

Also on Thursday, link:https://github.com/stephendonner[Stephen Donner from Mozilla]
will be giving a demo showing Mozilla's usage of Declarative Pipelines and
shared libraries at the Community Booth - Mozilla has been doing great work
with Declarative, and I'm excited to see their usage in more detail and hear
Stephen talk about their experience!

In addition, Robert, Stephen, and myself will all be at Jenkins World both days
of the main sessions, and Robert and myself will also be at the
link:https://jenkinsworld20162017.sched.com/event/BvPs/jenkins-world-2017-contributor-summit[Contributor Summit]
on Tuesday. We'd love to hear your thoughts on Declarative and will be happy to
answer any questions that we can. Looking forward to seeing you all!

[WARNING]
====
Andrew Bayer and Robert Sandell will be talking about the latest on
link:https://jenkinsworld20162017.sched.com/event/ALOd/declarative-pipelines-in-jenkins[Declarative Pipelines in Jenkins]
 at link:https://www.cloudbees.com/jenkinsworld/home[Jenkins World] in August,
register with the code `JWFOSS` for a 30% discount off your pass.
====

