tasks:
  - name: Start Preview server
    init: make prepare # runs during prebuild
    command: make run
    openMode: tab-before

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4242
    onOpen: open-preview

github:
  prebuilds:
    pullRequestsFromForks: true
    addBadge: true

vscode:
  extensions:
    - asciidoctor.asciidoctor-vscode
    - streetsidesoftware.code-spell-checker

jetbrains:
  intellij:
    plugins:
      - org.asciidoctor.intellij.asciidoc
    prebuilds:
      version: stable
