site:
  title: Jenkins
  url: https://www.jenkins.io
  start_page: jenkins::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./docs/supplemental-ui

output:
  dir: build/antora-site
  clean: false
