= Contributing to the Jenkins website

== Building

This project uses link:http://gradle.org[Gradle] to build, so as long as you
have JDK7 or later in your path, you should be able to build the site with:

    % ./gradlew assemble

NOTE: If you run `./gradlew -t assemble` this puts Gradle into
link:https://docs.gradle.org/current/userguide/continuous_build.html[continuous
build] mode, where it will regenerate the site whenever a `.adoc`, `.haml` or
`.md` file is changed.


The easiest way to run the site is with Python's built-in static HTTP server,
e.g.:

    % (cd build/_site && python -m SimpleHTTPServer)

This will host the statically generated site at
link:localhost:8000[http://localhost:8000]

== Editing content

The majority of what is considered "legacy" content is almost entirely under
`content/blog`. These files represent structured around the date the original
stories were written in Drupal.

=== Adding a blog post

In order to add a new blog post, create a new file ending in **.adoc** (for
link:http://asciidoctor.org[Asciidoctor]) in the appropriate
`content/blog/<year>` directory with the full date and a *lower-case* title for
your post. In effect, if you're writing a post that you want to title "Hello
World" on January 1st, 1970, you would create the directory:
`content/blog/1970/1970-01-01-hello-world.adoc`.

In that tile you need to enter some meta-data in the following format:

.1970-01-01-hello-world.adoc
[source,yaml]
----
---
layout: post
title: "Hello World!"
tags:
- jenkins
- timetravel
author: yourgithubname
---
----

The `layout` attribute tells the rendering engine to use the "post" layout,
`title` and `tags` should be fairly self-explanitory. This section is referred
to as the link:http://jekyllrb.com/docs/frontmatter/[front matter].

After the front matter, you can author your content and
link:https://help.github.com/articles/creating-a-pull-request/[create a pull
request] for your blog post.

The format of this file is Asciidoc, if you're unfamiliar with the syntax,
please consult this
link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[handy quick
reference guide].


=== Adding a stand-alone page

Encouraged formats:

* link:http://asciidoctor.org[Asciidoctor] (basic content creation) (link:http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoc syntax quick reference])
* link:http://haml.info[Haml] (more advanced/custom page) (link:http://haml.info/docs/yardoc/file.REFERENCE.html[Haml syntax reference]

Adding a new page is as easy as adding a a new file to the `content/`
directory. It is important to keep in mind that the filename you choose *will
be the URL of your page*, so ensure you have a *lower-case* and useful
filename.


The `content/index.html.haml` page is one such example of a special-case,
standalone page.


==== Clean URLs

In order to have a clean URL, e.g. "https://jenkins.io/my-clean-url", you would
need to create a directory with your content in it. Using the above example, I
would create the directory `content/my-clean-url` and if I were creating an
Asciidoc file, I would then create the file `content/my-clean-url/index.adoc`.
(Advanced Haml users would create `content/my-clean-url/index.html.haml`).


=== Advanced Building

The underlying technology is link:http://awestruct.org[awestruct] which is
Ruby project, but to make it easy to use we've wrapped these Ruby scripts with
link:http://jruby-gradle.org[JRuby/Gradle]. If you wish to circumvent using
Gradle entirely, you can do so, so long as you manage your own Ruby development
environment (e.g. with link:http://rvm.io[RVM]).

==== Gems

Install these gems:

* `awestruct`
* `haml`
* `kramdown`

==== Local development

The awestruct gem provides a command line interface which is very useful. If
you're using MRI (aka "CRuby", non-JRuby), just
execute: `(cd content && awestruct --dev --output-dir ../build/_site)` and you'll have a live-reloading webserver running
on link:http://localhost:4242/[localhost:4242]

In order to get a *legacy* version of jenkinsci.org, you need to setup the LEGACY environment variable and then run the code in another folder.
Example: `(cd content && LEGACY=true awestruct --dev --output-dir ../build/_legacy)`

