= jenkins.io

WHAT IS JENKINS?
Jenkins is an open source automation server written in Java, by Kohsuke Kawaguchi, which helps to automate the software development process. It allows for continuous integration by constantly checking through source code for changes that will trigger a build and run any neccessary tests before outputting to the Jenkins Dashboard.

Jenkins is open source, platform independent, user-friendly, easy to install and does not require additional installations or components. 

For further information, feel free to get acquainted:
https://jenkins.io/blog/2018/03/19/introducing-jenkins-x/


This repository is what powers the link:https://jenkins.io/[Jenkins
website]. This uses link:http://awestruct.org[awestruct]
with link:http://asciidoctor.org[Asciidoctor] under the hood to provide a very
useful and compelling web presence for the link:https://jenkins.io/[Jenkins
automation server].


If you're interested in contributing to the site, please see our
link:https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc[Contributing
document]
