= Jenkins Documentation Style Guide

CAUTION: This document is still a work in progress.

== Terminology

* Build
* Job
* Agent
* Master
* Node
* Pipeline

Mixing of these terms is incorrect

== Assorted comments

* Prefer "for example" over "e.g." which can be more clear to non-native english
  readers
* Don't use unordered lists (bullets) in place of section headers. Section
  headers offer a nesting/association of content in a way lists cannot
* If you write a sentence such as "there are three ways to do this:" and then
  intend to follow that statement with a list, use a *numbered* list
** If you are providing a list of "two ways", each description of a "way"
should follow the same structure, for example:

[source, asciidoc]
----

By default, new agents can be connected to Jenkins with one of
following four methods:

. Via SSH, requires that the master be able to connect directly to an
  agent machine and have valid authentication credentials. The agent must have an
  SSH daemon running.
. Via Java Web Start, requires no special configuration on the master. The agent
  must be able to connect to the Jenkins master and have a Java runtime.installed.
. Via command execution on the master, requires a command to be executable by
  the Jenkins system user on the master. This method is generally used to support
  more advanced invocations of the agent `.jar`.
. Via a Windows service, requires that the master is a Windows machine and has
  access to built-in link:http://en.wikipedia.org/wiki/Windows_Management_Instrumentation[Windows remote management facilities]
----

Note that each line item generally follows the same structure of "method, master
requirements, agent requirements." While not _strictly_ required, this
structuring can help readers compare and contrast the various options to make
an informed decision on which path is suitable for them.


* Titles should only have the first letter intentionally capitalized. This
  ensures that casing of articles and prepositions, mixed with proper nouns,
  doesn't get too confusing. For example:  "Starting a JNLP Agent on Windows"
  versus "Starting A JNLP Agent On Windows" versus "Starting a JNLP agent on
  Windows". The latter will result in the most consistent titles
* Only proper nouns should be capitalized, for example "Windows." But not
  "Windows Server" unless, of course, you're referring to a product named
  "Windows Server."
* Prefer explicit words/phrases over acronyms, for example:

[quote]
----
and the stage names will be displayed as columns in the Stage View UI.
----

"UI" can me a lot of different things, the CLI is a "UI", the Pipeline script
itself is a "UI," the Script Console is a "UI" and of course the web interface
is also a "UI."

The statement above is better written as:

[quote]
----
and the stage names will be displayed as columns in the Stage View web interface
----
