= Jenkins Documentation Style Guide

CAUTION: This document is still a work in progress.

== Terminology

* Build
* Job
* Agent
* Master
* Node
* Pipeline

Mixing of these terms is incorrect

== Assorted comments

* Prefer "for example" over "e.g." which can be more clear to non-native english
  readers
* Don't use unordered lists (bullets) in place of section headers. Section
  headers offer a nesting/association of content in a way lists cannot
* If you write a sentence such as "there are three ways to do this:" and then
  intend to follow that statement with a list, use a *numbered* list
** If you are providing a list of "three ways", each description of a "way"
should follow the same structure, for example:

[quote]
----

----

* Titles should only have the first letter intentionally capitalized. This
  ensures that casing of articles and prepositions, mixed with proper nouns,
  doesn't get too confusing "Starting a JNLP Agent on Windows" versus "Starting A JNLP
  Agent On Windows" versus "Starting a JNLP agent on Windows". The latter will
  result in the most consistent titles
* Only proper nouns should be capitalized, for example "Windows." But not
  "Windows Server" unless you're referring to a product named "Windows Server"
  of course
* Prefer explicit words/phrases over acronyms, for example:

[quote]
----
and the stage names will be displayed as columns in the Stage View UI.
----

"UI" can me a lot of different things, the CLI is a "UI", the Pipeline script
itself is a "UI," the Script Console is a "UI" and of course the web interface
is also a "UI."

The statement above is better written as:

[quote]
----
and the stage names will be displayed as columns in the Stage View web interface
----
