---
:layout: post
:title: "2024 Jenkins Election Candidate Statements"
:tags:
- community
- governance
- governance-board
- elections
authors:
- basil
- markewaite
- jonesbusy
- krisstern
- notmyfault
- oleg_nenashev
- slide_o_mix
- stefan_spieker
- timja
description: >
  Candidate statements for 2024 Jenkins elections.
links:
  discourse: https://community.jenkins.io/t/jenkins-board-and-officer-elections-2024/20137
opengraph:
  image: /images/governance/elections/2024/2024-candidate-statements-opengraph.svg
---

Candidate nominations for the 2024 Jenkins elections are now complete.
Thanks to everyone who submitted nominations and to the candidates that have accepted the nominations.

This announcement shares the election candidates and their statements.
Nominees for the Jenkins governance board include:

* link:#slide_o_mix-board[Alex Earl]
* link:#NotMyFault[Alexander Brandes]
* link:#krisstern[Kris Stern]
* link:#oleg-nenashev[Oleg Nenashev]
* link:#stefan_spieker[Stefan Spieker]
* link:#jonesbusy[Valentin Delaye]

Nominees for the Jenkins release officer include:

* link:#slide_o_mix-officer[Alex Earl]
* link:#timja[Tim Jacomb]

As in years past, when a particular role receives only one nomination, an election is not required.
Officers that do not require an election include:

* link:/blog/authors/alyssat/[Alyssa Tong] - Events Officer
* link:/blog/authors/dduportal/[Damien Duportal] - Infrastructure Officer
* link:/blog/authors/kmartens27/[Kevin Martens] - Documentation Officer
* link:/blog/authors/wadeck/[Wadeck Follonier] - Security Officer

== Board Candidates

[[slide_o_mix-board]]
=== link:/blog/authors/slide_o_mix/[Alex Earl]

I have been involved with Jenkins for many years, going back to the Hudson days.
I got involved in the great community by making some changes that I needed at my company to one of the plugins.
I then became maintainer of that plugin and continued to participate in the IRC channels and discussion forums to help improve Jenkins.

The community of Jenkins is one of the best features, in my opinion.
The people are helpful, want to provide a great thing to the world, and are so invested in making Jenkins the best it can be.

As a member of the Jenkins Governance Board, I would love to continue pushing that community and excellence.
Getting more people involved in development and helping is something I would like to focus on.
A lot of people are intimidated by open source and contributing.
I would like to work on that idea and help lower the barriers for others to get involved, learn, and contribute.

Affiliations: Arm Ltd.

Profile pages:
link:https://github.com/slide[GitHub],
link:https://www.linkedin.com/in/alex-earl-109b091/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/alex-earl/[Contributor spotlight],
link:https://community.jenkins.io/u/slide_o_mix/summary[Jenkins community]

[[NotMyFault]]
=== link:/blog/authors/notmyfault/[Alexander Brandes]

I've been a passionate Jenkins user for almost a decade and have had the privilege of contributing to the project since 2020.
Since 2022, I've been serving as a board member, and I'm also part of the release team, a core maintainer, as well as a maintainer of various plugins.
Additionally, I'm involved in the hosting team, where I review and onboard new plugins into the Jenkins ecosystem.

One of my personal highlights this year was participating as a mentor in Google Summer of Code 2024, where I successfully onboarded two students to the Jenkins project.
I ensured their projects were a success, further strengthening the future of the Jenkins community.

As a board member, I've attended various in-person events to represent the Jenkins project and spread the word about our vibrant community.
From FOSDEM 2023 and 2024 to KubeCon 2023, CdCon 2023, and a GSoC meetup in Munich and Sunnyvale, I've built strong connections with fellow community members and like-minded individuals.

I firmly believe in the future of Jenkins, especially with the ongoing and upcoming UI/UX rework and the efforts to ensure Jenkins stays ahead of modern technology.
One of our key focuses is ensuring Jenkins can run seamlessly out of the box on platforms like Java 22.

Throughout my time on the project, I've documented various in-house workflows, including the LTS release process, and introduced numerous automations to reduce human input.
These efforts help keep Jenkins agile and efficient as we move forward into the future.

Affiliations: Card4Vend

Profile links:
link:https://github.com/NotMyFault[GitHub],
link:https://www.linkedin.com/in/alexander-brandes/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/alexander-brandes/[Contributor spotlight],
link:https://community.jenkins.io/u/NotMyFault/summary[Jenkins community]

[[stefan_spieker]]
=== link:/blog/authors/stefan_spieker/[Stefan Spieker]

I started contributing regularly in 2019, with a focus on improving quality.
I'm also keeping up with some older plugins that are still really popular, like the plugin:thinBackup[Thin Backup] plugin and the plugin:jobConfigHistory[Job Configuration History] plugin.
The community helped me to bring these back up to standard and I learned a lot along the way. Furthermore, I use these lessons to make regular improvements to the developer documentation.

In my day job, I'm a solution architect in a central team that provides Jenkins and DevOps consulting within a big automotive and industrial company.

I'm already honored to be nominated, but if elected and allowed to serve on the Jenkins Board, I'd love to bring the perspective of bigger enterprises using Jenkins.
I also plan to improve the developer documentation to make it easier for new maintainers to adopt abandoned plugins and keep the Jenkins ecosystem as diverse as it is today.

Affiliations: Schaeffler

Profile Links:
link:https://github.com/StefanSpieker[GitHub],
link:https://www.linkedin.com/in/stefan-spieker-446168161/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/stefan-spieker/[Contributor spotlight],
link:https://community.jenkins.io/u/stefanspieker/summary[Jenkins community],
link:https://stackoverflow.com/users/1287864/s-spieker[Stackoverflow]

[[jonesbusy]]
=== link:/blog/authors/jonesbusy/[Valentin Delaye]

I've been a Jenkins user since it's inception in 2011 and contributor since 2018.
As of today I maintain more than 35 plugins.

Starting of this year I got even more involved in the Jenkins community, by participating as a mentor for the Google Summer of Code to work on the Jenkins Plugin Modernizer Tool, which is a CLI to update plugins at scale using OpenRewrite.

I'm particularly interested in the "cloud ready" aspect of Jenkins including deployments, packaging (like Jenkinsfile Runner), or distributed storage.
A recent contribution on this topic is the link:https://plugins.jenkins.io/artifactory-artifact-manager/[Artifactory Artifact Manager plugin] that I authored and maintain.

If I'm elected on the Jenkins governance board those will be my subjects of choice.

Affiliations: ELCA Cloud Services

Profile Links:
link:https://github.com/jonesbusy[GitHub],
link:https://www.linkedin.com/in/valentindelaye/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/valentin-delaye/[Contributor spotlight],
link:https://community.jenkins.io/u/jonesbusy/summary[Jenkins community]

[[krisstern]]
=== link:/blog/authors/krisstern/[Kris Stern]

I have been a Jenkins contributor since 2021.
Currently I am a maintainer of four plugins, have been a GSoC org admin and mentor for Jenkins for three years, and continue to be a Jenkins Release Team member.
Academically I have been trained as an observational astrophysicist and obtained my PhD degree from the University of Hong Kong (HKU) in 2021.
I have worked professionally as a software engineer since late 2019, currently working in a AiFi startup.
Currently I am also a part-time MCIT Online student at UPenn.
I am passionate about open source and would like to share my love of open-source software with the others.
I feel grateful to be nominated. If elected, I would love to bring with me a startup mindset to help keep Jenkins perpetually youthful and relevant as well as a welcoming community to newcomers.

Affiliations: GAIB.ai

Profile Links:
link:https://github.com/krisstern[GitHub],
link:https://www.linkedin.com/in/kris-stern/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/kris-stern/[Contributor spotlight],
link:https://community.jenkins.io/u/krisstern/summary[Jenkins community]

[[oleg_nenashev]]
=== link:/blog/authors/oleg_nenashev/[Oleg Nenashev]

I’ve participated in Jenkins since 2012, including being a core maintainer since 2014,
I was a governance board member from 2019 for two terms (Dec 2019-2023) and also represented Jenkins on the Continuous Delivery Foundation TOC and the board.
During my work on Jenkins, I participated in many projects including JCasC, pluggable storage, and Jenkinsfile Runner. I also created or maintained around 30 plugins for Jenkins.
Many community programs, including GSoC and Hacktoberfest participation, were initially started by me.
In 2022. I took a sabbatical as a core and plugin maintainer due to the war in Ukraine, but I plan to return to the maintainer roles, too.

For me, Jenkins has one of the strongest open source communities, and I am proud to be a part of it.
Should I be elected to the board, my focus will be community growth via onboarding new contributors, improving contributor/developer experience for Jenkins, and facilitating technical partnerships.
The ecosystem evolves, and Jenkins should be changing and growing along with that.
For me, the priorities would be adopting open standards,
integrations with the key projects and services in the cloud-native, CI/CD, and Java space, and continuing Jenkins' evolution as a multi-purpose automation framework.

Affiliations: Gradle Inc., CNCF/CDF, API Neuchatel, Independent

Profile Links:
link:https://github.com/oleg-nenashev[GitHub],
link:https://www.linkedin.com/in/onenashev/[LinkedIn],
link:https://sessionize.com/onenashev[Sessionize]
link:https://community.jenkins.io/u/oleg-nenashev/summary[Jenkins community]

== Officer Candidates

[[slide_o_mix-officer]]
=== Release Officer - link:/blog/authors/slide_o_mix/[Alex Earl]

I have been involved with Jenkins for many years, going back to the Hudson days.
I got involved in the great community by making some changes that I needed at my company to one of the plugins.
I then became maintainer of that plugin and continued to participate in the IRC channels and discussion forums to help improve Jenkins.

The community of Jenkins is one of the best features, in my opinion.
The people are helpful, want to provide a great thing to the world, and are so invested in making Jenkins the best it can be.

As a member of the Jenkins Governance Board, I would love to continue pushing that community and excellence.
Getting more people involved in development and helping is something I would like to focus on.
A lot of people are intimidated by open source and contributing.
I would like to work on that idea and help lower the barriers for others to get involved, learn and contribute.

Affiliations: Arm Ltd.

Profile pages:
link:https://github.com/slide[GitHub],
link:https://www.linkedin.com/in/alex-earl-109b091/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/alex-earl/[Contributor spotlight],
link:https://community.jenkins.io/u/slide_o_mix/summary[Jenkins community]

[[timja]]
=== Release Officer - link:/blog/authors/timja/[Tim Jacomb]

I have been a user of Jenkins for the last 14 years and a regular contributor since 2018.
I began with maintaining the Slack plugin, and over the last couple of years, I have expanded my experience with several more plugins and Jenkins core.
These are some of the components I maintain when I have time: Slack, Azure Key Vault, Junit, most of the Database plugins, Dark theme, Plugin installation manager, Jenkins Helm chart, and the Configuration as code plugin.

I am a member of the Jenkins infrastructure team.
I was involved in the release automation project and the mirrors modernisation effort, along with the day to day support helping people regain access to accounts etc.

As Release Officer, I would like to increase automation, ease onboarding of new contributors to the release team, and ensure that responsibilities rotate among people so that I won't be a bottleneck for any task.

Affiliations: Kainos

Profile pages:
link:https://github.com/timja[Github],
link:https://www.linkedin.com/in/tim-jacomb/[LinkedIn],
link:https://contributors.jenkins.io/pages/contributors/tim-jacomb/[Contributor spotlight],
link:https://community.jenkins.io/u/timja/summary[Jenkins community]
