---
title: Working with JSON
summary: How to handle JSON HTTP request with Jenkins
layout: developersection
references:
- url: https://github.com/stapler/stapler/blob/master/docs/reference.adoc
  title: Stapler URL Binding Reference
- url: ../routing
  title: How requests in Jenkins are routed
- url: ../../testing
  title: Testing Jenkins
---

== Handle request in Jenkins

=== Pre-requisite : a POJO (Plain Old Java Object)

For this example we are using a very simple Object.
Note that if you use Stapler for marshalling and unmarshalling JSON, you need an empty constructor.

[source,bash]
----
public static class MyJsonObject {
    private String message;

    //empty constructor required for JSON parsing.
    public MyJsonObject() {}

    public MyJsonObject(String message) {
        this.message = message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}
----

=== Handling GET with Jenkins

[source,java]
----
/* (1) */
import hudson.model.RootAction;
import net.sf.json.JSONObject;
import org.junit.Rule;
import org.junit.Test;
import org.kohsuke.stapler.HttpResponse;
import org.kohsuke.stapler.QueryParameter;
import org.kohsuke.stapler.WebMethod;
import org.kohsuke.stapler.json.JsonBody;
import org.kohsuke.stapler.json.JsonHttpResponse;
import org.kohsuke.stapler.verb.GET;
import org.kohsuke.stapler.verb.POST;


@Extension /* (2) */
public static class JsonAPI implements RootAction /* (3) */ {

    @CheckForNull
    @Override
    public String getIconFileName() {
        return null; /* (4) */
    }

    @CheckForNull
    @Override
    public String getDisplayName() {
        return null; /* (5) */
    }

    @Override
    public String getUrlName() {
        return "custom-api"; /* (6) */
    }

    @GET
    @WebMethod(name = "get-example")/* (7) */
    public /* (8) */ JsonHttpResponse getExample() {
        JSONObject response = JSONObject.fromObject(new MyJsonObject("I am Jenkins"));
        return new JsonHttpResponse(response, 200); /* (9) */
    }

    @GET
    @WebMethod(name = "get-example-param")
    public JsonHttpResponse getWithParameters(
        @QueryParameter(required = true) String paramValue /* (9) */) {

        assertNotNull(paramValue);
        MyJsonObject myJsonObject = new MyJsonObject("I am Jenkins " + paramValue);
        JSONObject response = JSONObject.fromObject(myJsonObject);
        return new JsonHttpResponse(response, 200);
    }

    @GET
    @WebMethod(name = "get-error500")
    public JsonHttpResponse getError500() { /* (10) */
        MyJsonObject myJsonObject = new MyJsonObject("You got an error 500");
        JSONObject jsonResponse = JSONObject.fromObject(myJsonObject);
        JsonHttpResponse error500 = new JsonHttpResponse(jsonResponse, 500);
        throw error500;
    }
}
----

1. Non exhaustive list of imports to use.
2. Must be an extension to be discovered as a service by Jenkins.
3. This class is an extension of RootAction.  It is a way to expose HTTP paths that is more frequently used to expose the Web UI, but it can also be used without HTML rendering.
4. Since there is no HTML/Jelly rendering, no icons are needed.
5. Since there is no HTML/Jelly rendering, no display name is needed.
6. `getUrlName()` is the root of the JSON API.  Each WebMethod in the class is prefixed by this.
7. `@GET` indicates the HTTP method that is expected, and `@WebMethod` indicates that it is accepting an HTTP request. By default, the JAVA name of the WebMethod is used, but a different name can be specified by using `name =`
8. `JsonHttpResponse` is a sub class of `HttpResponse` that indicates that the response content will be JSON
9. An HTTP status can be set in the response.
10. The method `get-error500` is added in the example to show how to set a error response as JSON.


=== Testing with CURL

A `mvn hpi:run` in the plugin should be enough to run it locally.  Assuming that Jenkins is up at http://localhost:8080/jenkins/ , you should have at this point:

[source,bash]
----
curl -XGET \
    -w "\n STATUS:%{http_code}"  \
    http://localhost:8080/jenkins/custom-api/get-example-param?paramValue=hello

{"message":"I am Jenkins hello"}
 STATUS:200
----

=== Example of test with JenkinsRule

[source,java]
----
public class JsonAPITest {

    @Rule
    public JenkinsRule j = new JenkinsRule();

    private static String GET_API_URL = "custom-api/get-example-param?paramValue=hello";

    @Test
    public void testGetJSON() throws Exception {

        // Testing a simple GET that should answer 200 OK and a json
        JenkinsRule.JSONWebResponse response = j.getJSON(GET_API_URL);
        assertTrue(response.getContentAsString().contains("I am JenkinsRule hello"));
        assertEquals(response.getStatusCode(), 200);
    }

    @Test
    public void testAdvancedGetJSON() throws Exception {
        //Testing a GET that requires the user to be authenticated
        User admin = User.getById("admin", true);
        MockAuthorizationStrategy auth = new MockAuthorizationStrategy()
                .grant(Jenkins.ADMINISTER).everywhere().to(admin);

        j.jenkins.setSecurityRealm(j.createDummySecurityRealm());
        j.jenkins.setAuthorizationStrategy(auth);

        //We need to setup the webclient
        //By default if the status code is not ok, WebClient throw an exception
        //Since we want to assert the error status code, we need to set to false.
        JenkinsRule.WebClient webClient = j.createWebClient();
        webClient.setThrowExceptionOnFailingStatusCode(false);

        // - simple call without authentication should be forbidden
        response = j.getJSON(GET_API_URL, webClient);
        assertEquals(response.getStatusCode(), 403);

        // - same call but authenticated using withBasicApiToken() should be fine
        response = j.getJSON(GET_API_URL, webClient.withBasicApiToken(admin));
        assertEquals(response.getStatusCode(), 200);
    }

----

=== Handling POST with Jenkins

Starting from the class `JsonAPI` provided for GET example, add:

[source,java]
----
@POST
@WebMethod(name = "")
public JsonHttpResponse create(@JsonBody JSONObject body) {
    MyJsonObject parsedBody = (MyJsonObject) body.toBean(MyJsonObject.class);
    //Do any logic required for creation
    //For the example purpose we just unmarshall and recreate json
    JSONObject response = JSONObject.fromObject(parsedBody);
    return new JsonHttpResponse(response, 200);
}

----

=== Testing with CURL

A `mvn hpi:run` in the plugin should be enough to run it locally.  Assuming that Jenkins is up at http://localhost:8080/jenkins/ , you should have at this point:

Get the crumb.... TBD

Write a file `my.json` containing the JSON body:
[source,bash]
----
{"message":"A nice message to send"}
----

And then send the POST request:
[source,bash]
----
curl -XPOST \
    -H "Content-Type: application/json" \
    -H "Jenkins-Crumb: test" \
    http://localhost:40393/jenkins/testing-cli/postSomething \
    --data "@/my.json" \

{"message":"A nice message to send"}
 STATUS:200
----

=== Example of test with JenkinsRule

Starting from the class `JsonAPITest` provided for the GET example, add:

[source,java]
----
@Test
public void testPostJSON() throws Exception {

    MyJsonObject objectToSend = new MyJsonObject("Jenkins is the way !");
    JenkinsRule.JSONWebResponse response = j.postJSON("testing-cli/postSomething", jsonBody);

    //because API is returning the same object, we assert the input message.
    assertTrue(response.getContentAsString().contains("Jenkins is the way !")); 
    assertEquals(response.getStatusCode(), 200);
}
----