---
layout: post
title: "Blue Ocean Release - 1.5.0"
tags:
- jenkins
- blueocean
- plugins
author: jennbriden
---

Hello, I am Jenn Briden, the new Product Manager for Blue Ocean and the Jenkins pipeline at CloudBees. I am based out of the Seattle area and am excited to be working on Jenkins. :D 

== Release Overview
We released version 1.5.0 of the Blue Ocean plugin late last week. If you're using Blue Ocean, you'll want to grab this update since it includes many improvements and bug fixes. 

== Update Your Plugin
Plugin updates in Jenkins are available in the Plugin Manager Update Center. This page includes instructions for using the UI and CLI to update your plugins: https://jenkins.io/doc/book/managing/plugins/. 

If you are using the Blue Ocean UI, click Administration in the page's header to open Plugin Manager.

Installing the primary Blue Ocean plugin will update its dependencies as well.

== Review Updates in this Release
=== Reordering Steps in the Pipeline Editor
In the pipeline editor, a developer can drag and drop steps to reorder them in the list.  https://issues.jenkins-ci.org/browse/JENKINS-38323   

=== Visualization of Downstream Jobs 
Blue Ocean now includes a user interface update to show the downstream jobs launched with the 'build' step.  https://issues.jenkins-ci.org/browse/JENKINS-38339

=== Pagination Support for the Artifacts Tab
Developers can now paginate through the Artifacts tab. Previously, this list was cut off at 100 entries.  https://issues.jenkins-ci.org/browse/JENKINS-43588

=== Improvements for Dashboard Loading Time 
There are two fixes in 1.5.0 for reducing the time it takes for dashboards to load in Blue Ocean. 

* https://issues.jenkins-ci.org/browse/JENKINS-44995 
* https://issues.jenkins-ci.org/browse/JENKINS-48868

=== Support for Failed Build Output for Pipelines with No Stages
For developers who have no stages/steps defined in their pipelines, they can now see the full log output for failed runs. This update helps with pipeline debugging in Jenkins.  https://issues.jenkins-ci.org/browse/JENKINS-48074

=== Support for Wrapping Long Lines in the Log 
This update adds support for wrapping log lines in Blue Ocean. Previously, a single, long line of output in the log wouldn't be fully visible in the log window.
https://issues.jenkins-ci.org/browse/JENKINS-49036

=== Bug Fix: Input Steps in Post Directive Step Does Not Prompt 
This bug fix resolves the issue where Blue Ocean would not prompt the user for input when running a pipeline block Post step configured to request user input.
https://issues.jenkins-ci.org/browse/JENKINS-49297


== View the Detailed Change Log
https://wiki.jenkins.io/display/JENKINS/Blue+Ocean+Plugin

== Providing Feedback
* Chat with us at Gitter: https://gitter.im/jenkinsci/blueocean-plugin
* Report issues at https://issues.jenkins-ci.org/