---
layout: post
title: "Jenkins X making awesome progress after 23 days"
tags:
- jenkins-x
- kubernetes
- pipeline
author: jstrachan
---

Its been 23 days since we https://jenkins.io/blog/2018/03/19/introducing-jenkins-x/[announced Jenkins X],
a CI/CD solution for modern cloud applications on Kubernetes. 
I'm truly blown away by the response and feedback from the community - thank you!

We've also had lots of folks report they've successfully used http://jenkins-x.io/[Jenkins X] 
on a number of clouds including GKE, AWS and AKS along with on premise clusters which is great to hear!

Here's a brief overview of the changes in the last 23 days from the http://jenkins-x.io/contribute/roadmap/[Roadmap]:

* we now fully support GitHub and GitHub enterprise. BitBucket cloud and gitea is almost there too. 
  Hopefully BitBucketServer and Gitlab are not too far away either. For more detail see 
  http://jenkins-x.io/developing/git/[supporting different git servers]
* For issue tracking we support GitHub, GitHub Enterprise and JIRA. For more detail see 
  http://jenkins-x.io/developing/issues/[supporting issue trackers]
* Gradle support is now available from http://jenkins-x.io/developing/create-spring/[jx create spring]
  or by importing gradle apps
* Go, Node and Rust build packs are now available with more http://jenkins-x.io/contribute/roadmap/[planned]
* New _addons_ for https://anchore.com/[anchore] and http://kubeless.io/[kubeless]

Also we've made it a little bit easier to keep your `jx` binary up to date _continuously_. Just type

* http://jenkins-x.io/commands/jx_version/[jx version] to get prompted if there is a new version available
  and if prompted, it will upgrade itself
* http://jenkins-x.io/commands/jx_upgrade_cli/[jx upgrade cli] will upgrade the `jx` binary if its available or
  http://jenkins-x.io/commands/jx_upgrade_platform/[jx upgrade platform] for the platform


For more detail on the changes over the last 23 days with metrics please see the 
http://jenkins-x.io/news/changes-april-11-2018/[changelog generated by Jenkins X]

We'd love to hear your feedback what you think of 
http://jenkins-x.io/[Jenkins X] and the
http://jenkins-x.io/contribute/roadmap/[Roadmap] - please 
http://jenkins-x.io/community/[join the community].

== Links

* http://jenkins-x.io/[Jenkins X website]
* http://jenkins-x.io/demos/[Demos]
* https://github.com/jenkinsci/jep/tree/master/jep/400[Jenkins X JEP proposal]
