---
layout: gsodproject
title: "Document Jenkins on Kubernetes"
goal: "Create a new Kubernetes Volume which would describe the concepts, techniques, and choices for Kubernetes users running Jenkins."
category: Documentation
year: 2020
sig: jenkins-documentation
status: "Active"
technicalWriter: zaycodes
mentors:
- oleg_nenashev
- markewaite
- kwhetstone
- markyjackson-taulia
links:
  gitter: jenkins/docs:matrix.org
  draft: https://docs.google.com/document/d/1zTEKtOp2i1K2fw5RQ_a_KVOB2z0gz9987NYzTnIS6G8/edit?usp=sharing
  idea: /sigs/docs/#jenkins-on-kubernetes
tags:
- gsod2020
- kubernetes
- documentation
- guide
---

=== Abstract

Kubernetes is a platform-agnostic container orchestration tool created by Google and heavily 
supported by the open-source community as a project of the Cloud Native Computing Foundation. 
It allows you to use container instances and manage them for scaling and fault tolerance. 
It also handles a wide range of management activities that would otherwise require separate solutions or custom code, 
including request routing, container discovery, health checks, and rolling updates.

Kubernetes is compatible with the majority of CI/CD tools which allow developers to run tests, 
deploy builds in Kubernetes and update applications with no downtime. 
One of the most popular CI/CD tools now is Jenkins for the following reasons:
It is open-source and free.
it is user-friendly, easy to install and does not require additional installations or components.
Jenkins is also quite easy to configure, modify and extend. 
It deploys code instantly, generates test reports. 
Jenkins can be configured according to the requirements for continuous integrations and continuous delivery.
Jenkins is available for all platforms and different operating systems, whether it is OS X, Windows or Linux. 
It also boasts a rich plugin ecosystem. 
The extensive pool of plugins makes Jenkins flexible and allows building, 
deploying and automating across various platforms.
Most of the integration work is automated. 
Hence fewer integration issues. 
This saves both time and money over the lifespan of a project.

The following reasons have made Jenkins on Kubernetes a popular theme for Jenkins users, 
however, there’s currently no central location for documentation describing Jenkins on Kubernetes, 
thereby making it difficult for Jenkins on Kubernetes users to navigate and find information. 
This project would create a new Kubernetes Solutions page which would describe the concepts, 
techniques, and choices for Kubernetes users running Jenkins.

=== Current State

There are a lot of presentations and articles about running Jenkins on Kubernetes, 
however, there’s no central location for describing Jenkins on Kubernetes. 
This makes it difficult for:
Jenkins on Kubernetes users to navigate and find informationTrack, 
update and maintain information on Jenkins on Kubernetes. 

=== Deliverables

* Create a new Kubernetes Volume which would describe the concepts, 
techniques, and choices for Kubernetes users running Jenkins.


=== Reaching Out

Feel free to reach out to us for any questions, feedback, etc. on the project's
link:https://app.gitter.im/#/room/#jenkins/docs:matrix.org[Gitter Channel].

=== Other Links

* https://docs.google.com/document/d/1zTEKtOp2i1K2fw5RQ_a_KVOB2z0gz9987NYzTnIS6G8/edit?usp=sharing[GSoD Proposal] +
* https://docs.google.com/document/d/17cPLUrJ4Ul4Y8MREjDyfWBEN7PlnlrmPh6wuKMPFmPg/edit?usp=sharing[GSoD Office Hours Notes] +
* https://docs.google.com/document/d/1m0rTrXk7WisPXUeaKGj81dOFO2CcW4o_Nvo7NvcoL98/edit?usp=sharing[Google Season of Docs - Startup] +
