---
:layout: post
:title: A Big Step of the Chinese Localization
:tags:
- general
- community
- localization
- chinese
:author: linuxsuren
---

Since 2017, I started to do some contributions to the Jenkins community. As a beginner, translation might be
the easiest way to help the project. You don't need to understand the whole context, even to create a ticket in the
issue tracker system. Improvement of localization usually is minor. But some problems occurred soon,
there isn't a native speaker of Chinese that could review my PRs. So, sometimes my PRs
are delayed from being merged into master.

Some contributors told me that I can start a thread at the mailing list. Normally, discussing at the mailing list
is the open source community way. We got a lot of ideas for the localization from there. As a result,
we achieved some goals that I'd like to share here.

== JEP-216

Previously, language localization files were distributed in core and in each plugin.
For https://github.com/jenkinsci/jep/blob/master/jep/216/README.adoc[this proposal], each language has a single localization plugin, such as https://github.com/jenkinsci/localization-zh-cn-plugin[Chinese Localization plugin].
Finally, https://github.com/jenkinsci/localization-support-plugin[Localization Support Plugin] and
https://github.com/jenkinsci/localization-zh-cn-plugin[Chinese Localization plugin] are able to support
all types of localization resource files. From the https://plugins.jenkins.io/localization-zh-cn[plugins website],
you can see that there are already 13 000 installations.
We removed all Chinese localization files at the https://github.com/jenkinsci/jenkins/pull/4008[PR-4008].

I really appreciate https://github.com/daniel-beck[Daniel Beck] for helping me to add localization support,
https://github.com/bitwiseman[Liam Newman] helping me to review JEP-216, and many other community members.

== Chinese Localization SIG

We believe that this SIG could help to improve Jenkins experience for Chinese users and gather more contributors
from China. This SIG is responsible for maintaining the link:/zh/[Chinese Jenkins website],
promoting the Jenkins community in China in the social media with WeChat account. We publish translated blog
articles, Jenkins release notes, JAM or other events at the WeChat account. For now, there are 1800 followers that can
read our news from the last half a year.

Especially, I want to say thanks to https://github.com/donhui[Wang Donghui], https://github.com/zacker330[Zhai Zhijun], and other https://github.com/jenkins-infra/wechat/graphs/contributors[contributors]. They did a lot of contributions.
I wish I could see more and more folks join us.
