---
title: Agent &rarr; Controller Security Changes in 2.326
# TODO Mention the first LTS release with this change as well
layout: documentation
---

Jenkins 2.326 removes the ability to disable or customize the agent-to-controller security system.
This change is specified in https://github.com/jenkinsci/jep/tree/master/jep/235[JEP-235].

== Plugin Compatibility

Several plugins are known to be affected by this change.
For the following plugins, updates are available as of December 29, 2021:
// DATE SENSITIVE

* https://plugins.jenkins.io/cobertura/[Cobertura Plugin Plugin] needs to be updated to 1.17 or newer.
* https://plugins.jenkins.io/code-coverage-api/[Code Coverage API Plugin] needs to be updated to 2.0.4 or newer
* https://plugins.jenkins.io/log-parser/[Log Parser Plugin] needs to be updated to 2.2 or newer
* https://plugins.jenkins.io/maven-plugin/[Maven Integration Plugin] needs to be updated to 3.15.1 or newer
* https://plugins.jenkins.io/warnings-ng/[Warnings Next Generation Plugin] needs to be updated to 5.2.0 or newer
* https://plugins.jenkins.io/xunit/[XUnit Plugin] needs to be updated to 2.0.3 or newer
// XUnit is speculative, see JEP

Other plugins have not yet been adapted.
Their compatibility fixes are tracked in the Jira epic https://issue-redirect.jenkins.io/issue/67173[JENKINS-67173].


== API Compatibility

As part of the change in 2.326, almost all code related to the agent-to-controller security system's configuration has been removed.

A notable exception is `jenkins.security.s2m.AdminWhitelistRule` as that is used by https://plugins.jenkins.io/configuration-as-code/[Configuration as Code Plugin] and is also expected to be in frequent use in link:/doc/book/managing/groovy-hook-scripts/[Groovy init scripts].
It is now a stub retaining the basic API -- `#getMasterKillSwitch` and `#setMasterKillSwitch(boolean)`, but both methods only generate log messages informing users about their obsolescence.
Invocations of these methods can be safely removed when running Jenkins 2.326 or newer.
Users of Configuration as Code may remove the `remotingSecurity` section from

[source,yaml]
----
jenkins:
  remotingSecurity:
    enabled: true
----

// TODO Also mention first LTS here.
