---
layout: chapter
---
ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:hide-uri-scheme:
endif::[]

= Managing Jenkins

Most standard administrative tasks can be performed from the screens
in the *Manage Jenkins* section of the dashboard.
In this chapter, we look at these screens and explain how to use them.

Additional system administration topics are provided in
<<system-administration#,Jenkins System Administration>>.

The top of the *Manage Jenkins* screen may contain "Monitors"
that alert you when a new version
of the Jenkins software or a security update is available.
Each monitor includes links to the _changelog_ that describes the new update
as well as instructions to download and install the update.

The tiles displayed on the *Manage Jenkins* page are grouped logically.
Here we discuss the pages that are part of the standard installation.
Some plugins may add pages to this screen.

Inline help is available on most *Manage Jenkins* pages:

* To access the help, select the `?` icon to the right of each field.
* Click the `?` icon again to hide the help text.

Inline help is available on most *Manage Jenkins* pages:

* To access the help, select the `?` icon to the right of each field.
* Click the `?` icon again to hide the help text.

[NOTE]
====
The *Manage Jenkins* screens were modernized in 2020
to provide a more attractive user interface for all users
and a much better experience for users on narrow devices such as tablets and phones.
The main changes made were:

* Configuration screens used to use HTML `table` tags but now use HTML `div` tags.
* Older versions presented a long list of tasks in somewhat random order
rather than the logical groupings that are now used.
* Some configuration fields were moved or added.

For more information about these and other changes that have been implemented, see:

* link:https://www.jenkins.io/changelog-stable/[LTS Changelog]
* link:https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/[Jenkins 2.264+: Major changes in the weekly release line]
* link:https://www.jenkins.io/doc/upgrade-guide/[Jenkins LTS Upgrade Guide]
====

== System Configuration section

Screens for configuring resources for your Jenkins instance.

link:system-configuration[Configure System]::
Configure global settings and paths for the Jenkins instance

link:tools.adoc[Global Tool Configuration]::
Configure tools, their locations, and automatic installers

link:plugins.adoc[Manage Plugins]::
Add, update, remove, disable/enable plugins
that extend the functionality of Jenkins.

link:nodes.adoc[Manage Nodes and Clouds]::
Add, remove, control, and monitor the nodes used for the agents on which build jobs run.

link:casc.adoc[Configuration as Code]::
Configure your Jenkins instance using a human-readable YAML file.
This is an optional feature that appears here
only when the plugin is installed on your controller.

== Security section

Screens for configuring security features for your Jenkins instance.
See link:/doc/book/security/[Securing Jenkins] for general information
about managing Jenkins security.

link:system-configuration.adoc[Configure Global Security]::
Set configuration parameters that secure your Jenkins instance.

*Manage Credentials*::
Configure the credentials that provide secure access
to third-party sites and applications that interact with Jenkins.

*Configure Credential Providers*::
Configure credential providers and types

link:users.adoc[Manage Users]::
Manage users defined in the Jenkins user database.
This is not used if you use a different security realm such as LDAP or AD.

== Status Information section

link:system-info.adoc[System Information]::
Displays information about the Jenkins environment.

*System Log*::
Jenkins log that contains all `java.uil.logging` output related to Jenkins.

*Load Statistics*::
Displays information about resource utilization on you Jenkins instance.

*Disk usage*::
Simple disk usage estimation

link:about-jenkins.adoc[About Jenkins]::
Provides version and license information for your Jenkins instance.

== Troubleshooting section

*Manage Old Data*::
Remove configuraion information related to plugins that have been removed from the instance.

== Tools and Actions section

Screens for common management tasks
and management tools that enable you to do administrative tasks without using the UI.

*Reload Configuration from Disk*::
Discard all data that is loaded in memory and reload everything from the file system.
This is useful when you modify configuration files directly on disk.

link:cli-adoc[Jenkins CLI]::
How to use the Jenkins CLI from a shell or script.

*Script Console*::
Execute an Apache Groovy script for administration, troubleshooting, and diagnostics.

*Prepare for Shutdown*::
Prevents new builds from starting so that the system can be shut down safely.

== Uncategorized section

Screens for monitoring the Jenkins controller and agents
and for launching build agents as Docker containers.

*Monitoring of Jenkins controller*::
Monitors memory, cpu, http requests and more on the Jenkins controller.

*Monitoring of Jenkins agents*::
Monitors builds, the build queue, and Jenkins agents.

*Docker*::
Plugin for launching build agents as Docker containers.

