---
layout: section
title: Configuring the System
---
ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc: left
endif::[]


Jenkins can be configured at many levels and with many different techniques.
Your final configuration depends directly on which problems you want to solve.

Jenkins has a specific area all configurations items can be accessed.
Configuration layers might include Jenkins master configuration, 
link:/doc/book/using/using-agents/[agents configuration],
link:/doc/book/system-administration/security/[security configuration].

Configuration pages are frequently created and expanded by plugins, maybe already exists a plugin to resolve your needs.
Consider visiting the link:https://plugins.jenkins.io/[Jenkins plugin site] to check if any of them could be useful to you.

Configuration techniques might include:

== Configuration from the UI

The UI configuration is available under the Manage Jenkins menu item. 
There exists 3 main sections: System Configuration, Security, Status Information.
each one has their own options:

=== System Configuration options

==== Configure System

The Configure System has native options and can receive new ones from plugins.
The main Jenkins installation can be modified by plugins, such as System message, data and time format, Jenkins locations, SMTP Server, and others.

==== Global Tool Configuration

The Global Tool Configuration keeps together all information about the tool which Jenkins uses to run each task.
Maven, JDK, Git, Gradle, and Ant are tools present at default installations.

==== Manage Plugins

The Manage Plugins is the place where is possible to add, update, remove, or know more about plugins.
It is possible to request plugins from the web or uploads your own plugin by upload field.
Unter the advanced section it is possible to set the proxy configurations or changes the Update site URL.

==== Manage Nodes and Clouds

The Manage Nodes and Clouds menu is responsible for managing all information about all Jenkins agents.
from the initial page, you can add, remove, enable, or not.
Please visit the link:/doc/book/using/using-agents/[agents configuration page] to know more about it.

=== System Security options

==== Configure Global Security 

The Configure Global Security has all basic configuration to general security such as Authentication methods where it is possible
set Jenkins to use their own database or LDAP use, or set the strategy to authorization and others. 
The link:/doc/book/system-administration/security/[Security page] has all informations about the Jenkins  security.

==== Manage Credentials

The Manager Credentials is the right place to store all your credentials access to several services like ssh key, git, svn, and others.

==== Configure Credential Providers

==== Manager Users

The Manager Users menu is the place where it is possible to access information about users in the Jenkins’ own user database.
Visit the link:/doc/book/system-administration/authenticating-scripted-clients/[Script Authentication Clients page] to learn how to auth clients using the API.

=== Status Information

==== System Information

The System Information shows all information about the Jenkins installation. The Page show:
* System Properties
* Environment Variables
* Plugins
* Memory Usage
* and Thread Dumps

==== System Log

The link/doc/book/system-administration/monitoring/[System Log] offers a visual view to access the main system logs. 
Log messages at log levels lower than INFO are not recorded in the Jenkins Log page by default. 
Visit the Use log recorders to record these log messages.

It is possible to get the logs by RSS too. Or visit the link:/doc/book/system-administration/viewing-logs/[Log's page] to more details about how to access the logs from a program.

The link:/doc/book/system-administration/viewing-logs/[View logs page] can offer more tips about the Jenkins log's too.


==== Load statistics 

The Load statistics show a chart over time with data about:
* Number of online executors
* Number of busy executors
* Number of available executors
* Queue length

The graph is an exponential moving average of periodically collected data values. 3 timespans are updated every 10 seconds, 1 minute and 1 hour respectively.

==== About Jenkins

The About Jenkins page is similar to the System Information, but here it is show information about Jenkins depends on the following 3rd party libraries,
Static resources, License, and dependency information for plugins

== Configuration from REST API calls

Jenkins offers a rich API to fetch information or send requests, link:https://www.jenkins.io/doc/book/using/remote-access-api/[The page remote access api] has instructions about how to use it.

== Configuration from system level groovy scripts

It is possible to use groovy scripts to execute some actions. To know more about or learn how tu use this technique visite the page link:/doc/book/managing/groovy-hook-scripts/[Groovy Hook Scripts] 

== Configuration from Jenkins command line interface (CLI)

Jenkins has a built-in command line interface that allows users and administrators to access Jenkins from a script or shell environment. This can be convenient for scripting of routine tasks, bulk updates, troubleshooting, and more.
link:/doc/book/managing/cli/[The Jenkins CLI page] has instructions obout how to use the CLI.
