---
layout: gsocproject2
title: "Add probes to \"Plugin Health Score\""
goal: "First iteration of the tool provided a limited set of probes. To improve the effectiveness of the scoring system, more probes are needed."
category: Tools
year: 2023
tags:
- gsoc2022
- plugins
status: "Selected"
sig: platform
student: "jagruti"
mentors:
- "alecharp"
- "dheerajodha"
- "mostafaashraf"
links:
    idea: /projects/gsoc/2023/project-ideas/add-probes-to-plugin-health-score
    gitter: jenkinsci_GSoC-Plugin_Health_Score:gitter.im
    draft: https://drive.google.com/file/d/1VEd-RDpJglWMMZApkQ0cn3Xujfj4sXW6/view
    meetings: /projects/gsoc/#office-hours
---
=== Abstract

The project proposes to add new probes to the Plugin Health Score tool.
Originally started in 2022 as a part of a GSoC project, this tool determines the health score of a plugin.
Probes are the heart of the tool.
To extend the work started last year, I propose adding new probes to make the tool more valuable and feature-complete.

=== Rationale

In general, probes serve two purposes within the context of this toolset:

* To collect the data to compute the score of the plugin systematically. 
Based on the computed score, the health of the plugin can be determined.
* Based on the score future contributors, maintainers, and adopters decide which plugin(s) they want to invest their time in.

To enhance the effectiveness and usefulness of the Plugin Health Scoring System for the community, I propose to expand the number of probes used to gather data on plugin performance.

While the current probes provide valuable insights, they may not capture all the necessary criteria to fully evaluate the health of a plugin.
Adding more probes can provide a more comprehensive and accurate assessment of plugin health, benefiting a wider range of users.


=== Implementation
The project will be implemented in three parts:

* Interaction of probes with each other
* Probe's execution order
* Probe's scoring

Finally, the health percentage of the probe will be determined.

Health percentage categories

* Low health: < Q1 (25th percentile)
* Medium health: > Q1 (25th percentile) and < (75th percentile)
* High health: > Q3 (75th percentile)

=== Office hours
* (General) Official weekly Jenkins office hours: Thursdays 15:00 UTC
* (Project-based) Weekly project based office hours: Tuesdays 14:30  UTC

=== References

* https://docs.google.com/document/d/1QcwSiAuQtoy4dGlPXgY3w8FjDzTJn-3yCv75U-OFJ04/edit[Meeting notes]
