---
layout: gsocproject2
title: "Building Jenkins.io with alternative tools"
goal: "Using alternative tooling (i.e., Antora) to build the Jenkins static site and provide documentation per Jenkins version"
category: Tools
year: 2023
status: "Selected"
sig: documentation
tags:
- gsoc2023
- doc
student: vandit1604
mentors:
- "krisstern"
- "iamrajiv"
- "YimingGong"
- "markewaite"
links:
    idea: /projects/gsoc/2023/project-ideas/alternative-jenkinsio-build-tool
//   matrix: https://matrix.to/#/#jenkinsci_gsoc-2023-building-jenkinsio:matrix.org
//   draft: https://docs.google.com/document/d/1RS7-NO9shIaF2xZzYnAXTbSvpRNxoZMI7cJ5q5bc-h8/edit?usp=sharing
//   meeting: "/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool/#office-hours"
---

=== Abstract

The goal of this project is to build the Jenkins.io static site with alternative tools such as Antora and Gatsby.
We will divide the current site into sections.

- Blogs
- Documentation (both user and developer)
- Changelogs and Roadmaps

The preferred tools for the blogs, changelogs and roadmaps is Gatsby while Antora is preferred for the rest of the site.

=== Rationale

One of the drawbacks of the current build method is that the technical documentation is not product version bound. 
It is thus not possible to view the documentation for a given Jenkins version. 
Only the latest can be viewed. 
This can lead to unnecessary confusion and affects the overall User Experience.

Another reason is that Awestruct hasn't released a new version in more than two years, three months as of this writing.
It doesn't seem useful to rely on it continuously.

=== Implementation


=== Office hours

Details about the Office Hours (general or specific)

=== Links

Here come some useful links
