---
layout: gsocproject2
title: "Docker-based Jenkins quickstart examples"
goal: "Provide examples, sample code, and documentation on how to start a local Jenkins instance."
category: Tools
year: 2023
status: "Selected"
sig: platform
tags:
- gsoc2023
- doc
status: "Selected"
student: "ash-sxn"
mentors:
- "gounthar"
- "berviantoleo"
- "sbostandoust"
links:
    idea: "/projects/gsoc/2023/project-ideas/docker-compose-build/"
//   slack: "https://cdeliveryfdn.slack.com/archives/C0581AGMYQ0"
//   draft: https://docs.google.com/document/d/1ZpPihadYqpAvR20rxZkTD2SVpf34E6YMzg6opU6yHAg/edit?usp=sharing
//   meeting: /projects/gsoc/2023/projects/docker-compose-build.adoc#office-hours
---

=== Abstract

The project aims to simplify the use of Jenkins with Docker by creating easy-to-use Docker Compose files with suitable examples. Weekly testing with ci.jenkins.io and up-to-date documentation will be crucial, with the goal of enabling users to quickly spin up containers.

=== Rationale

Currently The process of getting started with Jenkins with docker is too complex. The available documentation is also hard to understand making it challenging for new users to get started. We will use Docker Compose to make it easier for beginers and coustomizable for experienced users

=== Implementation
Using Docker Compose to define and run a multi-container Docker application for Jenkins, simplifying the setup process. Automated Testing with a Jenkins Pipeline running on ci.jenkins.io, using a Jenkinsfile that checks the functionality of compose files. Keeping documentation up to date by using Pipeline Steps doc generator. Utilizing Gitpod for quick start, with a .gitpod.yml file that runs docker-compose commands and opens a preview of the Jenkins instance in Gitpod.

=== Office hours
* (General) Official weekly Jenkins office hours: Thursdays 15:00 UTC

