---
layout: gsocproject3
title: "Docker-based Jenkins quickstart examples"
goal: "Provide examples, sample code, and documentation on how to start a local Jenkins instance."
category: Tools
year: 2023
status: "Selected"
sig: platform
tags:
- gsoc2023
- doc
status: "Selected"
student: "ash-sxn"
mentors:
- "gounthar"
- "berviantoleo"
- "sbostandoust"
links:
    idea: "/projects/gsoc/2023/project-ideas/docker-compose-build/"
    Gitter: "https://matrix.to/#/#gsoc-2023-docker-quickstart:matrix.org"
    draft: https://docs.google.com/document/d/1ZpPihadYqpAvR20rxZkTD2SVpf34E6YMzg6opU6yHAg/edit?usp=sharing
    meeting: /projects/gsoc/#office-hours
---

=== Abstract

The project aims to simplify the use of Jenkins with Docker by creating easy-to-use Docker Compose files as suitable examples on which new documentation will be based. Weekly testing with `ci.jenkins.io` and up-to-date documentation will be crucial, with the goal of enabling users to quickly spin up containers.

=== Rationale

Currently the quickstart process with Jenkins using the existing Docker examples is too complex. The available documentation is also hard to understand (due to its opaqueness) making it challenging for new users to get started. We will be using Docker Compose to make it easier for beginners to pick up and for experienced users to customize.

=== Implementation
By using Docker Compose to define and run a multi-container Docker application for Jenkins, we can simplify the entire setup process. We will use automated testing in a Jenkins pipeline running on `ci.jenkins.io`, while using a `Jenkinsfile` to check the functionality of the Docker Compose files. We will also keep the documentation up to date by using Pipeline Steps documentation generator, as well as doing the appropriate updating/editing of the existing documentation Docker section. By utilizing Gitpod for quickstart, with a `.gitpod.yml` file that runs docker-compose commands, previews of the Jenkins instance in Gitpod can be made available quite readily.

=== Office hours
* (General) Official weekly Jenkins office hours: Thursdays 15:00 UTC
* (Project-based) Weekly project based office hours: Mondays 08:00 UTC


=== Links
* General office hours meeting can be attended link:https://zoom.us/j/93082176149[here]
* Project specific office hours can be attended link:https://zoom.us/j/92846964984[here]
* Project specific office hours meeting notes can be found link:https://docs.google.com/document/d/1yij9OvM2_92My3vqjn6u8ABHjXcyy0a7O6oM30b6ctM/edit[here]
* Recordings of these weekly project meetings can be found on the Discourse post link:https://community.jenkins.io/t/docker-quick-start-examples-gsoc-2023/7479[here]
* Gitter channel dedicated to this project can be joined link:https://matrix.to/#/#gsoc-2023-docker-quickstart:matrix.org[here]
