---
layout: gsocproject2
title: "GitLab Plugin Modernization"
goal: "Cleaning and modernizing the extensively used GitLab plugin"
category: Plugin improvement
year: 2023
status: "Selected"
sig: platform
tags:
- gsoc2023
- plugins
student: harsh-ps-2003
mentors:
- "markewaite"
- "krisstern"
- "freyam"
links:
  idea: /projects/gsoc/2023/project-ideas/gitlab-plugin-modernization
  gitter: jenkinsci_gitlab-plugin:gitter.im
  draft: https://docs.google.com/document/d/1fRTWTV2zwLnhWmylavKgQ30apHamrHRfJkK5s_acw7c/edit?usp=sharing
  meetings: "/projects/gsoc/2023/projects/gitlab-plugin-modernization/#office-hours"
---

=== Abstract

The GitLab plugin enables Jenkins to seamlessly interact with GitLab allowing it to automatically trigger builds, deploy code, etc. on the basis of GitLab events like Push, Merge Requests and more.
This project will replace usages of the very old version of the link:https://resteasy.dev/[RESTEasy] library
with usages of https://github.com/gitlab4j/gitlab4j-api[`gitlab4j-api`]
via the plugin:gitlab-api[GitLab API] Jenkins library plugin,
normalizing the GitLab plugin's use of the GitLab API with regard to
the plugin:gitlab-oauth[GitLab Authentication],
plugin:gitlab-branch-source[GitLab Branch Source],
and plugin:gitlab-logo[GitLab Logo] plugins.

=== Rationale

The plugin will be modernized to reduce future maintenance and improve implementation consistency with the other GitLab plugins.
Users will benefit from the actively supported GitLab4J-API and avoid the issues seen with the RESTEasy implementation.

=== Implementation

The old RESTEasy's Implementation will be ripped off from the codebase and instead GitLab4J-API will be used for V4 GitLab API calls (support for GitLab V3 API calls has been removed from GitLab server) and the tests will be adapted respectively. 
Care will be taken that the errors propagates correctly and no regression for the edge cases related to Proxy Servers happens.
The migration will be tested thoroughly in the Production environment before release.

=== Office hours

* (General) Official weekly Jenkins office hours: Thursdays 15:00 UTC
* (Project-based) Details regarding the Weekly project-specific office hours can be found inside our link:https://docs.google.com/document/d/18JrgxI9TucuqbKDycXBdVCWvBAvdqY5RgpY-UUKNc-4/edit#heading=h.iiyb3sq4n3xo[Meeting Document], along with important links.

=== Links

*link:https://app.gitter.im/#/room/#jenkinsci_gsoc-sig:gitter.im[GSoC-SIG]
*link:https://www.jenkins.io/projects/gsoc/2023/project-ideas/gitlab-plugin-modernization/[GitLab Plugin Modernization]
*link:https://github.com/jenkinsci/gitlab-plugin[GitHub repository]
*link:https://docs.google.com/document/d/1PKYIpPlRVGsBqrz0Ob1Cv3cefOZ5j2xtGZdWs27kLuw/edit#[Contributing to Open Source]
