---
:layout: post
:title: "Jenkins Board and Officer Elections 2023 - Nominations Open"
:tags:
- community
- governance
- governance-board
- elections
authors:
- notmyfault
description: >
  Nomination and voter registration period 2023 now open for Jenkins Board and officer elections.
opengraph:
  image: /images/governance/elections/2023/2023-announcement-opengraph.svg
---

**We are excited to announce the 2023 Jenkins Governance Board and officer elections!**

== Nominations

Nominations can be submitted for two link:/project/board/[governance board] positions, and all five link:/project/team-leads/[officer] positions (Security, Events, Release, Infrastructure, and Documentation).

During the registration period, we invite community members to nominate candidates by sending a message to the link:https://community.jenkins.io/g/election-committee[election-committee] group.
In your message, please include the name of the nominee, the specific position and your reasons for nominating that person.
The nomination period ends on *October 27*.
Nominees will be notified, and asked to confirm that they are interested in running as a candidate.
The list of candidates will be announced on November 06.

**Anyone can nominate anyone as candidate!**

Many thanks to link:https://github.com/oleg-nenashev[Oleg Nenashev] and link:https://github.com/markewaite[Mark Waite] for serving on the link:/project/board/[Jenkins Governance Board].
We also want to thank link:https://github.com/dduportal[Damien Duportal] as link:/project/team-leads/#jenkins-team-leads-and-officers[Infrastructure Officer], link:https://github.com/wadeck[Wadeck Follonier] as link:/project/team-leads/#security[Security Officer], link:https://github.com/alyssat[Alyssa Tong] as link:/project/team-leads/#events[Events Officer], link:https://github.com/timja[Tim Jacomb] as link:/project/team-leads/#release[Release Officer], and link:https://github.com/kmartens27[Kevin Martens] as link:/project/team-leads/#documentation[Documentation Officer] for all of their work over the last term.

== The election consists of 4 phases:

* Nomination of candidates (September 18 - October 27)
* Voter registration (September 18 - November 05)
* Voting (November 06 - December 1)
* Results announcement (December 11)

=== Voting

Participation in the election process requires registering an account on the link:https://community.jenkins.io[Jenkins community forums] and at least one contribution made before September 1, 2023.
When registering, you can use an existing GitHub account or create a new account specifically for link:https://community.jenkins.io[Jenkins community forums].
We ask all community members who are interested in voting and meet the requirements to join the link:https://community.jenkins.io/g/election-voter-2023[election-voter-2023] group during the registration period.
Previous elections utilized their own groups, so joining the link:https://community.jenkins.io/g/election-voter-2023[election-voter-2023] group is required for participation.

We have made the decision to trust participants and not require that you provide evidence of contribution as part of your voter registration.
We reserve the right to ban any account from the election process if we identify abuse.
Once registration is over, a list of email addresses will be sent to the link:https://civs1.civs.us/[Condorcet Internet Voting Service (CIVS)].

=== Contributing

As shown on the link:/participate/[Participate and Contribute] page, there are many different ways to contribute to Jenkins. You can contribute by:

* link:/participate/connect/[Connecting with the community]
* link:/participate/meet/[Joining or organizing a meetup]
* link:/participate/code/[Contributing code to Jenkins]
* link:/participate/help/[Helping Jenkins users]
* link:/doc/developer/internationalization/[Translating Jenkins resources]
* link:/participate/test/[Testing Jenkins core and plugins]
* link:/participate/document/[Contributing to Jenkins documentation]
* link:/participate/design/[Creating art or updating the Jenkins UI]
* link:/participate/review-changes/[Reviewing open pull requests]
* link:/donate/[Donating to Jenkins]

All contributions to Jenkins and its community are welcome

== Election

On November 06, candidates will be announced, and all registered voters will be notified by email to participate using the link:https://civs.cs.cornell.edu[Condorcet Voting System].
Registration to vote closes on November 05.
All votes must be submitted by December 1.

== Results

As soon as the votes are counted, the results will be published.
The new term starts on December 11, when the newly elected members will transition to their roles.

== Important Dates

[cols="1,1"]
|===
|Important Dates |Time

|Nomination of candidates open
|September 18

|Voter registration opens
|September 18

|Nomination of candidates closes
|October 27

|Voter registration closes
|November 05

|Candidates announced & Voting starts
|November 06

|Voting closes
|December 01

|Announcing Results
|December 11
|===

== Troubleshooting

If you are new to Jenkins elections, unfamiliar with the Condorcet Internet Voting Service (CIVS) or the community forums, or feel overwhelmed with the process, don't worry, we've got you covered. We published a link:/project/election-walkthrough/[step-by-step guide], outlining how to to join the link:https://community.jenkins.io/g/election-voter-2023[election-voter-2023], activate your CIVS account and cast your vote.

If you encounter issues still or need assistance, don't hesitate to contact the link:https://community.jenkins.io/g/election-committee[election committee].

Thank you, as always, and don't forget to register to vote by December 1!
