---
layout: subsection
title: Servlet Container Support Policy
---

This page documents the servlet container support policy for the Jenkins controller.

== Why?

Jenkins typically runs as a standalone application in its own process.
The Jenkins WAR file bundles link:https://github.com/jenkinsci/winstone[Winstone],
a link:https://www.eclipse.org/jetty/[Jetty] servlet container wrapper,
and can be started on any operating system or platform with a version of Java supported by Jenkins.
This is the preferred way to deploy Jenkins and is fully supported.

Theoretically, Jenkins can also be run as a servlet in a traditional servlet container
like link:https://tomcat.apache.org/[Apache Tomcat] or link:https://www.wildfly.org/[WildFly].
However, in practice, this is largely untested, and there are many caveats.
In particular, support for WebSocket agents is only implemented for the Jetty servlet container.

WARNING: Support for traditional servlet containers may be discontinued in the future.

== Support levels

We define multiple support levels for servlet containers.

[width="100%",cols="20%,35%,45%",options="header",]
|===
|Support level |Description |Servlet containers

| **Level 1:** Supported
| We run automated testing for these servlet containers, and we intend to fix reported issues in a timely manner.
a|The versions of Winstone and Jetty bundled in the Jenkins link:/doc/book/installing/war-file/[WAR file].

| **Level 2:** Patches considered
| Support may have limitations and extra requirements.
  We do not regularly test compatibility, and we may drop support at any time.
  We consider patches that do not put Level 1 support at risk and do not create maintenance overhead.
a|
  * Tomcat 9, based on Servlet API 4.0 (Jakarta EE 8) with `javax.servlet` imports. (2.474 and older)
  * WildFly 26, based on Servlet API 4.0 (Jakarta EE 8) with `javax.servlet` imports. (2.474 and older)
  * Other servlet containers that are based on Servlet API 4.0 (Jakarta EE 8) with `javax.servlet` imports. (2.474 and older)
  * Jetty 11 or later, based on Servlet API 5.0 (Jakarta EE 9) or later with `jakarta.servlet` imports. (2.475 and newer)
  * Tomcat 10 or later, based on Servlet API 5.0 (Jakarta EE 9) or later with `jakarta.servlet` imports. (2.475 and newer)
  * WildFly 27 or later, based on Servlet API 5.0 (Jakarta EE 9) or later with `jakarta.servlet` imports. (2.475 and newer)
  * Other servlet containers that are based on Servlet API 5.0 (Jakarta EE 9) or later with `jakarta.servlet` imports. (2.475 and newer)

| **Level 3:** Unsupported
| These versions are known to be incompatible or to have severe limitations.
  We do not support the listed servlet containers.
a|

|===

== References

* link:/doc/book/installing/servlet-containers/[Installation instructions]
* link:https://www.eclipse.org/jetty/[Jetty versions]
* link:https://tomcat.apache.org/whichversion.html[Tomcat versions]
* link:https://www.wildfly.org/news/2022/11/09/WildFly27-Final-Released/[WildFly 27 release announcement]

== Contributing

You are welcome to propose PRs that add support or documentation for other servlet containers or to share feedback;
we will appreciate your contributions!
Servlet container support in Jenkins falls under the link:/sigs/platform/[Platform Special Interest Group]
which has a link:https://app.gitter.im/#/room/#jenkinsci_platform-sig:gitter.im[chat], a link:https://community.jenkins.io/[forum]., and link:/sigs/platform/#meetings[regular meetings].
You are welcome to join these channels.
