---
layout: subsection
title:  Linux Support Policy
---

This page documents the Linux support policy for the Jenkins controller and agents.

== Scope

Individual Jenkins plugins may set additional requirements for Linux versions on controllers and/or agents.
This page does not document such requirements.
Refer to link:https://plugins.jenkins.io/[plugin documentation] for additional requirements.

== Why?

Theoretically, Jenkins can run everywhere where you can run a supported Java version,
but there are some limitations in practice.
Jenkins core and some plugins include native code or depend on Linux API and subsystems,
which make them dependent on specific Linux versions.
Jenkins platform specific installation packages rely on specific Linux versions.

== Support levels

We define multiple support levels for Linux platforms.

[width="100%",cols="20%,35%,45%",options="header",]
|===
|Support level |Description |Platforms

| **Level 1** - Supported
| We run automated package manager installation testing for these platforms, and we intend to fix reported issues in a timely manner.
  We recommend either package manager based installations or container based installations for Linux.
  Installations may also use `jenkins.war` without a package manager, though our automated testing focuses on package manager and container installations.
a|
  * 64-bit (amd64) Linux versions that use the Debian packaging format as link:https://ci.jenkins.io/job/Packaging/job/packaging/job/master/[tested on ci.jenkins.io]
  * 64-bit (amd64) Linux versions that use the Red Hat rpm packaging format as link:https://ci.jenkins.io/job/Packaging/job/packaging/job/master/[tested on ci.jenkins.io]
  * 64-bit (amd64) Linux versions that use the OpenSUSE rpm packaging format as link:https://ci.jenkins.io/job/Packaging/job/packaging/job/master/[tested on ci.jenkins.io]
  * 64-bit (arm64, s390x) Linux versions that use the Debian packaging format as link:https://ci.jenkins.io/job/Infra/job/acceptance-tests/[tested on ci.jenkins.io]
  * 64-bit (arm64, s390x) Linux versions that use the rpm packaging format as link:https://ci.jenkins.io/job/Infra/job/acceptance-tests/[tested on ci.jenkins.io]
  * Linux container images (amd64, arm64, s390x) as published for the link:https://hub.docker.com/r/jenkins/jenkins[controller] and various agents

| **Level 2** - Patches considered
| Support may have limitations and extra requirements.
  We do not test compatibility, and we may drop support at any time.
  We consider patches that do not put level 1 support at risk and do not create maintenance overhead.
a|
  * 32-bit (x86, arm) Linux versions
  * RISC-V and other architectures not included in level 1 support
  * Preview releases

| **Level 3** - Unsupported
| These versions are known to be incompatible or to have severe limitations.
  We do not support the listed platforms, and we do not accept patches.
a|
  * Linux versions no longer supported by operating system providers
|===

== References

* link:https://wiki.debian.org/LTS[Debian Long Term Support]
* link:https://access.redhat.com/support/policy/updates/errata[Red Hat Enterprise Linux Life Cycle]
* link:https://en.opensuse.org/Lifetime[openSUSE Product Support Lifecycle]
* link:https://ubuntu.com/about/release-cycle[Ubuntu lifecycle and release cadence]

== Contributing

You are welcome to propose PRs that add support for other Linux platforms or to share feedback;
we honestly appreciate your contributions!
Linux support in Jenkins is link:/sigs/platform/[Platform Special Interest Group]
which has a link:https://app.gitter.im/#/room/#jenkinsci_platform-sig:gitter.im[chat], a link:https://community.jenkins.io/[forum]., and link:/sigs/platform/#meetings[regular meetings].
You are welcome to join these channels.

== Version history

* March 2022 - First version
  (link:https://groups.google.com/g/jenkinsci-dev/c/cYi4GyG7Il8/m/oQ2m0C3UAgAJ[Discussion in the mailing list],
   link:https://community.jenkins.io/t/governance-meeting-jan-26-2022/1348[Governance meeting notes and recording])
