---
layout: subsection
title:  Java Support Policy
---

There are separate runtime and job execution requirements for Jenkins installations.

## Running Jenkins system

The following Java versions are required to run Jenkins:

|===
|Supported Java versions|Long term support (LTS) release|Weekly release

|Java 17 or Java 21|2.479.1 (October 2024) |2.463 (June 2024)
|Java 11, Java 17, or Java 21|2.426.1 (November 2023) |2.419 (August 2023)
|Java 11 or Java 17|2.361.1 (September 2022)|2.357 (June 2022)
|Java 8, Java 11, or Java 17|2.346.1 (June 2022)|2.340 (March 2022)
|Java 8 or Java 11|2.164.1 (March 2019)|2.164 (February 2019)
|Java 8|2.60.1 (June 2017)|2.54 (April 2017)
|Java 7|1.625.1 (October 2015)|1.612 (May 2015)
|===

[IMPORTANT]
.Supported Java versions
====
If you install an unsupported Java version, your Jenkins controller will not run.
====

These requirements apply to all components of the Jenkins system, including the Jenkins controller, all types of agents, CLI clients, and other components.
You do _not_ need to build your application with the same version of Java used to run Jenkins itself;
see the "Running Java-based tools and builds on Jenkins" section below.

[NOTE]
.Upgrading Java to a newer version
====
Upgrading an existing Jenkins setup to a newer version of Java?
Refer to the link:/doc/book/platform-information/upgrade-java-to-17[Java 11 to 17 upgrade guidelines] and the link:/doc/book/platform-information/upgrade-java-to-21/[Java 17 to 21 upgrade guidelines].
====

Docker installation instructions are included in link:/doc/book/installing/docker/#downloading-and-running-jenkins-in-docker["Downloading and running Jenkins in Docker"].

The Jenkins project performs a full test flow with the following JDK/JREs:

* OpenJDK JDK / JRE 17 - 64 bits
* OpenJDK JDK / JRE 21 - 64 bits

JRE/JDKs from other vendors are supported and may be used.
Refer to link:https://issues.jenkins.io/issues/?jql=labels%3Djdk[our issue tracker] for known Java compatibility issues.
Jenkins maintainers actively test link:https://en.wikipedia.org/wiki/HotSpot_(virtual_machine)[HotSpot based Java virtual machines] like those from OpenJDK, Eclipse Temurin, and Amazon Corretto.
Jenkins maintainers do not test link:https://en.wikipedia.org/wiki/OpenJ9[Eclipse OpenJ9 based Java virtual machines].
The link:/sigs/platform/[Platform Special Interest Group] does not actively work on OpenJ9 based Java virtual machines.

## Running Java-based tools and builds on Jenkins

The JDK versions used to build Java-based projects or run Java-based tools are independent from the version of Java used to run the Jenkins controller and agent processes.
During builds, any JRE or JDK version compatible with the host system can be launched.
This includes:

* Execution of `java` or `javac` from shell build steps and similar.
* Execution of Maven/Ant/… build steps using a JDK managed by a JDK link:https://plugins.jenkins.io/jdk-tool/[tool installer].

Some plugins have more strict requirements, and may require a build to execute the same Java version used to run the Jenkins controller and agents.
A notable plugin example is the plugin:maven-plugin[Maven Integration Plugin]. It requires the JDK version used for Maven builds to be at least the same Java version used in the Jenkins controller.
These cases are generally documented in the plugin documentation.
// This used to list Swarm Plugin Clients, but since they are agent processes that's kind of redundant.
// TODO This used to list docker-workflow, but it's unclear why.

## Monitoring Java versions

Modern Jenkins controllers and Jenkins agents verify Java requirements
and notify users when they are launched with an unsupported version.

The plugin:versioncolumn[Versions Node Monitors plugin] provides detailed Java version monitoring.

## JDKs used in Jenkins

The Jenkins project uses link:https://projects.eclipse.org/projects/adoptium.temurin[Eclipse Temurin] as its primary JDK for building and testing Java based applications.
This includes:

* Container Images
* Jenkins core release builds
* link:/doc/developer/publishing/releasing-cd/[Automated plugin releases]
* link:https://ci.jenkins.io[Continuous integration build and test]
* Testing Infrastructure

Some of the reasons for choosing Temurin are:

* Availability over many different Java SE versions and across a wide range of platforms, including different operating systems and architectures.
* Regular maintenance and long term support provided by the Eclipse Foundation.
