---
layout: subsection
title:  Java Support Policy
---

There are separate run and job execution requirements for Jenkins installations.

## Running Jenkins system

If you are installing or upgrading to Jenkins 2.357 or later, or to LTS 2.361.1 or later, Java 11 or 17 is required to run Jenkins.
link:/blog/2022/06/28/require-java-11/[Read more about this in the announcement blog post.]

[NOTE]
.Upgrading Java version to 11
====
Upgrading an existing Jenkins setup from Java 8 to Java 11?
Refer to the link:/doc/administration/requirements/upgrade-java-guidelines[upgrade guidelines].
====

## Running Jenkins on Java 11 in Docker

Java 11 Docker installation instructions are included in link:/doc/book/installing/docker/#downloading-and-running-jenkins-in-docker["Downloading and running Jenkins in Docker"].
Alternatively, the `jenkins/jenkins:jdk17` Docker image allows you to run the Jenkins controller on Java 17.

[IMPORTANT]
.Supported Java versions
====
Only Java 11 and Java 17 are supported. If you install an unsupported Java version, your Jenkins controller will not run. 
====

These requirements apply to all components of the Jenkins system, including the Jenkins controller, all types of agents, CLI clients, and other components.

The Jenkins project performs a full test flow with the following JDK/JREs:

* OpenJDK JDK / JRE 11 - 64 bits
* OpenJDK JDK / JRE 17 - 64 bits

JRE/JDKs from other vendors are supported and may be used.
Refer to link:https://issues.jenkins.io/issues/?jql=labels%3Djdk[our issue tracker] for known Java compatibility issues.
Jenkins maintainers actively test link:https://en.wikipedia.org/wiki/HotSpot_(virtual_machine)[HotSpot based Java virtual machines] like those from OpenJDK, Eclipse Temurin, and Amazon Corretto.
Jenkins maintainers do not test link:https://en.wikipedia.org/wiki/OpenJ9[Eclipse OpenJ9 based Java virtual machines].
The link:/sigs/platform/[Platform Special Interest Group] does not actively work on OpenJ9 based Java virtual machines.

## Running Java-based tools and builds on Jenkins

The JDK versions used to build Java-based projects or run Java-based tools are independent from the version of Java used to run the Jenkins controller and agent processes.
During builds, any JRE or JDK version compatible with the host system can be launched.
This includes:

* Execution of `java` or `javac` from shell build steps and similar.
* Execution of Maven/Ant/… build steps using a JDK managed by a JDK link:https://plugins.jenkins.io/jdk-tool/[tool installer].

Some plugins have more strict requirements, and may require a build to execute the same Java version used to run the Jenkins controller and agents.
A notable plugin example is the plugin:maven-plugin[Maven Integration Plugin]. It requires the JDK version used for Maven builds to be at least the same Java version used in the Jenkins controller.
These cases are generally documented in the plugin documentation.
// This used to list Swarm Plugin Clients, but since they are agent processes that's kind of redundant.
// TODO This used to list docker-workflow, but it's unclear why.

## Monitoring Java versions

Modern Jenkins controllers and Jenkins agents verify Java requirements
and notify users when they are launched with an unsupported version.

The plugin:versioncolumn[Versions Node Monitors plugin] provides detailed Java version monitoring.

## JDKs used in Jenkins

The Jenkins project uses link:https://projects.eclipse.org/projects/adoptium.temurin[Eclipse Temurin] as its primary JDK for building and testing Java based applications.
This includes:

* Container Images
* Jenkins core release builds
* link:/doc/developer/publishing/releasing-cd/[Automated plugin releases]
* link:https://ci.jenkins.io[Continuous integration build and test]
* Testing Infrastructure

Some of the reasons for choosing Temurin are:

* Availability over many different Java SE versions and across a wide range of platforms, including different operating systems and architectures.
* Regular maintenance and long term support provided by the Eclipse Foundation.
