---
layout: subsection
title:  Windows Support Policy
---

This page documents the Windows support policy for the Jenkins controller and agents.

== Scope

Jenkins plugins may set additional requirements to Windows versions on controllers and/or agents.
This page does not document such requirements.
Please refer to plugin documentation.

== Why?

Theoretically, Jenkins can run everywhere where you can run a supported Java version,
but there are some limitations in practice.
Jenkins core and some plugins include native code or depend on Windows API and subsystems,
and hence they rely on specific Windows platforms and versions.
In Windows services, we also use link:https://github.com/winsw/winsw[Windows Service Wrapper (WinSW)], which requires .NET Framework.

== Support levels

We define multiple support levels for Windows platforms.

[width="100%",cols="20%,35%,45%",options="header",]
|===
|Support level |Description |Platforms

| **Level 1** - Full support
| We run automated testing for these platforms, and we intend to fix reported issues timely.
a|
  * 64-bit (amd-64) Windows Server versions, with the latest GA update pack
  * Windows versions used in the official Docker images

| **Level 2** - Supported
| We do not actively test these platforms, but we intend to keep compatibility.
  We are happy to accept patches.
a|
  * 64-bit (amd-64) Windows Server versions generally supported by Microsoft
  * 64-bit (amd-64) Windows 10 and 11 versions generally supported by Microsoft

| **Level 3** - Patches considered
| Support may have limitations and extra requirements.
  We do not test compatibility, and we may drop support if there is a need.
  We will consider patches if they do not put Levels 1 or 2 support at risk and do not create maintenance overhead.
a|
  * x86 and other non-amd64 architectures
  * Non-mainstream versions, e.g., Windows Embedded
  * Preview releases
  * Windows API emulation engines, e.g., Wine or ReactOS

| **Level 4** - Unsupported
| These versions are known to be incompatible or to have severe limitations.
  We do not support the listed platforms, and we will not accept patches.
a|
  * Windows versions no longer supported by Microsoft
  * Windows XP older than SP3
  * Windows Phone
  * Other Windows platforms released before 2008
|===

== .NET Requirements

* Starting from `Jenkins 2.238`,
  .NET Framework 4.0 or above is required for all Windows service installations and built-in Windows service management logic.
* Before `Jenkins 2.238`, .NET Framework 2.0 was supported
* For platforms that do not support these versions,
  consider using Native executables provided by the link:https://github.com/winsw/winsw[Windows Service Wrapper] project.

== References

* link:https://docs.microsoft.com/en-us/lifecycle/[Microsoft Lifecycle Policy]
* link:https://support.microsoft.com/en-us/lifecycle/search[Microsoft Product Lifecycle Search]

== Contributing

If you would like to add support for more Windows platforms or to share feedback,
we honestly appreciate your contributions!
Windows support in Jenkins is link:/sigs/platform/[Platform Special Interest Group]
which has a chat, a mailing list, and regular meetings.
You are welcome to join these channels.

== Version history

* Jun 03, 2020 - First version
  (link:https://groups.google.com/forum/#!msg/jenkinsci-dev/oK8pBCzPPpo/1Ue1DI4TAQAJ[Discussion in the mailing list],
   link:https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#heading=h.ele42cjexh55[Governance meeting notes])
