---
layout: subsection
title: Upgrade to Java 17
---

When upgrading the JVM used to run Jenkins from Java 11 to Java 17, there are some details you should know and precautions you should take.

.Upgrading Jenkins Java Version From 11 to 17
video::ZabUz6sl-8I[youtube,width=800,height=420]

== Back up Jenkins

As with any upgrade, we recommend:

. link:https:/doc/book/system-administration/backing-up/#jenkins_home[Backing up `JENKINS_HOME`].
. Testing the upgrade with your backup.
. Only after all required tests pass, performing the upgrade on your production controller.

== Upgrade Jenkins

If you need to upgrade Jenkins, as well as the JVM, we recommend you:

. link:/doc/book/system-administration/backing-up/#jenkins_home[Back up `JENKINS_HOME`].
. Stop the Jenkins controller.
. Upgrade the JVM on which Jenkins is running.
** Use a package manager to install the new JVM.
** Ensure the default JVM is the newly installed version.
*** If it is not, run `systemctl edit jenkins`, and set either the `JAVA_HOME` environment variable or the `JENKINS_JAVA_CMD` environment variable.
. Upgrade Jenkins to the most recent version.
** How you upgrade Jenkins is dependent upon your original Jenkins installation method.
+
TIP: We recommend that you use the package manager of your system (such as `apt` or `yum`).
. Validate the upgrade to confirm that all plugins and jobs are loaded.
. Upgrade the required plugins.

When upgrading the Java version for Jenkins and the JVM, it is important to upgrade all plugins that support Java 17.
Plugin upgrades assure compatibility with the most recent Jenkins releases.

NOTE: If you discover a previously unreported issue, please let us know.
Refer to link:/participate/report-issue/#issue-reporting[our issue reporting documentation] for guidance.

== JVM version on agents

Agents must run a JVM that meets the minimum Java version required by the version of Jenkins running on the controller.
Agents do not need to run the same major Java version as the controller, but running the same major version reduces the risk of serialization incompatibilities between the controller and the agent.
If you are upgrading your Jenkins controller to run on Java 17, upgrade the JVM on any agents running below the minimum required Java version.

Validating the version of each agent can be done with the plugin:versioncolumn[Versions Node Monitors] plugin.
This plugin provides information about the JVM version of each agent on the node management screen of your Jenkins controller.
This plugin can also be configured to automatically disconnect any agent with an incorrect JVM version.
