---
layout: documentation
title: Getting Started
section: doc
---

:toc:

== What is a Pipeline?

Pipelines are a series of steps that allow you to orchestrate the work required to build, test and deploy applications. Pipelines are defined in file called `Jenkinsfile` that are stored in the root of your projects source repository.

== Quick Start

## Java

----
pipeline {
  agent docker:'maven:3.3.3'
  stages {
    stage('build') {
      sh 'mvn --version'
      sh 'mvn install'
    }
  }
}
----

=== Node.js / JavaScript

----
pipeline {
  agent docker:'node:6.3'
  stages {
    stage('build') {
      sh 'npm --version'
      sh 'npm install'
      sh 'npm test'
    }
  }
}
----

=== Ruby

----
pipeline {
  agent docker:'ruby:2.1'
  stages {
    stage('build') {
      sh 'ruby --version'
      sh 'bundle install'
    }
  }
}
----

=== Python

----
pipeline {
  agent docker:'python:3.5.1'
  stages {
    stage('build') {
      sh 'pip --version'
      sh 'python --version'
    }
  }
}
----

=== PHP

----
pipeline {
  agent docker:'php'
  stages {
    stage('build') {
      sh 'php --version'
    }
  }
}
----

== Create your first Pipeline

To get started quickly with Pipeline:
- Copy one of the examples into your repository and name it `Jenkinsfile`
- Click the *New Item* menu within Jenkins
- Provide a name for your new item (e.g. *My Pipeline*) and select *Multibranch Pipeline*
- Click the *Add Source* button, choose the type of repository you want to use and fill in the details.
- Click the *Save* button and watch your first Pipeline run!

You may need to modify one of the example `Jenkinsfile`'s to make it run with your project. Try modifying the `sh` command to run the same command you would run on your local machine.

After you have setup your Pipeline, Jenkins will automatically detect any new Branches or Pull Requests that are created in your repository and start running Pipelines for them.
