---
layout: simplepage
title: "Getting Started with Jenkinsfile"
---

:toc:



== Audience and Purpose

This document is intended for novice Jenkins users who want to leverage the power of pipeline functionality. Extending the reach of what was learned from a "Hello World" example in link:http://jenkins.io/doc/pipeline/[Getting Started with Pipelines], this document explains how to use a Jenkinsfile to perform a simple checkout and build for the contents of a repository. 

== Creating a Jenkinsfile

A Jenkinsfile is a container for your pipeline (or other) script, which details what specific steps are needed to perform a job for which you want to use Jenkins. You create a Jenkinsfile with your preferred Groovy editor, or through the configuration page on the web interface of your Jenkins instance. 

Using a Groovy editor to code a Jenkinsfile gives you more flexibility for building complex single or multi-branch pipelines, but whether you use an editor or the Jenkins interface does not matter if what you want to do is get familiar with basic Jenkinsfile content.


. Open your Jenkins instance or Groovy editor.
. Navigate to the directory you want (it should be the root directory for your project).
. Use standard Jenkins syntax.
. Save your file.

The following example shows a basic Jenkinsfile made to build and test code for a Maven project. "Node" is the step that schedules tasks in the following block to run on the machine (usually an agent) that matches the label specified in the step argument (in this case, a node called "linux"). Code between the braces ( { and } ) is the body of the node step. The *checkout scm* command indicates that this Jenkinsfile was created with an eye toward multi-branch support: 

____
 node (‘linux’){
  stage 'Build and Test'
  env.PATH = "${tool 'Maven 3'}/bin:${env.PATH}"
  checkout scm
  sh 'mvn clean package'
 }
____

In single-branch contexts, you could replace *checkout scm* with a source code checkout step that calls a particular repository, such as: 
____
git url: 'https://github.com/[my-repository]/simple-maven-project-with-tests.git'.
____

== Making Pull Requests

A pull request notifies the person responsible for maintaining a Jenkins repository that you have a change or change set that you want to see merged into the main codeline associated with that repository. Each individual change is called a "commit."

You make pull requests from a command line, or by selecting the appropriately labeled button (typically "Pull" or "Create Pull Request") in the interface for your source code management system.

A pull reqeust to a repository included in or monitored by an Organization Folder can be used to automatically execute a multi-branch pipeline build.


== Using Organization Folders

Organization folders enable Jenkins to automatically detect and include any new repositories within them as resources. 

When you create a new repository (as might be the case for a new project), that repository has a Jenkinsfile. If you also configure one or more organization folders, Jenkins automatically detects any repository in an organization folder, scans the contents of that repository at either default or configurable intervals, and creates a Multi-branch Pipeline project for what it finds in the scan. Organzation folders and multi-branch pipelines 

Organization folders alleviate the need for administrators or developers to manually create projects for new repositories. When organization folders are in use, Jenkins views your repositories as a hierarchy, and each repository may optionally have child elements such as branches and pull requests.


To create Organization folders:

. Open Jenkins in your web browser.
. Go to: New Item → GitHub Organization or New Item → Bitbucket Team.
. Follow the configuration steps, making sure to specify appropriate Scan Credentials and a specific owner for the GitHub Organization or Bitbucket Team name.
. Set build triggers by selecting the checkbox associated with the trigger type you want. Folder scans and the pipeline builds associated with those scans can be initiated by command scripts or performed at set intervals. They can also triggered by project promotion or changes to the images in a monitored Docker hub.
. Decide whether to automatically remove or retain unused items. "Orphaned Item Strategy" fields in the configuration interface let you specify how many days to keep old items, and how many old items to keep. If you enter no values in these fields, unused items are removed by default.


While configuring organization folders, you can set the following options:

* Repository name pattern - a regular expression to specify which repositories are included
* API endpoint - an alternate API endpoint to use a self-hosted GitHub Enterprise
* Checkout credentials - alternate credentials to use when checking out (cloning) code

Multi-branch Pipeline projects and Organization Folders are examples of "computed folder" functionality. In Multi-branch Pipeline projects, computation creates child items for each eligible branch within a child. In Organization Folders, computation populates child items for included repositories as individual Multi-branch Pipelines. Select the "Folder Computation" section of your Jenkins interface to see the duration (in seconds) and result (success or failure) of these operations, or to access a Folder Computation Log that records more detail.

== Basic Checkout and Build

Checkout and build command examples are shown in the code example used by the introduction this document. This document assumes Jenkins is running on Linux or another Unix-like operating system. 

If your Jenkins server or agent is running on Windows, you are less likely to be using the Bourne shell (*sh*) or link:http://www.computerhope.com/unix/ubash.htm[Bourne-Again shell] (*bash*) as a command language interpreter for starting software builds. In Windows environments, use *bat* in place of *sh*, and backslashes ( \ ) rather than slashes as file separators in pathnames.

