---
layout: simplepage
title: "Jenkins Code of Conduct"
section: conduct
---

:toc:

As community members, contributors and maintainers of this project,
and in the interest of fostering an open and welcoming community,
we commit to respect all people who participate in the community through reporting issues,
posting feature requests, updating documentation, submitting pull requests or
patches, and other activities.

This document defines the Code of Conduct along with reporting and handling guidelines for the Jenkins community. 
For more details about our cultural values, goals, philosophies, and structure, please consult our link:/project/governance[Governance Document]. 

== Our Pledge

We pledge to make our community welcoming, safe, and equitable for all.

We are committed to fostering an environment that respects and promotes the dignity, rights,
and contributions of all individuals, regardless of characteristics including race, ethnicity,
caste, color, age, physical characteristics, neurodiversity, disability, sex or gender, gender
identity or expression, sexual orientation, language, philosophy or religion, national or social
origin, socio-economic position, level of education, or other status. The same privileges of
participation are extended to everyone who participates in good faith and in accordance with this Covenant.

== Encouraged Behaviors

While acknowledging differences in social norms, we all strive to meet our community's expectations for positive behavior.
We also understand that our words and actions may be interpreted differently than we intend based on culture, background, or native language.

With these considerations in mind, we agree to behave mindfully toward each other and act in ways that center our shared values, including:

* Respecting the **purpose of our community**, our activities, and our ways of gathering.
* Engaging **kindly and honestly** with others.
* Respecting **different viewpoints** and experiences.
* **Taking responsibility** for our actions and contributions.
* Gracefully giving and accepting **constructive feedback**.
* Committing to **repairing harm** when it occurs.
* Behaving in other ways that promote and sustain the **well-being of our community**.

== Restricted Behaviors

We agree to restrict the following behaviors in our community.
Instances, threats, and promotion of these behaviors are violations of this Code of Conduct.

* **Harassment.** Violating explicitly expressed boundaries or engaging in unnecessary personal attention after any clear request to stop.
* **Character attacks.** Making insulting, demeaning, or pejorative comments directed at a community member or group of people.
* **Stereotyping or discrimination.** Characterizing anyone’s personality or behavior on the basis of immutable identities or traits.
* **Sexualization.** Behaving in a way that would generally be considered inappropriately intimate in the context or purpose of the community.
* **Violating confidentiality**. Sharing or acting on someone's personal or private information without their permission.
* **Endangerment.** Causing, encouraging, or threatening violence or other harm toward any person or group.
* Behaving in other ways that **threaten the well-being** of our community.

=== Other Restrictions

* **Misleading identity.** Impersonating someone else for any reason, or pretending to be someone else to evade enforcement actions.
* **Failing to credit sources.** Not properly crediting the sources of content you contribute.
* **Promotional materials**. Sharing marketing or other commercial content in a way that is outside the norms of the community.
* **Irresponsible communication.** Failing to responsibly present content which includes, links or describes any other restricted behaviors.

== Enforcement Responsibilities

Jenkins Board members are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Community leaders (Jenkins Board members, service administrators, plugin and other maintainers)
have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

== Scope

This Code of Conduct applies within all <<Community Spaces>>, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using an official e-mail address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.

=== Community Spaces

==== Source Control

All resources and conversations within the Jenkins GitHub organizations are subject to the code of conduct.
It includes but not limited to:

* Organizations
** link:https://github.com/jenkinsci[jenkinsci]
** link:https://github.com/jenkinsci-cert[jenkinsci-cert]
** link:https://github.com/jenkins-infra[jenkins-infra]
** link:https://github.com/jenkins-docs[jenkinsci-docs]
** link:https://github.com/jenkinsci-transfer[jenkinsci-transfer]
** link:https://github.com/stapler[stapler]
* Commits
* Pull requests
* Issues
* Wikis

Technical criticism is always appreciated. Keep it positive and constructive. Don't merely decry the current state of affairs. Offer and solicit suggestions as to how things may be improved.
(courtesy of the link:https://golang.org/conduct#values[Go Lang Code of Conduct])

==== Websites

Everything hosted under link:/[jenkins.io] and their sub-domains such as:

* link:https://issues.jenkins.io/[issues.jenkins.io]
* link:https://stories.jenkins.io/[stories.jenkins.io]

==== Mailing lists

All link:/mailing-lists[mailing lists] hosted on Google Groups and other platforms.

==== Chats

* All chats documented on the link:/chat[this page].
* Gitter channels within the link:https://app.gitter.im/#/room/#jenkins-ci:matrix.org[jenkinsci] space
* Jenkins chats hosted by Linux Foundation and its subsidiaries including Continuous Delivery Foundation 

==== Events

* link:/projects/jam/[Jenkins Area Meetups]
* link:/events/online-meetup[Jenkins Online Meetup]
* Events where Jenkins is officially being represented (e.g.
  link:https://fosdem.org[FOSDEM], link:https://socallinuxexpo.org/[SCaLE])

=== Other Jenkins Communities

Other Jenkins groups (such as conferences, meetups, and other unofficial forums) and local communities are encouraged to adopt this Code of Conduct.
Those groups must provide their own moderators and/or reporting system.

== Reporting an Issue

Tensions can occur between community members even when they are trying their best to collaborate.
Not every conflict represents a code of conduct violation, and this Code of Conduct reinforces
encouraged behaviors and norms that can help avoid conflicts and minimize harm.

When an incident does occur, it is important to report it promptly. To report a possible violation, send an email with the relevant information (links, screenshots, etc.) to `jenkinsci-board@googlegroups.com`.
This email list is only readable by the link:/project/board[Governance Board] members.
The board may not have all of the necessary context and history,
so it's better to describe the issue thoroughly.
All complaints will be reviewed
and investigated and will result in a response that is deemed necessary and
appropriate to the circumstances.

If the desired resolution cannot be reached on the Jenkins community level,
an issue can be escalated to the Continuous Delivery Foundation (CDF) by contacting the project team at `conduct@cd.foundation`.
See the link:https://github.com/cdfoundation/.github/blob/main/CODE_OF_CONDUCT.md[CDF Code of Conduct] for more information about reporting and enforcement in this case.

== Handling of violations

Community leaders will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct.

Depending on the severity of the violations the board may elect to take one of the following paths.
Handling of violations will be done in private and the affected people will be notified.
In the majority of cases there will not be a public announcement of the resolution,
unless the Governance Board deems it necessary to announce the resolution in public.

=== 1. Warning

1. Event: A violation involving a single incident or series of incidents.

2. Consequence: A private, written warning from the Community Moderators.

3. Repair: Examples of repair include a private written apology, acknowledgement of responsibility, and seeking clarification on expectations.

=== 2. Temporarily Limited Activities

1. Event: A repeated incidence of a violation that previously resulted in a warning, or the first incidence of a more serious violation.

2. Consequence: A private, written warning with a time-limited cooldown period designed to underscore
the seriousness of the situation and give the community members involved time to process the incident.
The cooldown period may be limited to particular communication channels or interactions with particular community members.

=== 3. Temporary Suspension

1. Event: A pattern of repeated violation which the Community Moderators have tried to address with warnings, or a single serious violation.

2. Consequence: A private written warning with conditions for return from suspension.
In general, temporary suspensions give the person being suspended time to reflect upon their behavior and possible corrective actions.

3. Repair: Examples of repair include respecting the spirit of the suspension, meeting the specified conditions for return, and being thoughtful about how to reintegrate with the community when the suspension is lifted.

=== 4. Permanent Ban

1. Event: A pattern of repeated code of conduct violations that other steps on the ladder have failed to resolve, or a violation so serious that the Community Moderators determine there is no way to keep the community safe with this person as a member.

2. Consequence: Access to all community spaces, tools, and communication channels is removed.
In general, permanent bans should be rarely used, should have strong reasoning behind them, and should only be resorted to if working through other remedies has failed to change the behavior.

3. Repair: There is no possible repair in cases of this severity.
// Addition to Contributor Covenant 2.0 begins here
The individual will be expelled from the Jenkins community.
After 12 months they may appeal to the board for the ban to be lifted.

The ban will include but is not limited to:

*  Bans from Jenkins community link:/chat[chats]
*  Deletion of their LDAP account
*  Blocking their GitHub username from the Jenkins GitHub organizations
*  Banning their email address from Jenkins mailing lists
*  Banning them from social media and meetup groups
*  Banning them from participating in Community-organized events

This enforcement ladder is intended as a guideline.
It does not limit the ability of the Jenkins governance board to use their discretion and judgment, in keeping with the best interests of our community.

== Attribution

This Code of Conduct is adapted from the Contributor Covenant, version 3.0, permanently available at link:https://www.contributor-covenant.org/version/3/0/[Contributor Covenant v3.0].

Contributor Covenant is stewarded by the Organization for Ethical Source and licensed under CC BY-SA 4.0. To view a copy of this license, visit link:https://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0].

For answers to common questions, see the link:https://www.contributor-covenant.org/faq[FAQ]. Translations are available at link:https://www.contributor-covenant.org/translations[translations]. Additional resources can be found at link:https://www.contributor-covenant.org/resources[resources]. The enforcement ladder was inspired by the work of Mozilla’s code of conduct team (link:https://github.com/mozilla/inclusion[GitHub]).

== Version history

* **Apr 07, 2026** - Major update to version link:https://github.com/EthicalSource/contributor_covenant/blob/dc57d29b3a15d81e51538fee940dada061ef2a7c/content/version/3/0/code_of_conduct.md[3.0]  of the Code of Conduct. Notable changes:
** Removed outdated IRC channel scopes
** Removed outdated way to contact the board
** Added additional GitHub organizations to the scope
* **Aug 23, 2023** - Minor update of the Code of Conduct adding translations to the footer and incorporating the link:https://github.com/EthicalSource/contributor_covenant/releases/tag/2.1[2.1] update.
* **Jul 02, 2020** - Major update of the Code of Conduct.
  It was approved the project governance meeting on Jul 01
  (link:https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg/edit#heading=h.6rx5y09hwmti[meeting notes],
   link:https://groups.google.com/forum/#!topic/jenkinsci-dev/u0T56f9MSZY[developer mailing list discussion]).
  Notable changes:
** Code of Conduct is updated to link:https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant, version 2.0]
** Align _Handling of Violations_ with link:https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant 2.0] _Enforcement Guidelines_
** Refresh the _Community Spaces_ section
** Reference Continuous Delivery Foundation (CDF) as a second escalation level
* **Jan 06, 2016** - First version of Code of Conduct is introduced.
  It is adapted from the link:https://www.contributor-covenant.org/version/1/3/0/[Contributor Covenant, version 1.3.0].
  The Code of Conduct was approved by the project governance meeting on
  link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.html[2016-01-06]
