---
layout: simplepage
title: "Jenkins Code of Conduct"
section: conduct
---

:toc:


This document defines the Code of Conduct and Reporting/Handling processes
for the Jenkins community. For more details about our cultural values,
goals, philosophies, structure and so on, please consult our
link:/project/governance[Governance Document]. 


== Our Pledge

// TODO(oleg_nenashev): First paragraph is an adapted paragraph of the Contributor Covenant 1.3.0. Should we keep it or remove it?

As community members, contributors and maintainers of this project,
and in the interest of fostering an open and welcoming community,
we pledge to respect all people who participate in the community through reporting issues,
posting feature requests, updating documentation, submitting pull requests or
patches, and other activities.

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, religion, or sexual identity
and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.

== Our Standards

Examples of behavior that contributes to a positive environment for our
community include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes,
  and learning from the experience
* Focusing on what is best not just for us as individuals, but for the
  overall community

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or
  advances of any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or email
  address, without their explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

== Enforcement Responsibilities

Jenkins Board members are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Community leaders (Jenkins Board members, service administrators, plugin and other maintainers)
have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

== Scope

This Code of Conduct applies within all <<Community Spaces>>, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using an official e-mail address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.

=== Community Spaces

==== Source Control

All resources and conversations within the Jenkins GitHub organizations are subject to the code of conduct.
It includes but not limited to:

* Organizations
** link:https://github.com/jenkinsci[jenkinsci]
** link:https://github.com/jenkinsci-cert[jenkinsci-cert]
** link:https://github.com/jenkins-infra[jenkins-infra]
** link:https://github.com/stapler[stapler]
* Commits
* Pull requests
* Issues
* Wikis

Technical criticism is always appreciated, but avoid destructive behavior such as unconstructive criticism: don't merely decry the current state of affairs; offer—or at least solicit—suggestions as to how things may be improved.
(courtesy of the link:https://golang.org/conduct#values[Go Lang Code of Conduct])

==== Websites

Everything hosted under link:https://jenkins.io/[jenkins.io], link:https://jenkins-ci.org/[jenkins-ci.org] and their sub-domains such as:

* link:https://jenkins.io[jenkins.io]
* link:https://issues.jenkins-ci.org/[issues.jenkins-ci.org]
* link:https://wiki.jenkins.io/[wiki.jenkins.io]

==== Mailing lists

All link:/mailing-lists[mailing lists] hosted on Google Groups and other platforms.

==== Chats

* All chats documented on the link:/chat[this page], e.g. IRC channels: `#jenkins`, `#jenkins-meeting`, `#jenkins-infra`, etc.
* Gitter channels within the link:https://gitter.im/jenkinsci/home[https://gitter.im/jenkinsci/] space
* Jenkins chats hosted by Linux Foundation and its subsidiaries including Continuous Delivery Foundation 

==== Events

* link:/projects/jam/[Jenkins Area Meetups]
* link:/events/online-meetup[Jenkins Online Meetup]
* Events where Jenkins is officially being represented (e.g.
  link:https://fosdem.org[FOSDEM], link:https://socallinuxexpo.org/[SCaLE])

=== Other Jenkins Communities

Other Jenkins groups (such as conferences, meetups, and other unofficial forums) and local communities are encouraged to adopt this Code of Conduct.
Those groups must provide their own moderators and/or reporting system.

== Reporting

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the link:/project/board[Jenkins board].
If you feel somebody has breached this code, please send an email with the
relevant information (links, etc) to jenkinsci-board@googlegroups.com. This
email list is only readable by the
link:/project/board[Governance
Board] members.
All complaints will be reviewed
and investigated and will result in a response that is deemed necessary and
appropriate to the circumstances.

Please understand that the board may not have all of the necessary context and
history, so it's better to be more verbose than less verbose about such
matters.

If you believe one of the members of the board has violated the code of conduct
above, please email one of the other members of the Governance Board with the
details (their emails are visible on the
link:/project/board[Governance
Board] page).

== Handling of violations

Community leaders will follow these Community Impact Guidelines in determining
the consequences for any action they deem in violation of this Code of Conduct.

Depending on the severity of the violations the board may elect to take one of the following paths.
The resolution of violations will be done in private.
And the affected people will be notified but there will not be a public announcement.

=== 1. Correction

If the severity of the violation is mild enough, the board will notify the community member that their conduct is not acceptable and needs to change.

**Community Impact**: Use of inappropriate language or other behavior deemed
unprofessional or unwelcome in the community.

**Consequence**: A private, written warning from community leaders, providing
clarity around the nature of the violation and an explanation of why the
behavior was inappropriate. A public apology may be requested.

=== 2. Warning

If the severity of the violation is serious enough,
the board will issue an official warning to the community member.

**Community Impact**: A violation through a single incident or series
of actions.

**Consequence**: A warning with consequences for continued behavior. No
interaction with the people involved, including unsolicited interaction with
those enforcing the Code of Conduct, for a specified period of time. This
includes avoiding interactions in community spaces as well as external channels
like social media. Violating these terms may lead to a _Probation_ or _Ban_.

=== 3. Probation

// oleg_nenashev: It merges statements of "3. Temporary ban" in Contributor Covenant 2.0
// + original statements of the Probation period in Jenkins CoC 2016

If the severity of the violation is serious or reprimands are not effective,
the board will ask the community member to "take a break" 
and to step
away from the community for a period of time/
The intent of this is to send a clear signal to the community member that their
conduct is unacceptable, de-escalate the situation for everyone who are
affected, and ask the community member to reflect on their behaviors.

**Community Impact**: A serious violation of community standards, including
sustained inappropriate behavior.

**Consequence**: A temporary ban from any sort of interaction or public
communication with the community for a specified period of time
(chats, mailing lists, pull requests, issues, events, etc.).
No public or
private interaction with the people involved, including unsolicited interaction
with those enforcing the Code of Conduct, is allowed during this period.
Violating these terms may lead to a ban.

=== 4. Ban

//oleg_nenashev: There is a deviation from Contributor Covenant 2.0 which recommends a Permanent Ban.
// Jenkins Code of Conduct in the 2016 edition offered a way to restore accounts after 12 months in the case of explusion,
// and it is retained in this edition

**Community Impact**: Demonstrating a pattern of violation of community
standards, including sustained inappropriate behavior,  harassment of an
individual, or aggression toward or disparagement of classes of individuals.

**Consequence**: A permanent ban from any sort of public interaction within
the community.
// Addition to Contributor Covenant 2.0 begins here
The individual will be expelled from the Jenkins community.
After 12 months of ban they may appeal to the
board for the ban to be lifted.

The ban will include but is not limited to:

*  Bans from Jenkins community link:/chat[chats]
*  Deletion of their LDAP account
*  Blocking their GitHub username from the Jenkins GitHub organizations
*  Banning their email address from Jenkins mailing lists
*  Banning them from social media and meetup groups
*  Banning them from participating in Community-organized events

== Attribution

This Code of Conduct is adapted from the Contributor Covenant,
version 2.0, available at
https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.

Community Impact Guidelines were inspired by link:https://github.com/mozilla/diversity[Mozilla's code of conduct
enforcement ladder].

== Version history

* **Jul TODO, 2020** - The Code of Conduct was updated.
  It was approved the project governance meeting, see the meeting notes link:TODO[here].
  Notable changes:
** Code of Conduct is updated to link:https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant, version 2.0]
** Align _Handling of Violations_ with link:https://www.contributor-covenant.org/version/2/0/code_of_conduct/[Contributor Covenant 2.0] _Enforcement Guidelines_
** Refresh the _Community Spaces_ section
* **Jan 06, 2016** - First version of Code of Conduct is introduced.
  It is adapted from the link:https://www.contributor-covenant.org/version/1/3/0/[Contributor Covenant, version 1.3.0].
  The Code of Conduct was approved by the project governance meeting on
  link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.html[2016-01-06]
