---
layout: simplepage
title: "Jenkins Code of Conduct"
section: conduct
---

:toc:


This document defines the Code of Conduct and Reporting/Handling processes
for the Jenkins community. For more details about our cultural values,
goals, philosophies, structure and so on, please consult our
link:/project/governance[Governance Document]. 


== Our Pledge

// TODO(oleg_nenashev): First paragraph is an adapted paragraph of the Contributor Covenant 1.3.0. Should we keep it or remove it?

As community members, contributors and maintainers of this project,
and in the interest of fostering an open and welcoming community,
we pledge to respect all people who participate in the community through reporting issues,
posting feature requests, updating documentation, submitting pull requests or
patches, and other activities.

We as members, contributors, and leaders pledge to make participation in our
community a harassment-free experience for everyone, regardless of age, body
size, visible or invisible disability, ethnicity, sex characteristics, gender
identity and expression, level of experience, education, socio-economic status,
nationality, personal appearance, race, religion, or sexual identity
and orientation.

We pledge to act and interact in ways that contribute to an open, welcoming,
diverse, inclusive, and healthy community.

== Our Standards

Examples of behavior that contributes to a positive environment for our
community include:

* Demonstrating empathy and kindness toward other people
* Being respectful of differing opinions, viewpoints, and experiences
* Giving and gracefully accepting constructive feedback
* Accepting responsibility and apologizing to those affected by our mistakes,
  and learning from the experience
* Focusing on what is best not just for us as individuals, but for the
  overall community

Examples of unacceptable behavior include:

* The use of sexualized language or imagery, and sexual attention or
  advances of any kind
* Trolling, insulting or derogatory comments, and personal or political attacks
* Public or private harassment
* Publishing others' private information, such as a physical or email
  address, without their explicit permission
* Other conduct which could reasonably be considered inappropriate in a
  professional setting

== Enforcement Responsibilities

Jenkins Board members are responsible for clarifying and enforcing our standards of
acceptable behavior and will take appropriate and fair corrective action in
response to any behavior that they deem inappropriate, threatening, offensive,
or harmful.

Community leaders (Jenkins Board members, service administrators, plugin and other maintainers)
have the right and responsibility to remove, edit, or reject
comments, commits, code, wiki edits, issues, and other contributions that are
not aligned to this Code of Conduct, and will communicate reasons for moderation
decisions when appropriate.

== Scope

This Code of Conduct applies within all <<Community Spaces>>, and also applies when
an individual is officially representing the community in public spaces.
Examples of representing our community include using an official e-mail address,
posting via an official social media account, or acting as an appointed
representative at an online or offline event.

== Attribution

This Code of Conduct is adapted from the Contributor Covenant,
version 2.0, available at
https://www.contributor-covenant.org/version/2/0/code_of_conduct.html.

Community Impact Guidelines were inspired by link:https://github.com/mozilla/diversity[Mozilla's code of conduct
enforcement ladder].

=== Community Spaces

==== Source Control

* GitHub
** Organizations
*** link:https://github.com/jenkinsci[jenkinsci]
*** link:https://github.com/jenkinsci-cert[jenkinsci-cert]
*** link:https://github.com/jenkins-infra[jenkins-infra]
*** link:https://github.com/stapler[stapler]
** Commits
** Pull requests
** Issues
** Wikis
* Subversion

Technical criticism is always appreciated, but avoid destructive behavior such as unconstructive criticism: don't merely decry the current state of affairs; offer—or at least solicit—suggestions as to how things may be improved.

(courtesy of the link:https://golang.org/conduct#values[Go Lang Code of Conduct])

==== Websites

Everything hosted under link:https://jenkins-ci.org/[jenkins-ci.org] and its sub-domains such as:

* link:https://issues.jenkins-ci.org/[issues.jenkins-ci.org]
* link:https://wiki.jenkins.io/[wiki.jenkins.io]
* link:http://lists.jenkins-ci.org/mailman/listinfo[lists.jenkins-ci.org]

==== Mailing lists

Those hosted on Google Groups (see
link:/mailing-lists[here]) and those self-hosted
on link:http://lists.jenkins-ci.org/mailman/listinfo[lists.jenkins-ci.org].

==== IRC Channels

Documented in the
link:/chat[IRC Channel] wiki
page, e.g.

* `#jenkins`
* `#jenkins-meeting`
* `#jenkins-infra`
* `#jenkins-community`

==== Events

* link:/projects/jam/[Jenkins
  Area Meetup]
* Events where Jenkins is officially being represented (e.g.
  link:https://fosdem.org[FOSDEM], link:https://socallinuxexpo.org/[SCaLE])
* Other Jenkins groups (such as conferences, meetups, and other unofficial
  forums) are encouraged to adopt this Code of Conduct. Those groups must
  provide their own moderators and/or reporting system.


== Reporting

Instances of abusive, harassing, or otherwise unacceptable behavior may be
reported by contacting the link:/project/board[Jenkins board].
If you feel somebody has breached this code, please send an email with the
relevant information (links, etc) to jenkinsci-board@googlegroups.com. This
email list is only readable by the
link:/project/board[Governance
Board] members.
All complaints will be reviewed
and investigated and will result in a response that is deemed necessary and
appropriate to the circumstances.

Please understand that the board may not have all of the necessary context and
history, so it's better to be more verbose than less verbose about such
matters.

If you believe one of the members of the board has violated the code of conduct
above, please email one of the other members of the Governance Board with the
details (their emails are visible on the
link:/project/board[Governance
Board] page).

== Handling of violations

Depending on the severity of the violations the board may elect to take one of the following paths. The resolution of violations will be done in private, and the affected people will be notified but there will not be a public announcement. We aim to prevent mud-slinging and unnecessary further personal attacks/etc.

=== Reprimand

If the severity of the violation is mild enough, the board will notify the
community member that his or her conduct is not acceptable and needs to change.

=== Probation

If the severity of the violation is serious or reprimands are not effective,
the board will ask the community member to "take a break." Meaning, to step
away from the project for a period of time. This means no participating in:

* The link:/chat/[IRC Channels]
* Mailing lists
* Pull requests
* Events
* etc

The intent of this is to send a clear signal to the community member that their
conduct is unacceptable, de-escalate the situation for everyone who are
affected, and ask the community member to reflect on their behaviors.

=== Expulsion

If probation clearly doesn't address the issue, or the issue is of high
severity to warrant an expulsion, the contributor will be expelled from the
Jenkins community for a period of 12 months. After which they may appeal to the
board for the ban to be lifted.

The ban will include but is not limited to:

*  Bans from Jenkins community IRC Channels
*  Deletion of their LDAP account
*  Blocking their GitHub username from the jenkinsci github organization
*  Banning their email address from jenkins mailing lists

== Version history

* **Jul TODO, 2020** - The Code of Conduct was updated.
  It was approved the project governance meeting, see the meeting notes link:TODO[here].
  Notable changes:
** Code of Conduct is updated to link:[Contributor Covenant, version 2.0]
* **Jan 06, 2016** - First version of Code of Conduct is introduced.
  It is adapted from the link:https://www.contributor-covenant.org/version/1/3/0/[Contributor Covenant, version 1.3.0].
  The Code of Conduct was approved by the project governance meeting on
  link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-01-06-19.01.html[2016-01-06]
