---
layout: simplepage
title: "Jenkins Team Leads and Officers"
section: project
---

Jenkins team leads and officers are individual contributors with the responsibility and accountability for
leading a particular facet of the Jenkins project and/or the community.
These roles are held by community members who have proven themselves to be responsible and courteous,
representing the executive branch of the Jenkins project governance model.
Team leads and officers act with the authority in guiding and making decisions within the project, and representing the Jenkins project within the area of their responsibility.
Officer roles are an essential part of Jenkins' community governance and well-being.

The difference between _Jenkins Officers_ and _Team Leads_ lays in the appointment process:

* Team Leads are appointed by the link:/project/governance-meeting/[Jenkins Governance Meeting] after nomination in the Jenkins developer mailing list.
  The Jenkins team leads do not have a specific term, roles may be introduced and transferred as deemed necessary by the community.
* Jenkins Officer is an *elected role*.
  Officers are elected by the Jenkins community during the regular link:/project/board-election-process/[Jenkins elections].
  Jenkins Officers have a fixed term though the number of terms is not limited.

== Responsibilities

All Jenkins officers and team leads have the following responsibilities:

* Coordinating the work inside the teams and SIGs they lead.
  While team leads are responsible to ensure that the mission-critical community processes work, they are not expected to work on them single-handedly.
* Onboarding new contributors to the teams they lead.
* Mentorship and knowledge sharing within the team to ensure healthy officer rotation in the project,
  with opportunity for team leads to move on to other roles or to take a break when needed.
* Facilitating initiatives within the scope of the responsibility, maintaining the team's roadmap,
  and ensuring that key team initiatives reflected on the link:/project/roadmap/[public Jenkins roadmap].
* Representing the Jenkins project and community within the area of their responsibility.


== Team Leads and Officers

[[security]]
=== Security Officer

Coordinates the security-related activities in the Jenkins project. This is an **elected role**. 

* Run the Jenkins CERT meeting
* Coordinate work on and releases of security fixes with plugin authors and Release Officer
* Publish link:https://wiki.jenkins.io/display/JENKINS/Security+Advisorie[Security Advisories] (including CVE IDs and CVSS) and notify the link:https://groups.google.com/g/jenkinsci-advisories[mailing list]
* Drive security policy definition/changes in the community
* Represent the Jenkins project on security topics with third parties
* Represent the link:/security/cna/[Jenkins CNA].

[[infrastructure]]
=== Infrastructure Officer

Oversees the Jenkins project infrastructure. This is an **elected role**.

* Direct triage of INFRA issues
* Direct maintenance of Jenkins project infrastructure ('INFRA' issues)
* Ensure the security of Jenkins project infrastructure
* Encourage contributors to INFRA project
* Communicate maintenance windows and manage execution of those windows
* Coordinate Jenkins Infrastructure initiatives and define priorities, get key initiatives reflected on the link:/project/roadmap/[public Jenkins roadmap]

[[events]]
=== Events Officer

_note: This team lead position was approved in the link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-02-17-19.00.html[2015-02-17 governance meeting]_

Has an active role in coordinating Jenkins community events and outreach programs. This is an **elected role**. 

Jenkins events include conferences where Jenkins is represented (cdCon, FOSDEM, SCALE, etc.),
community-organized local and virtual meetups,
contributor summits,
outreach events (hackathons, Hacktoberfest, GSoC/GSoD, etc.), and speaking opportunities.

The Events Team Lead is tasked with the following responsibilities:

* Be a point of contact for Jenkins community events mentioned above.
* Represent the Jenkins project on the Continuous Delivery Foundation (CDF) Outreach Committee.
* Participate in Advocacy & Outreach SIG and coordinate the events section there.
* Coordinate communication and logistics efforts surrounding Jenkins community events and outreach programs.
* Coordinate content/agenda for major conferences where the Jenkins community is represented.
* Process incoming event-related requests through developer and Advocacy&Outreach SIG mailing lists,
including Jenkins link:/events/online-meetup/[online] and link:/projects/jam/[local] meetups.
* Facilitate community contributions to Jenkins events organization: onboard event organizers, knowledge transfers, etc.
* Maintain the Jenkins Events calendar, together with other contributors.

[[release]]
=== Release Officer

_note: This team lead position was approved in the link:http://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-02-17-19.00.html[2016-02-17 governance meeting]_

Jenkins Release officer is responsible for coordinating Jenkins releases.
This is an **elected role**. 

* Manage keys for signing and producing official Jenkins releases (e.g. GPG signing keys, Windows and Mac OS X certificates)
* Operate LTS/weekly releases directly, or name specific release managers to be responsible for those releases (e.g. "this person is responsible for this LTS series, backporting, etc")
* Coordinate the LTS release baseline selection, backporting and release candidate testing
* Be responsible for release automation to produce LTS and weekly releases
* Act as a single point of contact for the Security Officer to incorporate security fixes/backports into releases (this implies membership to Jenkins CERT team)

[[documentation]]
=== Documentation Officer

_note:  This team lead position was approved in the link:http://meetings.jenkins-ci.org/jenkins-meeting/2019/jenkins-meeting.2019-09-11-18.04.html[2019-09-11 governance meeting]_

Oversees the Jenkins project documentation.
This is an **elected role**. 

* Enable and facilitate website/documentation contribution from the community
* Coordinate the Jenkins website copy-editors team
* Lead or be involved with link:/sigs/docs/[Documentation Special Interest Group]

// TODO: Formalize Team leads and add them to the list

== References

* link:/project/board-election-process/[Jenkins Governance Board and Officer election process]
