---
layout: gsocproject
title: "Artifact Promotion plugin for Jenkins Pipeline"
goal: "Create a new highly anticipated engine for managing promotions in Jenkins Pipeline, with modern UIs and REST APIs"
category: Plugins
year: 2019
status: Active
showGoogleDoc: false
project: Pipeline artifact promotion
tags:
- gsoc2019
student:
  name: "Prastik Gyawali"
  github: "dernDren161"
mentors:
- "bicschneider"
- "jonbrohauge"
- "oleg_nenashev"
links:
  draft: "https://docs.google.com/document/d/1UYi0jIYsKHE5IGS84B5W0XBoeMyF4yY_exu-21O99U8"
  gitter: jenkinsci/gsoc-project-artifact-promotion-plugin-for-pipeline

---

The popular promoted-builds-plugin in Jenkins currently supports Freestyle/Abstract Projects but however is incompatible with the
Pipeline structure. The existing plugin was developed before the introduction of pipelines which makes the current design archaic enough
to not support the pipeline builds. Thus, this project aims at reviving Promotion into the pipelines by introducing a new plugin which
includes major updates and redesigns done on a copy of the existing plugin(promoted-builds).
The end result here would be a robust plugin which can run an on-demand promotion when the pipeline build is completed along
with other artifact tracking and job triggering functions.


Sub-tasks to complete the project:


. Refactor the selected modules inside the promoted-builds-plugin and make them pipeline compatible.
. Detach all the required extension points and modules into the new plugin.
. Create new Custom "steps" for Declarative Pipeline script for Job promotion definition.
. Use the parameterized-trigger plugin as an inspiration to trigger the new Promotion Job.
. Avail from the run-Selector/copyArtifacts plugin to copy/send build information as parameters to the new Promotion Job.
. Use fingerprinting to trace the flow of the promoted pipeline jobs within Jenkins.(Other applications of fingerprinting yet to be discussed)
. Update the Jenkins release plugin(to share the common APIs)


Project Specific JIRA track link:
  link:https://issues.jenkins-ci.org/browse/JENKINS-57457[Community Bonding]
  link:https://issues.jenkins-ci.org/browse/JENKINS-36089[Project Epic]
  link:https://issues.jenkins-ci.org/browse/JENKINS-57634[Coding Phase -I]
  link:https://issues.jenkins-ci.org/secure/Dashboard.jspa?selectPageId=18742[Project Dashboard]

Project Proposal:
  More information on the Project can be found through this
  link:https://docs.google.com/document/d/1y6rStYSPAH3oB2cl6yw0KaVMd7pRDNmP2ljdYxS9qDM/edit[link]

Meeting Notes:
  link:https://docs.google.com/document/d/1SRLb8IeIKy3Ih83de0bDSHdJQdtmygloPfMMNRArkvo/edit#heading=h.d32s79oq7spv[link]

===== Weekly Meetings:
  General Weekly Meeting:  Wednesdays at 2:00 PM UTC

  Project Specific Meeting: Tuesdays and Thursdays at 10:00 AM UTC
  
  
