---
layout: gsocproject
title: "Multibranch Pipeline support for GitLab SCM"
goal: "Add Multibranch Pipeline support for GitLab SCM private and SaaS instances so that Jenkins can automatically build branches and pull requests with Jenkinsfile"
category: Plugin
year: 2019
status: Active
showGoogleDoc: false
student: baymac
mentors:
- "markyjackson-taulia"
- "linuxsuren"
- "justinharringa"
- "jeffpearce"
- "casz"
links:
  gitter: jenkinsci/gitlab-branch-source-plugin
  draft: https://docs.google.com/document/d/1Gqz4LyU5sw6I50OdAVsQSW_WPNDlvXg4Ic9NdcYj4Ts
---

Currently GitLab Plugin does not support Multibranch Pipeline jobs. The underlying API does
not implement calls to fetch Merge Requests during builds. Other problems with this plugin is
doesn't follow conventional SCM plugin design, doesn't support folder org, doesn't have separate
api plugin etc. So this project is about solving issues with the GitLab Jenkins Integration by
improving the current GitLab Plugin and creating separate plugins for GitLab Api and GitLab
Branch Source. One stretch goal is to add GitLab Pipeline support for Blueocean.

=== Issues
* No folder organisation support for GitLab
* No Multibranch Pipeline Job support for GitLab
* GitLab APIs currently used does not have all GitLab APIs features and limits the scope of future expansion
* GitLab Plugin does not follow convention of SCM Plugins i.e. 3 separate plugins for api, build and branch Source
* GitLab Plugin also does not leverage new SCM trait APIs, some features like auto-management of webhooks, password authentication are missing
* No Pipeline Support for GitLab in Blueocean while GitHub and BitBucket are supported

=== Solutions

* [NEW] GitLab Api Plugin that wraps new GitLab Java Api repository which is actively maintained and has almost all GitLab Apis support
* [NEW] GitLab Branch Source Plugin that supports Branch Source Functionality like Github BS, Bitbucket BS etc
* [IMPROVED] GitLab Plugin that is lightweight and provides build triggers, web hooks management and other API support
* [NEW] Pipeline Support for GitLab in Blueocean

For more details, see this Google Doc - https://docs.google.com/document/d/1YpuCC129U8KPXAwiXRXQ_4XWuLursPGl3rzQjz43-CY/edit?usp=sharing[Proposal]

=== Evaluation Phase 1

  . Complete implementation with documentation and plugin release of `GitLab API Plugin` that wraps the https://github.com/gmessner/gitlab4j-api/[gitlab4j-api] into a plugin +
  - Wiki -  https://wiki.jenkins.io/display/JENKINS/GitLab+API+Plugin
  - Source - https://github.com/jenkinsci/gitlab-api-plugin
  . Partial implementation of `GitLab Branch Source Plugin` that provides Branch Source Functionality for Multibranch Pipeline Jobs and Folder Organisation for GitLab repositories.
  This Evaluation phase is expected to contain the GitLab Server configuration in Jenkins Global Configuration (with webhooks management and personal access token generation from
  username and password). (80%) +
  - Source - https://github.com/baymac/gitlab-branch-source-plugin
  - TODO _add list of features to be implemented for Evaluation 1_

==== Resources

  . Blogs
  - https://baymac.github.io/2019/05/project-workflow-for-gsoc[Project workflow for GSoC]
  - https://medium.com/@baymac/setting-up-intellij-idea-for-jenkins-plugin-development-66a074bbe4a9[IntelliJ setup for Jenkins Plugin Development]
  . TODO _add blog links, documents links, slides links_

=== Evaluation Phase 2

  . Complete documentation, bug fixes and plugin release of `GitLab Branch Source Plugin`. (20%) +
  - TODO _add list of features to be implemented for Evaluation 2 and link to wiki_
  . Partial implementation of improved `GitLab Plugin` that is lightweight, supports new api and also leverages SCM trait apis. (70%) +
  - TODO _add list of features to be implemented for Evaluation 2_

==== Resources

  . TODO _add blog links, documents links, slides links_

=== Evaluation Phase 3

  . Complete implementation with documentation and plugin release of `GitLab Plugin`. (30%) +
  - TODO _add list of features to be implemented for Evaluation 3 and link to wiki_
  . Complete implementation and release of Pipeline support for `GitLab` in Blueocean with branches, tags, prs discover and build +
  - TODO _add list of features to be implemented for Evaluation 3_

==== Resources

  . TODO _add blog links, documents links, slides links_

=== Meeting Schedule

  * Weekdays - Tuesday and Friday
  * Time - 04:00am (UTC)

=== Other links

https://docs.google.com/document/d/12sICOnFXJXHEkqWV8yq6dy_ZcVs-5gL_zeDae8gnWdo/edit?usp=sharing[Daily Notes] +
https://docs.google.com/document/d/12elprUjiou80z2W7SSbNTZiyguJ6LEj4Z718MdoA2_c/edit?usp=sharing[GSoC Process] +
https://docs.google.com/document/d/1YpuCC129U8KPXAwiXRXQ_4XWuLursPGl3rzQjz43-CY/edit?usp=sharing[GSoC Proposal] +
https://docs.google.com/document/d/1r_zQy5KpNNAO4KerFJrowWvGfFIU7xdEdqKgFenS3lI/edit?usp=sharing[Design Document] +
