---
layout: project
title: "Jenkins in Google Summer of Code 2019"
tags:
- gsoc
links:
  gitter: jenkinsci/gsoc-sig
  googlegroup: jenkinsci-gsoc-all-public
  sig: gsoc
---

In 2019 we plan to apply to Google Summer of Code.
This page contains only the 2019-specific information.
See the link:/projects/gsoc/[main GSoC page] for the actual information.

== Project ideas

See the list of current project ideas link:/projects/gsoc/2019/project-ideas[here].
You can also link:/projects/gsoc/proposing-project-ideas[propose your own project] for GSoC.

== Schedule

See link:/projects/gsoc/2019/schedule[Jenkins year-round GSoC schedule].

== Call for mentors

We continuously look for mentors and project ideas.
You can propose your project at any time.

Official 2019 guidelines have not been published yet,
but there is a link:/projects/gsoc/proposing-project-ideas[HOWTO: Propose a project idea] page with guidelines.
Reach out to us using the link:/projects/gsoc/#contacts[GSoC contacts] if you are interested.

=== Org admins

GSoC Organization admins in 2019:

* link:https://github.com/martinda[Martin d'Anjou]
* link:https://github.com/jeffpearce[Jeff Pearce]
* link:https://github.com/lloydchang[Lloyd Chang]
* link:https://github.com/oleg-nenashev/[Oleg Nenashev]

Jenkins Org Admins mailing list: jenkins-gsoc-2019-org-admins@googlegroups.com.
Use this mailing list if you need to discuss something privately with org admins.
For all other use-cases,
use public contacts listed link:/projects/gsoc/#contacts[here].
