---
layout: gsocproject
title: "Plugin Installation Manager CLI Tool / Library"
goal: "Create a new library and tools to unify plugin management across the Jenkins ecosystem "
category: Tools
year: 2019
status: Active
showGoogleDoc: false
student:
  name: "Natasha Stopa"
  github: "stopalopa"
mentors:
- name: "Kristin Whetstone"
  github: "kwhetstone"
- name: "Baptiste Mathus"
  github: "batmat"
- name: "Jon Brohauge"
  github: "jonbrohauge"
- name: "Arnab Banerjee"
  github: "arnab1896"
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
links:
  gitter: "jenkinsci/plugin-installation-manager-cli-tool"
  draft: https://docs.google.com/document/d/1MW4qF6izW7_4R4x9SyFE1sW13TjU4wZj1wCf0dQdT6I
  sig: platform
---
There are currently many reincarnations of plugin management across Jenkins, including:

  * link:https://github.com/jenkinsci/docker#preinstalling-plugins[Docker images install-plugins.sh script]
  * link:https://github.com/jenkinsci/custom-war-packager[Custom WAR Packager]
  * link:https://jenkins.io/projects/evergreen/[Jenkins Evergreen]
  * link:https://github.com/ndeloof/jenkinsfile-runner-go[A Jenkinsfile Runner implementation]
  * link:https://github.com/coreos/jenkins-os/blob/master/init.groovy[coreOS groovy script]

This project will create a new Plugin Manager CLI tools and a library which would unify the plugin management across different Jenkins implementations.
Although we looked at extracting plugin management from Jenkins Core into its own module, this proved to be a challenging first step (see link:https://issues.jenkins-ci.org/browse/JENKINS-57672[JENKINS-57672]).
Right now the project is focusing on extracting the link:https://github.com/jenkinsci/docker/blob/master/install-plugins.sh[docker install-plugins bash script] to Java.

== Project Proposal
You can find more information in the project proposal link:https://docs.google.com/document/d/1lMCDqY5TKVXyFl67BmyMkaS9GTjRbueKr7ds395b_10/edit?usp=sharing[here].

== Repository
Code can be found link:https://github.com/jenkinsci/plugin-installation-manager-tool[here]

== Meeting Schedule
6:00 PM UTC on Tuesdays and Thursdays

The ongoing meeting notes can be found link:https://docs.google.com/document/d/1G_s2CFdZcb_TPQuLD4wL99Yy8egTLdQyRULcJFwsr1E/edit[here]
