---
layout: gsocproject
title: "Plugin Installation Manager CLI Tool / Library"
goal: "Create a new library and tools to unify plugin management across the Jenkins ecosystem "
category: Tools
year: 2019
status: Active
showGoogleDoc: false
student:
  name: "Natasha Stopa"
  github: "stopalopa"
mentors:
- "kwhetstone"
- "batmat"
- "jonbrohauge"
- "arnab1896"
- "oleg_nenashev"
links:
  gitter: "jenkinsci/plugin-installation-manager-cli-tool"
  draft: https://docs.google.com/document/d/1MW4qF6izW7_4R4x9SyFE1sW13TjU4wZj1wCf0dQdT6I
  sig: platform
---
There are currently many reincarnations of plugin management across Jenkins, including:

  * link:https://github.com/jenkinsci/docker#preinstalling-plugins[Docker images install-plugins.sh script]
  * link:https://github.com/jenkinsci/custom-war-packager[Custom WAR Packager]
  * link:https://jenkins.io/projects/evergreen/[Jenkins Evergreen]
  * link:https://github.com/ndeloof/jenkinsfile-runner-go[A Jenkinsfile Runner implementation]
  * link:https://github.com/coreos/jenkins-os/blob/master/init.groovy[coreOS groovy script]

This project will create a new Plugin Manager CLI tools and a library which would unify the plugin management across different Jenkins implementations.
Although we looked at extracting plugin management from Jenkins Core into its own module, this proved to be a challenging first step (see link:https://issues.jenkins-ci.org/browse/JENKINS-57672[JENKINS-57672]).
Phase 1 focused on extracting the link:https://github.com/jenkinsci/docker/blob/master/install-plugins.sh[docker install-plugins bash script] to Java.
Phase 2 will focus on improving upon what was written in Phase 1 and full integration with link:https://github.com/jenkinsci/docker[Jenkins Docker] and the link:https://github.com/jenkinsci/configuration-as-code-plugin[Configuration as Code Plugin].
More robust input parsing and support to view security warnings and available updates for plugins will be included in these improvements.

=== Project Information
* You can find more information about the original the project proposal link:https://docs.google.com/document/d/1lMCDqY5TKVXyFl67BmyMkaS9GTjRbueKr7ds395b_10/edit?usp=sharing[here].
* Code can be found link:https://github.com/jenkinsci/plugin-installation-manager-tool[here]
* Jira tasks and feature requests can be seen link:https://issues.jenkins-ci.org/browse/JENKINS-58199?jql=project%20%3D%20JENKINS%20AND%20component%20%3D%20plugin-installation-manager-tool[here]

=== Phase 1 Update
An alpha version of the library and CLI tool has been released! It implements basic functionality of the install-plugins.sh script to take in plugins and download them to a user-specified directory.
You can find the alpha version link:https://github.com/jenkinsci/plugin-installation-manager-tool/releases[here].

A link:/blog/2019/07/02/plugin-management-tool-alpha-release/[blog post] announcing the alpha release has also been created and a live demo can be seen in link:https://youtu.be/MDs0Vr7gnnA?t=196[the Phase 1 evaluation recording] (link:https://docs.google.com/presentation/d/12Bo8w9SinrG5n82w-Unjx4MNq0mjkHFEOMc3Jf6rTQQ/edit#slide=id.p1[slides])


=== Meeting Schedule
6:00 PM UTC on Tuesdays and Thursdays

The ongoing meeting notes can be found link:https://docs.google.com/document/d/1G_s2CFdZcb_TPQuLD4wL99Yy8egTLdQyRULcJFwsr1E/edit[here]
