---
layout: gsocproject
title: "Remoting over Apache Kafka. Docker/K8s Features"
goal: "Enhance the plugin and to provide out-of-the box management in Docker and especially Kubernetes environments"
category: Plugins, Core
year: 2019
status: Active
project: remoting
student:
  name: "Long Nguyen"
  github: "longngn"
mentors:
- "afalko"
- "pvtuan10"
- "ankit-jain"
- "supun94"
- "oleg_nenashev"
links:
  draft: https://docs.google.com/document/d/1CIgjz8IZxihYC6CKqE0pFuKljCKK3SPhKK87IpHs_38
---

Current version of Remoting over Apache Kafka plugin requires users to manually configure the entire system which includes Zookeeper, Apache Kafka and Remoting agents. It also doesn't support dynamic agent provisioning so scalability is harder to achieve. This project aims to solve two problems:

  . Out-of-the-box solution to provision Apache Kafka cluster. More specifically, users can connect with a Kafka server seamlessly by either local binary files, Kubernetes container or from a Software-as-a-Service provider.
  . Dynamic agent provisioning in a Kubernetes cluster. This can be done by implementing Cloud API or integrate Kafka agent launcher in Kubernetes plugin.

===== Project Proposal
You can find more information in the project proposal link:https://docs.google.com/document/d/1Iu0pJLkr_PHQIpMA2BDtQQ-fU4yDVBPe_5OwAbv2y-g/edit?usp=sharing[here].

===== Meeting Schedule
Every Tuesday and Friday at 1:00 PM UTC (from May 28th).
