---
layout: gsocproject
title: "Role Strategy Plugin performance"
goal: "Improve performance of one of the most popular authorization plugins in Jenkins"
category: Plugins
year: 2019
status: Active
student: abhyudayasharma
mentors:
- "oleg_nenashev"
- "runzexia"
- "supun94"
links:
  draft: "https://docs.google.com/document/d/1zUKRShhILzESwO7PIrYxXRSyLxxY-hAPclbREU8uE1o"
  gitter: "jenkinsci/role-strategy-plugin"
---

The Role Strategy Plugin is one of the most popular Jenkins authorization plugin. On adding a large number of roles to the plugin,
a significant slowdown is visible in the Jenkins Web UI. The project aims to improve the end user experience by improving the
performance of the plugin and creating a reliable performance testing framework which can be used in other Jenkins plugins.

The project is being tracked on Jenkins Jira:

* link:https://issues.jenkins-ci.org/browse/JENKINS-57415[Community Bonding]
* link:https://issues.jenkins-ci.org/browse/JENKINS-57416[Phase 1]
* link:https://issues.jenkins-ci.org/browse/JENKINS-18377[Phase 2]

Please follow our link:https://gitter.im/jenkinsci/role-strategy-plugin[Gitter chat] for more details.

===== Project Proposal
You can find more details at the project proposal link:https://docs.google.com/document/d/1zUKRShhILzESwO7PIrYxXRSyLxxY-hAPclbREU8uE1o/edit[Google Doc].

===== Project Meeting Schedule
Project Specific meetings: Tuesdays and Fridays at 7:00 AM UTC

Jenkins GSoC Office Hours: Wednesdays at 2:00 PM UTC

===== Performance Testing for Jenkins using JMH

The micro-benchmarking framework was made available to everyone through Jenkins Test Harness link:https://github.com/jenkinsci/jenkins-test-harness/releases/tag/jenkins-test-harness-2.51[2.51]
and Plugin POM link:https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-3.46[3.46].
A blog post summarizing how to use the framework was published and can be seen link:/blog/2019/06/21/performance-testing-jenkins/[here].

A demo of the framework was held on May 31 and can be found
at: https://www.youtube.com/watch?v=sr28UADG1AE .
Another demo was held at the Platform SIG meeting on June 6, this can be found at
https://www.youtube.com/watch?v=lyfbmhQd0Ag

The presentation slides are available at:  https://drive.google.com/file/d/1gig6u64rzvSzGKjN_PTTXTkSXQ9Ah7E5/view?usp=sharing

===== Performance improvements to Role Strategy Plugin

To improve the performance of the Role Strategy Plugin, a couple of changes
were made. First, a cache for the matching roles for each project was created.
This avoids iterating through all regular expressions every time a permission is
needed to be checked. The other change that brought performance improvements
was to pre-calculate implying permissions. In Jenkins, the ADMINISTRATOR
permission, for example, gives the user the permission to read any Job. This
change avoids having to calculate all implying permissions whenever a permission
needed to be checked. These performance improvements were released for everyone
in Role Strategy Plugin link:https://github.com/jenkinsci/role-strategy-plugin/releases/tag/role-strategy-2.13[2.13].

===== The new Folder Authorization Plugin

A new authorization plugin for Jenkins was created and can be found at
https://github.com/jenkinsci/folder-auth-plugin. The plugin allows assigning
permissions for Jobs through inheritance in 'folders' from Cloudbees' link:https://plugins.jenkins.io/cloudbees-folder[Folders plugin]
and does not use regular expressions. The plugin also supports Global Roles
(like from the Role Strategy plugin) and 'Agent Roles' which can be used for
restricting permissions for agents connected to Jenkins. The alpha releases for
the plugin can be found link:https://github.com/jenkinsci/folder-auth-plugin/releases[here].

The demo for the Phase 2 evaluations can be found at https://youtu.be/tnoObQqGhyM?t=1101 
and the slides for the presentation are available at https://drive.google.com/file/d/1IVe3T8WdTILmb62PAIJveR4KbBWzPt1k/view?usp=sharing

