---
layout: simplepage
title: Chat
---

The Jenkins project meets to discuss various topics on Gitter and IRC.
In addition to the general purpose rooms and channels listed below, link:../sigs/[special interest groups] and link:/projects[sub-projects] have their own spaces, and you will see chat rooms linked from their pages.

For the `#jenkins-infra` and `#jenkins-release` rooms, the IRC, Matrix, and Gitter channels have been connected.
This means you can use your preferred chat client to keep up to date with Jenkins and not miss anything!
Other channels will be connected similarly as we move forward.

== Gitter

The Jenkins community discusses various topics in multiple rooms on https://app.gitter.im/#/room/#jenkins-ci:matrix.org[Gitter].
Various link:../sigs/[special interest groups] also use Gitter to meet, and you will find their rooms linked on the SIGs overview page.

=== https://app.gitter.im/#/room/#jenkinsci_jenkins:gitter.im[jenkinsci/jenkins]

General discussions about Jenkins.

=== https://app.gitter.im/#/room/#jenkinsci_newcomer-contributors:gitter.im[jenkinsci/newcomer-contributors]

Q&A channel for newcomer contributors to Jenkins.
Use this channel if you are not sure where to ask, and other contributors will help you.
link:/participate/[More about contributing to Jenkins].

== Internet Relay Chat (IRC)

The Jenkins community discusses various project-related topics in multiple channels on the https://libera.chat/[Libera Chat] IRC network.

For information on how to connect, see the https://libera.chat/guides[Libera Chat] website.
https://libera.chat/guides/clients[Find an IRC client].

=== `#jenkins`

General discussions channel for Jenkins users and developers.
It used to be the primary one until non-IRC communication options were introduced.

**Tip:** If you have a question about Jenkins, just ask it. Don't ask whether you can ask a question.
It's common to not receive an answer for quite a while if no active contributors are currently checking IRC.
In that case, just stick around, and periodically (every few hours) ask your question again.

=== `#jenkins-infra`

Discussions of the link:/projects/infrastructure/[Jenkins project infrastructure], i.e. most services running on `jenkins.io`, `jenkins-ci.org`, and related domains.

=== `#jenkins-release`

Channel for coordinating the Jenkins link:/download/weekly/[weekly] and link:/download/lts/[LTS] releases.
It is used by the Release Team when planning and rolling out the new releases and release candidates.

=== `#jenkins-hosting`

Chat of the Jenkins link:/project/teams/hosting/[Hosting team] that manages permissions and handles plugin hosting requests.
We use the *jenkins-admin* bot to automate common administrative operations.
Its use is limited to users with _voice_ or _op_ in this channel.
link:/projects/infrastructure/ircbot/[Learn more about the IRC Bot].

=== Channel spam protection

Because of irregular spam attacks, we sometimes have to make some channels protected.
In such circumstances, we make the targeted channel(s) only accessible to registered IRC nicks.
Example error:

[source]
----
[10:28] -NickServ- my_nickname is not a registered nickname.
[10:28] == #jenkins Cannot join channel (+r) - you need to be identified with services
----

That means you basically need to create a reserved nick for you, link:https://libera.chat/guides/registration[following the official documentation].
Once done, you will be able to connect to `#jenkins` even if that channel is undergoing a spam attack.
Note that even without this, this is a recommended practice so that people *know* this is you, and cannot be someone else, when a given nick is online.

=== Cloaks

#jenkins is not only a registered channel, but the Jenkins project has an official relationship with Libera Chat (see https://libera.chat/chanreg[the Libera Chat site] for more details).
Because of this, we can provide IRC cloaks for developers.
IRC cloaks are used to protect the privacy of developers.
Cloaking is also a common way for projects with an IRC presence to designate status for contributors and developers.
We currently offer the following cloak levels:

* `jenkins/contributor/(username)`

To obtain a cloak:

* ensure you have a *registered user* on Libera Chat
* ensure you are already recognized as a developer (have +vV voice privilege)
* Contact a https://www.jenkins.io/projects/infrastructure/[Jenkins Infrastructure Team] member, who will request a cloak on your behalf in `#libera-community`
* monitor your memoserv notices for updates from Libera Chat staff requesting confirmation of cloak request
** */msg memoserv help*

== Slack

Some teams and working groups use Slack for communications.

=== Continuous Delivery Foundation 

link:https://cd.foundation/[Continuous Delivery Foundation (CDF)] Slack is used for coordinating the Jenkins community activities with the CDF, other projects and special interest groups.
Any contributor can join this channel, but the Jenkins community does not currently host its official channels there.
link:https://join.slack.com/t/cdeliveryfdn/shared_invite/zt-nwc0jjd0-G65oEpv5ynFfPD5oOX5Ogg[Join CDF Slack]

=== Kubernetes

The Kubernetes Slack includes an **unofficial** `#jenkins-ci` channel.
This channel is commonly used to discuss various aspects of running Jenkins in Kubernetes.
Our sister project link:https://jenkins-x.io/[Jenkins X] also hosts its official chats there (link:https://jenkins-x.io/community/#slack[links]).

You can join this Slack workspace by requesting an invitation link:https://slack.k8s.io/[here].

=== Jenkins Operator for Kubernetes

The link:/projects/jenkins-operator/[Jenkins Operator sub-project] uses a separate `#jenkins-operator` channel on link:https://virtuslab-oss.slack.com/[virtuslab-oss.slack.com].
See more information and joining guidelines link:https://github.com/jenkinsci/kubernetes-operator#community[here].
