---
layout: simplepage
title: "Donate to Jenkins"
---

NOTE: You can donate directly through the link:https://co.clickandpledge.com/advanced/default.aspx?wid=46160[SPI donation page] (donation in USD)
or via the link:http://www.ffis.de/Verein/donations.html[ffis.de donation page] (donation in EUR) if you do not need the context below

The Jenkins project is affiliated with link:https://www.spi-inc.org[Software in the Public Interest], a non-profit organization.
Via SPI we can accept link:https://co.clickandpledge.com/advanced/default.aspx?wid=46160[donations online] in USD.
For other ways to donate, refer to the link:https://spi-inc.org/donations[donations page on the SPI website].


For European residents, we can also accept donations through link:http://www.ffis.de/Verein/donations.html[ffis.de] via bank transfer in EUR.
As ffis.de is a charitable association, this donation is tax deductible in Germany.

NOTE: If you donate via ffis.de, please write to `donation[at]ffis.de` to ensure that your donation will be earmarked for the Jenkins project.


== Why donate?

Your contributions help us keep Jenkins going by paying project expenses, such as:

*Operating expenses:*

* SSL certificates on our websites
* Covering network transit costs (not including that incurred by mirrors)
* Equipment/replacement hardware

A portion of contributions help fund SPI, Inc, which acts as the legal umbrella organization for holding copyrights, etc.

Your contribution is *not* used for paying personnel.

== Friend of Jenkins

In showing our appreciation, we'll send out a special "friend of Jenkins" plugin to those who have donated at least 25 USD / 25 EUR.
This plugin adds a little icon in the footer section, telling that you are a friend of Jenkins.
You can install this to your Jenkins to show off that you've helped us.
