---
layout: simplepage
title: "Donate to Jenkins"
---

WARNING: Jenkins donations flow is being redesigned at the moment.
See jira:INFRA-2396[Jenkins Donations flow update] for more information about the current status.
If you want to make a donation, please contact the link:mailto://jenkinsci-board@googlegroups.com[Jenkins Board].

== Why donate?

Your contributions help us keep Jenkins going by paying project expenses, such as:

*Operating expenses:*

* SSL certificates on our websites
* Covering network transit costs (not including that incurred by mirrors)
* Equipment/replacement hardware

Your contribution is *not* used for paying personnel.

== Ways to donate

There are multiple ways to donate money to the Jenkins project.

=== Donations through SPI

Before the transition to link:https://cd.foundation/[Continuous Delivery Foundation] in 2019,
Jenkins project was under the umbrella of link:http://www.spi-inc.org/[Software in the Public Interest (SPI)].
At the moment of this page update (Dec 26, 2019), SPI still accepts donations to the Jenkins project.
In the future SPI will stop accepting donations.

* You can do a link:https://co.clickandpledge.com/advanced/default.aspx?wid=46160[donation online] in USD
* For other ways to donate, refer to the link:https://spi-inc.org/donations[donations page on the SPI website]

=== Donations through ffis.de

WARNING: Status of this donation way is not clear, see jira:WEBSITE-703[]

For European residents, we can also accept donations through link:http://www.ffis.de/Verein/donations.html[ffis.de] via bank transfer in EUR.
As ffis.de is a charitable association, this donation is tax deductible in Germany.

NOTE: If you donate via ffis.de, please write to `donation[at]ffis.de` to ensure that your donation will be earmarked for the Jenkins project.

== Friend of Jenkins

In showing our appreciation, we'll send out a special "friend of Jenkins" plugin to those who have donated at least 25 USD / 25 EUR.
This plugin adds a little icon in the footer section, telling that you are a friend of Jenkins.
You can install this to your Jenkins to show off that you've helped us.
