---
layout: simplepage
title: "Donate to Jenkins"
---

WARNING: Jenkins donations flow is being redesigned at the moment.
At the moment there is no reliable way to donate money to the project, but we are working on it.
See jira:INFRA-2396[Jenkins Donations flow update] for more information about the current status.
If you want to make a donation, please contact the link:mailto://jenkinsci-board@googlegroups.com[Jenkins Board].

== Why donate?

Your contributions help us keep Jenkins going by paying project expenses, such as:

*Operating expenses:*

* SSL certificates on our websites
* Covering network transit costs (not including that incurred by mirrors)
* Equipment/replacement hardware

Your contribution is *not* used for paying personnel.

== Ways to donate

=== Donations through SPI

The Jenkins project used to accept donations through link:http://www.spi-inc.org/[Software in the Public Interest (SPI)].
Due to the ongoing migration to link:https://cd.foundation/[Continuous Delivery Foundation],
SPI will no longer accept donations to the Jenkins project. 

=== Donations through ffis.de

WARNING: Status of this donation way is not clear, see jira:WEBSITE-703[]

For European residents, we can also accept donations through link:http://www.ffis.de/Verein/donations.html[ffis.de] via bank transfer in EUR.
As ffis.de is a charitable association, this donation is tax deductible in Germany.

NOTE: If you donate via ffis.de, please write to `donation[at]ffis.de` to ensure that your donation will be earmarked for the Jenkins project.

== Friend of Jenkins

In showing our appreciation, we'll send out a special "friend of Jenkins" plugin to those who have donated at least 25 USD / 25 EUR.
This plugin adds a little icon in the footer section, telling that you are a friend of Jenkins.
You can install this to your Jenkins to show off that you've helped us.
