---
layout: simplepage
title: Mailing Lists
---

The Jenkins project uses link:https://en.wikipedia.org/wiki/Electronic_mailing_list[mailing lists] to communicate.
These mailing lists are organized by topic (see below).
Posting to the wrong mailing list will just result in your message being ignored.
Please strive to be clear and concise when sending messages.
link:http://www.catb.org/esr/faqs/smart-questions.html[How to ask questions the smart way.]

To subscribe to a mailing list, send an empty email to the "subscribe" email address.

WARNING: Due to heavy spam volume, we have enabled moderation of a user's first post on some of these lists.
This may result in delays in delivering your first email to these lists. For this reason, you should not re-send your email if it doesn't appear on the list straight away.

== English-language discussion lists


=== jenkinsci-users@googlegroups.com

Mailing list for users of Jenkins.
Post your questions on how to use Jenkins and Jenkins plugins here.

NOTE: If you're not sure which list is correct, post here.

link:http://groups.google.com/group/jenkinsci-users/topics[archive] |
mailto:jenkinsci-users+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-users+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-dev@googlegroups.com

Mailing list for *developers* of Jenkins.
Post your Jenkins core development and plugin development questions here, as well as topics related to project governance.

WARNING: *Questions that should be asked on the _jenkinsci-users_ list will be ignored*.
That means your email will be moderated and not posted to the list.
Do not cross-post.

link:http://groups.google.com/group/jenkinsci-dev/topics[archive] |
mailto:jenkinsci-dev+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-dev+unsubscribe@googlegroups.com[unsubscribe]

=== events@lists.jenkins-ci.org

Mailing list for events, meet-ups, and fostering local communities. +
link:http://lists.jenkins-ci.org/pipermail/jenkins-events/[archive] |
link:http://lists.jenkins-ci.org/mailman/listinfo/jenkins-events[subscribe] |
link:http://lists.jenkins-ci.org/mailman/listinfo/jenkins-events[unsubscribe]

=== jenkinsci-jam@googlegroups.com

Mailing list for link:/projects/jam/[Jenkins Area Meetup] coordination. +
link:http://groups.google.com/group/jenkinsci-jam/topics[archive] |
mailto:jenkinsci-jam+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-jam+unsubscribe@googlegroups.com[unsubscribe]

=== infra@lists.jenkins-ci.org

Mailing list for jenkins-ci.org operations and infrastructure. +
link:http://lists.jenkins-ci.org/pipermail/jenkins-infra/[archive] |
link:http://lists.jenkins-ci.org/mailman/listinfo/jenkins-infra[subscribe] |
link:http://lists.jenkins-ci.org/mailman/listinfo/jenkins-infra[unsubscribe]

=== jenkinsci-docs@googlegroups.com

Mailing list for collaborating on Jenkins user and developer documentation. +
link:http://groups.google.com/group/jenkinsci-docs/topics[archive] |
mailto:jenkinsci-docs+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-docs+unsubscribe@googlegroups.com[unsubscribe]

== Discussion lists in other languages

=== jenkinsci-br@googlegroups.com

Jenkins grupo de usuários em Português do Brasil +
link:http://groups.google.com/group/jenkinsci-br/topics[archive] |
mailto:jenkinsci-br+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-br+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-ja@googlegroups.com

日本語ユーザーおよび開発者の為のメーリングリスト +
link:http://groups.google.com/group/jenkinsci-ja/topics[archive] |
mailto:jenkinsci-ja+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-ja+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-kr@googlegroups.com

Jenkins users list in Korean +
link:http://groups.google.com/group/jenkinsci-kr/topics[archive] |
mailto:jenkinsci-kr+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-kr+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-zh@googlegroups.com

Jenkins 中文用户及开发者邮件组 +
link:http://groups.google.com/group/jenkinsci-zh/topics[archive] |
mailto:jenkinsci-zh+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-zh+unsubscribe@googlegroups.com[unsubscribe]

== Read-only lists

=== jenkinsci-advisories@googlegroups.com

Security Advisory announcements are sent to this list. link:/security[More about security in Jenkins] +
link:http://groups.google.com/group/jenkinsci-advisories/topics[archive] |
mailto:jenkinsci-advisories+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-advisories+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-commits@googlegroups.com

Automated core and plugin commit notifications. +
link:http://groups.google.com/group/jenkinsci-commits/topics[archive] |
mailto:jenkinsci-commits+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-commits+unsubscribe@googlegroups.com[unsubscribe]

=== jenkinsci-issues@googlegroups.com

Automated notifications from JIRA (JENKINS project only). +
link:http://groups.google.com/group/jenkinsci-issues/topics[archive] |
mailto:jenkinsci-issues+subscribe@googlegroups.com[subscribe] |
mailto:jenkinsci-issues+unsubscribe@googlegroups.com[unsubscribe]
