---
layout: simplepage
title: Merchandise
---

// TODO Who's running these? KK? Who gets the money for these?

== Jenkins figurine at HeroForge

The link:https://www.heroforge.com/load_config%3D13211607/[Jenkins] is a share of a 3D print figurine of Mr. Jenkins.

The model for these figures was created by link:https://www.linkedin.com/in/w-douglas-west-0856094/[D. West] and is licensed as CC-BY-SA.
It can be downloaded from the link:/artwork/[logo] page.


== Jenkins T-Shirts

The link:https://www.teepublic.com/t-shirt/10501273-jenkins-at-your-service/[Jenkins at Your Service T-shirt] at pebble is a design featuring the playful phrase "Jenkins at Your Service", perfect for fans who appreciate a humorous nod to the Jenkins build server.

The link:https://www.teepublic.com/t-shirt/53097299-jenkins-logo/[Jenkins Logo T-shirt] at pebble showcases the iconic Jenkins logo in a stylish design, ideal for professionals and enthusiasts alike.

The link:https://www.redbubble.com/i/t-shirt/Jenkins-on-Fire-by-unixorn/28042083.L1PUX/[Jenkins on Fire T-shirt] at redbubble presents a dynamic illustration of Jenkins with an "on fire" theme, offering a bold twist on the classic branding.

The link:https://printerval.com/jenkins-do-you-even-build-t-shirt-t-shirts-p974234589/[Jenkins Do You Even Build T shirt] at printerval offers a witty take on the build process, making it a fun addition for those who live and breathe continuous integration.
