---
layout: simplepage
title: "Jenkins Security"
section: security
---


The Jenkins project takes security seriously and makes every possible effort to
ensure users can adequately secure their automation infrastructure. Under the
guidance of the Jenkins Security Officer, link:/2.0/[Jenkins 2.0] (and higher)
include more secure defaults than previous releases of Jenkins.

Additionally, the
link:https://wiki.jenkins-ci.org/display/JENKINS/Governance+Board#GovernanceBoard-Security[Jenkins
Security Officer], with help from members of
link:https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CERT+team[Jenkins CERT]
work with security researchers, plugin and core developers to release security
fixes and advisories for plugin and core in a timely manner.

// TODO: Once there is a good Handbook chapter it should be prominently linked
// from here


== Security Advisories

From time to time, we issue a security advisory to report security problems in
Jenkins. You can receive notifications for such advisories in one of the
following ways:

. jenkinsci-advisories@googlegroups.com (_read-only_) mailing list (link:https://groups.google.com/forum/#!forum/jenkinsci-advisories[list archive])
. link:http://feeds.feedburner.com/jenkins-security-advisories[jenkins-security-advisories RSS feed]

=== Archived Advisories

Archive of the past security advisories can be seen in the
`jenkinsci-advisories` mailing list and the security advisories list on this
link:https://wiki.jenkins-ci.org/display/SECURITY/Home[wiki page].


== Reporting vulnerabilities

If you find a vulnerability in Jenkins, please report it in the issue tracker
under the link:http://issues.jenkins-ci.org/browse/SECURITY[SECURITY project].
This project is configured in such a way that only the reporter and the core
Jenkins developers can see the details.

By restricting the access to the potential sensitive information, we can work
on the problem and deliver the fix before the method of attack becomes
well-known.

For information on what makes a good report in general, see
link:https://wiki.jenkins-ci.org/display/JENKINS/How+to+report+an+issue[this Issue Tracking] page.
