---
layout: project
title: "Google Summer of Code"
section: projects
tags:
- gsoc
- gsoc2017
---

The link:https://developers.google.com/open-source/gsoc/[Google Summer of Code]
(GSoC) project is an annual, international, program which encourages
college-aged students to participate with open source projects during the summer
break between classes. 

Students accepted into the program receive a stipend,
paid by Google, to work well-defined projects to improve or enhance the Jenkins
project. 
In exchange, numerous Jenkins community members volunteer as "mentors"
for students to help integrate them into the open source community and succeed
in completing their summer projects.

== 2017 Student Projects

[NOTE]
====
Preparation is still underway for Google Summer of Code 2017

The project has not been accepted to GSoC 2017 yet;
the list of accepted organizations will be published on **Feb 27**.
All students are welcome to start project discussions before this date.
====

=== Project ideas

NOTE: The table below lists the well-defined project ideas, which already have potential mentors.
Students are eligible to submit any other Jenkins-related ideas though it may be hard to find mentors in particular cases.

.Project Ideas with Mentors
[frame="topbot",options="header,footer",cols="asciidoc,literal,asciidoc,literal"]
|======================
|Title |Area | Description | Potential Mentors

| EDA tool integration plugin
| Plugins, Hardware Design
| The idea is to create a Jenkins plugin for one of the widely used Electronic Design Automation (EDA) tools. 

Tools from both ASIC or FPGA design flow are acceptable. 
We are ready to consider conditionally-free and open-source tools, which would be available to the student and his mentors. 

Prerequisites:

* Basic knowledge of the hardware engineering area
* Basic knowledge of Java programming language
* Hands-on experience with the selected EDA tool. 
In the case of FPGA flows it would be useful to have a prototyping board as well.
| link:https://github.com/martinda[Martin d'Anjou], link:https://github.com/oleg-nenashev[Oleg Nenashev]

| link:https://wiki.jenkins-ci.org/display/JENKINS/Support+Core+Plugin[Support core plugin] improvements 
| Plugins
| It is often difficult for plugins developers to diagnose issues and analyse the user environment.

The link:https://wiki.jenkins-ci.org/display/JENKINS/Support+Core+Plugin[Support Core plugin] allows users to generate a bundle to help on this but it is nowadays rarely used because it is isn't user friendly.
Various fixes and improvements may help our community a lot. 

Few ideas of new features to add:

* Ease the management of bundles (UI to list, delete, browse, download bundles) - link:https://issues.jenkins-ci.org/browse/JENKINS-33090[JENKINS-33090]
* Bundles will have to be stored in our public JIRA thus it is critical to provide anonymisation of the content by default - link:https://issues.jenkins-ci.org/browse/JENKINS-21670[JENKINS-21670]
* Submission of bundles in link:https://issues.jenkins-ci.org[our bug tracker] - link:https://issues.jenkins-ci.org/browse/JENKINS-33090[JENKINS-33090]
* etc.

Prerequisites:

* Basic knowledge of Jenkins (as a user)
* Basic knowledge of Java programming language

| link:https://github.com/alecharp[Adrien Lecharpentier], link:https://github.com/christ66[Steven Christou]
|======================

=== Application process

1. Check out the project ideas (see above).
2. Select an interesting project idea or draft your own proposal.
3. If you are not familiar with Jenkins, read the introductory info on the website and trying it out with one of your previous projects.
4. Join the _jenkinsci-dev_ and _jenkinsci-gsoc-all-public_ mailing lists
5. If you do not have a GitHub account, create one
6. Introduce yourself the community and start your project proposal discussion by sending an introductory email to the link:https://groups.google.com/forum/#!forum/jenkinsci-dev[jenkinsci-dev] Google Group (see the guidelines below).
7. Join us at GSoC office hours.

NOTE: 
Please note that link:https://groups.google.com/forum/#!forum/jenkinsci-dev[jenkinsci-dev] mailing list is publicly visible inside and outside the community. 
It is required for the initial review and feedback collection.

=== First email to jenkinsci-dev

* Please use the _[GSoC2017] -_ prefix in your message subject
* In the first e-mail we would be interested to see the following information:
 * A short self-introduction: your area of study, interests, background
 * Motivation letter. Why are you interested in the Jenkins project? On which project areas would you like to work? If there are particular proposals, please let us know about them as well, and any initial thoughts on why you would be suited
 * If you participate in open-source projects, please reference them
 * If you have profile pages in professional networks like LinkedIn, please reference them
 * If you have a Twitter account, a blog or technical/scientific publications, please reference them as well

NOTE: In GSoC we do not hire you in the common sense.
Please do not **just** send us your CVs or universal cover letters.
We are mostly interested to understand your interests and your motivation to work in the project.

== Getting in touch

=== Chat and Mailing lists

There are the following main resources:

Technical conversations:

* _jenkinsci-dev@googlegroups.com_ - for all technical discussions and the project application
* _#jenkins_ IRC channel on FreeNode.
link:https://wiki.jenkins-ci.org/display/JENKINS/IRC+Channel[More Info]

Organizational questions:

* _jenkinsci-gsoc-all-public@googlegroups.com_ - sync-ups on organizational topics (meeting scheduling, process Q&A)
* _jenkinsci-gsoc-orgs@googlegroups.com_ - for private communications with Jenkins GSoC Org Admins (escalations)

=== Office hours

In the Jenkins project we will have regular public office hours for students and mentors.
These office hours will start when and if the project gets accepted.

NOTE: Regular office hours will be announced after Feb 27. 
If you need office hours or a call with Org admins before that, please contact us via the mailing list.


=== Expectations from students

NOTE: The section below is under development. 
The expectations may slightly change before the beginning of the Student application period.

==== Student application process

0. We expect students to get involved into project discussions on the beginning of the student application period in order to have opportunity to discuss the project with them and to jointly review the proposal drafts.
0. We expect students to attend at least one office hours during the application period.
0. We expect proposals to contain all the sections discussed in the link:http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/[GSoC Student Guide]

==== Community bonding

Students and mentors are expected to...

0. Work closely in order to study the area of their project and to get introduced to the key stakeholders and contributors in the area of the project
0. Define the communication ways (chats, etc.) and setup regular meetings (recommended - at least 2 meetings per week)
0. Create a mini-design for the project, which would include top-level architecture and implementation plan with milestones
0. Prepare the development environment, including setup of the development tools and getting of special permissions (if required)
0. Attend Jenkins governance meetings if the timezone allows
0. Spend a significant amount of time on study and design during the community bonding

==== Coding period

Students are expected to...

0. Work on the GSoC project as it is a full-time employment. 
 * It means that 30..40 hours per week is an **expected** workload though it can be adjusted upon the agreements with mentors.
 * It also means that you have ~5 "vacation days" during the project, do not hesitate to use them if required
0. Use weekend to have a rest, avoid significant overwork and enjoy coding
0. Timely notify mentors in the case of emergencies and outages (missing scheduled meetings, etc.).
0. Timely notify mentors and org admins about unexpected time commitments
0. Be around in _#jenkins_ IRC and in the project chats during the working hours
0. Attend Jenkins governance meetings if the timezone allows
0. Be proactive; reach out to the community if required
0. Produce the good quality code with reasonable amount of testing and documentation
0. Have a finalized deliverable at the end of the project

Students are not expected to...

0. Strictly follow the originally submitted mini-design and the project proposal
* The world is not ideal, and there may be unexpected obstacles or shortcuts
* Upon the discussion with mentors, any plan can be adjusted
* We expect students to achieve at least some goals in the original proposal
0. Investigate and solve every issue on their own
* We have mentors and experts, who can help you by answering questions and doing joint investigation if required

==== Evaluations

0. At the end of the each coding phase students and mentors present the project status at the public meeting
0. As a part of the Final evaluation students present the project results at the link:https://www.meetup.com/Jenkins-online-meetup/[Jenkins Online Meetup]

==== Post-GSoC

Depending on the project results and available budget, 

== Links

* link:https://developers.google.com/open-source/gsoc/[Google Summer of Code page]
* link:http://write.flossmanuals.net/gsocstudentguide/what-is-google-summer-of-code/[GSoC Student Guide]
* link:http://archive.flossmanuals.net/gsocmentoring/[GSoC Mentor Guide]

== Previous years

* link:/projects/gsoc/gsoc2016[Google Summer of Code 2016] (5 student projects)


