---
layout: project
title: "Jenkins Area Meetups"
section: projects
---

Jenkins Area Meetups (JAMs) are local meetups intended to bring Jenkins users
and contributors together for socializing and learning.
JAMs are organized by local Jenkins community members who have a passion for
sharing new Jenkins concepts, patterns and tools. JAMs can be found
link:http://www.meetup.com/pro/jenkins/[around the world], and if there isn't a
JAM in your city, you could be the one to start it!

Jenkins Area Meetups are driven by local organizers but receive support from
the Jenkins project via swag (stickers, etc), promotion, and help bootstrapping
and operating the meetup group.

== Getting Started

Send us an email jenkinsci-jam@googlegroups.com to get started. Let us know the
city in which you’d like to host the JAM. Our team will create a meetup page on
meetup.com and we will work with you to organize your JAM.

*JAM Support*

* Swag - We will send you cool swags (stickers, t-shirts, Jenkins bobble-heads, etc) to share with members
* Promote - We give every JAM continuous social media love via Twitter, blog posts, Facebook, newsletter, and post on the jenkinsci.org events calendar.
* Jenkins Expertise - We will help you to schedule a Jenkins expert as the key speaker at your JAM, or provide you with presentation materials.
* Outreach - We will assist in reaching out to your local community for food/venue sponsorship.

=== Best Practices

* Attend existing meetup groups to gauge Jenkins interest/market within your area.
* Reach out to existing JAM organizer(s) to learn best practices and time commitment.
* Set up a Twitter account (for example, #JenkinsNYC). Email your group’s Twitter ID to jenkinsci-jam@googlegroups.com so we can help to promote your JAM.
* Promote, tweet and post your JAM in advance.
* Avoid product pitches. Keep it real, it’s not about promotions. This is about - and for - learning opportunities for the community.
* Shake up the format. Have presentations, panel discussions, roundtables, workshops, hackathons, etc.
* Set a consistent date, time and location so members will plan for it. Avoid cancelling your meeting as people will lose faith and stop RSVPing for your JAM.

=== Stepping Down

In the event you can no longer be a JAM organizer, we ask that you nominate a
replacement organizer in your place. If this is not possible please send email
to jenkinsci-jam@googlegroups.com, we will work with you to find a replacement.

== Supporting a JAM

If you are not able to be a JAM organizer, food or venue, or recording sponsors are always needed. If your company is interested in sponsoring any of these items pls email jenkinsci-jam@googlegroups.com or reach out to the local JAM organizer via meetup.com.

*Benefits of Being a Food or Venue or Recording Sponsor:*

* Logo and link on the meetup page.
* Verbal acknowledgement at the opening/closing remark by the host.
* Sponsor table at the meeting to display collaterals, signage, swag.
* Opportunity to host a drawing.
* Mention in social media.
* A two minute talk to address the attendees.

*Food Sponsor:*

Sponsor food and beverages for the specific month's meetup. The cost is about
$200 to $600 depending on the number of attendees. The money is used to
purchase pizza, soft drinks and paperware. One sponsor is needed for each
monthly meeting.

*Venue Sponsor:*

Venue sponsors provide the facility to host the meeting for free. One venue sponsor is needed per meeting. A meeting room with chairs and a couple of six feet tables with open space for food/beverages and mingling would be sufficient. Access to a public bathroom would be needed as well. A meetup will need such equipments as projection and screen. In the event where a meeting has more than 50 attendees an audio system will be needed.

*Recording Sponsor:*

Recording sponsor volunteer his/her recording equipments and time to record a
meeting and make it public after the meeting.


== JAMs Around the World

The list below is manually curated, for the most up-to-date information,
consult this link:https://www.meetup.com/pro/jenkins/[meetup.com page].

We also have the link:http://www.meetup.com/Jenkins-online-meetup/[Jenkins Online Meetup].

=== North America

* link:http://www.meetup.com/Atlanta-Jenkins-Meetup/[Atlanta, GA]
* link:http://www.meetup.com/Austin-Jenkins-Area-Meetup/[Austin, TX]
* link:http://www.meetup.com/Boston-Jenkins-Area-Meetup/[Boston, MA]
* link:http://www.meetup.com/Boulder-Jenkins-Area-Meetup/[Boulder, CO]
* link:http://www.meetup.com/DFW-Jenkins-Area-Meetup/[Dallas/Fort Worth, TX]
* link:http://www.meetup.com/Guadalajara-Jenkins-Area-Meetup/[Guadalajara, Mexico]
* link:http://www.meetup.com/Los-Angeles-Jenkins-Area-Meetup/[Los Angeles, CA]
* link:http://www.meetup.com/NYC-Jenkins-Meetup/[New York, NY]
* link:http://www.meetup.com/Raleigh-Jenkins-Area-Meetup/[Raleigh, NC]
* link:http://www.meetup.com/San-Francisco-Jenkins-Area-Meetup/[San Francisco, CA]
* link:http://www.meetup.com/Seattle-Jenkins-Area-Meetup/[Seattle, WA]
* link:http://www.meetup.com/Washington-DC-Jenkins-Area-Meetup/[Washington, DC]

=== Europe

* link:http://www.meetup.com/Amsterdam-Jenkins-Area-Meetup/[Amsterdam, Netherlands]
* link:http://www.meetup.com/Barcelona-Jenkins-Area-Meetup/[Barcelona, Spain]
* link:http://www.meetup.com/Brno-Jenkins-Area-Meetup/[Brno, Czech Republic]
* link:http://www.meetup.com/Budapest-JenkinsCI-Users/[Budapest, Hungary]
* link:http://www.meetup.com/Jenkins-Copenhagen-JAM/[Copenhagen, Denmark]
* link:http://www.meetup.com/Dublin-Jenkins-Meetup/[Dublin, Ireland]
* Hamburg, Germany
* London, UK
* Moscow, Russia
* link:http://www.meetup.com/Rennes-Jenkins-Area-Meetup/[Rennes, France]
* link:http://www.meetup.com/Seville-Jenkins-Area-Meetup/[Seville, Spain] - link:http://seville-jam.es/[website]
* link:http://www.meetup.com/St-Petersburg-Jenkins-Meetup/[St. Petersburg, Russia]
* link:http://www.meetup.com/Stockholm-Jenkins-Meetup/[Stockholm, Sweden]
* link:http://www.meetup.com/Toulouse-Jenkins-Area-Meetup/[Toulouse, France]
* Zurich, Switzerland

=== Asia

* Bangalore, India
* link:http://www.meetup.com/Delhi-Jenkins-Meetup/[Delhi, India]
* Hyderabad, India
* Singapore, Singapore
* link:http://www.meetup.com/Tel-Aviv-Jenkins-Area-Meetup/[Tel Aviv, Israel]

=== South America

* link:http://www.meetup.com/Lima-Jenkins-Area-Meetup/[Lima, Perú]

== Resources
