---
layout: project
title: "Remoting and Agent support"
section: projects
tags:
- remoting
- agent
- agents
- slave
- slaves
---

Jenkins Remoting is a library and executable JAR, which implements communication layer in Jenkins automation server: 
TCP-based communication protocols, Remote procedure calls, classloading, data streaming, etc.
It's being used in _master <=> agent_ communications and also in several other cases (Remoting CLI, Maven Project Plugin).
Effectively, `slave.jar` in agents is a renamed Remoting JAR file.

Remoting subproject includes the Remoting library itself, packaging for agents, and also specific Jenkins plugins and core modules.

:toc:

== Project Scope

== Remoting Library

link:https://github.com/jenkinsci/remoting[Remoting Library] is a main component of the Remoting subproject.

* link:https://github.com/jenkinsci/remoting/blob/master/README.md[Documentation]
* link:https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md[Changelog]

== Packaging

There are several packages, which bundle Remoting library and allow connecting Jenkins agents
via one of remoting protocols.