---
:layout: post
:title: "Google Summer Of Code 2017: Call for mentors"
:tags:
- gsoc
- events
- general
- gsoc2017
:author: oleg_nenashev
---


On behalf of the GSoC Org Admin team I am happy to announce that we are going to apply to
link:https://developers.google.com/open-source/gsoc/[Google Summer of Code (GSoC) again this year].
In GSoC high-profile students work in open-source projects for several months under mentorship of organization members.

We are looking for mentors and project ideas.
So yes, we are looking for you :)

== Conditions

As a mentor, you will be asked to:

* lead the project in the area of their interest
* actively participate in the project during student selection, community bonding and coding phases (March - August)
* work in teams of 2+ mentors per 1 each student
* dedicate a consistent and significant amount of time, especially during the coding phase (_~5 hours_ per week in the team of two mentors)

Mentorship does not require strong expertise in Jenkins plugin development.
The main objective is to guide students and to get them involved into the Jenkins community.
If your mentor team requires any specific expertise, GSoC org admins will do their best in order to find advisors.

== What do you get?

* A student, who works within the area of your interest on full-time for several months
* Joint projects with Jenkins experts, lots of fun and ability to study something together
* Limited edition of swags from Google and Jenkins project
* Maybe: Participation in GSoC Mentor Summit in California with expense coverage (depends on project results and per-project quotas)

== Requirements

You are:

* passionate about Jenkins
* interested in being a mentor or advisor
* ready to dedicate time && have no major unavailability periods planned to this summer
 ** We expect mentors to be available by email during 75% of working days in the May-August timeframe

Your project idea is:

* about code (though it may and likely should include some documentation and testing work)
* about Jenkins (plugins, core, infrastructure, etc.)
* potentially doable by a student in 3-4 months

== How to apply

If you are interested, drop the Email to the Jenkins Developer mailing list with the _GSoC2017_ prefix.

* Briefly describe your project idea (a couple of sentences) and required qualifications from students. Examples: link:https://wiki.jenkins-ci.org/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Projectideas[GSoC2016], link:/projects/gsoc[GSoC2017 - current project ideas]
* If you already have a co-mentor(s), please mention them
* Having several project ideas is fine. Having no specific ideas is also fine.

[NOTE]
====
Disclaimer: We cannot guarantee that all projects happen, it depends on student application results and the number of project slots.
====

== Links

* link:https://developers.google.com/open-source/gsoc/[Google Summer of Code page]
* link:/projects/gsoc[Jenkins GSoC Page]
* link:https://wiki.jenkins-ci.org/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Projectideas[GSoC2016 project ideas]

* link:/projects/gsoc/gsoc2016[GSoC2016 page] (project results and more info)
