---
layout: post
title: "Pipeline as YAML (Simple pull request plugin)"
tags:
- gsoc2018
- plugin
- pipeline
- yaml
author: abhishek_gautam
---

=== About me

I am Abhishek Gautam, 3rd year student from Visvesvaraya National Institute of
technology, India, Nagpur. I was a member of ACM Chapter and Google student developer club of my
college. I am passionate about automation.

=== Project Summary

This is a GSoC 2018 project.

This project aims to develop a pull request Job Plugin. Users should be able to
configure job type using YAML file placed in root directory of the
Git repository being the subject of the pull request. The plugin should interact with various
platforms like Bitbucket, Github, Gitlab, etc whenever a pull request is created or updated.

Plugin detects the presence of certain types of reports at conventional locations,
and publish them automatically. If the reports are not present at their respective conventional
location, the location of the report can be configured in the YAML file.

My mentors are
link:https://github.com/oleg-nenashev[Oleg Nenashev] (Org Admin),
link:https://github.com/martinda[Martin d'Anjou],
link:https://github.com/kwhetstone[Kristin Whetstone],
link:https://github.com/grandvizier[Jeff Knurek]

==== Project Repository
link:https://github.com/jenkinsci/simple-pull-request-job-plugin[Project repository]

==== Code changes

All the pull requests made can be found link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pulls?q=is%3Apr+is%3Aclosed[here]

==== List of major pull requests.

===== Phase 1
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/5[PR-5]: Git wrappers like clone, pull, checkout,
pullChangesOfPullrequest, merge, deleteBranch and merge added.
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/6[PR-6]: Yaml to Declarative Pipeline code generation.

Please see link:https://jenkins.io/blog/2018/06/15/simple-pull-request-plugin/[Phase 1 blog post]

===== Phase 2
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/11[PR-11]: Implemented StepConfigurator
using Jenkins configuration as code plugin.
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/19[PR-19]: Unit tests created for agent and yaml to pipeline generation.

Please see link:https://jenkins.io/blog/2018/07/17/simple-pull-request-plugin/[Phase 2 blog post]

===== Phase 3
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/25[PR-25]: Declarative pipeline code generator code
exported to extensions for extensibility and support of custom sections

=== Benefits to the community

* Project administrators will be able to handle pull request builds more easily.
* Build specifications for pull requests can be written in a concise declarative format.
* Build reports will be automatically published to Github, Bitbucket, etc.
* Build status updates will be sent to git servers automatically.
* Users will not have to deal with pipeline code.
* If there will be no merge conflicts or build failures, the PR can be merged into target branch.

=== Implementations till now

Alpha version of the plugin is released. It supports all features of Multi-Branch Pipeline and offers the following features.

Build description is defined via YAML file stored within the SCM repo. This plugin
will depend on GitHub plugin, Bitbucket plugin, Gitlab plugin if users will be
using respective platforms for their repositories.

. Conversion of YAML to Declarative Pipeline: A class YamlToPipeline
is written which will load the "Jenkinsfile.yaml" and make use of PipelineSnippetGenerator class
to generate Declarative pipeline code.
. Reporting of results, only xml report types is supported for now.
. Use of Yaml file (Jenkinsfile.yaml) from target branch.
. Git Push step: To push the changes of pull request to the target branch. This is implemented
using git-plugin, PushCommand is used for this from git-plugin. credentialId,
branch name and repository url for interacting with Github, Bitbucket, etc
will be taken automatically from "Branch-Source" (Users have to fill this
details of branch source in job configuration UI). (You can see
link:https://github.com/Jenkinsci/simple-pull-request-job-plugin/blob/master/README.md[How to run the demo])
. StepConfigurator: To generate pipeline code for all supported steps in Jenkins. This is using
Jenkins configuration-as-code plugin (JCasC plugin) to configure a particular step object and
then that step object is passed to `Snippetizer.object2Groovy()` method to generate the script of that step.

=== Jenkinsfile.yaml example

For the phase 1 prototype demonstration Finalize documentationn, the following yaml file was used.
Note that this format is subject to change in the next phases of the project,
as we formalise the yaml format definition.

[source, yaml]
----
#  Docker image agent example
agent:
 label: my_label
 customWorkspace: path_to_workspace
 dockerImage: maven:3-alpine
 args: -v /tmp:/tmp

  tools:
    maven : maven_3.0.1
    jdk : jdk8

configuration:
  # Push PR changes to the target branch if the build succeeds.
  # default value is false
  pushPrOnSuccess: false

  # Trusted user to approve pull requests
  prApprovers:
    - username1
    - username2
    - username3

environment:
  variables:
    variable_1: value_1
    variable_2: value_2

  # Credentials contains only two fields. credentialId must be present in the Jenkins Credentials
  credentials:
    - credentialId : fileCredentialId
      variable : FILE

      # In user scripts Username and Password can be accessed by LOGIN_USR and LOGIN_PSW
      # respectively as environment variales
    - credentialId : dummyGitRepo
      variable : LOGIN

stages:
  - name: stage1
    agent: any
    steps:
      - sh: "scripts/hello"
      - sleep:
          time: 2
          unit: SECONDS
      - sleep: 2
      - junit:
          testResults: "target/**.xml"
          allowEmptyResults: true
          testDataPublishers:
            - AutomateTestDataPublisher
            - JunitResultPublisher:
                urlOverride: "urlOverride"
    # Post section for "stage1". All Conditions which are available in Jenkins
    # declarative pipeline are supported
    post:
      failure:
        - sh: "scripts/hello"

# Outer post section. Just like declarative pipeline.
post:
  always:
    - sh: "scripts/hello"
----

=== Tasks completed in Coding Phase 3

. Add unit tests, JenkinsRule tests link:https://issues.jenkins-ci.org/browse/JENKINS-52495[JENKINS-52495]
. Refactor snippet generator to extensions (link:https://issues.jenkins-ci.org/browse/JENKINS-52491[JENKINS-52491])
. Plugin overview (Present in link:https://github.com/jenkinsci/simple-pull-request-job-plugin/blob/master/README.md[README.md])


=== Future tasks
https://issues.jenkins-ci.org/browse/JENKINS-52452[Phase 3 Jira Epic]

. Release 1.0 (link:https://issues.jenkins-ci.org/browse/JENKINS-52519[JENKINS-52519])
. Support the “when” Declarative Pipeline directive (link:https://issues.jenkins-ci.org/browse/JENKINS-52520[JENKINS-52520])
. Nice2have: Support hierarchical report types (link:https://issues.jenkins-ci.org/browse/JENKINS-52521[JENKINS-52521])
. Acceptance Test Harness tests link:https://issues.jenkins-ci.org/browse/JENKINS-52496[JENKINS-52496]
. Automatic Workspace Cleanup when PR is closed (link:https://issues.jenkins-ci.org/browse/JENKINS-51897[JENKINS-51897])

. Test Multi-Branch Pipeline features support:
.. Support for webhooks (link:https://issues.jenkins-ci.org/browse/JENKINS-51941[JENKINS-51941])
.. Check if trusted people have approved a pull request and start build accordingly (link:https://issues.jenkins-ci.org/browse/JENKINS-52517[JENKINS-52517])
. Finalize documentation (link:https://issues.jenkins-ci.org/browse/JENKINS-52518[JENKINS-52518])

. Test the integration with various platforms Bitbucket, Gitlab, Github.


=== Phase 3 evaluation presentation video


Video: link:https://www.youtube.com/watch?v=GGEtN4nbtng[Link to video evaluation]
++++
<center>
      <iframe width="720" height="400" src="https://www.youtube.com/watch?v=GGEtN4nbtng"
  frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</center>
++++

=== Phase 3 evaluation presentation slides

link:https://speakerdeck.com/player/46e467bc5e364cb08c39b9e4b69bdef2[Link to presentation slides]

++++
<center>
    <iframe width="720" height="400" frameborder="0"
      src="https://speakerdeck.com/player/46e467bc5e364cb08c39b9e4b69bdef2"></iframe>
</center>
++++

=== How to reach me

* Email: gautamabhishek46@gmail.com
* Gitter room: link:https://gitter.im/Jenkinsci/simple-pull-request-job-plugin[]

=== References

* link:https://github.com/jenkinsci/simple-pull-request-job-plugin[Project repository]
* link:https://jenkins.io/projects/gsoc/2018/simple-pull-request-job-plugin/[Project page]
* link:https://gitter.im/jenkinsci/simple-pull-request-job-plugin?utm_source=share-link&utm_medium=link&utm_campaign=share-link[Gitter chat]
* link:https://issues.jenkins-ci.org/issues/?jql=project%20%3D%20Jenkins%20AND%20component%20%3D%20simple-pull-request-job-plugin[Bug Tracker]
* link:https://github.com/gautamabhishek46/dummy[Demo Repository]