---
layout: post
title: "alpha-3 release Pipeline as YAML (Simple pull request plugin)"
tags:
- gsoc2018
- plugin
- pipeline
- yaml
author: abhishek_gautam
---

=== About me

I am Abhishek Gautam, 3rd year student from Visvesvaraya National Institute of
technology, India, Nagpur. I was a member of ACM Chapter and Google student developer club of my
college. I am passionate about automation.

=== Project Summary

This is a GSoC 2018 project.

This project aims to develop a pull request Job Plugin. Users should be able to
configure job type using YAML file placed in root directory of the
Git repository being the subject of the pull request. The plugin should interact with various
platforms like Bitbucket, Github, Gitlab, etc whenever a pull request is created or updated.

Plugin detects the presence of certain types of reports at conventional locations,
and publish them automatically. If the reports are not present at their respective conventional
location, the location of the report can be configured in the YAML file.

My mentors are
link:https://github.com/oleg-nenashev[Oleg Nenashev] (Org Admin),
link:https://github.com/martinda[Martin d'Anjou],
link:https://github.com/kwhetstone[Kristin Whetstone],
link:https://github.com/grandvizier[Jeff Knurek]

==== Project Repository
link:https://github.com/jenkinsci/simple-pull-request-job-plugin[Project repository]

==== Code changes

All the pull requests made can be found link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pulls?q=is%3Apr+is%3Aclosed[here]

==== List of major pull requests.

===== Phase 1
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/5[PR-5]: Git wrappers like clone, pull, checkout,
pullChangesOfPullrequest, merge, deleteBranch and merge added.
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/6[PR-6]: Yaml to Declarative Pipeline code generation.

Please see link:/blog/2018/06/15/simple-pull-request-plugin/[Phase 1 blog post]

===== Phase 2
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/11[PR-11]: Implemented StepConfigurator
using Jenkins configuration as code plugin.
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/19[PR-19]: Unit tests created for agent and yaml to pipeline generation.

Please see link:/blog/2018/07/17/simple-pull-request-plugin/[Phase 2 blog post]

===== Phase 3
* link:https://github.com/jenkinsci/simple-pull-request-job-plugin/pull/25[PR-25]: Declarative pipeline code generator code
exported to extensions for extensibility and support of custom sections

=== Jenkinsfile.yaml example

Documentation of Jenkinsfile.yaml and yaml format can be found link:https://github.com/jenkinsci/simple-pull-request-job-plugin/tree/master/yamlExamples[here]

=== Tasks completed in Coding Phase 3

. Add unit tests, JenkinsRule tests link:https://issues.jenkins.io/browse/JENKINS-52495[JENKINS-52495]
. Refactor snippet generator to extensions (link:https://issues.jenkins.io/browse/JENKINS-52491[JENKINS-52491])
. Plugin overview (Present in link:https://github.com/jenkinsci/simple-pull-request-job-plugin/blob/master/README.md[README.md])


=== Future tasks
https://issues.jenkins.io/browse/JENKINS-52452[Phase 3 Jira Epic]

. Release 1.0 (link:https://issues.jenkins.io/browse/JENKINS-52519[JENKINS-52519])
. Support the “when” Declarative Pipeline directive (link:https://issues.jenkins.io/browse/JENKINS-52520[JENKINS-52520])
. Nice2have: Support hierarchical report types (link:https://issues.jenkins.io/browse/JENKINS-52521[JENKINS-52521])
. Acceptance Test Harness tests link:https://issues.jenkins.io/browse/JENKINS-52496[JENKINS-52496]
. Automatic Workspace Cleanup when PR is closed (link:https://issues.jenkins.io/browse/JENKINS-51897[JENKINS-51897])

. Test Multi-Branch Pipeline features support:
.. Support for webhooks (link:https://issues.jenkins.io/browse/JENKINS-51941[JENKINS-51941])
.. Check if trusted people have approved a pull request and start build accordingly (link:https://issues.jenkins.io/browse/JENKINS-52517[JENKINS-52517])
. Finalize documentation (link:https://issues.jenkins.io/browse/JENKINS-52518[JENKINS-52518])

. Test the integration with various platforms Bitbucket, Gitlab, Github.


=== Phase 3 evaluation presentation video


Video: link:https://www.youtube.com/watch?v=GGEtN4nbtng[Link to video evaluation]
++++
<center>
  <iframe width="720" height="400" src="https://www.youtube.com/embed/GGEtN4nbtng?start=250"
  frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</center>
++++

=== Phase 3 evaluation presentation slides

link:https://speakerdeck.com/player/46e467bc5e364cb08c39b9e4b69bdef2[Link to presentation slides]

++++
<center>
    <iframe width="720" height="400" frameborder="0"
      src="https://speakerdeck.com/player/46e467bc5e364cb08c39b9e4b69bdef2"></iframe>
</center>
++++

=== My GSoC experience

Student applications started on March 12 16:00 UTC and ended on March 27 16:00 UTC. Application period allowed me to explore
many new technology and platforms that are making peoples life easy.

Before starting of the application
period I did not know anything about Jenkins. I found Jenkins organisation on the link:https://summerofcode.withgoogle.com/organizations/[GSoC organisations page]
and came to know that I is a CI/CD platform that is used automate various things related to software development. I studied
about Jenkins online and went through the link:/projects/gsoc/gsoc2018-project-ideas/[problem statements provided by some mentors].

I decided that to work on link:/projects/gsoc/gsoc2018-project-ideas/#simple-pull-request-job-plugin[Simple Pull-Request Job Plugin] project.
Then I wrote a draft proposal for this project and received many comments to refactor the proposal and enhance its quality from the mentors,
then finally I submitted my link:https://summerofcode.withgoogle.com/serve/5141186688319488/[final proposal] to Google.

I was able to complete most of the tasks decided in Phase 1 and 2. After Phase 2 I was not able to give time to the project because
of the placement season in the my college. I modified the code so that other plugin developers can contribute to it by Jenkins extensions.

All the mentors made themselves available for most of the weekly calls and provided many valuable suggestions during the
entire period of GSoC. Sometimes I was not able to communicate effectively. As communication is the key while working remotely, mentors
suggested to communicate more thorough gitter chat.

My overall experience of GSoC was good and all the mentors helped me as they can all times. This project allowed me to explore
Jenkins and the services offered by it. I am allowed to work on the project after GSoC ends (This is a good thing).

=== How to reach me

* Email: gautamabhishek46@gmail.com
* Gitter room: https://app.gitter.im/#/room/#jenkinsci_simple-pull-request-job-plugin:gitter.im[]

=== References

* link:https://github.com/jenkinsci/simple-pull-request-job-plugin[Project repository]
* link:/projects/gsoc/2018/simple-pull-request-job-plugin/[Project page]
* link:https://app.gitter.im/#/room/#jenkinsci_simple-pull-request-job-plugin:gitter.im[Gitter chat]
* link:https://issues.jenkins.io/issues/?jql=project%20%3D%20Jenkins%20AND%20component%20%3D%20simple-pull-request-job-plugin[Bug Tracker]
* link:https://github.com/gautamabhishek46/dummy[Demo Repository]
