---
layout: post
title: "Pipeline-Authoring SIG Update"
tags:
- Pipeline-Authoring
- SIG
- community
- opensource
author: markyjackson-taulia
---


==== What is the Pipeline-Authoring Special Interest Group

This special interest group aims to improve and curate the experience of authoring Jenkins Pipelines. This includes the
syntax of `Jenkinsfile`s and shared libraries, code sharing and reuse, testing of Pipelines and shared libraries, IDE
integration and other development tools, documentation, best practices, and examples.

=== What Are The Focus Areas of the Pipeline-Authoring Special Interest Group

* Syntax - How `Jenkinsfile`s and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of `Jenkinsfile`s and shared libraries.
* IDE integration, editors, and other development tools - IDE plugins, visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evangelizing best practices in Jenkins Pipeline.
* Examples - Real-world `Jenkinsfile`s and shared libraries demonstrating how to utilize various features of Pipeline,
as well as basic or starter `Jenkinsfile`s for common patterns that can be used as jumping-off points by new users.


=== What Have We Been Up To
With the start of a new year, members got together to discuss the roadmap for 2020. During the initial discussions we
determined that it would be good to examine the goals of previous meetings and determine the best path forward.

A mutual decision was made that to better create a roadmap; we needed to understand better who we were aiming to help.
We decided that creating personas was very beneficial. Personas are fictional characters, which we are creating based
upon our research to represent the different user types that might use Jenkins pipelines.
Creating personas can help us step out of ourselves. It can help us to recognize that different people have different
needs and expectations, and it can also help us to identify with the user we are building the roadmap for. Personas make
the task at hand less complicated, they guide our ideation processes, and they can help us to achieve the goal of
creating a good user experience for our target user group.
A lot of that work can be found here:
https://docs.google.com/document/d/1CdyzJwt50Wk3uUNsLMl2d4w2MGYss-phqet0s-KjbEs/edit
The idea is to map the personas to a maturity model and then map the maturity model to the actual documentation. That
maturity model can be found here: https://drive.google.com/file/d/1ByzWlPU0j1qM_gqspJppkNKkR5ZVLWlB/view

=== How Can I Get Involved

We have been meeting regularly to define personas to help us better create the SIG roadmap. We meet twice a week,
once on Thursday for the EMEA timezone and once on Friday for the US timezone. Meeting notes can be found here:
https://docs.google.com/document/d/1EhWoBplGl4M8bHz0uuP-iOynPGuONjcz4enQm8sDyUE/edit# and the calendar, if you would
like to attend link:/event-calendar[here]. The previous recording of the meetings are
located here: https://www.youtube.com/watch?v=pz_kPpb9C1w&list=PLN7ajX_VdyaOKKLBXek6iG8wTS24Ac7Y3

=== Next Steps

We have a lot of work to do and could use your help. If you would love to join us, check out the meeting link. If you
would like to check out the personas and give feedback, also check out the link.
Once we have wrapped up the personas work, we will start to identify the available documentation and ensure we have
adequate documentation with the help of the Doc SIG.
We will finally then start working to build out tools to help the community with pipelines in Jenkins better.

=== Contact Us

If you would like to get in touch with the Pipeline-Authoring SIG, you can by joining the
link:https://app.gitter.im/#/room/#jenkinsci_pipeline-authoring-sig:gitter.im[Pipeline-Authoring SIG gitter channel] or via the
link:https://groups.google.com/g/jenkins-pipeline-authoring-sig/[Pipeline-Authoring SIG mailing list]
