---
layout: post
title: "Google Summer of Code Mentor and Org Admin Perspective"
tags:
- gsoc
- gsoc2019
- jenkins
- community
- events
- mentor
author: markyjackson-taulia
---

I was fortunate enough to participate in the Google Summer of Code 2019 as a mentor and org admin. This was great
and I wanted to share in hopes of encouraging more people to join.
link:/projects/gsoc/[You can learn more about the Google Summer of Code here]

== Community Bonding

The first phase of the project is the community bonding phase. This is where the student and other mentors come together
to lay out the plan for the project. It is important to set expectations and ensure that the student is well aware of
what will take place and also made to feel welcome.

link:/blog/authors/baymac[Parichay Barpanda] was the student and he was super awesome from the get go. The project he was working on was the Gitlab
Branch Source Plugin. More can be found here: link:https://github.com/jenkinsci/gitlab-branch-source-plugin[jenkinsci/gitlab-branch-source-plugin]

From the mentor side it was myself and Justin Harringa. Justin was just amazing throughout this project and I seriously
could not have done this without him. He was encouraging, empathetic and just all around great. I would gladly serve
with him again.

We laid out our plan and guidance and got to work.

== First Evaluations

The first evaluation was quickly upon us and Parichay was ready!
The work he put in was nothing shy of amazing. We did our 1st demo and he really rocked it. A video of that demo can be
found on : link:https://www.youtube.com/watch?v=ij6ByZqI67o[Youtube]

== Second Evaluations

There was not much time to rest before we realized that phase II end was upon us but Parichay was ready. Again, he
nailed it.

That demo can be found link:https://www.youtube.com/watch?v=tnoObQqGhyM&t=2380s[here]

== Mentors Submit Final Evaluations

We had our final evaluation and at this point Parichay was seasoned. He was getting issues assigned to him, working on
little bug fixes and setting his roadmap for features. He absolutely blew Justin and I away.

Parichay's final evaluation demo can be seen link:https://www.youtube.com/watch?v=cMSbdGwGWp0&t=905s[here]

At the conclusion of the final demo's, Justin and I met and went over Parichay's final evaluation. At this point we had
met twice a week for several months, we have reviewed code daily, we had community involvement and most of all we had
seen Parichay grow into a seasoned software developer.

Justin and I were without a doubt passing Parichay on his entire body of work. I am actually tearing up typing this
because I am so proud of Parichay.

== Org Admin

Being an org admin for the 2019 Google Summer of Code project for the Jenkins organization was truly rewarding and couldn't
have been accomplished without the help from Oleg Nenashev, Martin d'Anjou, Jeff Pearce and Lloyd Chang.

As an org admin we handled issues with mentors, community members and disagreements involving work. These items were only
a few and as a team we handled them accordingly.

We regularly met to discuss and plan. Coordinating and dealing with a project like Google Summer of Code is no small feat
but this team made it super easy and I am so thankful for them and all that I learned.

== Closing

In looking back at this experience I am so grateful for the opportunity I was given. This was such a rewarding experience
to not only be able to mentor but also be an org admin. Not only will I be back next year (we are already in the
planning stages) but I highly encourage people reading this to consider joining. You will not be disappointed.

I am so thankful for all the students, mentors and fellow org admins. Your dedication to open source is so valued. You
showed and continue to show what this project is all about, and that is being welcoming, open and transparent. Helping
people grow as individuals while learning skills is what I love about this community.

Thank you to everyone and I hope your futures are bright!
