---
layout: gsocprojectidea
title: "Android and/or iOS tutorials in official documentation"
goal: "Adding Android and/or iOS tutorials for Jenkins in the official documentation"
category: Documentation
year: 2025
status: draft
sig: documentation
skills:
- Documentation
- Java
- YAML
- Android / iOS development
- Command line tools
mentors:
- "gounthar"
- "krisstern"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

Topics such as _how to proceed_, _what are the successful patterns_, and _what are the pitfalls_ are poorly documented.
It very often requires potential users and Jenkins Administrators to "reinvent the wheel".

==== iOS
The project idea is to have a clear status of what can be done with Jenkins for iOS app builds now.
There are only a few articles here and there about iOS.

==== Android
For Android development, some experiments are link:https://github.com/gounthar/MyFirstAndroidAppBuiltByJenkins[available] and were link:https://www.youtube.com/watch?v=fmTdT4Y-uCw&ab_channel=JeanQuinze[presented publicly].

The proof of concept could be docker-compose based.
It would work under Windows, Linux, Vagrant, macOS (x86 and ARM), and _mostly_ on Gitpod.
It should be easily transposable to a production environment.
The demo/proof-of-concept would be composed of a Jenkins controller (configured with JCasc), an Android agent, a generic Docker agent, an Android emulator, and an Android device farm (link:https://github.com/DeviceFarmer[STF]).

The idea is to have a more precise status of what can be done now with Jenkins.
We could then amend the existing link:/solutions/android/[Android documentation] and describe architectures for:

* Standalone Android projects
* Android apps building farms
* Android distro building (customized AOSP)


=== Skills to Study and Improve

- Jenkins technical architecture
- iOS application development
- CI principle and practice
- Android application development
- Docker


=== Project Size
175 - 350 hours


=== Project Difficulty Level

Intermediate


=== Expected Outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
