---
layout: gsocprojectidea
title: "Complete build retooling of jenkins.io"
goal: "Using alternative tooling with Gatsby and Antora to build the Jenkins static site and provide versioned Jenkins documentation"
category: Tools
year: 2025
status: published
sig: documentation
skills:
- Web development
- AsciiDoc
- Static website tooling
- Documentation
- Website retooling
mentors:
- "krisstern"
- "gounthar"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

The link:/[jenkins.io] website is generated as a static website using Awestruct from AsciiDoc sources, YAML data files, and HAML templates stored in GitHub.
One of the drawbacks of the current build method is that the technical documentation is not product version bound.
It is thus not possible to view the documentation for a given Jenkins version.
Only the latest can be viewed.
This can lead to unnecessary confusion and is a worse experience than many other documentation sites like the git site, FreeBSD, and others...

The preferred tool to replace Awestruct is link:https://antora.org/[Antora].

The potential GSoC project would be to build a working site generator to demonstrate the existing site.
Once the existing site is generated with Antora, the site should be extended to add version specific documentation.

The project has been discussed extensively at link:https://github.com/jenkins-infra/jenkins.io/issues/5474[GitHub issue #5474], where some existing proof-of-concept code can be found referenced there.

// There are multiple ways to approach the implementation. Still, from experimentation, it has been found that the backend replacement requires minimal effort for the documentation, with the frontend implementation expected to require much effort to reproduce the look and feel of the current link:/[jenkins.io] website. However, the blog can be split from the documentation using something like link:https://www.gatsbyjs.com/[Gatsby], which is expected to make it easier for users to submit posts in the future.

We have already begun work on this project in GSoC 2023 as link:/projects/gsoc/2023/projects/alternative-jenkinsio-build-tool/["Building Jenkins.io with alternative tools"].
However, we were only able to complete most of the groundwork for the Antora part of the versioned docs and some of the groundwork for the Gatsby part, mostly for the non-versioned part.

So now the core work left will be to update the outdated content of both the Antora versioned docs as well as the Gatsby backbone at the project at link:https://github.com/jenkins-infra/docs.jenkins.io/[jenkins-infra/docs.jenkins.io repo].

The outcome of this project is expected to produce a visible impact they can showcase in their portfolio of the link:/[jenkins.io] website, as the GSoC contributor is also expected to contribute via UI/UX improvements beyond the basic tooling required.

This selected GSoC contributor is expected to work very diligently to play catch up with the transition from the current link:https://github.com/jenkins-infra/jenkins.io/[jenkins.io repo] and the new link:https://github.com/jenkins-infra/docs.jenkins.io/[jenkins-infra/docs.jenkins.io repo].
So we will only shortlist candidates who do not have competing commitments in order for this project to have a successful outcome.

Please note that for the UI/UX improvement portion we may need to deal with the link:https://github.com/jenkins-infra/jenkins-io-components[jenkins-io-components repo], where the code for components shared by various Jenkins websites (link:/[jenkins.io], link:https://plugins.jenkins.io/[plugins.jenkins.io], etc.) is currently hosted.


=== Quick Start

Documentation quick start steps include:

* Build the current documentation site locally
* Become familiar with the current site, including:
** Page types and how they are generated
*** Changelogs
*** Roadmap
*** User handbook
*** Developer handbook
*** Artwork
*** Security advisories
*** Version specific content in tutorials (like "Improve a plugin")
** Page content sources
*** Asciidoc
*** HAML / Ruby
*** Web components
** Build process
*** Makefile
*** Docker containers
*** Syntax and spelling checks
* Fix several link:https://github.com/jenkins-infra/jenkins.io/labels/good%20first%20issue/["good first issues"]
* Explore link:https://github.com/jenkins-infra/jenkins-io-components[jenkins-io-components repo]
* Explore link:https://antora.org/[Antora]
* Review version specific documentation techniques (some of them are Antora sites)
** link:https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-secure-guide/folders-plus[CloudBees documentation site]
** link:https://git-scm.com/docs/git-config[Git reference pages]
** link:https://docs.python.org/3/[Python] (sphinx is the generator)
** link:https://pytorch.org/docs/stable/index.html[PyTorch]
** link:https://www.tensorflow.org/api_docs[TensorFlow]


=== Skills to Study and Improve

* Web development
* AsciiDoc
* Static website tooling
** HAML templates
** YAML data files
* Documentation


=== Project Difficulty Level

Beginner to Intermediate


=== Project Size

175 to 350 hours


=== Expected outcomes

The deliverables of the project would be:

1. Iterative and incremental improvements to the site throughout the project
2. Demonstration that all the existing pages are rendered in an equivalent way
    - Suggestions of improved page design(s)
    - A list of all automation that are difficult/impossible to port to the new tool
    - Suggestions and demos of alternative ways to solve this
3. Demonstration of the versioned documentation automated tooling
    - Description of the publication process (how does one contribute to document a new or modified feature)
4. Successful migration of revamped link:/[jenkins.io] website to replace website using old tooling


=== New features

Improved layout of the existing site and its pages.
New link:/[jenkins.io] website.


=== Newbie Friendly Issues

Basically any good-first-issue listed in the jenkins.io GitHub repo would do. These can be accessed at the link:https://github.com/jenkins-infra/jenkins.io/labels/good%20first%20issue/[GitHub repo issues tracker with the "good first issue" label].
