---
layout: gsocprojectidea
title: "Pipeline documentation improvements - Phase 2 and Phase 3"
goal: "Improving the navigation and implementation of the Pipeline Steps Reference"
category: Documentation
year: 2025
status: draft
sig: documentation
skills:
- Documentation
- Web development
- Jenkins plugins
mentors:
- "krisstern"
- "berviantoleo"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

Continuing from link:https://www.jenkins.io/projects/gsoc/2022/projects/pipeline-step-documentation-generator/[the GSoC 2022 Pipeline Step Documentation Generator project] as Phase 2 of that project.
More to do during this Phase 2 and the next Phase 3, as we will need to include both the refinement of the detailing and the navigation design.
The project will involve the adopting of multiple plugins and improving their Pipeline Steps documentation.
The selected contributor is expected to do lots of writing, exploring, testing, but not lots of coding.


=== Quick Start

Studying all materials relevant to link:https://www.jenkins.io/projects/gsoc/2022/projects/pipeline-step-documentation-generator/[the GSoC 2022 Pipeline Step Documentation Generator project] and become familiar with them.


=== Skills to Study and Improve

* Jenkins plugin development life cycle
* Documentation
* Web UI/UX design for documentation
* Testing Jenkins plugins


=== Project Difficulty Level

Beginner to Intermediate


=== Project Size

175 to 350 hours (depending on the scope)
