---
layout: gsocprojectidea
title: "Improving Jenkinsfile Runner abilities and GitHub Actions"
goal: "To investigate the current state of the Jenkinsfile Runner project and to improve its abilities as well as those of GitHub Actions when used in conjunction"
category: Tools
year: 2025
status: draft
sig: platform
skills:
- Java
- Jenkinsfile Runner
- Docker
- GitHub Actions
mentors:
- "jonesbusy"
- "krisstern"
- "berviantoleo"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

This project idea is a continuation of the link:/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions.adoc/[GSoC 2022 Jenkinsfile Runner Action for GitHub Actions project].
The current link:https://github.com/jenkinsci/jenkinsfile-runner[Jenkninsfile Runner project] will need to switch to Spring Security 6, Jetty 12, as well as Jakarta EE 9 as part of its modernization.
We would like to encourage more adoption and compatibility with the latest Jenkins version.
There are many open issues within this project.
We will also need to work on reporting on GitHub checks.


=== Skills to Study and Improve

* Java
* To run Jenkinsfile Runner (an incubating project) to create an action inside Docker
* Docker configuration
* GitHub Actions configuration
* Jenkins modernization


=== Project Size
175 - 350 hours


=== Project Difficulty Level

Intermediate to Advanced


=== Expected outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
