---
layout: gsocprojectidea
title: "Improving Plugin Modernizer "
goal: "Improving the Jenkins Plugin Modernizer tool and provide integrations with Jenkins ecosystem"
category: Tools
year: 2025
status: published
sig: platform
skills:
- OpenRewrite
- Data structure (Trees) and visitor pattern
- Java
- Plugin hygiene and migration
mentors:
- "gounthar"
- "jonesbusy"
- "sridamul"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

This project idea is a continuation of the link:/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates[GSoC 2024 Using OpenRewrite Recipes for Plugin Modernization].
The current link:https://github.com/jenkins-infra/plugin-modernizer-tool[Plugin Modernizer] will need to be enhanced to support more modernization recipes and provide integrations with the Jenkins ecosystem.

Improvements and integration could include:

- Store metadata about the modernization process on link:https://reports.jenkins.io[Jenkins reports site]
- Provide APIs to access the modernization metadata in addition to the existing CLI module (or even run the modernization recipes as a service)
- Generate metadata regularly (using Jenkins infrastructure or GitHub Actions depending on the research done during the project)
- Better integration with the Plugin Health Score to automatically run modernization recipes on plugins with low scores
- Visualize the modernization metadata on link:https://stats.jenkins.io[Jenkins statistics site]
- Any recipe improvements or new recipes that could be added to the tool to improve plugins health
- ...


=== Skills to Study and Improve

* Java
* OpenRewrite
* Plugin refactoring and ecosystem
* Jenkins modernization


=== Project Size
175 - 350 hours


=== Project Difficulty Level

Intermediate to Advanced


=== Expected Outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
