---
layout: gsocprojectidea
title: "Revamping jenkins.io website Success Stories feature"
goal: "To investigate the current state of the Jenkinsfile Runner project and to improve its abilities as well as those of GitHub Actions when used in conjunction"
category: UI/UX
year: 2025
status: published
sig: infra
skills:
- Website development
- UI/UX design
- Geospatial data visualization
- Gatsby.js and React.js
mentors:
- "krisstern"
- "berviantoleo"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

The current jenkins.io "Success Stories" feature at link:https://stories.jenkins.io/[] is in need of a revamp to keep it looking sharp and relevant. The project at link:https://github.com/jenkins-infra/stories/[] is in need of modernization tech-stack wise, kas we ill need to upgrade the React version used as well as upgrade the versions of most of the dependencies used. Besides, we will need to redesign the layout of its UI/UX including but not limited to the landing page, the story page, the map, etc.


=== Skills to Study and Improve

* Website development
* UI/UX design
* Geospatial data visualization
* Gatsby.js and React.js


=== Project Size
175 hours


=== Project Difficulty Level

Beginner


=== Expected outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
