---
layout: gsocprojectidea
title: "Revamping jenkins.io website Success Stories feature"
goal: "To revamp jenkins.io website's Success Stories feature to update both tooling and UI/UX experience with new design"
category: UI/UX
year: 2025
status: published
sig: infra
skills:
- Website development
- UI/UX design
- Geospatial data visualization
- Gatsby.js and React.js
mentors:
- "krisstern"
- "berviantoleo"
- "iamrajiv"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

The current jenkins.io "Success Stories" feature at link:https://stories.jenkins.io/[] is in need of a revamp to keep it looking sharp and relevant.
The project at link:https://github.com/jenkins-infra/stories/[] is in need of modernization tech-stack wise, as we will need to upgrade the React version used to the latest possible (ideally v19) as well as upgrade the versions of most of the dependencies used.
Besides, we will need to redesign the layout of its UI/UX including but not limited to the landing page, the story page, the map, etc.

Moreover, the workflow for users to submit new stories may need to be redesigned and reimplemented, given the context of the Infra Helpdesk issue at link:https://github.com/jenkins-infra/helpdesk/issues/4392/[].


=== Skills to Study and Improve

* Website development
* UI/UX design
* Geospatial data visualization
* Gatsby.js and React.js


=== Project Size
175 hours


=== Project Difficulty Level

Beginner to Intermediate


=== Expected Outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
