---
layout: post
title: "Jenkins Hackfest in September"
tags:
- events
- community
- hacktoberfest
- newcomer
author: oleg_nenashev
---

After DevOps World - Jenkins World there was a 2-day Jenkins hackfest, 
sponsored by link:https://cloudbees.com[CloudBees].
Jenkins Community booth crew members and a number of speakers were invited to this event.
I was leading the event from the content site,
link:https://github.com/alyssat[Alyssa Tong] and link:https://github.com/bitwiseman[Liam Newman] provided all the logistics for the event.

Below there is a group photo of participants on the second day of the hackathon.
You can find more photos from events link:TODO[here]. 

There were 3 major topics of the event

* Java 11 support in Jenkins
* Jenkins Configuration-as-Code
* Jenkins infrastructure

=== Java 11 support

"Have you heard that Java 11 is coming?", "What would Java do?"... these are just few memes we had at this hackathon (thanks Mark!).

It was a major topic on our plate over last months.
In June we got a great progress during the link:TODO[Jenkins and Java 10+ hackfest],
and we wanted to get some progress towards support of Java 11 which was released few days after on September 25.
This time link:TODO[Mark Waite] was driving the effort.
Participants:
//TODO: list


Accomplishments:

* Exploratory testing everything with Java 11 eap 28 on Linux, Windows and MacOS
* Support running plugin builds on JDK 11
* Jenkins core builds with JDK11 (works on Oleg’s machine (c))
Ongoing memory leak investigation, grumbling
* A bunch of patches in the core (Update Center signature checks, Dev. tools, refactoring)
* Illegal Reflective access patches in EnvInject
* Testing Platform Labeler Plugin and other plugins with Java 11

After the hackathon we have presented the Java 11 support status at the link:/sigs/platform[Platform SIG meeting] and discussed the next steps
(link:TODO[meeting notes], link:TODO[video]).
Generally we are getting close to make Java 11 preview support available in common weekly releases according to the jep:211[] plan.
All mandatory Jenkins patches have been been already upstreamed to the master branch,
but we also need to enable CI flows on the master branch before it becomes fully available.
I plan to make a separate blogpost about it in November.

=== Jenkins Configuration as Code

There was a team working on the plugin:TODO[Configuration-as-Code plugin].
    link:https://github.com/ewelinawilkosz[Ewelina Wilkosz],
    link:https://github.com/ndeloof[Nicolas de Loof],
    link:https://github.com/uhafner[Ulli Hafner],
    link:https://github.com/martinda[Martin d'Anjou] and
    link:https://github.com/batmat[Baptiste Mathus]
focused on this area and did the following:

Accomplishments:

* Some patches for JCasC stability and Web UI
* Verified support in warnings plugin and added documentation/tests
* JCasC support in the External Workspace Manager plugin
* Fixed the random issue in the PR builder

// TODO: Photo

=== Jenkins Infrastructure

Last but not least, Jenkins Infrastructure.
It was our first time when we had such topic at Jenkins hackathons.
Olivier Vernin,
Michael Pailloncy,
James Albert, and
Pham Vu Tuan
worked together in order to improve the project infrastructure.

Summary:

* Jenkins.io and jenkins-ci.org DNS are on Azure
* Datadog monitoring was automated, repo still needs a transfer
* Progress on Account app for voting, the app has been also demoed during the hackfest
* Added JDK11 to the CI infrastructure

//TODO: image

=== Other topics

There were some other activities happening during the hackathon:

* 5 training and demo sessions done by participants:
    Jenkins Infrastructure,
    Intro to JCasC development,
    Warnings Plugin 5.0, etc.
* Sync-ups on projects: Google Summer of Code 2019, link:TODO
* Telemetry service ( jep:TODO[]) has been implemented by Daniel Beck
* Experiments with Pipeline on the K8s storage
* Mario Kart competitions. We do community bonding, not only the code!
* Together with Daniel Beck we ran a hand-on Jenkins Weekly release preparation

Full hackfest notes are available link:https://docs.google.com/document/d/1eI3e5u4XoE1q06wILv9sDRvYh91n1JCqZ4M1njcpp_Q/edit#[here].

//TODO: image

== Acknowledgements

I would like to personally thank CloudBees, Alyssa Tong and Liam Newman for making this event happen.
We did a great progress during the event w.r.t. various topics,
and it helps to push Jenkins forward.


