---
layout: post
title: "Jenkins Hackathons in October"
tags:
- events
- community
- hacktoberfest
author: oleg_nenashev
---

Traditionally there are a lot of events happening in the Jenkins organization in Autumn.
I would like to share some information about the upcoming hackathons.

== Online Event: Hacktoberfest

As you probably know, there is an ongoing link:https://hacktoberfest.digitalocean.com/[Hacktoberfest] event.
The Jenkins project is participating in it and everybody is welcome to contribute to Jenkins as a part of this event.
The event lasts from October 01 to October 31,
and you can can join it at any time.

See link:/blog/2018/10/01/hacktoberfest/[this blogpost] for more information about Hacktoberfest in the Jenkins project.

== Onsite Hackathons

Hacktoberfest is not the only event happening in the Jenkins community this month,
there are also a number of upcoming on-site events:

* Oct 19 - Copenhagen, Denmark - Jenkins Configuration as Code hackathon at 
  link:https://www.code-conf.com/2018/day-of-jenkins-as-code/[Day of Jenkins [as code]]
** Registration: all conference participants can attend
* Oct 22 - Nice, France - Hackathon at 
  link:https://www.cloudbees.com/devops-world/nice[DevOps World - Jenkins World Nice] 
  for those who arrive early for the conference and plan to also participate in the Jenkins Contributor Summit
** Registration: contact Oleg Nenashev in the 
   link:https://gitter.im/jenkinsci/jenkins-community[jenkinsci/community Gitter room]
* Oct 30 - Neuchatel, Switzerland - Hacktoberfest: Jenkins & Friends event (Swiss Jenkins Area meetup)
** Registration: RSVP to the meetup link:https://www.meetup.com/Swiss-Jenkins-Area-Meetup/events/255345695/[here]
* TBA - Beijing, China - Hacktoberfest

All contributions during these in-person events qualify as 
link:https://hacktoberfest.digitalocean.com/[Hacktoberfest] contributions as well. :)
More events will also be announced later in the year, 
e.g. we traditionally do a hackfest in Brussels after FOSDEM in February.
Follow our developer mailing lists and social media to receive announcements.
