
tags:
- events
- community
- hacktoberfest

Traditionally there is a lot of events happening in the Jenkins organization in September and October.
I would like to share some information about the incoming events and about what we achieved at the previous event at DevOps World | Jenkins World.

== 

After DevOps World - Jenkins World there was a 2-day Jenkins hackfest, 
sponsored by link:https://cloudbees.com[CloudBees].
Jenkins Community booth crew members and a number of speakers were invited to this event.
I was leading the event from the content site,
link:TODO[Alyssa Tong] and link:TODO[Liam Newman] provided all the logistics for the event.

Below there is a group photo of participants on the second day of the hackathon.
You can find more photos from events link:TODO[here]. 

There were 3 major topics of the event

* Java 11 support in Jenkins
* Jenkins Configuration-as-Code
* Jenkins infrastructure

=== Java 11 support

It was a major topic on our plate over last months.
In June we got a great progress during the link:TODO[Jenkins and Java 10+ hackfest],
and we wanted to get some progress towards support of Java 11 which was released few days after on September 25.
This time link:TODO[Mark Waite] was driving the effort.

After the hackathon we have presented the Java 11 support status at the link:/sigs/platform[Platform SIG meeting] and discussed the next steps
(link:TODO[meeting notes], link:TODO[video]).
Generally we are getting close to make Java 11 preview support available in common weekly releases according to the jep:211[] plan.
All mandatory Jenkins patches have been been already upstreamed to the master branch,
but we also need to enable CI flows on the master branch before it becomes fully available.
I plan to make a separate blogpost about it in November.

=== Jenkins Configuration as Code

There was a team working on the plugin:TODO[Configuration-as-Code plugin].
Ewelina TODO, Nicolas de Loof, Ulli Hafner, Martin d'Anjou  and Baptiste Mathus focused on this area and did the following:

TODO: image

=== Jenkins Infrastructure

Last but not least, Jenkins Infrastructure.
It was our first time when we had such topic at Jenkins hackathons.
Olivier Vernin, Michael TODO, James Albert, and Pham Vu Tuan worked together in order to improve the project infrastructure.

Summary:



TODO: image

=== Other topics

There were some other activities happening during the hackathon:

* 5 training and demo sessions done by participants: Jenkins Infrastructure, Intro to JCasC development, Warnings Plugin 5.0, etc.
* Together with Daniel Beck we ran a 
* Sync-ups on projects: Google Summer of Code 2019, link:TODO
* TODO: Cloud Native Jenkins
* Mario Kart competitions. We do community bonding, not only the code!

I would like to personally thank CloudBees, Alyssa Tong and Liam Newman for making this event happen.
We did a great progress during the event w.r.t. various topics, and it helps to push Jenkins forward.

== Incoming hackathons

Want to participate in such Jenkins hackathons? There are more happening in October!

As you probably know, there is ongoing Hacktoberfest event.
Jenkins project participates in it, and everybody is welcome to contribute to Jenkins as a part of this event, see link:TODO[this blogpost] for more information.
But Hacktoberfest is not the only event happening in the Jenkins commmunity, there is a number of incoming on-site events:

* Oct 19 - Copenhagen, Denmark - Jenkins Configuration as Code hackathon at link:TODO[Day of Jenkins [as code]]
** Registration: all conference participants can attend
* Oct 22 - Nice, France - Hackathon at DevOps World - Jenkins World Nice for those who arrives early and participated in the Jenkins Contributor Summit
** Registration: contact Oleg Nenashev in the link:TODO[jenkinsci/community Gitter room]
* Oct 30 - Neuchatel, Switzerland - Hacktoberfeest: Jenkins & Friends event (Swiss Jenkins Area meetup)
** Registration: RSVP to the meetup link:TODO[here]
* TBA - Beijing, China - Hacktoberfest

All contributions during these events qualify as Hacktoberfest ones, of course :)
More events may be annunced later, e.g. we traditionally do a hackfest in Brussels after FOSDEM.
Follow our developer mailing lists and social media to receive announcements.

