base_url: https://jenkins.io/
local_tz: UTC
base_title: Jenkins
google_analytics:
  anonymizeIp: true
  account: UA-4216293-5
haml:
  :ugly: true
  :escape_html: false
asciidoctor:
  :safe: unsafe
  :base_dir: null
  :attributes:
    # " If an attribute value that is passed to the API ends with an @ symbol,
    # it makes that assignment have a lower precedence than an assignment in
    # the document."
    # <http://asciidoctor.org/docs/user-manual/#configuring-attributes-for-awestruct>
    imagesdir: /images@
    compat-mode: '@'
    attribute-missing: warn
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    source-highlighter: coderay
    coderay-css: style
    prewrap: null
    fragment: ''
    notitle: ''
profiles:
  production:
    base_url: https://jenkins.io/
  development:
    # Don't log to GA while working on the site
    google_analytics:
      account: UA-000000-0
    base_url: http://localhost:4242/
  hrmpw:
    base_url: https://hrmpw.github.io/jenkins.io/
    deploy:
      host: github_pages
      branch: gh-pages
  rtyler:
    base_url: https://rtyler.github.io/jenkins.io/
    deploy:
      host: github_pages
      branch: gh-pages
