base_url: https://www.jenkins.io/
local_tz: UTC
base_title: Jenkins
haml:
  :escape_html: false
asciidoctor:
  :safe: unsafe
  :base_dir: null
  :attributes:
    # " If an attribute value that is passed to the API ends with an @ symbol,
    # it makes that assignment have a lower precedence than an assignment in
    # the document."
    # <https://asciidoctor.org/docs/user-manual/#configuring-attributes-for-awestruct>
    imagesdir: /images@
    attribute-missing: warn
    relfileprefix: '../'
    outfilesuffix: '/'
    idprefix: ''
    idseparator: '-'
    icons: font
    sectanchors: ''
    linkattrs: ''
    source-highlighter: rouge
    prewrap: null
    fragment: ''
    notitle: ''
profiles:
  production:
    base_url: https://www.jenkins.io/
  user-site:
    google_analytics:
      account: UA-000000-0
  development:
    partial_debug: true
    base_url: http://localhost:4242/
