---
title: Extensibility
layout: developerchapter
summary: About Jenkins' internal extension functionality, modules, and plugins
wip: true
references:
- url: https://wiki.jenkins.io/display/JENKINS/Dependency+Injection
  title: Dependency Injection in Jenkins
- url: https://wiki.jenkins.io/display/JENKINS/Participating+to+the+initialization
  title: Participating to the initialization
- url: https://wiki.jenkins.io/display/JENKINS/Action+and+its+family+of+subtypes
  title: Action and its family of subtypes
- url: /doc/developer/extensions
  title: Generated list of extension points
- url: https://wiki.jenkins.io/display/JENKINS/AnnotationExtension
  title: "On @Extension"
- url: https://wiki.jenkins.io/display/JENKINS/Plugin+Cookbook
  title: List of commonly used extension points
- url: https://wiki.jenkins.io/display/JENKINS/Defining+a+new+extension+point
  title: Defining a new extension point
- url: https://wiki.jenkins.io/display/JENKINS/My+class+is+missing+descriptor
  title: My class is missing descriptor
- url: https://wiki.jenkins.io/display/JENKINS/Extension+Point+for+Project+Views+Navigation
  title: Extension Point for Project Views Navigation # TODO make into guide or remove as obsolete with BO
- url: https://github.com/jenkinsci/sample-extensions
  title: Sample extension implementations
---

Jenkins is designed with extensibility in mind, both internally (core) and with plugins.
Extensibility in Jenkins is accomplished by combining the concepts discussed below.

== Extension annotation

link:https://javadoc.jenkins.io/hudson/Extension.html[Extension] is an annotation that allows Jenkins to discover classes, instantiate them, and register them in global lists of implementations of their supertypes and interfaces.
This works for implementations both directly in core, and contributed by plugins, so that plugins can provide implementations of extension points defined in core (or other plugins).
Whenever Jenkins needs to provide a list, e.g. of security realm implementations (LDAP, Jenkins user database, etc.) it can query for all subtypes of `SecurityRealm` that are annotated with `@Extension`.
// link:TODO[Learn more about `@Extension`].

== Descriptors and Describables

`jenkinsdoc:Descriptor[]` and `jenkinsdoc:Describable[]` (or subtypes thereof) are used whenever multiple instances of a certain extension are needed, for example build steps.
The `Descriptor` can be used to store their global configuration, and as a factory, while the `Describable` is the specific instance with its independent, instance-specific configuration.
This is similar to class/object in object-oriented programming.
// link:TODO[Learn more about `Descriptor` and `Describable`].

== Actionable and Actions

`jenkinsdoc:Actionable[]` is an abstract class allowing subtypes to be extensible using `jenkinsdoc:Action[]` implementations.
`jenkinsdoc:Action[]` implementations can be used to store arbitrary data with a model object, or contribute additions to its presentation.
The exact details vary depending on the subtype, but typically, `jenkinsdoc:Actionable[]` objects will show actions in the sidepanel, and route requests to the action's `getUrlName()` to the action, allowing it to contribute pages to `jenkinsdoc:Actionable[]` objects.
// link:TODO[Learn more about `Action` and `Actionable`].
