---
layout: post
title: "Pipeline and Blue Ocean Demos from Jenkins World"
tags:
- jam
- jenkinsonlinemeetup
- jenkinsworld
- events
author: rtyler
---

At Jenkins World last month, we continued the tradition of "lunch-time demos"
in the Jenkins project's booth which we started in 2016.  We invited a number
of Jenkins contributors to present brief 10-15 minute demos on something they
were working on, or considered themselves experts in. Continuing the
post-Jenkins World tradition, we also just hosted a "Jenkins Online Meetup"
featuring a selection of those lunch-time demos.

++++
<center>
<iframe width="853" height="480" src="https://www.youtube-nocookie.com/embed/jBGFjFc6Jf8?list=PLN7ajX_VdyaOfwJ-BMZo_JNTIMCMNxlbN" frameborder="0" allowfullscreen></iframe>
</center>
++++

I would like to thank link:https://github.com/alyssat[Alyssa Tong] for organizing this online meetup, link:https://github.com/bitwiseman[Liam Newman] for acting as the host, and our speakers:

* link:https://github.com/oleg-nenashev[Oleg Nenashev]
* link:https://github.com/michaelhuettermann[Michael Hüttermann]
* link:https://github.com/scherler[Thorsten Scherler]
* link:https://github.com/stephendonner[Stephen Donner]
* link:https://github.com/markewaite[Mark Waite]
* link:https://github.com/kzantow[Keith Zantow]


Below are some links from the sample projects demonstrated and the direct links
to each session.

=== Developing Pipeline Libraries Locally

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=10s[Video link]

[quote]
____
If you have ever tried developing Pipeline Libraries, you may have noticed how
long it takes to deploy a new version to server to discover just another syntax
error. I will show how to edit and test Pipeline libraries locally before
committing to the repository (with Configuration-as-Code and Docker).
____


* link:https://speakerdeck.com/onenashev/jenkins-world-2017-developing-pipeline-libraries-locally[Slides]
* link:https://github.com/oleg-nenashev/demo-jenkins-config-as-code[Source Code]
* link:https://hub.docker.com/r/onenashev/demo-jenkins-config-as-code/[Demo container]


=== Delivery Pipelines with Jenkins

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=1447s[Video link]

[quote]
____
Showing off how to set up holistic Delivery Pipelines with the DevOps enabler tool Jenkins.
____

* link:https://github.com/michaelhuettermann/sandbox/tree/master/all[Demo application]


=== Pimp my Blue Ocean

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=3018s[Video link]

[quote]
____
How to customize Blue Ocean, where I create a custom plugin and extending Blue
Ocean with custom theme and custom components.
____

* link:https://github.com/scherler/jw17boseed[Presentation and demo code]

=== Deliver Blue Ocean Components at the Speed of Light

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=3810s[Video link]

[quote]
____
Using storybook.js.org for Blue Ocean frontend to speed up the delivery process
- validate with PM and designer the UX. Showing how quickly you develop your
components.
____

* link:https://github.com/scherler/jw17boseed[Presentation and demo code]


=== Mozilla's Declarative + Shared Libraries Setup

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=4878s[Video link]


[quote]
____
How Mozilla is using Declarative Pipelines and shared libraries together.
____

* link:https://docs.google.com/document/d/1sXW6ghoXvoN8_XU_5PTFYRQrXjpCJCq-t1Ajrc3-Oj4/edit[Google Doc with links]
* link:https://github.com/mozilla/fxtest-jenkins-pipeline[Shared Library source code]
* link:http://firefox-test-engineering.readthedocs.io/en/latest/[Documentation for the shared library]


See also the `#fx-test` IRC channel on `irc.mozilla.org`


=== Git Tips and Tricks

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=6425s[Video link]

[quote]
____
Latest capabilities in the git plugin, like large file support, reference
repositories and some reminders of existing tips that can reduce server load,
decrease job time, and decrease disc use.
____


=== Visual Pipeline Creation in Blue Ocean

link:https://www.youtube.com/watch?v=jBGFjFc6Jf8&t=7390s[Video link]

[quote]
____
We will show how to use Blue Ocean to build a real-world continuous delivery
pipeline using the visual pipeline editor. We will coordinate multiple
components of a web application across test and production environments,
simulating a modern development and deployment workflow.
____

