---
layout: gsocprojectidea
title: "Retool Jenkins.io Contributor Spotlight website"
goal: "Migrate and redesign the Jenkins.io Contributor Spotlight website using Vite.js and React.js to enhance user experience and modernize the tech stack."
category: UI/UX
year: 2026
status: draft
sig: docs
skills:
- UI/UX
- JavaScript/TypeScript
- Vite.js and React.js
- Documentation
- Material UI
mentors:
- "krisstern"
- "berviantoleo"
links:
  meetings: /projects/gsoc/#office-hours
  gitter: "jenkinsci_gsoc-sig:gitter.im"
---

=== Background

The current jenkins.io "Contributor Spotlight" feature at link:https://contributors.jenkins.io/[] is in need of a retool to keep it looking sharp and relevant due to its using Gatsby.js as the current framework, which is no longer being actively maintained.
The project at link:https://contributors.jenkins.io/[]
This project is also in need of modernization tech-stack wise, as we will need to migrate from Gatsby.js to Vite.js and React.js as well as upgrade the versions of most of the dependencies re-used.


=== Skills to Study and Improve

* UI/UX
* JavaScript/TypeScript
* Vite.js and React.js
* Documentation
* Material UI


=== Project Size

175 hours


=== Project Difficulty Level

Beginner to Intermediate


=== Expected Outcomes

* Migrate the current Gatsby.js based Contributor Spotlight website to Vite.js and React.js
* Modernize the tech stack including upgrading React and other dependencies to their latest versions
* Redesign the UI/UX of the Contributor Spotlight website including but not limited to:
** The landing page
** The spotlight profile page
* Improve accessibility and responsiveness of the website
* Optimize performance and loading times of the website
* Document the development and migration process for future reference
* Ensure seamless integration with the existing Jenkins.io ecosystem
* Engage with the Jenkins community to gather feedback and iterate on the design and functionality of the website
* Deliver a fully functional and visually appealing Contributor Spotlight website that enhances the visibility of Jenkins contributors and their stories
* Contribute to the Jenkins documentation by providing guides on how to maintain and update the new Contributor Spotlight website
* Collaborate with the Jenkins documentation team to ensure consistency in design and user experience across Jenkins.io
* Participate in community discussions and share insights gained during the project to foster a collaborative learning environment within the Jenkins community


=== Quickstart

To get started:

1. **Familiarize Yourself with Contributor Spotlight Development:** Review the link:https://github.com/jenkins-infra/contributor-spotlight/blob/main/README.adoc/[Contributor Spotlight README.adoc].
2. **Explore Vite.js and React.js:** Investigate the official documentation and tutorials for link:https://vite.dev/[Vite.js] and link:https://react.dev/[React.js] to understand their features and capabilities.
3. **Understand Existing Website Implementations:** Study existing websites built with Vite.js and React.js to gather insights into design and functionality.
4. **Engage with the Jenkins Documentation Team:** Connect with the Jenkins documentation team to understand
    the requirements and expectations for the Contributor Spotlight website.
5. **Set Up Development Environment:** Prepare your local development environment with the necessary tools and dependencies to start working on the project.
6. **Join Community Discussions:** Participate in the Jenkins Gitter channel link:https://matrix.to/#/#jenkinsci_gsoc-sig:gitter.im[gsoc-sig] to stay updated and seek guidance from mentors and community members.
7. **Plan the Migration and Redesign:** Outline a plan for migrating the existing website to Vite.js and React.js, including timelines and milestones for redesigning the UI/UX.


=== Expected Outcomes
Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
