---
layout: gsocprojectidea
title: "Retool jenkins.io website Success Stories"
goal: "To revamp jenkins.io website's Success Stories feature to update both tooling and UI/UX experience with new design"
category: UI/UX
year: 2026
status: draft
sig: infra
skills:
- Website development
- UI/UX design
- Geospatial data visualization
- Gatsby.js and React.js
mentors:
- "krisstern"
- "iamrajiv"
links:
  meetings: /projects/gsoc/#office-hours
  gitter: "jenkinsci_gsoc-sig:gitter.im"
---

=== Background
The current jenkins.io "Success Stories" feature at link:https://stories.jenkins.io/[] is in need of a retool to keep it looking sharp and relevant.
The project at link:https://github.com/jenkins-infra/stories/[] is in need of modernization tech-stack wise, as we will need to upgrade the React version used to the latest possible as well as upgrade the versions of most of the dependencies used.
Besides, we will need to redesign the layout of its UI/UX including but not limited to the landing page, the story page, the map, etc.

Moreover, the workflow for users to submit new stories may need to be redesigned and reimplemented, given the context of the Infra Helpdesk issue at link:https://github.com/jenkins-infra/helpdesk/issues/4392/[].


=== New Features

* Modernize the tech stack including upgrading React and other dependencies to their latest versions
* Redesign the UI/UX of the Success Stories website including but not limited to:
** The landing page
** The story page
** The geospatial map visualization of story locations
* Redesign and reimplement the story submission workflow for users to submit new stories more easily
* Improve accessibility and responsiveness of the website
* Optimize performance and loading times of the website


=== Skills to Study and Improve

* Website development
* UI/UX design
* Geospatial data visualization
* Vite.js and React.js


=== Project Size
175 hours


=== Project Difficulty Level
Beginner


=== Expected Outcomes
Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
