---
layout: gsocprojectidea
title: "Use OpenTelemetry for Jenkins Jobs on ci.jenkins.io"
goal: "To help enhance observability of Jenkins jobs on ci.jenkins.io via the introduction of the use of OpenTelemetry"
category: Tools
year: 2026
status: draft
sig: infra
skills:
- OpenTelemetry
- Observability
- DevOps
mentors:
- "shivaylamba"
- "krisstern"
- "iamrajiv"
links:
  meetings: /projects/gsoc/#office-hours
  gitter: "jenkinsci_gsoc-sig:gitter.im"
---

=== Motivation

Infra team would like to to perform deeper monitoring of specific jobs on ci.jenkins.io and infra.ci.jenkins.io.
The introduction of OpenTelemetry would allow us to do this.
OpenTelemetry is a collection of APIs, SDKs, and tools used to instrument, generate, collect, and export telemetry data (metrics, logs, and traces) to help analyzing software performance and behavior.
With proper design and orchestration of the different moving parts of OpenTelemetry, we hope that the contributor completing the project will be able to gain invaluable experience in implementing observability tooling to the Jenkins project.


=== Project Size
This project is of medium size and is expected to be completed in ~175 hours.


=== Project Difficulty
Intermediate


=== Links

* link:https://opentelemetry.io/[OpenTelemetry official website]
