---
layout: sig
title: "Chinese Localization"
section: sigs
sigId: "chinese-localization"
logo: /images/user.gif
tags:
- Chinese
- localization
- chinese-localization
- chinese-localization-sig
leads:
- name: "Zhao Xiaojie"
  id: "linuxsuren"
  github: "linuxsuren"
participants:
- name: "Zheng Shenyu"
  id: "cizezsy"
  github: "cizezsy"
- name: "Li Lianqiang"
  id: "xuesea"
  github: "xuesea"

links:
  gitter: jenkinsci/chinese-localization-sig
  googlegroup: jenkins-chinese-localization-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  The Chinese Localization group of contributors and collaborators focuses on
  improving Jenkins experience for Chinese users. The scope covered include:
  Jenkins Core and plugins, official website. Welcome aboard!

---

The Chinese Localization group of contributors and collaborators focuses on
  improving Jenkins experience for Chinese users. The scope covered include:
  Jenkins Core and plugins, official website. Welcome aboard!

=== Target Audience

Jenkins users and developers can join us.

=== Jenkins Core

Current status like below:

Simplified Chinese: 66.54% +
Traditional Chinese: 65.69%

=== Jenkins Plugins

We will do localization work for these plugins first:

link:https://github.com/jenkinsci/credentials-plugin[credentials-plugin] +
link:https://github.com/jenkinsci/plain-credentials-plugin[plain-credentials-plugin] +
link:https://github.com/jenkinsci/ssh-credentials-plugin[ssh-credentials-plugin] +
link:https://github.com/jenkinsci/cloudbees-folder-plugin[cloudbees-folder-plugin] +
link:https://github.com/jenkinsci/github-organization-folder-plugin[github-organization-folder-plugin] +
link:https://github.com/jenkinsci/blueocean-plugin[blueocean-plugin] +
link:https://github.com/jenkinsci/pipeline-plugin[pipeline-plugin] +
link:https://github.com/jenkinsci/workflow-cps-plugin[pipeline-plugin] +
link:https://github.com/jenkinsci/workflow-scm-step-plugin[workflow-scm-step-plugin] +
link:https://github.com/jenkinsci/workflow-support-plugin[workflow-support-plugin] +
link:https://github.com/jenkinsci/pipeline-model-definition-plugin[pipeline-model-definition-plugin] +
link:https://github.com/jenkinsci/pipeline-stage-view-plugin[pipeline-stage-view-plugin] +
link:https://github.com/jenkinsci/pipeline-utility-steps-plugin[pipeline-utility-steps-plugin] +
link:https://github.com/jenkinsci/pipeline-input-step-plugin[pipeline-input-step-plugin] +
link:https://github.com/jenkinsci/pipeline-view-plugin[pipeline-view-plugin] +
link:https://github.com/jenkinsci/github-plugin[github-plugin] +
link:https://github.com/jenkinsci/github-branch-source-plugin[github-branch-source-plugin] +
link:https://github.com/jenkinsci/bitbucket-plugin[bitbucket-plugin] + 
link:https://github.com/jenkinsci/bitbucket-branch-source-plugin[bitbucket-branch-source-plugin] +
link:https://github.com/jenkinsci/bitbucket-build-status-notifier-plugin[bitbucket-build-status-notifier-plugin] +
link:https://github.com/jenkinsci/configuration-as-code-plugin[configuration-as-code-plugin] +
link:https://github.com/jenkinsci/kubernetes-plugin[kubernetes-plugin] +
link:https://github.com/jenkinsci/cmakebuilder[cmakebuilder]

=== Meetings

There will be regular SIG meetings scheduled.
Initially the meetings will be conducted once per month,
then they may be adapted according to the activity.

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.

