---
layout: sig
title: "Chinese Localization"
section: sigs
sigId: "chinese-localization"
logo: /images/user.gif
tags:
- Chinese
- localization
- chinese-localization
- chinese-localization-sig
leads:
- name: "Zhao Xiaojie"
  id: "linuxsuren"
  github: "linuxsuren"
participants:
- name: "Zheng Shenyu"
  id: "cizezsy"
  github: "cizezsy"
- name: "Li Lianqiang"
  id: "xuesea"
  github: "xuesea"

links:
  gitter: jenkinsci/chinese-localization-sig
  googlegroup: jenkins-chinese-localization-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  The Chinese Localization group of contributors and collaborators focuses on
  improving Jenkins experience for Chinese users. The scope covered include:
  Jenkins Core and plugins, official website. Welcome aboard!

---

The Chinese Localization group of contributors and collaborators focuses on
  improving Jenkins experience for Chinese users. The scope covered include:
  Jenkins Core and plugins, official website. Welcome aboard!

=== Target Audience

Jenkins users and developers can join us.

=== Jenkins Website

If you are interested in Chinese localization for Jenkins website, please fork link:https://github.com/jenkins-infra/cn.jenkins.io[cn.jenkins.io] and create PR for us.

=== Jenkins Core & Plugins

We will maintain all Simplified Chinese resource files in link:https://github.com/jenkinsci/localization-zh-cn-plugin[here] that include Jenkins core and all plugins.

=== Meetings

There will be regular SIG meetings scheduled.
Initially the meetings will be conducted once per month,
then they may be adapted according to the activity.

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.

