---
layout: gsocprojectidea
title: "Security validator for Jenkins Kubernetes Operator"
goal: "Improve security aspects of installing Jenkins plugins in Kubernetes environment."
category: Plugins
year: 2021
status: discussion
mentors:
- "SylwiaBrant"
- "jakalkhalili"
- "antoniaklja"
skills:
- Go
- Kubernetes
- Bash
links:
  slack: https://github.com/jenkinsci/kubernetes-operator#community
---

=== Project Details

The [Jenkins Operator](https://github.com/jenkinsci/kubernetes-operator) is a Kubernetes Native Operator which manages operations for Jenkins on Kubernetes.
It enables  community to run Jenkins in cloud-native environments like Kubernetes, OpenShift and others. Also, supports most of the public cloud providers (AWS, Azure, GCP) in terms of additional capabilities like backups, observability and cloud security.

* Visit the project page at https://github.com/jenkinsci/kubernetes-operator
* Follow https://jenkinsci.github.io/kubernetes-operator/docs/developer-guide/ and run Jenkins Operator locally

If you are interested in exploring Kubernetes and software-defined operators ecosystem more in-depth, as well as enhance your Go coding skill - this is definitely an interesting opportunity to consider.

=== Problem Statement

Some of the plugins have security warnings which are not properly presented to the end users. This may result in introducing security risk in existing CI/CD infrastructure.

As part of reconciliation process of Jenkins, when plugins are already downloaded but not yet installed add a validation step that will check if chosen plugins contain security issues, using [Kubernetes Admission Controller](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/).
It can be implemented by taking an advantage of built-in security check mechanism in Jenkins Update Centre - the operator should fetch the data directly from Jenkins Download Center (over REST API) about security warnings for corresponding list of plugins to be installed.

Additionally, in case a security warning is detected, user should be able to choose if Jenkins Operator should continue with installation process.

* https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html
* https://sdk.operatorframework.io/docs/building-operators/ansible/reference/webhooks/

=== Newbie Friendly Issues

For information about how to contribute to and what to work on, please use the slack channel. Since the project is in active development, these issues could be closed by the time you are looking at them.

=== Skills to improve/study

* Go
* Kubernetes
* [Operator SDK](https://sdk.operatorframework.io/)
* REST API
* JSON
* Bash
* Jenkins Update Centre