---
layout: gsocprojectidea
title: "Tekton Pipelines DSL for Jenkins with the Tekton Client Plugin"
goal: "Manage Tekton resources via Pipeline Steps / Jenkinsfile"
category: Plugins
year: 2021
status: published
sig: cloud-native
skills:
- Java
- Kubernetes
- Tekton Pipelines
mentors:
- "waveywaves"
- "garethjevans"
links:
  draft: https://docs.google.com/document/d/1_mS0gLgM7oz7PanE0X_SkJ8iUo-BPVCixXMSDO7-VMk/edit#
  design doc: https://docs.google.com/document/d/10n3vgYrjS_M1571OUOYLw4tK2QmxY7kp_wyUT3ke4gY/edit#
---

=== Background
With the movement of traditional software architecture to microservices, there has been a growth in usage of container orchestration infrastructure (Kubernetes) and tooling around it. To adapt to this there have been plugins developed for Jenkins like the kubernetes-plugin which allow this transition to be smooth for the users to keep the same CI/CD platform and migrate their workloads.

Building on Kubernetes would mean that any CI/CD tool which has been Kubernetes-native built with building on Kubernetes as it’s main idea would thrive better than Jenkins itself. Leveraging this, we can use the capability of spinning pipelines on Tekton (Serverless CI/CD for Kubernetes) through Jenkins. Using the same vocabulary and ideas to execute Jobs from Jenkins and having the workloads of the Jobs run by Tekton in Kubernetes, this plugin aims to bridge the gap between Jenkins and Kubernetes.

The Tekton Client Plugin allows users to create/delete resources via Build Steps but there is no way for users to employ their preexisting Jenkinsfile to extend their Jenkins pipeline to leverage Tekton for deploying on Kubernetes.

With no DSL for Tekton on Jenkins there is no way for the users to write scripts which can automate their Tekton lifecycle through Jenkins.

==== Project Details
Create a DSL to interact with Tekton supported by Jenkins. 

=== Reference Links

* link:https://github.com/jenkinsci/tekton-client-plugin[Tekton Client Plugin]
* link:https://github.com/tektoncd/pipeline[Tekton Pipelines controller (Would need to be installed on a Kubernetes Cluster for development)]
* link:https://github.com/fabric8io/kubernetes-client[Kubernetes Client in Java (used in Tekton Client Plugin)]
* link:https://docs.google.com/document/d/10n3vgYrjS_M1571OUOYLw4tK2QmxY7kp_wyUT3ke4gY/edit#[Tekton DSL Design Doc (outlines the scope of work)]


=== Quick-start
To work with Tekton Client Plugin, having a Kubernetes cluster is essential.
A Minikube or KIND kubernetes cluster is sufficient to begin with development on the plugin.

==== Installing kubectl

kubectl is a commandline tool used to interact with Kubernetes clusters. We would be using it here to understand the state of the resources 


==== Installing KIND

Follow this link:https://kind.sigs.k8s.io/docs/user/quick-start/[quick start guide] to install a KIND cluster.

Create a cluster using `kind` cli.
[source,bash]
kind create cluster

Check cluster installation
[source,bash]
kubectl get pods -n kube-system

The output should contain pods which are in the `Running` state.

==== Installing Tekton on your Kubernetes cluster

Follow this link:https://github.com/tektoncd/pipeline/blob/main/docs/install.md#installing-tekton-pipelines-on-kubernetes[github doc] and install the latest release of Tekton Pipeline on your k8s cluster.

Check Tekton installation
[source,bash]
kubectl get pods -n tekton-pipelines

The output should contain pods which are in the `Running` state.

==== Installing Tekton CLI 

The Tekton CLI would be used to better debug and work with Tekton Pipelines.
Use this link:https://github.com/tektoncd/cli#installing-tkn[github doc] to install Tekton CLI.

==== Create a Tekton resource using Jenkins + Tekton Client Plugin

===== Start a Jenkins instance with the plugin installed

Running a Tekton pipeline using the plugin is the best way to get acquainted to the plugin.
Once we have a kubernetes cluster running with Tekton installed we can start the plugin in development mode and create a tekton resources from the Jenkins console.

Clone and run the plugin in development mode.
[source,bash]
git clone https://github.com/jenkinsci/tekton-client-plugin
cd tekton-client-plugin
mvn hpi:run

===== Create a Tekton TaskRun 

Browse to localhost:8080/jenkins which will take you to the Jenkins console.
- Create a new Freestyle Project / Job by navigating to the `New Item` button on the top left corner of the screen. Choose Freestyle Project, give a name and click on `Ok`. This will take us to the job configuration next.
- In the job configuration, scroll down to the `Build` sub header. From the "Add build step` drop down, choose `Tekton : Create Resource (Raw)`. This will add a Build step to the configuration which will help us create a Tekton resource.
- In the Tekton createRaw build step configuration, choose the Input Type as `URL` and add the following url as the input.
[source,bash]
https://raw.githubusercontent.com/tektoncd/pipeline/main/examples/v1beta1/taskruns/task-result.yaml
This would create a TaskRun running a Task in Tekton.

===== Checking the state of TaskRun using the Tekton CLI.

Run the following commands to check the state of the TaskRun and the get the logs for the same respectively.
[source,bash]
tkn taskrun list
tkn taskrun logs -f

===== Checking the state of TaskRun from the Jenkins Console

Go to the Jenkins console for the Job to see the output of the TaskRun from Jenkins.

=== Next Steps

To explore the Tekton Client Plugin further, check out more of the link:https://github.com/jenkinsci/tekton-client-plugin/tree/master/docs[documentation] and the link:https://github.com/jenkinsci/tekton-client-plugin/issues[github issues] to understand current landscape of the plugin and future work.

=== Newbie-friendly issues

* link:https://issues.jenkins.io/issues/?jql=labels%20%3D%20newbie-friendly%20AND%20status%20not%20in%20(Closed%2C%20Done%2C%20Resolved%2C%20%22Fixed%20but%20Unreleased%22)%20AND%20component%20%3D%20tekton-client-plugin%20AND%20project%20%3D%20JENKINS[Open newbie-friendly issues]

=== Skills to improve/study

* Java
* Docker,Kubernetes
* Jenkins
* Tekton Pipelines
