---
layout: gsocprojectidea
title: "Tekton Pipelines DSL for Jenkins with the Tekton Client Plugin"
goal: "Manage Tekton resources via Pipeline Steps / Jenkinsfile"
category: Plugins
year: 2021
status: published
sig: docs
skills:
- Java
- Kubernetes
- Tekton Pipelines
mentors:
- "waveywaves"
- "garethjevans"
links:
  draft: https://docs.google.com/document/d/1_mS0gLgM7oz7PanE0X_SkJ8iUo-BPVCixXMSDO7-VMk/edit#
  design doc: https://docs.google.com/document/d/10n3vgYrjS_M1571OUOYLw4tK2QmxY7kp_wyUT3ke4gY/edit#
---

=== Background
With the movement of traditional software architecture to microservices, there has been a growth in usage of container orchestration infrastructure (Kubernetes) and tooling around it. To adapt to this there have been plugins developed for Jenkins like the kubernetes-plugin which allow this transition to be smooth for the users to keep the same CI/CD platform and migrate their workloads.

Building on Kubernetes would mean that any CI/CD tool which has been Kubernetes-native built with building on Kubernetes as it’s main idea would thrive better than Jenkins itself. Leveraging this, we can use the capability of spinning pipelines on Tekton (Serverless CI/CD for Kubernetes) through Jenkins. Using the same vocabulary and ideas to execute Jobs from Jenkins and having the workloads of the Jobs run by Tekton in Kubernetes, this plugin aims to bridge the gap between Jenkins and Kubernetes.

The Tekton Client Plugin allows users to create/delete resources via Build Steps but there is no way for users to employ their preexisting Jenkinsfile to extend their Jenkins pipeline to leverage Tekton for deploying on Kubernetes.

With no DSL for Tekton on Jenkins there is no way for the users to write scripts which can automate their Tekton lifecycle through Jenkins.

==== Project Details
Leverage the Tekton command-line tool link:https://github.com/tektoncd/cli[tkn] to create a DSL which can be used in a groovy based Jenkinsfile to manage Tekton specific lifecycle.

=== Links

* link:https://github.com/fabric8io/kubernetes-client[Java Kubernetes Client]
* link:https://github.com/tektoncd/pipeline[Tekton Pipelines]
* link:https://github.com/jenkinsci/tekton-client-plugin[Tekton Client Plugin]
* link:https://docs.google.com/document/d/10n3vgYrjS_M1571OUOYLw4tK2QmxY7kp_wyUT3ke4gY/edit#[Tekton DSL Design Doc]


=== Quick-start

The project requires the student to start with plugin development from the [Tekton Client Plugin implemented as a link:https://github.com/jenkinsci/tekton-client-plugin[proof of concept].
Work with potential mentors and plugin maintainers to understand the plugin, identify its strengths and weaknesses, and better understand how to use Tekton from Jenkins.

=== Newbie-friendly issues

* link:https://issues.jenkins.io/issues/?jql=labels%20%3D%20newbie-friendly%20AND%20status%20not%20in%20(Closed%2C%20Done%2C%20Resolved%2C%20%22Fixed%20but%20Unreleased%22)%20AND%20component%20%3D%20tekton-client-plugin%20AND%20project%20%3D%20JENKINS[Open newbie-friendly issues]

=== Skills to improve/study

* Java
* Docker,Kubernetes
* Jenkins
* Tekton Pipelines
