---
layout: documentation
title: Jenkins Documentation
section: doc
---

Jenkins is a self-contained, open source automation server which can be used to
automate all sorts of tasks such as building, testing, and deploying software.
Jenkins can be installed through native system packages, Docker, or even run
standalone by any machine with the Java Runtime Environment installed.

== Guided Tour

This guided tour will use the "standalone" Jenkins distribution which requires
a minimum of Java 7, though Java 8 is recommended. A system with more than
512MB of RAM is also recomended.

. http://mirrors.jenkins.io/war-stable/latest/jenkins.war[Download Jenkins].
. Open up a terminal in the download directory and run `java -jar jenkins.war`
. Browse to `http://localhost:8080` and follow the instructions to complete the installation.
. Many Pipeline examples require an
  https://docs.docker.com/engine/installation[installed Docker]
  on the same computer as Jenkins.

When the installation is complete, start putting Jenkins to work and create a
Pipeline.

Jenkins Pipeline is a suite of plugins which supports implementing and
integrating continuous delivery pipelines into Jenkins. Pipeline provides an
extensible set of tools for modeling simple-to-complex delivery pipelines "as
code".

Typically, a Pipeline is written to a `Jenkinsfile` and
checked into a project's source control repository.

**link:pipeline/getting-started[Continue to "Create your first Pipeline"]**
