---
layout: documentation
title: Jenkins User Documentation
section: doc
---

Welcome to the Jenkins user documentation - for people wanting to _use_
Jenkins's existing functionality and plugin features.

If you want to _extend_ the functionality of Jenkins by developing your own
Jenkins plugins, please refer to the link:developer[Extend Jenkins] (developer
documentation).

== What is Jenkins?

Jenkins is a self-contained, open source automation server which can be used to
automate all sorts of tasks related to building, testing, and deploying software.

Jenkins can be installed through native system packages, Docker, or even run
standalone by any machine with a Java Runtime Environment (JRE) installed.

== About this documentation

This documentation begins with a link:pipeline/tour/getting-started[Guided Tour]
to help you get up and running with Jenkins and introduce you to Jenkins's main
feature, Pipeline.

There are also link:tutorials[introductory tutorials] geared to developers who
want to automate building their project in Jenkins using Pipeline and Blue
Ocean.

If you've never used Jenkins before or have limited Jenkins experience, then the
Guided Tour and introductory tutorials are good places to start.

If you are looking for more detailed information about using Jenkins, please
refer to the link:book/getting-started[User Handbook].
