---
layout: documentation
title: Jenkins User Documentation
section: doc
---

Welcome to the user documentation for Jenkins.

== What is Jenkins?

Jenkins is a self-contained, open source automation server which can be used to
automate all sorts of tasks such as building, testing, and deploying software.

Jenkins can be installed through native system packages, Docker, or even run
standalone by any machine with the Java Runtime Environment (JRE) installed.

== Getting Started with the Guided Tour

This guided tour introduces you to the basics of using Jenkins and its main
feature, Jenkins Pipeline. This tour uses the "standalone" Jenkins distribution,
which runs locally on your own machine.

=== Prerequisites

For this tour, you will require:

* A machine with:
** 256 MB of RAM, although more than 512MB is recommended
** 10 GB of drive space (for Jenkins and your Docker image)
* The following software installed:
** Java 8 (either a JRE or Java Development Kit (JDK) is fine)
** https://www.docker.com/[Docker] (navigate to *Get Docker* at the top of the
   website to access the Docker download that's suitable for your platform)

=== Download and run Jenkins

. http://mirrors.jenkins.io/war-stable/latest/jenkins.war[Download Jenkins].
. Open up a terminal in the download directory.
. Run `java -jar jenkins.war --httpPort=8080`.
. Browse to `http://localhost:8080`.
. Follow the instructions to complete the installation.

When the installation is complete, start putting Jenkins to work and create a
link:book/pipeline[Pipeline].

=== What is a Jenkins Pipeline?

Jenkins Pipeline is a suite of plugins which supports implementing and
integrating continuous delivery pipelines into Jenkins. Pipeline provides an
extensible set of tools for modeling simple-to-complex delivery pipelines "as
code".

A
link:book/pipeline/jenkinsfile[`Jenkinsfile`]
is a text file that contains the definition of a
Jenkins Pipeline and is checked into source control.
footnoteref:[scm, https://en.wikipedia.org/wiki/Source_control_management]
This is the foundation of "Pipeline-as-Code"; treating the continuous delivery
pipeline a part of the application to be version and reviewed like any other code.
Creating a `Jenkinsfile` provides a number of immediate benefits:

* Automatically create Pipelines for all Branches and Pull Requests
* Code review/iteration on the Pipeline
* Audit trail for the Pipeline
* Single source of truth
  footnote:[https://en.wikipedia.org/wiki/Single_Source_of_Truth]
  for the Pipeline, which can be viewed and edited by multiple members of the project.

While the syntax for defining a Pipeline, either in the web UI or with a
`Jenkinsfile`, is the same, it's generally considered best practice to define
the Pipeline in a `Jenkinsfile` and check that in to source control.

**link:pipeline/tour/hello-world[Continue to "Create your first Pipeline"]**
