---
layout: documentation
title: Jenkins User Documentation
section: doc
---

Welcome to the user documentation for Jenkins. This documentation is for people
who wish to _use_ Jenkins functionality.

If you wish to _extend_ the functionality of Jenkins by developing plugins,
please refer to the link:developer[Extend Jenkins] (developer documentation).

== What is Jenkins?

Jenkins is a self-contained, open source automation server which can be used to
automate all sorts of tasks related to building, testing, and deploying software.

Jenkins can be installed through native system packages, Docker, or even run
standalone by any machine with a Java Runtime Environment (JRE) installed.

== About this documentation

This documentation begins with a link:pipeline/tour/getting-started[Guided Tour]
to help you get up and running with Jenkins and introduce you to Jenkins' main
feature, Pipelines. If you've never used Jenkins before, this is great place to
start.

If you are looking for more detailed information about using Jenkins, please
refer to the link:book/getting-started[User Handbook].
