==== Remoting update

https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#320[Remoting changelog],
https://issues.jenkins.io/browse/JENKINS-50237[JENKINS-50237]

The Remoting library has been updated to improve diagnosability and reliability.
One of those changes ensures that exceptions are always properly serialized over the channel, even if some exception fields are blocked by link:/redirect/class-filter/[JEP-200 class filters].

In order to get this fix applied, Remoting needs to be updated to version 3.13 or newer on the agent side.
Without this upgrade, some remote operations on agents may fail if the call results in an exception, even if a the exception could be handled.

plugin:ssh-slaves[SSH Slaves] based agents will always use the latest `agent.jar`, but other agent types may need to have their `agent.jar` updated manually.
The following agent types should be updated:

* Java Web Start agents with `agent.jar` / `slave.jar` JARs on the disk need to update those to version 3.19 or above.
* plugin:swarm[Swarm Plugin] Client needs to be updated to version 3.11 or above.
* Agent Docker Packages offered by the Jenkins project (https://hub.docker.com/r/jenkins/agent/[jenkins/agent] and https://hub.docker.com/r/jenkins/inbound-agent/[jenkins/inbound-agent]) need to be updated to version 3.19-1 or above.


==== Job/Build permission no longer implies Job/Cancel permission

link:https://issues.jenkins.io/browse/JENKINS-14713[JENKINS-14713]

To allow greater flexibility in configuring permissions, the 'implies' relationship between Job/Build and Job/Cancel has been removed.
Users now need to be granted the Job/Cancel permission explicitly to cancel builds, even those they started themselves.

==== UI for renaming jobs has been changed

link:https://issues.jenkins.io/browse/JENKINS-22936[JENKINS-22936]

It is no longer possible to rename jobs from their configuration page.
Jobs now have a link in the side panel titled "Rename" that links to a page specifically dedicated to renaming jobs.

==== New administrative monitor warns about undefined root URL

link:https://issues.jenkins.io/browse/JENKINS-31661[JENKINS-31661]

If you have not defined a root URL, various Jenkins features will not work correctly.
To ensure to the extent possible that a root URL is configured, an administative monitor will show when it's not.

==== JDK Tool Plugin detached from Jenkins core

link:https://issues.jenkins.io/browse/JENKINS-22367[JENKINS-22367]

The automatic installer for JDKs has been moved into a plugin to have a lifecycle independent from Jenkins core.

==== UI option for custom builds and workspace directories on the master has been removed

link:https://issues.jenkins.io/browse/JENKINS-50164[JENKINS-50164]

Build Record Root Directory and Workspace Root Directory can no longer be configured through the UI as these options were generally unsafe to use while Jenkins was running.
Instead, these locations can now be customized using system properties on startup.
Existing changes to these options will be retained unless and until overridden at startup.

==== Pipeline improvements

link:https://issues.jenkins.io/browse/JENKINS-46652[JENKINS-46652]
link:https://issues.jenkins.io/browse/JENKINS-47142[JENKINS-47142]
link:https://issues.jenkins.io/browse/JENKINS-26143[JENKINS-26143]

Various changes to Jenkins core make it easier to use Pipelines:

* Choice parameters now allow the use of a list of options instead of a string of options separated by line breaks.
* `archiveArtifacts` now throws a normal exception when no matching files could be found.
* Jenkins no longer prevents the execution of pipelines running as a user without Job/Build permission on the master node with Authorize Project Plugin.
