==== New login and user signup pages

link:/blog/2018/06/27/new-login-page/[Announcement blog post],
https://issue-redirect.jenkins.io/issue/50447[JENKINS-50447]

The login and user signup pages have been redesigned.
As a side effect, existing `PageDecorator` implementations will not be used on the redesigned pages.

See the link:/blog/2018/06/27/new-login-page/[announcement blog post] for further information.


==== New API token system

link:/blog/2018/07/02/new-api-token-system/[Announcement blog post],
https://issue-redirect.jenkins.io/issue/32442[JENKINS-32442],
https://issue-redirect.jenkins.io/issue/32776[JENKINS-32776]

The per-user API tokens that allow access to the HTTP remote API have been redesigned:
API tokens can now be created and revoked, and are stored in a non-recoverable format.

See the link:/blog/2018/07/02/new-api-token-system/[announcement blog post] for further information.


==== Disabled deprecated agent protocols

https://issue-redirect.jenkins.io/issue/48480[JENKINS-48480]

The deprecated Jenkins CLI Protocol versions 1 and 2, and Java Web Start Agent Protocol versions 1, 2, and 3 have been disabled.

If you still use these protocols (e.g. remoting-based CLI, or old `slave.jar` files on agents), you need to re-enable these protocols after upgrade, or upgrade the clients.
The same recommendations as in link:/doc/upgrade-guide/2.121/#remoting-update[the 2.121.x upgrade guide for remoting changes] apply here.

==== Require GNU C Library 2.7 or above on Unix systems

jira:JENKINS-52771[]

Starting from this version, Jenkins requires link:https://www.gnu.org/software/libc/[GNU C Library] version 2.7 or above.
It makes some Linux distributions unsupported, in particular RHEL 5 and CentOS 5.
See jira:JENKINS-53924[] and jira:JENKINS-53832[] for more info.
