==== Security hardening to prevent XSS vulnerabilities

A security hardening to prevent cross-site scripting vulnerabilities from being exploitable was applied to views in Jenkins.
This can in rare cases result in views having some content escaped twice (typically resulting in visible HTML entities).

We consider these effects to be a bug in plugins that either opt out of the default test suite, or use outdated toolchains.
We track known affected plugins and their status on https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+2018-10-10+Stapler+security+hardening[the Jenkins wiki].

As a temporary workaround, this hardening can be disabled by setting the system property `org.kohsuke.stapler.jelly.CustomJellyContext.escapeByDefault` to `false`.

==== Warning logged on first startup after upgrade

https://issue-redirect.jenkins.io/issue/53998[JENKINS-53998]

When starting Jenkins 2.138.2 for the first time, a warning like the following might be logged if the plugin:jobConfigHistory[Job Config History Plugin] is installed in a version older than 2.19.

----
Oct 10, 2018 2:27:17 PM hudson.ExtensionFinder$GuiceFinder$FaultTolerantScope$1 error
WARNING: Failed to instantiate Key[type=jenkins.telemetry.Correlator, annotation=[none]]; skipping this component
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Tried proxying jenkins.telemetry.Correlator to support a circular dependency, but it is not an interface.
----

This does not appear to result in further problems.
Subsequent restarts of Jenkins will no longer log this warning.

==== Security hardening impacts use of GitHub OAuth Plugin

https://issue-redirect.jenkins.io/issue/54031[JENKINS-54031]

A security hardening in 2.138.2 and 2.146 can result in problems accessing jobs with plugin:github-oauth[GitHub OAuth Plugin] due to a bug in the plugin.

As a workaround, it is possible to temporarily disable part of the security hardening by setting the link:/doc/book/managing/system-properties/[Java system properties] `hudson.model.AbstractItem.skipPermissionCheck` and `hudson.model.Run.skipPermissionCheck` to `true`.

IMPORTANT: Please see the link:/security/advisory/2018-12-05/#SECURITY-595[description of SECURITY-595 in the 2018-12-05 security advisory] for important information about this workaround.
