[java11]
==== Changes related to Java 11 compatibility

// TODO jaxb Plugin explanation for Java 8



Some plugins use JAXB libraries provided by the JDK. However, the `java.xml.bind` and `javax.activation` modules are no longer included in OpenJDK 11, and plugins might fail if no replacement is offered.

To fix this problem, we’ve bundled those libraries into a new detached plugin: plugin:jaxb[JAXB plugin].
When Jenkins 2.164 or newer is running on Java 11, this plugin is automatically installed.
However, if you manage your plugins outside Jenkins (for example, if you use `plugins.txt` in your Docker images), you might need to explicitly install the plugin.

Many further changes related to Java 11 have been implemented since 2.150.3.
See the changelog for a list, and the following documentation for an overview of Java 11 compatibility:

* link:/doc/administration/requirements/upgrade-java-guidelines/[Upgrading Jenkins Java version from 8 to 11]
* link:https://jenkins.io/doc/administration/requirements/jenkins-on-java-11/[Running Jenkins on Java 11]
* https://wiki.jenkins.io/display/JENKINS/Known+Java+11+Compatibility+issues[Known Java 11 Compatibility issues]
* https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines[Java 11 Developer Guidelines]
