==== Remoting-mode of CLI removed

link:/blog/2019/02/17/remoting-cli-removed/[Announcement blog post]

Support for the remoting mode of the CLI has been removed (previously available using the `-remoting` argument to `java -jar jenkins-cli.jar`).
This includes related features and commands only available in that mode.
Most CLI features are still available via HTTP transport, or the builtin SSH server.

==== Symbol `nonStoredPasswordParam` removed

https://issue-redirect.jenkins.io/issue/56776[JENKINS-56776]

The password parameter type offered an alternative symbol `nonStoredPasswordParam` for use in pipelines and scripts.
It implied that the password value would not be stored.
As this is false -- it is stored encrypted -- the symbol has been removed.
Pipelines and other scripts using the symbol need to be changed to use the symbol `password` instead.

==== Mailer plugin resources removed

https://issue-redirect.jenkins.io/issue/55292[JENKINS-55292]

plugin:mailer[Mailer Plugin] used to be a feature of Jenkins core that was split off into a plugin.
Some resources were accidentally left in core.
These have now been removed.

It is recommended to update to Mailer Plugin 1.23, the first plugin release to contain the resources, or newer, to prevent errors.

==== New security warning related to build authorization

https://issue-redirect.jenkins.io/issue/24513[JENKINS-24513]

Builds in Jenkins run as the internal SYSTEM pseudo-user with full privileges by default.
This means that one build can e.g. trigger builds of any other project, unless the specific feature implementation performs some additional permission checks.

Jenkins now informs administrators if they have a potentially insecure configuration of Jenkins due to lack of installed or configured build authenticators.
Additionally, if builds run as the internal SYSTEM pseudo-user, build logs will include a message with that information.

==== Built-in support for CCtray (cc.xml) files removed

https://issue-redirect.jenkins.io/issue/40750[JENKINS-40750]

Built-in support for offering build information in the CCtray (cc.xml) format has been removed.
To restore this feature, install the plugin:cctray-xml[CCtray XML Plugin].

==== Chinese translations removed

All Chinese translations not required for the setup wizard have been migrated into the plugin:localization-zh-cn[Localization: Chinese (Simplified) plugin].
