[#SECURITY-626]
==== Improved CSRF protection

link:/security/advisory/2019-07-17/#SECURITY-626[SECURITY-626]

https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF] tokens (crumbs) are now only valid for the web session they were created in to limit the impact of attackers obtaining them.
Scripts that obtain a crumb using the `/crumbIssuer/api` URL will now fail to perform actions protected from CSRF unless the scripts retain the web session ID in subsequent requests. 

NOTE: Scripts could instead use an API token, which has not required a CSRF token (crumb) since link:/changelog/#v2.96[Jenkins 2.96].

To disable this improvement you can set the system property `hudson.security.csrf.DefaultCrumbIssuer.EXCLUDE_SESSION_ID` to `true`.
Alternatively, you can install the plugin:strict-crumb-issuer[Strict Crumb Issuer Plugin] which provides more options to customize the crumb validation.
It allows excluding the web session ID from the validation criteria, and instead e.g. replacing it with time-based expiration for similar (or even better) protection from CSRF.


[#SECURITY-534]
==== New restrictions for view dispatching

link:/security/advisory/2019-07-17/#SECURITY-534[SECURITY-534]

A design flaw in the Stapler web framework used by Jenkins allowed attackers in some cases to bypass permission checks and access view fragments disclosing sensitive information.
link:/security/advisory/2019-07-17/#SECURITY-534[For further details, see the security advisory].

As a side effect of this security fix, some views may no longer be accessible.
This typically results in `HTTP 404 Not Found` responses.
Whenever this happens, Jenkins write a message similar to the following to the Jenkins system log:

----
WARNING: New Stapler dispatch rules result in the URL "/example" no longer being allowed. If you consider it safe to use, add the following to the whitelist: "jenkins.model.Jenkins example". Learn more: https://jenkins.io/redirect/stapler-facet-restrictions
----

If this happens due to legitimate use of the Jenkins UI, the affected view can be added to the list of approved views.
By default, a file named `stapler-views-whitelist.txt` in the `JENKINS_HOME` directory can be modified to add these signatures.
The location of this file can be overridden by the system property `jenkins.security.stapler.StaplerDispatchValidator.whitelist`.
Each line of this file contains a model class name followed by a space-delimited list of view names to allow.
Lines beginning with `#` are ignored.
For example:

----
# allow dispatch to 'example' from the 'jenkins.model.Jenkins' class
jenkins.model.Jenkins example

# allow some other views
com.example.FooBar foo bar
----

When making changes to this whitelist, Jenkins will not automatically detect changes to the file.
To make Jenkins reload its cache of these whitelist entries, execute the following command in the Jenkins script console as an administrator:

----
jenkins.security.stapler.StaplerDispatchValidator.getInstance(Jenkins.instance.servletContext).cache.load()
----

Alternatively, individual line entries can be directly added in memory to the cache.
These will not be persisted on disk, so they're only active until Jenkins is restarted.
This can be useful for iteratively enabling views without directly modifying the filesystem.
An administrator can add these entries using the following Jenkins script console command:

----
jenkins.security.stapler.StaplerDispatchValidator.getInstance(Jenkins.instance.servletContext).cache.loadWhitelist([
    'jenkins.model.Example example',
    'com.example.FooBar foo bar'
])
----

These entries must be manually saved into the whitelist file in order to persist between restarts of Jenkins.

We track known affected plugins and their status in link:https://wiki.jenkins.io/display/JENKINS/Plugins+affected+by+the+SECURITY-534+fix[the Jenkins wiki].
