==== Plugin dependency resolution fix

https://issue-redirect.jenkins.io/issue/21486[JENKINS-21486]

Previous versions allowed Jenkins to run with invalid plugin configurations. For example, plugins depending on other plugins were loaded even if those dependencies were outdated, or disabled. This could result in difficult to debug errors at run time.

Now, Jenkins will refuse to load plugins with unsatisfied dependencies. Diagnostic messages explaining this will be written to the Jenkins log during startup, and we strongly recommend monitoring that after upgrading.

==== Form autocompletion disabled

https://issue-redirect.jenkins.io/issue/18435[JENKINS-18435]

A long-standing problem with JavaScript-heavy configuration forms was that submitting a form, then using the web browser Back button to return to the form resulted in the wrong form contents. Submitting the form again would then result in unexpectedly broken configuration.

To work around this problem, we disabled autocompletion for almost all form fields.

==== Agent protocol selection in security configuration

https://issue-redirect.jenkins.io/issue/37032[JENKINS-37032]

The Configure Global Security form now includes options to enable/disable specific agent protocol versions, along with short descriptions of each protocol. There is no general guidance on when to customize the status of specific protocols, but it may be needed in the future.

==== Hiding the Java Web Start launcher

https://issue-redirect.jenkins.io/issue/36996[JENKINS-36996]

By default, new Jenkins 2 instances will have the JNLP agent port disabled. As this is a requirement for the JNLP Web Start launch method for build agents to work, this form option will now be hidden if the port is disabled. To make it show up, just enable the JNLP agent port in the Global Security Configuration.
