==== JNLP agent protocol options weren't correctly persisted

https://issue-redirect.jenkins.io/issue/39465[JENKINS-39465]

The JNLP agent protocol configuration could not be loaded from disk after a Jenkins restart.

If you customized these settings since 2.19.1, review that they are configured as expected.

==== Honor `jenkins.model.Jenkins.slaveAgentPort` again

https://issue-redirect.jenkins.io/issue/38187[JENKINS-38187]

A regression in Jenkins 2.0 caused Jenkins to ignore the System property `jenkins.model.Jenkins.slaveAgentPort`.

The previous behavior has been restored, and a new System property `jenkins.model.Jenkins.slaveAgentPort` added that, if set, will enforce the JNLP agent port on every Jenkins startup, and will not allow the value to be changed through the UI.

It can still be changed via Groovy scripting for troubleshooting purposes, but any change will be reverted on startup.

==== Text boxes on configuration screens will no longer stretch to accommodate long lines

https://issue-redirect.jenkins.io/issue/27367[JENKINS-27367]

The layout of job configuration screens will no longer break if users don't insert extra line breaks to break long lines. Instead, the text box will allow horizontal scrolling.

==== Don't spawn numerous threads on the agent build history page

https://issue-redirect.jenkins.io/issue/23244[JENKINS-23244]

The build history for specific agents has long caused numerous potentially long-running threads to spawn. This has been fixed.

==== Memory leak on dashboard fixed

https://issue-redirect.jenkins.io/issue/10912[JENKINS-10912]

A memory leak on the dashboard (view pages) was fixed, so that browser memory use will no longer grow unbounded.
