==== Removal of Inbound TCP Agent Protocol/3
http://jenkins.io/security/advisory/2020-01-29/#SECURITY-1682[SECURITY-1682]

It is no longer possible to enable Inbound TCP Agent Protocol/3 through the UI.
Instances upgrading from previous releases of Jenkins, which had this protocol enabled, will have it disabled.

The system property `jenkins.slaves.JnlpSlaveAgentProtocol3.ALLOW_UNSAFE` can be set to `true` to allow enabling this protocol again if necessary.
We strongly discourage doing this.

NOTE: This only applies to Jenkins 2.204.2 and subsequent releases in that LTS line; the protocol has been removed entirely from Jenkins 2.214 and newer.

==== Disabled network auto-discovery services
link:/security/advisory/2020-01-29/#SECURITY-1641[SECURITY-1641]

Jenkins no longer enables DNS multicast and UDP multicast/broadcast by default.

To re-enable these services, set the system property `hudson.DNSMultiCast.disabled` to `false` (for DNS multicast) or the system property `hudson.udp` to `33848`, or another port (for UDP broadcast/multicast).
These are the same system properties that controlled whether these features were enabled in the past, so any instances explicitly enabling these features by setting these system properties will continue to have them enabled.

==== Stapler security hardening

Access to URLs processed by the `Computer` and `Plugin` types (or subtypes) now requires users to have Overall/Read permission.

These new restrictions can be disabled by setting the system properties `hudson.Plugin.skipPermissionCheck` or `hudson.model.Computer.skipPermissionCheck` to `true` if this change causes problems.
