==== Global configuration save and configuration as code plugin

Jenkins 2.199 introduced a
link:https://github.com/jenkinsci/jenkins/pull/4171[check to prevent saving global configuration before loading the configuration has occurred].
Configuration As Code needs to apply global configuration before Jenkins loads jobs (so they can load and correctly reference any global state) and as such until JENKINS-51856 is implemented there exists a race condition where by Jenkins may fail to start when used with this plugin.

If you encounter the race condition Jenkins will fail to start with an exception message similar to the following:

[source,bash]
----
SEVERE	jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
java.lang.IllegalStateException: An attempt to save the global configuration
  was made before it was loaded
----

If you encounter this, you can tell the plugin to delay configuration for an amount of time to give Jenkins time to load the global configuration before the configuration is applied by the plugin.

To enable this set the `io.jenkins.plugins.casc.ConfigurationAsCode.initialDelay` system property to a number of milliseconds to delay the initialisation.
The required value will be dependant on aspects of your system (cpu/disk) and configuration, and how it can be found is mostly a trial and error.
A suggestion would be to start with 5000 (5 Seconds) and then increment by 2000 (2 seconds) until you no longer exhibit the issue and finally add 1000 (1 second) for some extra safety.
For example, to delay the configuration by 9 seconds you would use something like the following command `java -Dio.jenkins.plugins.casc.ConfigurationAsCode.initialDelay=9000 -jar jenkins.war`.
Exactly how and where you specify this option depends on the installation method used to install Jenkins.

==== Remove browser-based metadata download settings

The ability to download update center metadata using the user's browser was removed from Jenkins.
Jenkins will no longer inform administrators about available updates without an internet connection.
We recommend the use of a local mirror of our update sites or a self-hosted update center like link:https://github.com/jenkinsci/juseppe[Juseppe] in such situations.

An administrative monitor has warned users that browser-based metadata download is deprecated.
This release removes the capability and the administrative monitor.

Users maintaining Jenkins with the link:https://plugins.jenkins.io/configuration-as-code[configuration as code plugin] will need to remove the `downloadSettings` entry from the configuration file:

[source,yaml]
----
security:
  downloadSettings:
    useBrowser: false
----

If that section is not removed, Jenkins will fail to start.
When it fails to start, the message in the logfile will look something like this:

[source,bash]
----
SEVERE jenkins.InitReactorRunner$1#onTaskFailed: Failed ConfigurationAsCode.init
io.jenkins.plugins.casc.ConfiguratorException: Invalid configuration elements
  for type class jenkins.model.GlobalConfigurationCategory$Security : downloadSettings.
----

The Jenkins web page may also display a message like this:

[source,bash]
----
java.lang.IllegalStateException: Expected 1 instance of jenkins.security.ResourceDomainConfiguration
  but got 0
----

Remove the `downloadSettings` and `useBrowser` lines from the configuration as code file to resolve those errors.

==== Resource domain support

https://issue-redirect.jenkins.io/issue/41891[JENKINS-41891]

Static resources (HTML pages, workspace files, images, etc.) served from Jenkins are protected by default using a link:https://en.wikipedia.org/wiki/Content_Security_Policy[content security policy].
Many Jenkins plugins need to serve static resources but have not been updated to support content security policy.
Previously, administrators were required to define custom content security policies in order to display those pages correctly.

Administrators may now choose to define a **Resource Root URL** that Jenkins will use to serve static pages without adding content security policy headers.

==== Stop bundling Maven plugin and Subversion plugin with Jenkins

Certain key Jenkins capabilities were initially created inside the Jenkins core.
As Jenkins has developed further, capabilities moved from inside Jenkins core to dedicated Jenkins plugins, like the maven and subversion plugins.
When those plugins were created, the plugins were "bundled" inside the jenkins.war file to retain compatibility for plugins that depended on their functionality to be inside Jenkins core.
The Jenkins project is no longer publishing any plugins that require the "bundled" versions of the maven and subversion plugins.
The Maven and Subversion plugins are no longer bundled with Jenkins.

In very rare cases, this could result in problems when attempting to install plugins compatible with Jenkins before 1.310.
In those cases, the best path forward is usually to modify the plugin that has the problem so that it requires a newer version of Jenkins core.

// Not sure what to say here about link:https://github.com/jenkinsci/jenkins/pull/4245[script-security updated to 1.65].
