==== Changes to CSRF protection

link:/security/advisory/2020-03-25/#SECURITY-1774[SECURITY-1774]

Changes in Jenkins 2.228, 2.204.6, and 2.222.1 affect CSRF protection in multiple ways:

* Responses to `POST` requests that do not set a CSRF crumb/token may in very rare cases change in unexpected ways due to the fix for SECURITY-1774.
  In case of problems with such requests, administrators can disable this security fix by setting the system property `hudson.security.csrf.CrumbFilter.UNPROCESSED_PATHINFO` to `true`.
* As an additional safeguard, semicolon (`;`) characters in the path part of a URL are now banned by default.
  Administrators can disable this protection by setting the system property `jenkins.security.SuspiciousRequestFilter.allowSemicolonsInPath` to `true`.

These features overlap, so both may need to be disabled in case of problems. Doing so is strongly discouraged, as that re-opens the SECURITY-1774 general CSRF vulnerability.

We expect neither of these changes to result in problems. If they do, please https://wiki.jenkins.io/display/JENKINS/How+to+report+an+issue[file a bug] and use the labels `security-1774` and `regression`.
