==== Removed Agent Protocols

https://jenkins.io/security/advisory/2020-01-29/#SECURITY-1659[SECURITY-1659] and Remoting changelogs for https://github.com/jenkinsci/remoting/releases/tag/remoting-4.2[4.2],
https://github.com/jenkinsci/remoting/releases/tag/remoting-4.0.1[4.0.1],
https://github.com/jenkinsci/remoting/releases/tag/remoting-4.0[4.0],
https://github.com/jenkinsci/remoting/releases/tag/remoting-3.40[3.40],
https://github.com/jenkinsci/remoting/releases/tag/remoting-3.39[3.39].
https://github.com/jenkinsci/remoting/releases/tag/remoting-3.38[3.38], and
https://github.com/jenkinsci/remoting/releases/tag/remoting-3.37[3.37]

The Remoting library has been updated to resolve a security issue in remoting versions prior to 4.0.1 and to add support for the <<websocket-protocol,WebSocket protocol>>.
The update removes outdated agent protocols that had previously been link:/blog/2017/08/11/remoting-update/[deprecated in Jenkins 2.75].
`Inbound TCP Agent Protocols` versions 1, 2, and 3 have been removed.

<<websocket-protocol,WebSocket protocol>> connections require agents using Remoting 4.2 or later.

plugin:ssh-slaves[SSH Build Agents Plugin] will always use the latest `agent.jar`, but other agent types may need to have their `agent.jar` updated manually.
The following agent types should be updated:

* Inbound TCP Agent Protocol agents (formerly known as Java Web Start agents) with `agent.jar` / `slave.jar` on the disk should update to version 4.2 or newer.
  The latest `agent.jar` can be downloaded from any Jenkins server at `/jnlpJars/agent.jar` as in \https://your-jenkins-server.example.com/jnlpJars/agent.jar.
  Users running Windows agents as a service with the Windows Service Wrapper should refer to https://github.com/jenkinsci/windows-slave-installer-module#upgrading-old-agents[Upgrading Old Agents] for information on agent upgrades
* plugin:swarm[Swarm Plugin Client] should update to version 3.18 or newer
* Agent Docker packages offered by the Jenkins project (https://hub.docker.com/r/jenkins/slave/[jenkins/slave] and https://hub.docker.com/r/jenkins/jnlp-slave/[jenkins/jnlp-slave]) should update to version https://github.com/jenkinsci/docker-slave/releases/tag/4.0.1-1/[4.0.1-1] or newer

==== Security Defaults

Some global security settings no longer have a user interface setting that will disable them.
Previously, administrators could disable security with a single checkbox.
They could also disable cross-site request forgery (CSRF) protection with a single checkbox.
Those two settings **cannot be disabled** in this release.

Password auto-fill is only allowed on the login password field.
Password fields which are **not** the login password field will no longer allow password auto-fill.
This avoids browser prompts to automatically fill password fields that are not the login password field.
Password auto-fill for other password fields can be enabled with the system property:

[source,java]
----
hudson.Functions.hidingPasswordFields=false
----

==== Security Deprecations

In 2017 the `Overall/RunScripts`, `Overall/UploadPlugins`, and `Overall/ConfigureUpdateCenter` were announced as potentially dangerous permissions.
 They were disabled by default in the most popular authorization strategies.
Those permissions are now **deprecated** and no longer used in the Jenkins core.
Security configurations which grant `Overall/RunScripts`, `Overall/UploadPlugins`, and `Overall/ConfigureUpdateCenter` while not granting `Overall/Administer` will not work as expected for the Jenkins core functionality.
Plugins relying on these permissions will also eventually move to checking `Overall/Administer` instead.
Custom authorization strategies that that grant `Overall/Administer` without implying one or more of those permissions will no longer work as expected.

==== New Experimental User Interface

The experimental Jenkins user interface refresh can be enabled by setting the property `jenkins.ui.refresh=true`.
The user interface refresh enables a new header color scheme.
Additional user interface changes will be enabled in future releases with the `jenkins.ui.refresh=true` property.

[[websocket-protocol]]
==== Experimental WebSocket Protocol

Jenkins agents have commonly been connected through a dedicated network port.
The dedicated network port required additional firewall and reverse proxy configuration.
The requirement for an extra port sometimes interfered with user port limitations.

The WebSocket protocol has been added to this release as an experimental agent protocol.
WebSocket protocol allows agents to connect to Jenkins over the http and https ports, without requiring additional ports.
Refer to the link:/blog/2020/02/02/web-socket/[WebSocket] blog post for more details.

==== Experimental SystemRead and Manager permissions

Add a new experimental `Overall/SystemRead` permission, which gives (almost) full read access to the Jenkins instance.
The permission is disabled by default, install the link:https://plugins.jenkins.io/extended-read-permission/[Extended Read Permission plugin] to activate it.

Add a new experimental `Overall/Manage` permission which allows a user to configure parts of the global Jenkins configuration without having the `Overall/Administer` permission.
This is an experimental feature, disabled by default, that can be enabled by setting the system property `jenkins.security.ManagePermission=true`.

==== Header and Breadcrumb Layout Improvements

Instances with plugins that depend on specific details of the Jenkins layout (like the https://plugins.jenkins.io/simple-theme-plugin/[Simple Theme plugin]) may have user interface issues with this release.
In the case of the Simple Theme plugin, users or theme maintainers may need to update CSS and JavaScript to match the new layout structure.
