==== Plugin manager improvements

The plugin manager interface includes significant improvements.
Those improvements include a change in the "Available" tab.

The "Available" tab previously listed all available plugins then filtered based on the value in the "search" field.
The "Available" tab now lists no plugins until the user enters a value in the "search" field.
Users who previously scrolled through over 1000 plugins to find their plugin will now need to enter a value in the search field.

==== Auto refresh removed

link:https://issue-redirect.jenkins.io/issue/19828[JENKINS-19828]

The "Enable auto refresh" capability has been removed from Jenkins 2.235.1.
Auto refresh causes serious Jenkins performance issues if a user enables auto refresh on an expensive page and leaves their browser open on that page.
Auto refresh breaks form data entry by requiring that the form must be submitted before the next refresh or entered data will be lost.
Auto refresh breaks expandable list views.

Page refresh extensions are available for popular web browsers like Google Chrome and Mozilla Firefox.
Users that need automatic refresh of a Jenkins page should install one of those extensions.

