==== Plugin manager improvements

The plugin manager interface includes significant improvements.
The "Available" tab previously showed all available plugins then filtered based on the value in the "search" field.
The "Available" tab now has improved search facilities and only shows plugins that match the value in the "search" field.
Users who previously scrolled through over 1000 plugins to find their plugin will now need to enter a value in the search field.

Plugin updates that resolve security issues are shown in the "Updates" tab with a 'Security' label.
Plugins are sorted by popularity in the "Available" tab so that the most frequently installed plugins appear earlier in the list.
Plugin release dates are shown on the "Available" tab.
Plugins seeking new maintainers now include an "up for adoption" banner on the "Available" tab and the "Installed" tab.
Plugin categories are displayed as labels on each plugin.
Clicking a plugin category searches for all plugins matching that category.

==== Auto refresh removed

The "Enable auto refresh" capability has been removed from Jenkins 2.235.1.
Auto refresh causes serious Jenkins performance issues if a user enables auto refresh on an expensive page and leaves their browser open on that page.
Auto refresh breaks form data entry by requiring that the form must be submitted before the next refresh or entered data will be lost.
Auto refresh breaks expandable list views.

Page refresh extensions are available for popular web browsers like Google Chrome and Mozilla Firefox.
Users that need automatic refresh of a Jenkins page should install one of those extensions.
