==== New Windows Installer

Beginning with Jenkins LTS release link:/changelog-stable/#v2.235.3[2.235.3], the same Windows installer is used in the stable release as has been used since April 2020 in the weekly release.
The new Windows installer was announced in a link:/blog/2019/02/01/windows-installers/[blog post].

Jenkins administrators on Windows may choose to continue using and upgrading their existing installation using the mechanism in the Jenkins UI, or they may choose to migrate to the new Windows installer.

===== Upgrade with existing installation

Jenkins administrators on Windows are offered new Jenkins versions from within the "Manage Jenkins" page of their installation.
After the initial installation of Jenkins on Windows, administrators perform upgrades through the "Manage Jenkins" page.
Administrators generally do not use the Jenkins MSI installer to perform a Jenkins upgrade because the upgrade is simple and easy from within Jenkins itself.

Administrators that choose to continue using their existing installation will continue to be able to upgrade to new Jenkins versions.
Settings in the Jenkins installation can be modified by editing the `jenkins.exe.config` file and other configuration files.

In this configuration, Jenkins will continue to use the 32 bit Java Runtime Environment that was included with the previous installer unless `jenkins.exe.config` has been modified to use a 64 bit Java Runtime Environment.
It will similarly continue to use the default port and service account unless it has been modified locally.

===== Upgrade with new Windows Installer

The new Windows installer provides the following additional features:

* Choose a 64 bit Java 8 or 64 bit Java 11 installation to run Jenkins
* Choose the port that Jenkins will use
* Choose the user account and password that will run the Jenkins service

In addition to those choices, the Jenkins home directory is created in the standard AppData location rather than in `C:\Program Files (x86)\Jenkins`.
You'll find the Jenkins home directory in the `%LocalAppData%` of the user account that runs the Jenkins service.
For example, if the user account running the Jenkins service is named `jservice`, then the Jenkins home directory will be in `C:\Users\jservice\AppData\Local\Jenkins.jenkins`.
Once Jenkins is running, the 'System Information' page within 'Manage Jenkins' displays the properties and variables that describe the Jenkins installation.

Upgrading an existing Windows installation to the new installer requires:

. Stop and disable the existing Jenkins service from the Windows Service Manager
. Run the new installer to create the new installation with desired settings
. Stop the newly installed Jenkins service
. Copy existing Jenkins configuration files to the new Jenkins home directory
. Start the newly installed Jenkins service
. Confirm newly installed Jenkins service is behaving as expected

See the link:/blog/2019/02/01/windows-installers/[Windows installer blog post] for more details.
