==== SSHD key exchange and MAC algorithms

The link:https://github.com/jenkinsci/sshd-module/blob/master/README.adoc[Jenkins SSHD module] has been upgraded in this release.
The upgrade disables deprecated key exchange algorithms and deprecrated MAC algorithms by default.

If an administrator requires one or more of the deprecated algorithms, they may be enabled using link:/doc/book/managing/system-properties/[System properties].
Note that these system properties are generally considered unsupported and may be removed at any time.

* `org.jenkinsci.main.modules.sshd.SSHD.excludedKeyExchanges` is a comma-separated string of key exchange algorithms to disable.
  By default, this disables SHA-1 based algorithms as they're no longer considered safe.
  Use an empty string to disable no algorithms.
  The names of supported, enabled, and disabled algorithms can be viewed using the link:/doc/book/system-administration/viewing-logs/[logger] `org.jenkinsci.main.modules.sshd.SSHD` during initialization on the level `FINE`.
* `org.jenkinsci.main.modules.sshd.SSHD.excludedMacs` is a comma-separated string of HMAC algorithms to disable.
  By default, this disables MD5 and truncated SHA-1 based algorithms as they're no longer considered safe.
  Use an empty string to disable no algorithms.
  The names of supported, enabled, and disabled algorithms can be viewed using the link:/doc/book/system-administration/viewing-logs/[logger] `org.jenkinsci.main.modules.sshd.SSHD` during initialization on the level `FINE`.
