[#submittedform]
==== Security hardening for form submissions

A recurring security issue in Jenkins plugins is a lack of cross-site request forgery (CSRF) protection on form submission endpoints.

A security hardening in Jenkins 2.277.2 and 2.287 addresses some of these issues by causing structured form submission (calls to `StaplerRequest#getSubmittedForm`) to fail unless the HTTP verb of the request is POST (a requirement for CSRF protection to be effective).
This will prevent GET requests from being able to submit a JSON form submission (commonly used in Jenkins) as `?form` query parameter.

This additional safeguard can be configured by setting the link:/doc/book/managing/system-properties/#org-kohsuke-stapler-requestimpl-allowed_http_verbs_for_forms[Java system property `org.kohsuke.stapler.RequestImpl.ALLOWED_HTTP_VERBS_FOR_FORMS`].
It accepts a comma-separated list of HTTP verbs of requests allowed to provide structured form submission.
The default value is `POST`.
Setting this system property to `GET,POST` would also allow `GET` requests to provide structured form submissions.
Doing so is discouraged.
Affected components should instead explicitly require `POST` requests by annotating web methods using `@POST` and configure HTML forms they provide to use `<form … method="POST">`, and clients should submit `POST` requests.
