==== Configuration Form Modernization

The transition from HTML `table` layout to HTML `div` layout in configuration forms requires changes in some plugins for compatibility.
Jenkins administrators should update the installed plugins when they upgrade to Jenkins 2.277.1.
Some older plugin releases will cause the Jenkins "Configure System" page to fail to save.
Other older plugin releases will report Java runtime exceptions until they are updated to the most recent release.

Popular plugins that need to be updated after upgrading to Jenkins 2.277.1 include:

* plugin:branch-api[Branch API plugin]
* plugin:envinject[Environment injector plugin]
* plugin:favorite[Favorite plugin]
* plugin:github-branch-source[GitHub branch source plugin]
* plugin:ldap[LDAP plugin]
* plugin:maven-plugin[Maven integration plugin]
* plugin:parameterized-trigger[Parameterized trigger plugin]
* plugin:token-macro[Token macro plugin]

Use the Plugin Manager to update plugins immediately after upgrading to Jenkins 2.277.1.
Make sure to _Check for Updates_ to ensure no outdated cached data hides updates.

NOTE: Plugin maintainers should refer to the link:/doc/developer/views/table-to-div-migration/[table to div layout migration guide].
The link:https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=20741[table to div dashboard] provides the status of issues related to this user interface improvement.

==== Spring Security update

Jenkins 2.277.1 has replaced the outdated Acegi Security library with the Spring Security library.
The most popular plugins have already been updated as necessary to support the change.
Refer to the link:https://github.com/jenkinsci/jep/blob/master/jep/227/compatibility.adoc[Spring Security compatibility table] for questions related to specific plugins.

Privately maintained plugins may need changes to adapt to the change from Acegi Security to Spring Security.
Refer to Jesse Glick's link:/blog/2020/11/10/spring-xstream/[Spring Security blog post] for more details.

==== XStream update (JEP-228)

Jenkins 2.277.1 has replaced its outdated fork of the XStream XML serialization library with a recent release of the official XStream library.
The most popular plugins have already been updated as necessary to support the change.
Refer to the link:https://github.com/jenkinsci/jep/blob/master/jep/228/compatibility.adoc[XStream compatibility table] for questions related to specific plugins.

Privately maintained plugins may need changes to adapt to the change from the Jenkins XStream fork to the official XStream library.
Refer to Jesse Glick's link:/blog/2020/11/10/spring-xstream/[XStream unfork blog post] for more details.

// Intentionally not including this, since I'm not aware of any issues reported and don't know what the user would do if there is a problem.
//
// ==== JQuery update
//
// Jenkins 2.277.1 has replaced its outdated copy of the link:https://jquery.com/[JQuery user interface lirary] with the most recent release library.
// The most popular plugins have already been updated as necessary to support the change.

==== Stop bundling CVS plugin with Jenkins

Certain key Jenkins capabilities were initially created inside the Jenkins core.
As Jenkins has developed further, capabilities moved from inside Jenkins core to dedicated Jenkins plugins, like the plugin:cvs[CVS plugin].
When those plugins were created, the plugins were "bundled" inside the jenkins.war file to retain compatibility for plugins that depended on their functionality to be inside Jenkins core.
The Jenkins project is no longer publishing any plugins that require the "bundled" versions of the plugin:cvs[CVS plugin].
The plugin:cvs[CVS plugin] is no longer bundled with Jenkins.

In very rare cases, this could result in problems when attempting to install plugins compatible with Jenkins (then Hudson) before 1.340.
If you use a plugin that relies on the functionality provided by the CVS plugin and manage plugins outside the Jenkins plugin manager, you will now need to ensure yourself that a recent release of the CVS plugin is installed.
Jenkins will attempt to load such plugins but may fail at any time during startup or afterwards with `ClassNotFoundException` or similar.
In those cases, the best path forward is usually to modify the plugin that has the problem so that it requires a newer version of Jenkins core.
