==== New icons

The new icons introduced with Jenkins 2.289.1 replace the previous icons.
The plugin:greenballs[Green Balls plugin] is not compatible with the new icons.
The plugin:greenballs[Green Balls plugin] can be disabled or removed.

==== Stop bundling Ant and Javadoc plugins with Jenkins

Certain key Jenkins capabilities were initially created inside the Jenkins core.
As Jenkins has developed further, capabilities moved from inside Jenkins core to dedicated Jenkins plugins, like the plugin:ant[Ant plugin] and the plugin:javadoc[Javadoc plugin].
When those plugins were created, the plugins were "bundled" inside the jenkins.war file to retain compatibility for plugins that depended on their functionality to be inside Jenkins core.
The plugin:ant[Ant plugin] and the plugin:javadoc[Javadoc plugin] are no longer bundled with Jenkins.

In very rare cases, this could result in problems when attempting to install plugins compatible with Jenkins (then Hudson) before 1.430.
If you use a plugin that relies on the functionality provided by the Ant plugin or the Javadoc plugin and manage plugins outside the Jenkins plugin manager, you will now need to ensure yourself that a recent release of those plugins are installed.
Jenkins will attempt to load such plugins but may fail at any time during startup or afterwards with `ClassNotFoundException` or similar.
In these cases, the best path forward is usually to modify the plugin that has the problem so that it requires a newer version of Jenkins core.
