==== Default Docker images use Java 11

The Jenkins Docker images with tags that do not specify a Java version now use Java 11 instead of Java 8.
Jenkins controller images with the following tags will use Java 11 beginning with 2.303.1:

* `jenkins/jenkins:lts`
* `jenkins/jenkins:lts-alpine`
* `jenkins/jenkins:lts-centos7`
* `jenkins/jenkins:lts-slim`
* `jenkins/jenkins:2.303.1`
* `jenkins/jenkins:2.303.1-alpine`
* `jenkins/jenkins:2.303.1-centos7`
* `jenkins/jenkins:2.303.1-slim`

Additional controller images and tags have been added for those users who need to remain on Java 8.
The new Java 8 tags include:

* `jenkins/jenkins:lts-jdk8`
* `jenkins/jenkins:lts-alpine-jdk8`
* `jenkins/jenkins:lts-centos7-jdk8`
* `jenkins/jenkins:lts-slim-jdk8`
* `jenkins/jenkins:2.303.1-jdk8`
* `jenkins/jenkins:2.303.1-alpine-jdk8`
* `jenkins/jenkins:2.303.1-centos7-jdk8`
* `jenkins/jenkins:2.303.1-slim-jdk8`

Jenkins agents should be run with the same Java version as the controller.
With the controller upgrade from Java 8 to Java 11, Jenkins agents need to be updated to run with Java 11.
When using Docker images for the agent, that can generally be done by appending the `-jdk11` suffix to the agent tag.
Cloud agents and static agents will need to be configured to launch with Java 11 instead of Java 8.

////
// Not sure that agent images will be ready for initial release

===== Inbound agent images

Jenkins inbound agent images that do not specify a Java version now use Java 11 instead of Java 8.
Jenkins inbound agent images with the following tags will use Java 11:

* `jenkins/inbound-agent:alpine`
* `jenkins/inbound-agent:latest`
* `jenkins/inbound-agent:4.10-1`
* `jenkins/inbound-agent:4.10-1-alpine`
* `jenkins/inbound-agent:4.10-1-windowsservercore-ltsc2019`

Additional inbound agent images and tags have been added for those users who need to remain on Java 8.
The new Java 8 tags include:

* `jenkins/inbound-agent:alpine-jdk8`
* `jenkins/inbound-agent:latest-jdk8`
* `jenkins/inbound-agent:4.10-1-jdk8`
* `jenkins/inbound-agent:4.10-1-alpine-jdk8`
* `jenkins/inbound-agent:4.10-1-windowsservercore-ltsc2019-jdk8`

===== Outbound agent images

Jenkins outbound agent images that do not specify a Java version now use Java 11 instead of Java 8.
Jenkins outbound agent images with the following tags will use Java 11:

* `jenkins/ssh-agent:alpine`
* `jenkins/ssh-agent:latest`
* `jenkins/ssh-agent:3.1.0`
* `jenkins/ssh-agent:3.1.0-alpine`
* `jenkins/ssh-agent:3.1.0-windowsservercore-ltsc2019`

Additional outbound agent images and tags have been added for those users who need to remain on Java 8.
The new Java 8 tags include:

* `jenkins/ssh-agent:alpine-jdk8`
* `jenkins/ssh-agent:latest-jdk8`
* `jenkins/ssh-agent:3.1.0-jdk8`
* `jenkins/ssh-agent:3.1.0-alpine-jdk8`
* `jenkins/ssh-agent:3.1.0-windowsservercore-ltsc2019-jdk8`

===== Agent images

Jenkins agent images that do not specify a Java version now use Java 11 instead of Java 8.
Jenkins agent images with the following tags will use Java 11:

* `jenkins/agent:alpine`
* `jenkins/agent:archlinux`
* `jenkins/agent:latest`
* `jenkins/agent:latest-archlinux`
* `jenkins/agent:bullseye`
* `jenkins/agent:4.10-1`
* `jenkins/agent:4.10-1-alpine`
* `jenkins/agent:4.10-1-windowsservercore-ltsc2019`

Additional agent images and tags have been added for those users who need to remain on Java 8.
The new Java 8 tags include:

* `jenkins/agent:alpine-jdk8`
* `jenkins/agent:archlinux-jdk8`
* `jenkins/agent:latest-jdk8`
* `jenkins/agent:latest-archlinux-jdk8`
* `jenkins/agent:bullseye-jdk8`
* `jenkins/agent:4.10-1-jdk8`
* `jenkins/agent:4.10-1-alpine-jdk8`
* `jenkins/agent:4.10-1-windowsservercore-ltsc2019-jdk8`

// End of agent comment block
////

==== Obsolete Docker images and tags no longer published

Jenkins Docker images for new releases are not published for `centos`.
The `centos` images use CentOS 8 as a baseline and CentOS 8 is no longer receiving updates from the Red Hat Enterprise Linux upstream.

Jenkins Docker Windows images for new releases are not published for the `1809` images.
Microsoft has ended mainstream support for `1809`.

Jenkins Docker tags that include a version number are no longer published with the redundant `-lts` tag.
The transition looks like this:

* 2.303.1-lts is replaced with 2.303.1
* 2.303.1-lts-alpine is replaced with 2.303.1-alpine
* 2.303.1-lts-centos7 is replaced with 2.303.1-centos7
* 2.303.1-lts-slim is replaced with 2.303.1-slim

==== Multi-architecture Docker images

Jenkins Docker images now support multiple architectures, including `amd64` and `arm64` from selected images.
The images with support for multiple architectures include:

* 2.303.1 and 2.303.1-jdk11
* 2.303.1-rhel-ubi8-jdk11
* 2.303.1-almalinux

==== Plugins that do not support Java 11

Some Jenkins plugins do not support Java 11.
Plugins that do not support Java 11 also tend to be unmaintained.
Users should remove those plugins before running Jenkins with Java 11.

The plugin:ruby-rubtime[ruby runtime plugin] is not supported with Java 11.
Plugins that depend on the ruby runtime plugin do not load in Jenkins running with Java 11.

Plugins that depend on the ruby runtime include:

Ruby runtime plugins with more than 1000 installations:

* plugin:gitlab-hook[Gitlab Hook] (multiple security vulnerabilities)
* plugin:cucumber[Cucumber]
* plugin:rvm[Rvm]
* plugin:pyenv[pyenv]

Ruby runtime plugins with less than 700 installations:

* plugin:capitomcat[Capitomcat]
* plugin:chef[Chef]
* plugin:ci-skip[Ci Skip]
* plugin:commit-message-trigger-plugin[Commit Message Trigger]
* plugin:git-notes[git-notes]
* plugin:mysql-job-databases[MySQL Job Databases]
* plugin:Pathignore[Pathignore]
* plugin:perl[Perl]
* plugin:rbenv[rbenv]
* plugin:singleuseslave[Single Use Agent]
* plugin:travis-yml[Travis YML]

Ruby runtime plugins with less than 100 installations:

* plugin:buddycloud[buddycloud]
* plugin:devstack[DevStack]
* plugin:ikachan[Ikachan]
* plugin:jenkinspider[Jenkinspider]
* plugin:perl-smoke-test[Perl Smoke Test]
* plugin:pry[pry]
* plugin:Yammer[Yammer]

==== New RPM package manager dependency

The Jenkins 2.303.1 RPM package has been made more consistent with the Debian Jenkins packaging.
It uses the `daemonize` program to run the Java process of the Jenkins controller as a daemon.
The `daemonize` program is available from the `epel-release` repository for most RPM based distributions.

Some distributions based on the RPM package manager do not enable the 'epel-release' repository by default.
Instructions to enable the epel-release repository are included in the Jenkins installation guide instructions for link:/doc/book/installing/linux/#red-hat-centos[Red Hat Enterprise Linux / CentOS].

Before updating to Jenkins 2.303.1, run the command:

.Red Hat Enterprise Linux / CentOS
[source,bash]
----
# yum install epel-release
----

==== Debian upgrade in Docker images

Docker controller images based on Debian, including `jenkins/jenkins:lts`, `jenkins/jenkins:lts-slim`, `jenkins/jenkins:2.303.1`, and `jenkins/jenkins:2.303.1-slim` are now based on link:https://www.debian.org/releases/bullseye/[Debian bullseye], the most recent Debian release.
Debian bullseye was released August 14, 2021 after a long period of stabilization and testing.

Some packages that had been included in the Debian buster images may not be installed in these images.
If your installation needs one of those packages, you'll need to install it from inside your custom Dockerfile.

==== Removed Apache Commons Digester from the Jenkins core

The Apache Commons Digester v2.1 has been removed from Jenkins core.
The library was last released in 2010.
Plugins that depend on the library need to be updated to remove that dependency.

Plugins that are affected include:

* link:https://plugins.jenkins.io/vs-code-metrics/[Visual Studio Code Metrics]
* link:https://plugins.jenkins.io/BlameSubversion/[Blame Subversion]
* link:https://plugins.jenkins.io/javatest-report/[JavaTest report]
* link:https://plugins.jenkins.io/vss/[Visual SourceSafe]
* link:https://plugins.jenkins.io/synergy/[Synergy]
* link:https://plugins.jenkins.io/config-rotator/[Config Rotator]
* link:https://plugins.jenkins.io/harvest/[Harvest SCM]
* link:https://plugins.jenkins.io/cmvc/[CMVC]

Suspended plugins (no longer distributed by the Jenkins update center) that are affected include:

* link:https://plugins.jenkins.io/tfs/[TFS]
* link:https://issues.jenkins-ci.org/browse/INFRA-2487[svn-release-mgr]
* link:https://plugins.jenkins.io/cpptest/[cpptest]
* link:https://plugins.jenkins.io/CFLint/[CFLint]

==== Stop bundling External Monitor Job Type, LDAP, and PAM plugins with Jenkins

Certain key Jenkins capabilities were initially created inside the Jenkins core.
As Jenkins has developed further, capabilities moved from inside Jenkins core to dedicated Jenkins plugins, like the plugin:external-monitor-job[External Monitor Job plugin], the plugin:ldap[LDAP plugin], and the plugin:pam[PAM authentication plugin].
When those plugins were created, the plugins were "bundled" inside the jenkins.war file to retain compatibility for plugins that depended on their functionality to be inside Jenkins core.
The plugin:external-monitor-job[External Monitor Job plugin], the plugin:ldap[LDAP plugin], and the plugin:pam[PAM authentication plugin] are no longer bundled with Jenkins.

In very rare cases, this could result in problems when attempting to install plugins compatible with Jenkins before 1.467.
If you use a plugin that relies on the functionality provided by the plugin:external-monitor-job[External Monitor Job plugin], the plugin:ldap[LDAP plugin], or the plugin:pam[PAM authentication plugin] and manage plugins outside the Jenkins plugin manager, you will now need to ensure yourself that a recent release of those plugins are installed.
Jenkins will attempt to load such plugins but may fail at any time during startup or afterwards with `ClassNotFoundException` or similar.
In these cases, the best path forward is usually to modify the plugin that has the problem so that it requires a newer version of Jenkins core.

==== Removed JEP-200 compatibility workarounds

Workarounds that assured older plugin compatibility with the link:/blog/2018/03/15/jep-200-lts/[security hardening improvements] of link:https://github.com/jenkinsci/jep/blob/master/jep/200/README.adoc[JEP-200] have been removed.
If you are using any of the following plugins, make sure you use at least the versions specified:

* Maven Integration 3.1 (released Jan 2018)
* Job DSL 1.67 (released Jan 2018)
* Monitoring 1.71.0 (released Feb 2018)
* Git Client 2.7.1 (released Jan 2018)
* Pipeline: Supporting APIs 2.17 (released Jan 2018)
* OWASP Dependency-Check 3.1.1 (released Jan 2018)

==== Removed `jna-posix` from Jenkins core

The `jna-posix` dependency has been removed from Jenkins core.
Plugins that use `jna-posix` functionality, including
plugin:maven-repo-cleaner[Maven Repository Scheduled Cleanup],
plugin:sicci_for_xcode[SICCI for Xcode], and
plugin:tmpcleaner[java.io.tmpdir cleaner]
are no longer supported and must be removed.

==== Removed `JTidy` from Jenkins core

The `JTidy` dependency has been removed from Jenkins core.
Users of the plugin:jdepend[JDepend plugin] must upgrade to the latest version.
Other plugins that use JTidy functionality, including plugin:nis-notification-lamp[NIS notification lamp], must be updated to explicitly declare a dependency on JTidy rather than relying on Jenkins core to provide this library.

==== Removed Bytecode Compatibility Transformer from Jenkins core

Support for plugins that rely on the `hudson.model.Queue$Item#id` or `hudson.model.AbstractProject#triggers fields`, including plugin:slave-prerequisites[Slave Prerequisites plugin] and plugin:vertx[vertx plugin], has been dropped.
Any such plugins must be removed prior to upgrading Jenkins.
If you have customized the hudson.ClassicPluginStrategy.noBytecodeTransformer system property, you should remove this customization.
