[#SECURITY-2452]
==== Redefinition of build cause description property

The short description of build causes  was defined as a short snippet of HTML in Jenkins 2.314 and earlier, LTS 2.303.1 and earlier.
It is exposed as the `shortDescription` field of build causes in the link:/doc/book/using/remote-access-api/[Remote Access API] of Jenkins, and rendered on the UI on the overview page of builds, unless a build cause provides a custom UI.

To prevent further security vulnerabilities like link:/security/advisory/2021-10-06/#SECURITY-2499[SECURITY-2499] from having an impact on Jenkins users, the method has been redefined to return plain text in Jenkins 2.315 and LTS 2.303.2, and its output is no longer rendered as HTML on the UI.

Users of the remote API who are currently rendering this field as HTML on their custom dashboards or similar API clients are advised to no longer do so.
With the redefinition, any content that could be interpreted as HTML would be unsafe to render that way, as plugins may no longer escape it.

Advice for maintainers has been added to the link:/doc/developer/security/xss-prevention/Cause-getShortDescription/[developer documentation].

// TODO Mention SECURITY-2424?
