==== Remoting 3 upgrade

Remoting, the library handling the communication between Jenkins master and agents, got a major upgrade that introduced a new communication protocol (JNLP4).

With this upgrade comes a restriction on which `Launcher` implementations are allowed to connect.
It is possible that some plugins (mostly _cloud_ implementations) will fail to connect.
If that happens, set the System property `jenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification` as a workaround.

    java -Djenkins.slaves.DefaultJnlpSlaveReceiver.disableStrictVerification=true … -jar jenkins.war

https://wiki.jenkins.io/display/JENKINS/Features+controlled+by+system+properties[Learn more about system properties in Jenkins.]

Additionally, this is the first remoting release that requires Java 7. While agents have needed Java 7 for a while now, remoting is also used to communicate with the Maven process in the Maven project type in the Maven Integration Plugin. These builds now needs a JDK 7 or newer to run. Use toolchains to compile with an older version of Java.

==== Administrative monitors are now shown on most pages

_Administrative monitors_ are the notifications only shown on the _Manage Jenkins_ page so far.
They are now also displayed to administrators on most other pages to increase visibility of important notifications.

To allow finer-grained control over which administrative monitors are shown, they can now be disabled and enabled in _Configure Jenkins_.

Please note that due to how it's implemented, the _Reverse Proxy Setup_ monitor will _not_ be shown on every screen.
