==== Linux installation packages use `systemd`

Linux installation packages provided by the Jenkins project now use the Linux system and service manager (`systemd`) to manage the Jenkins service and its configuration.
Existing installations that use the Debian/Ubuntu deb package format, the Red Hat rpm package format, and the SUSE rpm package format will use `systemd` when they upgrade to Jenkins 2.332.1.

The upgrade process reads the existing settings from the operating system specific System V `init` configuration files and writes those settings into a `systemd` override file for the Jenkins service.

After the upgrade process is complete, the system-level configuration settings are managed with the command:

[source,bash]
----
$ systemctl edit jenkins
----

See the link:/doc/book/system-administration/systemd-services/[Managing systemd services] page for more details of `systemd` administration.

==== Guava upgraded

The Guava library from Google is bundled in Jenkins core.
Jenkins has upgraded the Guava library from 11.0.1 (released on January 9, 2012) to 31.0.1 (released on September 27, 2021).
Plugins have already been prepared to support the new version of Guava in link:https://github.com/jenkinsci/jep/blob/master/jep/233/README.adoc[JEP-233].
Use the Plugin Manager to upgrade all plugins before and after upgrading to Jenkins 2.332.1.
See the link:/blog/2021/11/09/guava-upgrade/[Guava upgrade blog post] for more details.

==== JRuby removed

JRuby support has been removed from Jenkins core.
A small number of JRuby-based plugins are affected.
See the link:/blog/2021/12/22/deprecated-ruby-runtime/[JRuby removal blog post] for migration notes.

==== ASM 5 removed

A repackaged version of ObjectWebASM 5 and the upstream version of ASM were both included in Jenkins core.
Jenkins core no longer provides the repackaged version of ASM 5.
Users of SCM API must upgrade SCM API to the latest version prior to upgrading Jenkins.
Plugins that use the repackaged version of ASM 5 must be updated to use the upstream version of ASM instead.
