==== OpenJDK 11.0.16/17.0.4 and the C2 JIT compiler

OpenJDK 11.0.16 and 17.0.4 are susceptible to https://bugs.openjdk.org/browse/JDK-8292260[JDK-8292260], a regression in the C2 JIT compiler which https://mail.openjdk.org/pipermail/jdk-updates-dev/2022-August/016460.html[may cause the JVM to crash unpredictably].
The OpenJDK project has released fixes in 11.0.16.1 and 17.0.4.1.
As of August 26, 2022, the official Jenkins Docker images have been updated with OpenJDK 11.0.16.1 and 17.0.4.1 in version 2.346.3-2.

==== OpenJDK 11.0.16/17.0.4 and the metaspace

The version of OpenJDK in the official Docker image has been upgraded from 11.0.15 to 11.0.16 and from 17.0.3 to 17.0.4.
This exposes a metaspace memory leak in Pipeline: Groovy 2692.v76b_089ccd026 and earlier and in Script Security 1172.v35f6a_0b_8207e and earlier.
After upgrading Jenkins to 2.346.3, upgrade Pipeline: Groovy to 2705.v0449852ee36f or later and upgrade Script Security to 1175.v4b_d517d6db_f0 or later.
It is generally recommended to upgrade all plugins after upgrading Jenkins core.

For more information about recent JVM metaspace changes,
see https://www.youtube.com/watch?v=XqaQ-z70sQs[Taming Metaspace: a look at the machinery, and a proposal for a better one | FOSDEM 2020] and the following blog posts:

* https://stuefe.de/posts/metaspace/what-is-metaspace/[What is Metaspace?]
* https://stuefe.de/posts/metaspace/metaspace-architecture/[Metaspace Architecture]
* https://stuefe.de/posts/metaspace/what-is-compressed-class-space/[What is Compressed Class Space?]
* https://stuefe.de/posts/metaspace/sizing-metaspace/[Sizing Metaspace]
* https://stuefe.de/posts/metaspace/analyze-metaspace-with-jcmd/[Analyze Metaspace with `jcmd VM.metaspace`]

==== OpenJDK 11.0.16 and container awareness for cgroups v2

OpenJDK 11.0.16 contains a fix for https://bugs.openjdk.org/browse/JDK-8230305[JDK-8230305];
i.e., container awareness for https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html[cgroups v2].

Previously, there would be no container detection when running OpenJDK 11.0.15 on cgroups v2,
and the limits from the container host would be used.
As of OpenJDK 11.0.16, OpenJDK detects container limits via cgroups v2.
These limits affect, for example,
the garbage collection (GC) algorithm selected by the JVM,
the default size of the heap,
the sizes of thread pools,
and how default parallelism is determined for `ForkJoinPool`.

For more information, see https://developers.redhat.com/articles/2022/04/19/java-17-whats-new-openjdks-container-awareness#tuning_defaults_for_containers[Java 17: What’s new in OpenJDK's container awareness]
and https://www.youtube.com/watch?v=ZmTUBKvSWzs[OpenJDK 17 | Container Detection Demo].
