==== Require Java 11

The official Jenkins Docker images have been based on Java 11 for many months, with Java 8 available as a fallback and Java 17 available in preview mode.
Beginning with the weekly release line of Jenkins 2.357, the Java 8 images have been retired and the Java 17 images will transition from preview to general availability.
Users of the official Docker images do not need to install or configure Java on their own, as it comes preinstalled in the Docker images.

Users of the official Jenkins OS packages for Debian, Red Hat, and SUSE Linux distributions should note that these packages are agnostic to the Java vendor.
This means you must bring your own Java package. 
One straightforward way to do this is to install Java 11 from your Linux distribution, as described on the package download site:

* link:https://pkg.jenkins.io/debian/[Debian]
* link:https://pkg.jenkins.io/redhat/[Red Hat]
* link:https://pkg.jenkins.io/opensuse/[SUSE]

This does not require any custom repositories, so this is the simplest method and was used by the Jenkins project's packaging tests.
However, it does not give the user a high degree of control over the Java runtime environment.
The official Jenkins Docker images and the Jenkins infrastructure project use Adoptium/Eclipse Temurin.
Enthusiastic users may wish to install Java from Adoptium or another vendor.
Adoptium recently began providing Linux installation packages, as described in link:https://blog.adoptium.net/2021/12/eclipse-temurin-linux-installers-available/[a piece by George Adams].
The choice of which Java vendor to use is your own, as long as that vendor provides Java 11 or Java 17.
Refer to your chosen Java vendor for installation instructions.

Once you have installed a suitable version of Java, configuring Jenkins to use that Java runtime is easy.
The most straightforward way is to configure that version of Java as the default version of Java at the operating system (OS) level:

Debian: `update-alternatives --config java`
Red Hat: `alternatives --config java`
SUSE: `update-alternatives --config java`

Alternatively, users who do not wish to change the default version of Java can customize the `JAVA_HOME` or `JENKINS_JAVA_CMD` environment variable as part of the Jenkins `systemd(1)` service unit.
Refer to the link:https://www.jenkins.io/doc/book/system-administration/systemd-services/[Managing systemd services] section of the Jenkins documentation for more information.

==== Updated Jetty version

The Jetty version has been updated from 9.4.46.v20220331 to 10.0.11.
Support for OpenSSL-style PEM-encoded RSA private keys has been removed when running Jenkins with the embedded Jetty (Winstone) container and TLS.
Specifically, the `--httpsPrivateKey` and `--httpsCertificate` flags have been removed in favor of the `--httpsKeyStore` flag.
The removed flags have had printed deprecation warnings since 2016, and were implemented with non-standard APIs that have since been removed from Java 17.
The recommendation is to migrate to the `--httpsKeyStore` flag, which takes a keystore as described in link:https://www.jenkins.io/doc/book/installing/initial-settings/#https-with-an-existing-certificate[the documentation].
As of link:https://openjdk.org/jeps/229[JEP 229], link:https://en.wikipedia.org/wiki/PKCS_12[PKCS12] is the recommended keystore type.

==== Updated minimum supported Remoting version

The minimum required Remoting version has been increased to 4.2.1. Ensure that all agents are running a recent version of Remoting prior to upgrading.

==== Converted `instance-identity` to a separate plugin

Since `instance-identity` is normally a basic part of Jenkins core, this new plugin will be automatically installed.
If you use an “as-code” installation mechanism, for example a text file with a list of plugins, you may need to add `instance-identity` version 3.1 or later, in order to restore this functionality.
In particular, inbound agents using TCP (but not WebSocket) transport require this plugin to be installed.
There may be other cases, which can be identified by use of APIs in the `jenkins.model.identity` package rather than directly accessing `org.jenkinsci.main.modules.instance_identity`.

==== Removed Java Web Start support

Jenkins no longer supports attaching a static inbound agent by selecting the Launch button from an agent machine's web browser when running the controller on Java 8.
Java Web Start has been removed from newer versions of most distributions.
You should instead download the agent JAR file from the provided link and run the supplied command (`java -jar agent.jar -jnlpUrl …`) on the agent machine. 
The *JVM options* field was removed from the inbound launcher configuration, as it would not have any effect beyond adjusting the suggested command.

The control window displayed when using a Java Web Start agent is also removed.
Its main function was to be closed, which is now done by simply terminating the shell process.
It also offered a menu with platform-specific agent installers that would offer to create system services to make the agent permanent. 
You can accomplish something similar in many ways without this GUI, according to your operating system.