[#SECURITY-3030]
==== Request part count limit for `multipart/form-data` requests

A link:/security/advisory/2023-03-08/#SECURITY-3030[security fix] for a DoS vulnerability when parsing `multipart/form-data` request bodies introduces limits for the number of request parts that can be processed.
By default, these limits are 1000.

Some Jenkins forms can be very complex, and these limits apply to all fields and not just fields representing uploaded files.
As a result, legitimate submissions of complex forms that include (possible) file uploads may be affected by these limits.
If that happens, these limits can be changed by setting the Java system properties link:/doc/book/managing/system-properties/#hudson-util-multipartformdataparser-fileupload_max_files[`hudson.util.MultipartFormDataParser.FILEUPLOAD_MAX_FILES`] and link:/doc/book/managing/system-properties/#org-kohsuke-stapler-requestimpl-fileupload_max_files[`org.kohsuke.stapler.RequestImpl.FILEUPLOAD_MAX_FILES`] to a bigger value, or to `-1` to completely disable them.
