==== De-duplicate logging implementations

Support for log rotation via `SIGALRM` has been removed.
The command-line argument `--daemon` has been removed.
Users of the official Jenkins OS packages, which rely on the `copytruncate` option, are not affected.
Users of the `--logfile` argument who have their own `logrotate` configuration should ensure they are using the `copytruncate` option rather than relying on `SIGALRM`.

==== Set a default file size rotation of AsyncPeriodicWork/AsyncAperiodicWork

Periodic task log files are now rotated based on the file size, with a default size of 10 MB.
Previously, they were not rotated based on the file size.
To revert to the previous behavior and disable the file size rotation, the system properties link:/doc/book/managing/system-properties/#hudson-model-asyncaperiodicwork-logrotatesize[`hudson.model.AsyncAperiodicWork.logRotateSize=-1`] and link:/doc/book/managing/system-properties/#hudson-model-asyncperiodicwork-logrotatesize[`hudson.model.AsyncPeriodicWork.logRotateSize=-1`] can be used.

==== Upgrade required Remoting version from 4.2.1 to 4.7

The minimum required Remoting version has been increased to 4.7, which released on February 16, 2021.
When an agent with a Remoting version older than 4.7 connects to the Jenkins controller, the agent connection is rejected.
Ensure that all agents are running a recent version of Remoting prior to upgrading.
Agents with unsupported Remoting versions can be allowed to connect to the controller by setting the `hudson.slaves.SlaveComputer.allowUnsupportedRemotingVersions` system property to true.
