==== Input name prefix added

When creating or saving a view where "elements" was used for the name of something such as a freestyle job, folder, or even pipeline, the `elements` property was being overloaded.
To resolve this, a prefix (`item_`) has been added to the name of input elements of ListView to prevent form submission issues when an Item (job) is named "elements".
The following plugins *must* be upgraded when updating Jenkins:

* plugin:categorized-view[Categorized view]
* plugin:build-monitor-plugin[Build Monitor View]
* plugin:calendar-view[Calendar View]

==== Remove dependency on jenkins-js-modules

The `jenkins-js-modules` dependency has been removed to simplify the loading of JavaScript and CSS.
This dependency was removed for core, where usage was limited to the new job, plugin manager, and system information pages.
Additionally, the only plugins that were using the dependency are plugin:dependency-track[OWASP Dependency-Track] and plugin:servicenow-cicd[ServiceNow CI/CD].
The plugins have been updated accordingly and users of OWASP Dependency-Track must upgrade to 4.3.1 or later, while users of ServiceNow CI/CD must upgrade to 2.1 or later.

==== Jenkins sign-in page update

The Jenkins sign-in page was updated with enhanced visuals and support for browser-native themes.
As a result, users that have the plugin:login-theme[Login Theme] plugin installed must update to version link:https://github.com/jenkinsci/login-theme-plugin/releases/tag/46.v36f624efb_23d[46.v36f624efb_23d].

