==== Java 21 supported

Jenkins 2.426.1 supports Java 21.
Java 21 is supported from `java -jar jenkins.war`, from the operating system specific installers, and from the container images.
Container labels that previously included "-jdk21-preview" are now available with "-jdk21" for amd64 (Intel/AMD) and aarch64 (ARM) architectures.

Refer to the specific link:https://hub.docker.com/r/jenkins/jenkins/tags?page=1&name=jdk21[Java 21 container images on hub.docker.com] for more details.

A Java 21 preview is available for architectures where Eclipse Temurin has not yet released a general availability release of Java 21.

==== Prototype removed from Jenkins

As of Jenkins 2.426.1, Prototype has been removed from Jenkins core.
This was initially removed in the weekly 2.426 release and is the result of work done since May 2023.
Plugins that had previously used Prototype must have its usage removed accordingly.
Thanks to all of the work from plugin maintainers and contributors, there has been great progress made to ensure that plugins have been updated.
The list of plugins can be found in our link:https://docs.google.com/spreadsheets/d/1dpaKALZaK0_HIGy6ony3wnegr1frTg3u1lngG4KdoC8/edit#gid=0[tracking sheet].
At this time, there are several plugins with over 800 installs that have not removed Prototype from their configuration.
These plugins are:

* link:https://issues.jenkins.io/browse/JENKINS-71303[Fortify]
* link:https://github.com/jenkinsci/xray-connector-plugin/issues/75[Xray Connector]
* link:https://issues.jenkins.io/browse/JENKINS-71308[Synopsys Coverity]
* link:https://issues.jenkins.io/browse/JENKINS-71309[qTest]
* link:https://issues.jenkins.io/browse/JENKINS-71311[Azure App Service]

There are other plugins, all under 700 installs, that have issues created for them in the Jenkins issue tracker, linked to the overall link:https://issues.jenkins.io/browse/JENKINS-70906[Prototype removal epic].

==== Appearance system configuration breaks JCasC

The newly introduced Appearance system configuration page will require adjustments in your JCasC files when at least one of the following plugins is installed in its latest version:

* link:https://plugins.jenkins.io/theme-manager[Theme Manager]
* link:https://plugins.jenkins.io/dark-theme[Dark Theme]
* link:https://plugins.jenkins.io/simple-theme-plugin[Simple Theme]
* link:https://plugins.jenkins.io/customizable-header[Customizable Header]
* link:https://plugins.jenkins.io/customize-build-now[Customize Build Now Label]
* link:https://plugins.jenkins.io/login-theme[Login Theme]

The configuration of these plugins needs to be moved from `unclassified` to `appearance`.

==== Minimum required Remoting version updated to 4.13

The minimum required Remoting version has been increased to 4.13, which was released on March 4, 2022.
When an agent with a Remoting version older than 4.13 connects to the Jenkins controller, the agent connection is rejected.
Ensure that all agents are running a recent version of Remoting prior to upgrading.
Agents with unsupported Remoting versions can be allowed to connect to the controller by setting the `hudson.slaves.SlaveComputer.allowUnsupportedRemotingVersions` system property to true.

==== Treeview option removed for artifactList

In an effort to ensure content security policy (CSP) compatibility, `hudson.model.Run#TREE_CUTOFF` has been removed in favor of `hudson.model.Run#LIST_CUTOFF`.
The treeview option was using inline JavaScript, going against the link:https://www.jenkins.io/doc/developer/security/csp/#inline-javascript-blocks[Jenkins CSP standards].
This is also part of the larger project to link:https://issues.jenkins.io/browse/JENKINS-71014[remove or update any non-compliant code in Jenkins core].

==== Remove System V initialization script

Since March 2022, Jenkins has required the use of `systemd` to manage services.
For newer systems such as RHEL 7 or Fedora 15 (and above), `systemd` is used and there are no issues.
However, earlier versions are still using the System V initialization script.
To remedy this, the System V init script has been removed and RPM users with a custom log directory will no longer have a `logrotate(8)` configuration out-of-the-box.

==== End of support for Red Hat Enterprise Linux 7 and is derivatives

The May 30, 2023 link:/blog/2023/05/30/operating-system-end-of-life/[end of life operating systems blog post] announced the end of support for Red Hat Enterprise Linux 7 and its derivatives like CentOS 7, Scientific Linux 7, and Oracle Linux 7.
Users should replace their Red Hat Enterprise Linux 7 installations with another operating system.
If they prefer to continue with Red Hat or one of its derivatives, they have many alternatives, including:

* link:https://access.redhat.com/products/discover-red-hat-enterprise-linux/[Red Hat Enterprise Linux] 8 or 9
* link:https://almalinux.org/[AlmaLinux] 8 or 9
* link:https://rockylinux.org/[Rocky Linux] 8 or 9
* link:https://www.oracle.com/linux/[Oracle Linux] 8 or 9
