==== Upgrade to the latest version of Remoting

The `+-jnlpUrl ${JENKINS_URL}/computer/${AGENT_NAME}/jenkins-agent.jnlp+` argument to the agent JAR has been deprecated; use `+-url ${JENKINS_URL}+` and `+-name ${AGENT_NAME}+` instead, potentially also passing in `-webSocket`, `-tunnel`, and/or work directory options as needed.
Make sure you reset all inbound launcher options to defaults, and follow new guidance for command-line options for agent.jar.
The official Docker images are already using the new calling convention.

==== Replace diskSpaceMonitor with diskSpace in configuration as code

Improvements in node monitoring (agents and the controller) include a change in the configuration as code definition for nodeMonitors.
Jenkins LTS 2.426.3 and earlier used diskSpaceMonitor to configure the free space threshold for agents.
Jenkins LTS 2.440.1 and later use diskSpace to configure the free space threshold for agents.

If diskSpaceMonitor is used in Jenkins 2.440.1 and later, a warning message is displayed that says:

[source]
----
Configuration as Code obsolete file format:
    'diskSpaceMonitor' is obsolete, please use 'diskSpace'
----

Replace the 'diskSpaceMonitor' entry with 'diskSpace' to resolve the warning.
