NOTE: These upgrade are not specific to the 2.440.2 release, but are crucial for Jenkins users.

==== OpenJDK Upgrade

Due to a recent change in the upstream OpenJDK, users may encounter a breaking change if they do not upgrade and restart their Java processes.
When upgrading the Java runtime to OpenJDK 11.0.22 and later or 17.0.10 and later, you must restart the Java process.
This practice applies to both controllers and agents: when upgrading the Java runtime on the controller, restart the Java process on the controller; when upgrading the Java runtime on the agent, restart the Java process on the agent.

==== Jakarta Plugin Upgrades

Users that have the plugin:jakarta-mail-api[Jakarta Mail API] and plugin:jakarta-activation-api[Jakarta Activation API] plugins installed in their Jenkins instance must update both plugins to the latest version in lockstep.
If the link:https://github.com/jenkinsci/jakarta-mail-api-plugin/releases/tag/jakarta-mail-api-2.1.3-1[Jakarta Mail] and link:https://github.com/jenkinsci/jakarta-activation-api-plugin/releases/tag/jakarta-activation-api-2.1.3-1[Activation] API plugins are not updated subsequently this will cause a breaking change.
As with any update or upgrade we advise link:/doc/book/system-administration/backing-up/[backing up] your instance and upgrading all plugins before and after you update Jenkins.