==== Upgrade Commons FileUpload from 1.5 to 2.0

The Apache Commons FileUpload library that Jenkins uses for file upload has been upgraded from 1.5 to 2.0 in preparation for the Spring Security 6.x upgrade.
Users of the SAML Single Sign On (SSO) (`miniorange-saml-sp`) plugin should upgrade to a compatible version in lockstep with upgrading Jenkins core.
Users of the OpenText Application Automation Tools (`hp-application-automation-tools-plugin`) plugin should wait for a compatible version before upgrading Jenkins core.

==== Remove Windows path traversal escape hatch

The `hudson.model.DirectoryBrowserSupport.allowAbsolutePath` system property that allows the Windows path traversal vulnerability escape hatch has been removed.
Users that rely on it will need to adapt their usage to no longer require the Windows path traversal vulnerability.
No other workaround is planned.
Refer to link:https://www.jenkins.io/security/advisory/2021-10-06/#SECURITY-2481[SECURITY-2481] for details.

==== Remove Winstone support for multiple WAR files

The `webappsDir` argument to run Winstone with a directory full of WAR files has been removed without replacement.
