==== Yahoo! UI disabled by default

The Yahoo! User Interface library (YUI) is now disabled by default in Jenkins.
There have been several pull requests created towards this goal, with work being done over several years by multiple contributors.
Additionally, elements of Jenkins that were originally built with YUI have been replaced with alternatives to help ensure there is no loss of functionality.

If you need to re-enable YUI in your Jenkins environment, you must set the following system property:

`-Djenkins.model.experimentalflags.RemoveYuiUserExperimentalFlag.defaultValue="false"`

Full removal of YUI will occur in a later LTS release, providing time for users to configure their environments accordingly.

==== Removing configurability of Jenkins agent protocols list

The list of agent protocols is no longer configurable through the GUI or the Configuration as Code (JCasC) plugin.
Going forward, there are two protocols: one for inbound TCP agents and a ping protocol used to test connectivity.
The `agentProtocols` section of a JCasC bundle should be deleted because it will now be ignored.
If you do not wish to allow inbound TCP agents, disable the port instead of the protocol.
