==== Yahoo! UI removed from Jenkins

As of Jenkins 2.504.1, Yahoo! UI (YUI) has been removed from Jenkins core.
This was initially removed in the weekly 2.493 release and is the result of work done over multiple years.
Plugins that had previously used YUI must remove its usage accordingly.
Thanks to all of the work from core and plugin maintainers and contributors, there has been great progress made to ensure that components have been updated.
The list of plugins can be found in our link:https://docs.google.com/spreadsheets/d/1UjvtFmNmEdjMN5DUoFxJfBryA8q-E5_HwOzVKbVG9b0/edit?gid=969462704#gid=969462704[tracking sheet].
At this time, there are only a few plugins with over 800 installs, not planned for deprecation, that have not removed YUI from their configuration.
These plugins are:

* link:https://issues.jenkins.io/browse/JENKINS-73542[AWS Lambda]
* link:https://issues.jenkins.io/browse/JENKINS-73543[SLOCCount]
* link:https://github.com/jenkinsci/openstack-cloud-plugin/issues/389[OpenStack Cloud]
* link:https://github.com/jenkinsci/fortify-on-demand-uploader-plugin/issues/165[Fortify on Demand]

There are other plugins, all under 700 installs, that have issues created for them in the Jenkins issue tracker, linked to the overall link:https://issues.jenkins.io/browse/JENKINS-73539[YUI removal epic].

==== Remove jCIFS and j-Interop

Originally, j-Interop existed so that Jenkins can be installed as a service through the Jenkins UI.
However, this functionality should not be used and has been removed accordingly.
Instead, users should manage installations using the Windows installer.

The jCIFS library has been removed as it was outdated and no longer maintained.
It's sole purpose was only to support launching Windows agents via DCOM, which no longer works with currently supported Windows versions.

Therefore, these have been removed in order to keep up with current support and recommended best practices.
Users wanting this functionality should instead link:/download/[download and install] the MSI package.