==== Configuration as code entry for 'myViewsTabBar' is deprecated.

As of 2.528.1, the configuration as code entry for 'myViewsTabBar' has been deprecated.
In its place, a new user property has been introduced that makes it possible for a user to override what is configured for the global dashboard or a folder.
This will be seen as the Views Tab Bar in Jenkins UI.
Instead of the 'myViewsTabBar', users can now select one of the implementations of 'ViewsTabBar' to be used for the My Views dashboard.
The default view on the *My Views* configuration is a selectable option instead of checking if the user enters a valid view name.

==== Update Debian from Bookworm to Trixie

With the release of 2.528.1, the container images based on Debian are now using Debian 13 ("Trixie") instead of Debian 12 ("bookworm").
The upgrade to Trixie includes performance improvements, upgrades to Linux kernel 6.12 LTS for enhanced performance and hardware support, and adds native support for the Ryk V64 architecture.
Please keep this in mind when using any Debian based Jenkins images and report any issues you come across in the link:https://github.com/jenkinsci/docker/issues[Jenkins Docker issue tracker].

==== Timestamper plugin update

If you have the plugin:timestamper[Timestamper] plugin installed, it must be upgraded to the link:https://plugins.jenkins.io/timestamper/releases/[latest version] before upgrading to Jenkins LTS 2.528.1.
If the plugin is not updated prior to the Jenkins upgrade, you may encounter issues withe the plugin compatability and dependencies.
If you mistakenly update to Jenkins 2.528.1 before updating the plugin, you will need to revert to the previous Jenkins version and update the Timestamper plugin before you can upgrade Jenkins again.
