==== Unified RPM package for Red Hat and openSUSE

Red Hat and openSUSE have the same RPM packages from the same unified repository at link:https://pkg.jenkins.io/rpm-stable/[https://pkg.jenkins.io/rpm-stable/].
Users with an already installed prior version are transparently redirected when refreshing their repositories: https://pkg.jenkins.io/redhat-stable/ and https://pkg.jenkins.io/opensuse-stable/ both redirect to the new URL.

The old repositories are retained and allow older versions (before 2.541.1) to be installed
by using the following URLs: https://pkg.jenkins.io/redhat-stable-legacy/ for Red Hat distributions and https://pkg.jenkins.io/opensuse-stable-legacy/ for openSUSE distributions.

Note for openSUSE users: the System V initialization scripts are removed for openSUSE installations (details in the link:/blog/2022/03/25/systemd-migration/[blog post]).

==== New GPG signing key for Linux packages

Linux packages (RPM and DEB) are signed with a new GPG key.
Administrators need to accept the new signing key when upgrading.
