==== MSI Installer Signing Certificate

Beginning with Jenkins LTS 2.555.2 and Jenkins weekly 2.562, the Jenkins MSI installer is signed by "LF Open Source, LLC" using the Microsoft Artifact Signing Service.

The change may cause the Edge browser on Windows to report that the file is not commonly downloaded.
Users need to select "Keep anyway" to download the installer.

When running the Jenkins MSI installer with the new signature, Windows SmartScreen may report:

[quote, Microsoft Defender SmartScreen]
Microsoft Defender SmartScreen prevented an unrecognized app from starting.
Running this app might put your PC at risk.

Users need to select "More info" to advance to the next screen and then select "Run anyway".

A link:/blog/2026/04/29/windows-installer-signing-change/[blog post] provides screenshots and more details.

The Microsoft link:https://learn.microsoft.com/en-ca/answers/questions/5861981/blocked-by-windows-defender-smartscreen[support forum] says that Microsoft SmartScreen will stop prompting users once there are enough installations to increase its reputation score.
