==== Java 8 Required

Jenkins 2.60.1 is the first LTS release to require Java 8.
This applies to both master and agents.

If you're using the Maven Plugin for your Maven-based builds, note that the JDK selected for them needs to be at least Java 8 as well with this change.
If an older JDK is configured, Jenkins will attempt to find a more recent JDK automatically.
If your Maven projects need to be built with JDK 7, consider converting them to freestyle projects, or look into Maven toolchains.

If you're using the plugin:ssh-slaves[SSH Build Agents] plugin, it may attempt to start the agent process on an unsupported JRE, which will fail.
If this happens, make sure to install a supported JRE (8 or newer) on the agent system and make it available on the PATH.
If you rely on SSH Build Agents plugin to automatically install a Java runtime on the agent, delete the existing one inside the agent root directory after upgrading to SSH Build Agents 1.17 or newer (1.20 recommended, see below).

==== Groovy 2.4.8 Upgrade

https://issue-redirect.jenkins.io/issue/33358[JENKINS-33358],
https://issue-redirect.jenkins.io/issue/42189[JENKINS-42189]

Groovy has been upgraded to 2.4.8 to fix a memory leak.

If you're using Pipeline, note that you will need to update the plugin:workflow-cps[Pipeline: Groovy] plugin to version 2.28 or later.

==== Trilead SSH Library Upgrade

https://issue-redirect.jenkins.io/issue/42959[JENKINS-42959]

The Trilead SSH library bundled with Jenkins has been upgraded.
If you're using the SSH slaves plugin to connect agents via SSH, a known issue resulting from that upgrade can result in connection failures.

The plugin:ssh-slaves[SSH Slaves] plugin should be upgraded to version 1.20 or newer.

==== RPM Packaging No Longer Performs Recursive `chown`

https://issue-redirect.jenkins.io/issue/23273[JENKINS-23273]

The RPM packaging post-install step used to perform a recursive `chown` on `JENKINS_HOME` and other directories to ensure correct ownership.
Especially in the case of `JENKINS_HOME` this could lead to very long-running installations and updates.

This has been optimized to only perform the recursive `chown` if the Jenkins home directory is owned by a different user than the one the service would be running as.

NOTE: All files inside `JENKINS_HOME` are expected to be owned, readable, and writable by the Jenkins user.

==== Windows Services Upgrade

https://issue-redirect.jenkins.io/issue/39231[JENKINS-39231],
https://issue-redirect.jenkins.io/issue/39237[JENKINS-39237]

Jenkins 2.60.1 includes major improvements in Windows Service management, which were introduced from Jenkins 2.50 to 2.60.
In particular, link:https://github.com/kohsuke/winsw[Windows Service Wrapper (WinSW)] has been updated to the 2.x baseline.

Newly installed agent and master instances will get the features automatically, but existing instances require additional configuration.

See link:windows[Upgrading Windows masters and agents] for more details.
