
==== Low-privilege users may not be able to reconfigure some agents anymore

link:/security/advisory/2017-10-11/[SECURITY-478]

The launch method _Launch agent via execution of command on master_ did not properly check the permission to run commands of the configuring user.
This has been fixed, and this launch method can now only be configured by Jenkins administrators (or, more specifically, users with the _Run Scripts_ permission).

A known limitation of this fix is that users without the _Run Scripts_ permission (typically everyone who isn't an administrator) are no longer able to configure agents with this launch method at all, even if the launch method and the script remain unchanged.


==== Restrictions to remote API output

link:/security/advisory/2017-10-11/[SECURITY-514, SECURITY-611, SECURITY-617, SECURITY-618]

Multiple remote API endpoints had the content they provide restricted.
More detailed information can be found in the security advisory linked above.

* All _user properties_ got removed from `/user/(username)/api/` and other APIs returning users except when accessed by administrators or the users themselves.
* APIs returning queue items and tasks (builds) now only return them when requested by users with read permission for them.
* The `/queue/item/(ID)/api/` is now only accessible by users with read permission for the specified item.


==== Fixes for regressions in 2.73.1

link:https://issue-redirect.jenkins.io/issue/45755[JENKINS-45755],
link:https://issue-redirect.jenkins.io/issue/46754[JENKINS-46754]

The regressions in 2.73.1 listed below have been fixed in 2.73.2.
