==== Command Launcher Plugin

link:https://issue-redirect.jenkins.io/issue/47393[JENKINS-47393],
link:https://issue-redirect.jenkins.io/issue/48365[JENKINS-48365],
link:https://issue-redirect.jenkins.io/issue/47593[JENKINS-47593]

The launch method _Launch agent via execution of command on the master_ has been moved to a new _Command Launcher_ plugin and integrated with the _Script Security_ plugin.

Two potential problems have been identified with this change:

* Jenkins does not automatically install the plugin when upgrading from before Jenkins 2.86 to that version or newer. This includes an upgrade to 2.89.1 from any earlier LTS release. The plugin will need to be installed manually after an update. If it appears to be unavailable on the update center, make sure to update the cached metadata by clicking _Check Now_.
* The integration with Script Security can result in problems with plugins making use of this launch method internally in a way that is incompatible with the security model of Script Security. A known instance of this problem is EC2 Plugin. The issue is tracked as link:https://issue-redirect.jenkins.io/issue/47593[JENKINS-47593].
