name: '📝 Documentation'
labels: 'documentation'
description: 'Let us know if any documentation is missing or could be improved'

body:
  - type: textarea
    attributes:
      id: suggestion
      label: Describe your use-case which is not covered by existing documentation.
      description: If it is easier to submit a documentation patch instead of writing an issue, just do it!
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Are you interested in contributing a fix?
      description: Indicate if this is something you would like to work on, and how we can best support you in doing so. More details [on contributing](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc)
