name: '🚀 Website enhancement'
labels: 'enhancement'
description: 'I have a suggestion how to improve the website (and may want to implement it 🙂)!'

body:
  - type: textarea
    attributes:
      id: suggestion
      label: Suggestion
      description: A clear and concise description of what the problem is. Ex. `I have an issue when [...]`, `As a Jenkins user, I want to [...]
    validations:
      required: true
  - type: textarea
    attributes:
      id: links
      label: Links
      description: Link any related documentation pages and other materials.
      placeholder: |
        * Links 1
    validations:
      required: false
  - type: textarea
    attributes:
      label: Are you interested in contributing to this improvement?
      description: Indicate if this is something you would like to work on, and how we can best support you in doing so. More details [on contributing](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc)
