name: '🐛 Bug report'
labels: 'bug'
description: 'Create a bug report for the website'

body:
  - type: input
    id: problem
    attributes:
      label: Problem with this page
      description: The page URL you encounter issues on.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Describe what actually happened.
    validations:
      required: true
  - type: textarea
    id: possible-solution
    attributes:
      label: Possible solution
      description: If you have suggestions on a fix for the bug, please describe it here.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Are you interested in contributing a fix?
      description: Indicate if this is something you would like to work on, and how we can best support you in doing so. More details [on contributing](https://github.com/jenkins-infra/jenkins.io/blob/master/CONTRIBUTING.adoc)
