blank_issues_enabled: false
contact_links:
  - name: Mailing list
    url: https://groups.google.com/forum/#!forum/jenkinsci-docs
    about: Jenkins Documentation SIG mailing list
  - name: Gitter chat
    url: https://gitter.im/jenkinsci/docs
    about: Jenkins Documentation SIG chat
