---
layout: simplepage
title: Jenkins Update Sites
uneditable: true
---

== Default Update Site

This is the default Jenkins update site.
It is configured by default on every Jenkins instance.
Its content is periodically generated by https://github.com/jenkins-infra/update-center2/[jenkins-infra/update-center2].

=== Configuration

To configure this default update site in Jenkins, specify `+https://updates.jenkins.io/update-center.json+` in _Manage Jenkins » Plugins » Advanced_.

This file serves JSONP despite the file name. See `+https://updates.jenkins.io/update-center.actual.json+` for the JSON variant, and https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md[Site Layout] for an explanation of the different files and directories available on this site.

=== Version-Specific Update Sites

Jenkins adds a query parameter `?version` to the update site URL.
This lets the update site offer plugin releases compatible with your version of Jenkins.
At the moment, Jenkins weekly and LTS releases up to a year old are supported; anything older will receive update metadata for the oldest supported releases.

See https://github.com/jenkins-infra/update-center2/tree/master/site[Jenkins Update Center Site Architecture] for more information.

== Experimental Plugin Site

The experimental plugin site is located at https://updates.jenkins.io/experimental/[https://updates.jenkins.io/experimental/].
Configure `+https://updates.jenkins.io/experimental/update-center.json+` in Jenkins to receive experimental releases (those with `alpha` or `beta` in their version numbers).

See link:/doc/developer/publishing/releasing-experimental-updates/[Publishing Experimental Plugin Releases] for more information.

This update site always serves the latest releases, which may be incompatible with your version of Jenkins.

////
TODO Should we continue to advertise this?
== Mirroring

You can rsync these files via `rsync -avz rsync://rsync.osuosl.org/jenkins/updates/` somewhere.
////

== Other Notable Content

* https://updates.jenkins.io/download/[Index of all releases of Jenkins core and plugins]
* https://updates.jenkins.io/latest/[Latest releases of jenkins.war and all plugins] (also in version-specific update sites)
* https://updates.jenkins.io/updates/[Tool installer metadata] (also in version-specific update sites)

See https://github.com/jenkins-infra/update-center2/blob/master/site/LAYOUT.md[Site Layout] for a complete reference of the files and directories available on this site.

Many of the files on this site are intended for internal use by the Jenkins project and may change at any time.
