---
layout: section
title: Blue Ocean Frequently Asked Questions
---
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:imagesdir: /doc/book/resources
:hide-uri-scheme:

= Blue Ocean Frequently Asked Questions

== Why does Blue Ocean exist?

The world has moved on from developer tools that are purely functional to
developer tools being part of a "developer experience". That is to say, it's no
longer about a single tool but the many tools developers use throughout the day
and how they work together to achieve a workflow that's beneficial for the
developer - this is Developer Experience.

Developer tools companies like Heroku, Atlassian and Github have raised the bar
for what is considered good developer experience, and developers are
increasingly expecting exceptional design. In recent years developers are
becoming more rapidly attracted to tools that are not only functional but are
designed to fit into their workflow seamlessly and are a joy to use. This shift
represents a higher standard of design and user experience that Jenkins needs
to rise to meet.

Creating and visualising continuous delivery pipelines is something valuable
for many Jenkins users and this is demonstrated in the 5+ plugins that the
community has created to meet their needs. To us this indicates a need to
revisit how Jenkins currently expresses these concepts and consider delivery
pipelines as a central theme to the Jenkins user experience.

It's not just continuous delivery concepts but the tools that developers use
every day – Github, Bitbucket, Slack, HipChat, Puppet or Docker. It's about
more than Jenkins – it's the developer workflow that surrounds Jenkins that
spans multiple tools.

New teams have little time for learning to assemble their own Jenkins
experience – they want to improve their time to market by shipping better
software faster. Assembling that ideal Jenkins experience is something we can
work together as a community of Jenkins users and contributors to define. As
time progresses, developers' expectations of good user experience will change
and the mission of Blue Ocean will enable the Jenkins project to respond.

The Jenkins community has poured its sweat and tears into building the most
technically capable and extensible software automation tool in existence. Not
doing anything to revolutionize the Jenkins developer experience today is just
inviting someone else – in closed source – to do it.

== Where is the name from?

The name Blue Ocean comes from the book
link:https://en.wikipedia.org/wiki/Blue_Ocean_Strategy[Blue Ocean Strategy]
where instead of looking at strategic problems within a contested space you
look at problems in the larger uncontested space. To put this more simply,
consider this quote from ice hockey legend Wayne Gretzky: "skate to where the
puck is going to be, not where it has been".

=== Does Blue Ocean support Freestyle jobs?

Blue Ocean aims to deliver a great experience around Pipeline and be compatible
with any Freestyle jobs that you have configured in your system. However, they
won't be able to benefit from any of the features built for Pipelines – for
example, Pipeline visualization.

As Blue Ocean is designed to be extensible it will be possible for the
community to extend it for other job types in the future.

== What does this mean for the classic Jenkins UI?

The intention is that as Blue Ocean matures there will be less and less reasons
for users to go back to the existing UI.

For example, in the first version we will mainly be targeting Pipeline jobs.
You might be able to see your existing non-pipeline jobs in Blue Ocean but it
might not be possible to configure them from the new UI for some time. This
means users will have to jump back to the classic UI for configuration of
non-pipeline jobs.

There are likely going to be more examples of this and that's why the classic
UI will still be important in the long term.

== Is this a CloudBees project?

The short answer is *"no"*. The project has been originated and sponsored by
CloudBees, but it is a *100% open project* (including sources, roadmaps, public
discussions, etc.). Everybody is invited to contribute to it.

To quote link:https://github.com/i386[James Dumay] (Blue Ocean Product Manager
at CloudBees):

____
While the project's inception has happened within CloudBees we see this project
being one owned by the community. At CloudBees we recognize the importance of a
vibrant and healthy Jenkins community, we see the company and community working
in symbiosis: a thriving developer community is good for CloudBees and CloudBees
provides time and money back into the community to make it stronger. Blue Ocean
is our way of giving back and strengthening. To that effect we've put together a
new a team of product, UX, frontend and backend developers (some old faces and a
lot of new ones!) that will be working on this project with the community full
time
____

== What does this mean for my plugins?

Extensibility is a pretty core concept to Jenkins, so being able to extend the
Blue Ocean UI is important. Based on some research, we worked out a way to
allow "<ExtensionPoint name=..>" to be used in the markup of Blue Ocean,
leaving places for plugins to contribute to the UI (plugins can have their own
Blue Ocean extension points, just like they do today in Jenkins). Blue Ocean
itself (as it is so far) is implemented using these extension points.
Extensions are delivered by plugins, as normal, only if they wish to contribute
to the Blue Ocean experience they will have some additional javascript that
provides extensions.

== What technologies are currently in use?

Blue Ocean is built as a collection of Jenkins plugins itself. There is one key
difference, however. It provides both its own endpoint for http requests and
delivers up html/javascript via a different path, without the existing Jenkins
UI markup/scripts. React.js and ES6 are used to deliver the javascript
components of Blue Ocean. Inspired by this excellent open source project
(link:https://nylas.com/blog/react-plugins[react-plugins]) an <ExtensionPoint>pattern was
established, that allows extensions to come from any Jenkins plugin (only with
Javascript) and should they fail to load, have failures isolated.

== Where can I find the source code?

The source code can be found on Github:

* link:http://github.com/jenkinsci/blueocean-plugin[Blue Ocean]
* link:http://github.com/jenkinsci/jenkins-design-language[Jenkins Design Language]
