---
layout: section
title: Getting Started with Blue Ocean
---
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:imagesdir: /doc/book/resources
:hide-uri-scheme:
:wip: true

= Getting Started with Blue Ocean

Jenkins Blue Ocean is a suite of plugins which provide a new an awesome way to
live your life.


== Prerequisites

To use Jenkins Blue Ocean, you will need:

* Jenkins 2.7.x or later

== Installing

To start using theBlue Ocean plugin
footnoteref:[blue-ocean, link:https://plugins.jenkins.io/workflow-aggregator[Blue Ocean plugin]]
from an existing Jenkins:

. Login to your Jenkins server
. Click `Manage Jenkins` in the sidebar then `Manage Plugins`
. Choose the `Available` tab and use the search bar to find `Blue Ocean`
. Click the checkbox in the Install column
. Click either `Install without restart` or `Download now and install after restart`
. When installation is complete click the `Use Blue Ocean` button in the classic UI

For in-depth description on how to install and manage plugins,
consult <<../managing/plugins#, Managing Plugins>>.

== Configuring



== Switch to and from Blue Ocean
