---
layout: section
title: Starting with Blue Ocean
---
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:imagesdir: /doc/book/resources
:hide-uri-scheme:

= Starting with Blue Ocean

This section will show how to start using Blue Ocean.
It will include instructions for installing and configuring the Blue Ocean plugin,
and how to get switch into and out of the Blue Ocean UI.

== Prerequisites

To use Jenkins Blue Ocean, you will need:

* Jenkins 2.7.x or later

All other dependencies of Blue Ocean are installed automatically.

== Installing

Blue Ocean can be installed on an existing Jenkins instance or you can try it out
in a separate Docker container.

[NOTE]
====
The majority of Blue Ocean requires no additional configuration after installation.
Existing Pipelines and Jobs will continue to work as usual.
However, the first time a <<#creating-pipelines, Pipeline is created>,
Blue Ocean will ask for permissions to access your repositories (either Git or GitHub)
in order to create pipelines based on those repositories.
====

=== On Jenkins

To start using the
plugin:blue-ocean[Blue Ocean plugin] on an existing Jenkins instance:

. Login to your Jenkins server
. Click `Manage Jenkins` in the sidebar then `Manage Plugins`
. Choose the `Available` tab and use the search bar to find `Blue Ocean`
. Click the checkbox in the Install column
. Click either `Install without restart` or `Download now and install after restart`

For in-depth description on how to install and manage plugins,
consult <<managing/plugins#, Managing Plugins>>.

=== On Docker

There is a Docker container that is continuously updated with the
latest Blue Ocean and Jenkins LTS releases.

To start a new Jenkins with Blue Ocean installed:
. Install Docker
. Run docker run -p 8888:8080 jenkinsci/blueocean:latest
. Browse to http://localhost:8888/blue

This will be an clean Jenkins instance with Blue Ocean and Pipeline installed.


== Switching to the Blue Ocean UI

After installing, you can switch to the Blue Ocean by click on "Open Blue Ocean"
in the middle of the top bar on the Jenkins web UI.

//TODO:Image

== Switching to Classic Jenkins

If you need to switch back to the Classic Jenkins UI, you can do so using the button
in the upper right corner of the screen.

//TODO:Image

Some links in Blue Ocean, like "Administration", will also navigate to the
classic Jenkins UI, when there is no Blue Ocean equivalent yet.  In those cases,
Blue Ocean will switch to the classic UI automatically as needed.

[[creating-pipelines]]
== Creating Pipelines

To create a new Pipeline using Blue Ocean,
click on "New Pipeline" in the upper right of the Blue Ocean Dashboard.
This will start the Pipeline creation process.
Blue Ocean currently supports creating Pipelines from Git or GitHub.

=== Git


=== GitHub
