---
layout: developersection
title: Add more spotbugs checks
---

:modified-files: pom.xml
:task-identifier: add-spotbugs-checks
:task-description: Increase spotbugs effort and threshold

= Add more spotbugs checks

.Add more thorough spotbugs checks
video::2c8wK2jkcIA[youtube,width=800,height=420,start=255]

The Jenkins plugin pom enables static analysis with link:https://spotbugs.github.io/[spotbugs].
Plugin maintenance can be improved in some cases by increasing the depth of spotbugs analysis.

// Create the branch
include::doc/developer/tutorial-adopt/_create-a-branch.adoc[]

== Increase spotbugs checks

To increase the spotbugs analysis checks, add the three spotbugs properties entries in the properties section of the `pom.xml` file:

```
   <properties>
     <jenkins.version>PLACEHOLDER_RECENT_LTS_POINT_HIGH</jenkins.version>
+    <spotbugs.effort>Max</spotbugs.effort>
+    <spotbugs.failOnError>true</spotbugs.failOnError>
+    <spotbugs.threshold>Low</spotbugs.threshold>
   </properties>
```

== Review and fix spotbugs warnings

When the spotbugs analysis checks are increased, they often report new issues that need to be resolved or suppressed.
Spotbugs checks are included in the Apache Maven `verify` step.
Run the spotbugs analysis checks as part of the Apache Maven `verify` step with the command:

```
$ mvn clean -DskipTests verify
```

It is generally preferred to fix a spotbugs warning rather than suppress the warning message.
However, in those cases where a spotbugs message is incorrect or is infeasible to fix, it can be suppressed with the `SuppressFBWarnings` annotation.
A suppression might look like this:

```java
import edu.umd.cs.findbugs.annotations.SuppressFBWarnings;
/* ... preceding a method that returns a Boolean and may return null */
    @SuppressFBWarnings(
            value = "NP_BOOLEAN_RETURN_NULL",
            justification = "Null return indicates others should evaluate further")
```

// Create a pull request
include::doc/developer/tutorial-adopt/_create-a-pull-request.adoc[]
