---
layout: developersection
title: Update parent pom
---

:task-identifier: update-parent-pom
:task-description: Use most recent parent pom

= Update parent pom

.Use more recent parent pom
video::Fev8KfFsPZE[youtube,width=800,height=420,start=807]

The Maven project object model ("pom") defines a parent project object model that provides default settings.
An update of the parent pom will allow this plugin to compile with Java 11 and will allow other improvements.

// Create the branch
include::doc/developer/tutorial-adopt/_create-a-branch.adoc[]

== Compile the plugin

Use Apache Maven to compile the plugin.

[source,bash]
----
$ mvn -ntp clean verify
----

If you are using Java 11, you may need to use Java 8 to compile the plugin initially.
Once the parent pom has been updated, you'll be able to compile and test with Java 11.

== Update plugin parent pom

Use Apache Maven to update the parent pom:

[source,bash]
----
$ mvn -ntp versions:update-parent
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.jenkins-ci.plugins:schedule-build >----------------
[INFO] Building Schedule Build Plugin 1.0.0-SNAPSHOT
[INFO] --------------------------------[ hpi ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.8.1:update-parent (default-cli) @ schedule-build ---
[INFO] Updating parent from 3.50 to 4.27
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.013 s
[INFO] Finished at: 2021-09-26T20:03:00-06:00
[INFO] ------------------------------------------------------------------------
----

Review the change that Apache Maven performed for you with the command:

[source,bash]
----
$ git diff
diff --git a/pom.xml b/pom.xml
index e6a8356..3a42d47 100644
--- a/pom.xml
+++ b/pom.xml
@@ -3,7 +3,7 @@
   <parent>
     <groupId>org.jenkins-ci.plugins</groupId>
     <artifactId>plugin</artifactId>
-    <version>3.50</version>
+    <version>4.27</version>
   </parent>

   <artifactId>schedule-build</artifactId>
----

Compile the updated code with the command:

[source,bash]
----
$ mvn clean verify
----

In many cases, other changes will be needed to the pom.xml file in order to use the most recent parent pom.
Some of the changes that may be required when updating the plugin pom may include:

* Resolve spotbugs warnings
* Resolve link:/doc/developer/plugin-development/updating-parent/#understanding-requireupperbounddeps-failures-and-fixes[upper bounds dependency warnings]
* Prevent cross-site scripting by link:/doc/developer/security/xss-prevention/[escaping expressions in Jelly pages]

// Create a pull request
include::doc/developer/tutorial-adopt/_create-a-pull-request.adoc[]
