---
layout: developersection
title: Use plugin bill of materials for easier dependency management
---

:task-identifier: use-plugin-bill-of-materials
:task-description: Use plugin bill of materials for easier dependency management

.Simplify dependency management with the plugin bill of materials

video::pk1gweLvcEI[youtube,width=800,height=420,start=1749]

Updating the versions of plugin dependencies can be a very frustrating search for the set of versions that work with each other and do not cause upper-bounds dependency error reports.
The link:https://github.com/jenkinsci/bom#bill-of-materials-for-jenkins-plugins[Jenkins plugin bill of materials] simplifies that by shifting the evaluation of versions from each plugin author to a centralized process maintained by members of the Jenkins community.

// Create the branch
include::doc/developer/tutorial-adopt/_create-a-branch.adoc[]

== Use the plugin bill of materials

Add a `dependencyManagement` section to the `dependencies` section of the pom file that references the link:https://github.com/jenkinsci/bom/releases[most recent version] of the plugin bill of materials for that line.
For example, the addition might look like:

----
<dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.jenkins.tools.bom</groupId>
            <artifactId>bom-2.289.x</artifactId>
            <version>1075.v14bef33e5d7b</version>
            <scope>import</scope>
            <type>pom</type>
        </dependency>
    </dependencies>
</dependencyManagement>
----

Remove as many `<version>` declarations from the pom file as you can while still compiling successfully.

Compile the updated code with the command:

[source,bash]
----
$ mvn clean verify
----

// Create a pull request
include::doc/developer/tutorial-adopt/_create-a-pull-request.adoc[]
