---
layout: post
title: "Automatic Plugin Documentation"
tags:
- jenkins
- gsoc
- plugins
author: cynthia
---
=== About me 
I am Cynthia Anyango from Nairobi , Kenya . I am a second yeat student at Maseno University . I am currently specializing on Ruby on Rails and trying to learn Python . I recently started contributing to Open source projects . My major contribution was at Mozilla , where I worked with the QA for Cloud services . I did manual and automated tests for various cloud services  . I wrote documentation too . Above that , I am competent and I am always passionate about what I get my hands on . 
 	
=== Project summary 

Currently Jenkins has plugin documentation is being stored in Confluence. Sometimes the documentation is scattered and outdated. In order to improve the situation we would like to follow the documentation-as-code approach and to put docs to plugin repositories and then publish them on the project website using the awestruct engine. The project aims an implementation of a documentation continuous deployment flow powered by Jenkins and Pipeline Plugin.

The idea is to automatically pull in the README and other docs from GitHub, show changelogs with versions and releases dates . I will be designing file templates that will contain most of the  docs information that will be required from plugin developers . The file templates will be written in ASCIIDOC .  Plugin developers will get a chance to review the templates. The templates will be prototyped by various plugin developers . 

The docs that will be automatically pulled from github and will be published on link:https://jenkins.io/[Jenkins.io] under the Documentation section . 

My mentors are link:https://wiki.jenkins-ci.org/display/~rtyler[R.Tyler] and https://wiki.jenkins-ci.org/display/~batmat[Baptiste Mathus]

I hope to achieve this by 25th June when we will be having our mid-term evalluations . 

I will update more on the progress . 

=== Links 

* link:https://summerofcode.withgoogle.com/dashboard/project/5120513768685568/details/[Gsoc Page]
* link:https://wiki.jenkins-ci.org/display/JENKINS/Google+Summer+Of+Code+2016[Jenkins Gsoc Page ]
* link:https://groups.google.com/forum/#!topic/jenkinsci-dev/kNZMOsF_ueA[Mailing List discussion on Jenkins-Developers]