---
layout: post
title: Jenkins joins the Google Summer of Code 2016
tags:
  - general
  - jenkins2
  - gsoc
author: oleg_nenashev
---
We are happy to announce that Jenkins project application has been accepted to
https://developers.google.com/open-source/gsoc/timeline[Google Summer of Code 2016] (GSoC). Thanks
to everybody who helped prepare the application and submitted project ideas!

We would like to invite students to join the Jenkins community and work together
on the ongoing link:/2.0[Jenkins 2.0] activities and other medium-term projects.

The student projects we are primarily interested in would improve the overall
Jenkins user experience in a number of different aspects. This includes user
interface changes and stability improvements but also major new features such
as https://wiki.jenkins.io/display/JENKINS/2.0+Pipeline+as+Code[Pipeline as code].

The projects we've suggested revolve around all parts of the Jenkins project:
core, plugins, website and our internal automation infrastructure. More details
on what has been suggested can be found https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Projectideas[on the
wiki]
which include:

* Jenkins web interface improvements
* "Update Center 2.0"
* New generation of the fingerprinting engine
* External workspace manager
* Integration of link:/solutions/docker/[Docker plugins] with Jenkins 2.0 features
* Plugins for Electronic Design Automation and Embedded tools integration
* Improvements of the https://wiki.jenkins.io/display/JENKINS/Support+Core+Plugin[Support] plugin
* Improvements to Jenkins project infrastructure: core infra, website, plugin documentation and more

== If you are a student:

. Check out the project ideas https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Projectideas[here].
. Select an interesting project idea or draft your own proposal.
. If you are not familiar with Jenkins, we highly recommend trying it out with one of your previous projects. You can also try available Jenkins features from the https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Projectideas[project ideas].
. Introduce yourself the community and start your project proposal discussion (see the guidelines https://summerofcode.withgoogle.com/organizations/5668199471251456/[here]).
. Join us at https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016#GoogleSummerOfCode2016-Forinterestedstudents[GSoC office hours]. We plan to have two meetings starting on March 7th.

== If you want to be a mentor:

* Feel free to team up with other mentors
* We accept extra project proposals from mentors until March 9th.

== Links

* https://summerofcode.withgoogle.com/organizations/5668199471251456/[Jenkins project page] on the GSoC2016 website
* https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016[GSoC2016 page] on our wiki
* https://twitter.com/jenkinsci/status/704384831124209664[Announcement in Twitter]
