---
layout: post
title: "GSoC: External Workspace Manager for Pipeline is released"
tags:
- pipeline
- plugins
- external-workspace-manager
- gsoc
author: alexsomai
---

This blog post is the last one from the series of
link:https://summerofcode.withgoogle.com/[Google Summer of Code] 2016, External Workspace Manager Plugin project.
The previous posts are:

* link:/blog/2016/05/23/external-workspace-manager-plugin/[Introductory blog post]
* link:/blog/2016/06/30/ewm-alpha-version/[Alpha release announcement]
* link:/blog/2016/08/09/ewm-beta-version/[Beta release announcement]

In this post I would like to announce the 1.0.0 release of the External Workspace Manager Plugin version to the main
update center.

Here's a highlight of the available features:

* Workspace share and reuse across multiple jobs, running on different nodes
* Automatic workspace cleanup
* Provide custom workspace path on the disk
* Disk Pool restrictions
* Flexible Disk allocation strategies

All the above are detailed, with usage examples, on the plugin's
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/README.md[documentation page].

=== Future work

Currently, there is work in progress for the _workspace browsing_ feature (see pull request
link:https://github.com/jenkinsci/external-workspace-manager-plugin/pull/37[#37]).
Afterwards, I'm planning to integrate fingerprints, so that the user can view a specific workspace in which
other jobs was used.
A particular feature that would be nice to have is to integrate the plugin with at least one disk provider
(e.g. Amazon EBS, Google Cloud Storage).

Many other features and improvements are still to come, they are grouped in the phase 3 EPIC:
link:https://issue-redirect.jenkins.io/issue/37543[JENKINS-37543].
The plugin's repository is on link:https://github.com/jenkinsci/external-workspace-manager-plugin[GitHub].
If you'd like to come up with new features or ideas, contributions are very welcome.

=== Closing

This was a Google Summer of Code 2016 project.
A summary of the contributions that I've made to the Jenkins project during this time may be found
link:https://alexsomai.github.io/gsoc-2016/[here].
It was a great experience, from which I learned a lot, and I'd wish I could repeat it every year.

I'd like to thank to my mentors, link:https://github.com/oleg-nenashev[Oleg Nenashev] and
link:https://github.com/martinda[Martin d'Anjou] for all their support, good advice and help they gave me.
Also, thanks to the Jenkins contributors with which I have interacted and helped me during this period.

If you have any issues in setting up or using the plugin, please feel free to ask me on the plugin's Gitter
link:https://app.gitter.im/#/room/#jenkinsci_external-workspace-manager-plugin:gitter.im[chat].
Any feedback is welcome, and you may provide it either on the Gitter chat, or on
link:https://issues.jenkins.io[Jira] by using the __external-workspace-manager-plugin__ component.

=== Links

link:https://app.gitter.im/#/room/#jenkinsci_external-workspace-manager-plugin:gitter.im[image:https://badges.gitter.im/jenkinsci/external-workspace-manager-plugin.svg[title: "Gitter"]]

* link:https://github.com/jenkinsci/external-workspace-manager-plugin[Project repository]
* link:https://alexsomai.github.io/gsoc-2016/[Work product page]
* link:https://summerofcode.withgoogle.com/[GSoC page]
* link:/projects/gsoc/[Jenkins GSoC Page]
