---
layout: post
title: "Introducing Jenkins Certification"
tags:
- certification
author: fdechery
---

NOTE: This is a guest post by link:https://twitter.com/francoisdechery[Francois
Dechery], he works at CloudBees managing Customer Engagement/Support, Consulting
and Training. He is also leading the Jenkins Certification program at CloudBees
which has been discussed in some of our previous (link:https://meetings.jenkins-ci.org/jenkins/2015/jenkins.2015-08-05-18.00.html[1],
link:https://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-02-17-19.00.html[2],
link:https://meetings.jenkins-ci.org/jenkins-meeting/2016/jenkins-meeting.2016-03-02-19.00.html[3])
link:https://wiki.jenkins.io/display/JENKINS/Governance+Meeting+Agenda[governance
meetings].


In the IT world, namely in software, "certification" is used in many different
ways and for many different purposes. From very simple and light certifications
to very heavy and complex ones. In the "light" category you can usually be
certified on the basis of a short quiz at the end of an online training. At the
other end of the spectrum, certifications are based on a proctored
multiple-choice questionnaire-based exam and/or hands-on labs. In some
industries, certifications are even more demanding. For instance, to become a
Certified Public Accountant in the US, you have to pass a standard examination
and, on top of this, each state/jurisdiction has its own set of education and
experience requirements that individuals must meet.

== Creating the Jenkins certification

When we started our internal discussions at CloudBees regarding a certification
program for Jenkins, we were aware of this broad set of certification
definitions. Therefore, our first goal was to define what type of certification
we wanted to develop and for what purpose. We quickly agreed on the fact that it
should be _a professional-grade certification, whose purpose would be to provide
a professional standard for the Jenkins ecosystem,_ benefiting both individuals
and organizations, thanks to a common, respected and well-known body of
knowledge and practice. "Professional" means that you have the expected level of
skills and experience in order to leverage them in a professional environment,
for example in enterprise projects or as a consultant.

Many members of the CloudBees team have firsthand experience with certification
programs developed in other IT ecosystems such as telecoms (Cisco),
infrastructure (Microsoft, Red Hat) or business applications (SAP), to name a
few. This was definitely the type of professional certification we wanted to
bring to Jenkins. We knew it would represent a substantial investment but we
also knew that the whole Jenkins ecosystem would benefit. Whether at the overall
community or individual level, as well as IT organizations, system integrators
or recruiting firms looking for qualified Jenkins personnel.


I have had the privilege to supervise the creation and implementation of the
link:https://www.cloudbees.com/jenkins-certification[Jenkins Certification Program]
at CloudBees. The program is comprised of two certifications: "Certified Jenkins
Engineer" (CJE) for Jenkins certification, and Certified CloudBees Jenkins
Platform Engineer (CCJPE) for certification on the CloudBees Jenkins Platform.

We started by creating a Certification Advisory Board whose members are:
link:https://github.com/kohsuke[Kohsuke Kawaguchi], Jenkins creator and CTO at
CloudBees; link:https://github.com/harpreetsingh[Harpreet Singh], VP Products at
CloudBees; link:https://github.com/olivergondza[Oliver Gondža], initially
representing the Jenkins community; link:https://twitter.com/jsin[Jason Shawn],
senior director DevOps at Ellucian, representing the CloudBees customer
constituency; and link:https://twitter.com/alvarezjj1[Jose Alvarez],
managing director at Zivra, representing the CloudBees partner ecosystem.

This dedicated group helped us first to create the certification blueprint which
defines the main sections of the exam and their relative importance in the
overall scoring. This blueprint also provides the high-level table of contents
of the certification
link:https://www.cloudbees.com/sites/default/files/cje_study_guide_final.pdf[study guides].
They also helped to define the Jenkins Engineer profile that the certification
assesses.

With this blueprint in hand, we put together a team of 40 Jenkins subject-matter
experts (SMEs), mostly from CloudBees with a few from partners. Together they
worked for several months on the creation of hundreds of exam questions, doing
iterative peer reviews, filtering out any irrelevant or ambiguous questions and
narrowing down the pool of questions to the best questions for each section.
All this, plus a thorough analysis and balancing exercise to make sure the level
of difficulty was evenly distributed across each section of the exam.

The big lesson from the exam creation experience is that creating a
professional-grade exam is hard! And it requires very specific experience. In
short, being a subject-matter expert is definitely not enough and we're glad to
have collaborated with link:https://www.prometric.com/[Prometric]'s
certification specialists who guided us through this process. The result is
definitely worth the effort. Either of the two certifications offered within the
Jenkins Certification Program are truly what we would consider
"professional-grade certifications."


== What does certification get you?

Getting certified means being recognized for your skills and experience as a
Jenkins professional. However, like any exam-based recognition, its actual value
depends on three criteria: the level of difficulty of the exam, its quality and
its integrity.

As far as *difficulty* is concerned, it is clear that not everyone will pass and
that is expected from a professional-grade certification, as mentioned earlier.
We have definitely created an exam that is demanding. It does not only measure
your theoretical knowledge of Jenkins but also your hands-on practical
experience. To ensure its *quality*, we have applied best-industry practices
regarding the exam's creation and review process, working with certification
specialists. It includes the weighing of questions, the distribution of easy,
medium and difficult ones, the removal of any ambiguous wording, as well as
alpha and beta final test procedures, in order to only keep the most appropriate
questions. We are also putting in place a formal maintenance process to capture
any "bug" in the exam and adapt the questions to Jenkins evolutions over time.
Last but not least, we ensure the exam's *integrity* by working with Prometric
for the administration of exams. Tests are taken in fully secured and proctored
test rooms, without any access to any human or electronic resource and
without any doubt about who takes the test. Thanks to Prometric's hundreds
of test centers around the world, this integrity is ensured in any location.

Beyond this external recognition, getting certified is also a process that lets
you take a step back from your day-to-day practice of Jenkins and assess your
skills and knowledge. You start this reassessment process by reading the Study
Guides for the certifications. Then, by taking the test itself, you can identify
your strengths and weaknesses in a very practical way. In short, a certification
gives you a measurable goal to achieve.


Click link:https://www.cloudbees.com/jenkins-certification[here] for more
information on the Jenkins Certification Program by CloudBees.
