---
layout: post
title: "Blue Ocean July development update "
tags:
- blueocean
- ux
- pipeline
author: i386
---

The team have been hard at work moving the needle forward on the Blue
Ocean 1.0 features. Many of the features we have been working on have
come a long way in the past few months but here's a few highlights:

==== Goodbye page refreshes, Hello Real Time updates!

Building upon
https://twitter.com/tomfennelly[Tom]'s great work on
https://github.com/jenkinsci/sse-gateway-plugin[Server Sent Events] (SSE) both
https://twitter.com/cliffmeyers[Cliff] and
https://twitter.com/tomfennelly[Tom] worked
on making the all the screens in Blue Ocean update without manual
refreshes.

https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events[SSE is a great technology]
choice for new web apps as it only pushes out
events to the client when things have changed on the server. That means
there’s a lot less traffic going between your browser and the Jenkins
server when compared to the continuous AJAX polling method that has been
typical of Jenkins in the past.

++++
<center>
<iframe width="640" height="505"
src="https://www.youtube-nocookie.com/embed/AEnByFwPYaE?rel=0" frameborder="0"
allowfullscreen></iframe>
</center>
++++

==== New Test Reporting UI

https://twitter.com/kzantow[Keith] has
been working with https://twitter.com/vivekpandey[Vivek] to
drive out a new set of extension points that allow us to build a new
rest reporting UI in Blue Ocean. Today this works for JUnit test reports
but can be easily extended to work with other kinds of reports.

++++
<center>
<iframe width="640" height="505"
src="https://www.youtube-nocookie.com/embed/QEeSOBCYY4o?rel=0" frameborder="0"
allowfullscreen></iframe>
</center>
++++

==== Pipeline logs are split into steps and update live

https://twitter.com/ThorScherler[Thorsten] and
https://twitter.com/sophistifunk[Josh] have
been hard at work breaking down the log into steps and making the live
log tailing follow the pipeline execution - which we’ve lovingly
nicknamed the “karaoke mode”

++++
<center>
<iframe width="640" height="505"
src="https://www.youtube-nocookie.com/embed/Ew13TjclNME?rel=0" frameborder="0"
allowfullscreen></iframe>
</center>
++++

====  Pipelines can be triggered from the UI

https://twitter.com/tomfennelly[Tom] has
been on allowing users to trigger jobs from Blue Ocean, which is one
less reason to go back to the Classic UI :)

++++
<center>
<iframe width="640" height="505"
src="https://www.youtube-nocookie.com/embed/kdT02vPTxQI?rel=0" frameborder="0"
allowfullscreen></iframe>
</center>
++++

==== Blue Ocean has been released to the experimental update center

Many of you have asked us questions about how you can try Blue Ocean
today and have resorted to building the plugin yourself or running our
Docker image.

We wanted to make the process of trying Blue Ocean in its unfinished
state by publishing the plugin to the experimental update center - it's
available today!

So what is the Experimental Update Center? It is a mechanism for the
Jenkins developer community to share early previews of new plugins with
the broader user community. Plugins in this update center are
experimental and we strongly advise not running them on production or
Jenkins systems that you rely on for your work.

That means any plugin in this update center could eat your Jenkins data,
cause slowdowns, degrade security or have their behavior change at no
notice.

You can learn how to
link:/blog/2013/09/23/experimental-plugins-update-center/[activate
the experimental update center on this post].

Stay tuned for more updates!
