---
layout: post
title: "GSoC Project: New Job Creation and Configuration"
- jenkins
- core
- jenkins2
- gsoc
author: samatdav
---

=== Abstract
Although powerful, Jenkins new job creation and configuration process may be non obvious and time consuming. This can be improved by making UI more intuitive, concise, and functional. I plan to achieve this by creating a simpler new job creation, configuration process focused on essential elements, and embedding new functionality. 

=== Deliverables
==== New job creation
* [Required] New job name validation
** Sending GET request to doCheckJobName after each input character
** Blocking item creation if it’s name is inappropriate
* [Required] Popup window. http://i.imgur.com/6O3jcuA.gif[Here is a
demonstrating animation]
** Rendering a popup window with job creation +
** Receiving JSON with job types
** Sending a POST request with job name and type
* [Optional] Simple new job configuration
** Job creation popup contains step to preset some of configuration
** Job creation popup sends a POST request to change confuguration on
job creation

==== Configuration page
* [Required] Changing help information.
http://i.imgur.com/zoSvB1G.gif[Here is a demonstrating animation.]
** The extension points and the plugin using them are created
** Help information can be styled using markdown
** Admin can choose editing rights to deny or allow users to modify the
help
** [Optional] The functionality is extended to creation of crowd sourced
"wiki like" documentation. As in
https://wiki.jenkins-ci.org/display/JENKINS/Translation+Assistance+Plugin[localization
plugin] the changes are gathered and applied beyond installation of a
particular user
* [Required] More intuitive configuration page. Pursuing to solve
https://issues.jenkins-ci.org/browse/JENKINS-32578[this issue]
** Accordion based navigation with collapsable parts
** Configuration finder autocomplete

==== Home page
* [Optional] Removing "My Views" page.
http://i.imgur.com/Dk8E5I4.jpg[Here is a demonstrating image.]
** "My Views" tabs are moved to home page
** Icons are added to "My Views" tabs
** View creation page functionality can create either of the types
* [Optional] Reducing number of UI elements
** Elements "enable auto refresh", “edit description”, “icon
sizes”,”legend”, “RSS” are removed from home page
** The elements are placed under "Manage Jenkins" or an upper menu
** New extension points are created to support new UI elements through
plugins

==== Credentials store page
* [Optional] Grouping credentials and their domains.
http://i.imgur.com/BUTVU5d.jpg[Here is a demonstrating image.]
** Credentials are shown under corresponding domains on one page
** Domains may be added, configured, or deleted on this page
** Credentials may be added, configured, or deleted on this page

=== Current progress
By May 25th I learned about the structure and tools of Jenkins and started working on the first project:

* I started with New Job Name validation first. Lickily, in last updates the https://github.com/jenkinsci/jenkins/pull/2324/files[changes of recena]. There were implemented all of the changes I proposed except real time check on name validity. https://github.com/jenkinsci/jenkins/compare/master...samatdav:master#diff-e146d4fdbfe6385a456aea9775f6282d[Here I proposed the change] which fixes it by sending GET request on keyup event in addition to blur.
* I also made a New Job Popup with using exiisting interface. https://raw.githubusercontent.com/samatdav/test1/master/example/out_2_ogv.gif[On
this GIF you can see my current results.] I used a
https://github.com/VodkaBears/Remodal[Remodal] library for popup and put
there https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/hudson/model/View/newJob.jelly[existing
New Job container]. Surprisingly, that it was fully functional
right away. On the GIF you can see that popup receives all job types and
then successfully submits the post form creating a new job. I think that
could be a good first step. Further I can start changing the window
itself.

=== About me
I interned at Intel and Yandex, and cofounded http://expfood.ru/[a startup project] where I personally developed front-end and back-end of the website.
I am excited to participate in GSoC with Jenkins this summer as a chanсe to make a positive change for thousands of users as well as to learn from great mentors.
