---
layout: post
author: rtyler
title: "Jenkins 2.0 Online JAM Wrap-up"
tags:
- jenkins2
- jam
- meetup
---


Last week we hosted our first ever
link:https://www.meetup.com/Jenkins-online-meetup/[Online JAM] with the debut
topic of: link:/2.0/[Jenkins 2.0]. link:https://github.com/alyssat[Alyssa], our
Events officer, and I pulled together a
link:https://www.meetup.com/Jenkins-online-meetup/events/230154841/[series of
sessions] focusing on some of the most notable aspects of Jenkins 2 with:

* A Jenkins 2.0 keynote from project founder
 link:https://github.com/kohsuke[Kohsuke Kawaguchi]
* An overview of "Pipeline as Code" from link:https://github.com/hrmpw[Patrick
  Wolf]
* A deep-dive into Pipeline and related plugins like Multibranch, etc from
  link:https://github.com/jglick[Jesse Glick] and
  link:https://github.com/kishorebhatia[Kishore Bhatia]
* An overview of new user experience changes in 2.0 from
  link:https://github.com/kzantow[Keith Zantow]
* A quick lightning talk about documentation by yours truly
* Wrapping up the sessions, was Kohsuke again, talking about the road beyond
  Jenkins 2.0 and what big projects he sees on the horizon.

++++
<center>
  <iframe width="560" height="315" src="https://www.youtube.com/embed/emV60CcDVV0" frameborder="0" allowfullscreen></iframe>
</center>
++++


The event was really interesting for me, and I hope informative for those who
participated in the live stream and Q&A session. I look forward to hosting more
Virtual JAM events in the future, and I hope you will
*link:https://www.meetup.com/Jenkins-online-meetup/[join us!]*

=== Questions and Answers

Below are a collection of questions and answers, that were posed during the
Virtual JAM. Many of these were answered during the course of the sessions, but
for posterity all are included below.

==== Pipeline

____
What kind of DSL is used behind pipeline as code? Groovy or allow freely use
different languages as a user prefer?
____

Pipeline uses a Groovy-based domain specific language.

____
How do you test your very own pipeline DSL?
____

Replay helps in testing/debugging while creating pipelines and at the branch
level. There are some ideas which link:https://github.com/jglick[Jesse Glick]
has proposed for testing `Jenkinsfile` and Pipeline libraries captured in
link:https://issue-redirect.jenkins.io/issue/33925[JENKINS-33925].

____
Isn't "Survive Jenkins restart" exclusive to [CloudBees] Jenkins Enterprise?
____

No, this feature does not need
link:https://www.cloudbees.com/capabilities/continuous-integration[CloudBees
Jenkins Enterprise]. All features shown
during the virtual JAM are free and open source. CloudBees' Jenkins Enterprise
product does support restarting from a specified stage however, and that is not
open source.

____
How well is jenkins 2.0 integrate with github for tracking job definitions?
____

Using the
link:https://wiki.jenkins.io/display/JENKINS/GitHub+Organization+Folder+Pluginp[GitHub
Organization Folder plugin], Jenkins can automatically detect a `Jenkinsfile` in
source repositories to create Pipeline projects.


____
Please make the ability for re-run failed stages Open Source too :)
____

This has been passed on to our friends at CloudBees for consideration :)

____
If `Jenkinsfile` is in the repo, co-located with code, does this mean Jenkins can
auto-detect new jobs for different branches?
____

This is possible using the
link:/doc/pipeline/#creating-multibranch-pipelines[Pipeline Multibranch plugin].


____
What documentation sources are there for Pipeline?
____

Our link:/doc/[documentation section] contains a number of pagesaround Pipeline.
There is also additional documentation and examples in the plugin's
link:https://github.com/jenkinsci/pipeline-plugin[git repository] and the
link:https://github.com/jenkinsci/pipeline-examples[jenkinsci/pipeline-examples]
repository. (contributions welcome!)

____
Where we can find the DSL method documentation?
____

There is generated link:/doc/pipeline/steps[documentation on jenkins.io] which
includes steps from all public plugins. Inside of a running Jenkins instance,
you can also navigate to
link:http://localhost:8080/workflow-cps-snippetizer/dslReference[JENKINS_URL/workflow-cps-snippetizer/dslReference]
to see the documentation for the plugins which are installed in that instance.


____
If Pipeline is not support some plugins (there is a lot actually), I needed
SonarQube Runner but unfortunately it's not supported yet, in Job DSL plugin i
can use "Configure Block" and cover any plugin via XML, how i can achieve the
same with a Pipeline?
____

Not at this time

____
Is there a possibility to create custom tooltips i.e. with a quick reference or
a link to internal project documentation? Might be useful i.e. for junior team
members who need to refer to external docs.
____

Not generally. Though in the case of Pipeline global libraries, you can create
descriptions of vars/functions like `standardBuild` in the demo, and these will
appear in Snippet Generator under Global Variables.

____
Oh pipeline supports joining jobs? It's really good, but I cannot find document
on link:/doc/[jenkins.io] could you tell me where is it?
____

There is a `build` step, but the Pipeline system is optimized for single-job
pipelines

____
We have multiple projects that we would like to follow the same pipeline.  How
would I write a common pipeline that can be shared across multiple projects.
____

You may want to look at implementing some additional steps using the
link:https://github.com/jenkinsci/pipeline-examples/tree/master/global-library-examples[Pipeline Global
Library] feature. This would allow you to define
organization-specific extensions to the Pipeline DSL to abstract away common
patterns between projects.

____
How much flexibility is there with creating context / setting environment
variables or changing / modifying build tool options when calling a web hook /
api to parameterize pipelines for example to target deployments to different env
using same pipeline
____

Various environment variables are exposed under the `env` variable in the Groovy
DSL which would allow you to construct logic as simple or as complex as
necessary to achieve your goal.

____
When you set up the job for the first time, does it build every branch in git,
or is there a way to stop it from building old branches?
____

Not at this time, the best way to prevent older branches from being built is to
remove the `Jenkinsfile` in those branches. Alternatively, you could use the
"include" or "exclude" patterns when setting up the SCM configuration of your
multibranch Pipeline. See also
link:https://issue-redirect.jenkins.io/issue/32396[JENKINS-32396].


____
Similar to GitHub organizations, will BitBucket "projects" (ways of organizing
collections of repos) be supported?
____

Yes, these are supported via the
link:https://wiki.jenkins.io/display/JENKINS/Bitbucket+Branch+Source+Plugin[Bitbucket
Branch Source plugin].

____
How do you handle build secrets with the pipeline plugin? Using unique
credentials stored in the credentials plugin per project and/or branch?
____

This can be accomplished by using the
link:https://wiki.jenkins.io/display/JENKINS/Credentials+Binding+Plugin[Credentials
Binding plugin].

____
Similar to GitHub Orgs, are Gitlab projects supported in the same way?
____

GitLab projects are not explicitly supported at this time, but the extension
points which the GitHub Organization Folder plugin uses could be extended in a
similar manner for GitLab. See also link:https://issue-redirect.jenkins.io/issue/34396[JENKINS-34396]

____
Is Perforce scm supported by the Pipeline plugin?
____

As a SCM source for discovering a `Jenkinsfile`, not at this time. The
link:https://wiki.jenkins.io/display/JENKINS/P4+Plugin[P4]
plugin does provide some `p4` steps which can be used in a Pipeline script
however, link:/doc/pipeline/steps/p4[see here for documentation].


____
Is Mercurial supported with multibranch?
____

Yes, it is.

____
Can `Jenkinsfile` detect when it's running against a pull request vs an approved commit, so that it can perform a different type of build?
____

Yes, via the `env` variables provided in the DSL scope. Using an `if` statement,
one could guard specific behaviors with:

[source,groovy]
----
if (env.CHANGE_ID != null) {
    /* do things! */
}
----

____
Let's say I'm building RPMs with Jenkins and use build number as an RPM
version/release number. Is there a way to maintain build numbers and leverage
versioning of `Jenkinsfile`?
____


Through the `env` variable, it's possible to utilize `env.BUILD_NUMBER` or the
SCM commit ID, etc.

____
Love the snippet generator! Any chance of separating it out from the pipeline
into a separate page on its own, available in the left nav?
____

Yes, this is tracked in
link:https://issue-redirect.jenkins.io/issue/31831[JENKINS-31831]

____
Any tips on pre-creating the admin user credential and selecting plugins to
automate the Jenkins install?
____

There are various link:https://github.com/jenkinsci/puppet-jenkins[configuration
management modules] which provide parts of this functionality.



____
I'm looking at the pipeline syntax (in Jenkins 2.0) how do I detect a
`step([...])` has failed and create a notification inside the `Jenkinsfile`?
____

This can be done by wrapping a step invocation with a Groovy `try/catch` block.
See also link:https://issue-redirect.jenkins.io/issue/28119[JENKINS-28119]


==== User Interface/Experience
____
Is the user experience same as before when we replace the Jenkins.war(1.x to
2.x) in an existing (with security in place) installation?
____

You will get the new UI features like redesigned configuration forms, but the
initial setup wizard will be skipped. In its stead, Jenkins will offer to
install Pipeline-related functionality.


____
Is it possible to use custom defined syntax highlighting ?
____

Within the Pipeline script editor itself, no. It is using the
link:https://ace.c9.io/[ACE editor] system,
so it may be possible for a plugin to change the color scheme used.


____
Can you elaborate on what the Blue Ocean UI is? Is there a link or more
information on it?
____

Blue Ocean is the name of user experience an design project, unfortunately at
this point in time there is not more information available on it.


==== General
____
How well this integrate with cloud environment?
____

The Jenkins controller and agents can run easily in any public cloud environment
that supports running Java applications. Through the
link:https://wiki.jenkins.io/display/JENKINS/Amazon+EC2+Plugin[EC2],
link:https://wiki.jenkins.io/display/JENKINS/JClouds+Plugin[JClouds],
link:https://wiki.jenkins.io/display/JENKINS/Azure+Slave+Plugin[Azure], or
any other plugins which extend the cloud
link:/doc/developer/extensions/jenkins-core/#cloud[extension
point], it is possible to dynamically provision new build agents on a configured
cloud provider.

____
Are help texts and other labels and messages updated for other localizations /
languages as well?
____

Practically every string in Jenkins core is localizable. The extent to which those
strings have been translated depends on contributors by speakers of those
languages to the project. If you want to contribute translations, this
link:https://wiki.jenkins.io/display/JENKINS/Internationalization#Internationalization-Whattranslatorsneedtoknow%2Fdo[wiki
page] should get you started.

____
Any additional WinRM/Windows remoting functionality in 2.0?
____

No

____
Is there a CLI to find all the jobs created by a specific user?
____

No, out-of-the-box Jenkins does not keep track of which user created which jobs.
The functionality provided by the
link:https://wiki.jenkins.io/display/JENKINS/Ownership+Plugin[Ownership]
plugin may be of interest though.

____
Please consider replacing terms like "master" and "slave" with "primary" and
"secondary".
____

"slave" has been replaced with "agent" in Jenkins 2.0.

*Updated 2020-09-18*: The term "master" is being replaced with "controller".

____
We've been making tutorial videos on Jenkins for awhile (mostly geared toward
passing the upcoming CCJPE). Because of that we're using 1.625.2 (since that is
what is listed on the exam), but should we instead base the videos on 2.0?
____

As of right now all of the
link:https://www.cloudbees.com/jenkins-certification[Jenkins Certification] work done by CloudBees is
focused around the Jenkins LTS 1.625.x.
