---
layout: post
title: "GSOC Project Intro: Automatic Plugin Documentation"
tags:
- gsoc
- plugins
author: cynthia
---

=== About me

I am Cynthia Anyango from Nairobi, Kenya. I am a second year student at Maseno
University. I am currently specializing on Ruby on Rails and trying to learn
Python. I recently started contributing to Open source projects.My major
contribution was at Mozilla, where I worked with the QA for Cloud services. I did
manual and automated tests for various cloud services. I wrote documentation
too. Above that, I am competent and I am always passionate about what I get my
hands on.

=== Project summary


Currently Jenkins plugin documentation is being stored in Confluence. Sometimes
the documentation is scattered and outdated. In order to improve the situation we
would like to follow the documentation-as-code approach and to put docs to
plugin repositories and then publish them on the project website using the
awestruct engine. The project aims an implementation of a documentation
continuous deployment flow powered by Jenkins and Pipeline Plugin.

The idea is to automatically pull in the README and other docs from GitHub, show
changelogs with versions and releases dates. I will be designing file templates
that will contain most of the  docs information that will be required from
plugin developers. Initially the files will be written in
link:https://asciidoctor.org/[AsciiDoc]. Plugin developers will get a chance to
review the templates. The templates will be prototyped by various plugin
developers.

The docs that will be automatically pulled from github and will be published on
link:/[Jenkins.io] under the Documentation section.

My mentors are link:https://github.com/rtyler[R.Tyler] and
https://github.com/batmat[Baptiste Mathus]

I hope to achieve this by 25th June when we will be having our mid-term
evaluations.

I will update more on the progress.

=== Links

* link:https://summerofcode.withgoogle.com/dashboard/project/5120513768685568/details/[Gsoc Page]
* link:https://wiki.jenkins.io/display/JENKINS/Google+Summer+Of+Code+2016[Jenkins Gsoc Page ]
* link:https://groups.google.com/forum/#!topic/jenkinsci-dev/kNZMOsF_ueA[Mailing List discussion on Jenkins-Developers]
* link:https://medium.com/@anyango_cynthia[My blog on Medium]
