---
layout: post
title: "Possible Jenkins Project Infrastructure Compromise"
tags:
- infra
- security
author: rtyler
---

Last week the infrastructure team identified a potential for compromise of a
key machine in the cluster which could have been taken advantage of in, what I
would categorize as, an attempt targeted at contributors with elevated access.
Unfortunately, when facing the uncertainty of a _potential_ compromise, the safest
option is to treat it as if it were an actual incident, and react accordingly.
The machine in question had access to binaries published to our primary and
secondary mirrors and contributor account information.

Since this machine is not the source of truth for Jenkins binaries, we verified
that the files distributed to Jenkins users: plugins, packages, etc, were not
tampered with. We can not, however, verify that contributor account information
was not accessed or tampered with and as a proactive measure are issuing a
password reset across the database. We have also spent significant effort
migrating all key services off of the potentially compromised machine to
(virtual) hardware so the machine can be re-imaged or decommissioned entirely.

=== What you should do

If you have ever filed an issue in link:https://issues.jenkins-ci.org[JIRA], edited a link:https://wiki.jenkins-ci.org[wiki] page or released a
plugin, you have a Jenkins community account. You should be receiving a
password reset email shortly, but if you have re-used your Jenkins account
password with other services with strongly encourage you to update your
passwords with those other services. If you're not already using one, we also
encourage the use of a password manager for generating and managing
service-specific passwords.


=== What we're doing to prevent events like this in the future

As stated above, the potentially compromised machine is being removed from our
infrastructure. That helps address the immediate problem but doesn't put
guarantees in place for the future. To help prevent potential issues in the
future we're taking the following actions.

. Incorporating more security policy enforcement into our
  link:https://github.com/jenkins-infra[Puppet-driven infrastructure]. Without a
  configuration management tool enforcing a given state for some legacy services,
  user error and manual mis-configurations can adversely affect project security.
  As of right now, all key services are managed by Puppet.
. Balkanizing our machine and permissions model more. The machine affected was
  literally the first independent (outside of Sun) piece of project
  infrastructure and many legacy systems, it grew to host a multitude of
  services. We are rapidly evolving away from that model with increasing levels
  of user and host separation for project services.
. In a similar vein, we have also introduced a "trusted" zone in our
  infrastructure which is not routable on the public internet where sensitive
  operations, such as generating update center information, can be managed and
  secured more effectively.
. We are performing an infrastructure permissions audit. Some portions of our
  infrastructure are 6+ years old and have had contributors come and go. Any
  inactive users with unnecessarily elevated permissions in the project
  infrastructure will have those permissions revoked.


I would like to extend thanks, on behalf of the Jenkins project, to
link:https://www.cloudbees.com[CloudBees] for their help in funding and
migrating this infrastructure.

If you have further questions about the Jenkins project infrastructure, you can
join us in the `#jenkins-infra` channel on link:http://freenode.net[Freenode]
or in an Infrastructure Q&A session I've scheduled for next Wednesday (April
27) at 20:00 UTC (12:00 PST).

