---
layout: post
title: "GSoC: Jenkins Usage Statistics Analysis Introduction"
tags:
-infra_statistics
-gsoc
-jenkins_usage
author: payal94
---

=== About myself
Hello, my name is Payal Priyadarshini.
I am pursing my major in Computer Science & Engineering at the Indian Institute of Technology Kharagpur, India.
I am very proficient in writing code in Python, C++, Java and currently getting familiar and hopefully good in Groovy too.

I have internship experiences in renowed institutions like Google and VMware where I worked with some exciting
technologies for example Knowledge Graphs, BigTable, SPARQL, RDF in Google. I am a passionate computer science student who
is always interested in learning and looking for new challenges and technologies.That’s how I came across to Google Summer 
of Code where I am working on some exciting data mining problems which you are going to encounter below in this blog.

=== Project Overview
Jenkins has collected anonymous jenkins usage information of more than 100,000 installations which includes set of plugins
and their versions, release history etc. This data collection can be exploited for various data mining experiments. 
Main goal of this project is to perform various analysis and studies over the available dataset to discover trend in data
usage for example plugins utilization, spotting downgrades etc. This project covers a wide range of high priority problems
which need to be solved such as:
* _How quickly users are upgrading jenkins and its plugins_, will give us the insight of popularity of the releases.
* _Spotting downgrades_, which will warn us that something is wrong with the version.
* _Correlating_ what users are saying (community rating) with what users are doing (upgrades/downgrades).
* _Distribution of cluster size_, where clusters represents jobs, nodes count which approximates the size of installation.
* _Finding set of plugins which are likely to be used together_, will setup pillar for plugin recommendation system.

As a part of the link:https://summerofcode.withgoogle.com/[Google Summer of Code] 2016, I will be working on the above
mentioned problems. My mentors for the project are Kohsuke Kawaguchi and Daniel Beck. Few link:http://stats.jenkins-ci.org/jenkins-stats/svg/svgs.html[analyses] has been done over this
data but those are outdated as charts can be more clearer and interactive. This project aims to improvise existing
statistics and generating new ones discussed above.

=== Use Cases
This project covers wide-range of the use-cases that has been derived from the problems mentioned above.

==== UseCase 1: Upgrade/Downgrade Analysis
Understanding the trend in upgrades and downgrades have lots of utilities, some of them have already been explained
earlier which includes measuring the popularity, spotting downgrades, giving warning about the wrong versions quickly etc.

===== Usecase 1.1: Upgrading time metrics
This analysis refers to the time taken by the users to upgrade its jenkins installation and its plugins. Required dataset
for the analysis are link:https://bigquery.cloud.google.com/table/jenkins-user-stats:jenkinsstats.jenkins_usage?_ga=1.195703460.947004610.1452882463&pli=1[jenkins-usage] data and link:http://mirror.xmission.com/jenkins/updates/current/release-history.json[release-history] data. Types of queries that are supported in this
analysis are:
* *Query1 :* Enter the update release date, whose performance user wants to study.
* *Query2 :* Enter the plugin name, whose release history, charts and upgrading time metric, user wants to study.	

===== Usecase 1.2: Spotting dowgrades
Here we are interested to know, how many installations downgraded from any given version to any earlier version. The idea
is to measure the monotonicity of the version_number vs timestamp graph per installation id because graph must be
increasing if there are no downgrades.

===== Usecase 1.3: Correlation with the perceived quality of Jenkins release 
To correlate what users are saying to what users are doing, we have community ratings which tells us about the ratings and
reviews of the releases and has following parameters:			
* Used the release on production site w/o major issues.		
* Don’t recommend to other.			
* Tried but rolled it back to the previous version. 
Similar parameters can be fetch from the analysis explained in above section.

==== Usecase 2: Plugin Recommendation System
This section involves setting up ground work for the plugin recommendation system. The idea is to find out the set of
plugins which are most likely to be used together. Here we will be following both content based filtering as well as
collaborative filtering approach. 

===== Collaborative Filtering
This approach is based upon the collecting and analysing large amount of information on user’s behaviours, activities or
preferences. We have implicit form of the data about the plugins, that is for every install ids, we know the set of
plugins installed. We can exploit this information to construct plugin usage graph where nodes are the plugins and the
edges between them is the number of installations in which both plugins are installed together.

===== Content-based Filtering
Content-based filtering methods are based on a description of the item and a profile of the user’s preference for example
recommending items that are similar to the those that a user liked in the past or examining in the present. Here, we are
exploiting link:http://stats.jenkins-ci.org/jenkins-stats/jenkinsgraph.html?filter=kohsuke[Jenkins plugin dependency graph]
to learn about the properties of a plugin.

=== Additional Details
You may find the complete project proposal along with the detailed design of the use-cases with their implementation
details here in the link:https://docs.google.com/document/d/1ZSVDzYChadUcmsLpI274t36kHJAIE03IDkxBLiVVylM/edit?usp=sharing[design document].
A complete version of the *use-case 1: Upgrage & DowngradeAnalysis* should be available in late June and basic version
of plugin recommendation system will be available in late July.

I do appreciate any kind of feedback and suggestions.
You may add comments in the link:https://docs.google.com/document/d/1ZSVDzYChadUcmsLpI274t36kHJAIE03IDkxBLiVVylM/edit?usp=sharing[design doc].
I will be posting time to time updates about the statistics generation status on the link:https://groups.google.com/forum/#!forum/jenkinsci-dev[jenkins-dev] mailing list and link:Jenkins-infra@lists.jenkins-ci.org[jenkins-infra] mailing list.

=== Links:
* link:https://docs.google.com/document/d/1ZSVDzYChadUcmsLpI274t36kHJAIE03IDkxBLiVVylM/edit?usp=sharing[Design Doc]
* link:https://summerofcode.withgoogle.com/[Google Summer of Code]
* link:https://github.com/jenkinsci/infra-statistics[Github infra-stats]
* link:http://stats.jenkins-ci.org/jenkins-stats/svg/svgs.html[Jenkins statistics]
* link:http://stats.jenkins-ci.org/jenkins-stats/jenkinsgraph.html?filter=kohsuke[Jenkins Plugin Dependency Graph]
* link:https://github.com/Payal94/GSoC-Jenkins-Usage-Statistics-Analysis[Github GSoC Jenkins Usage Statistics Analysis]
