---
layout: post
title: "SCaLE 14x Conference Report"
tags:
- scale
- meetup
author: rtyler
---

Historically January has always been a very big month for the Jenkins
community. Between link:https://fosdem.org[FOSDEM]
link:https://socallinuxexpo.org[Southern California Linux Expo]  (also known as
SCaLE) we seem to hand out more stickers during the last week in January than
any other week of the year.

This year's SCaLE 14X conference finally outgrew the LAX Hilton in Los Angeles,
where it had been hosted in years past, and moved over to the Pasadena
Convention Center in Pasadena California. While the organizers of the
conference expanded their scope, so did the Jenkins project!

In addition to our normal Jenkins stickers, we also had some special edition stickers with link:/artwork/[special logos] to give away this year, namely:

* Angry Jenkins
* General Jenkins
* Superhero Jenkins
* "Cute" Jenkins
* Ninja Jenkins

To accompany the stickers we also had both blue Jenkins and red "Angry Jenkins"
pins. Savvy Jenkins users might recognize "Angry Jenkins" from the Jenkins
server's internal 500 page; fortunately however very few people that came by
the booth to say 'hello' were familiar with Angry Jenkins.

=== Talking Points

Aside from talking about the cool stickers and pins, we spent the vast
majority of time talking about Jenkins to two groups of people:

. those who never had actually used Jenkins, even if they had heard of it
. users who knew plenty about Jenkins but hadn't actually heard about some of
  the link:/content/jenkins-20-proposals[Jenkins 2.0 Proposals].

Anecdotally, it seemed like most of the people that I talked to about "Jenkins
2.0" were pretty excited about the `Jenkinsfile` idea and starting to define
their link:/solutions/pipeline[build processes and delivery pipelines as code]
in their source repositories.

Perhaps more importantly though, we spoke with many users about where Jenkins
is causing them pain or frustration. Speaking directly with users at events
like SCaLE or Jenkins Area Meetups is always fun, having a high-bandwidth
conversation about what we can do better and/or offering solutions/workarounds
to hopefully relieve some pain-points.

In one such case, a contributor approached me and complained that he had
emailed the developers' mailing list and frustratingly never actually received
a response. Comically enough, neither of us were able to find the email he had
sent the mailing list (whoops!) but because of the dynamic nature of booth-duty
at SCaLE, we got him squared away with a repository to contribute a
link:https://github.com/jenkinsci/jenkins-charm[Jenkins Charm] for the Juju
configuration management tool.


=== Jammin'

Among the booth-duty highlights was meeting a few folks who were interested on
starting a southern California Jenkins meetup. Over the days following the
conference, and a brief discussion on the
link:https://groups.google.com/d/msgid/jenkinsci-jam/a071f664-30ab-44eb-b65f-a6f19cfbfdf5%40googlegroups.com.[jenkinsci-jam@
mailing list], and the
*link:https://www.meetup.com/Los-Angeles-Jenkins-Area-Meetup/[Los Angeles
Jenkins Area Meetup]* was born!

I'm looking forward to the meetup growing over the next couple months and
helping build a stronger local Jenkins community in Southern Califonia for the
other 51 weeks a year that SCaLE isn't happening.

---

link:https://socallinuxexpo.org[SCaLE] is one of my more favorite
open source conferences, the positive community in attendance, a kid-friendly
atmosphere ("Game Night" was a blast) and the broad spectrum of sessions
available make it a great way to spent the weekend in southern California.

We hope to see you there again next year!

