---
layout: post
title: "GSoC: External Workspace Manager Plugin beta version"
tags:
- pipeline
- plugins
- external-workspace-manager
- gsoc
author: alexsomai
---

This blog post is a continuation of the External Workspace Manager Plugin related posts, starting with
link:/blog/2016/05/23/external-workspace-manager-plugin/[the introductory blog post], and followed by
link:/blog/2016/06/30/ewm-alpha-version/[the alpha version release announcement].

As the title suggests, a beta version of the External Workspace Manager Plugin was launched!
This means that it's available only in the
link:/blog/2013/09/23/experimental-plugins-update-center/[Experimental Plugins Update Center].

[NOTE]
Take care when installing plugins from the Experimental Update Center, since they may change in
backward-incompatible ways.
It's advisable not to use it for Jenkins production environments.

The plugin's repository is on link:https://github.com/jenkinsci/external-workspace-manager-plugin[GitHub].
The complete plugin's documentation can be accessed
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/README.md[here].
A summary of the features added so far, since the alpha version:

* It has support for the
link:https://github.com/jenkinsci/run-selector-plugin[Run Selector Plugin] (which is still in beta),
so you can provide different run selection strategies when allocating a disk from the upstream job.
You can find an example of its usage in this
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/doc/PIPELINE_EXAMPLES.md#workspace-reuse-in-two-different-jobs[Pipeline code].
* Provides an automatic workspace cleanup by integrating the
link:https://github.com/jenkinsci/ws-cleanup-plugin[Workspace Cleanup Plugin].
Some basic examples can be seen if you follow this
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/doc/WORKSPACE_CLEANUP.md[link].
* Allows the user to specify a custom workspace path to be used when allocating workspace on the disk.
The plugin offers two alternatives for doing this.
For more details see the afferent
link:https://github.com/jenkinsci/external-workspace-manager-plugin/blob/master/doc/CUSTOM_WORKSPACE_PATH.md[documentation page].
* It comes with Disk Pool restriction strategies, meaning that you can restrict a particular Disk Pool to be allocated
only if the Jenkins job was triggered by specific users/groups, or if the project's name matches a defined
pattern, etc.
It does this by using the restriction capabilities provided by the
link:https://github.com/jenkinsci/job-restrictions-plugin[Job Restrictions Plugin].

Currently there is ongoing work for providing flexible disk allocation strategies.
Afterwards, the plugin will enter a final testing phase.

If all goes to plan, a stable version should be released in about two weeks.

If you have any issues in setting up or using the plugin, please feel free to ask me on the plugin's Gitter
link:https://gitter.im/jenkinsci/external-workspace-manager-plugin[chat].
Any feedback is welcome, and you may provide it either on the Gitter chat, or on
link:https://issues.jenkins-ci.org[Jira] by using the __external-workspace-manager-plugin__ component.

=== Links

link:https://gitter.im/jenkinsci/external-workspace-manager-plugin?utm_source=share-link&utm_medium=link&utm_campaign=share-link[image:https://badges.gitter.im/jenkinsci/external-workspace-manager-plugin.svg[title: "Gitter"]]

* link:https://github.com/jenkinsci/external-workspace-manager-plugin[Project repository]
* link:/blog/2016/05/23/external-workspace-manager-plugin/[Project intro blog post]
* link:https://jenkins.io/blog/2016/06/30/ewm-alpha-version/[Alpha version announcement]
* link:https://summerofcode.withgoogle.com/[GSoC page]
* link:https://jenkins.io/projects/gsoc/[Jenkins GSoC Page]
