---
layout: chapter
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc:
endif::[]

////
XXX: Pages to mark as deprecated by this document:
      * https://wiki.jenkins.io/display/JENKINS/Terminology
////

= Glossary

++++
<script>
$(function () {
    anchors.add('dt');
})
</script>
++++

////
NOTE: The [glossary] delimiter in AsciiDoctor doesn't autogenerate anchors for
each of the terms below. Which means that if we want to cross-reference terms
directly from other documents we need to include an inline anchor.

Additionally, because these inline anchors don't attach to section headings,
cross referencing must include the appropriate display text, for example:

  MyTerm:: [[myterm]] this is the definition of MyTerm

Should be cross-referenced with:

  <<myterm,MyTerm>>

To ensure it is rendered appropriately.
////

== General Terms

[glossary]
link:/doc/book/using/using-agents/[Agent]::
    An agent is typically a machine, or container, which connects to a Jenkins
    controller and executes tasks when directed by the controller.
Artifact::
    An immutable file generated during a <<build,Build>> or <<pipeline,Pipeline>>
    run which is *archived* onto the Jenkins <<controller,Controller>> for
    later retrieval by users.
Build:: [[build]]
    Result of a single execution of a <<job,job>>
Cloud:: [[cloud]]
    A System Configuration which provides dynamic <<agent,Agent>>
    provisioning and allocation, such as that provided by the
    plugin:azure-vm-agents[Azure VM Agents]
    or
    plugin:ec2[Amazon EC2] plugins.
Controller::
    The central, coordinating process which stores configuration, loads plugins,
    and renders the various user interfaces for Jenkins.
Core::
    The primary Jenkins application (`jenkins.war`) which provides
    the basic web UI, configuration, and foundation upon which <<plugin, Plugins>>
    can be built.
Downstream:: [[downstream]]
    A configured <<pipeline,Pipeline>> or <<job,job>> which is triggered
    as part of the execution of a separate Pipeline or Job.
Executor:: [[executor]]
    A slot for execution of work defined by a <<pipeline,Pipeline>> or
    <<job,job>> on a <<node, Node>>. A Node may have zero or more
    Executors configured which corresponds to how many concurrent Jobs or
    Pipelines are able to execute on that Node.
Fingerprint::
    A hash considered globally unique to track the usage of an
    <<artifact,Artifact>> or other entity across multiple
    <<pipeline,Pipelines>> or <<job,jobs>>.
Folder:: [[folder]]
    An organizational container for <<pipeline,Pipelines>> and/or
    <<job,jobs>>, similar to folders on a file system.
Item:: [[item]]
    An entity in the web UI corresponding to either a:
    <<folder,Folder>>, <<pipeline,Pipeline>>, or <<job,job>>.
Jenkins URL:: [[jenkins-url]]
    The main url for the jenkins application, as visited by a user.
    e.g. https://ci.jenkins.io/
Job:: [[job]]
    A user-configured description of work which Jenkins should perform, such as
    building a piece of software, etc.
Kubernetes:: [[kubernetes]]
    Kubernetes (K8s) is an open-source system for automating deployment, scaling,
    and management of containerized applications.
    See link:/doc/book/installing/kubernetes/[Installing Jenkins / Kubernetes]
    for more info.
Label:: [[label]]
    User-defined text for grouping <<agent,Agents>>, typically by similar
    functionality or capability. For example `linux` for Linux-based agents or
    `docker` for Docker-capable agents.
LTS::
    A long-term support <<release, Release>> line of Jenkins products, becoming
    available for downloads every 12 weeks.
    See link:/download/lts/[this page] for more info.
Master::
    A deprecated term, synonymous with <<controller,Controller>>.
link:/doc/book/managing/nodes/[Node]::
    A machine which is part of the Jenkins environment and capable
    of executing <<pipeline,Pipelines>> or <<job,jobs>>. Both the
    <<controller,Controller>> and <<agent,Agents>> are considered to be Nodes.
Project:: [[project]]
    A deprecated term, synonymous with <<job,job>>.
Pipeline:: [[pipeline]]
    A user-defined model of a continuous delivery pipeline, for more read the
    <<pipeline#,Pipeline chapter>> in this handbook.
Plugin::
    An extension to Jenkins functionality provided separately
    from Jenkins <<core,Core>>.
Publisher::
    Part of a <<build,Build>> after the completion of all configured
    <<step,Steps>> which publishes reports, sends notifications, etc.
    A publisher may report <<stable,Stable>> or <<unstable,Unstable>> result
    depending on the result of its processing and its configuration.
    For example, if a JUnit test fails, then the whole JUnit publisher may
    report the build result as <<unstable,Unstable>>.
Resource Root URL:: [[resource-root-url]]
    A secondary url used to serve potentially untrusted content (especially
    build artifacts). This url is distinct from the <<jenkins-url,Jenkins URL>>.
Release::
    An event, indicating availability of Jenkins distribution products or one
    of Jenkins plugins. Jenkins products belong either to <<lts, LTS>> or weekly
    Release lines.
Stage::
    `stage` is part of Pipeline, and used for defining a conceptually distinct
    subset of the entire Pipeline, for example: "Build", "Test", and "Deploy",
    which is used by many plugins to visualize or present Jenkins Pipeline
    status/progress.
Step::
    A single task; fundamentally steps tell Jenkins _what_ to do inside of a
    <<pipeline,Pipeline>> or <<job,job>>.
    See link:/doc/book/pipeline/getting-started/[Pipelines / Getting Started]
    and link:/doc/book/pipeline/jenkinsfile/[Pipeline / Using a jenkinsfile]
    for more info.
Trigger:: [[trigger]]
    A criteria for triggering a new <<pipeline,Pipeline>> run or
    <<job,job>>.
Update Center:: [[update-center]]
    Hosted inventory of plugins and plugin metadata to enable plugin
    installation from within Jenkins.
Upstream:: [[upstream]]
    A configured <<pipeline,Pipeline>> or <<job,job>> which triggers a
    separate Pipeline or Job as part of its execution.
View:: [[view]]
    A way of displaying the data of Jenkins in a dashboard style.
    This is an extensible object, so there are lots of different ways to list <<job,jobs>>, show trends, and analyze data.
Workspace:: [[workspace]]
    A disposable directory on the file system of a <<node,Node>>
    where work can be done by a <<pipeline,Pipeline>> or <<job,job>>.
    Workspaces are typically left in place after a <<build,Build>> or
    <<pipeline,Pipeline>> run completes unless specific Workspace cleanup policies
    have been put in place on the Jenkins <<controller,Controller>>.

[build-status]
== Build Status

Aborted::
    The <<build,Build>> was interrupted before it reaches its expected end. For example, the user has stopped it manually or there was a time-out.
Failed::
    The <<build,Build>> had a fatal error.
Stable::
    The <<build,Build>> was <<successful,Successful>> and no <<publisher,Publisher>> reports it as <<unstable,Unstable>>.
Successful::
    The <<build,Build>> has no compilation errors.
Unstable::
    The <<build,Build>> had some errors but they were not fatal. A <<build,Build>> is unstable if it was built successfully and one or more publishers report it unstable. For example if the JUnit publisher is configured and a test fails then the <<build,Build>> will be marked unstable.
