= Git Credentials Binding for sh, bat, powershell

== Abstract

This project proposes to implement two new credential bindings to perform authenticated operations using command line git in Jenkins pipeline job/freestyle project.

The two credential bindings are `gitSshPrivateKey` and `gitUsernamePassword`.

== Implementation

Type::
Feature

Location::
Both `gitUsernamePassword` and `gitSshPrivateKey` bindings are implemented in Jenkins https://plugins.jenkins.io/git/[git-plugin] v4.8.0.

Dependencies::
1. https://plugins.jenkins.io/credentials-binding/[Credentials Binding Plugin]-
It is used to bind Git specific environment variables with shell scripts/commands which perform git authentication on behalf of the user, without their interaction with the command-line.

2. https://plugins.jenkins.io/bouncycastle-api/[Bouncy Castle API Plugin]-
Provides an API to do common tasks like PEM/PKCS#8 Encoding/Decoding and ensuring its stability among BC versions.

3. https://plugins.jenkins.io/sshd/[SSHD Plugin]-
Provides an API to perform tasks like OpenSSH Encoding/Decoding.

== Phase 1: Git Username Password Binding (gitUsernamePassword)

=== Deliverables
* To support git authentication over *HTTP* protocol
** Use the `GIT_ASKPASS` environment variable to provide user credentials while git authentication process
* Support different
** _OS environments_: CentOS 7, CentOS 8, Debian 9, Debian 10, FreeBSD 12, OpenBSD 6.9, openSUSE 15.2, Ubuntu 18.04, Ubuntu 20.04, Ubuntu 21.04, and Windows 10.
** _Processors_: amd64, arm32, arm64, and s390x.
* Authentication support for Cli Git only, not JGit or JGit Apache.
** Check for specific git versions
** Setting git specific environment variables based on OS type
* Automated test coverage more that 90%

=== Resources

* Pull Requests
*** https://github.com/jenkinsci/git-plugin/pull/1104[Add Git Credentials binding for Username and Password]
*** https://github.com/jenkinsci/git-client-plugin/pull/724[Check the least Cli Git version required]
*** https://github.com/jenkinsci/git-plugin/pull/1119/files[Git Username Password binding doc update in git-plugin]
* https://github.com/jenkins-infra/jenkins.io/pull/4516[gitUsernamePassword binding explanation]
* https://docs.google.com/presentation/d/1LCH0dXzWka_l-WQ3SVMCXfU7w7jQENXS-bdz2E5GIgU/edit?usp=sharing[Slides]
* https://www.jenkins.io/blog/2021/07/27/git-credentials-binding-phase-1/[Git Username Password binding released blog post]
* Phase 1 demo and presentation:

video::_D0hiA1Cgz8[youtube,start=4068,width=800,height=420]

== Phase 2: Git SSH Private Key Binding (gitSshPrivateKey)

=== Deliverables
* To support git authentication over *SSH* protocol
* Supports:
** Private Key Formats
*** OpenSSH
*** PEM
*** PKCS#8
** Encryption algorrithms
*** RSA
*** DSA
*** ECDSA
*** ED25519
** _OS environments_: CentOS 7, CentOS 8, Debian 9, Debian 10, FreeBSD 12, OpenBSD 6.9, openSUSE 15.2, Ubuntu 18.04, Ubuntu 20.04, Ubuntu 21.04, and Windows 10.
** _Processors_: amd64, arm32, arm64, and s390x.
* Authentication support for Cli Git only, not JGit or JGit Apache.
* Use git specific environment variables depending upon the minimum CLI-git version
** `GIT_SSH_COMMAND` - If version is greater than 2.3, provides ssh command including the necessary options.
** `SSH_ASKPASS` - If version is less than 2.3, an executable script is attached to the variable.
** Setting variables based on OS type

=== Resources
* Pull Requests
** https://github.com/jenkinsci/git-plugin/pull/1111[Add Git Credentials binding for SSH Private Key]
*** https://github.com/jenkinsci/git-plugin/pull/1111/commits/828cc946442a0e6ab6944d2e2315c8c9d0a7b9d0[Last GSOC-2021 noted commit]
** https://github.com/jenkinsci/git-client-plugin/pull/727[Scope change of getSSHExecutable method]
* https://github.com/jenkins-infra/jenkins.io/pull/4516[gitSshPrivateKey binding explanation]

== Achievements

. The git credential bindings which are available through git plugin automates the git authentication process for a user effortlessly.
. The gitUsernamePassword and gitSshPrivateKey binding provides git authentication support for Pipeline and FreeStyle Project users in various OS environments on different processors.
. The gitUsernamePassword binding has been released and is readily available from git plugin v4.8.0 and above.
. The gitSshPrivateKey binding provides support for OpenSSH format which is default for OpenSSH v7.8 and above.

== Needs more time (TODO)

* SSH Private Key Binding
** If SSHD plugin dependency in git plugin requires shading using Java modules approach to prevent failures in production code.
