---
title: Artifact Repository
layout: developersection
---

The Jenkins project uses its own Artifactory binary repository, to distribute core, library, and plugin releases.
Only artifacts uploaded there can be considered released.
Plugins and libraries are not uploaded or mirrored to Maven Central.
The Jenkins Artifactory is hosted at https://repo.jenkins-ci.org.

Anyone has permission to view and download all (public) artifacts.
Permission to upload/deploy artifacts is controlled via link:https://github.com/jenkins-infra/repository-permissions-updater/[YAML files in a jenkins-infra GitHub repository].

[NOTE]
====
Permission to delete artifacts is not granted to anyone but administrators.
Do not expect them to delete even broken or accidental releases on request unless leaving it up puts Jenkins users or project infrastructure at risk.
Please report such an exceptional situation as https://jenkins.io/security/#reporting-vulnerabilities[a security vulnerability].

If a specific plugin or specific releases of a plugin should not be published on update sites, see link:../removing-from-distribution[Removing from Distribution] for instructions how to do that.
Note that this will not prevent anyone from directly downloading the artifacts from Artifactory.
====
