---
title: Plugin Documentation
layout: developersection
references:
- url: https://plugins.jenkins.io/
  title: Plugin site
- url: ../plugin-site/
  title: Plugin site documentation
- url: ../wiki-page/
  title: Hosting plugin documentation on Jenkins Wiki
---

Documentation is an important part of any Jenkins plugin.
It includes user documentation (plugin pages, changelogs, user guidelines, etc.)
and the contributor documentation (how to contribute, developer guidelines, etc.).
This section provides overview of these documentation types.

== Plugin pages

Plugin pages are hosted on the link:https://plugins.jenkins.io/[Plugin Site].
These pages are generated automatically using the metadata from the latest plugin release and an external documentation page.
External documentation can be retrieved from GitHub or from the https://wiki.jenkins.io[Jenkins Wiki].
GitHub documentation support was introduced in September 2019
(https://groups.google.com/forum/#!topic/jenkinsci-dev/VSdfVMDIW-A[announcement]).

For new plugins we recommend storing documentation in the GitHub repositories.
It allows plugin maintainers to provide the same documentation from README pages and the Jenkins plugin site,
and at the same time it allows using the Documentation-as-Code techniques when the documentation is a part of the
repository and hence all common practices can be applied 
(versioning, pull requests and reviews, creating documentation in parallel with features, editing docs from GitHub Web UI).

=== Using GitHub as a source of documentation

The plugin site can pull documentation from the root README pages or from other locations defined by the plugin URL (see below).
Multiple formats are supported: GitHub Markdown, Asciidoc or raw text.

To publish the plugin documentation on GitHub...

. Create a README page and put the plugin documentation there.
  This page will become a landing page for the link:https://plugins.jenkins.io/[Plugin site].
** More documentation pages can be introduced inside the repository and
linked from the README, the plugin site will display both absolute and
relative links
** Images from pages will be displayed by the plugin site as well
. Modify your project URL to point to the GitHub repository, e.g. `http://github.com/jenkinsci/your-plugin`.
  See the guidelines for Maven and Gradle below.
. Release the new plugin version.
  After several hours, the link:https://plugins.jenkins.io/[Plugin site] with start using it as a documentation source.

Documentation examples:

* https://plugins.jenkins.io/configuration-as-code
* https://plugins.jenkins.io/gradle
* https://plugins.jenkins.io/mailer

=== Using Jenkins Wiki as source of documentation

link:https://wiki.jenkins.io[Jenkins Wiki] can still be used for previously created plugins or for new plugins if there are reasons to do so.
See link:../wiki-page[this page] for more information.

=== Referencing the documentation page from the project file

You should link to your plugin's documentation, whether on the wiki or elsewhere, in your plugin's pom.xml, like this:

```xml
<project>
  ...
  <url>http://github.com/jenkinsci/your-plugin</url>
  ...
</project>
```

If you're building your plugin with https://github.com/jenkinsci/gradle-jpi-plugin[Gradle], 
you can set the URL in your `+build.gradle+` like so:

```groovy
jenkinsPlugin {
  // ...
  url = 'http://github.com/jenkinsci/your-plugin'
  // ...
}
```


This ensures that the update center will list your plugin correctly once
the new plugin version is released. If this is missing, or does not
point to your Jenkins wiki page, your plugin will not be included in the
update center.

== Adding Maintainer Information

Maintainer information is listed for every plugin on the https://plugins.jenkins.io/[plugin site].

In your POM, make sure to include developer information, such as:

```xml
<project>
  ...
  <developers>
    <developer>
      <id>exampleauthor</id>
      <name>Author Name</name>
      <email>author@example.com</email>
    </developer>
  </developers>
</project>
```


The ID is your jenkins-ci.org account. The name is a human readable
display name. This ensures that the update center and related tools are
able to properly display the maintainer for your plugin. +
It's highly advisable to include an email address so that people can
contact you (this will be shown in the plugin infobox on the wiki), but
it's optional. If pull requests go unmerged for a long time, and there's
no way of contacting you, the maintainer, others will be encouraged to
take over maintainership.

== Changelogs

Once you have made your first release, you should add release notes to your plugin. 
You have many options how to do it:

* use GitHub Releases (possibly with the help of
https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc[Release Drafter]), 
add a link to releases page to your documentation page
(recommended)
* create a CHANGELOG file (Markdown, Asciidoc) in the repository root and link it from the documentation page
* include the changelog content in the documentation page

== Contributor documentation

For open-source plugins it is important to have contributor guidelines to attract more contributors.
GitHub offers standard ways to define guidelines and to show them to contributors,
including contributing guidelines, code of conduct, pull request templates, etc.

Some notes:

* `CONTRIBUTING` guidelines can be defined by plugin maintainers, we do not set a default guide at the moment.
  See link:https://help.github.com/en/articles/setting-guidelines-for-repository-contributors[Setting guidelines for repository contributors] for more information
* Jenkins has a link:https://jenkins.io/project/conduct/[Code of Conduct] which applies to any contributor and to any component hosted by the project.
  It is defined for all repositories using the link:https://github.com/jenkinsci/.github[jenkinsci/.github] repository,
  plugin maintainers do not need to set it up.
* Pull request templates can be created by plugin maintainers if needed.
  See link:https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository[Creating a pull request template for your repository].
