---
title: Plugin Site
layout: developersection
references:
- url: https://plugins.jenkins.io/
  title: Plugin site
- url: ../documentation/
  title: Plugin documentation
---

This page explains how https://plugins.jenkins.io/[the plugins site]
works.

This is not a manual on how to _use_ the site to e.g. find plugins, but
rather explains how it gets its data and how plugin developers can
change the data on it.

== Data shown on the plugins site

=== Which plugins are listed? How can I make my plugin appear?

All plugins published to the current (weekly) update center are listed.

=== What is the plugin installation trend based on?

This uses the monthly data from https://stats.jenkins.io as gathered
from Jenkins instances that have not opted out of reporting data.

Learn more on the link:../usage-statistics[usage statistics page].

=== What does "most installed" mean?

This ranks plugins by the number of different Jenkins instances that
reported the plugin installed during the previous month.

=== What does 'Recently updated' mean?

This is based on metadata created by the update site generator, which
uses the creation date of a plugin release.

Note that very recent plugin releases may not appear here due to caching
and delays in data aggregation.

=== What does 'Trending' mean?

This is an attempt to capture the plugins whose popularity is growing
rapidly.
As we only have the monthly installation stats for this, it's
necessarily a worse approximation than what you'd likely see e.g. in app
stores.

Currently (2019-10) this just divides the previous month's install count
by the month before that.
Plugins with the greatest numbers are shown in
descending order.

=== What are categories based on?

Categories are based on link:https://github.com/jenkins-infra/update-center2/blob/master/src/main/resources/label-definitions.properties[label-definitions.properties]
 in the link:https://github.com/jenkins-infra/update-center2/#categorizing-plugins[update-center2] GitHub repository.

See link:../requesting-hosting/#categorize-the-plugin[categorize the plugin] for further documentation.

=== How are plugins labeled?

Plugin labels are assigned to plugin repositories by their maintainers as link:https://help.github.com/en/github/administering-a-repository/classifying-your-repository-with-topics[GitHub topics].
GitHub topics that match entries from the link:https://github.com/jenkins-infra/update-center2/blob/master/resources/allowed-github-topics.properties[plugin label allowlist] are displayed on the plugin site.
The link:../documentation[plugin documentation guide] includes instructions for link:../documentation#documenting-plugins[documenting], categorizing, and link:../documentation#labeling-plugins[labeling] plugins.

=== Where does the description of the plugin come from?

The plugin site will pull content from a specified Markdown or AsciiDoc file in plugin's GitHub repository, defaulting to the README file.
See link:../documentation/#using-github-as-a-source-of-documentation[documentation] for
how to configure GitHub documentation.

NOTE: In the past it was possible to use Jenkins Wiki as the source of documentation.
After the wiki shutdown the contents are still available, but maintainers are encouraged to link:/doc/developer/publishing/wiki-page/#migrating-from-wiki-to-github[migrate the documentation to GitHub].

=== What is the maintainer information based on?

These are taken from the plugin's latest released version's metadata,
and additionally (if not redundant) includes the user who released that
version.

=== What's the data source for Version, Dependencies and Display Name?

These are all taken from the plugin's latest released version's pom.xml
metadata.

Implicit dependencies (plugins split from core) are included with '(Implied)' after the plugin name.

== Data collection and caching

=== Wiki page data

The plugin site caches wiki pages as needed. The cached copy of each
wiki page is marked invalid after several (2019-10: six) hours.

=== Statistics and other plugin metadata

The data for the plugins site is periodically collected based on the
stats.jenkins.io data and the current update-center.json, and made
available to the plugins site at a known URL.

The plugins site periodically (2019-10: every hour) updates its internal
storage from that URL.
