---
title: Before you start
summary: Read this before you start
layout: developer
---

== Look for similar plugins

We welcome contributions from anyone, but for the benefit of Jenkins users we ask that you look for plugins solving the same or similar problems to see whether you can join forces with existing maintainers.
You can find an overview of existing plugins on https://plugins.jenkins.io. Feel free to ask on the link:/mailing-lists[jenkinsci-dev mailing list] to see whether anyone is aware of another plugin implementing something similar to what you're planning to do.


== Naming Convention

Make sure your plugin follows link:../style-guides/#plugin-naming-convention[the naming conventions].


== License

All plugins distributed by the Jenkins project need to be free and open source software.
This applies to the plugin source code as well as all its dependencies.
Make sure to specify the license both in the `pom.xml` file, as well as a `LICENSE` file in your repository.

We recommend use of the MIT license which is used for Jenkins core and most plugins and libraries, but any link:https://opensource.org/licenses/[OSI-approved] or link:https://en.wikipedia.org/wiki/Public-domain-equivalent_license[public-domain-equivalent] license or public domain dedication will do.

Library plugins, which exist only to wrap some third-party library to implement dynamic linking,
may be licensed under either the MIT license or the license of the library being wrapped.
When these library plugins deliver nontrivial Jenkins-specific production code, the MIT license is appropriate;
however, when the only Jenkins-specific code is in build and test logic, we prefer the license of the library being wrapped for simplicity and consistency.

== Documentation

We recommend that plugins include user documentation so users understand quickly what the plugin does and how to use it.
We recommend following the documentation-as-code approach and keeping the documentation directly in the plugin repository.

See link:../documentation[Documentation] for more information.

== Signup Required

Jenkins plugins distributed via Jenkins project update sites need to be hosted in the link:https://github.com/jenkinsci[jenkinsci GitHub organization], so you will need a user account on GitHub.

To actually release your plugin, you will need a link:https://accounts.jenkins.io[Jenkins community account] that will give you access to the link:https://issues.jenkins.io/[Jira issue tracker] and link:https://repo.jenkins-ci.org/[Maven repository]. 

You should receive a welcome email confirming your Jenkins community account was created successfully.
If you do not receive any email, please open a ticket on the link:https://github.com/jenkins-infra/helpdesk/issues[Jenkins Infrastructure Help Desk].

Even if you choose to track your plugin's issues on GitHub, link:/security/for-maintainers/[you may be assigned security vulnerabilities in your plugin in Jira].
