---
title: Publishing Experimental Plugin Releases
layout: developerguide
---

To simplify delivery of beta versions of plugins to interested users, the Jenkins project publishes an _experimental update center_.
It includes alpha and beta versions of plugins, which aren't usually included in the regular update center.

== Creating Experimental Plugin Releases

Plugin releases that contain `alpha` or `beta` in their version number will only appear in the experimental update site, not in the regular update center.
The experimental update center also serves regular releases.
Newer releases hide older releases in all update centers.
For example, the release of version `1.4` will hide `1.3-beta-2` from the experimental update center.

Note that **only** `alpha` and `beta` strings in the version number will publish to the experimental update center.
Other version strings like `proto`, `rc`, and `unstable` **will appear** in the regular update center.

== Using the Experimental Update Center

Experimental Update Center is not enabled by default in Jenkins, additional steps are needed to enable it in Jenkins.

=== From the Web interface

Users who are interested in downloading experimental plugin releases can go to _Plugin Manager_, then to the _Advanced_ tab, and configure the update center URL `\https://updates.jenkins.io/experimental/update-center.json`.
Submit, and then select _Check Now_.
Experimental plugin updates will be marked as such on the _Available_ and _Updates_ tabs of the _Plugin Manager_.

Once you install the beta plugins that you wanted, you can switch back to the default `\https://updates.jenkins.io/update-center.json` update center URL.
The experimental update center only offers the latest version of each plugin, even if it is incompatible with your version of Jenkins.

=== In Jenkins Configuration-as-Code plugin

plugin:configuration-as-code[Jenkins Configuration-as-Code plugin] allows configuring update centers in configuration YAMLs.
Once configured, it will be possible to install experimenta plugins and versions from the _Plugin Manager_ Web UI.

```yml
jenkins:
  updateCenter:
    sites:
      - id: "default"
        url: "https://updates.jenkins.io/update-center.json"
      - id: "experimental"
        url: "https://updates.jenkins.io/experimental/update-center.json"
```

=== In official Docker images

Official link:https://github.com/jenkinsci/docker[Jenkins Docker image] includes plugin management scripts which allow preinstalling plugins from the Experimental update center.
See the documentation and examples link:https://github.com/jenkinsci/docker#preinstalling-plugins[here].
