---
title: Publishing Experimental Plugin Releases
layout: developerguide
---

To simplify delivery of beta versions of plugins to interested users, the Jenkins project published an _experimental update center_.
It will include alpha and beta versions of plugins, which aren't usually included in the regular update sites.

== Creating Experimental Plugin Releases

Plugin releases that contain `alpha` or `beta` in their version number will only show up in the experimental update site.
Note that it also serves regular releases, so the release of version `1.4` will result in `1.3-beta-2` no longer being available.

== Configuring Jenkins to Use Experimental Update Center

Users who are interested in downloading experimental plugin releases can go to _Plugin Manager_, then to the _Advanced_ tab, and configure the update center URL `\https://updates.jenkins.io/experimental/update-center.json`.
Save, and then select _Check Now_.
Experimental plugin updates will be marked as such on the _Available_ and _Updates_ tabs of the _Plugin Manager_.

Once you install the beta plugins that you wanted, you can switch back to the default `\https://updates.jenkins.io/update-center.json` update center URL.
