---
title: Guide to Plugin Hosting
layout: developerguide
---

This guide will cover the entire plugin hosting process.

Once you've completed all steps described on this page you will have accomplished the following:

* Your plugin source code will be hosted in a repository in the `jenkinsci` GitHub organization.
  You will have admin access to this repository.
* You will be allowed to release the plugin to the Jenkins project Maven repository, which serves as a source for the Jenkins project operated update sites.

== Preparation

Complete the following steps before requesting plugin hosting with the Jenkins project:

. Review the link:../preparation[preparation steps] and make sure they're satisfied.
. Make sure your plugin follows the plugin naming convention outlined in the link:../style-guides[style guides].
. Have a public repository containing the plugin source code on GitHub.


== Open HOSTING request

[NOTE]
Our automated process makes it much easier to fork + delete (see below), rather than transfer repository ownership.
If your repository already has a significant number of forks, issues, pull requests, or other auxiliary data, we can manually transfer it -- just request so in the hosting request, and provide an explanation.

Log in to link:https://issues.jenkins-ci.org/[JIRA] and create a new issue link:https://issues.jenkins-ci.org/browse/HOSTING[in the HOSTING] project.
Make sure to fill out all fields as described.

A Jenkins project member will review your request within a few days.
If any changes are requested, please implement them.

Once all requirements have been satisfied, your repository will be forked into the `jenkinsci` organization and you will be invited to join it, and a JIRA component in the JENKINS project will be created for you.

At this point, you're asked to delete your repository we forked from.
You can recreate it afterwards by forking from `jenkinsci` again.
This will ensure that the `jenkinsci` repository is the root of the network graph on GitHub.
This means:

- There will be no confusion which repository is the canonical one.
- https://help.github.com/articles/searching-in-forks/[Source code search] will succeed even without a significant number of watchers on GitHub.
- Others are more likely to file pull requests in the `jenkinsci` repository (which is ideal for collaboration).

== Enable CI Builds

The Jenkins project hosts a Jenkins instance to perform continuous integration builds for plugins.
We recommend you set up CI builds for your plugin in the `jenkinsci` GitHub organization by creating a `Jenkinsfile` in your plugin's GitHub repository.
See link:../continuous-integration[the documentation for CI builds] for details how to do this.


== Request Upload Permissions

After your plugin source code has been forked into the `jenkinsci` organization, you will need to file a request for upload permissions.
link:https://github.com/jenkins-infra/repository-permissions-updater/[Follow the instructions in the README of this repository] to do that.

Once you've completed this step and your request has been merged, you will be able to link:../releasing/[release your plugin].
See that guide for release instructions.


== Categorize the Plugin

Jenkins shows plugins in categories that are defined in the update site.
See https://github.com/jenkins-infra/backend-update-center2#categorizing-plugins[the update center generator README] for more information.
