---
title: Usage Statistics
layout: developersection
---

== Overview

Anonymous usage statistics are collected from Jenkins controllers that have not opted out from this.
They help us identify trends in Jenkins use and configuration, like the popularity of plugins and average number of plugins installed on controllers.

Those usage statistics are encrypted on individual Jenkins controllers and sent to the Jenkins project infrastructure, where they are stored.
Decryption and anonymization is done in one step using the https://github.com/jenkins-infra/usage-log-decrypter[Usage Log Decrypter] to ensure no private data, like private-source plugin usage information, is published.
Only members of the link:/project/governance/#governance-board[Jenkins governance board] have the decryption key.

The data is then further transformed using https://github.com/jenkinsci/infra-statistics[various scripts] and then published on https://stats.jenkins.io

== Published Statistics

A number of different statistics are published on https://stats.jenkins.io/[stats.jenkins.io].
The following stats are most useful to plugin developers:

* https://stats.jenkins.io/plugin-installation-trend/[Plugin Installation Trend] contains the raw numbers for known installations of each plugin, both by version and total.
* https://stats.jenkins.io/pluginversions/[Install Counts Per Plugin Version and Core Version] provides tables showing what versions of any given plugin are installed on what versions of Jenkins.
  This can help plugin maintainers decide on Jenkins baselines to depend on.
