---
title: Plugin Wiki Pages
layout: developersection
references:
- url: ../documentation/
  title: Plugin documentation
---

WARNING: This page describes hosting of plugin documentation on link:https://wiki.jenkins.io[the Jenkins wiki].
For newly created plugins it is recommended to keep plugin documentation in GitHub repositories.
See link:../documentation[this page] for the guidelines.

Plugins should have user documentation outside the plugin itself so that potential users can learn about the plugin without installing it.
A common way to do this is to create a plugin wiki page on link:https://wiki.jenkins.io[the Jenkins wiki].

== Creating a wiki page

Plugin wiki pages should be organized as child pages of the https://wiki.jenkins.io/display/JENKINS/Plugins[Plugins] page.
Go to that page, be sure to be logged in, and click _Create_ in the page header.
The page you'll create will automatically be added as a child of the Plugins page.

== Content recommendations

=== Plugin macro

Use the `+{jenkins-plugin-info:pluginId=YOUR-ARTIFACT-ID}+` macro near the top of your plugin's wiki page.
It will link to the plugin's page on the link:../plugin-site[plugin site], as well as any security warnings applicable to the plugin to warn users.footnoteref:[previously,Before the plugin site existed, the wiki macro included various statistics, but that was removed as redundant.]


=== Documentation

The wiki page should contain basic documentation that explains what the plugin does, and how to configure it in Jenkins.
This documentation should be kept up to date as the plugin changes.
Note that it is best to keep the documentation as a whole in mind when amending it:
For example, don't just add new sections at the bottom when you add new features, but write the documentation so that someone new to the plugin has the best experience reading the documentation.


=== Changelog

Include a changelog that shows the changes in every version you release.
Keep in mind that many Jenkins users are not necessarily Java developers, so focus on the effect of a change to users, rather than exactly what code you changed.
People can always read the source code if they want to know exactly what was changed.

=== Basic macros only

If a plugin links to its wiki page from its metadata (defined using the `<url>` tag in the `pom.xml`), the plugin site will scrape the wiki and include the page contents directly.
If a non-wiki URL is specified, for example to a GitHub repository, it will only show a link instead.

Given the limitations inherent in including scraped content, many advanced macros will not show up properly on the plugin site:
Basically every macro that uses AJAX to load data in the background will not work.
Since Jenkins will link to the plugin's page on the plugin site from its plugin manager, this will result in a bad experience reading broken documentation for many users.

== Migrating from Wiki to GitHub

Document migration can be done in a semi-automated way using the link:https://pandoc.org[Pandoc] tool for Wiki->Asciidoc conversion.
This guide shows how to do so for a common case when the documentation page is going to be sourced from the README file inside the repository's root.

NOTE: If there is no ticket for the documentation migration created by the current plugin maintainers,
make sure to create one and then discuss with the plugin maintainers.
Similarly, Asciidoc/Markdown preferences should be also discussed with maintainers.

. Fork the plugin repository in GitHub and clone it to the local machine.
. Open the plugin's Wiki page page you want to migrate.
. In the "..." button in the top right corner click the _View Source_ action. A new window will open.
. Save the document as HTML to the repository, e.g. as `myplugin.html`.
. Call `pandoc -o myplugin.md --extract-media=docs/images myplugin.html`.
  Asciidoc format can be used as well, with the `.adoc` extension.
. Review/edit the exported file formatting
** Remove the macro references in the top of the document.
** If the document includes "Table of contents", remove this section in Markdown 
   or replace it by `:toc:` macros in Asciidoc (link:https://raw.githubusercontent.com/jenkinsci/.github/master/.github/release-drafter.adoc[example]).
** If the source Wiki page includes code blocks, they will need to be manually converted. 
   Pandoc exports them as tables.
. Merge the exported file with existing README file. 
  If it does not exist, just rename the file.
. Review the contents.
** Plugin Wiki pages often contain changelogs.
   It is recommended to extract them to a separate `CHANGELOG.md` file in the repository root.
** Wiki pages are often outdated, and it is nice to review them before submitting 
   (e.g. rename "slave" to "agent", "workflow" to "pipeline", "Hudson" to "Jenkins", etc.)
. Modify the URL documentation page reference in the project file so that it points to GitHub (link:/doc/developer/publishing/documentation/#referencing-the-documentation-page-from-the-project-file[documentation]).
. Commit changes, push them to your fork and create a pull request against the repository.
. Once the pull request is merged, replace the content on Wiki by a link to the new GitHub location
  (use info boxes to do that).
