---
title: Plugin Wiki Pages
layout: developersection
references:
- url: ../documentation/
  title: Plugin documentation
- url: https://reports.jenkins.io/jenkins-plugin-migration.html
  title: Plugin migration progress report
---

WARNING: The Jenkins wiki was made 'read-only' in link:https://groups.google.com/d/msg/jenkinsci-dev/lNmas8aBRrI/eL3u7A6qBwAJ[October 2019]. 
In September 2021, link:/blog/2021/09/04/wiki-attacked/[Jenkins wiki was attacked] and as a result, the impacted server was permanently disabled and the site was rendered static.
Plugin documentation is now maintained in the GitHub repository of the plugin.
See the link:../documentation[plugin documentation guidelines] for details.

Plugin documentation is available from the link:https://plugins.jenkins.io[Jenkins plugins site] so that potential users can learn about the plugin without installing it.

== Migrating from Wiki to GitHub

All plugin documentation has been converted to markdown and is stored in the link:https://github.com/jenkins-infra/plugins-wiki-docs/[plugins-wiki-docs] repository.
This guide will walk you through the process of migrating plugin documentation from the plugins-wiki-docs repository to the plugin repository, so that it is sourced from the README file inside the repository's root.

NOTE: If there is no ticket for the documentation migration created by the current plugin maintainers,
make sure to create one and then discuss with the plugin maintainers.
Similarly, Asciidoc/Markdown preferences should be also discussed with maintainers.

The following list provides the migration steps:

. Search for the plugin to update in the link:https://reports.jenkins.io/jenkins-plugin-migration.html[plugin migration progress report].
** If the status of the plugin is _TODO_ move on to step two, else retry step one with a different plugin.
. Fork the plugin repository in GitHub and clone it to your local machine.
. Search for and open the plugin page in the link:https://github.com/jenkins-infra/plugins-wiki-docs/[plugins-wiki-docs] repository.
. Copy the README.md file and all docs/images to the plugin repository.
** You can merge the copied file with the existing README file or create a new one.
. Copy-edit the documentation as described <<copy-edit-documentation, below>>.
. Modify the URL documentation page reference in the project file so that it points to GitHub (link:/doc/developer/publishing/documentation/#referencing-the-documentation-page-from-the-project-file[documentation]).
. Commit changes, push them to your fork, and create a pull request against the repository.
. Configure a redirect from the out-of-date wiki page to the migrated content (see <<configuring-wiki-redirects, Configuring Wiki Redirects>> below).

NOTE: After migration, the continued existence of out-of-date wiki pages causes several problems, such as duplication, confusion, and unclear migration progress.
This persistence makes it harder to identify which pages have migrated and those waiting for migration.
If you cannot identify migrated pages, this creates a major technical obstacle in content migration from the wiki.

[[copy-edit-documentation]]
=== Reviewing the documentation

. Review/edit the migrated file formatting.
** If the document includes "Table of contents", remove this section in Markdown 
   or replace it using the `:toc:` macros in Asciidoc (link:https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc?plain=1[example]).
** If the source Wiki page includes code blocks, they will need to be manually converted. 
   Pandoc exports them as tables.
. Extract changelogs to a separate file or create GitHub releases for past versions.
** If you create a changelog file, extract the changelogs to a separate `CHANGELOG.md` file in the repository root.
   It allows tools like Dependabot to read changelog summaries.
** Use versions as headers.
   Changelogs in Wiki often include release dates, but it is better to keep them in the text below the header.
** Examples: link:https://github.com/jenkinsci/envinject-api-plugin/blob/master/CHANGELOG.md[EnvInject API Plugin], link:https://github.com/jenkinsci/aws-java-sdk-plugin/blob/master/CHANGELOG.md[AWS Java SDK Plugin]
. Review the text.
** Verify formatting and spelling.
** Wiki pages are often outdated, and it is nice to review them before submitting 
   (e.g. rename "slave" to "agent", "workflow" to "pipeline", "Hudson" to "Jenkins", etc.).
. Check that the images are not outdated.
** A lot of UI changes have occurred, and wiki pages often contain out-of-date images (images that contain keywords like Hudson will need to be replaced).
. Commit changes, push them to your fork and create a pull request against the plugin repository.
. Once the pull request is merged, create an `INFRA` Jenkins JIRA ticket to replace the content on Wiki by a link to the new jenkins.io locations.

[[configuring-wiki-redirects]]
=== Configuring Wiki Redirects

After successfully migrating plugin documentation from the wiki to GitHub, it's important to configure redirects from the old wiki pages to prevent duplication and confusion.
This ensures that users who find old wiki links are automatically directed to the current documentation.

To configure a redirect from an old wiki page:

. Fork the link:https://github.com/jenkins-infra/docker-confluence-data[docker-confluence-data] repository.
. Edit the link:https://github.com/jenkins-infra/docker-confluence-data/blob/main/nginx/nginx.conf[nginx/nginx.conf] file.
. Add a `rewrite` rule for your migrated page using the following format in the appropriate section:
+
[source,nginx]
----
rewrite ^/display/JENKINS/Old\+Wiki\+Page$ https://plugins.jenkins.io/plugin-name/ permanent;
----
+
Where:
** `^/display/JENKINS/Old\+Wiki\+Page$` is the path to the old wiki page (spaces are replaced with `\+`)
** `https://plugins.jenkins.io/plugin-name/` is the URL to the new documentation location
** `permanent` indicates this is a 301 (permanent) redirect
. Commit your changes and create a pull request against the docker-confluence-data repository.
. Reference the pull request in your wiki migration issue or pull request.

For inspiration and examples of redirect configurations, see link:https://github.com/jenkins-infra/docker-confluence-data/pull/41[this example PR].

[TIP]
====
When adding redirects:

* Ensure you escape special characters in the wiki page path (spaces become `\+`, other special characters may need escaping)
* Test that the old wiki URL path is correct before submitting your PR
* Group related redirects together in the nginx.conf file for better maintainability
* Add a comment above your redirect rules indicating which plugin or pages are being redirected
====
