---
layout: gsocprojectidea
title: "Add probes to \"Plugin Health Score\""
goal: "First iteration of the tool provided a limited set of probes. To improve the effectiveness of the scoring system, more probes are needed."
category: Tools
year: 2023
status: draft
sig: platform
skills:
- Java
- YAML
- Command line tools
- Package management tool theory
mentors:
- "gsoc"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-add-probes-to-plugin-health-score/4838
//   gitter: "jenkinsci/plugin-installation-manager-cli-tool"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---
=== Background

Keeping a plugin current with the ongoing development of Jenkins is key for a smooth operation.
Keeping it current can require user interface improvements, dependency updates, and more.

Measurements of the plugin's "health" will help **maintainers** as they decide how to invest their development time.
With such a system, items that need to be maintained, improved, or adapted are identified. +
For example, having Release Drafter correctly configured and Pull Request Labeling in place is a recognized good practice.
It reduces the effort to provide a changelog with each release. +
Another example: having Dependabot properly configured will reduce the dependency update effort by automatically submitting update pull requests.

Measurements of the plugin's "health" will help **users** to decide if they should install and use a plugin.
Plugins with a lower health score may be less likely to meet the user's reliability needs.
It is similar to a badly maintained garden that will make harvesting difficult and not yield good vegetables or fruits.

The plugin health score already provides a few probes to measure the health of a plugin. Now it's your turn to implement more probes.

=== Quick Start

A presentation of the "Plugin Health Score" project was made during the link:https://community.jenkins.io/t/gsoc-office-hours-emea/1471[10-Feb-2022 GSoC Office Hour].

video::i7Y0FM1tms4[youtube,width=800,height=420,start=488]

A presentation of the status of the "Plugin Health Score" project at the end of GSoC 2022 was made during the link:https://community.jenkins.io/t/jom-jenkins-gsoc-project-2022-final-edition/3826[05-Oct-2022 GSoC Final Edition].

video::fM2SMbppRxw[youtube,width=800,height=420,start=328]

=== Conceptual structure/idea

This project is articulated around four axes:

* data collection
* data aggregation
* data presentation
* data delivery

==== Data Collection

Each data point is retrieved by running an atomic analysis probe on the plugin.
Probes could be "Version of plugin parent pom", "Number of installations", etc.

Some measurement ideas are listed in the link:https://community.jenkins.io/t/gsoc-2023-project-idea-add-probes-to-plugin-health-score/4838/11["Add probes to “Plugin Health Score”"] community discussion.

Typical work on that axis would cover probe identification and description,
probe algorithm definition,
probe proof of concept, and lastly probe implementation.
An important step is to run the probe on all the plugins to gather statistical data to validate the probe and the thresholds.

==== Data Aggregation

The actual "health score" of a plugin is computed by aggregating probe measurements.
It is calculated based on the measurement's deviation from the expected score (or range).

==== Data Presentation

The health score and the probe details need to be presented to the user.
This part of the project has to deal with where and how the collected data is presented (summary, diagramming, details, navigation/drill down)

==== Data Delivery

This axis covers how the probes are run, the data collected and displayed.
It covers thus the "industrialization" of the feature.
Aspects such as deployment, infrastructure, monitoring are very important.

=== Skills to Study and Improve

* Java
* Data extraction from GitHub repositories
* Data analysis applied to data representation.

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours


=== Expected outcomes

New probes to help improve the plugin health score.

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.

// === Newbie Friendly Issues
