---
layout: gsocprojectidea
title: "Building Jenkins.io with alternative tools"
goal: "Using alternative tooling (i.e., Antora) to build the Jenkins static site and provide documentation per Jenkins version"
category: Tools
year: 2023
status: published
sig: documentation
skills:
- Web development
- AsciiDoc
- Static website tooling
- Proof of concept
- Documentation
mentors:
- "krisstern"
- "iamrajiv"
- "markewaite"
links:
   emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-jenkins-io-with-alternative-tools/4863
//   gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---

=== Background
link:/[Jenkins.io] is generated as a static website using Awestruct from AsciiDoc sources, YAML data files, and HAML templates stored in GitHub.
One of the drawbacks of the current build method is that the technical documentation is not product version bound.
It is thus not possible to view the documentation for a given Jenkins version.
Only the latest can be viewed.
This can lead to unnecessary confusion and is a worse experience than many other documentation sites like the git site, FreeBSD, and others..

The preferred tool to replace Awestruct is link:https://antora.org/[Antora].

The potential GSoC project would be to build a working site generator to demonstrate the existing site.
Once the existing site is generated with Antora, the site should be extended to add version specific documentation.

The project has been discussed extensively at link:https://github.com/jenkins-infra/jenkins.io/issues/5474[GitHub issue #5474], where some existing proof-of-concept code can be found referenced there.

There are multiple ways to approach the implementation, but from experimentation it has been found that the backend replacement requires minimal effort for the documentation, with the frontend implementation expected to require much effort to reproduce the look and feel of the current link:/[jenkins.io] website. However, the blog can be split from the documentation using something like link:https://www.gatsbyjs.com/[Gatsby], which is expected to make it easier for users to submit posts in the future.

While the tasks of the project are very clearly defined, the scope may vary depending on the plans of the contributor. If we split the project into milestones, we see three important ones that can be tackled in sequence: The most urgent milestone is (1) to set up the user documentation using Antora with versioning, while next would be (2) to set up the developer documentation with Antora without versioning, and finally (3) to set up the blog using Gatsby. The contributor can choose either 1, or a combination of 1 + 2, or a combination of 1 + 2 + 3, but not in any other way. The expected project outcome is at least a drop-in replacement website that is building locally.

The outcome of this project is expected to produce visible impact they can showcase in their portfolio of the link:/[jenkins.io] website, as the GSoC contributor is also expected to contribute via UI/UX improvements beyond the basic tooling required.

Please note that for the UI/UX improvement portion we may need to deal with the link:https://github.com/jenkins-infra/jenkins-io-components[jenkins-io-components repo], where the code for components shared by various Jenkins websites (link:/[jenkins.io], link:https://plugins.jenkins.io/[plugins.jenkins.io], etc.) is currently hosted.

=== Quick Start

Documentation quick start steps include:

* Build the current documentation site locally
* Become familiar with the current site, including:
** Page types and how they are generated
*** Changelogs
*** Roadmap
*** User handbook
*** Developer handbook
*** Artwork
*** Security advisories
*** Version specific content in tutorials (like "Improve a plugin")
** Page content sources
*** Asciidoc
*** HAML / Ruby
*** Web components
** Build process
*** Makefile
*** Docker containers
*** Syntax and spelling checks
* Fix several link:https://github.com/jenkins-infra/jenkins.io/labels/good%20first%20issue/["good first issues"]
* Explore link:https://github.com/jenkins-infra/jenkins-io-components[jenkins-io-components repo]
* Explore link:https://antora.org/[Antora]
* Review version specific documentation techniques (some of them are Antora sites)
** link:https://docs.cloudbees.com/docs/cloudbees-ci/latest/cloud-secure-guide/folders-plus[CloudBees documentation site]
** link:https://git-scm.com/docs/git-config[Git reference pages]
** link:https://docs.python.org/3/[Python] (sphinx is the generator)
** link:https://pytorch.org/docs/stable/index.html[PyTorch]
** link:https://www.tensorflow.org/api_docs[TensorFlow]

=== Skills to Study and Improve

* Web development
* AsciiDoc
* Static website tooling
** HAML templates
** YAML data files
* Proof of concept
* Documentation

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 to 350 hours

=== Expected outcomes

The deliverables of the project(s) would be:

1. Iterative and incremental improvements to the site throughout the project
2. A fully automated (CI ready) build procedure, equivalent to the existing one, but using Antora
3. Demonstration that all the existing pages are rendered in an equivalent way
    - Suggestions of improved page design(s)
    - A list of all automation that are difficult/impossible to port to the new tool
    - Suggestions and demos of alternative ways to solve this
4. Demonstration of the versioned documentation automated tooling
    - Description of the publication process (how does one contribute to document a new or modified feature)

=== New features

Improved layout of the existing site and its pages.

=== Newbie Friendly Issues

Basically any good-first-issue listed in the jenkins.io GitHub repo would do. These can be accessed at the link:https://github.com/jenkins-infra/jenkins.io/labels/good%20first%20issue/[GitHub repo issues tracker with the "good first issue" label].
