---
layout: gsocprojectidea
title: "Building iOS Apps with Jenkins"
goal: "Describe best practices and provide architectural templates for building iOS applications with Jenkins"
category: Tools
year: 2023
status: draft
sig: platform
skills:
- Java
- YAML
- iOS development
- Command line tools
- Package management tool theory
mentors:
- "gounthar"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-ios-apps-with-jenkins/4799
---
//   gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc

=== Background

Applying CI principles when building iOS applications brings its own challenges, different from those of more classical applications.
How to proceed, what are the successful patterns, what are the pitfalls is poorly documented. 
It very often requires potential user and Jenkins Administrator to "reinvent the wheel".

The project idea is to have a clear status of what can be done with Jenkins for iOS app builds now.
There are only a few articles here and there about iOS.

//
// === Quick Start
// TBD
//
=== Skills to Study and Improve

- Jenkins technical architecture
- iOS application development
- CI principle and practice

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours

=== Expected outcomes

* A working iOS application CI build with Jenkins from a public GitHub public repository (Proof of Concept).
* A proposed architecture that would work for almost anyone (so Docker whenever it’s possible, or virtual machines) using a public GitHub repo.
* The required additional tooling to make it all work.
* At least one blog post explaining how to replicate the POC, preferably a full documentation to be integrated in Jenkins.io


Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase. 
// 
// === Newbie Friendly Issues
