---
layout: gsocprojectidea
title: "Building Android Apps with Jenkins"
goal: "Describe best practices and provide architectural templates for building Android applications with Jenkins"
category: Tools
year: 2023
status: discussion
sig: platform
skills:
- Java
- YAML
- Command line tools
- Package management tool theory
mentors:
- "gsoc"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-android-apps-with-jenkins/4798
---
//   gitter: "jenkinsci/plugin-installation-manager-cli-tool"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc

=== Background
I've been playing with CI/CD for mobile apps for more than eight years (mostly with gitlab-ci).
Since last June, I am experimenting with Jenkins to build and publish Android apps, mostly with Docker.
I already have a working prototype and gave a talk 1 about it last month.

The thing is I created that very naively, starting with my old Gitlab habits.
Furthermore, I was not looking for the perfect Android apps building Jenkins architecture, just a Jenkins system that would allow anyone to start it with just one command line.
That's why I went the docker-compose way. The proof of concept works under Windows, Linux, Vagrant, macOS (x86 and ARM), and mostly on Gitpod, but… It's not (yet) something you can copy and paste to production.
It is composed of a Jenkins controller (using JCasc), an Android agent, a generic Docker agent, an Android emulator, and an Android device farm (STF 1).

The idea is to have a more precise status of what can be done now with Jenkins. We could then amend the existing documentation 1, and describe architectures for:

* Standalone Android projects
* Android apps building farms
* Android distro building (customized AOSP)

//
// === Quick Start
// TBD
//
// === Skills to Study and Improve
// * TBD
//
// === Project Difficulty Level
// 
// Beginner to Intermediate
// 
// === Project Size
// 
// 175 hours
// 
// === Expected outcomes
// 
// New feature
// 
// Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase. 
// 
// === Newbie Friendly Issues
