---
layout: gsocprojectidea
title: "Docker-based Jenkins quickstart examples"
goal: "Provide examples, sample code, and documentation on how to start a local Jenkins instance."
category: Tools
year: 2023
status: published
sig: platform
skills:
- Java
- YAML
- Command line tools
- Package management tool theory
mentors:
- "gounthar"
- "berviantoleo"
- "sbostandoust"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-jenkins-io-with-docker-compose/4866
//   gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---
=== Background

We already have a link:/doc/book/installing/docker/[section] dedicated to docker in the documentation, but it's too difficult to use for beginners, and even too complex to begin with. 
We need to provide a simple way to get started with Jenkins and Docker.

We could have a set of `docker-compose` files representing various types of Jenkins instances (simple Docker, Kubernetes, …).

These examples would be described in the documentation, and would also (*and that’s the main point*) be tested every week thanks to ci.jenkins.io so that we know they are still working.

As the documentation is using link:https://asciidoc.org/[`asciidoc`] we could use the link:https://docs.asciidoctor.org/asciidoc/latest/directives/include-uri/[Include Content by URI] feature to have an up-to-date documentation when it comes to code snippets and at the same time, have link:https://ci.jenkins.io[`ci.jenkins.io`] test these same code snippets.

Of course, these snippets could also be run thanks to link:https://www.gitpod.io/[GitPod].

=== Quick Start

* link:https://docs.docker.com/compose/install/[Install Docker Compose]
* Clone a link:https://github.com/gounthar/MyFirstAndroidAppBuiltByJenkins[repo] that already uses docker-compose for Jenkins.
* Run `docker-compose up` and wait for the Jenkins instance to be up and running.
* Study the `docker-compose.yml` file to understand what it does.

=== Skills to Study and Improve

* link:https://docs.docker.com/compose/[Docker Compose]
* link:https://docs.docker.com/compose/compose-file/compose-file-v3/[Docker Compose file format v3]
* link:/projects/jcasc/[Jenkins Configuration as Code]
* link:https://plugins.jenkins.io/job-dsl/[Job DSL]
* link:/doc/book/installing/kubernetes/[Kubernetes]

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours

=== Expected outcomes

* A set of docker-compose files that can be used to get started with Jenkins and Docker or Kubernetes on Windows, Linux, macOs, Vagrant and GitPod.
* The documentation that describes how to use these docker-compose files.
* A link:https://ci.jenkins.io[`ci.jenkins.io`] job that tests these docker-compose files every week.


//
// Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase. 
// 
// === Newbie Friendly Issues
