---
layout: gsocprojectidea
title: "Plugin Installation Manager Tool Improvements"
goal: "Introduce new features and improvements in the plugin installation manager"
category: Tools
year: 2023
status: published
sig: platform
skills:
- Java
- YAML
- Command line tools
- Package management tool theory
mentors:
- "markewaite"
- "freyam"
links:
  gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
  draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc
---
=== Background

In 2019 there was a Jenkins link:/projects/gsoc/2019/plugin-installation-manager-tool-cli/[Google Summer of Code project] to create a tool to link:https://github.com/jenkinsci/plugin-installation-manager-tool/#readme[automatically install plugins] from the command line based on a provided input.
This is meant to help with creating reproducible environments and other places where you would want to install a certain set of plugins.
The project was successful in creating a useable tool to install plugins with a 1.0 release.
Over time, the plugin installation manager was improved and added to other components like official link:https://github.com/jenkinsci/docker#preinstalling-plugins[Jenkins container images].

As a part of this project,
contributors are invited to introduce new features and improvements in the plugin installation manager.
The list of enhancements is a subject for discovery as a part of the application process.
Some of the ideas are available in the link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues[project tracker].

Additional background information may be found in a video recording from 2021.

video::QJcwcLnHjRw[youtube, width=640, height=360, align="center"]

=== Quick Start

Visit the link:https://github.com/jenkinsci/plugin-installation-manager-tool[project page] for more details.

1. Clone the project
2. Run the tests; there are several different lists of plugins
3. Run the Plugin Installation Manager for various combinations of plugins with a real Jenkins instance.
   See how the downloads and caching work.
4. Try out some edge cases to see what could be improved.

=== Skills to Study and Improve

* Java
* YAML/data structures/package management tools
* Writing command line interfaces
* How the Jenkins Docker image and Configuration as Code (CasC) work

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours

=== Expected outcomes

Improvements to existing tool

Key improvements for the plugin installation manager tool will be identified, prioritized, and planned.
Google Summer of Code contributor will propose the areas for improvement and work with mentors to plan those improvements.

Some candidate ideas from the mentors include:

* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/237[Add subcommands to the command line arguments] requires a definition and design of the subcommands and their behavior
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/488[Generate plugins.txt file from existing directory]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/432[Optionally show progress bar during download]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/446[Retain comments when creating new file from existing file]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/428[List skipped plugins when broken downloads are skipped]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/321[Report the mirror URL and original URL on download failure]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/312[Improve plugin-versions caching for container builds]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/270[Only download a plugin once per session (test if still an issue)]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/267[Allow security warnings report for only specified plugins]
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/264[Read hpi files from maven cache if found there] (and link:https://issue-redirect.jenkins.io/issue/58217[JENKINS-58217])
* link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues/263[Allow logging to be increased for debug and diagnosis]
* link:https://issue-redirect.jenkins.io/issue/65298[Allow plugin versions from the plugin bill of materials to be preferred over latest version]
* link:https://issue-redirect.jenkins.io/issue/65297[Provide an optional flag that returns an error if a plugin dependency is not in the list of plugins to be installed]
* link:https://issue-redirect.jenkins.io/issue/58129[Add command line option to ignore errors if plugin download fails]
* link:https://issue-redirect.jenkins.io/issue/60654[Document the handling of bundled plugins more clearly]
* link:https://issue-redirect.jenkins.io/issue/59066[Cache downloaded plugin files in the Maven cache]

=== Newbie Friendly Issues

Some good first issues are available in the link:https://github.com/jenkinsci/plugin-installation-manager-tool/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[issue tracker].
For information about how to contribute to and what to work on, please use the link:https://app.gitter.im/#/room/#jenkinsci_plugin-installation-manager-cli-tool:gitter.im[gitter channel].
