---
:layout: post
:title: JUC SF 2014 is Here!
:nodeid: 505
:created: 1409260192
:tags:
  - general
  - meetup
  - news
  - juc
:author: kohsuke
---
https://www.cloudbees.com/event/juc/2014/san-francisco[JUC SF] on October 23, 2014 is shaping up to be bigger and better this year. +


Here’s what we have in store for you! +


== Three Tracks


We’ve received a record high of 40 stellar proposals this year. To accommodate the many community proposals, we’ve decide to add a third track to the +
agenda. https://www.cloudbees.com/event/juc/2014/san-francisco[JUC SF sessions] are now available for you to view. We have speakers from Google, +
Target, Gap, Cloudera, Ebay, Chicago Drilling Company, and much more. https://www.eventbrite.com/e/jenkins-user-conference-us-west-san-francisco-oct-23-2014-tickets-10558684309[Register now] for early bird price. +
The early bird price is only good until September 21, 2014. +


== Live Stream


If you can’t attend the conference in person, https://www.cloudbees.com/event/juc/2014/san-francisco[Track 1] sessions will be available via live +
stream, it’s all free. Brought to you by CloudBees. Registration for JUC SF live stream is https://www.eventbrite.com/e/jenkins-user-conference-us-west-san-francisco-live-stream-tickets-12240011203[here]. +


== Get Drunk on Code


Have a beer while learning how to write Jenkins plugin. Steve Christou, Jenkins support engineer will lead this lecture from 3:30pm to 6:00pm. He will +
teach everything from how to get started, to techniques like writing a new https://wiki.jenkins.io/display/JENKINS/Jenkins+CLI[CLI Command], to writing your own builder. +


== Ask the Experts


Meet the Jenkins creator, committers, support engineers, and developers. We have dedicated time slot(s) for our attendees to get 1 on 1 access to our +
experts. Exact time is TBD. Ask them anything from plugins, configuration, technical support, to bug fixes. +


Our current list of experts are: +


*  +
Andrew Bayer +
*  +
Gareth Bowles +
*  +
Steve Christou +
*  +
Jesse Glick +
*  +
Kohsuke Kawaguchi +
*  +
Dean Yu +


Want to join our panel of experts? Contact Alyssa Tong aly13@gmail.com +


== Exhibit Mixer


Sixteen technology https://www.cloudbees.com/event/juc/2014/san-francisco[sponsors] will be showcasing their newest technologies during +
the exhibition hour from 2:25 – 3:30pm. Grab a beer, visit with sponsors and see how they are using Jenkins. +


This is just a taste of what you’ll see at JUC SF. We look forward to seeing you there!! +
