---
:layout: post
:title: FreeBSD project use of Jenkins for OS testing
:nodeid: 514
:created: 1413821550
:tags:
  - general
  - feedback
  - guest post
:author: kohsuke
---
This is a guest post by Craig Rodrigues

'''

The https://www.freebsd.org[FreeBSD project] produces a modern operating system derived from https://en.wikipedia.org/wiki/Berkeley_Software_Distribution[BSD Unix].

In the past 6 months, we have set up Jenkins at https://jenkins.freebsd.org/, to continuously build FreeBSD as developers add new code to the project. This has helped us identify and fix build breaks very quickly.

We have gone even farther by integrating Jenkins, https://github.com/jmmv/kyua#readme[Kyua],
and http://bhyve.org/[Bhyve].
https://github.com/jmmv/kyua#readme[Kyua] is a testing framework for infrastructure software.
http://bhyve.org/[Bhyve] is the native hypervisor that comes with FreeBSD (similar to KVM on Linux).

We use the https://wiki.jenkins.io/display/JENKINS/Build+Flow+Plugin[Build Flow plugin] in this https://ci.freebsd.org/job/FreeBSD-head-amd64-build/[example Build flow]	 to do the following:

. Build the FreeBSD kernel and userland on amd64 whenever someone checks in new code to https://svn.freebsd.org
. Create a bootable FreeBSD disk image with https://www.freebsd.org/cgi/man.cgi?query=makefs[makefs]
. Boot the image under bhyve
. Run these commands inside the bhyve VM:

----
    cd /usr/tests; kyua test; kyua report-junit --output=test-output.xml
----

. Shut down the bhyve VM
. Imports test-output.xml into Jenkins.
. Produces a https://ci.freebsd.org/job/FreeBSD-head-amd64-test/3069/testReport/[full native test report in Jenkins]

The results of this work were presented at the https://bafug.org[Bay Area FreeBSD Users Group]
in https://www.slideshare.net/CraigRodrigues1/kyua-jenkins[this presentation] in October 2014.

Jenkins has been very easy to set up and use under FreeBSD.   We hope that by using
Jenkins to run OS-level unit tests, we will be able to improve the quality of FreeBSD.
For further information, please feel free to contact us at link:mailto:freebsd-testing@FreeBSD.org[freebsd-testing@FreeBSD.org] .
