////
// This file is only meant to be included as a snippet in other
// documents.  It provides the same text to multiple files so that we can
// make a single change and have it apply to multiple files
////

== Install Apache Maven

Jenkins plugins are built with Apache Maven.

Download Maven from the link:https://maven.apache.org/download.cgi[Apache Maven website].
Make sure to download one of the binary archives (with `bin` in their name).

NOTE: Many Linux distributions provide packages for Maven for an easier install and upgrade experience.
Consult your distribution's documentation for details.
On macOS, the link:https://brew.sh/[Homebrew] package manager offers Maven packages.
Make sure a recent version of Maven 3, ideally 3.8.6 or newer, is provided if you decide to go this route.

Next, you will need to extract Maven and take note of its location.
When you extract the Maven files, make sure you extract them directly into the target directory.
For example, extract the files straight into C:\Program Files (x86)\Maven; do not extract the files to a different location and then copy the files.

Then, add the full path of the `bin/` subdirectory extracted (for example, `~/Applications/apache-maven/bin` or `C:\Program files\Maven\bin`) to the `PATH` variable in your OS.
This will let you invoke Maven using `mvn`.

The rest of the tutorial assumes that Maven is on your `PATH` environment variable.

== Configure Apache Maven

Apache Maven needs to be configured for Jenkins plugin development.
The link:https://github.com/jenkinsci/maven-hpi-plugin[hpi plugin] for Apache Maven requires some additional global configurations to function correctly with older Jenkins plugin environments.

Improper configuration settings can cause Maven to report errors or warnings, including failure to download artifacts during the update process.
To avoid issues, include the following content in the `settings.xml` file in your `~/.m2` directory (Windows users will find them in `%USERPROFILE%\.m2\settings.xml`):

[source,xml]
----
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <pluginGroups>
    <pluginGroup>org.jenkins-ci.tools</pluginGroup>
  </pluginGroups>
  <profiles>
    <profile>
      <id>jenkins</id>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
      <repositories>
        <repository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>repo.jenkins-ci.org</id>
          <url>https://repo.jenkins-ci.org/public/</url>
        </pluginRepository>
      </pluginRepositories>
    </profile>
  </profiles>
</settings>
----
