---
layout: developersection
title: Check dependencies
---

:modified-files: .github/dependabot.yml
:task-identifier: auto-update-deps
:task-description: Automate dependency updates

= Automate dependency updates

.Automate dependency checks with dependabot
video::2c8wK2jkcIA[youtube,width=800,height=420,start=980]

Jenkins plugins frequently depend on external libraries and other plugins.
Automatic dependency checks help assure that new releases of dependencies are reviewed by plugin maintainers.

The GitHub `dependabot` tool can be configured to periodically check for new releases of dependencies.
When a new release is detected, dependabot submits a pull request to include that update in the plugin pom file.

See the link:https://www.youtube.com/watch?v=RXIJpjYlECQ[Jenkins Online Meetup video] for more details on dependabot with Jenkins.

// Create the branch
include::doc/developer/tutorial-improve/_create-a-branch.adoc[]

Automated dependency checks by dependabot are defined in a .github/dependabot.yml file.

[source,bash]
----
mkdir .github
cat > .github/dependabot.yml <<END-OF-HERE-DOC
version: 2
updates:
# Maintain dependencies for your plugin
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
END-OF-HERE-DOC
----

Commit the file and push it to GitHub with the commands:

// Create a pull request
include::doc/developer/tutorial-improve/_create-a-pull-request.adoc[]
