---
layout: developersection
title: Update Jenkins version
---

:modified-files: pom.xml
:task-identifier: require-newer-core
:task-description: Require 2.504.3 as minimum Jenkins version

= Update minimum Jenkins version

.Require a newer minimum Jenkins version
video::Fev8KfFsPZE[youtube,width=800,height=420,start=2430]

Jenkins plugins declare a minimum supported Jenkins version.
The minimum Jenkins version is a good way for plugin developers to indicate the range of Jenkins versions they are willing to support and test.
See the link:/doc/developer/plugin-development/choosing-jenkins-baseline[developer documentation] for the recommended minimum Jenkins version.

// Create the branch
include::doc/developer/tutorial-improve/_create-a-branch.adoc[]

== Update minimum required Jenkins version

Update the minimum required Jenkins version by setting a `jenkins.version` value in the properties section of the `pom.xml` file:

[source,xml,subs="attributes+"]
----
   <properties>
     <jenkins.version>2.504.3</jenkins.version>
   </properties>
----

If the plugin is already using the plugin bill of materials, then the bill of materials also needs to be updated with the matching `artifactId` for the minimum required Jenkins version.
The `version` may also need an upgrade see the link:/doc/developer/plugin-development/dependency-management/#jenkins-plugin-bom[developer documentation].

The `git diff` might look like this:

[source,xml]
----
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.jenkins.tools.bom</groupId>
-        <artifactId>bom-2.426.x</artifactId>
+        <artifactId>bom-2.492.x</artifactId>
-        <version>3208.vb_21177d4b_cd9</version>
+        <version>5294.va_d2e144c80e1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
----

// Compile the plugin
include::doc/developer/tutorial-improve/_compile-the-plugin.adoc[]

// Create a pull request
include::doc/developer/tutorial-improve/_create-a-pull-request.adoc[]
