---
layout: developersection
title: Update parent POM
---

:modified-files: pom.xml
:task-identifier: update-parent-pom
:task-description: Use most recent parent pom

= Update parent POM

.Use latest parent POM
video::Fev8KfFsPZE[youtube,width=800,height=420,start=807]

The Maven project object model ("POM") defines a parent project object model that provides default settings.
An update of the parent POM will allow this plugin to compile with recent Java versions.
The most recent parent POM files also provide additional static analysis like spotbugs and optional automated source code formatting.

// Create the branch
include::doc/developer/tutorial-improve/_create-a-branch.adoc[]

// Install and configure Apache Maven
include::doc/developer/tutorial-improve/_install-apache-maven.adoc[]

// Compile the plugin
include::doc/developer/tutorial-improve/_compile-the-plugin.adoc[]

When modernizing older plugins, You may need to use Java 8 to compile the plugin initially.
Once the parent POM has been updated, you'll be able to compile and test with recent Java versions.

== Update parent POM

Use Apache Maven to update the parent POM:

[source,bash]
----
mvn -ntp versions:update-parent
----
----
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< org.jenkins-ci.plugins:your-plugin >----------------
[INFO] Building Schedule Build Plugin 1.0.0-SNAPSHOT
[INFO] --------------------------------[ hpi ]---------------------------------
[INFO]
[INFO] --- versions-maven-plugin:2.8.1:update-parent (default-cli) @ your-plugin ---
[INFO] Updating parent from 3.50 to 4.47
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.013 s
[INFO] Finished at: 2021-09-26T20:03:00-06:00
[INFO] ------------------------------------------------------------------------
----

Review the change that Apache Maven performed for you with the command:

[source,bash]
----
git diff
----
----
diff --git a/pom.xml b/pom.xml
index e6a8356..3a42d47 100644
--- a/pom.xml
+++ b/pom.xml
@@ -3,7 +3,7 @@
   <parent>
     <groupId>org.jenkins-ci.plugins</groupId>
     <artifactId>plugin</artifactId>
-    <version>3.50</version>
+    <version>4.80</version>
     <relativePath />
   </parent>

   <artifactId>your-plugin</artifactId>
----

// Compile the plugin
include::doc/developer/tutorial-improve/_compile-the-plugin.adoc[]

== Remove `java.level` property

If there is a `<java.level>` property defined in the POM, remove it.
The minimum version required for a specific pom is now implicit in the POM.
The plugin maintainer does not need to specify a `<java.level>` property.

In many cases, other changes will be needed to the pom.xml file in order to use the most recent parent POM.
Some of the other changes may include:

* Resolve spotbugs warnings
* Resolve link:/doc/developer/plugin-development/updating-parent/#understanding-requireupperbounddeps-failures-and-fixes[upper bounds dependency warnings]
* Prevent cross-site scripting by link:/doc/developer/security/xss-prevention/[escaping expressions in Jelly pages]
* Resolve ambiguous property encodings by link:../convert-translations/[converting translations with native2ascii]

// Create a pull request
include::doc/developer/tutorial-improve/_create-a-pull-request.adoc[]
