---
layout: developersection
title: Use plugin bill of materials
---

:modified-files: pom.xml
:task-identifier: use-plugin-bom
:task-description: Use plugin bill of materials for easier dependency management

= Use plugin bill of materials for easier dependency management

.Simplify dependency management with the plugin bill of materials

video::pk1gweLvcEI[youtube,width=800,height=420,start=1749]

Updating the versions of plugin dependencies manually can be exhausting, looking for the correct set of versions that work with each other and do not cause upper-bounds dependency error reports.
The link:https://github.com/jenkinsci/bom#bill-of-materials-for-jenkins-plugins[Jenkins plugin bill of materials] simplifies that by shifting the evaluation of versions from each plugin author to a centralized process maintained by members of the Jenkins community.

// Create the branch
include::doc/developer/tutorial-improve/_create-a-branch.adoc[]

== Use the plugin bill of materials

Add a `dependencyManagement` section to the `dependencies` section of the pom file that references the link:https://github.com/jenkinsci/bom/releases[most recent version] of the plugin bill of materials for that line.
For example, the addition might look like:

[source,xml]
----
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.jenkins.tools.bom</groupId>
      <artifactId>bom-2.504.x</artifactId>
      <version>5577.vea_979d35b_b_ff</version>
      <scope>import</scope>
      <type>pom</type>
    </dependency>
  </dependencies>
</dependencyManagement>
----

Remove as many `<version>` declarations from the pom file as you can while still compiling successfully.

// Compile the plugin
include::doc/developer/tutorial-improve/_compile-the-plugin.adoc[]

Confirm that there are no errors reported and no test failures reported.

// Create a pull request
include::doc/developer/tutorial-improve/_create-a-pull-request.adoc[]
