---
:layout: post
:title: "Jenkins Board and Officer Elections 2025 - Nominations Open"
:tags:
- community
- governance
- governance-board
- elections
authors:
- markewaite
- basil
description: >
  Nominations are open for Jenkins Board and Officer elections.
opengraph:
  image: /images/governance/elections/2025/2025-announcement-opengraph.svg
---

**We are excited to announce the 2025 Jenkins Governance Board and Officer elections!**

== Nominations

Nominations can be submitted for link:/project/board/[governance board] positions and all link:/project/team-leads/[officer] positions (link:/project/team-leads/#security[Security], link:/project/team-leads/#events[Events], link:/project/team-leads/#release[Release], link:/project/team-leads/#infrastructure[Infrastructure], and link:/project/team-leads/#documentation[Documentation]).

During the registration period, we invite community members to nominate candidates by sending a message to the link:https://community.jenkins.io/g/election-committee[election-committee] group.
In your message, please include the name of the nominee, the specific position and your reasons for nominating that person.
A tutorial is available that shows the steps to link:/project/election-walkthrough/#nominate-a-candidate[nominate a candidate].

The nomination period ends on *September 22*.
Nominees will be notified and asked to confirm that they are interested in running as a candidate.
The list of candidates will be announced on September 23.

**Anyone can nominate anyone as a candidate!**

Many thanks to link:/blog/authors/markewaite/[Mark Waite] and link:/blog/authors/basil/[Basil Crow] for serving on the link:/project/board/[Jenkins Governance Board].
We also want to thank link:/blog/authors/dduportal/[Damien Duportal] as link:/project/team-leads/#infrastructure[Infrastructure Officer], link:/blog/authors/wadeck/[Wadeck Follonier] as link:/project/team-leads/#security[Security Officer], link:/blog/authors/alyssat/[Alyssa Tong] as link:/project/team-leads/#events[Events Officer], link:/blog/authors/timja/[Tim Jacomb] as link:/project/team-leads/#release[Release Officer], and link:/blog/authors/kmartens27/[Kevin Martens] as link:/project/team-leads/#documentation[Documentation Officer] for all of their work over the last term.

== The election consists of 4 phases:

* Nomination of candidates (August 8 - September 22)
* Voter registration (September 16 - October 31)
* Voting (November 1 - November 30)
* Results announcement (December 1)

=== Voting

Participation in the election process requires registering an account on the link:https://community.jenkins.io[Jenkins community forums] and at least one contribution made before September 1, 2025.
When registering, you can use an existing GitHub account or create a new account specifically for link:https://community.jenkins.io[Jenkins community forums].
We ask all community members who are interested in voting and meet the requirements to join the link:https://community.jenkins.io/g/election-voter-2025[election-voter-2025] group during the registration period.
Previous elections utilized their own groups, so joining the link:https://community.jenkins.io/g/election-voter-2025[election-voter-2025] group is required for participation.

We have made the decision to trust participants and not require that you provide evidence of contribution as part of your voter registration.
We reserve the right to ban any account from the election process if we identify abuse.
Once registration is over, a list of email addresses will be sent to the link:https://civs1.civs.us/[Condorcet Internet Voting Service (CIVS)].

=== Contributing

As shown on the link:/participate/[Participate and Contribute] page, there are many different ways to contribute to Jenkins. You can contribute by:

* link:/participate/connect/[Connecting with the community]
* link:/participate/meet/[Joining or organizing a meetup]
* link:/participate/code/[Contributing code to Jenkins]
* link:/participate/help/[Helping Jenkins users]
* link:/doc/developer/internationalization/[Translating Jenkins resources]
* link:/participate/test/[Testing Jenkins core and plugins]
* link:/participate/document/[Contributing to Jenkins documentation]
* link:/participate/design/[Creating art or updating the Jenkins UI]
* link:/participate/review-changes/[Reviewing open pull requests]
* link:/donate/[Donating to Jenkins]

All contributions to Jenkins and its community are welcome

== Election

Candidates will be announced September 23.
Voter registration closes on October 31.
Voting begins November 1.
Registered voters will be notified by email to participate using the link:https://civs1.civs.us/[Condorcet Internet Voting System].
All votes must be submitted by end of day November 30.

== Results

Election results will be published December 1.
The new term starts on December 1, when the newly elected members will transition to their roles.

== Important Dates

[cols="1,1"]
|===
|Important Dates |Time

|Nomination of candidates open
|August 8

|Voter registration opens
|September 16

|Nomination of candidates closes
|September 22

|Candidates announced
|September 23

|Voter registration closes
|October 31

|Voting starts
|November 1

|Voting closes
|November 30

|Results announced
|December 1
|===

== Troubleshooting

If you are new to Jenkins elections, unfamiliar with the Condorcet Internet Voting Service (CIVS) or the community forums, or feel overwhelmed with the process, don't worry, we've got you covered.
We published a link:/project/election-walkthrough/[step-by-step guide], outlining how to to join the link:https://community.jenkins.io/g/election-voter-2025[election-voter-2025], activate your CIVS account and cast your vote.

If you encounter issues still or need assistance, don't hesitate to contact the link:https://community.jenkins.io/g/election-committee[election committee].

Thank you, as always, and don't forget to register to vote by October 31!
