---
layout: section
---
ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]

= Reset Jenkins administrator password

As a system administrator, you can reset the Jenkins admin password.
In case you have forgotten or lost the password, this page provides instructions to reset the admin password.

== Reset the administrator password

. Login to your Jenkins controller and edit the Jenkins configuration file (config.xml) inside your Jenkins folder.
. Look for the **useSecurity** option and change it from **true** to **false**.
. Save your file and close it.
. Restart Jenkins service to apply changes. (This time it will not ask for password)
. On the dashboard, click on **Manage Jenkins** in the navigation pane on the left side of the page.
. In Manage Jenkins, in the **Security** section you will get **Configure Global Security**. Click on it.
. In **Security Realm**, click on the checkbox of **Jenkins' own user database** and save it. You will get redirected to the Manage Jenkins page.
. In **Security**, click on **Manage Users**. 

You will get a screen showing your user name with multiple tabs. Click on the setting icon.
. Search for **Password** section to change your password.
After changing the password you will be able to try logging into Jenkins again using the username and password that you have set.

link:https://www.youtube.com/watch?v=_VhOMyWDIcY