---
layout: section
---

ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]

= Reset the Jenkins administrator password

As a system administrator, you can reset the Jenkins admin password.
In case you have forgotten or lost the password, this page provides instructions on how you can reset the admin password.

video::_VhOMyWDIcY[youtube, width=640, height=360]
== Reset the administrator password

1. Log in to your Jenkins controller and edit the Jenkins configuration file (`config.xml`) inside your `jenkins/` or `$JENKINS_HOME` directory.
2. Look for **useSecurity** and change it from *true* to *false* manually.
3. Save your file and close it.
4. Restart the Jenkins service to apply your changes.
After restarting Jenkins, navigate to your controller and sign in.
5. On the dashboard, select  *Manage Jenkins* in the navigation pane on the left side of the page.
6. On the *Manage Jenkins* page, under the *Security* section, select *Configure Global Security*.
7. Under *Security Realm*, select *Jenkins' own user database* from the dropdown menu and save.
This redirects you to the Manage Jenkins page.
8. In **Security**, click on **Manage Users**.
9. You will see a screen showing your username with multiple tabs. Click on the **Settings** icon.
10. Locate  the *Password* section to change your password.

After changing the password, you will be able to log into your Jenkins instance again using the same username but the new password that you have just set.

