---
layout: section
wip: true
---
ifdef::backend-html5[]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]

= Backing-up/Restoring Jenkins

It is important to maintain regular backups of your Jenkins data. Backups are useful insurance against accidental configuration changes or for operational use in case of catastrophic failure. In the unlikely event that something goes wrong, you can recover and restore from the backup. Backing up the Jenkins executable is less critical, as it can easily be reinstalled without affecting your build environment.

This backup overview section includes strategies for configuration setting backup in Jenkins. It does not cover how to backup and restore your data, which depends on your organization’s configuration, tools and specific needs.

== Choose a configuration backup strategy

-   Back up the Jenkins Home directory
-   Back up a subset of the Jenkins Home directory

=== Back up the Jenkins Home directory

In a simple Jenkins configuration, the easiest solution is to periodically backup your entire `$JENKINS_HOME` directory. The Jenkins home directory contains all the information about your build server configuration, your build jobs, build artifacts, user accounts, and other useful information such as any plugins you may have installed.

You can perform backups on Jenkins at any time without stopping the server. The `$JENKINS_HOME` directory is compatible with all Jenkins versions, so that you can update or reinstall your Jenkins executable without affecting your Jenkins home directory.

`$JENKINS_HOME` directory structure 

----
JENKINS_HOME
 +- config.xml     (jenkins root configuration)
 +- *.xml          (other site-wide configuration files)
 +- updates
 +- users
 +- userContent    (files in this directory will be served under your http://server/userContent/)
 +- plugins        (stores plugins)
 +- workflow-libs
 +- secrets (generally credentials and similar secrets are encrypted on disk, and the keys are stored in this directory)
 +- logs
 +- nodes
 +- jobs
     +- [JOBNAME]      (sub directory for each job)
         +- config.xml     (job configuration file)
         +- latest         (symbolic link to the last successful build)
         +- builds
             +- [BUILD_ID]     (for each build)
                 +- build.xml      (build result summary)
                 +- log            (log file)
                 +- changelog.xml  (change log)
----

Archive this directory to make a back up. 

TIP: The general protection needs for a Jenkins "system" backup is lower if the `secrets` directory is excluded from the backup. 

To restore the data, replace the contents of the `JENKINS_HOME` directory from a back up.

=== Back up a subset of the Jenkins Home directory

The size of the `$JENKINS_HOME` directory will naturally grow larger over time to contain large amounts of data. To optimize Jenkins backups, decide what data is important to your organization. Some considerations of what to include in your backup are:
-   system configuration
-   job configuration
-   build records
-   sensitive information such as keys and passwords.

For example, the bulk of your data, including your job configuration and past filed records, lives in the `$JENKINS_HOME/jobs` directory. The `/jobs` directory contains job configuration, build history and archived files for each of your build jobs. Its directory structure looks similar to this:

----
+- jobs
    +- [JOBNAME]      (sub directory for each job)
        +- config.xml     (job configuration file)
        +- latest         (symbolic link to the last successful build)
        +- builds
            +- [BUILD_ID]     (for each build)
                +- build.xml      (build result summary)
                +- log            (log file)
                +- changelog.xml  (change log)
----
== Configure a backup location

Configure a directory for your Jenkins backup that is different from the drive where your Jenkins instance is setup. Make certain the backup directory you specify has read/write permissions for the user who is running the Jenkins service.

You may choose to backup to a Local directory, a Network mounted disk, a Remote SFTP server or a Remote WebDAV server.

If you are on https://aws.amazon.com[Amazon Web Services (AWS)], https://azure.microsoft.com[Microsoft Azure] or https://cloud.google.com[Google Cloud Platform], you can upload your backups to cloud storage.

== Create a backup retention policy

Your backup retention policy denotes how many and how long backups are kept. Jenkins backups can pile up and cause disk consumption and performance issues.

Backup retention is based on file names that include both the job name and the build number of the backup job. You can safely use a single destination directory for multiple backup jobs. Backup retention policies are enforced without interfering with each other.

== Restore your configuration settings from a backup

One of the most important things to remember when it comes to your Jenkins backup is to test your backup restore configuration on a Jenkins test server.

== How to back up Jenkins data

=== File-based backup tools

The tar command is widely used to create compressed archive files that can be moved easily from one disk to another disk, or machine to machine. Tar stands for tape archive, and is commonly referred to as tarball or tar, gzip and bzip in Linux. 

===== tar syntax
- c – Creates a new .tar archive file.
- z – use a gzip compression on the .tar archive
- f – File name type of the archive file.

===== Create tar.gz Archive File
From the command line, change directories into the `$JENKINS_HOME` folder. 
----
$ cd $JENKINS_HOME
----
----
$ tar czf backup_archive.tgz backupdirectory/
----

To restore from the backup_archive, in the Jenkins GUI, navigate to the "Manage Jenkins" page and choose the "Reload Configuration from Disk" option.

=== Backup plugins

There are many Jenkins plugins you can use to back up, monitor and restore your Jenkins configuration settings and data. Some plugins require manual configuration, while others can be scheduled or automated. A partial list includes:

- https://plugins.jenkins.io/backup[Backup] (unmaintained) Manual backups stores all data found in JENKINS_HOME.
- https://go.cloudbees.com/docs/cloudbees-documentation/cje-user-guide/index.html=backup[Taking Backup] Create, schedule and monitor backup jobs on CloudBees Jenkins Enterprise.
- https://github.com/jenkinsci/configuration-as-code-plugin[Jenkins Configuration as Code plugin (JCasC)] Configure jenkins based on human-readable declarative configuration files.
- https://plugins.jenkins.io/periodicbackup[Periodic Backup] A backup plugin that provides extended functionality without having to write code.
- https://plugins.jenkins.io/thinBackup[thinBackup] (unmaintained) Automates full and incremental data backups on a retention schedule. This plugin backs up the global and job specific configurations only, it does not backup the archive or the workspace.
- https://plugins.jenkins.io/s3[S3 publisher] Upload build artifacts to Amazon S3.
- https://plugins.jenkins.io/scm-sync-configuration[SCM Sync Configuration] Syncs your Jenkins configuration files with a Source Control Management (SCM) repository.
- https://plugins.jenkins.io/google-cloud-backup[Google Cloud Backup] Local and cloud-storage backups and automatic restores.

=== Using Containers and virtual machines

Containers and virtualization are also popular tools for creating backups. See:

- https://wiki.jenkins.io/display/JENKINS/Containers[Containers]
- https://medium.com/pacroy/how-to-backup-and-restore-your-jenkins-data-volume-in-docker-2ac66d99315a[How-To Backup and Restore Your Jenkins Data Volume in Docker]
- https://jenkins.io/doc/book/pipeline/docker/[Using Docker with Pipeline]
- https://antonfisher.com/posts/2017/01/16/run-jenkins-in-docker-container-with-persistent-configuration[Run Jenkins in Docker container with persistent configuration]

== Further reading
- https://jenkins-x.io/getting-started[Get Started with Jenkins X on Kubernetes] A CI/CD solution for modern cloud applications on Kubernetes
- https://thepracticalsysadmin.com/backing-up-jenkins-configurations-to-s3[Backing up Jenkins configurations to S3]
- https://openedx.atlassian.net/wiki/spaces/TE/pages/44073670/Backup+strategies+for+Build+Jenkins[Backup strategies for Build Jenkins]

