---
layout: project
title: "Jenkins Area Meetups (now sponsored by CDF)"
section: projects
tags:
- jam
- jams
links:
  googlegroup: 'jenkinsci-jam'
  gitter: 'jenkinsci/advocacy-and-outreach-sig'
---

There has been a few updates to the Jenkins Area Meetups. First, the Jenkins Area Meetup Pro account, which JAMs has been under, has been rebranded to reflect our new sponsor, the Continuous Delivery Foundation (CDF). We notified JAM organizers about this transition in early October 2019. 

JAM organizers are welcome to transition their meetup to CDF specific branding (if you would also like to update your meetup name we offer the following naming convention Project Name City Name Meetup or CI/CD City Name Meetup). By no means JAMs are under any obligation to update the naming convention or the branding. We are giving organizers the freedom to choose. For more info, please visit us at https://www.meetup.com/pro/cicd-cdf or drop us a line at https://www.meetup.com/pro/cicd-cdf.
 
CI/CD Meetups (formerly JAMs) are local meetups intended to bring CI/CD users and contributors together for socializing and learning. CI/CD Meetups are organized by local community members who have a passion for sharing new CI/CD concepts, patterns and tools. We are also welcoming community members who are interested in other CI/CD projects such as Spinnaker, Tekton, and Jenkins X to join our network. CI/CD Meetups can be found link:https://www.meetup.com/pro/cicd-cdf[around the world], and if there isn’t a CI/CD Meetup in your city, you could be the one to start it! Apply link:https://docs.google.com/forms/d/e/1FAIpQLSeaoOkc-1FAcyYbD7TYOjJoiXbX7cQTArRACsps2g1VG7xgew/viewform[here]! 
 
CI/CD and Jenkins Meetups are driven by local organizers but receive support from the CD Foundation via swag (stickers, etc), promotion, and help bootstrapping and operating the meetup group.

== Getting Started

Whether you want to start a JAM or a CI/CD meetup, send us an email meetups@cd.foundation to get started. Let us know the city in which you’d like to host the CI/CD Meetup. Our team will create a meetup page on meetup.com and we will work with you to organize your meetup.

*CI/CD and JAM Support*

* Swag - We will send you cool swags (stickers, t-shirts, etc) to share with members
* Promote - We give every CDF Meetup and JAM social media love via Twitter, blog posts, Facebook, newsletter, and post on the link:https://cd.foundation/events/list/[events calendar].
* CI/CD Expertise - We will help you to schedule a project expert as the key speaker at your meetup, or provide you with presentation materials.
* Outreach - We will assist in reaching out to your local community for food/venue sponsorship.
* Support specific to JAMs - As CDF will manage the operational aspect of JAMs and CI/CD meetups, the Advocacy & OutReach SIG is a channel to provide guidance/advice to new JAM organizers if needed. Email jenkins-advocacy-and-outreach-sig@googlegroups.com 

=== Best Practices

* Attend existing meetup groups to gauge any of CDF's current projects interest/market within your area.
* Reach out to existing CDF/JAM organizer(s) to learn best practices and time commitment.
* Set up a Twitter account (for example, #JenkinsNYC). Email your group’s Twitter ID to meetups@cd.foundation so we can help to promote your meetup.
* Promote, tweet and post your meetup in advance.
* Avoid product pitches. Keep it real, it’s not about promotions. This is about - and for - learning opportunities for the community.
* Shake up the format. Have presentations, panel discussions, roundtables, workshops, hackathons, etc.
* Set a consistent date, time and location so members will plan for it. Avoid cancelling your meeting as people will lose faith and stop RSVPing for your meetup.
* Review the CDF meetups repository on Github https://github.com/cdfoundation/meetups

=== Stepping Down

In the event you can no longer be an organizer, we ask that you nominate a
replacement organizer in your place. If this is not possible please send email
to meetups@cd.foundation, we will work with you to find a replacement.

== Supporting a meetup group

If you are not able to be an organizer, speakers, food or venue, or recording sponsors are always needed. If your company is interested in sponsoring any of these items pls email meetups@cd.foundation or reach out to the local organizer via meetup.com or fill out link:https://docs.google.com/a/cloudbees.com/forms/d/1dGpwxpwoJDHR3fTlIcFXO8GZVpx5i_dWUlbi9LKolX4/edit[this form]. 

*Benefits of Being a Food or Venue or Recording Sponsor:*

* Logo and link on the meetup page.
* Verbal acknowledgement at the opening/closing remark by the host.
* Sponsor table at the meeting to display collaterals, signage, swag.
* Opportunity to host a drawing.
* Mention in social media.
* A two minute talk to address the attendees.

*Food Sponsor:*

Sponsor food and beverages for the specific month's meetup. The cost is about
$200 to $600 depending on the number of attendees. The money is used to
purchase pizza, soft drinks and paperware. One sponsor is needed for each
monthly meeting.

*Venue Sponsor:*

Venue sponsors provide the facility to host the meeting for free. One venue sponsor is needed per meeting. A meeting room with chairs and a couple of six feet tables with open space for food/beverages and mingling would be sufficient. Access to a public bathroom would be needed as well. A meetup will need such equipments as projection and screen. In the event where a meeting has more than 50 attendees an audio system will be needed.

*Recording Sponsor:*

Recording sponsor volunteer his/her recording equipments and time to record a
meeting and make it public after the meeting.

== CI/CD meetup groups around the World

See the current list of Jenkins & CI/CD meetup groups link:https://www.meetup.com/pro/cicd-cdf[here].



