---
layout: simplepage
title: LTS Release Line
---
:toc:

The weekly Jenkins releases deliver bug fixes and new features rapidly to users and plugin developers who need them.
But for more conservative users, it's preferable to stick to a release line which changes less often and only receives important bug and security related fixes, even if such a release line lags behind in terms of features.
Several companies maintain their own private branches off of Jenkins for stabilization and internal customizations.
We encourage everybody to shift a part of the effort to this release line.

This is called the Jenkins *Long-Term Support* release, or *LTS*. The concept is very similar to the link:https://wiki.ubuntu.com/LTS[LTS concepts in Ubuntu] and our model is described below.

## Model

Every 12 weeks, the community will pick one of the relatively recent releases by consensus and mark it as the baseline for the next "stable but older" release line.
Let's say this was version X.
We'll create a branch from X to produce stable but older patch releases of *X.1*, *X.2*, and *X.3*.
Changes to this branch will be restricted to backported cherry-picked bug fixes from the trunk that are "battle-tested" — meaning those commits that have already been a part of a main line release for more than a week.
There are 3 minor releases for a baseline published in four week cycles.
A release candidate is published two weeks before a minor release.

The following table demonstrates release dates within the 12 week cycle:

++++
<style>
  table#process th, table#process td {
    min-width: 60px;
    border: 1px solid grey;
    padding: 3px;
  }
</style>
<table id="process">
  <tr>
    <th>Week</th>
    <th>0</th>
    <th>2</th>
    <th>4</th>
    <th>6</th>
    <th>8</th>
    <th>10</th>
    <th>12</th>
    <th>14</th>
    <th>16</th>
    <th>18</th>
    <th>20</th>
    <th>22</th>
    <th>24</th>
  </tr>
  <tr>
    <th>Release</th>
    <td>W.3</td>
    <td>X.1 RC</td>
    <td>X.1</td>
    <td>X.2 RC</td>
    <td>X.2</td>
    <td>X.3 RC</td>
    <td>X.3</td>
    <td>Y.1 RC</td>
    <td>Y.1</td>
    <td>Y.2 RC</td>
    <td>Y.2</td>
    <td>Y.3 RC</td>
    <td>Y.3</td>
  </tr>
  <tr>
    <th>Baseline Selection</th>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>Y chosen</td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td>Z chosen</td>
    <td></td>
  </tr>
</table>
++++

There is a two week period for backporting followed by two weeks for testing the release candidate resulting in the release of X.1.
Backporting and RC testing is repeated twice, producing X.2 and X.3.
This concludes the cycle for a given baseline and the new one is started immediately based on the new baseline selected in week 10.

The baseline release is typically between 0-3 weeks old when it is chosen, so X.1 LTS releases are published about 6-9 weeks after their baseline.

See the link:/content/event-calendar[event calendar] for the specific LTS RC/release dates in the near future.

## Backporting Process

Any user can propose that an issue is backported to LTS by labeling with link:https://github.com/jenkinsci/jenkins/issues?q=state%3Aclosed%20label%3Alts-candidate[lts-candidate].

To label an issue or pull request without write access to the repository, add a comment with `/label lts-candidate`.

For an issue to be eligible for backporting it should be a small, safe-looking, uncontroversial fix for an important bug with no change to API surface.
Backporting candidates should be delivered in a weekly release before shipping in an LTS release.
Additionally library updates can also be considered if the library contains a public CVE that does not affect Jenkins (if Jenkins is vulnerable via a library then the link:/security[security] process applies).
Backporters use link:https://github.com/jenkinsci/jenkins/issues?q=state%3Aclosed%20label%3Alts-candidate[this query] to list issues that need to be attended once resolved.

Aside from the model set out above, backporters apply some subjective selection — for example whether a fix is easy and safe to backport, confidence in the fix, importance/impact of the problem, how much time is left until the end of backporting window and so on.

If backported, a label like `2.46.2-fixed` is applied to communicate to the user what LTS version(s) it's going to be in.
If the backport is rejected, a label like `2.46.2-rejected` is used to indicate that this ticket will not be backported to that specific release -- but it may still be picked up in a later LTS release.

## Switching Between Release Lines

Due to how Jenkins stores data internally, users are generally able to upgrade to newer releases, but not downgrade to older releases.
In the context of LTS, the _baseline_ is almost always the deciding factor that determines to which releases of the other line a Jenkins controller can be migrated.

### Switching From LTS to Weekly

Make sure that the weekly release you're migrating to has been released after the LTS version you're migrating from.

We recommend that users moving from LTS to weekly should use the most recent weekly release to assure they have the latest features and fixes.

### Switching From Weekly to LTS

Make sure that the LTS baseline you're migrating to is more recent (compared numerically) than the weekly release you're migrating from.
For example, if you're using Jenkins 2.5, 2.18, or 2.46, you will be able to upgrade to Jenkins LTS 2.46.x without major problems.
However, if you're using Jenkins 2.47 or Jenkins 2.56, you may have problems downgrading to Jenkins LTS 2.46.x, even if the specific LTS releases were created at a later date than the weekly release you're using.

### Switching Update Sites

The Jenkins project operates multiple update sites that inform Jenkins about available updates to Jenkins and plugins.
As Jenkins sends its current version when requesting new data, the same link:https://updates.jenkins.io/update-center.json[URL] can be used for all releases of Jenkins, and will always serve the most appropriate update information.
For example, controllers running an LTS release of Jenkins will only be offered LTS versions of Jenkins to upgrade to.
See https://updates.jenkins.io/[updates.jenkins.io] to learn more.

After switching between release lines, it's recommend to update the update site metadata cached in Jenkins by hitting the "Check now" button in the Plugins Manager (further instructions link:/doc/book/managing/plugins/#from-the-web-ui[here]).
Otherwise, Jenkins may offer to update or install plugins whose newer versions are incompatible with the installed version.
