---
layout: chapter
---
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc:

////
NOTE: The sections are ordered from simpler to progressively more complex
subjects.  The earlier sections are intended for those new to pipeline or
unfamiliar with its latest features.  The later sections with discuss
expert-level considerations and corner-cases.

This chapter functions as a continuation of "Getting Started with Jenkins" and
"Using Jenkins" , but the format will be slightly different - see the
description above.  The first sections should lead users through the basics of
pipeline, and later sections can switch to feature reference for experienced
users. All sections should still be written and ordered to only assume
knowledge from "Getting Started", "Using Jenkins", or from previous sections in
this chapter.
////


= Pipeline

This chapter will cover all aspects of Jenkins Pipeline, from running pipeline jobs
to writing your own pipeline code, and even extending Pipeline.

This chapter is intended to be used by Jenkins users of all skill levels,
but beginners may need to refer to some sections of "<<using#,Using Jenkins>>"
to understand some topics covered in this chapter.

If you are not yet familiar with basic Jenkins terminology and features, start with
<<getting-started#,Getting Started with Jenkins>>.

[[overview]]
== What is Pipeline?

Jenkins Pipeline is a suite of plugins which support building continuous
delivery pipelines "natively" in Jenkins. While Jenkins has always allowed
rudimentary forms of chaining Freestyle Jobs together to perform sequential
tasks or actions,
footnote:[Additional plugins have been used to implement complex behaviors
utilizing Freestyle Jobs such as the Copy Artifact, Parameterized Trigger,
and Promoted Builds plugins],
Jenkins Pipeline provides an integrated and extensible set of tools for modeling
simple-to-complex delivery pipelines "as code" via the Pipeline DSL.
footnoteref:[dsl,link:https://en.wikipedia.org/wiki/Domain-specific_language[Domain-Specific Language]]

Typically, this "Pipeline as Code" would be written to  a `Jenkinsfile` and
checked into a project's source control repository, for example:

.Jenkinsfile
[source, groovy]
----
node { // <1>
    stage('Build') { // <2>
        sh 'make' // <3>
    }

    stage('Test') {
        sh 'make check'
        junit 'reports/**/*.xml' // <4>
    }

    stage('Deploy') {
        sh 'make publish'
    }
}
----
<1> <<node,`node`>> indicates that Jenkins should allocate an executor and workspace for
this part of the Pipeline.
<2> <<stage,`stage`>> describes a stage of this Pipeline.
<3> `sh` executes the given shell command
<4> `junit` is a Pipeline <<step,step>> provided by the
link:https://plugins.jenkins.io/junit[JUnit plugin]
for aggregating test reports.

[[terms]]
== Pipeline Terms

[[step]]
Step::
    A single task, fundamentally steps tell Jenkins _what_ to do. For example, in
    order to instruct Jenkins to execute the shell command `make`, the `sh`
    step would be used: `sh 'make'`.
    When a plugin extends to Pipeline DSL, that typically means the plugin has
    implemented a new _step_.

[[node]]
Node::
    Generally speaking, all _work_ which is done by a Pipeline, will be done in
    the context of a single, or multiple, `node` step declarations, which does two things:
    . Schedules the steps contained within the block to run by adding an item
      to the Jenkins queue. As soon as an executor is free on a node, the
      steps will run.
    . Creates a workspace, a directory specific to that particular
      Pipeline, where files can be checked out from source control and work can
      be done.

CAUTION: Depending on your Jenkins configuration, some workspaces may not get
automatically cleaned up after a period of inactivity. See tickets and
discussion linked from
https://issues.jenkins-ci.org/browse/JENKINS-2111[JENKINS-2111]
for more information.

[[stage]]
Stage::
    A "stage" is a step for defining a conceptually distinct subset of the
    entire Pipeline, for example: "Build", "Test", and "Deploy". While stages
    no bearing on the execution of the Pipeline, they are used by many plugins
    which visualize or present Jenkins Pipeline status/progress.
    footnoteref:[blueocean,link:/projects/blueocean[Blue Ocean], link:https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Stage+View+Plugin[Pipeline Stage View plugin]]
