---
layout: chapter
---
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc:

= Pipeline

This chapter will cover all aspects of Jenkins Pipeline, from running pipeline jobs
to writing your own pipeline code, and even extending Pipeline.

This chapter is intended to be used by Jenkins users of all skill levels,
but beginners may need to refer to some sections of "<<using#,Using Jenkins>>"
to understand some topics covered in this chapter.

If you are not yet familiar with basic Jenkins terminology and features, start with
<<getting-started#,Getting Started with Jenkins>>.


== What is Pipeline?

Jenkins Pipeline is a suite of plugins which support building continuous
delivery pipelines "natively" in Jenkins. While Jenkins has always allowed
rudimentary forms of chaining Freestyle Jobs together to perform sequential
tasks or actions,
footnote:[Additional plugins have been used to implement complex behaviors
utilizing Freestyle Jobs such as the Copy Artifact, Parameterized Trigger,
and Promoted Builds plugins],
Jenkins Pipeline provides an integrated and extensible set of tools for modeling
simple-to-complex delivery pipelines "as code" via the Pipeline DSL.
footnoteref:[dsl,link:https://en.wikipedia.org/wiki/Domain-specific_language[Domain-Specific Language]]

Typically, this "Pipeline as Code" would be implemented in a `Jenkinsfile` and
checked into source control, for example:

.Jenkinsfile
[source, groovy]
----
node { // <1>
    stage('Build') { // <2>
        sh 'make' // <3>
    }

    stage('Test') {
        sh 'make check'
        junit 'reports/**/*.xml' // <4>
    }

    stage('Deploy') {
        sh 'make publish'
    }
}
----
<1> `node` indicates that Jenkins should allocate an executor and workspace for
this part of the pipeline.
<2> `stage` describes a stage of this pipeline.
<3> `sh` executes the given shell command
<4> `junit` is a pipeline "step" provided by the
link:https://plugins.jenkins.io/junit[JUnit plugin]
for aggregating test reports.

