---
layout: section
---
:notitle:
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:

= Multibranch Pipelines

The *Multibranch Pipeline* project type enables you to configure different jobs
for different branches of the same project. In a multibranch pipeline
configuration, Jenkins automatically discovers, manages, and executes jobs
for multiple source repositories and branches. This eliminates the need for
manual job creation and management, as would otherwise be necessary
when, for example, a developer adds a new feature to an existing
product.

A multibranch pipeline project always includes a 'Jenkinsfile' in its
repository root. Jenkins automatically creates a sub-project for each branch
that it finds in a repository with a `Jenkinsfile`.

Multibranch pipelines use the same version control as the rest of your software
development process. This "pipeline as code" approach has the following
advantages:

* You can modify pipeline code without special editing permissions.
* Finding out who changed what and why no longer depends on whether developers remember to comment their code changes in configuration files.
* Version control makes the history of changes to code readily apparent.

To create a Multibranch Pipeline:

. Click New Item on your Jenkins home page, enter a name for your job, select Multibranch Pipeline, and click OK.
. Configure your SCM source (options include Git, GitHub, Mercurial, Subversion, and Bitbucket), supplying information about the owner, scan credentials, and repository in appropriate fields.
  For example, if you select Git as the branch source, you are prompted for the usual connection information, but then rather than enter a fixed refspec (Git's name for a source/destination pair), you would enter a branch name pattern (Use default settings to look for any branch).
. Configure the other multibranch pipeline options:
 * API endpoint - an alternate API endpoint to use a self-hosted GitHub Enterprise
 * Checkout credentials - alternate credentials to use when checking out the code (cloning)
 * Include branches - a regular expression to specify branches to include
 * Exclude branches - a regular expression to specify branches to exclude; note that this will takes precedence over the contents of include expressions
. Save your configuration.

Jenkins automatically scans the designated repository and creates appropriate branches.

For example (again in Git), if you started with a master branch, and then wanted
to experiment with some changes, and so did `git checkout -b newfeature` and
pushed some commits, Jenkins would automatically detect the new branch in your
repository and create a new sub-project for it. That sub-project would have its
own build history unrelated to the trunk (main line).

If you choose, you can ask for the sub-project to be automatically removed after
its branch is merged with the main line and deleted. To change your Pipeline
script—for example, to add a new Jenkins publisher step corresponding to new
reports that your `Makefile`/`pom.xml`/etc. is creating—you edit the appropriate
`Jenkinsfile`. Your Pipeline script is always synchronized with
the rest of the source code you are working on.

*Multibranch Pipeline* projects expose the name of the branch being built with
the `BRANCH_NAME` environment variable. In multibranch pipelines, the `checkout
scm` step checks out the specific commit that the `Jenkinsfile` originated, so
as to maintain branch integrity.
