---
layout: section
title: Using credentials
---
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:


= Using credentials

There are numerous 3rd-party sites and applications that can interact with
Jenkins, for example, artifact repositories, cloud-based storage systems and
services, and so on.

A systems administrator of such an application can configure credentials in the
application for dedicated use by Jenkins. This would typically be done to "lock
down" areas of the application's functionality available to Jenkins, usually by
applying access controls to these credentials. Once a Jenkins manager (i.e. a
Jenkins user who administers a Jenkins site) adds/configures these credentials
in Jenkins, the credentials can be used by Pipeline projects to interact with
these 3rd party applications.

*Note:* The Jenkins credentials functionality described on this and related
pages is provided by the
link:https://plugins.jenkins.io/credentials-binding[Credentials Binding plugin].

Credentials stored in Jenkins can be used:

* anywhere applicable throughout Jenkins (i.e. global credentials),
* by a specific Pipeline project/item (read more about this in the
  <<jenkinsfile#handling-credentials,Handling credentials>> section of the
  <<jenkinsfile#,Using a Jenkinsfile>> page),
* by a specific Jenkins user (as is the case for
  link:/doc/book/blueocean/creating-pipelines[Pipeline projects created in Blue
  Ocean]).

Jenkins can store the following forms of credentials:

* a token such as an API token (e.g. a GitHub personal access token), also known
  as "secret text",
* a username and password, which could be handled as separate components or as a
  colon separated string in the format `username:password`,
* a "secret file", which is essentially secret content in a file,
* an link:http://www.snailbook.com/protocols.html[SSH public/private key pair],
* a link:https://tools.ietf.org/html/rfc7292[PKCS#12 certificate file] and
  optional password, also known as a "certificate", or
* Docker host certificate authentication credentials.


== Credential security

To maximize security, credentials configured in Jenkins are stored in an
obfuscated form on the master Jenkins instance (encyrpted by the Jenkins
instance ID) and are only handled in Pipeline projects via their credential IDs.

This minimizes the chances of exposing the actual credentials themselves to
Jenkins users and hinders the ability to copy functional credentials from one
Jenkins instance to another.


== Configuring credentials

This section describes procedures for configuring credentials in Jenkins.


=== Adding new global credentials



When a Jenkins manager manually
adds credentials to Jenkins, the opportunity is provided to specify a meaningful
credential ID value - for example, `jenkins-user-for-xyz-artifact-repository`. If this optional field is not
specified, Jenkins assigns a globally unique ID (GUID) value for the credential
ID. Bear in mind that once a credential ID is set, it can no longer be changed.
