---
chart:
  user: "Jenkins Infra Bot (updatecli)"
  email: "60776566+jenkins-infra-bot@users.noreply.github.com"
  username: "jenkins-infra-bot"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "master"
  owner: "jenkins-infra"
  repository: "charts"
