---
layout: chapter
title: Updating Jenkins
---
ifdef::backend-html5[]
:notitle:
:description:
:sectanchors:
:toc:
:toclevels: 4
:imagesdir: ../resources
endif::[]

[pass]
++++
<!-- Redirect anchor references with Javascript -->
<!-- This is ONLY for anchor references like updating/#windows. -->
<!-- Use redirects as described in the contributing guide for page level redirects. -->
<!-- https://stackoverflow.com/questions/1305211/javascript-to-redirect-from-anchor-to-a-separate-page/21198129#21198129 -->
<script>
(function () {
    var anchorMap = {
        "ji-toolbar" : "/doc/book/updating/", /* Algolia search redirect to stay on same page */

        "accessing-the-jenkins-blue-ocean-docker-container": "/doc/book/updating/docker#accessing-the-jenkins-blue-ocean-docker-container",
        "accessing-the-jenkins-console-log-through-docker-logs": "/doc/book/updating/docker#accessing-the-jenkins-console-log-through-docker-logs",
        "accessing-the-jenkins-home-directory": "/doc/book/updating/docker/#accessing-the-jenkins-home-directory",
        "docker": "/doc/book/updating/docker/",
        "downloading-and-running-jenkins-in-docker": "/doc/book/updating/docker/",
        "updating-docker": "/doc/book/updating/docker/",

        "configuring-http": "/doc/book/updating/initial-settings/#configuring-http",
        "miscellaneous-parameters": "/doc/book/updating/initial-settings/#miscellaneous-parameters",
        "networking-parameters": "/doc/book/updating/initial-settings/#networking-parameters",
        "using-http2": "/doc/book/updating/initial-settings/#using-http2",

        "creating-the-first-administrator-user": "/doc/book/updating/linux/#creating-the-first-administrator-user",
        "customizing-jenkins-with-plugins": "/doc/book/updating/linux/#customizing-jenkins-with-plugins",
        "debianubuntu": "/doc/book/updating/linux/#debianubuntu",
        "fedora": "/doc/book/updating/linux/#fedora",
        "linux": "/doc/book/updating/linux/",
        "prerequisites": "/doc/book/updating/linux/#prerequisites",
        "red-hat-centos": "/doc/book/updating/linux/#red-hat-centos",
        "setup-wizard": "/doc/book/updating/linux/#setup-wizard",
        "unlocking-jenkins": "/doc/book/updating/linux/#unlocking-jenkins",

        "freebsd": "/doc/book/updating/other/#freebsd",
        "openindiana-hipster": "/doc/book/updating/other/#openindiana-hipster",
        "other-operating-systems": "/doc/book/updating/other/",
        "solaris-omnios-smartos-and-other-siblings": "/doc/book/updating/other/#solaris-omnios-smartos-and-other-siblings",

        "https-certificates-with-windows": "/doc/book/updating/initial-settings/#https-certificates-with-windows",
        "https-with-an-existing-certificate": "/doc/book/updating/initial-settings/#https-with-an-existing-certificate",
        "jenkins-parameters": "/doc/book/updating/initial-settings/#jenkins-parameters",
        "jenkins-properties": "/doc/book/updating/initial-settings/#jenkins-properties",

        "kubernetes": "/doc/book/updating/kubernetes/",

        "macos": "/doc/book/updating/macos/",

        "offline-jenkins-installation": "/doc/book/updating/offline/",

        "war-file": "/doc/book/updating/war-file/",
        "war-files": "/doc/book/updating/war-file/",

        "windows": "/doc/book/updating/windows/",
    }
    /*
    * Best practice for extracting hashes:
    * https://stackoverflow.com/a/10076097/151365
    */
    var hash = window.location.hash.substring(1);
    if (hash) {
        /*
        * Best practice for javascript redirects:
        * https://stackoverflow.com/a/506004/151365
        */
        window.location.replace(anchorMap[hash]);
    }
})();
</script>
++++

The procedures in this chapter are for Upgrading Jenkins.

Jenkins is typically run as a standalone application in its own process and can be upgraded through downloading Latest Jenkins WAR file.The Jenkins WAR file bundles link:https://github.com/jenkinsci/winstone[Winstone],
a link:https://www.eclipse.org/jetty/[Jetty] servlet container wrapper,
and can be updated on any operating system or platform with a version of Java supported by Jenkins.
