---
layout: section
title: Linux
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc: left
:toclevels: 3
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

link:https://www.jenkins.io/doc/book/installing/linux/[Linux installations]
should be upgraded using the same method as was used for the original installation
This section will guide you through updating your Jenkins instance to the most recent version.

include::doc/book/updating/_pre-upgrade-wizard.adoc[]

== Upgrade steps on Linux
[unordered.stack]
1) Stop your Jenkins Instance :: 
[source,bash]
```
#Stop running Jenkins service using the following command:

sudo su -
systemctl stop jenkins
```
2) Take Jenkins instance backup as a recovery option ::
[source,bash]
```
#Take backup of Jenkins home directory. In my case my Jenkins home directory is /var/lib/jenkins.
```

See the link:/doc/book/system-administration/backing-up/[backup instructions] for alternatives.

5) Start The Jenkins Service ::
[source,bash]
```
#Start the Jenkins service using the following command:
systemctl start jenkins
```

== Updating Based on Operating Systems
---

Red Hat / CentOS ::

* Update Controller with `yum upgrade jenkins`

Debian / Ubuntu ::
* Update Controller with `apt-get update && apt-get upgrade jenkins`

openSUSE / SUSE Linux ::
* Update Controller with `zypper update jenkins`

include::doc/book/updating/_update-wizard.adoc[]
