---
layout: section
title: Windows
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

== Upgrade steps on Windows

Insert MSI upgrade instructions here.

=== 1. Stop the running Jenkins service

To stop Jenkins Please avoid shutting down the Java process or the Windows service. These are not usual commands. Use those only if your Jenkins is causing problems.

use the following command to stop server

`http://[jenkins-server]/exit`

Example: if my local PC is running Jenkins at port 8080, it will be

`http://localhost:8080/exit`

=== 2. Go to the location where your Jenkins instance is installed

=== 3. Rename the war folder to war.old

=== 4. Rename jenkins.war file to jenkins.war.old

=== 5. Copy the new jenkins.war you downloaded into your Jenkins installation directory

=== 6.Start Jenkins service

To start the service you need to open the terminal in the directory where your Java WAR File is present and run the following command

```
java -jar jenkins.war
```

=== 7. Observe the creation of a new war directory which will now contain the contents of the new jenkins.war archive

By doing so, you can avoid losing your setup and builds that happen when a WAR file is replaced.

include::doc/book/updating/_update-wizard.adoc[]