---
layout: gsocproject
title: "GSoC 2018. Code Coverage API Plugin"
status: "Active"
tags:
- gsoc2018
student:
  name: "Shenyu Zheng"
  id: "cizezsy"
  github: "cizezsy"
  irc: "cizezsy"
mentors:
- name: "Steven Christou"
  id: "schristou"
  github: "christ66"
  irc: "schristou"
- name: "Supun Wanniarachchi"
  id: "supun"
  irc: "Supun"
  github: "Supun94"
  twitter: "SuuPuuN"
- name: "Jeff Pearce"
  id: "jeffpearce"
  irc: "TODO"
  github: "jeffpearce"
  twitter: "Jeff_Pearce"
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
  irc: "oleg_nenashev"
  twitter: "oleg_nenashev"
links:
  gitter: "jenkinsci/code-coverage-api-plugin"
  github: "jenkinsci/code-coverage-api-plugin"
---

There are a lot of plugins which currently implement code coverage (clover plugin, cobertura plugin, clover php plugin, etc),
however they all are using similar charts and similar content.
Instead of having one plugin for each code coverage result it would be best if we could merge them all into one plugin which will handle code coverage.

* link:https://docs.google.com/document/d/10ko6W07pIpRqgYcv2Eq6tZwSg1UUybzJ9AsMZszfiXA/edit#heading=h.jv1f2icy8a5j[Project Proposal]
* link:https://jenkins.io/blog/2018/06/13/code-coverage-api-plugin/[Introduction Blogpost]
* link:https://www.youtube.com/watch?v=qWHM8S0fzUw[Phase 1 Presentation Video]
* link:https://docs.google.com/presentation/d/141gvnLeNem-2SdiIEM4ZN-nzDmhVJUrUYv-r6a482R8/edit?usp=sharing[Phase 1 Presentation Slides]
* link:https://www.youtube.com/watch?v=tuTODhJOTBU[Phase 2 Presentation Video]
* link:https://docs.google.com/presentation/d/1pHe7qFwo1ej1YdIUUVriQK09rVasmGpHnmycHy7ikws/edit?usp=sharing[Phase 2 Presentation Slides]

=== Office hours

* Every Wednesday, 01:00-02:00 PM UTC
* Every Friday, 01:00-02:00 PM UTC

=== Objectives

First Phase (May 15 - June 15):

* Prototype based on Cobertura plugin data model.
* Integrate other Java code coverage tools.
* Auto detect support.
* Health report support.
* Pipeline support.
* Threshold support.
* Modernize report.
* Unit tests.

Second Phase (June 16 - July 9):

* APIs which can be used by others
** Integrate Cobertura Plugin with Code Coverage API.
** Provide Java API and REST API for getting coverage information.
* Implementing abstract layer for other report formats like JSON.
* Supporting converters for non-Java languages.
* Supporting combining reports within a build(e.g. after parallel() execution in Pipeline).
* Adding source code navigation in Coverage Result Page.
* Refactoring the configuration page to make it more user-friendly.

Third Phase (July 14 - August 6):

* Supporting more coverage tools
** Gcov
** Coverage.py
** others
* Polishing code.
* Fixing bugs.
* Writing documentation.
* Releasing the plugin.
