---
layout: gsocproject
title: "GSoC 2018. Jenkins Remoting over Message Bus/Queue"
status: "Active"
tags:
- gsoc2018
- remoting
student:
  name: "Pham Vu Tuan"
  id: "pvtuan10"
  github: "pvtuan10"
  irc: "pvtuan10"
mentors:
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
  irc: "oleg_nenashev"
  twitter: "oleg_nenashev"
- name: "Supun Wanniarachchi"
  id: "supun"
  irc: "Supun"
  github: "Supun94"
  twitter: "SuuPuuN"
links:
  gitter: "jenkinsci/remoting"
  github: "jenkinsci/remoting-kafka-plugin"
---

Current versions of Jenkins Remoting are based on the TCP protocol.
If it fails, the agent connection and the build fails as well.
There are also issues with traffic prioritization and multi-agent communications,
which impact Jenkins stability and scalability.

This project aims an update of Remoting and Jenkins in order to add support of
a popular message queue/bus technology (RabbitMQ or Kafka) as a fault-tolerant communication layer in Jenkins.

link:https://docs.google.com/document/d/17vmPvDtMbHT7nTKRlGReFRgOtwVImhgsETLOGPW9Rso/edit[More info about the project]

=== Office hours

* Every Tuesday, 02:00-03:00 PM UTC
* Every Friday, 02:00-03:00 PM UTC

=== Documentation

All the notes, meeting minutes, design documentation can be found at https://drive.google.com/open?id=1-sua3rHvz84I8OZKL_3VpTlgEAMoBEHO

=== Timeline

First phase:

* 14/05 - 18/05: Setting up project skeleton, implementation of publishers, subscribers.
* 21/05 - 08/06: PoC - Implementation of command transport for the message bus which involves command invocation, RMI, classloading and data streaming.
* 11/06 - 15/06: Phase 1 Evaluation

=== Objectives

First phase:

* Create a proof of concept for Remoting over Kafka.
* Do demonstration of the PoC.
* Define design for the final implementation.
* Decide whether we use Kafka in the final implementation (or not).
* Create a blogpost with a PoC introduction.
