---
layout: gsocproject
title: "GSoC 2018. Simple Pull-Request Job Plugin"
tags:
- gsoc2018
student:
  name: "Abhishek Gautam"
  id: "gautamabhishek46"
  github: "gautamabhishek46"
  irc: "abhishekg"
mentors:
- name: "Kristin Whetstone"
  id: "kwhetstone"
  github: "kwhetstone"
  irc: "kwhetstone"
- name: "Jeff Knurek"
  id: "TODO"
  github: "Jeff-Symphony"
  irc: "TODO"
- name: "Willy Aguirre"
  id: "marti_"
  github: "marti1125"
  irc: "TODO"
links:
  gitter: "jenkinsci/simple-pull-request-job-plugin"
  github: "jenkinsci/simple-pull-request-job-plugin"
---

This project aims to develop a Job Plugin
which can interact with Bitbucket Server, Bitbucket Cloud, and Github
whenever a pull request is created or updated.
Users should be able to configure job type using YAML file
which will be placed in root directory of the Git repository being the subject of the PR.

Detect the presence of certain types of the report based on a conventional location,
and automatically publish them.
If the reports are not in a conventional location,
users could specify the location using the YML file.

link:https://docs.google.com/document/d/1cuC0AvQG3e4GCjIoCwK3J0tcJVAz1eNDKV8d_zXxlO8/edit[More info about the project]

=== Project Summary
This plugin will be developed on the top of the MultiBranch Pipeline plugin.

.This plugin will follow below steps
* clone target repo
* checkout to target branch
* fetch the source branch
* merge source-branch
* call user call user script to build the repo.
* push to target branch [if specified by user in YAML]
* harvest results and reports and post to PR

Plugin will start above steps if and only if the pull request is will be
mergeable to avoid merge conflicts while merging the source branch to target
branch. The pull request is mergebale or not can also be decided by the webhook also.

==== Developement upto 24 May 2018
* Source of YAML file can be specified in job configuration UI
* git wrappers except push are done

==== To de done till 30 May 2018
* Finish work on the plugin skeleton.
* Finish git wrapper functions (merge and push is remaining).
* Call user script.

=== Regular meeting Hours
Every Wednesday 5 PM to 6 PM UTC. Click
link:https://www.timeanddate.com/worldclock/fixedtime.html?msg=Simple+Pull+Request+Plugin+Meeting+Hours&iso=20180523T17&ah=1[here]
to see it in your local time.
