---
layout: project
title: "Hosting Team"
section: projects
tags:
- hosting
- plugin-site
links:
  mailinglist: "/mailing-lists/#jenkinsci-dev-googlegroups-com"
  chat: "/project/teams/hosting/#chat"
---

The Jenkins Hosting Team handles various requests related to hosting of open-source plugins and other components (forking and transferring plugins, managing permissions and update centers, etc.).
There are multiple contributors involved in this activity on a regular basis.

== Team Responsibilities

* Triage and processing of new plugin link:https://github.com/jenkins-infra/repository-permissions-updater/issues?q=is%3Aissue+is%3Aopen++label%3Ahosting-request+[Hosting] requests.
  There is some automation around this process, but human reviews are needed too...
** Ensure that link:/doc/developer/publishing/preparation[plugin publishing requirements] are followed:
naming conventions and `artifactId`s, `groupId`s, documentation, duplication of existing plugins, license compliance, etc.]
** Check plugin compliance with security best practices and recommendations.
* Managing plugin developer and release permissions (link:/doc/developer/plugin-governance/managing-permissions/[documentation]).
* Processing link:/doc/developer/plugin-governance/adopt-a-plugin/[plugin adoption] requests in the developer mailing list
* Processing blacklisting and plugin tagging/doc URL requests in the Update Centers for non-security reasons.
* Maintaining the link:/doc/developer/publishing[publishing] and link:/doc/developer/plugin-governance/[plugin governance] documentation.

== Key repositories

* link:https://github.com/jenkins-infra/repository-permissions-updater[Repository Permission Updater] - Manages release permissions for all components hosted in Jenkins Artifactory
* link:https://github.com/jenkins-infra/update-center2[Jenkins Update Center] - Jenkins Update Center repository.
  Includes update center generation logic, including plugin blacklists, security labels and documentation metadata.
* link:https://github.com/jenkins-infra/ircbot[Jenkins IRC Bot] - our ChatOps tool

== How to contribute?

=== Assisting with Q&A and request reviews

A significant part of this team's work is helping new plugin maintainers to get their plugins hosted and published.
Also, we help with permission management when contributors add new developers or adopt plugins.
There are a lot of channels for these topics, but all of them are public and do not require special permissions to join.
We invite any interested Jenkins contributor to join the team.

How to start contributing?

. Subscribe to the link:/mailing-lists/#jenkinsci-dev-googlegroups-com[Jenkins Developer Mailing list]
. Subscribe to the link:https://github.com/jenkins-infra/repository-permissions-updater/[Repository Permission Updater] repository
. Subscribe to the link:https://github.com/jenkins-infra/update-center2[Jenkins Update Center] repository.

=== Joining the main hosting team

==== Members of the hosting team:
* Adrien Lecharpentier (link:https://github.com/alecharp[@alecharp])
* Alex Earl (link:https://github.com/slide[@slide])
* Alexander Brandes (link:https://github.com/NotMyFault[@NotMyFault])
* Baptiste Mathus (link:https://github.com/batmat[@batmat])
* Oleg Nenashev (link:https://github.com/oleg-nenashev[@oleg-nenashev])
* Tim Jacomb (link:https://github.com/timja[@timja])

==== Requesting membership

If you are interested in joining the team, 
you can request membership in the link:https://groups.google.com/d/forum/jenkinsci-dev[Jenkins Developer mailing list].
The request will be processed and discussed by the community, and the decision will be made based on consensus among contributors.

Eligibility:

* Membership in the team requires a track record of contributions to the hosting process.
  Assisting users with Q&A and request reviews does not require special permissions.
* All applicants should have a signed link:https://github.com/jenkinsci/infra-cla[Contributor License Agreement] before they apply.
* Applicants should link:https://libera.chat/guides/registration[register] their username with NickServ on libera.chat.

A registered username is needed too, if you're using matrix clients, such as element, to connect to room bridged to matrix, like `jenkins-hosting`. Therefore, see link:https://matrix-org.github.io/matrix-appservice-irc/latest/usage.html[the starting guide].

==== Configuration

. Subscribe to all channels and repositories listed in the _Assisting with Q&A and request reviews_ section
. Join the link:/chat/[`#jenkins-hosting` IRC channel] and link:/chat/#cloaks[obtain a cloak].
  It will be needed for ChatOps.
. Request voice permission (`+vV`) from a channel operator in the link:/chat/[`#jenkins-hosting` IRC channel] to get access to the bot commands.
Current channel operator(s):
@timja

==== Notes

* Some requests require manual changes in GitHub repositories for some requests, e.g. plugin renaming.
  Jenkins GitHub org admins manage such requests.
  Create a Jenkins Jira issue if such assistance is needed (project=INFRA, component=github)
* Processing repo transfer requests (when maintainers want to transfer plugins instead of forking) also needs actions from Jenkins GitHub org admins.

== Chat

The team has a dedicated `#jenkins-hosting` IRC channel on Libera Chat.
To join it, follow link:/chat/[these guidelines].

== Meetings

The team has no regular meetings at the moment.
If needed, you can request a meeting in the developer mailing list.

== Tools

* link:/projects/infrastructure/ircbot/[Jenkins IRC Bot] - ChatOps tool for managing the hosting and ownership requests.

== References

* link:https://github.com/orgs/jenkins-infra/teams/hosting[@jenkins-infra/hosting] - team alias in the Jenkins Infrastructure GitHub organization
* Getting Started session:
  link:https://docs.google.com/presentation/d/1bf80nEjbllitdzEM-p00tdr521In5u16GwdTQRI7_ag/edit?usp=sharing[slides]
