---
layout: developersection
title: Plugin Build Process
references:
- url: ../updating-parent/
  title: Guide to Updating Your Maven Parent POM
- url: https://github.com/jenkinsci/plugin-pom/
  title: Plugin parent POM 2.x and up
- url: https://github.com/jenkinsci/maven-hpi-plugin/
  title: Maven HPI Plugin
---

Most Jenkins plugins are built with link:https://maven.apache.org[Maven].
They typically use the link:https://github.com/jenkinsci/plugin-pom/[Jenkins plugin POM] as their parent link:https://maven.apache.org/pom.html[POM], which provides a sensible default configuration for the plugin build.
The link:https://github.com/jenkinsci/maven-hpi-plugin/[Maven HPI plugin] is one of the plugins configured there.
It does the heavy lifting, such as bundling plugins in the HPI/JPI archive format used for Jenkins plugins, or allowing developers to run a debug Jenkins instance with the plugin.

Since version 2.0 of the plugin POM, it's possible to specify the core version dependency of the parent POM independent of its version.footnoteref:[1.x,Up to Jenkins 1.645, the plugin POM was kept in sync with Jenkins releases, so that the minimum required Jenkins version for a plugin determined the versions of the tools used to build the plugin. These versions should no longer be used.]
This allows plugins compatible with older Jenkins releases to benefit from fixes and improvements in the parent POM.
The link:https://github.com/jenkinsci/plugin-pom/blob/master/CHANGELOG.md[plugin POM changelog] provides more details.

== Keeping up to date

It is generally recommended to frequently update to a recent plugin parent POM for multiple reasons:

* Plugin developers and users benefit from bug fixes and improvements to the parent POM and the tools and libraries it specifies
* Additions to the default build like static code analysis and general tests aim to improve the overall quality of plugins.
// TODO Need a good reference for that before including it as example:
// For example, plugins depending on the plugins parent POM 1.637 (with maven-hpi-plugin 1.110) or newer will need to specify the <code>escape-by-default</code> in all Jelly files for the InjectedTest to pass. Plugins depending on older releases may have hidden XSS vulnerabilities.
* Recent versions of the tools (inherited from the parent plugins POM) allow developers to use more advanced tools like the https://github.com/jenkinsci/plugin-compat-tester[plugin compatibility tester] to determine whether their plugin is compatible with newest Jenkins releases.


== Jenkins BOM

Since version 2.195, Jenkins provides a  link:https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies[Maven Bill Of Materials (BOM)]
that centrally defines versions of various libraries used by Jenkins. If you are using Maven to build your plugin, then you can simplify dependency management by importing this BOM,
at `jenkins.version`. Then, dependency versions will automatically be synchronised with whatever version of Jenkins you are building against. This can help to avoid build errors like:

[source]
----
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for commons-codec:commons-codec:1.9 paths to dependency are:
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-commons-codec:commons-codec:1.9
and
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.195
    +-commons-codec:commons-codec:1.12
,
Require upper bound dependencies error for org.slf4j:jcl-over-slf4j:1.7.25 paths to dependency are:
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.slf4j:jcl-over-slf4j:1.7.25
and
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.195
    +-org.slf4j:jcl-over-slf4j:1.7.26
----


What this error is saying is that there is a conflict between the versions of `commons-codec` and `jcl-over-slf4j` specified by the plugin versus Jenkins. Without using the BOM, you would need to go and update the dependencies
in your plugin to match those required by Jenkins, and then keep changing these as your `jenkins.version` changes. With the BOM all you have to do is import the link:https://github.com/jenkinsci/jenkins/blob/master/bom/pom.xml[jenkins-bom]
for the version of Jenkins you are building against, and the versions of these and other common dependencies will be matched to that version of Jenkins.

To use the Jenkins BOM in your plugin, simply add this import to your POM file:

[source, xml]
----
<dependency>
    <groupId>org.jenkins-ci.main</groupId>
    <artifactId>jenkins-bom</artifactId>
    <version>${jenkins.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
----


Or, if you are using the plugin-pom (4.0 or later) as the parent, then things are even easier as there is a profile that will do this import for you. The default behaviour of `plugin-pom` is to _not_ use
the BOM, but you can switch on BOM support by setting the Maven property `use-jenkins-bom`. For example:

[source]
----
	mvn -Djenkins.version=2.195 -Duse-jenkins-bom package
----

This will import the BOM for Jenkins 2.195.

If you want this to become the default for building your plugin, you can avoid having to specify the `use-jenkins-bom` property on the command line every time by putting it into a
link:https://maven.apache.org/configure.html[.mvn/maven.config] file in the root of your plugin project:

[source]
----
	-Duse-jenkins-bom
----
