---
layout: corebaseline
title: Choosing a Jenkins version to build against
---
// This file contains placeholders that are replaced in the Ruby script that's part of the 'corebaseline' layout.

Your plugin's POM controls which version of Jenkins it is building/testing against.

## Choosing a version

You need to balance compatibility and features:

* *Keeping the Jenkins version your plugin builds against low* will allow more users to install and use your plugin. 
In particular, the LTS Release Line is based on slightly older releases to provide a more stable experience for conservative users.
* *Building against recent Jenkins versions* allows you to use recently added core features and API from your plugin. 
You will also use that newer version for `mvn hpi:run`, so it may be easier to test your plugin with newer Jenkins releases. 
* *Do not use versions no longer supported by the update center*, which is currently anything older than PLACEHOLDER_OLDEST_WEEKLY for weekly releases, and PLACEHOLDER_OLDEST_LTS for LTS releases.
* *Prefer the last release within an LTS line over weekly versions and the 2.xxx.1 release within an LTS line*.
* *Prefer releases that no longer result in implied plugin dependencies*.
  Sometimes Jenkins core features are moved into plugins, and any plugin with a dependency on an older core release will have an _implied_ dependency on the new plugin.
  This makes plugin management more difficult for administrators, so core dependencies should ideally be chosen so that there are no, or few, implied dependencies.
  See https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/split-plugins.txt[split-plugins.txt] for details.
  At this time, a dependency on Jenkins versions *newer than PLACEHOLDER_LATEST_SPLIT* will not result in such implied dependencies.

There are link:https://stats.jenkins.io/pluginversions/[statistics of core versions by plugin] that can help you decide.
These are updated monthly.
When updating the core dependency, choose the link:/changelog-stable/[newest LTS version] that doesn't exclude a majority of your existing users (by requiring a newer Jenkins than they have).

## Currently recommended versions

// TODO update
At the moment, the Jenkins releases *PLACEHOLDER_OLDER_LTS_POINT_ONE* and *PLACEHOLDER_NEWER_LTS_POINT_ONE* make good core dependencies unless there are specific reasons, like new features, to choose a different release.

## Changing the minimum required version

Set the `jenkins.version` property in `pom.xml` to the version you need to depend on.

[source,xml]
----
<properties>
  <jenkins.version>PLACEHOLDER_NEWER_LTS_POINT_ONE</jenkins.version>
</properties>
----
