---
layout: developersection
title: Dependency Management
references:
- url: https://github.com/jenkinsci/plugin-pom/
  title: Plugin parent POM 4.0 and up
- url: https://github.com/jenkinsci/jenkins/blob/master/bom/pom.xml
  title: Jenkins Core BOM
---

Plugins frequently have dependencies on specific versions of libraries and other plugins,
each of which is versioned independently.
Each plugin may have dependencies of its own and different versions
of different libraries and  plugins may not be compatible with each other.
Moreover, the dependencies can change with each Jenkins release,
so managing these dependencies manually can be difficult and time consuming.

Dependency issues cause `Require upper bound dependencies` build errors such as:

[source]
----
[WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for commons-codec:commons-codec:1.9 paths to dependency are:
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-commons-codec:commons-codec:1.9
and
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.195
    +-commons-codec:commons-codec:1.12
,
Require upper bound dependencies error for org.slf4j:jcl-over-slf4j:1.7.25 paths to dependency are:
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.slf4j:jcl-over-slf4j:1.7.25
and
+-org.jenkins-ci.plugins:blueocean-display-url:2.3.1-SNAPSHOT
  +-org.jenkins-ci.main:jenkins-core:2.195
    +-org.slf4j:jcl-over-slf4j:1.7.26
----

This error says that a conflict exists between the versions of `commons-codec` and `jcl-over-slf4j` specified by the plugin versus Jenkins.
See
link:https://www.jenkins.io/doc/developer/plugin-development/updating-parent/#understanding-requireupperbounddeps-failures-and-fixes[Understanding requireUpperBoundDeps failures and fixes] for more information.

This page details ways to simplify the management of dependency versions.

== Apache Maven Bill of Materials (BOM)

The link:https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Importing_Dependencies[Apache Maven Bill Of Materials (BOM)]
defines the versions of various libraries used by Jenkins.
It is included in version 2.195 (and LTS version 2.164.x) and later of Jenkins Core.

If you use Maven to build your plugin,
dependencies are defined in the `dependencyManagement` section of you _pom.xml_ file.
You can import the appropriate Jenkins BOM to your _pom.xml_ file
so that dependency versions are automatically synchronised
with the version of Jenkins against which you are building.

To use the Jenkins Core BOM in your plugin:

////
Does this need a hint about how to be sure one is using this?
////
. Be sure that you are using
link:https://github.com/jenkinsci/plugin-pom/[Parent POM for Jenkins Plugins] 
(4.0 or later).
. Go to the the link:https://github.com/jenkinsci/bom[jenkinsci/bom] repository.
. Go to the `bom-*` folder that corresponds to
the Jenkins version against which you are building.
. Open the _pom.xml_ file in that folder.
. Copy the `dependencyManagement` section from the _pom.xml_ file.
. Paste the `dependencyManagement` section into the _pom.xml_ file for your plugin.
If your file already has a `dependencyManagemnt` section,
replace it with this text.
Your _pom.xml_ file should only have one `dependencyManagement` section.
. Rebuild your plugin to see if this solves your dependency issues.

The _README_ file in the jenkinsci/bom repository includes background
and more details about using the BOM in your plugin.


== Dependabot

////
PLEASE CHECK THIS CAREFULLY!
////
The GitHub link:https://github.com/dependabot[Dependabot] feature
can be used to simplify dependency management for builds
no matter what build tools are used.
link:https://github.com/jenkinsci/archetypes/blob/master/.github/dependabot.yml[dependabot.yml]
is the default in the template/archtype.
