---
layout: sig
title: "Configuration as Code"
section: sigs
sigId: "casc"
logo: /images/user.gif
tags:
- configuration-as-code
- jenkins-configuration-as-code
- groovy
- pipeline
- yaml
- gce
- casc
- casc-sig
leads:
- name: "Ewelina Wilkosz"
  id: "ewelinawilkosz"
  github: "ewelinawilkosz"
participants:
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
- name: "Tracy Miranda"
  id: "tracymiranda"
  github: "tracymiranda"
- name: "Nicolas De loof"
  id: "ndeloof"
  github: "ndeloof"
- name: "Liam Newman"
  id: "Liam Newman"
  github: "bitwiseman"

organizations:
- name: "CloudBees"
  github: "cloudbees"

links:
  gitter: jenkinsci/casc-sig
  googlegroup: jenkins-casc-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  The Configuration as Code (casc) group of contributors and collaborators focuses on improving Jenkins configuration as code related tools and practices.

---

The Configuration as Code (casc) group of contributors and collaborators focuses on improving Jenkins configuration as code related tools and practices.

The group focuses on:

* Jenkins Configuration as Code plugin
* groovy hooks
* Configuration management tools
* Pipeline


=== Target Audience

The improvements are targeted at both existing and new Jenkins users that use, or would prefer to use,
different ways to configure Jenkins itself but also build processes as code.

=== Meetings

There will be regular SIG meetings scheduled.
Initially the meetings will be conducted every second week,
then they may be adapted according to the activity.

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.
Participant links will be posted in the SIG Gitter Chat within 10 minutes before the meeting starts.

When needed periodic updates will be performed at other related SIGs (e.g. Cloud Natve SIG)


