---
layout: sig
title: "Cloud Native"
section: sigs
sigId: "cloud-native"
logo: /images/user.gif
tags:
- cloud
- docker
- kubernetes
- aws
- azure
- gce
- cloud-native
- cloud-native-sig
- configuration-as-code
- jcasc
leads:
- name: "Carlos Sanchez"
  id: "csanchez"
  github: "carlossg"
participants:
- name: "Jesse Glick"
  id: "jglick"
  github: "jglick"
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
- name: "Tracy Miranda"
  id: "tracymiranda"
  github: "tracymiranda"
- name: "Ewelina Wilkosz"
  id: "ewelinawilkosz"
  github: "ewelinawilkosz"
- name: "Nicolas De loof"
  id: "ndeloof"
  github: "ndeloof"
- name: "Olivier Vernin"
  id: "olblak"
  github: "olblak"
- name: "Samuel Van Oort"
  id: "svanoort"
  github: "svanoort"
- name: "Leonardo Rossetti"
  id: "Leonardo Rossetti"
  github: "odra"
- name: "Baptiste Mathus"
  id: "Baptiste Mathus"
  github: "batmat"
- name: "Vic Iglesias"
  id: "Vic Iglesias"
  github: "viglesiasce"
- name: "Evan Brown"
  id: "Evan Brown"
  github: "evandbrown"
- name: "Liam Newman"
  id: "Liam Newman"
  github: "bitwiseman"
- name: "Rick"
  id: "LinuxSuRen"
  github: "LinuxSuRen"
- name: "David Currie"
  id: "dcurrie"
  github: "davidcurrie"
- name: "Alex Nordlund"
  id: "deepy"
  github: "deepy"
- name: "Dominic Gunn"
  id: "dgunn"
  github: "dominicgunn"

organizations:
- name: "CloudBees"
  github: "cloudbees"
- name: "Google Cloud Platform"
  github: "GoogleCloudPlatform"
- name: "Microsoft Azure"
  github: "azure"

links:
  gitter: jenkinsci/cloud-native-sig
  googlegroup: jenkins-cloud-native-sig
  meetings: "/projects/sigs/cloud-native/#meetings"

overview: >
  The Cloud Native group of contributors and collaborators focuses on
  improving Jenkins to run on Cloud environments as a "Cloud Native" application.
  The improvements are targeted at both existing and new Jenkins users that use, or would prefer to use,
  Jenkins deployed in one of the cloud providers,
  or using cloud services for their operation.

---

This group of contributors and collaborators focuses on
improving Jenkins to run on Cloud environments as a "Cloud Native" application.

=== Target Audience

The improvements are targeted at both existing and new Jenkins users that use, or would prefer to use,
Jenkins deployed in one of the cloud providers,
or using cloud services for their operation.


=== Areas for Improvement

There are the following main areas for the SIG:

* Pluggable storage - Externalizing data being stored in `JENKINS_HOME`
* Cloud Native Jenkins - Architecture changes and optimizations towards stateless Jenkins
* Configuration as Code - Simplify creation of static Jenkins configurations

=== Pluggable Storage

The current default approach of storing everything into the filesystem is the main reason why Jenkins does not fit the "Cloud Native" model, with features like HA, zero downtime, or pay per use.
While there are plenty of plugins that implement parts of this vision, this becomes cumbersome to configure and a usability nightmare for users, as jep:300[] has pointed out.
Going towards a model where cloud services are consumed where it makes sense, the overall complexity on operating Jenkins in a cloud or containerized environment is greatly reduced.
Other related projects include https://github.com/jenkinsci/jep/tree/master/jep/400[Jenkins X]
and link:https://github.com/jenkins-infra/evergreen[Jenkins Evergreen]
which would greatly benefit from a Cloud Native storage for Jenkins.

There are several clear areas open for improvement, which are summarized here and will be detailed in future documents.
A mayor pain point is the usage of local disk as all-purpose storage, which causes issues running on containerized or distributed environments, requiring highly performant filesystems, and all the configuration pain like initial sizing and resizing with downtime.
We believe that by using cloud provided services the overall usability, performance and scalability can be improved while enabling new demanded functionality.

See the link:pluggable-storage[Pluggable Storage page] for more information about the projects.
You can also find more information about Pluggable Storage and priorities
in link:/blog/2018/07/30/introducing-cloud-native-sig/[this blogpost].

=== Cloud Native Jenkins

If all the data currently stored in the filesystem is moved to external storage a replicated Jenkins service becomes possible,
and the next steps are true High Availability, rolling or canary upgrades and zero downtime.

It also opens a way towards stateless Jenkins.
By converting Jenkins to a "stateless" application long awaited features such as high availability and replication would help to operate Jenkins more efficiently,
with zero downtime and reducing risk in upgrade operations by using canary or rolling deployments.

Currently there is no JEPs associated with this topic.

=== Configuration as Code

Configuration as Code related topics belong to the Cloud Native SIG.
The Configuration as Code (casc) group consists of contributors and collaborators focuses on improving Jenkins configuration as code related tools and practices.

The target audience are both existing and new Jenkins users that use, or would prefer to use,
different ways to configure Jenkins as code.

There is a separate link:https://calendar.google.com/event?action=TEMPLATE&tmeid=a28yZTc0cGdxcHZwcHJ1aWNjZWcyMnU5ZGdfMjAxODA5MTJUMDcwMDAwWiBld2VAcHJhcW1hLm5ldA&tmsrc=ewe%40praqma.net&scp=ALL[Office Hours meeting] conducted every second week on Wednesdays, 9am CEST.
Click on a link:https://calendar.google.com/event?action=TEMPLATE&tmeid=a28yZTc0cGdxcHZwcHJ1aWNjZWcyMnU5ZGdfMjAxODA5MTJUMDcwMDAwWiBld2VAcHJhcW1hLm5ldA&tmsrc=ewe%40praqma.net&scp=ALL[link] for an invitation.
Anyone can join a meeting, meetings will be recorded via Jenkins Hangouts-on-Air.

Participant links will be posted in the link:https://gitter.im/jenkinsci/configuration-as-code-plugin[Configuration as Code Gitter Chat] within 10 minutes before the meeting starts.

When needed the topics discussed at Office Hours meeting will be reported back at Cloud Native SIG meeting.

=== Meetings

There will be regular SIG meetings scheduled.
Initially the meetings will be conducted once per month,
then they may be adapted according to the activity.

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.

==== 2018-09-17. Meeting at the Jenkins Contributor summit

We will have a BoF table at the link:/blog/2018/07/25/contributor-summit/[Jenkins Contributor Summit]
in San Francisco on Sep 17.
There will be no recording, but we will still have public meeting notes from the event

* link:https://docs.google.com/document/d/1Hw1mpXSpH8BAe2YK5SrCfFuHQLRf__KnjDBK_SbhGls/edit?usp=sharing[Meeting notes]

==== 2018-08-16. Status meeting

Status sync-up: External Build Log Storage (JEP-207, JEP-210, JEP-212),
External Configuration Storage (JEP-213),
Jenkins Configuration-as-Code.

* link:https://www.youtube.com/watch?v=aoJn4AgAEdk[Youtube video]
* link:https://docs.google.com/document/d/1_lciDKHI7iKc6X043eWl1rMCcn_ixVgpwcKRLLu12Ts/edit[Meeting Agenda and Notes]


==== 2018-07-31. External Build Log Storage

At this inaugural meeting we had introductions from SIG participants.
Then link:https://github.com/oleg-nenashev[Oleg Nenashev] and
link:https://github.com/jglick[Jesse Glick] presented  and discussed
the current state of the External Build Log Storage work
(link:https://issues.jenkins-ci.org/browse/JENKINS-38313[JENKINS-38313]).

* link:https://docs.google.com/presentation/d/1wcbvqmOhY0jIrKt_X9XEBfcXe29zycvhoWoI3qgSyDM/[Intro Slides]
* link:https://www.youtube.com/watch?v=9lTOtC9wA_I[Video recording]
* link:https://docs.google.com/document/d/1sWpIOY0jtHMTXa3H58Rmdp7untoTjKnpEfUbwIPdeQk/edit[Meeting Notes]
