---
layout: documentation
title: Defining execution environments
---
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:imagesdir: /doc/book/resources
:hide-uri-scheme:


In the
link:../running-multiple-steps[previous section]
you may have noticed the `agent` directive in each of the examples. The
`agent` directive tells Jenkins where and how to execute the Pipeline, or
subset thereof. As you might expect, the `agent` is required for all Pipelines.


Underneath the hood, there are a few things `agent` causes to happen:

* All the steps contained within the block are queued for execution by Jenkins.
  As soon as an <<../../book/glossary/#executor, executor>> is available, the
  steps will begin to execute.
* A <<../../book/glossary/#workspace, workspace>> is allocated which will
  contain files checked out from source control as well as any additional
  working files for the Pipeline.


////
XXX: Link to all the various agent directive options in the handbook
https://gist.github.com/abayer/93b68cddfac2b808d905e27d12d7ef99
////
There are several ways to define agents for use in Pipeline, for this tour we
will only focus on using an ephemeral Docker container for the Pipeline.

=== Using Docker

Pipeline is designed to easily use Docker images and containers to
run inside. This allows the Pipeline to define the build and test environment
and tools required without having to manually configure various agents. This
can pretty much be any image you like, your build steps and stages will run
inside it.

[pipeline]
----
// Declarative //
pipeline {
    agent {
        docker { image 'node:7-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
// Script //
node {
    /* Requires the Docker Pipeline plugin to be installed */
    docker.image('node:7-alpine').inside {
        stage('Test') {
            sh 'node --version'
        }
    }

}
----


**link:../environment[Continue to "Using environment variables"]**
