---
layout: documentation
title:  Jenkins Upgrade Guide
notitle: true
---

== Upgrading to Jenkins LTS 2.60.x

Each section covers the upgrade from the previous LTS release, the section on 2.60.1 covers the upgrade from 2.46.3.

=== Upgrading to Jenkins LTS 2.60.1

==== Java 8 Required

Jenkins 2.60.1 is the first LTS release to require Java 8.
This applies to both master and agents.

If you're using the Maven Plugin for your Maven-based builds, note that the JDK selected for them needs to be at least Java 8 as well with this change.
If an older JDK is configured, Jenkins will attempt to find a more recent JDK automatically.
If your Maven projects need to be built with JDK 7, consider converting them to freestyle projects, or look into Maven toolchains.

If you're using the plugin:ssh-slaves[SSH Slaves] plugin, it may attempt to start the agent process on an unsupported JRE, which will fail.
If this happens, make sure to install a supported JRE (8 or newer) on the agent system and make it available on the PATH.
If you rely on SSH Slaves plugin to automatically install a Java runtime on the agent, delete the existing one inside the agent root directory after upgrading to SSH Slaves 1.17 or newer (1.20 recommended, see below).

==== Groovy 2.4.8 Upgrade

https://issues.jenkins-ci.org/browse/JENKINS-33358[JENKINS-33358],
https://issues.jenkins-ci.org/browse/JENKINS-42189[JENKINS-42189]

Groovy has been upgraded to 2.4.8 to fix a memory leak.

If you're using Pipeline, note that you will need to update the plugin:workflow-cps[Pipeline: Groovy] plugin to version 2.28 or later.

==== Trilead SSH Library Upgrade

https://issues.jenkins-ci.org/browse/JENKINS-42959[JENKINS-42959]

The Trilead SSH library bundled with Jenkins has been upgraded.
If you're using the SSH slaves plugin to connect agents via SSH, a known issue resulting from that upgrade can result in connection failures.

The plugin:ssh-slaves[SSH Slaves] plugin should be upgraded to version 1.20 or newer.

==== RPM Packaging No Longer Performs Recursive `chown`

https://issues.jenkins-ci.org/browse/JENKINS-23273[JENKINS-23273]

The RPM packaging post-install step used to perform a recursive `chown` on `JENKINS_HOME` and other directories to ensure correct ownership.
Especially in the case of `JENKINS_HOME` this could lead to very long-running installations and updates.

This has been optimized to only perform the recursive `chown` if the Jenkins home directory is owned by a different user than the one the service would be running as.

NOTE: All files inside `JENKINS_HOME` are expected to be owned, readable, and writable by the Jenkins user.

==== Windows Services Upgrade

https://issues.jenkins-ci.org/browse/JENKINS-39231[JENKINS-39231],
https://issues.jenkins-ci.org/browse/JENKINS-39237[JENKINS-39237]

Jenkins 2.60.1 includes major improvements in Windows Service management,
which were introduced from Jenkins 2.50 to 2.60.
In particular, link:https://github.com/kohsuke/winsw[Windows Service Wrapper (WinSW)] has been updated to the 2.x baseline.

Newly installed agent and master instances will get the features automatically, 
but existing instances require extra configuration.
In particular, the following features can be enabled: 

* Automatic upgrade of link:https://github.com/jenkinsci/remoting[Remoting] library (aka "slave.jar") on agents
* Automatic termination of runaway agent processes on agents
* Automatic termination of Jenkins master processes 

NOTE: The described features and guidelines apply to classic JNLP agents installed as services.
Plugins like link:https://plugins.jenkins.io/windows-slaves[Windows Agents Plugin] do not offer all features so far, see 
link:https://issues.jenkins-ci.org/browse/JENKINS-42743[JENKINS-42743].

===== Upgrading old Jenkins agents

The upgrade steps are described in the 
https://github.com/jenkinsci/windows-slave-installer-module#upgrading-old-agents[Agent Upgrade Guide]
(Windows Agent Installer Module Docs). 

The only non-trivial action is a XML configuration change. 
During the `2.60.1` upgrade it is recommended to...

1. Add the link:https://github.com/kohsuke/winsw/blob/master/doc/extensions/runawayProcessKiller.md[Runaway Process Killer] extension. 
 ** See the example in the template referenced below.
1. Enable automatic download of the `slave.jar` file
 ** Example: `<download from="JENKINS_URL/jnlpJars/slave.jar" to="%BASE%\slave.jar"/>` (replace `JENKINS_URL` by the actual URL)
 
NOTE: If you use Jenkins with HTTP over insecure network,
be aware about potential MITM attacks.
By default new agents have auto-update enabled for HTTPS only.

When updating the `jenkins-slave.xml` configuration file, you can use 
link:https://github.com/jenkinsci/windows-slave-installer-module/blob/windows-slave-installer-1.9/src/main/resources/org/jenkinsci/modules/windows_slave_installer/jenkins-slave.xml[this file] 
as a template for the new configuration.

===== Upgrading Jenkins master

Jenkins master executables may run away in some edge cases,
hence it is recommended to enable link:https://github.com/kohsuke/winsw/blob/master/doc/extensions/runawayProcessKiller.md[Runaway Process Killer] for them.

In order to upgrade the master, do the following...

1. Update Jenkins to 2.60.1 and start the instance. It will automatically upgrade the `jenkins.exe` file.
1. Stop the Jenkins service
1. Modify `jenkins.xml` in the installation root
** To enable Runaway Process Killer, add link:https://github.com/jenkinsci/windows-slave-installer-module/blob/windows-slave-installer-1.9/src/main/resources/org/jenkinsci/modules/windows_slave_installer/jenkins-slave.xml#L62-L75[the following entry] to `jenkins.xml`
1. Start Jenkins instance again

To verify the upgrade correctness, check the `jenkins.wrapper.log` output. 
It should contain log entries for Runaway Process Killer after the successful startup.

===== Enabling extra Windows service features

WinSW and Agent installer offer many advanced features you may want to enable.
See more details in these documents: 
 
* link:https://github.com/kohsuke/winsw/blob/master/README.md[WinSW Documentation]
* link:https://github.com/jenkinsci/windows-slave-installer-module/blob/master/README.md[Windows Agent Installer Documentation]

