---
layout: documentation
title:  Jenkins Upgrade Guide
notitle: true
---

== Upgrading to Jenkins LTS 2.60.x

Each section covers the upgrade from the previous LTS release, the section on 2.60.1 covers the upgrade from 2.46.3.

=== Upgrading to Jenkins LTS 2.60.1

==== Java 8 Required

Jenkins 2.60.1 is the first LTS release to require Java 8.
This applies to both master and agents.

If you're using the Maven Plugin for your Maven-based builds, note that the JDK selected for them needs to be at least Java 8 as well with this change.
If an older JDK is configured, Jenkins will attempt to find a more recent JDK automatically.
If your Maven projects need to be built with JDK 7, consider converting them to freestyle projects, or look into Maven toolchains.

==== Groovy 2.4.8 Upgrade

https://issues.jenkins-ci.org/browse/JENKINS-33358[JENKINS-33358],
https://issues.jenkins-ci.org/browse/JENKINS-42189[JENKINS-42189]

Groovy has been upgraded to 2.4.8 to fix a memory leak.
If you're using Pipeline, note that you will need to update the Pipeline: Groovy plugin to version 2.28 or later.

==== Trilead SSH Library Upgrade

https://issues.jenkins-ci.org/browse/JENKINS-42959[JENKINS-42959]

The Trilead SSH library bundled with Jenkins has been upgraded.
If you're using the SSH slaves plugin to connect agents via SSH, a known issue is TODO
