---
layout: documentation
title:  Jenkins Upgrade Guide
notitle: true
---

== Upgrading to Jenkins LTS 2.73.x

Each section covers the upgrade from the previous LTS release, the section on 2.73.1 covers the upgrade from 2.60.3.

=== Upgrading to Jenkins LTS 2.73.1


==== Known Issue: Agent connection failures involving Jenkins masters with undefined or non-writable home directory

link:https://issues.jenkins-ci.org/browse/JENKINS-45755[JENKINS-45755]

A regression involving agent connections has been identified.
If the user home directory (`HOME`, not `JENKINS_HOME`) on the Jenkins master is undefined, or not writable, no remoting connections can be established.

The following features are known to impacted:

. Agent connections
. Remoting-based CLI connections (deprecated since 2.46.2)
. Building Maven projects (Maven Integration Plugin)

The error shown will include the path to a directory `.jenkins/cache/jars` inside the home directory, and its stack trace will reference `hudson.remoting.FileSystemJarCache`.

The Jenkins Docker image has been changed to have a defined, writable home directory for the Jenkins user.
Typical web application container (e.g. Tomcat) setups may not have a writable home directory for the user the container is running as, and may need to be adapted to work around this issue.

Possible workarounds:

. Make the specified home directory writable to the Jenkins user.
. Define a home directory that is writable for the user Jenkins is running as.
. Override it for the process running Jenkins, for example using the `-Duser.home=/path/to/directory` parameter to the `java` command, pointing to a writable directory.


==== Known Issue: Possible connectivity issue involving ed25519 SSH keys

link:https://issues.jenkins-ci.org/browse/JENKINS-46754[JENKINS-46754]

A possible regression involving SSH authentication using password protected ed25519 keys has been identified.
More details and the current state of the investigation is available in the linked issue.


==== Groovy 2.4.11 Upgrade

link:https://issues.jenkins-ci.org/browse/JENKINS-43197[JENKINS-43197]

Groovy was updated from 2.4.8 to 2.4.11.
This may resolve existing Groovy-related memory problems, as 2.4.9 contains the fix for link:https://issues.apache.org/jira/browse/GROOVY-8067[GROOVY-8067].
It may no longer be necessary to apply the `groovy.use.classvalue` workaround.


==== Winstone 4.1 Upgrade

link:https://issues.jenkins-ci.org/browse/JENKINS-43713[JENKINS-43713]

The embedded Jetty container has been updated from version 9.2.15 to version 9.4.5.
In this update, support for the optional `--spdy` parameter has been dropped.
Jenkins will now refuse to start if the `---spdy` parameter is specified.
It needs to be removed from any Jenkins init scripts.


==== Build Authorization

link:https://issues.jenkins-ci.org/browse/JENKINS-22949[JENKINS-22949],
link:https://issues.jenkins-ci.org/browse/JENKINS-30574[JENKINS-30574]

This change affects only users of Authorize Project Plugin.

Previous releases of Jenkins implemented a special permission fallback when Authorize Project Plugin did not specify a global default configuration:
For the purposes of *Build other projects* and *Build after other projects are built*, if Authorize Project configuration did not specify a build authorization for the job in question, it fell back to acting with the permissions of the _anonymous_ user.
This ensured a secure default, but only for these trigger-related permission checks.

This behavior has been changed, and Jenkins will now perform the permission check as SYSTEM (i.e. with full permissions) to determine whether a project should be built.

To restore the previous behavior, configure a global *Project default Build Authorization* setting the default authorization to that of the anonymous user.
This feature has been implemented in Authorize Project Plugin version 1.2.0.
