---
layout: documentation
title:  Jenkins Upgrade Guide
notitle: true
---

== Upgrading to Jenkins LTS 2.73.x

Each section covers the upgrade from the previous LTS release, the section on 2.73.1 covers the upgrade from 2.60.3.

=== Upgrading to Jenkins LTS 2.60.1

==== Groovy 2.4.11 Upgrade

link:https://issues.jenkins-ci.org/browse/JENKINS-43197[JENKINS-43197]

Groovy was updated from 2.4.8 to 2.4.11.
This may resolve existing Groovy-related memory problems, as 2.4.9 contains the fix for link:https://issues.apache.org/jira/browse/GROOVY-8067[GROOVY-8067].
It may no longer be necessary to apply the `groovy.use.classvalue` workaround.

==== Remoting 3.10 Upgrade

TODO

==== Winstone 4.1 Upgrade

TODO

==== Build Authorization

TODO

==== Possible issue involving ed25519 SSH keys

link:https://issues.jenkins-ci.org/browse/JENKINS-46754[JENKINS-46754]

A possible regression involving SSH authentication using password protected ed25519 keys has been identified.
More details and the current state of the investigation is available in the linked issue.

==== Possible issue with agents on systems with undefined or non-writable home directory

link:https://issues.jenkins-ci.org/browse/JENKINS-45755[JENKINS-45755]

A possible regression involving agent connectivity issues has been identified.
This can occur if the user home directory (`HOME`, not `JENKINS_HOME`) is undefined (e.g. Docker) or not writable.
More details and the current state of the investigation is available in the linked issue.
