---
layout: post
title: "Remoting Update. Jan 2018"
tags:
- remoting
- agents
- upgrade
- core
author: oleg_nenashev
---

:toc:

## What has changed?

### Remoting 3.15

### Switching class serializattion to whitelist

As it has been announced in link:/blog/2018/01/13/jep-200[JEP-200 blogpost],
starting from Jenkins 2.102 Jenkins master performs all class serialization over Remoting
in a whitelist mode.
Classes will be rejected unless they are whitelisted of located in Jenkins components
(core, plugins, modules or specially annotated libraries).

### Extension of the blacklist

Although Jenkins master switched to the whitelist,
Remoting on agent side still uses blacklists while serializing data.
In Remoting 3.16  the default blacklist got also extended a bit
so that now it includes more classes which have been formerly blacklisted on the master side only.

In particular, serialization of net.sf.TODO.JSON objects was prohibited.
If you use this version of Remoting on agents, there is a risk of issues in plugins even if
your Jenkins master is older than 2.102.

## What's next?

### Introducing a "minimal supported" version

In Jenkins 2.97 we had a major fallout, which has been caused by binary compatibility
between Remoting 3.15 on the master side and older remoting versions on agents.
You can find more info about this issue in link:TODO[this post-mortem thread].
TL;DR: refactoring is *evil*.

It is recommended to keep Remoting on agents up to date
(use link:TODO[Version Column Plugin] for that!),
but de-facto there is was no formal minimal version requirement.
This month I have seen Remoting 2.28 connected to fresh Jenkins master, for example.

The current state puts a pressure

### Disabling JNLP1/2 

## Useful links

* link:/projects/remoting/[Remoting Sub-Project] on Jenkins website
* link:https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md[Remoting Release Notes]
* link:https://github.com/jenkinsci/remoting/blob/master/README.md[Remoting documentation] on GitHub
* link:https://speakerdeck.com/onenashev/day-of-jenkins-2017-dealing-with-agent-connectivity-issues[My slides] about Remoting issues troubleshooting
