---
layout: gsocproject2
title: "Automatic git cache maintenance on the controller"
goal: "Automate the maintenance of cached git repositories on the Jenkins controller"
category: tools
year: 2022
sig: platform
tags:
- gsoc2022
- plugins
status: "Selected"
student: HrushikeshRao
mentors:
- "rishabhbudhouliya"
- "markewaite"
links:
  gitter: https://gitter.im/jenkinsci/git-plugin
  draft: https://docs.google.com/document/d/1Jc0zyLtbh0lj1MwG9FdBY9PRed5falQGnUbU1KfREqk/edit#heading=h.63lwv71bjiiy 
  idea: /projects/gsoc/2022/project-ideas/automatic-git-cache-maintenance
  meetings: "/projects/gsoc/2022/projects/automatic-git-cache-maintenance/#office-hours"
---

=== Abstract

The project aims to add https://git-scm.com/docs/git-maintenance[git-maintenance] to improve performance of the Jenkins controller. Git-maintenance optimizes caches, thereby executing the git commands faster.

=== Rationale

Git caches that exist on the controller can become slower and larger than necessary during the lifetime of the remote repositories. Command line git focuses on high performance for frequent operations and relies on end users to perform most repository maintenance. Garbage collection, removal of deleted branches, and other operations are not performed by default on most cached repositories. This project aims to undertake the responsibility of git maintenance tasks by doing all the hard work behind the scenes and providing a simple user interface to configure the maintenance.

=== Implementation

Two separate plugins are used to implement the Git Cache Maintenance

. Git Plugin - 
  Administrators can enable maintenance tasks by configuring required settings in the UI. Based on this configuration, Git Plugin schedules maintenance tasks for caches present on the controller. It uses background process to perform scheduling. Based on the git-version present on the system, it decides which maintenance tasks it can execute. The result regarding the execution is displayed to the Administrator in the UI.

. Git Client Plugin -
  Responsible for execution of maintenance tasks(GitCLI) by Jenkins.

Development Strategy: Test Driven Development (Suggested by the mentors).

=== Office hours

* Specific: link:https://zoom.us/j/94692927320?pwd=VHBvSU5rZzZNY3RUNUpNUzBqSDExQT09[Git Maintenance Office Hours] - Wednesday @ *0300 UTC*
* General: link:https://zoom.us/j/97478518050?pwd=NjZ4KzByUGsrdFBDM1p2a3czRSswUT09[GSoC office hours] - Thursday @ *1500 UTC*

=== Links

Here come some useful links

* link:https://docs.google.com/document/d/1oYNgbcld3nMKoQpzFSSUW-BizBU7aeu3hLshNHJDp9c/edit[Project Notes]
* link:https://docs.google.com/document/d/1vpeIX75i5ylM068JsMdhB8npuS7EEkIANdCmpLN_Yzo/edit[Brainstorming Ideas]
* link:https://docs.google.com/document/d/16gQ_8PDM2TRlF0Wbcaivt1q0dULa6uLBHDCDw-Ibcig/edit[Design Documentation]
* link:https://github.com/jenkinsci/git-plugin[Git Plugin]
* link:https://github.com/jenkinsci/git-client-plugin[Git Client Plugin]
