---
layout: gsocproject2
title: "Jenkinsfile Runner Action for GitHub Actions"
goal: "Implement a (near) feature-complete version of Jenkinsfile Runner Action for GitHub Actions"
category: tools
year: 2022
sig: platform
tags:
- gsoc2022
- plugins
status: "Selected"
student: "YimingGong"
mentors:
- "krisstern"
- "abhyudayasharma"
links:
  chat: "/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions/#chat"
  draft: "https://docs.google.com/document/d/1SC__C6V8LFZvs99uR4fqoraJPcF_-JG5QhvBdaYaVFo/edit?usp=sharing"
  idea: "/projects/gsoc/2022/project-ideas/jenkinsfile-runner-action-for-github-actions"
  meetings: "/projects/gsoc/2022/projects/jenkinsfile-runner-action-for-github-actions/#office-hours"
---


=== Abstract
Jenkinsfile Runner Action for GitHub Actions provides the customized containerized environment and useful GitHub Actions for users to run the Jenkins pipeline inside GitHub Actions. It aims at applying Jenkins in the GitHub Actions which is a Function-as-a-Service context.
This feature is based on the Jenkinsfile Runner, which is a command line tool for the Jenkins pipeline execution engine.
The user can define the Jenkins pipeline environment by extending several Vanilla images and configuring the Jenkins Configuration-as-Code plugin.

=== Rationale
The Jenkins pipeline environment includes the Jenkins core war package and the Jenkinsfile Runner.
All the dependencies are incorporated into the containers.
As the GitHub Actions support using the predefined containers and building custom images, the containers - which include the Jenkins runtime - are able to start inside the GitHub Actions.

=== Implementation
Jenkinsfile Runner Action for GitHub Actions defines the dependencies in the prebuilt container and wraps the entrypoint in one GitHub Action so that the users can call the running environment and the related GitHub Action in their workflow definitions. 
The decoupling of environment declaration and Jenkinsfile Runner Action enables the users to utilize other useful GitHub Actions. This project will provide several vanilla images including necessary dependencies to run the Jenkins pipeline.
Users can extend these images to set up their customized environment.
What's more, the user can install the plugins, which is enabled by Plugin Installation Manager Tool, and then configure Jenkins, which is enabled by Configuration-as-Code plugin.

=== Chat

We use the `#gsoc-jenkinsfile-runner` channel in the CDF Slack workspace.

link:/chat/#continuous-delivery-foundation[Explanations about the CDF Slack] (the invitation link is at the end of the paragraph).

=== Office hours

* (General) Official weekly Jenkins office hours: Thursdays 3pm to 3:30pm UTC
* (Project-based) link:https://us05web.zoom.us/j/81912236313?pwd=WGtHTHZnSHFhS3dYTmVHUXdrK05Sdz09[Weekly project-specific office hours]: Mondays 12pm to 12:30pm UTC

=== Project Links
Here come some useful links:

* link:https://github.com/jenkinsci/jenkinsfile-runner/[Jenkinsfile runner]
* link:https://github.com/Cr1t-GYM/jenkins-action-poc/[Jenkins Action POC Repository]
* link:https://docs.google.com/document/d/154a7pZbLaZqGYpgsefohDHU2uueYypVNJJ_aBEyPHFY/edit#heading=h.ozbrfhdlfv83/[Project Plan]
* link:https://github.com/Cr1t-GYM/JekinsTest/[A demo about applying these Jenkins Actions in a small SpringBoot project]
* link:https://github.com/jenkinsci/jenkinsfile-runner-image-packs/[Jenkinsfile runner image packs]
* link:https://github.com/jenkinsci/configuration-as-code-plugin/[Configuration as code plugin]
* link:https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction/[GitHub Docker container action]
