---
title: Translate a help file
layout: developer
---
:toc:

This guide explains how to generate and translate help files used in Jenkins localization.

Stand-alone HTML files are often used in Jenkins for things like inline help messages.
To translate these resources, add the locale code between the file name and the extension.
For example, the Japanese version of `+abc.html+` would be `+abc_ja.html+`.
These files must be encoded in UTF-8.

== Generate help files

Help text is stored in HTML files.
The maintainers of the plugin usually provide those files for the default locale.
Translators create help files for their specific locale by appending the locale identifier to the file name.
For example, `Messages.properties` for Portuguese as spoken in Brazil is named `Messages_pt_BR.properties`.
`Messages.properties` for Japanese is named `Messages_ja.properties`.

Insert instructions here

== Translate help files

Translate the HTML help files and save them with the UTF-8 character set.

== Test the translation

Test the translation by running Jenkins in the target locale with the plugin enabled.

----
LANG=pt_BR.utf-8 mvn hpi:run
----


== Commit the changes

Commit the changes and submit a pull request with the changes.
