---
title: Translate a properties file
layout: developer
references:
- url: https://en.wikipedia.org/wiki/.properties
  title: .properties file format on Wikipedia
---
:toc:

This guide explains how to generate and translate property files used in Jenkins localization.
Property files provide the strings that are displayed to users.

Property files can be associated with Java files or with Jelly views.

== Generate property files

The other messages that need to be translated are in Jelly view files,
which are in `+src/main/resources/**.jelly+`. To localize them, first
you run Maven to generate a skeleton property file for your locale:

----
mvn stapler:i18n -Dlocale=fr
----

This generates `+*_fr.properties+` throughout `+src/main/resources+` with empty values.
If the file already exists, missing entries are appended.

It is not necessary to translate the entire file.
Entries that are empty fall back to the default locale.

== Translate property files

Insert instructions here

== Test the translation

Insert instructions here

== Commit the changes

Insert instructions here
