---
layout: project
title: "Jenkins Remoting"
section: projects
tags:
- remoting
- agent
- agents
links:
  gitter: 'jenkinsci/remoting'
  googlegroup: 'jenkinsci-dev'
---

Jenkins Remoting is a library, and executable Java archive, which implements the communication layer in Jenkins.
This includes the TCP-based communication protocols, remote procedure calls, class loading, data streaming, etc.
Currently Remoting is primarily used in communications between the Jenkins controller and Jenkins agents.

The Remoting sub-project includes the Remoting library itself, package for agents, and a number of Remoting-specific plugins and core modules.


:toc:

== Remoting Usage in Jenkins

* Agent executables (`remoting.jar` is named `agent.jar` or `slave.jar` in Jenkins)
* Controller to Agent communication protocols being used in various Agent types, including inbound (formerly known as “JNLP”) and plugin:ssh-slaves[SSH] agents
* link:/doc/book/managing/cli/[Jenkins CLI], Remoting mode is **deprecated since 2.54** (link:/blog/2017/04/11/new-cli/[announcement])
* Communication with Maven instance in the plugin:maven-plugin[Maven Integration plugin].

== Project Components

=== Remoting Library

Remoting Library is the main component of the sub-project.
The code base is located in a link:https://github.com/jenkinsci/remoting[separate repository],
which also contains Remoting developer and user documentation.
This library also has an independent release cycle and LTS release lines.

Links:

* link:/redirect/project/remoting[Home Page]
* link:/redirect/project/remoting/changelog[Release Notes]
* link:/redirect/project/remoting/protocols[Remoting Protocols]
* link:/redirect/project/remoting/troubleshooting[Troubleshooting] (under construction)

=== Jenkins Core and Modules

Although Remoting library is a standalone component,
Jenkins core includes some extensions and modules for working with Remoting.
Core extensions also allow implementing custom protocols on-demand (e.g. for Jenkins CLI).
There is ongoing activity on detaching these core components to Jenkins plugins
(see jira:JENKINS-44099[]),
but in the meantime upgrading of Jenkins core may be required to fix Remoting issues.

Jenkins core extensions:

* link:/doc/developer/extensions/jenkins-core/#agentprotocol[Agent Protocol] - Protocol Implementations
* link:/doc/developer/extensions/jenkins-core/#jnlpagentreceiver[JNLP Agent Receiver] - Receives Incoming connections

Modules:

* link:https://github.com/jenkinsci/slave-installer-module[Agent Installer Module] - Generic API for Remoting Agent installations
* link:https://github.com/jenkinsci/windows-slave-installer-module[Windows Agent Installer Module] - Provides logic for installing Jenkins agents as Windows services, powered by link:https://github.com/kohsuke/winsw/[WinSW project]
* etc.

=== Packaging

There are several packages which bundle the Remoting library and allow connecting Jenkins agents
via one of remoting protocols.

* link:https://hub.docker.com/r/jenkins/agent/[Docker Agent]: Base image, which bundles Remoting
* link:https://hub.docker.com/r/jenkins/inbound-agent/[Docker Inbound Agent]: Image, which can be used to connect agents using TCP or WebSocket
* Jenkins CLI executable (Requires Remoting CLI to be enabled on the Jenkins controller)
* Swarm Agent Connector executable in link:https://plugins.jenkins.io/swarm[Swarm Plugin]
