---
layout: solution
title: "Jenkins and Docker"
---

Combining Jenkins and link:https://www.docker.io[Docker] together can bring
improved speed and consistency to your automation tasks, which is why we've
collected some *hopefully* helpful resources on this page to get you started!

== What's Docker?

[quote, Wikipedia]
____
link:https://en.wikipedia.org/wiki/Docker_%28software%29[Docker] is an
open-source project that automates the deployment of applications inside
software containers, by providing an additional layer of abstraction and
automation of operating-system-level virtualization on Linux.*
____

What this offers to Jenkins users is a means to isolate different jobs from one another, quickly clean a job's workspace or even dynamically deploy or schedule jobs with Docker containers to increase resource utilization and efficiency.

== Resources

* link:https://github.com/jenkinsci/workflow-aggregator-plugin/blob/master/demo/README.md[Docker image for the Jenkins Workflow demo]

