---
layout: solution
title: "Pipeline as Code with Jenkins"
---

The default interaction model with Jenkins, historically, has been very web UI
driven, requiring users to manually create jobs, then manually fill in the
details through a web browser. This requires additional effort to create and
manage jobs to test and build multiple projects, it also keeps the
configuration of a job to build/test/deploy separate from the actual code being
built/tested/deployed. This prevents users from applying their existing CI/CD
best practices to the job configurations themselves.


== Pipeline

With the introduction of the link:https://plugins.jenkins.io/workflow-aggregator[Pipeline
plugin],
users now can implement a project's entire build/test/deploy pipeline
in a `Jenkinsfile` and store that alongside their code, treating their
pipeline as another piece of code checked into source control.

The Pipeline plugin was inspired by the
link:https://wiki.jenkins.io/display/JENKINS/Build+Flow+Plugin[Build Flow
plugin] but aims to improve upon some concepts explored by Build Flow with
features like:

* the ability to suspend/resume of executing jobs.
* checking the pipeline definition into source control (`Jenkinsfile`)
* support for extending the domain specific language with additional,
  organization specific steps, via the
  "link:/doc/book/pipeline/shared-libraries/[Shared Libraries]" feature.

In an adjacent space is the
link:https://plugins.jenkins.io/job-dsl[Job DSL plugin]
which is worth mentioning as well.


== Getting Started

* link:/doc/pipeline[Getting Started with Pipeline]
* The link:https://plugins.jenkins.io/workflow-aggregator[Pipeline
  plugin]
  has a fairly comprehensive
  link:https://github.com/jenkinsci/pipeline-plugin/blob/master/TUTORIAL.md[tutorial]
  checked into its source tree too.
* link:https://go.cloudbees.com/docs/cloudbees-documentation/cookbook/ch13.html#ch13__continuous_delivery_with_jenkins_pipeline[Overview of Continuous Delivery with Pipeline]
* link:https://dzone.com/refcardz/continuous-delivery-with-jenkins-workflow[DZone Refcard]

== Demos

Demonstrations of Pipeline functionality you can run locally.

* link:https://hub.docker.com/r/jenkinsci/workflow-demo/[continuous delivery]
* link:https://hub.docker.com/r/jenkinsci/pipeline-as-code-github-demo/[GitHub organization folders]
* link:https://hub.docker.com/r/jenkinsci/parallel-test-executor-demo/[running tests in parallel]
* link:https://hub.docker.com/r/jenkinsci/docker-workflow-demo/[build, test, and publish with Docker]

== Additional resources

* link:https://plugins.jenkins.io/workflow-aggregator[Pipeline Plugin page]
* link:https://github.com/jenkinsci/workflow-plugin/blob/master/COMPATIBILITY.md[Plugins compatible with Workflow]
* link:https://stackoverflow.com/questions/tagged/jenkins-workflow[Stack Overflow "jenkins-workflow" tag]
* link:https://github.com/jenkinsci/workflow-examples[Examples/snippets repository]


== Presentations

The presentations below were given by link:https://github.com/jglick[Jesse Glick], author of the link:https://plugins.jenkins.io/workflow-aggregator[Pipeline Plugin]

++++
<center>
<iframe width="560" height="315" frameborder="0"
  src="https://www.youtube-nocookie.com/embed/VkIzoU7zYzE"></iframe>
</center>
++++

* link:https://www.youtube.com/watch?v=gpaV6x9QwDo[2014 presentation] (with link:https://www.cloudbees.com/sites/default/files/2014-0618-Boston-Jesse_Glick-Workflow.pdf[slides])

Other presentations:

* link:https://www.slideshare.net/cloudbees/pimp-your-continuous-delivery-pipeline-with-jenkins-workflow-wjax-14[Pimp your Continuous Delivery Pipeline with Jenkins workflow (W-JAX 14)] by link:https://github.com/cyrille-leclerc[Cyrille Le Clerc]
