////
This file is only meant to be included as a snippet in other documents.
////

=== Download and run Jenkins in Docker

In this tutorial, we'll be running Jenkins as a Docker container from a Docker
image of Jenkins with Blue Ocean (pre-bundled). Read more about these concepts
in the Docker documentation's https://docs.docker.com/get-started/[Getting
Started, Part 1: Orientation and setup] page and the
https://docs.docker.com/engine/docker-overview/[Docker overview] page for an
extensive overview of Docker's capabilities.

*Tip:* If you've already run though this procedure from link:..[another
introductory tutorial], then you can skip this section and
<<fork-and-clone-the-sample-repository-on-github,jump to the next>>.

. Open up a terminal/command prompt window.
. Pull the https://hub.docker.com/r/jenkinsci/blueocean/[latest Docker image for
Jenkins with Blue Ocean (pre-bundled)] by running the command: +
  `docker pull jenkinsci/blueocean` +
  This command downloads the latest Docker image for Jenkins with Blue Ocean
  that will run Jenkins as a container in your locally running Docker instance
  (also known as your Docker host).
. Create the following Docker data volume that will be used to persistently
store all data in the Jenkins home directory (explained in a bit more detail
later) by running the command: +
  `docker volume create jenkins-data` +
  *Note:* This data volume allows you to shut down Docker (for example, part way
  through the tutorial) without you losing any work you've already done.
. Start the downloaded Jenkins/Blue Ocean Docker image (for running this
tutorial) using the appropriate command:
** *On Mac OS X and Linux:*
+
----
docker run --rm \
  -u root \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$HOME":"$HOME" \
  jenkinsci/blueocean
----
+
** *On Windows:* +
  The following command is effectively the same command shown for Mac OS X/Linux
  above but the `-v "$HOME":"$HOME"` is replaced with `-v "%HOMEPATH%":"$HOME"`
  (assuming that your user home directory on Windows is on the C drive). Also,
  if you're using the Windows command prompt, replace the backslash symbols `\`
  at the end of each line with carat symbols instead `^`, giving you:
+
----
docker run --rm ^
  -u root ^
  -p 8080:8080 ^
  -v jenkins-data:/var/jenkins_home ^
  -v /var/run/docker.sock:/var/run/docker.sock ^
  -v "%HOMEPATH%":"$HOME" ^
  jenkinsci/blueocean
----
+
*Note:* This command's options do the following:

* `--rm` - Automatically removes the Docker container (which is the
  instantiation of this Jenkins/Blue Ocean Docker image) when the Docker image
  is shut down. Keeps things tidy if you need to quit Jenkins.
* `-u root` - Sets the default user within the container to be root. This is not
  a recommended practice for running Docker images in production. However, this
  is fine for the sake of this tutorial.
* `-p 8080:8080` - Makes the container running the Jenkins/Blue Ocean Docker
  image accessible through port 8080.
* `-v jenkins-data:/var/jenkins_home` - Mounts the `jenkins-data` data volume
  (which you created in the previous step) with the `/var/jenkins_home`
  directory in the container.
* `-v "$HOME":"$HOME"` (and its variants for other operating systems) - Mounts
  the `$HOME` directory on the host (i.e. your local) machine (usually the
  `/Users/<your-username>` directory) to the `$HOME` directory in the container
  (usually `/root`).

+
If you have some experience with Docker, you can add an option like
`--name jenkins-tutorials`, which gives the Jenkins/Blue Ocean Docker container
a name like "jenkins-tutorials". This makes it easier to refer to the container
if, for instance you wish to access the container through a terminal/command
prompt.

+
. After the 2 sets of asterisks appear in the terminal/command prompt window,
  browse to `http://localhost:8080` and wait until the *Unlock Jenkins* page
  appears.
. From your terminal/command prompt window, copy the automatically-generated
  alphanumeric password (between the 2 sets of asterisks).
. On the *Unlock Jenkins* page, paste this password in the *Administrator
  password* field and click *Continue*.
. On the *Customize Jenkins* page, click *Install suggested plugins*. The
  *Getting Started* page is displayed, showing the progression of Jenkins being
  configured and the suggested plugins being installed. (This process may take a
  few minutes.)
. When the *Create First Admin User* page appears, specify your details in the
  respective fields and click *Save and Finish*.
. Click *Start using Jenkins* to and you're now ready to begin using Jenkins.

Throughout the remainder of this tutorial, you can stop the Jenkins/Blue Ocean
Docker container by typing `Ctrl-C` in the terminal/command prompt window from
which you ran the `docker run ...` command above.

To restart the Jenkins/Blue Ocean Docker container, run the same `docker run
...` command you ran in step 4 (above).

*Note:* You can also install Jenkins locally by:

. Downloading the http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest
  stable Jenkins WAR file] to a directory you wish to run Jenkins from - for e.g.
* `/Users/<your-username>` on Mac OS X,
* `/home/<your-username>` on Linux or
* `C:\Users\<your-username>` on Windows, +
  where `<your-username>` is your user account's name on your operating system.
. Opening up a terminal/command prompt window to the download directory.
. Running `java -jar jenkins.war --httpPort=8080`.
. Browsing to `http://localhost:8080`.
. Following the instructions to complete the installation.

However, this process doesn't automatically install the Blue Ocean features,
which would need to installed separately via a set of related plugins through
Jenkins Management.
