////
This file is only meant to be included as a snippet in other documents.
////

=== Prerequisites

For this tutorial, you will require:

* A macOS, Linux or Windows machine with:
** 256 MB of RAM - more than 512MB is recommended
** 10 GB of drive space for Jenkins and your Docker image
* The following software installed:
** https://git-scm.com/downloads[Git] and optionally
   https://desktop.github.com/[GitHub Desktop]
** https://www.docker.com/[Docker] - navigate to *Get Docker* at the top of the
   website to access the Docker download that's suitable for your platform +
   *Note:* If you use Linux, ensure you configure Docker so it can be managed
   as a non-root user. Read more about this in Docker's
   https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
   steps for Linux] page of their documentation. This page also contains
   information about how to configure Docker to start on boot. Furthermore, the
   tutorial assumes that you are not running Docker commands as the root user,
   but instead with a single user account that also has access to the other
   tools used throughout this tutorial.
