---
layout: documentation
title: Using Jenkins to build a multibranch Pipeline project
section: doc
---

:toc:
:toclevels: 3
:imagesdir: /doc/book/resources

This tutorial shows you how to use Jenkins to orchestrate building a simple
https://nodejs.org/en/[Node.js] and https://reactjs.org/[React] application
with the https://www.npmjs.com/[Node Package Manager (npm)], and selectively
deliver the results for development and production purposes.

Before starting this tutorial, it is recommended that you run through at least
one of the initial set of link:../#introductory-tutorials[Introductory
tutorials] from the link:..[Tutorials overview] page first to familiarize
yourself with CI/CD concepts (relevant to a technology stack you're most
familiar with), how these concepts are implemented in Jenkins and the
fundamentals of Jenkins Pipelines.

This tutorial uses the same application that the
link:../building-a-node-js-and-react-app-with-npm[Using Jenkins to build a
Node.js and React application with npm] tutorial is based on. Therefore, you'll
be building the same application although this time, from different Git branches
that selectively execute different stages depending on the Git branch that your
Jenkins build is running on.

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<run-jenkins-in-docker,run Jenkins in Docker>> from link:..[another tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/_prerequisites.adoc[]
** https://git-scm.com/downloads[Git] and optionally
   https://desktop.github.com/[GitHub Desktop].

include::doc/tutorials/_run-jenkins-in-docker.adoc[]


=== Fork and clone the sample repository on GitHub

Obtain the simple "Welcome to React" Node.js and React application from GitHub,
by forking the sample repository of the application's source code into your own
GitHub account and then cloning this fork locally.

. Ensure you are signed in to your GitHub account. If you don't yet have a
  GitHub account, sign up for a free one on the https://github.com/[GitHub
  website].
. Fork the
  https://github.com/gilesgas/building-a-multibranch-pipeline-project[`building-a-multibranch-pipeline-project`]
  on GitHub into your local GitHub account. If you need help with this process,
  refer to the https://help.github.com/articles/fork-a-repo/[Fork A Repo]
  documentation on the GitHub website for more information.
. Begin cloning your forked `building-a-multibranch-pipeline-project` repository
  (on GitHub) locally to your machine by opening up a terminal/command line
  window to the directory in which the repository will be cloned. This tutorial
  assumes that `simple-node-js-react-npm-app` will be cloned within the
  following directories on these platforms, which you should `cd` into now:
* macOS - `/Users/<your-username>/Documents/GitHub`
* Linux - `/home/<your-username>/GitHub`
* Windows - `C:\Users\<your-username>\Documents\GitHub`

+
where `<your-username>` is your user account's name on your operating system.

+
*Note:*

** On a Windows machine, use a Git bash command line window (as opposed to the
   usual Microsoft command prompt).
** Alternatively, and in particular if you have the GitHub Desktop app installed
   on your machine, in GitHub, you can click the green *Clone or download*
   button on your forked repository and follow the instructions to clone the
   repository locally. If you use GitHub Desktop, you can omit the following
   step.

+
. Run the following command to continue/complete cloning your forked repo: +
  `git clone https://github.com/YOUR-GITHUB-ACCOUNT-NAME/building-a-multibranch-pipeline-project` +
  where `YOUR-GITHUB-ACCOUNT-NAME` is the name of your GitHub account.


[source,groovy]
----
pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 -p 5000:5000'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
    }
}
----

[source,groovy]
----
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
                sh './jenkins/scripts/deliver-for-development.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
                sh './jenkins/scripts/deploy-for-production.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
----
