---
layout: documentation
title: Creating a Pipeline in Blue Ocean
section: doc
---

:toc:
:imagesdir: /doc/book/resources

This tutorial shows you how to use Jenkins's Blue Ocean feature to create a
Pipeline that will orchestrate building a simple application.

Before starting this tutorial, it is recommended that you run through at least
one of the initial set of tutorials from the link:..[Tutorials overview] page
first to familiarize yourself with CI/CD concepts and how they are implemented
in Jenkins.

This tutorial uses the same application that the
link:../building-a-node-js-and-react-app-with-npm[Using Jenkins to build a
Node.js and React application with npm] tutorial is based on and you'll be
building the same application, but this time completely through Blue Ocean.
Since Blue Ocean provides a simplified Git-handling experience, you'll be
interacting directly with GitHub (as opposed to a local clone of this
repository).

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<download-and-run-jenkins-in-docker,downloaded and run Jenkins in Docker>> from
link:..[another introductory tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/_prerequisites.adoc[]

include::doc/tutorials/_download-and-run-jenkins-in-docker.adoc[]


=== Wrapping up

Well done! You've just completed building a simple Node.js and React application
using npm in Jenkins!

The "build", "test" and "deliver" stages you created above are the basis for
building more complex Node.js and React applications in Jenkins, as well as
Node.js and React applications that integrate with other technology stacks.

Because Jenkins is extremely extensible, it can be modified and configured to
handle practically any aspect of build orchestration and automation.

To learn more about what Jenkins can do, check out:

* The link:/doc/tutorials[Tutorials overview] page for other introductory
  tutorials.
* The link:/doc/book[User Handbook] for more detailed information about using
  Jenkins, such as link:/doc/book/pipeline[Pipelines] (in particular
  link:/doc/book/pipeline/syntax[Pipeline syntax]) and the
  link:/doc/book/blueocean[Blue Ocean] interface.
* The link:/node[Jenkins blog] for the latest events, other tutorials and
  updates.

include::doc/_feedback-footer.adoc[]
