---
layout: documentation
title: Creating a Pipeline in Blue Ocean
section: doc
---

:toc:
:imagesdir: /doc/book/resources

This tutorial shows you how to use Jenkins's Blue Ocean feature to create a
Pipeline that will orchestrate building a simple application.

Before starting this tutorial, it is recommended that you run through at least
one of the initial set of tutorials from the link:..[Tutorials overview] page
first to familiarize yourself with CI/CD concepts and how they are implemented
in Jenkins.

This tutorial uses the same application that the
link:../building-a-node-js-and-react-app-with-npm[Using Jenkins to build a
Node.js and React application with npm] tutorial is based on. Therefore, you'll
be building the same application, but this time completely through Blue Ocean.
Since Blue Ocean provides a simplified Git-handling experience, you'll be
interacting directly with the repository on GitHub (as opposed to a local clone
of this repository).

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<download-and-run-jenkins-in-docker,downloaded and run Jenkins in Docker>> from
link:..[another introductory tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/_prerequisites.adoc[]

include::doc/tutorials/_download-and-run-jenkins-in-docker.adoc[]


=== Fork the sample repository on GitHub

Fork the simple "Welcome to React" Node.js and React application on GitHub into
your own GitHub account.

. Ensure you are signed in to your GitHub account. If you don't yet have a
  GitHub account, sign up for a free one on the https://github.com/[GitHub
  website].
. Fork the
  https://github.com/gilesgas/creating-a-pipeline-in-blue-ocean[`creating-a-pipeline-in-blue-ocean`]
  on GitHub into your local GitHub account. If you need help with this process,
  refer to the https://help.github.com/articles/fork-a-repo/[Fork A Repo]
  documentation on the GitHub website for more information. +
  *Note:* This is a different repository to the one used in the
  link:../building-a-node-js-and-react-app-with-npm[Using Jenkins to build a
  Node.js and React application with npm] tutorial. Although these repositories
  contain the same application code, ensure you fork and use the correct one
  before continuing on.


=== Create your Pipeline project in Blue Ocean

. Ensure you have accessed Jenkins's Blue Ocean interface. To do this, log in to
  Jenkins (if necessary) and either:
* Click *Open Blue Ocean* on the left +
  or
* Browse to `http://localhost:8080/blue`
. Under *Welcome to Jenkins* in the center of the page, click *Create a new
  Pipeline*. +
  *Note:* If you don't see this, click *New Pipeline* at the top right.
. Under *Where do you store your code?*, click *GitHub*.
. Under *Connect to GitHub*, click *Create an access key here*.
. In the new browser tab, sign in to your GitHub account (if necessary) and on
  the GitHub's *New Personal Access Token* page, specify a brief description for
  your GitHub access token (e.g. `Create Pipeline in Blue Ocean Tutorial`). +
  *Note:* An access token is usually an alphanumeric string that respresents
  your GitHub user account (and its various features and areas). Access tokens
  can be used by other applications (like Jenkins) to access aspects of your
  GitHub account on your behalf.
. Scroll down to the end of the page (leaving all other *Select scopes* options
  with their default settings) and click *Generate token*.
. On the resulting *Personal access tokens* page, copy your newly generated
  access token.
. Back in Blue Ocean, paste the access token into the *Your GitHub access token*
  field and click *Connect*.
.


=== Wrapping up

Well done! You've just completed building a simple Node.js and React application
using npm in Jenkins!

The "build", "test" and "deliver" stages you created above are the basis for
building more complex Node.js and React applications in Jenkins, as well as
Node.js and React applications that integrate with other technology stacks.

Because Jenkins is extremely extensible, it can be modified and configured to
handle practically any aspect of build orchestration and automation.

To learn more about what Jenkins can do, check out:

* The link:/doc/tutorials[Tutorials overview] page for other introductory
  tutorials.
* The link:/doc/book[User Handbook] for more detailed information about using
  Jenkins, such as link:/doc/book/pipeline[Pipelines] (in particular
  link:/doc/book/pipeline/syntax[Pipeline syntax]) and the
  link:/doc/book/blueocean[Blue Ocean] interface.
* The link:/node[Jenkins blog] for the latest events, other tutorials and
  updates.

include::doc/_feedback-footer.adoc[]
