---
layout: documentation
title: Creating a Pipeline in Blue Ocean
section: doc
---

:toc:
:imagesdir: /doc/book/resources

This tutorial shows you how to use Jenkins to orchestrate building a simple
https://nodejs.org/en/[Node.js] and https://reactjs.org/[React] application
with the https://www.npmjs.com/[Node Package Manager (npm)].

If you are a Node.js and React developer who is new to CI/CD concepts, or you
might be familiar with these concepts but don't know how to implement building
your application using Jenkins, then this tutorial is for you.

The simple Node.js and React application (which you'll obtain from a sample
repository on GitHub) generates a web page with the content "Welcome to React"
and is accompanied by a test to check that the application renders
satisfactorily.

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<download-and-run-jenkins-in-docker,downloaded and run Jenkins in Docker>> from
link:..[another introductory tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/_prerequisites.adoc[]

include::doc/tutorials/_download-and-run-jenkins-in-docker.adoc[]


=== Wrapping up

Well done! You've just completed building a simple Node.js and React application
using npm in Jenkins!

The "build", "test" and "deliver" stages you created above are the basis for
building more complex Node.js and React applications in Jenkins, as well as
Node.js and React applications that integrate with other technology stacks.

Because Jenkins is extremely extensible, it can be modified and configured to
handle practically any aspect of build orchestration and automation.

To learn more about what Jenkins can do, check out:

* The link:/doc/tutorials[Tutorials overview] page for other introductory
  tutorials.
* The link:/doc/book[User Handbook] for more detailed information about using
  Jenkins, such as link:/doc/book/pipeline[Pipelines] (in particular
  link:/doc/book/pipeline/syntax[Pipeline syntax]) and the
  link:/doc/book/blueocean[Blue Ocean] interface.
* The link:/node[Jenkins blog] for the latest events, other tutorials and
  updates.

include::doc/_feedback-footer.adoc[]
