=== Download and run Jenkins in Docker

In this tutorial, we'll be running Jenkins as a Docker container from a Docker
image of Jenkins with Blue Ocean (pre-bundled). For more information about these
concepts, see the Docker documentation's
https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation and
setup] page and the https://docs.docker.com/engine/docker-overview/[Docker
overview] page for an extensive overview of Docker's capabilities.

. Open up a terminal/command prompt window.
. Pull the https://hub.docker.com/r/jenkinsci/blueocean/[latest Docker image for
Jenkins with Blue Ocean (pre-bundled)] by running the command: +
  `docker pull jenkinsci/blueocean` +
  This command downloads the latest Docker image for Jenkins with Blue Ocean
  that will run Jenkins as a container in your locally running Docker instance.
. Create the following Docker data volumes that will be used to persistently
store all data in the Jenkins home directory and Maven repository (explained in
more detail later) by running the commands: +
  `docker volume create jenkins-data` +
  and +
  `docker volume create maven-repository`
+
--
NOTE: These data volumes allow you to shut down Docker (for example, part way
through the tutorial) without you losing any work you've already done.
--
+
. Start the downloaded Jenkins/Blue Ocean Docker image (for running this
tutorial) using the appropriate command:
* *On Mac OS X:* +
  `docker run --rm --name jenkins-tutorials -u root -p 8080:8080
  -v /Users:/Users -v jenkins-data:/var/jenkins_home
  -v maven-repository:/root/.m2 -v /var/run/docker.sock:/var/run/docker.sock
  jenkinsci/blueocean`
* *On Linux:* +
  Use the Mac OS X command above but replace `-v /Users:/Users` with
  `-v /home:/home`
* *On Windows:* +
  Use the Mac OS X command above but replace `-v /Users:/Users` with
  `-v c:/Users:/Users` (assuming that the user's home directory is on the C
  drive)

+
[NOTE]
====
This command's options do the following:

* `--rm` - Automatically removes the Docker container (which is the
  instantiation of this Jenkins/Blue Ocean Docker image) when the Docker image
  is shut down. Keeps things tidy if you need to quit Jenkins.
* `--name jenkins-tutorials` - Assigns the name “jenkins-tutorials” to the
  container of the Jenkins/Blue Ocean Docker image. Makes it easier to
  identify the container in Docker.
* `-u root` - Sets the default user within the container to be root. This is not
  a recommended practice for running Docker images in production. However, this
  is fine for the sake of this tutorial.
* `-p 8080:8080` - Makes the container running the Jenkins/Blue Ocean Docker
  image accessible through port 8080.
* `-v /Users:/Users` (and its variants for other operating systems) - Mounts the
  `/Users` directory on your local machine to a directory called `/Users` in the
  container.
* `-v jenkins-data:/var/jenkins_home` - Mounts the `jenkins-data` data volume
  (which you created in the previous step) with the `/var/jenkins_home`
  directory in the container.
* `-v maven-repository:/root/.m2` - Mounts the `maven-repository` data volume
  with the `/root/.m2` directory in the container.
====

+
. After the 2 sets of asterisks appear in the terminal/command prompt window,
  browse to `http://localhost:8080` and wait until the *Unlock Jenkins* page
  appears.
. From your terminal/command prompt window, copy the automatically-generated
  alphanumeric password (between the 2 sets of asterisks).
. On the *Unlock Jenkins* page, paste this password into the *Administrator
  password* field and click *Continue*.
. On the *Customize Jenkins* page, click *Install suggested plugins*. The
  *Getting Started* page is displayed, showing the progression of Jenkins being
  configured and the suggested plugins being installed. (This process may take a
  few minutes.)
. When the *Create First Admin User* page appears, specify your details in the
  respective fields and click *Save and Finish*.
. Click *Start using Jenkins!* to and you're now ready to begin using Jenkins.

[NOTE]
====
You can also install Jenkins locally by:

. Downloading the http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest
  stable Jenkins WAR file] to a directory you wish to run Jenkins from - for e.g.
* `/Users/<your-username>` on Mac OS X,
* `/home/<your-username>` on Linux or
* `C:\Users\<your-username>` on Windows, +
  where `<your-username>` is your user account's name on your operating system.
. Opening up a terminal/command prompt window to the download directory.
. Running `java -jar jenkins.war --httpPort=8080`.
. Browsing to `http://localhost:8080`.
. Following the instructions to complete the installation.

However, this process doesn't automatically install the Blue Ocean features,
which would need to installed separately via a set of related plugins through
Jenkins Management.
====
