---
layout: documentation
title: Tutorials overview
section: doc
---

This part of the Jenkins User Documentation contains a series of introductory
tutorials to help you begin building your applications in an automated fashion
with Jenkins.

If you're a developer who wants to improve your understanding of Continuous
Integration (CI) / Continuous Delivery (CD) concepts, or you might already be
familiar with these concepts but don't yet know how to implement them in
Jenkins, then these tutorials are a great place to start.

== Introductory tutorials

The following tutorials show how to use Jenkins to cover the basics of CI/CD
concepts based on specific technology stacks.

Choose the tutorial that's relevant to your technology stack or one that you're
most familiar with:

* link:build-a-java-app-with-maven[Build a Java app with Maven]
* link:build-a-node-js-and-react-app-with-npm[Build a Node.js and React app with
  npm]
* link:build-a-python-app-with-pyinstaller[Build a Python app with PyInstaller]

The following tutorials show how to use key features of Jenkins (such as
link:/doc/book/blueocean/[Blue Ocean]) to facilitate implementing CI/CD
processes to build your applications:

* link:create-a-pipeline-in-blue-ocean[Create a Pipeline in Blue Ocean]

== Advanced tutorials

The following tutorials demonstrate more advanced features of Jenkins and how
to manage your Pipeline projects with greater sophistication and flexibility.

* link:build-a-multibranch-pipeline-project[End-to-End Multibranch Pipeline Project Creation]


'''
++++
include::_partials/_feedback-footer.html[]
++++
