---
layout: documentation
title: Tutorials overview
section: doc
---

This part of the Jenkins User Documentation contains a series of introductory
tutorials to help you begin building your applications in an automated fashion
with Jenkins.

If you're a developer who wants to improve your understanding of Continuous
Integration (CI) / Continuous Delivery (CD) concepts, or you might already be
familiar with these concepts but don't yet know how to implement them in
Jenkins, then these tutorials are a great place to start.

== Introductory tutorials

The following tutorials show how to use Jenkins to cover the basics of CI/CD
concepts based on specific technology stacks.

Choose the tutorial that's relvant to your technology stack or one that you're
most familiar with:

* link:building-a-java-app-with-maven[Using Jenkins to build a Java application
  with Maven]
* link:building-a-node-js-and-react-app-with-npm[Using Jenkins to build a
  Node.js and React application with npm]

The following tutorials show how to use key features of Jenkins (such as
link:/doc/book/blueocean/[Blue Ocean]) to facilitate implementing CI/CD
processes to build your applications:

* link:creating-a-pipeline-in-blue-ocean[Creating a Pipeline in Blue Ocean]

== Advanced tutorials

* link:building-a-multibranch-pipeline-project[Using Jenkins to build a
  multibranch Pipeline project]

include::doc/_feedback-footer.adoc[]
