---
layout: documentation
title: Using Jenkins to build a Java/Maven project
section: doc
---

:toc:

This tutorial shows you how to automate building a simple Java project (built
with Maven) using Jenkins.

If you are a Java/Maven developer who is new to CI/CD concepts, or you might be
familiar with these concepts but don't know how to implement building your
project using Jenkins, then this tutorial is for you.

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<download-and-run-jenkins-in-docker,downloaded and run Jenkins in Docker>> from
link:..[another introductory tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/prerequisites.adoc[]

include::doc/tutorials/download-and-run-jenkins-in-docker.adoc[]


=== Fork and clone the sample repository on GitHub

. Ensure you are signed in to your GitHub account.
+
TIP: If you don't yet have a GitHub account, you can sign up for a free one on
the https://github.com/[GitHub website].
+
. Fork the
  https://github.com/gilesgas/simple-java-maven-app[`simple-java-maven-app`] on
  GitHub into your local GitHub account. If you need help with this process,
  refer to the https://help.github.com/articles/fork-a-repo/[Fork A Repo]
  documentation on the GitHub website for more information.
. Begin cloning your forked `simple-java-maven-app` repository (on GitHub)
  locally to your machine by opening up a terminal window to the directory in
  which the repo will be cloned. In this tutorial, we'll assume that
  `simple-java-maven-app` will be cloned into:
* `/Users/<your-username>/GitHub/Documents` for Mac OS X,
* `/home/<your-username>/GitHub` for Linux or
* `C:\Users\<your-username>\GitHub\Documents` for Windows,

+
where `<your-username>` is your user account's name on your operating system.

+
[NOTE]
====
* On a Windows machine, use a Git bash command prompt window (as opposed to the
  usual Microsoft command prompt).
* Alternatively, and in particular if you have the GitHub Desktop app installed
  on your machine, in GitHub, you can click the green *Clone or download* button
  on your forked repository and follow the instructions to clone the repository
  locally. If you use GitHub Desktop, you can omit the following step.
====

+
. Run the following command to continue/complete cloning your forked repo: +
  `git clone https://github.com/YOUR-GITHUB-ACCOUNT-NAME/simple-java-maven-app` +
  where `YOUR-GITHUB-ACCOUNT-NAME` is the name of your GitHub account.


=== Create your Pipeline project in Jenkins

. Back to Jenkins, log in again if necessary and click *create new jobs* under
  *Welcome to Jenkins!*
. In the *Enter an item name* field, specify the name for your new Pipeline
  project. In this tutorial, we'll assume `simple-java-maven-app`.
. Scroll down and click *Pipeline*, then click *OK* at the end of the page.
. ( _Optional_ ) On the next page, specify a brief description for your Pipeline
  in the *Description* field (e.g. `An entry-level Pipeline demonstrating how to
  build a simple Java Maven project using Jenkins.`)
. Click the *Pipeline* tab at the top of the page to scroll down to the
  *Pipeline* section.
. From the *Definition* field, choose the *Pipeline script from SCM* option.
  This option tells Jenkins to obtain your Pipeline from Source Control
  Management (SCM), which will be your locally cloned Git repository.
. From the *SCM* field, choose *Git*.
. In the *Repository URL* field, specify the directory path of your locally
  cloned repo above - i.e.
* `/Users/<your-username>/Documents/GitHub/simple-java-maven-app` for Mac OS X,
* `/home/<your-username>/GitHub/simple-java-maven-app` for Linux or
* `C:\Users\<your-username>\Documents\GitHub\simple-java-maven-app` for Windows.
. Click *Save* to save your new Pipeline project. You're now ready to begin
  creating your Jenkinsfile, which you'll be checking into your cloned Git repo.


=== Create your initial Pipeline as a Jenkinsfile

You're now ready to create your Pipeline that will automate building your
Java/Maven project in Jenkins. Your Pipeline will be created as a `Jenkinsfile`,
which will be committed to your locally cloned Git repository
(`simple-java-maven-app`).
