---
layout: documentation
title: Using Jenkins to build a Node.js/React project
section: doc
---

:toc:
:imagesdir: /doc/book/resources

This tutorial shows you how to build a simple
https://nodejs.org/en/[Node.js]/https://reactjs.org/[React] application using
the https://www.npmjs.com/[Node Package Manager (npm)], whose overall build
process will be orchestrated in Jenkins.

If you are a Node.js/React developer who is new to CI/CD concepts, or you might
be familiar with these concepts but don't know how to implement building your
project using Jenkins, then this tutorial is for you.

The simple Node.js/React application (which you’ll obtain from a sample
repository on GitHub) generates a web page with the content "Welcome to React"
and is accompanied by a unit test to check that the application works as
expected.

*Duration:* This tutorial takes 20-40 minutes to complete (assuming you've
already met the <<prerequisites,prerequisites>> below). The exact duration will
depend on the speed of your machine and whether or not you've already
<<download-and-run-jenkins-in-docker,downloaded and run Jenkins in Docker>> from
link:..[another introductory tutorial].

You can stop this tutorial at any point in time and continue from where you left
off.

include::doc/tutorials/_prerequisites.adoc[]

include::doc/tutorials/_download-and-run-jenkins-in-docker.adoc[]


=== Fork and clone the sample repository on GitHub

Obtain the simple "Welcome to React" Node.js/React application from GitHub, by
forking the sample repository of the application's source code into your own
GitHub account and then cloning this fork locally.

. Ensure you are signed in to your GitHub account. If you don't yet have a GitHub account,
  sign up for a free one on the https://github.com/[GitHub website].
. Fork the
  https://github.com/gilesgas/simple-java-maven-app[`simple-java-maven-app`] on
  GitHub into your local GitHub account. If you need help with this process,
  refer to the https://help.github.com/articles/fork-a-repo/[Fork A Repo]
  documentation on the GitHub website for more information.
. Begin cloning your forked `simple-java-maven-app` repository (on GitHub)
  locally to your machine by opening up a terminal/command line window to the
  directory in which the repository will be cloned. In this tutorial, we'll
  assume that `simple-java-maven-app` will be cloned within the following
  directories on these platforms, which you should `cd` into now:
* macOS - `/Users/<your-username>/Documents/GitHub`
* Linux - `/home/<your-username>/GitHub`
* Windows - `C:\Users\<your-username>\Documents\GitHub`

+
where `<your-username>` is your user account's name on your operating system.

+
*Note:*

** On a Windows machine, use a Git bash command line window (as opposed to the
   usual Microsoft command prompt).
** Alternatively, and in particular if you have the GitHub Desktop app installed
   on your machine, in GitHub, you can click the green *Clone or download*
   button on your forked repository and follow the instructions to clone the
   repository locally. If you use GitHub Desktop, you can omit the following
   step.

+
. Run the following command to continue/complete cloning your forked repo: +
  `git clone https://github.com/YOUR-GITHUB-ACCOUNT-NAME/simple-java-maven-app` +
  where `YOUR-GITHUB-ACCOUNT-NAME` is the name of your GitHub account.
