---
layout: post
title: "Tutorials in the Jenkins User Documentation"
tags:
- jenkins
- tutorial
- blueocean
- pipeline
author: gilesgas
---

Regular perusers of the link:/doc[Jenkins User Documentation] may have noticed
the presence of the *Tutorials* part (between the *Guided Tour* and *User
Handbook*) that appeared in the last couple of months and gradually began to get
populated with, well, tutorials.


== Why tutorials?

My exposure to Jenkins and its usage over the years has been patchy at best,
although I've had some degree of experience as a user of various continuous
delivery (CD) tools like Jenkins throughout that time and am reasonably familiar
with the advantages these tools can offer software development teams.

Now, as one of the major contributors to the Jenkins User Documentation (and
faced with a reasonably steep learning curve), it quickly became apparent to me
how there was a lack of documentation to hand-hold people relatively new to
Jenkins through the entire application building process (from initial build
stages through to test and delivery stages) using genuine apps.

Furthermore, as a general trend over the years, I've found that while many
software developers are familiar with the broader concept of "developer
operations" (or simply "devops"), fewer seem less familiar with the concepts of
CD and related tools to facilitate devops within organizations.

With the guidance and assistance of helpful colleagues, I therefore decided to
embark on creating a series of Jenkins tutorials (based on Daniele Procida's
description of "tutorials" in his blog post
"link:https://www.divio.com/en/blog/documentation/[What nobody tells you about
documentation]") to help fill these documentation and knowledge gaps.

You can access all currently available tutorials from the
link:/doc/tutorials[Tutorials overview] page in the Jenkins User Documentation.


==== Introductory tutorials

CD is based on the fundamental process of *building software* > *testing it* >
*delivering it*, where typically:

* The "building" part involves compiling the software and/or ensuring all
  necessary libraries and dependencies are in place for it to run as intended.
* The "testing" part involves testing the built software with automated tests to
  ensure that changes implemented by developers function as expected.
* The "delivery" part involves packaging the software in a way that can be
  delivered to customers or other users.

The first set of tutorials on the link:/doc/tutorials[Tutorials overview] page
(beginning with "Using Jenkins to build ..." in their titles) demonstrate how
to build a simple application for a given technology stack like
