---
layout: gsocproject2
title: "Using OpenRewrite Recipes for Plugin Modernization or Automation Plugin Build Metadata Updates"
goal: "Explore ways OpenRewrite recipes can be used for Jenkins plugin modernization or automation of plugin build metadata updates"
category: Tools
year: 2024
sig: infra
tags:
- gsoc2024
status: "Selected"
student: sridamul
mentors:
- "jonesbusy"
- "berviantoleo"
- "gounthar"
- "iamrajiv"
links:
  slack: "https://cdeliveryfdn.slack.com/archives/C071YTZ807N"
  draft: https://docs.google.com/document/d/1e1QkprPN6fLpFXk_QqBUQlJhZrAl9RvXbOXOiJ-gAuY/edit?usp=sharing
  idea: /projects/gsoc/2024/project-ideas/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates
  meetings: "/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates/#office-hours"
---


=== Abstract

OpenRewrite enables large-scale distributed source code refactoring for framework migrations, vulnerability patches, and API migrations via large-scale automated source code refactoring.
While the original focus was on the Java language, OpenRewrite is continuously expanding language and framework coverage.

=== Rationale

The Jenkins ecosystem combines a monolithic core with a modular plugin system.
True, this design provides a great degree of flexibility and robustness, yet also it poses challenges to propagating large-scale changes throughout the ecosystem.
The lack of automation has led to many plugins falling behind with regard to ecosystem-wide migrations.
This project proposes the creation of a new tool to apply generic transformations across the Jenkins ecosystem.

=== Implementation

The project will consist of the following steps:

1. **Research**: Identify common patterns in Jenkins plugins that can be automated.
2. **CLI tool**: Create a new CLI tool that can apply OpenRewrite recipes to Jenkins plugins.
3. **Recipes**: Create OpenRewrite recipes that can be used to modernize Jenkins plugins.
4. **Integration**: Integrate the new tool with the Jenkins plugin ecosystem.

=== Office hours

* (General) Official weekly Jenkins office hours: Thursdays 13:00 UTC
* (Project-based) Weekly project based office hours: Tuesdays 15:00 UTC (link:https://meet.google.com/oyq-tbpg-aaa[Direct link])

=== Links

* link:https://docs.openrewrite.org/recipes/jenkins/[OpenRewrite Jenkins recipes]
* link:https://docs.openrewrite.org/concepts-explanations/lossless-semantic-trees[OpenRewrite LST]
