---
title: Read only view
layout: developerguide
---

Extended read (and the up-coming system read) permission allow read only access
to parts of Jenkins.

The jelly taglib's in core will render a read only look and feel,
if the user only has access to read the view.

This is handled for developers transparently if they are already using one
of the supported views, like the `job` configure view.

== Enabling read-only view support

In the view file add:

[source,xml]
----
<j:choose>
    <j:when test="${app.hasPermission(it.CONFIGURE)}">
        <j:set var="readOnlyMode" value="false" />
    </j:when>
    <j:otherwise>
        <j:set var="readOnlyMode" value="true" />
    </j:otherwise>
</j:choose>
----

[source,groovy]
----
set("readOnlyMode", h.hasPermission(it.CONFIGURE) ? "false" : "true")
----

=== Partial view read-only

It's also possible to only use read-only mode for part of a view,

This is an example taken from the /configure page showing the 
`SYSTEM_READ` and `MANAGE` permissions working together, non-editable parts of the view
render in a read only manner:

[source,xml]
----
<j:forEach var="descriptor" items="${h.getSortedDescriptorsForGlobalConfigUnclassifiedReadable()}">
    <j:set var="editable" value="${h.getSortedDescriptorsForGlobalConfigUnclassified()}"/>
    <j:set var="readOnlyMode" value="${!editable.contains(descriptor)}" />
</j:forEach>
----

== Taglib changes required

If you provide your own taglib that isn't in Jenkins core you may need to make some changes.

Depending on what change is required there is a few different changes you might need to make,
here is a few examples.

Rendering plain text instead of a control, and adding a default text when it is empty:

[source,xml]
----
<j:choose>
    <j:when test="${readOnlyMode}">
        <j:choose>
            <j:when test="${empty(value)}">
                <span class="jenkins-not-applicable">N/A</span>
            </j:when>
            <j:otherwise><pre class="jenkins-readonly">${value}</pre></j:otherwise>
        </j:choose>
    </j:when>
    <j:otherwise>
    ... your normal default configuration
    </j:otherwise>
</j:choose>
----

Disabling the control, it is preferable to render plain text or some other
method that is obvious to the user what is going on (disabled controls aren't very obvious), but a lot of the javascript
and jelly taglibs depend on inputs of specific types being there for rendering,
so sometimes it is preferable to just disable the control:

[source,xml]
----
<input type="radio" 
    checked="${attrs.checked?'true':null}" 
    disabled="${readOnlyMode?'true':null}" 
/>
----

Removing controls from a page, like an X button on a repeatable element:

[source,xml]
----
<j:if test="${!readOnlyMode}">
    <f:block>
    <div align="right">
        <f:repeatableDeleteButton value="${attrs.deleteCaption}" />
    </div>
    </f:block>
</j:if>
----

== Compatibility with Jenkins core version

You do not need to worry about bumping your minimum required Jenkins core version
as this feature is driven by variables set in the jelly context,
old versions of Jenkins will just ignore it.

This was released in 2.TODO