---
title: Symbols
layout: developerguide
---

[.version]#Available since Jenkins 2.TODO.#

image::/images/developer/views/symbols.svg[Selection of Symbols]

[.text-right]
View the complete list of symbols available to use on link:https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols[GitHub]

{nbsp}

[.lead]
Jenkins Symbols are an extensive and consistent collection of icons for use in Jenkins and plugins.
Symbols are intended to be used everywhere a traditional icon would be used, such as in the sidebar,
in buttons and in tables. Symbols are scalable, support different weights and adapt to the user's theme.

{nbsp}

---

=== Using Symbols

Using symbols in your view is simple. Use the existing `icon` component and set the `src`
value to the symbol you want, prefixed with `"symbol-"`.

*Jelly example:*
[source, xml]
----
<l:icon src="symbol-search" />
----

*Groovy example:*
[source, groovy]
----
l.icon(src: 'symbol-search')
----

It's possible to add alt text and custom classes to symbols, for example:

*Jelly example:*
[source, xml]
----
<l:icon src="symbol-search" alt="Search" class="custom-class" />
----

*Groovy example:*
[source, groovy]
----
l.icon(src: 'symbol-search', alt: 'Search', class: 'custom-class')
----

---

=== Custom Symbols

pass:[<span class="version">Coming soon</span>]

As a plugin developer, you'll soon be able to add your own symbols for use in your plugin for when
there isn't an appropriate existing symbol to use.
