---
title: Symbols
layout: developerguide
---

image::/images/developer/views/symbols.svg[Selection of Symbols]
View the complete list of Symbols available to use in Jenkins link:https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols[here].

[.lead]
Jenkins Symbols are an extensive and consistent collection of icons that you can use on Jenkins or in your plugin.
Symbols are scalable, support different weights and also adapt to the user's theme.

---

=== Using Symbols

Using Symbols in your view is simple. Use the existing `icon` component and set the `src`
value to the symbol you want, prefixed with `"symbol-"`.

*Jelly example:*
[source, xml]
----
<l:icon src="symbol-search" />
----

*Groovy example:*
[source, groovy]
----
l.icon(src: 'symbol-search')
----

As Symbols build on top of the existing `icon` component you can use all the same attributes as
you could before, for example:

*Jelly example:*
[source, xml]
----
<l:icon src="symbol-search" alt="Search" class="custom-class" />
----

*Groovy example:*
[source, groovy]
----
l.icon(src: 'symbol-search', alt: 'Search', class: 'custom-class')
----

---

=== Custom Symbols (Coming soon)

As a plugin developer, you'll soon be able to add your own symbols for use in your plugin.

---

=== Licence

Jenkins Symbols are built from various sources:

* link:https://github.com/ionic-team/ionicons/blob/main/LICENSE[Ionicons v5]
* Contributions by developers
