---
title: Table to div layout migration
layout: developerguide
---

NOTE: This is a documentation for a new feature in the Jenkins core.
See jira:JENKINS-56109[Change Jenkins configuration UI from tables to divs] for details.

Jenkins core changed its form layout from 'table' to 'div' in 2.264.
The March 2021 LTS is expected to change its form layout from 'table' to 'div'.
The December 2020, January 2021, and February 2021 LTS releases will *not* change their form layout from 'table' to 'div'.

All core taglib's and views were updated in link:https://github.com/jenkinsci/jenkins/pull/3895[jenkins#3895]
as part of jira:JENKINS-56109[].

For 99% of plugins they do not require any changes at all as they just use the standard jelly tags
in Jenkins for their forms, such as `f:entry`, `f:textbox`, `f:checkbox`.

== Some plugins are known to be broken

If you're experiencing problems,
please check the link:https://issues.jenkins.io/secure/Dashboard.jspa?selectPageId=20741[list of known broken plugins dashboard].
If you're using any of these plugins, please disable them (or wait to upgrade) and upvote the issue.

If you're experiencing problems (form controls not working, the save button not working)
you can minimize your Jenkins installation to identify which plugin is the problem.

. If you're uncomfortable using your Jenkins, set up a minimal Jenkins

    JENKINS_HOST=username:password@myhost.com:port
    curl -sSL "http://$JENKINS_HOST/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins" | perl -pe 's/.*?<shortName>([\w-]+).*?<version>([^<]+)()(<\/\w+>)+/\1 \2\n/g'| sed 's/ /:/' | cut -d ':' -f 1 | sort > plugins.txt
    wget https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.2.0/jenkins-plugin-manager-2.2.0.jar
    wget https://get.jenkins.io/war/2.266/jenkins.war
    export JENKINS_HOME=~/.jenkins-tables-to-div
    java -jar jenkins-plugin-manager-2.2.0.jar -f plugins.txt -d $JENKINS_HOME/plugins --war jenkins.war
    java -jar jenkins.war

. Create a freestyle job to reproduce the issue
. Generally disable plugins (in groups of 10) -- recording which you've disabled
. Restart jenkins
. If you problem hasn't gone away, keep disabling
. Once the problem is resolved, enable plugins one at a time to identify the problematic plugin
. Report an issue with the label `tables-to-divs-regression`

== Examples of area which may require changes

Below are some areas that may require you to adjust the form layout or JavaScript in your plugin:

* Adding `td` / `tr` elements directly instead of using the `f:entry` tag, e.g. link:https://github.com/jenkinsci/config-rotator-plugin/pull/2[config-rotator-plugin#2]

* Custom JavaScript that is brittle to the Jenkins form UI layout. We’ve done our best to introduce shims, to not cause breakage here, 
but if you have written JavaScript that is reliant on the DOM structure you may need to make adjustments,
take a look at the JavaScript link:https://github.com/jenkinsci/jenkins/pull/3895[changes in jenkins#3895].

* Forking jelly taglibs from core and extending them, e.g. link:https://github.com/jenkinsci/multiple-scms-plugin/pull/25[multiple-scms-plugin#25],
it would be good to contribute fixes or enhancements to core rather than doing this where possible.

* Using tables in the plugin for layout, e.g. link:https://github.com/jfrog/jenkins-artifactory-plugin/pull/266[jenkins-artifactory-plugin#266] and link:https://github.com/jenkinsci/matrix-auth-plugin/pull/83[matrix-auth-plugin#83].


== Maintaining support for tables and div layout

There is a jelly property set on Jenkins instances that use div's for form layout called `divBasedFormLayout`,
so you can adapt your plugin UI based on the presence of this property.

_Note: This property is only set if the form tag uses the `f:form` jelly tag, and not the HTML `form` tag,
this will be done automatically for you in form sections but not in actions or custom views._

Jelly example:

[source,xml]
----
<j:jelly xmlns:j="jelly:core" xmlns:d="jelly:define" xmlns:local="local">
  <d:taglib uri="local">
    <d:tag name="blockWrapper">
          <j:choose>
              <j:when test="${divBasedFormLayout}">
                  <div>
                      <d:invokeBody/>
                  </div>
              </j:when>
              <j:otherwise>
                  <table style="width:100%">
                      <d:invokeBody/>
                  </table>
              </j:otherwise>
          </j:choose> 
      </d:tag>
  </d:taglib>

  <local:blockWrapper>
  ...
  </local:blockWrapper>
</j:jelly>
----

This will use a table on Jenkins instances that don't have `divBasedFormLayout` and will use a div when it is set.

_Note: You will likely need more tags to adapt the `tr` and `td` tags to divs see link:https://github.com/jenkinsci/multiple-scms-plugin/pull/25[multiple-scms-plugin#25] for a full example, or link:https://github.com/jenkinsci/notification-plugin/pull/40/files[notification-plugin#40] for an even more extensive example of different wrapper types (note they are shipped in separate files, included from the jelly files to edit with references like `xmlns:p="/lib/notification"` with a path part relative to `src/main/resources/` directory)._

Groovy example:

[source,groovy]
----
blockWrapper {
    p('Hello, World!')
}

def blockWrapper(Closure closure) {
    if (context.getVariableWithDefaultValue("divBasedFormLayout", "false") == "true") {
        div() {
            closure.call()
        }
    } else {
        table(style: "width: 100%") {
            closure.call()
        }
    }
}
----

== I still need more help?

Contact the link:/sigs/ux[UX sig] on link:https://gitter.im/jenkinsci/ux-sig[Gitter] or on the link:https://groups.google.com/forum/#!forum/jenkinsci-ux[mailing list].
