---
:layout: post
:title: Official Jenkins image to use from Docker Hub
:tags:
- docker
:author: batmat
---

There a now three different Docker Hub repositories that are or have been used as the "official" Jenkins image.
This article aims at providing a clarification about which one is the current official one (as of December 2018 :-)).

## The official one

[source]
----
docker pull jenkins/jenkins
---- 

is the right repository to use.

I also documented some time ago on my blog the link:https://batmat.net/2018/09/07/how-to-run-and-upgrade-jenkins-using-the-official-docker-image/[recommended way to run Jenkins using the official Docker image].

## The deprecated ones

link:https://hub.docker.com/_/jenkins/[`jenkins`]::
Deprecated since a long time already.
A short version of why we stopped using and updating this image is that we never had a way to get our images published without having each time to go through a manual process.
link:https://hub.docker.com/r/jenkinsci/jenkins[`jenkinsci/jenkins`]::
Deprecated since a long time too, but for easing transition, we had kept updating both `jenkins/jenkins` (the right one) and `jenkinsci/jenkins` together.
We stopped updating `jenkinsci/jenkins` in early December 2018 (cf. link:https://issues.jenkins-ci.org/browse/INFRA-1934[INFRA-1934] for details if you are interested)

Thanks for reading!
