---
layout: project
title: "Jenkins Configuration as Code"
section: projects
tags:
- jenkins-configuration-as-code
- jcasc
links:
  gitter: 'jenkinsci/configuration-as-code-plugin'



---

The ‘as code’ paradigm is about being able to reproduce and/or restore a full environment within minutes based on recipes and automation, managed as code.

== Manage configuration as human-readable config file(s)

Setting up Jenkins is a complex process, as both Jenkins and its plugins require some tuning and configuration,
with dozens of parameters to set within the web UI manage section.

Jenkins Configuration as Code allows to define this whole configuration as a simple, human-friendly, plain text yaml syntax. Without any manual step this configuration can be validated and applied to a Jenkins master in fully a reproducible way. With JCasC setting up a new Jenkins master will become a no-brainer event.

== Configure ALL jenkins initial setup

Fully working Jenkins master with:

* **no hands** on keyboard
* **no click** on UI

== Support most plugins without extra development effort

* No need to write glue code for every supported plugin
* Most plugins supported out of the box
* Others can bundle adapter code

== Getting started

* link:https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md[*Documentation and getting started*]
* You can ask questions about it on the regular Jenkins Developer mailling list (just prefix with [JCasC]).
* The link:https://github.com/jenkinsci/configuration-as-code-plugin[source code]
* Feature requests, bugs and so on are currently tracked via the github link:https://github.com/jenkinsci/configuration-as-code-plugin/issues[issue tracker]

