---
layout: project
title: "Jenkins Configuration as Code"
section: projects
tags:
- jenkins-configuration-as-code
- jcasc

---

The ‘as code’ paradigm is about being able to reproduce and/or restore a full environment within minutes based on recipes and automation, managed as code.

== Manage configuration as human-readable config file(s)

Experienced Jenkins users rely on groovy init scripts to customize jenkins and enforce desired state. Those scripts directly invoke Jenkins API and as such can do everything (at your own risk). But they also require you know Jenkins internals, and are confident in writing groovy scripts on top of Jenkins API.

Configuration-as-Code plugin has been designed as an opinionated way to configure jenkins based on human-readable declarative configuration files. Writing such a file should be feasible without being a Jenkins expert, just translating into code a configuration process one is used to executing in the web UI.

== Configure ALL jenkins initial setup 

Fully working Jenkins master with:
  
* **no hands** on keyboard
* **no click** on UI

== Support most plugins without extra development effort

* No need to write glue code for every supported plugin
* Most plugins supported out of the box
* Others can bundle adapter code

== Getting started

* link:https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/README.md[*Documentation and getting started*] 
* You can ask questions about it on the regular Jenkins Developer mailling list (just prefix with [JCasC]).
* The link:https://github.com/jenkinsci/configuration-as-code-plugin[source code]
* Feature requests, bugs and so on are currently tracked via the github link:https://github.com/jenkinsci/configuration-as-code-plugin/issues[issue tracker]

