---
layout: post
title: "Welcome Basil Crow - new Jenkins Governance Board member"
tags:
- community
- governance
- governance-board
authors:
- notmyfault
description: >
  Welcome, Basil Crow, to the Jenkins Governance Board!
opengraph:
  image: /images/governance/elections/2023/2023-governance-board-changes.svg
---

We would like to announce changes in the Jenkins Governance Board.
There has been no election this year, because there was only one candidate per seat.
Please welcome Basil Crow!
At the same time, Oleg Nenashev retires from the board. We would like to thank Oleg for his contributions to the Jenkins project and the community.
As a regular leader in GSoC, Jenkins Contributor Summits, and other community activities, Oleg has been a great fit for a governance board member.
Thank you Oleg!

In addition to Basil's inclusion in the Governance Board, our current officers will remain in their positions for another term.
Thanks to all of the officers for continuing their service:

* Release Officer - link:/blog/authors/timja[Tim Jacomb]
* Security Officer - link:/blog/authors/wadeck[Wadeck Follonier]
* Events Officer - link:/blog/authors/alyssat[Alyssa Tong]
* Infrastructure Officer - link:/blog/authors/dduportal[Damien Duportal]
* Documentation Officer - link:/blog/authors/kmartens27[Kevin Martens]

Basil will join other governance Board Members:
link:/blog/authors/kohsuke[Kohsuke Kawaguchi],
link:/blog/authors/notmyfault[Alexander Brandes],
link:/blog/authors/uhafner[Ullrich Hafner], and
link:/blog/authors/markewaite[Mark Waite].

Basil's term will last until December 2025.

== About Basil Crow

Here is Basil's statement from the elections:

_I have been a Jenkins user since 2012, a contributor since 2014, a
plugin maintainer since 2018, a core maintainer since 2021, and a
GitHub organization administrator since 2023. I look forward to
continuing to serve the Jenkins community in my new role as a board
member._

_My vision involves leading the design and implementation of
community-wide projects while also actively supporting the board in
executing the various administrative and operational tasks that are
needed to sustain the Jenkins project and community. The values of the
Jenkins community have always resonated with me, and I am eager to
continue championing them._

_As the Jenkins project nears its 19th birthday, it stands as a
testament to the resilience of open source communities. Much like
cities, these communities can be small yet vibrant, serving a critical
role to their constituencies. I look forward to ensuring that the
Jenkins project not only survives but thrives, providing sustained
value to its dedicated users and contributors for years to come._

== What's next for the Jenkins Governance Board?

In February we host a link:/blog/2023/11/10/Jenkins-Contributor-Summit-in-Brussels/[Jenkins Contributor Summit], the day before FOSDEM.
It is a day-long event featuring presentations on the "State of Jenkins", Project/SIG updates, discussion on various key projects, "Ignite Talks", and demos.

Don’t hesitate to reach out if you want to submit a presentation, talk, or demo!

== Participating in Jenkins Governance

link:/project/board/[Jenkins Governance Board] has just a representative function in the community.
The project and the community have a long history of open and inclusive governance driven by many contributors.
We invite all community members to participate in the project by joining the
link:/project/governance-meeting/[governance meeting],
participating in the link:/mailing-lists[mailing list] conversations,
and joining link:/sigs[special interest groups] driving particular topics.

Please refer to link:/participate[the participation page] to learn more about contributing to Jenkins in general.
