---
layout: post
title: "Jenkins GSoC 2022: The Return of Students as Mentors"
tags:
- gsoc
- gsoc2022
- community
- events
- developer
authors:
- alyssat
description: >
  This blogpost shares the experience of previous year GSoC students, returning as mentors.
---

Since 2005, the Google Summer of Code program has connected 18,000+ new open source contributors from 112 countries with 17,000+ mentors from 118 countries.
Google Summer of Code has produced over 40 million lines of code for 746 open source organizations.

The Jenkins project has been a mentoring organization for five years,
successfully mentored 27 GSoC students by ~80 mentors,
not to mention countless numbers of proposed and accepted project ideas.

=== The Need for More Project Ideas and Mentors
This year, the Jenkins project is gearing up to participate in the GSoC 2022.
Just like previous years, an integral element of this program consists of project ideas and mentors.
However, link:/projects/gsoc/2022/project-ideas/#ji-toolbar[Jenkins GSoC 2022 project ideas and mentors] are still on the dangerously light side.
We are in need of more project ideas and mentors.
Please see our link:/blog/2022/01/07/gsoc-2022/[previous post] for more details on project ideas and mentorship.

=== Meet our Returning Students, Now Mentors
This year, we are especially excited to have former GSoC students join the program as mentors.
The following GSoC students turned mentors include:

* link:https://github.com/rishabhBudhouliya[Rishabh Budhouliya]
* link:https://github.com/arpoch[Harshit Chopra]
* link:https://github.com/AbhyudayaSharma[Abhyudaya Sharma]
* link:https://github.com/krisstern[Kris Stern]
* link:https://github.com/stopalopa[Natasha Stopa]

We asked them to take us through how they came to decide to be GSoC mentors.

## What sort of role has mentoring played in your life?

Abhyudaya Sharma:: Mentoring has helped me improve my communication skills, meet new people, and learn things in more detail.
  I feel that by explaining something to someone, you are not only helping them learn, but you also improve your own understanding.

Kris Stern:: Mentoring has helped me in my work, especially when I need to collaborate with my colleagues.
  In a way the experience hones my soft skills, so that I have become a more effective communicator.

## What made you decide to be a GSoC mentor?

Abhyudaya Sharma:: GSoC is not just an opportunity for students to learn new technologies and improve their programming skills, it is much more than that.
  As a GSoC student in 2019, the feedback from the community members made me realize that even a single project can lead to a substantial improvement in the quality of life of its users.
  Hence, I'm back this year as a mentor to help the amazing Jenkins ecosystem become even better.

Kris Stern:: I have learned a lot from my previous mentors as well as mentoring community through participation in GSoC as a contributor in 2019 and 2020,
  and I would like to give back by becoming a mentor myself.

## What advice would you share with future GSoC participants?

Abhyudaya Sharma:: I wish I knew the importance of writing documentation when I started out as a GSoC student.
  Writing documentation for your code may seem like a chore at first but with time one realizes that a project is only as good as its documentation.
  I would recommend future GSoC students to make daily notes of their work and compile them so that they are useful for users and future developers.

Kris Stern:: I wish I knew as open-source contributors we do not always know everything, even for the more experienced ones who are in more senior roles in the open-source communities.

## What advice would you share with potential mentors?

Abhyudaya Sharma:: If you've always wanted a new feature or have something fixed, this is the perfect opportunity.
  Students will be working under your guidance for over three months and will have a chance to create something that would benefit not just you but the entire open-source community.
  Moreover, mentoring is an excellent opportunity to hone one's skills and meet new people from all around the world.

Kris Stern:: By taking part in mentoring a new cohort of GSoC contributors we are not just giving, but are learning and benefiting in the process as well.
  It may seem like we do not have all the necessary skills and knowledge to offer mentorship in a particular project at first,
  but this can be overcome,
  especially building on the strengths of our skills and knowledge gained from past GSoC projects as contributors ourselves.
