---
layout: post
title: "3 Cases: Jenkins success stories from the community"
tags:
- Jenkinsistheway
- Jenkinsuserstories
author: alyssat
description: "3 case studies highlighting how organizations implement Jenkins in the work place"
---

Back in April, when we started canvassing the Jenkins community for user stories concerning how Jenkins helped enterprise companies, startups, and students, we thought we'd see some exciting tales of DevOps inspiration and CI/CD integration. We found that some submitted stories were far too big to be constrained by our format of 'background/goal/solution/results.'

Some Jenkins users had a much more complex story to tell, whether it was about getting upper management to buy-in, keeping developers happy, or simply making sure pipelines weren't just bottlenecks in disguise. 

Here are a handful of link:https://stories.jenkins.io/case-studies/[Jenkins Case Studies] we've published in the past few months, with many more on the way!

== Case Study #1: D4Science

=== Amping up scientific research with CI/CD powered by Jenkins

To promote open science practices and support scientific communities while serving 11k registered users in 45 countries, link:https://www.d4science.org/[D4Science] introduced a new delivery pipeline that replaced their pre-existing build platform.

Of course, they had to build and release their software framework (gCube) in a way that would support multi-project releases at scale — from 200+ Git repositories within the same day! It had to be fast, automate all release activities, and it had to deliver incremental releases to address user requirements quickly. Most of all, the solution had to be cost-effective.

Using Jenkins, they created an innovative approach to software delivery: a continuous integration/continuous delivery (CI/CD) pipeline, scalable, easy to maintain, and upgradable at a minimal cost.  

Discover how D4Science empowers e-Science and virtual research communities with software released via Jenkins. link:https://stories.jenkins.io/case-studies/d4science-amps-up-their-scientific-research-platform-with-ci-cd-powered-by-jenkins/[Read the Jenkins case study featuring D4Science here!]

== Case Study #2: Gainsight

=== Humanizing CSX with tech innovation and a robust DevSecOps platform

link:https://www.gainsight.com/[Gainsight's] customer service experience platform helps customer success teams at more than 100 leading IT and healthcare clients. How? By driving engagement for tens of thousands of their customers. 

That's why the engineering team at Gainsight approached the customer experience by building a smarter, faster DevSecOps platform using Jenkins. They stuck to an infrastructure-as-code approach while integrating various tools and programming languages all within the platform. And they secured processes with better visibility and air-tight quality control.

The result was a flexible DevSecOps infrastructure, 95% of which is scalable with code. And the cost of infrastructure costs was 40% less. That provides Gainsight with ease of collaboration, keener operational insight, and — because builds are 30% faster — the ability to stay a step ahead of the competition.

Read why Gainsight's lead DevOps engineer, Prudviraj Pentakota, says "Jenkins is the epicenter of DevSecOps in our organization." link:https://stories.jenkins.io/case-studies/jenkins-case-study-gainsight/[Get the full story here.]

== Case Study #3: Avoris Travel

=== Reinventing travel with an inventive technology platform

Part of Barceló Group, link:https://www.avoristravel.com/[Ávoris Travel] is behind prominent destination travel brands like LeSki, Le Musik, and a selection of author travels under its "Viagens Com Assinatura" signature travel concept. A proprietary database and a smart, dynamic booking engine are the tickets to offering differentiating and inventive travel opportunities.

Also unique to Avoris is a discreet machining technology that enables agents to enter specific criteria to search and find all types of trips and travel opportunities across the entire network. 

"Our infrastructure is very important because we have to be online to meet customer demand anywhere in the world," said Alejandro Alvarez Vazquez, Sysadmin, Avoris Travel. "Our CI/CD platform is used by 200 people. The services that we build and deploy are used by thousands of potential clients and by our network of 675 own agencies located in Spain and Portugal." 

link:https://stories.jenkins.io/case-studies/jenkins-case-study-avoris-travel/[Read the case study] to learn how the flexibility of Jenkins plugins helped Avoris reduce build times by over 50% and became a go-to, scalable infrastructure supporting 675 agencies and over 2.8 million international consumers.

=== What’s your story?
We want to know what you're building with Jenkins and would love to post your case study on our link:https://stories.jenkins.io/["Jenkins Is The Way"] website, a global showcase of how developers and engineers build, deploy, and automate great stuff with Jenkins.

The best way to get started is to link:https://www.surveymonkey.com/r/JenkinsIsTheWay[share your Jenkins User story with us]. We'll send you a free Jenkins Is The Way T-Shirt in return and publish your account for the entire Jenkins community to see. And if it's selected for a Case Study, we'll be in touch for a one-on-one interview! Hope to hear from you soon! 
