lts:
  platforms:
    - value: Linux
      from: '1.0'
    - value: Windows
      from: '1.0'
  jdks:
    - value: '11'
      from: '2.164.1'
      to: '2.462.3'
    - value: '17'
      from: '2.346.1'
      to: '2.541.3'
    - value: '21'
      from: '2.426.1'
    - value: '25'
      from: '2.541.1'
