---
layout: post
title: "GSoC Project Intro: Simple pull request Plugin"
tags:
- gsoc2018
- plugin
author: abhishek_gautam
---

=== About me

I am Abhishek Gautam, 3rd year student from Visvesvaraya National Institute of technology, India, Nagpur.

As a person who is passionate is intrested in automation.

=== Project Summary
This plugin will be developed on the top of the MultiBranch Pipeline plugin.

.This plugin will follow below steps
* clone target repo
* checkout to target branch
* fetch the source branch
* merge source-branch
* call user call user script to build the repo.
* push to target branch [if specified by user in YAML]
* harvest results and reports and post to PR

Plugin will start above steps if and only if the pull request is will be
mergeable to avoid merge conflicts while merging the source branch to target
branch. The pull request is mergebale or not can also be decided by the webhook also.

https://github.com/jenkinsci/simple-pull-request-job-plugin/blob/master/README.md[How to run the demo]

=== Deliverables for Phase 1
1. User will be able to select to use Jenkinsfile.yaml for build.
2. Git Push step
3. harvest results and reports [and post in the PR]
 a. junit()
 b. findbugs()
 c. archiveArtifacts()
4. Basic interface to parse and get build specifications from YAML file.

=== Things decided
1. To build the plugin on the top of multibranch pipeline plugin.
2. Convert the YAML configuration to declarative pipeline for to run the build.
3. User will provide path to the script relative to the root directory of the repository
  without extension (.sh or .bat) in the YAML file. The plugin will generate pipeline script to detect the
  platform and call .sh or .bat script.

  Example:
    Path provided: ./scripts/hello
    a. On UNIX machine “./scripts/hello.sh” will be called
    b. On non-UNIX machine “./scripts/hello.bat” will be called.

=== Implementations till now
1. Git Push step: To push the changes of PR to the target branch.
2. Basic conversion of YAML to Declarative Pipeline.

=== References

* https://docs.google.com/document/d/1cuC0AvQG3e4GCjIoCwK3J0tcJVAz1eNDKV8d_zXxlO8/edit[Initial proposal of the project]
* https://github.com/jenkinsci/simple-pull-request-job-plugin[Project repository]
