---
layout: gsocprojectidea
title: "Plugin(s) for Electronic Design Automation tools"
goal: "Create a new Jenkins plugin for one of widely used EDA tools"
category: Plugins
year: 2019
status: published
sig: hw-and-eda
skills:
- Java
- EDA Tools
mentors:
- "martinda"
- "oleg_nenashev"
links:
  gitter: "jenkinsci_hw-and-eda-sig:gitter.im"
  draft: /projects/gsoc/2019/project-ideas/eda-plugins-draft.pdf
---

The idea is to create a Jenkins plugin for one of widely used EDA tools.
Both ASIC or FPGA design flow are acceptable, the tool should be proposed by the potential student.
Open-source EDA tools would be preferable (e.g. Yosys, FuseSoC, ArachnePnR, icetools), but we also consider
conditionally-free tools (like FPGA design EDAs).

Examples of tool integration:

* Tool launch and publishing steps for Free-style and/or Pipeline jobs
* Integration with Warnings Plugin for report parsing.
* Reporting of FPGA resource utilization (per build + trends)
* Timing report trend publishing
* Integrating UVM reports into Jenkins build and project pages

More details are available in the link:/projects/gsoc/2019/project-ideas/eda-plugins-draft.pdf[draft project idea].

== Special requirements

In the case of FPGA tools integration, a prototyping board will be required.
