---
layout: gsocprojectidea
title: "Role Strategy Plugin: user experience"
goal: "Improve UI and REST APIs using new technologies to make it more user-friendly"
category: Plugins
year: 2019
status: published
skills:
- Java
- JavaScript
- REST/GraphQL
mentors:
- "oleg_nenashev"
- "supun94"
- "runzexia"
links:
  gitter: "jenkinsci_role-strategy-plugin:gitter.im"
---

link:https://plugins.jenkins.io/role-strategy[Role Strategy Plugin] is widely used in Jenkins as an authorization engine,
but it has a pretty legacy Web UI which could be significantly improved.
The plugin's existing APIs are also very limited, and they could be redesigned.

Ideas:

* Redesign the WebUI using a new technology stack, e.g. React
* Introduce new REST APIs and CLIs to improve manageability of the plugin
* Introduce new logic to query permissions from Jenkins instances,
  probably as a part of the plugin:security-inspector[Security Inspector Plugin]
* Offer new features, e.g. the `sudo` mode for Jenkins administrators
* Create more demos for the plugin using Configuration-as-Code and other such technologies

You can find more UX-related requests for the plugin using link:https://issues.jenkins.io/issues/?jql=labels%20%3D%20user-experience%20and%20component%20%3D%20role-strategy-plugin%20and%20labels%20%3D%20gsoc-2019-project-idea%20[this JIRA query].
As a part of the project applications,
ideas for related plugins (e.g. plugin:security-inspector[Security Inspector] or plugin:ownership[Ownership]) may be also proposed.

==== Quickstart

1. Create a Jenkins instance with several projects and user roles defined by the plugin
** link:https://github.com/oleg-nenashev/demo-jenkins-config-as-code[oleg-nenashev/demo-jenkins-config-as-code]
can be used as an example of such configuration
2. Try out various configurations of Role Strategy and explore the features documented for the plugin
3. Provide feedback about your user experience in Gitter

==== Newbie-friendly tasks

See link:https://issues.jenkins.io/issues/?jql=component%20%3D%20role-strategy-plugin%20and%20labels%20%3D%20newbie-friendly%20[this JIRA query].
More issues can be added to the list if needed,
please do not hesitate to ask in the task.
