---
layout: project
title: "Infrastructure"
section: projects
tags:
- infra
- infrastructure
links:
  chat: "/chat/#jenkins-infra"
  mailinglist: "/mailing-lists/#infralists-jenkins-ci-org"
---

As an independent open source project, Jenkins maintains most of its own
infrastructure including services which help keep the project running.
The kinds of things that fall into "infrastructure" can span from operating
virtual machines and distribution networks, to project-specific applications
developed to make the development of Jenkins core and plugins more efficient.


== Overview

For the most part, the Jenkins project's infrastructure is managed and
orchestrated via our
link:https://github.com/jenkins-infra/jenkins-infra[Puppet repository].


== Applications

The Jenkins project operates a number of scripts and applications to further
the project's goals. Not all the scripts or applications are listed below, but
those that are listed are of sufficient scope/size to merit an overview.

=== Account app

link:https://github.com/jenkins-infra/account-app[On GitHub]

In order to provide centralized identity management across a variety of Jenkins
project services, we use LDAP. To provide some amount of self-service to
members of the project, the account app was created to allow users to log in
and edit some of their own properties in LDAP. The production instance of this
application can be found at:
link:https://accounts.jenkins.io[accounts.jenkins.io].

=== IRC Bot(s)

link:https://github.com/jenkins-infra/ircbot[On GitHub]

The primary Jenkins IRC Channel (`#jenkins` on the
link:http://freenode.net[Freenode]
network) uses an administrator bot "jenkins-admin" so that some of the project
operation work can be done by the community. This bot is available for anyone
in the channel with "voice", which is an IRC jargon for those users who are
trusted.

link:/projects/infrastructure/ircbot[Learn more about the IRC bot].


=== Jenkins

Naturally, the Jenkins project runs Jenkins itself for a variety of
build/test/release tasks, in addition to some periodic or batch tasks. The only
publicly visible Jenkins cluster can be found at
link:https://ci.jenkins.io[ci.jenkins.io]
whereas other clusters require escalated access and are not publicly available.


See also:

* link:https://github.com/jenkins-infra/documentation/blob/master/ci.adoc[Available nodes/tools/labels/etc]
* link:https://github.com/jenkinsci/puppet-jenkins[puppet-jenkins module]

=== Plugin site

link:https://github.com/jenkins-infra/plugin-site-api[On GitHub]

=== Rating app

link:https://github.com/jenkins-infra/rating[On GitHub]
