---
layout: documentation
title: Running Jenkins on Java 17
---

For simplicity, this document describes how to run the most recent version of Jenkins on Java 17.

NOTE: Production deployments should use only LTS versions of Jenkins.

== Running Jenkins with Docker

The easiest way to run Jenkins on Java 17 is with a Docker image.

To use the latest weekly release of the Java 17 images, use the `jdk17-preview` tag. For other releases, append the `-jdk17-preview` tag to the version (for example, `2.339-jdk17-preview`).

For example, this command starts Jenkins on Java 17 using the latest weekly release:

[source, shell]
----
docker pull jenkins/jenkins:jdk17-preview
docker run --rm -ti \
  -p 8080:8080 -p 50000:50000 \
  -v jenkins-home:/var/jenkins_home \
  jenkins/jenkins:jdk17-preview
----

== Running Jenkins with Java

As with Java 11, you can start Jenkins using the `java` command:

[source, shell]
----
java -jar jenkins.war --enable-future-java
----

== Discovering issues with Java 17

In March 2022, the community performed many exploratory tests to discover as many Java 17 issues as possible.

As a result, the community solved a lot of problems before announcing Java 17 support in Jenkins. However, it is still possible that some plugins have not been updated to support Java 17.

If you find a regression in a plugin, please file a bug report in Jira:

* link:https://issues.jenkins.io/browse/JENKINS-67908[Open Java 17 issues]

For security issues, please use the standard link:/security/#reporting-vulnerabilities[vulnerability reporting process].
