---
layout: documentation
title: Upgrading Jenkins Java version from 8 to 11
---

In order to upgrade the JVM used to run Jenkins, more specifically from Java 8 to Java 11, there are a few details and steps to take care.

First, we need to understand that some plugins were not directly compatible with Java 11. 
So if those plugins are installed in our instance, we need to make sure they are installed with those versions or more recent ones.

== Workflow Support 3.0 

One of the most important upgrades is the plugin:workflow-support[Workflow Support plugin].
We need to make sure that the version of the plugin is at least `3.0`.
Because this upgrade changes the serialization of the Pipeline builds, it requires that no Pipeline jobs are running when upgrading this plugin. 

Even if Pipeline jobs are supposed to survive a Jenkins restart, when the restart of the instance is due to a Pipeline related plugin, it is always a better option to make sure that no Pipeline builds are in progress before restarting the instance.
