---
:layout: post
:title: Meet-up and Hack alongside Kohsuke and Co.
:nodeid: 180
:created: 1268061300
:tags:
  - feedback
  - meetup
:author: rtyler
---
Ever wanted to pick the brains of *multiple* Hudson developers and users, all at the same time? Feel like finally meeting Kohsuke in person? Now's your chance!

We're hosting our https://wiki.jenkins.io/display/JENKINS/Hudson+Bay+Area+Hackathon+2.0[second-ever Bay Area Hudson Hackathon/Meetup] on *March 19th and 20th*. That's nearly _two_ whole days of Hudson!

=== Day One (Mar. 19)

The first day of the hackathon/meetup is aimed primarily at those working with Hudson's core, or are building on top of Hudson (plugins, etc).

* _Start:_ 10 a.m.
* _End:_   5 p.m.
* _Location:_ https://tinyurl.com/SunSantaClaraCampus[Oracle Santa Clara campus] in the "library" conference room of SCA7 "Mansion" building.

There will a number of community and corporate Hudson hackers joining us on Friday, so bring everything you'll need to get some grade A hacking done with Kohsuke, Andrew Bayer, Alan Harder and your fellow plugin hackers.

=== Day Two (Mar. 20)

I'm tentatively calling this the *main event*, which will be hosted at the delightful https://hackerdojo.pbworks.com[Hacker Dojo] in Mountain View. The "main event" will carry over the hackathon from the day before at Oracle, into a full blown community hackathon and meet-up. This is for Hudson *hackers and users* alike!

* _Start:_ 10 a.m.
* _End:_   6 p.m.
* _Location:_ https://hackerdojo.pbworks.com/[Hacker Dojo] (Savanna room)

As I've link:/content/hudson-pycon[pointed out before], Hudson's getting a lot of attention in other developer circles such as the Python, Ruby, Cocoa communities. As such, I'm hoping to get a lot of folks interested in using Hudson to come to Hacker Dojo where we (already being Hudson users) can help get them up to speed with all the great things Hudson can do.

'''

*If you're interested please RSVP:*

* Via the https://wiki.jenkins.io/display/JENKINS/Hudson+Bay+Area+Hackathon+2.0[hackathon page on the wiki]
* Via Facebook for https://www.facebook.com/event.php?eid=369652692847[day one] and https://www.facebook.com/event.php?eid=359578281880[day two]

'''

{blank} +

=== How you can help

While I casually refer to myself as a "PR intern" for https://twitter.com/kohsukekawa[Kohsuke], I'm technically a busy software engineer, meaning I'm grateful for all the help I can get.

[discrete]
===== Get the word out

The best way to help get the word out is to talk about Hudson and the meetup, this includes:

* Link to this post on Twitter
* Ping any user groups you are a member of in the area
* Blog about it
* Let your co-workers know about it
* Attend!

{blank} +

[discrete]
===== Volunteer to help setup/teardown

Hosting the Saturday event at Hacker Dojo does carry some responsibilities with it. We will need some extra hands to make sure everybody has power, refreshments are chilled, lunch is ordered and delivered, and of course, cleaning up after we leave. If you're in a generous mood, or in a real need for some karma, sign up to help on https://wiki.jenkins.io/display/JENKINS/Hudson+Bay+Area+Hackathon+2.0[the bottom of the wiki page]

I am hoping Oracle and some other heavy users/contributors will kick in a few bucks for lunch and drinks on Saturday, if you think your company can help us out, feel free to ping me directly at `tyler` at `linux.com`.

'''

// break
