---
:layout: post
:title: Hudson 1.349 Released
:nodeid: 181
:created: 1268049600
:tags:
  - development
  - feedback
  - just for fun
  - links
:author: rtyler
---
Last Friday, March 5th, Hudson 1.349 was pushed out into the wild with an even split of bug fixes and enhancements. Included in this release is Alan Harder's (a.k.a `mindless`) old data monitor code, discussed previously in the post "link:/content/call-testers-older-better[Call for Testers: The older the better]." Included in this release were further updates to the japanese and german localizations of Hudson; if you're interested in helping localize Hudson into more languages you can join the effort via the https://wiki.jenkins.io/display/JENKINS/Internationalization[Internationalization page on the wiki].

Now for the breakdown of the 1.349 release:

=== Bug fixes

* Fix deserialization problem with fields containing double underscore. (https://issues.jenkins.io/browse/JENKINS-5768[issue 5768])
* Fix deserialization problem for Exception objects where the XML has bad/old data. (https://issues.jenkins.io/browse/JENKINS-5769[issue 5769])
* Fix serialization problem with empty CopyOnWriteMap.Tree. (https://issues.jenkins.io/browse/JENKINS-5776[issue 5776])
* Fixed a bug that can cause 404 in the form validation check.

{blank} +

=== Enhancements

* Remote build result submission shouldn't hang forever even if Hudson goes down.
* Added a monitor for old or unreadable data in XML files and a manage screen to assist in updating files to the current data format and/or removing unreadable data from plugins that are no longer active. "Manage Hudson" page will show a link if any old/unreadable data was detected.
* Added a mechanism to bundle +++<tt>+++init.groovy+++</tt>+++ inside the war for OEM. (https://n4.nabble.com/preconfigured-hudson-war-tp1575216p1575216.html[report])
* Added an extension point to annotate console output. (https://issues.jenkins.io/browse/JENKINS-2137[issue 2137])</ul>

{blank} +

=== Contributors

Hudson 1.349 contains *43* commits from 6 contributors, due to the merging in of Alan Harder's old-data-monitor branch the commit count is a bit off from the amount of code change that actually went out in 1.349.

* https://twitter.com/abayer[abayer]
* https://twitter.com/kohsukekawa[kohsuke]
* https://blogs.sun.com/mindless[mindless]
* https://twitter.com/ssogabe[sogabe]
* swiest
* https://twitter.com/wyukawa[wyukawa]

{blank} +
As usual, you can go grab the http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest .war file] straight from `hudson-ci.org` or if you're using a native package, use your package manager to upgrade.

'''

// break
