---
:layout: post
:title: Hudson 1.346 Released
:nodeid: 201
:created: 1266246000
:tags:
  - development
  - feedback
  - just for fun
  - links
:author: rtyler
---
After some scrambling earlier in the week to get link:/blog/2010/02/08/breaking-hudson-1-345-released/[1.345 out the door], correcting some regressions in 1.344, the Hudson team still rolled out a 1.346 release last Friday, February 12th, 2010. Similar to the past couple releases, 1.346 had a good number of bug fixes, including a a performance fix when dealing with larger build submissions and a substantial revision of the SCM polling code to fix a long-standing issue with the quiet period blocking the build from running (https://issues.jenkins.io/browse/JENKINS-2180[issue 2180]), there were also some additionally memory improvements made to https://en.wikipedia.org/wiki/Apache%20Jelly[Jelly], the library with which the majority of Hudson's web interface is rendered, that Kohsuke will detail in a later post.

Here's the breakdown:

=== Bugs fixed

* Maven modules should not be buildable when the parent project is disabled. (https://issues.jenkins.io/browse/JENKINS-1375[issue 1375])
* Fixed the broken quiet period implementation when polling interval is shorter than the quiet period. (Changes in SCM impls are needed for this to take effect.) (https://issues.jenkins.io/browse/JENKINS-2180[issue 2180])
* Escape username in URLs in case it contains special characters such as "#". (https://issues.jenkins.io/browse/JENKINS-2610[issue 2610])
* Fix sidepanel link for People to be visible and show view-specific info when appropriate. (https://issues.jenkins.io/browse/JENKINS-5443[issue 5443])
* Improved HTML rendering, not using closing tags that do not exist in HTML. (https://issues.jenkins.io/browse/JENKINS-5458[issue 5458])
* Show better error message for missing view type selection when creating a view. (https://issues.jenkins.io/browse/JENKINS-5469[issue 5469])
* Hudson wasn't properly streaming a large external build submission, which can result in OOME and unresponsiveness. </ul> +
### Enhancements
 ** Use fixed-width font in text area for shell/batch build steps. (https://issues.jenkins.io/browse/JENKINS-5471[issue 5471])
 ** Use user selected icon size on People page. (https://issues.jenkins.io/browse/JENKINS-5447[issue 5447])
 ** Speed/footprint improvement in the HTML rendering.

+
+
### Contributors This release of Hudson contained 37 commits from 3 different contributors to "core": * https://twitter.com/kohsukekawa[kohsuke] * https://blogs.sun.com/mindless[mindless] * https://twitter.com/ssogabe[sogabe] +
As usual, you can go grab the [latest .war file](http://mirrors.jenkins.io/war-stable/latest/jenkins.war) straight from `hudson-ci.org` or if you're using a native package, use your package manager to upgrade. ---- **Updated:** Added the "official" changelog notes
+
// break
