---
:layout: post
:title: Hudson 1.344 Released
:nodeid: 150
:created: 1265652000
:tags:
  - development
  - feedback
  - just for fun
  - links
:author: rtyler
---
The latest release of Hudson, 1.344, was released on February 5th, 2010. The release contains primarily bug-fixes but has a few enhancements baked into it as well. As mentioned in "link:/content/incoming-more-translations[[Incoming! More Translations]", 1.344 incorporates a number of community-driven translations (see the other post for more information). Additionally, 1.344 removes the "easter egg" background image I wrote about in a post to my personal blog: http://unethicalblogger.com/posts/2010/01/mourning_sun[Mourning Sun] Enough of the small talk, here's the breakdown.

== Bugs fixed

* Removed the forced upper casing in parameterized builds. (https://issue-redirect.jenkins.io/issue/5391[issue 5391])
* Password parameter on the disk should be encrypted. (https://issue-redirect.jenkins.io/issue/5420[issue 5420])
* Duplicate entries on Upstream/Downstream project with "Build modules in parallel". (https://issue-redirect.jenkins.io/issue/5293[issue 5293])
* "Projects tied on" should be "Projects tied to". (https://issue-redirect.jenkins.io/issue/5451[issue 5451])
* Fixed the bug that prevents update center metadata retrieval in Jetty. (https://issue-redirect.jenkins.io/issue/5210[issue 5210])

== Enhancements

* Show which plugins have already been upgraded in Plugin Manager. (https://issue-redirect.jenkins.io/issue/2313[issue 2313])
* Show Hudson upgrade status on manage page instead of offering same upgrade again. (https://issue-redirect.jenkins.io/issue/3055[issue 3055])
* Make badges in build history line up. (https://web.archive.org/web/20100524080401/https://hudson.361315.n4.nabble.com/Align-lock-sign-of-keep-build-forever-td1016427.html[report])

== Contributors

This release of Hudson contained 44 commits from 5 different contributors to "core":

* https://twitter.com/abayer[abayer]
* https://twitter.com/kohsukekawa[kohsuke]
* https://blogs.sun.com/mindless[mindless]
* https://twitter.com/ssogabe[sogabe]
* https://www.linkedin.com/in/thuybrechts[huybrechts]

As usual, you can go grab the http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest .war file] straight from `hudson-ci.org` or if you're using a native package, use your package manager to upgrade.

'''''

*Update:* This post was written a day before https://issue-redirect.jenkins.io/issue/5536[issue 5536] was discovered. I recommend waiting until 1.345 to update any production Hudson instances.
