---
:layout: post
:title: Hudson 1.347 Released
:nodeid: 196
:created: 1266849000
:tags:
  - development
  - feedback
  - just for fun
  - links
:author: rtyler
---
The release of Hudson 1.347 last friday, February 19th, was a relatively "minor" one insofar that it contained an assortment of smaller fixes instead of fixes to major regressions (they weren't any to be fixed) or major features added. There were however some notable commits in this release cycle that didn't make the changelog just yet, for example https://twitter.com/_godin_[godin] committed an https://en.wikipedia.org/wiki/Ebuild[ebuild] which will allow for a native package of Hudson for https://en.wikipedia.org/wiki/Gentoo%20Linux[Gentoo Linux], joining the ranks of the existing packages for Debian/Ubuntu, FreeBSD, OpenSolaris, openSUSE and RedHat/Fedora Linux. The bundled Subversion plugin was updated and thanks to https://twitter.com/ssogabe[sogabe] and https://twitter.com/wyukawa[wyukawa] the Japanese translations for Hudson got some updates as well.

For Hudson developers, both plugin and core, this release contains some notable changes from https://blogs.sun.com/mindless[mindless] (a.k.a Alan Harder), a number of calls which have been deprecated for over *two years* have finally been pruned from the code base:

* `Hudson.addListener(JobListener)`, `Hudson.removeListener(JobListener)`
* Entire `listeners.JobListener` class (replaced by `ItemListener`)
* One form of `DirectoryBrowser` constructor
* One form of `Descriptor.configure()` (with `HttpServletRequest` param)
* `Descriptor.convert(Map)` and 4 implementations of this method, and code calling it in `Descriptor.readResolve()` (this code called `save()` whenever updating data, so there should be no remaining cases out there)

Alan's quest for removing deprecated code will likely continue for a while, but this is a good step in the right direction, keeping Hudson's internals in good working order. Worth mentioning, the influx of plugin releases in the link:/content/week-plugins-0[This Week in Plugins] from a couple weeks ago, was driven largely by Alan, rummaging through the code of older plugins, updating plugins left and right.
// break
Now the breakdown for this release:

=== Bugs fixed

* Fix javascript problem showing test failure detail for test name with a quote character. (https://issue-redirect.jenkins.io/issue/1544[issue 1544])
* Hudson can incorrectly configure labels for the controller when bleeding edge EC2 plugin is used.
* Fixed the regression wrt the whitespace trimming caused by 1.346. (https://issue-redirect.jenkins.io/issue/5633[issue 5633])
* Under some circumstances, Hudson can incorrectly delete the temporary directory itself. (https://issue-redirect.jenkins.io/issue/5642[issue 5642])
* Newlines in MAVEN_OPTS environment variable can cause problems in other contexts. (https://issue-redirect.jenkins.io/issue/5651[issue 5651])

{blank} +

=== Enhancements

* Improved the form validation mechanism to support multiple controls. (https://issue-redirect.jenkins.io/issue/5610[issue 5610])
* Added message to agent log when it has successfully come online. (https://issue-redirect.jenkins.io/issue/5630[issue 5630])

{blank} +

=== Contributors

This release of Hudson contained 36 commits from *7* different contributors to "core":

* https://twitter.com/abayer[abayer]
* https://twitter.com/_godin_[godin]
* https://www.linkedin.com/in/thuybrechts[huybrechts]
* https://twitter.com/kohsukekawa[kohsuke]
* https://blogs.sun.com/mindless[mindless]
* https://twitter.com/ssogabe[sogabe]
* https://twitter.com/wyukawa[wyukawa]

{blank} +
As usual, you can go grab the http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest .war file] straight from `hudson-ci.org` or if you're using a native package, use your package manager to upgrade.
