---
title: Managing plugin dependencies
layout: developerguide
---

Jenkins has a complex, modular architecture.
To enable plugins to use the rich array of libraries available in the Java ecosystem,
and build on one another using plugin-to-plugin APIs,
the Jenkins plugin extension mechanism goes beyond simple plugin manifests.

The de facto build tool for Jenkins plugins is Apache Maven.
All examples here will use Maven.
Building plugins using Gradle is also possible but particular capabilities may lag behind.

## Using the 2.x parent POM

TODO mention archetype

## The plugin class loader hierarchy

TODO gentle overview of the distinction between “initiating” and “defining” loader

### +Messages+, views, and other resources

TODO

## Depending on other plugins

TODO

## Bundling third-party libraries

TODO

### Using library wrapper plugins

TODO

### +pluginFirstClassLoader+ and its discontents

TODO

### Checking +WEB-INF/lib/*.jar+ for junk

TODO

## Understanding +requireUpperBoundDeps+ failures and fixes

TODO

### Transitive dependency plugin too old

TODO Jenkins 2.12+ also checks this during +InjectedTest+, but more slowly

### Improper attempt to use core component

TODO

### Test-scoped dependency mismatch

TODO

### Picking up fixes to dependency plugins

TODO

### Suppressing violations

TODO

### Shading libraries

TODO

## Jenkins modules

TODO

## +JenkinsRule+ vs. +acceptance-test-harness+ testing

TODO

## Overridable core components

TODO

[source,xml]
----
<TODO/>
----
