#!/usr/bin/env bash

mkdir -p build
./scripts/node npx antora $@ 2> build/antora-error.txt || {
    cat build/antora-error.txt >&2
    exit 1
}
if [[ -n "$( grep '\(ERROR\|WARNING\)' build/antora-error.txt )" ]] ; then
    echo "Failing build due to warnings/errors in log output:" >&2
    sort -u build/antora-error.txt >&2
    exit 1
fi
