#!/usr/bin/env bash

mkdir -p build
./scripts/ruby bundle exec asciidoctor-pdf $@ 2> build/error.txt || {
    cat build/error.txt >&2
    exit 1
}
if [[ -n "$( grep --fixed-strings WARNING build/error.txt | grep --fixed-strings --invert-match user-handbook.adoc | grep --fixed-strings --invert-match 'conversion missing in backend pdf' )" ]] ; then
    echo "Failing build due to warnings in log output:" >&2
    cat build/error.txt >&2
    exit 1
fi
