#!/usr/bin/env bash

if [[ "$1" = "--dev" ]] ; then
    ./scripts/ruby bundle exec awestruct $@
else
    mkdir -p build
    ./scripts/ruby bundle exec awestruct $@ 2> build/error.txt || {
        cat build/error.txt >&2
        exit 1
    }
    if [[ -n "$( grep --fixed-strings WARNING build/error.txt )" ]] ; then
        echo "Failing build due to warnings in log output:" >&2
        cat build/error.txt >&2
        exit 1
    fi
fi

