#!/bin/sh
#
# This script is meant to be added to the PATH so the latest blobxfer is
# always ready to use

set +x

CONTAINER_NAME=alfpark/blobxfer:1.0.0b2

pull_container() {
    docker pull ${CONTAINER_NAME}
}

# Pull down the container if we don't already have it
docker inspect ${CONTAINER_NAME} > /dev/null 2>&1
if [ $? -ne 0 ]; then
    pull_container
fi;

exec docker run \
    --rm \
    -t \
    -u "$(id -u):$(id -u)" \
    -v "$(pwd)/build:/data" \
    "${CONTAINER_NAME}" "${@}"
