#!/usr/bin/env bash

SITE_COPY=build/checklinks
rm -rf $SITE_COPY
cp -r build/_site $SITE_COPY
for REDIRECT in zh survey jep/210
do
  mkdir -p $SITE_COPY/$REDIRECT
  echo "foo" > $SITE_COPY/$REDIRECT/index.html
done
find $SITE_COPY -type f -exec sed -i -e 's/https:\/\/jenkins.io/http:\/\/localhost:8888/g' {} \;
scripts/node npm run check-broken-links

