#!/usr/bin/env bash

# Report adoc files that use https://www.jenkins.io or https://jenkins.io

# Site development depends on links being relative to the current site
# so that we can show the site on a developer desktop or in the preview
# sites without links that jump to the original site.

# See https://github.com/jenkins-infra/jenkins.io/issues/5718
# See also https://github.com/jenkins-infra/jenkins.io/pull/5715

# Returns 0 if no issues are detected or script is running on trusted.ci.jenkins.io
# Returns 1 if one or more adoc files include https://www.jenkins.io
# Returns 2 if one or more adoc files include https://jenkins.io
# Returns 3 if both https://www.jenkins.io and https://jenkins.io are found

return_code=0

files=$(git grep -l https://www.jenkins.io -- content/[a-zA-Z]**/*.adoc)
if [ "$files" != "" ]; then
        echo "ERROR: incorrectly used https://www.jenkins.io in ${files}"
        echo
        echo "See https://github.com/jenkins-infra/jenkins.io/issues/5718"
        echo "See also https://github.com/jenkins-infra/jenkins.io/pull/5715"
        echo
        return_code=1
fi

files=$(git grep -l https://jenkins.io -- content/[a-zA-Z]**/*.adoc)
if [ "$files" != "" ]; then
        echo "ERROR: incorrectly used https://jenkins.io in ${files}"
        echo
        echo "See https://github.com/jenkins-infra/jenkins.io/issues/5718"
        echo "See also https://github.com/jenkins-infra/jenkins.io/pull/5715"
        echo
        return_code=$(( return_code + 2 ))
fi

exit $return_code
