#!/usr/bin/env bash


# https://github.com/jenkins-infra/jenkins.io/pull/1129
if [[ "$(docker version -f {{.Server.Version}})" =~ ^1[7-9]\. ]]; then
    DELEGATED=:delegated
fi

# When using SELinux, bind mounted Docker volumes need the ":Z" option
# https://github.com/jenkinsci/acceptance-test-harness/pull/2032 has more details
if [ -x /usr/bin/sestatus ]; then
    if /usr/bin/sestatus | grep -q 'status:.*enabled'; then
        DELEGATED=:Z
    fi
fi

# allow scripts to be passed special argument that triggers a docker pull
# without this images can get stale and out of sync from CI system
if [ "$1" = "pull" ]; then
    exec docker pull "${CONTAINER_NAME}"
    exit $?
fi
