#!/bin/sh -x

WORKDIR=$(dirname $0)/../content/_tmp/examples
REPODIR=${WORKDIR}/pipeline-examples
REPO=https://github.com/jenkinsci/pipeline-examples.git

echo ">> Working in ${WORKDIR}"

if [ ! -d "${WORKDIR}" ]; then
    mkdir -p ${WORKDIR}
fi

if [ ! -d "${REPODIR}" ]; then
    (cd $WORKDIR && git clone $REPO)
else
    (cd $REPODIR && git pull --rebase)
fi
