#!/usr/bin/env bash

source ./scripts/docker-env

exec docker run --rm \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    groovy:jre-alpine $@
