#!/usr/bin/env bash

# TODO detect $(docker version --format '{{.Server.Version}}') is 17.06+ and add :delegated to -v (ditto in node & ruby)

exec docker run --rm  \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -v "${PWD}":"${PWD}" \
    -w "${PWD}" \
    groovy:jre-alpine $@
