#!/usr/bin/env bash

CONTAINER_NAME=groovy:jre-alpine
source ./scripts/docker-env

exec docker run --rm \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    "${CONTAINER_NAME}" $@
