#!/usr/bin/env bash

CONTAINER_NAME=node:alpine
source ./scripts/docker-env

exec docker run --rm \
    -u $(id -u):$(id -g) \
    -e HOME="${PWD}" \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    "${CONTAINER_NAME}" $@
