#!/usr/bin/env bash

VERSION=15.11

if command -v node &> /dev/null; then
    # going to assume some version of ruby is installed for this comparison
    if [ $(ruby -e "puts Gem::Version.new('$(node -v | cut -c2- )') >= Gem::Version.new('$VERSION')") == "true" ]; then
        exec node "$@"
    fi
fi
CONTAINER_NAME=node:${VERSION}-alpine
source ./scripts/docker-env

exec docker run --rm \
    -u $(id -u):$(id -g) \
    -e HOME="${PWD}" \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    "${CONTAINER_NAME}" "$@"
