#!/usr/bin/env bash

if [ -n "${USE_LOCAL_RUBY}" ]; then
    if [ "$1" = "pull" ]; then
        exit 0
    fi

    exec $@

    exit
fi

CONTAINER_NAME=ruby:3.3.6
source ./scripts/docker-env

if [ ! -z ${LISTEN+x} ]; then
    ADDITIONAL_ARGS="-p 4242:4242"
fi;

exec docker run --rm \
    ${ADDITIONAL_ARGS} \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -e HOME="${PWD}" \
    -e  GEM_HOME="${PWD}/vendor/gems" \
    -e  BUNDLE_PATH="${PWD}/vendor/gems" \
    -e  BUNDLE_APP_CONFIG="${PWD}/vendor/gems/.bundle" \
    -e  BUNDLE_DISABLE_SHARED_GEMS=true \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    "${CONTAINER_NAME}" $@
