#!/usr/bin/env bash

if [ -n "${USE_LOCAL_RUBY}" ]; then
    if [ "$1" = "pull" ]; then
        exit 0
    fi

    exec $@

    exit
fi

# TODO: track with 'updatecli' from https://github.com/jenkins-infra/packer-images/blob/2.20.0/provisioning/tools-versions.yml#L42
# with the same technique as https://github.com/jenkins-infra/jenkins-infra/blob/8cd6e81d4f2f6a2df46809917298ff676f4dbefa/updatecli/weekly.d/jenkinscontroller-tools-maven.yaml#L16-L32
CONTAINER_NAME=ruby:3.4.7
source ./scripts/docker-env

if [ ! -z ${LISTEN+x} ]; then
    ADDITIONAL_ARGS="-p 4242:4242"
fi;

exec docker run --rm \
    ${ADDITIONAL_ARGS} \
    -u $(id -u):$(id -g) \
    -e LANG=C.UTF-8 \
    -e HOME="${PWD}" \
    -e  GEM_HOME="${PWD}/vendor/gems" \
    -e  BUNDLE_PATH="${PWD}/vendor/gems" \
    -e  BUNDLE_APP_CONFIG="${PWD}/vendor/gems/.bundle" \
    -e  BUNDLE_DISABLE_SHARED_GEMS=true \
    -v "${PWD}":"${PWD}"${DELEGATED} \
    -w "${PWD}" \
    "${CONTAINER_NAME}" $@
