---
layout: documentation
section: doc
---
ifdef::backend-html5[]
:doctitle: Architecting for Manageability
:notitle:
:description:
:author: R. Tyler Croy
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc:
endif::[]

== Architecting for Manageability

=== Introduction

With over 1,000 plugins and countless versions of said plugins in the
open-source community, testing for all possible conflicts before upgrading one
or more production Jenkins instances is simply not feasible. While Jenkins
itself will warn of potential incompatibility if it detects that a plugin
requires a newer version of the Jenkins core, there is no automatic way to
detect conflicts between plugins or to automatically quantifying the impact of
upgrading a plugin before doing the upgrade.

Instead, Jenkins administrators should be made responsible for manually testing
their own instance's plugin and core version updates before performing them on
the production instance. This kind of testing requires a copy or "test
instance" of the production server to act as the sandbox for such tests and can
prevent production master downtime.

=== Test Instances

A test master is a Jenkins master used solely for testing configurations and
plugins in a non-production environment. For organizations with a
mission-critical Jenkins instance, having a test master is highly recommended.

Upgrading or downgrading either the Jenkins core or any plugins can sometimes
have the unintended side effect of crippling another plugin's functionality or
even crashing a master. As of today, there is no better way to pre-test for
such catastrophic conflicts than with a test master.

Test masters should have identical configurations, jobs, and plugins as the
production master so that test upgrades  will most closely resemble the
outcomes of a similar change on your production master. For example, installing
the Folders plugin while running a version of the Jenkins core older than
1.554.1 will cause the instance crash and be inaccessible until the plugin is
manually uninstalled from the _plugin_ folder.

==== Setting up a test instance

There are many methods for setting up a test instance, but the commonality
between them all is that the _$JENKINS_HOME_ between them is nearly identical.
Whether this means that most all of the production masters' _$JENKINS_HOME_
folder is version controlled in a service like GitHub and mounted manually or
programmatically to a test server or Docker container, the result is nearly the
same.

It is ideal to first ensure sure the master is idle (no running or queued jobs)
before attempting to create a test master.

*With GitHub + manual commands*

You will simply need to open up your command-line interface and "cd" to the
folder that contains the _$JENKINS_HOME_ directory for your production master
and run the "git init" command. For the location of this folder, please refer
to section 3.

It is recommended that before running the "git add" command that you create a
good _.gitignore_ file. This file will prevent you from accidentally
version-controlling a file that is too large to be stored in GitHub (anything
>50 MB).

Here is an example _.gitignore_ file for a Jenkins master running on OS X:

[source]
----
.DS_Store
.AppleDouble
.LSOverride
Icon
._*
.Spotlight-V100
.Trashes
.AppleDB
.AppleDesktop
Network Trash Folder
Temporary Items
.apdisk
*.log
*.tmp
*.old
*.jar
*.son
.Xauthority
.bash_history
.bash_profile
.fontconfig
.gitconfig
.gem
.lesshst
.mysql_history
.owner
.ri
.rvm
.ssh
.viminfo
.vnc
bin/
tools/
**/.owner
**/queue.xml
**/fingerprints/
**/shelvedProjects/
**/updates/
**/jobs/*/workspace/
**/war/
/tools/
**/custom_deps/
**/slave/workspace/
**/slave-slave.log.*
cache/
fingerprints/
**/wars/jenkins*.war
*.log
*.zip
*.rrd
*.gz
----

Once you have a good _.gitignore_ file, you can run the follow git commands to
commit your _$JENKINS_HOME_ to a git repository like GitHub:

[source,bash]
----
git add -—all
git commit -m "first commit"
git push
----

Now you can install Jenkins to a fresh instance and "git clone" this
_$JENKINS_HOME_ from the git repository to your new instance. You will need to
replace the files in the new instance with your version-controlled files to
complete the migration, whether through scripts or through a drag-and-drop
process.

Once this is done, you will need to restart the new test master's Jenkins
service or reload its configuration from the Jenkins UI ("Manage Jenkins" >>
"Reload Configuration").

*With GitHub + Docker (Linux-only)*

When it comes to version controlling your $JENKINS_HOME, just follow the
instructions in the previous section.

The next step will be to create a Docker image with identical configurations to
your production instance's - operating system (Linux-only), installed
libraries/tools, and open ports. This can be accomplished through Dockerfiles.

You will then just need to create mounted storage on your Docker server with a
clone of your version-controlled _$JENKINS_HOME_ home and a simple image to
clone the _$JENKINS_HOME_ into.

For example, we can create a Docker image called _jenkins-storage_ and version
control our _$JENKINS_HOME_ in a Github repository known as "demo-joc". The
"jenkins-storage" Docker image can be built from a Dockerfile similar to this:

[source,bash]
----
FROM debian:jessie
RUN apt-get update && apt-get -y upgrade
RUN apt-get install -y --no-install-recommends \
    openjdk-7-jdk \
    openssh-server \
    curl \
    ntp \
    ntpdate  \
    git  \
    maven  \
    less  \
    vim
RUN printf "AddressFamily inet" >> /etc/ssh/ssh_config
ENV MAVEN_HOME /usr/bin/mvn
ENV GIT_HOME /usr/bin/git
# Install Docker client
RUN curl https://get.docker.io/builds/Linux/x86_64/docker-latest -o /usr/local/bin/docker
RUN chmod +x /usr/local/bin/docker
RUN groupadd docker
# Create Jenkins user
RUN useradd jenkins -d /home/jenkins
RUN echo "jenkins:jenkins" | chpasswd
RUN usermod -a -G docker jenkins
# Make directories for [masters] JENKINS_HOME, jenkins.war lib and [slaves] remote FS root, ssh privilege separation directory
RUN mkdir /usr/lib/jenkins /var/lib/jenkins /home/jenkins /var/run/sshd
# Set permissions
RUN chown -R jenkins:jenkins /usr/lib/jenkins /var/lib/jenkins /home/jenkins
#create data folder for cloning
RUN ["mkdir", "/data"]
RUN ["chown", "-R", "jenkins:jenkins", "/data"]
USER jenkins
VOLUME ["/data"]
WORKDIR /data
# USER jenkins
CMD ["git", "clone", "https://github.com/[your-github-id]/docker-jenkins-storage.git", "."]
----

Creating mounted storage for containers would just require something similar to
the following command:

[source,bash]
----
docker run --name storage [your-dockerhub-id]/jenkins-storage git clone https://github.com/[your-github-id]/docker-jenkins-storage.git .
----

And Jenkins images that rely on the mounted storage for their _$JENKNIS_HOME_
will then need to point to the mounted volume:

[source,bash]
----
docker run -d --dns=172.17.42.1 --name joc-1 --volumes-from storage -e JENKINS_HOME=/data/var/lib/jenkins/jenkins [your-dockerhub-id]/jenkins --prefix=""
----

.Test master slaves

Test masters can be connected to test slaves, but this will require further
configurations. Depending on your implementation of a test instance, you will
either need to create a Jenkins Docker slave image or a slave VM. Of course,
open-source plugins like the EC2 plugin also the option of spinning up new
slaves on-demand.

The slave connection information will also need to be edited in the config.xml
located in your test master's _$JENKINS_HOME_.

.Rolling back plugins that cause failures

If you discover that a plugin update is causing conflict within the test
master, you can rollback in several ways:

* For bad plugins, you can rollback the plugin from the UI by going to the
  plugin manager ("Manage Jenkins" >> "Manage Plugins") and going to the
  "Available" tab. Jenkins will show a "downgrade" button next to any plugins
  that can be downgraded.

* If the UI is unavailable, then enter your _$JENKINS_HOME_ folder and go to
  the plugins folder. From there, delete the .hpi or .jpi file for the
  offending plugin, then restart Jenkins. If you need to rollback to an older
  version, you will need to manually copy in an older version of that .jpi or
  .hpi. To do this, go to the plugin's page on the
  link:https://updates.jenkins-ci.org/download/plugins[Jenkins wiki] and download one
  of its archived versions.


=== Troubleshooting for Stability

Jenkins masters can suffer instability problems when the master is not properly
sized for its hardware or a buggy plugin wastes resources. To combat this,
Jenkins administrators should begin their troubleshooting by identifying which
components are behaving abnormally and which resources are insufficient. The
administrator can
link:https://wiki.jenkins-ci.org/display/JENKINS/Obtaining+a+thread+dump[take thread
dumps] and head dumps to get some of this information, but in some cases where
the instance has become non-operational and taking a thread dump is impossible,
it is useful to have a persistent record outside of Jenkins itself to reference
when such troubleshooting is required.

==== Using the Jenkins Metrics Plugin

The link:https://wiki.jenkins-ci.org/display/JENKINS/Metrics+Plugin[Jenkins Metrics
Plugin] is an open-source plugin which exposes metrics on a Jenkins instance.
Metrics are exposed using the
link:https://dropwizard.github.io/metrics/3.1.0[Dropwizard Metrics API]

.Metrics exposed

The exact list of exposed metrics varies depending on your installed plugins.
To get a full list of available metrics for your own master, run the following
script on
https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+Script+Console[your
master's script console]:

[source,groovy]
----
for (j in Jenkins.instance.getExtensionList(jenkins.metrics.api.MetricProvider.class)) {
     for (m in j.getMetricSet()) {
          for (i in m.metrics)
               { println i.getKey() }
     }
}
----

CloudBees has
link:https://documentation.cloudbees.com/docs/cje-user-guide/monitoring-sect-reference.html#monitoring-sect-reference-metrics[documented]
the full list of exposed metrics, along with in-depth explanations of each.

.Metrics Usage

Metrics are protected by a set of permissions for viewing, accessing the thread
dump, and posting a health check. The Metrics Operational Menu can be access
via the web UI by visiting <jenkins-url>/metrics/currentUser, and the 4 menu
options (Metrics, Ping, Threads, Healthcheck) lead to a JSON string containing
the requested metrics or thread dump.

Access to the Metrics Servlet can also be provided by issuing API keys. API
keys can be configured from the Jenkins global configuration screen
(<jenkins-url>/configure) under the "Metrics" section. Multiple access can be
generated and permissions associated with those keys can also be restricted at
this level.

More information on Metrics basic and advanced usages can be found
link:https://documentation.cloudbees.com/docs/cje-user-guide/monitoring-sect-getting-started.html[here].
