---
layout: documentation
section: doc
---

:notitle:
:sectanchors:
:toc: left

= Using Organization Folders
== What are Organization Folders?

Organization folders enable Jenkins to automatically detect and include any new
repositories within them as resources.

When you create a new repository (as might be the case for a new project), that
repository has a `Jenkinsfile`. If you also configure one or more organization
folders, Jenkins automatically detects any repository in an organization folder,
scans the contents of that repository at either default or configurable
intervals, and creates a Multibranch Pipeline project for what it finds in the
scan. An organization folder functions as a "parent," and any item within it is
treated as a "child" of that parent.

Organization folders alleviate the need to manually create projects for new
repositories. When you use organization folders, Jenkins views your repositories
as a hierarchy, and each repository (organization folder) may optionally have
child elements such as branches or pull requests.

== Creating Organization Folders

To create Organization folders:

. Open Jenkins in your web browser.
. Go to: New Item → GitHub Organization or New Item → Bitbucket Team.
. Follow the configuration steps, making sure to specify appropriate scan
  credentials and a specific owner for the GitHub Organization or Bitbucket Team
  name.
. Set build triggers by selecting the checkbox associated with the trigger type
  you want. Folder scans and the pipeline builds associated with those scans can
  be initiated by command scripts or performed at defined intervals. They can also
  triggered by project promotion or changes to the images in a monitored Docker
  hub.
. Decide whether to automatically remove or retain unused items. "Orphaned Item
  Strategy" fields in the configuration interface let you specify how many days to
  keep old items, and how many old items to keep. If you enter no values in these
  fields, unused items are removed by default.

While configuring organization folders, you can set the following options:

* Repository name pattern - a regular expression to specify which repositories are included in scans
* API endpoint - an alternate API endpoint to use a self-hosted GitHub Enterprise
* Checkout credentials - alternate credentials to use when checking out (cloning) code

Multibranch Pipeline projects and Organization Folders are examples of
"computed folder" functionality. In Multibranch Pipeline projects, computation
creates child items for eligible branches. In Organization folders, computation
populates child items as individual Multibranch Pipelines for scanned
repositories.

Select the "Folder Computation" section of your Jenkins interface to see the
duration (in seconds) and result (success or failure) of computation operations,
or to access a Folder Computation Log that provides more detail about this
activity.
