---
layout: simplepage
title: "Jenkins Governance Meeting"
section: project
---

As per the Jenkins link:/project/governance/[Governance Document],
the project holds a bi-weekly meeting on the `#jenkins-meeting` link:/chat[IRC Channel] on Freenode,
open for everyone to participate, where we can make decisions about the project.
In case of doubt, the project's link:/project/board[governance board] takes priority.

The meeting is run with http://meetbot.debian.net/Manual.html[the moderation of a bot].
You can use the `+#info+` and `+#idea+` commands to flag info and ideas as such, which will be noted in the meeting minutes. 
Further commands are documented http://meetbot.debian.net/Manual.html#commands[here].

Minutes for each meeting should be linked with each past meeting below, and can be otherwise found in full on
http://meetings.jenkins-ci.org/[meetings.jenkins-ci.org].
Action items are https://issues.jenkins-ci.org/browse/MEETING[tracked in JIRA].

=== Agenda

When adding agenda items, please add them to the to the *end of the list*
(i.e. first-come, first-served), and place your Jenkins user ID next to it.

[[GovernanceMeetingAgenda-ArchivedMeetings]]
=== Archived Meetings

Older agendas, minutes and IRC logs are archived on these pages:

* link:./archives/2019[Governance Meeting Archive 2019]
* link:./archives/2018[Governance Meeting Archive 2018]
* link:./archives/2017[Governance Meeting Archive 2017]
* link:./archives/2016[Governance Meeting Archive 2016]
* link:./archives/2015[Governance Meeting Archive 2015]
* link:./archives/2014[Governance Meeting Archive 2014]
* link:./archives/2013[Governance Meeting Archive 2013]
* link:./archives/2012[Governance Meeting Archive 2012]
* link:./archives/2011[Governance Meeting Archive 2011]

[[GovernanceMeetingAgenda-GeneralMeetingResources]]
== General Meeting Resources

* http://webchat.freenode.net/?channels=jenkins&uio=OT10cnVlde[Direct IRC Webchat link]
* http://permatime.com/UTC[Permatime]
