---
layout: simplepage
title: "Jenkins Governance Meeting"
section: project
---

As per the Jenkins link:/project/governance/[Governance Document],
the project holds a bi-weekly governance meeting on the `#jenkins-meeting` link:/chat[IRC Channel] on Freenode.
Jenkins Governance Meeting is open for everyone to participate and vote.
The meetings calendar is available link:/event-calendar[here].

This meeting is used to make decisions about the project: budget approvals, key decisions sign-off, voting on proposals if there is no consensus, etc.
The topics are usually discussed in the link:https://groups.google.com/forum/#!forum/jenkinsci-dev[developer mailing list], and contributors can cast their votes there ahead of the meeting.
This meeting is rarely used for technical decisions, for that purpose we use the developer mailing list and link:https://github.com/jenkinsci/jep/[Jenkins Enhancement Proposals].
If a decision cannot be made at the governance meeting, the project's link:/project/board[governance board] takes priority.

=== Agenda

Starting from 12.12.2019, the governance meeting agenda is posted in link:http://bit.ly/jenkins-governance-meeting[this Google Document].
Everyone is welcome to add a topic for one of the incoming meetings by suggesting a change in this Google document.

++++
<iframe src="https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg?embedded=true" width="100%" height="600px"></iframe>
++++

=== Meeting notes

Minutes and raw conversation history for each meeting can be found in full on link:http://meetings.jenkins-ci.org/[meetings.jenkins-ci.org].
The meeting minutes also contain the list of action items defined at the meeting.

=== Archived Meetings

Older agendas, minutes and IRC logs are archived on these pages:

* link:./archives/2019[Governance Meeting Archive 2019]
* link:./archives/2018[Governance Meeting Archive 2018]
* link:./archives/2017[Governance Meeting Archive 2017]
* link:./archives/2016[Governance Meeting Archive 2016]
* link:./archives/2015[Governance Meeting Archive 2015]
* link:./archives/2014[Governance Meeting Archive 2014]
* link:./archives/2013[Governance Meeting Archive 2013]
* link:./archives/2012[Governance Meeting Archive 2012]
* link:./archives/2011[Governance Meeting Archive 2011]

== Useful links

* https://webchat.freenode.net/#jenkins-meeting[Direct IRC Webchat link]

== IRC Tips

The meeting is run with http://meetbot.debian.net/Manual.html[the moderation of a bot].
You can use the `+#info+` and `+#idea+` commands to flag info and ideas as such, which will be noted in the meeting minutes. 
Further commands are documented http://meetbot.debian.net/Manual.html#commands[here].
