---
layout: simplepage
title: "Jenkins Governance Meeting"
section: project
---

As per the Jenkins link:/project/governance/[Governance Document], the community holds a regular governance meeting.
This meeting is used to make decisions about the project: budget approvals, key decisions sign-off, voting on proposals if there is no consensus, etc.
It is open for everyone to participate and vote.
The topics are usually discussed in the link:https://groups.google.com/g/jenkinsci-dev[developer mailing list] ahead of the meeting,
so contributors can share their feedback and cast votes asynchronously.

This meeting is rarely used for technical decisions, for that purpose we use the developer mailing list and link:https://github.com/jenkinsci/jep/[Jenkins Enhancement Proposals].
If a decision cannot be made at the governance meeting, the project's link:/project/board[governance board] takes priority.

=== How to join the meetings?

The governance meeting commonly happens every four weeks on Mondays.
The link:/events[event calendar] provides exact times and other details.
We hold the meeting as a recorded video call.
Links to the video call are also available in the link:/event-calendar[Jenkins events calendar].

=== How to propose a topic?

1. Start a discussion with your proposal in the link:https://groups.google.com/g/jenkinsci-dev[developer mailing list]
2. Wait for initial feedback in the mailing list.
   If there is a strong consensus among community members and no formal approval needed, the mailing list thread might be enough.
3. Suggest a change to the link:https://hackmd.io/6mgEkr1rS7Ca4j4a5YxZfA[next meeting agenda].

=== Agenda

The next governance meeting agenda is posted in link:https://hackmd.io/6mgEkr1rS7Ca4j4a5YxZfA[a HackMD note].
Everyone is welcome to add a topic for the upcoming meeting by suggesting a change in the mailing list or in the link:https://hackmd.io/6mgEkr1rS7Ca4j4a5YxZfA[HackMD note].

++++
<iframe src="https://hackmd.io/6mgEkr1rS7Ca4j4a5YxZfA" width="100%" height="600px"></iframe>
++++

=== Archived Meetings

Agendas, minutes, and other notes are archived in the link:https://github.com/jenkins-infra/governance-meetings-archives[Governance Meeting Archive 2011 - 2024].

// * link:./archives/2019[Governance Meeting Archive 2019]
// * link:./archives/2018[Governance Meeting Archive 2018]
// * link:./archives/2017[Governance Meeting Archive 2017]
// * link:./archives/2016[Governance Meeting Archive 2016]
// * link:./archives/2015[Governance Meeting Archive 2015]
// * link:./archives/2014[Governance Meeting Archive 2014]
// * link:./archives/2013[Governance Meeting Archive 2013]
// * link:./archives/2012[Governance Meeting Archive 2012]
// * link:./archives/2011[Governance Meeting Archive 2011]

// Minutes and raw conversation history for older meetings can be found in full on link:http://meetings.jenkins-ci.org/[meetings.jenkins-ci.org].

// Before using HackMD, we used Google Docs for the agenda.
// Previous notes are available in the old link:https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg[Google doc].
