---
layout: simplepage
title: "Jenkins Governance Meeting"
section: project
---

As per the Jenkins link:/project/governance/[Governance Document], the community holds a regular governance meeting.
This meeting is used to make decisions about the project: budget approvals, key decisions sign-off, voting on proposals if there is no consensus, etc.
It is open for everyone to participate and vote.
The topics are usually discussed in the link:https://groups.google.com/g/jenkinsci-dev[developer mailing list] ahead of the meeting,
so contributors can share their feedback and cast votes asynchronously.

This meeting is rarely used for technical decisions, for that purpose we use the developer mailing list and link:https://github.com/jenkinsci/jep/[Jenkins Enhancement Proposals].
If a decision cannot be made at the governance meeting, the project's link:/project/board[governance board] takes priority.

=== How to join the meetings?

The governance meeting commonly happens every two weeks on Mondays, see the link:/events[event calendar] for exact times and subscription.
We hold the meeting as a recorded video call.
The meetings calendar with links is available link:/event-calendar[here].

=== How to propose a topic?

1. Start a discussion with your proposal in the link:https://groups.google.com/g/jenkinsci-dev[developer mailing list]
2. Wait for initial feedback in the mailing list.
   If there is a strong consensus among community members and no formal approval needed, the mailing list thread might be enough.
3. Suggest a change to the agenda document linked below.

=== Agenda

Starting from 12.12.2019, the governance meeting agenda is posted in link:http://bit.ly/jenkins-governance-meeting[this Google Document].
Everyone is welcome to add a topic for one of the incoming meetings by suggesting a change in this Google document.

++++
<iframe src="https://docs.google.com/document/d/11Nr8QpqYgBiZjORplL_3Zkwys2qK1vEvK-NYyYa4rzg?embedded=true" width="100%" height="600px"></iframe>
++++

=== Archived Meetings

Older agendas, minutes and IRC logs are archived on these pages:

Minutes and raw conversation history for each meeting can be found in full on link:http://meetings.jenkins-ci.org/[meetings.jenkins-ci.org].

* link:./archives/2019[Governance Meeting Archive 2019]
* link:./archives/2018[Governance Meeting Archive 2018]
* link:./archives/2017[Governance Meeting Archive 2017]
* link:./archives/2016[Governance Meeting Archive 2016]
* link:./archives/2015[Governance Meeting Archive 2015]
* link:./archives/2014[Governance Meeting Archive 2014]
* link:./archives/2013[Governance Meeting Archive 2013]
* link:./archives/2012[Governance Meeting Archive 2012]
* link:./archives/2011[Governance Meeting Archive 2011]
