---
layout: simplepage
title: Jenkins Security Advisory 2012-09-17
section: security
kind: core and plugins
---

This advisory announces security vulnerabilities that were found in Jenkins core and several plugins.

* The first vulnerability in Jenkins core allows unprivileged users to insert data into the Jenkins controller, which can lead to remote code execution. For this vulnerability to be exploited, the attacker must have an HTTP access to a Jenkins controller, and he must have a read access to Jenkins.
* The second vulnerability in Jenkins core is a cross-site scripting vulnerability. This allows an attacker to craft an URL that points to Jenkins, and if a legitimate user clicks this link, and the attacker will be able to hijack the user session.
* The third vulnerability is a cross-site scripting vulnerability in plugin:violations[the Violations plugin]
* The fourth vulnerability is a cross-site scripting vulnerability in plugin:ci-game[the Continuous Integration Game plugin]

Several of these vulnerabilities were discovered by link:https://www.randomstorm.com/[Avram Marius Gabriel].

== Severity
The first vulnerability in the core is rated as *critical*, as it allows malicious users to execute arbitrary code on the server. The other three XSS vulnerabilities are rated as *high*, as they allow malicious users to escalate privileges.

== Fix
The following versions incorporate fixes to the vulnerabilities found in the Jenkins core.

* Main line users should upgrade to Jenkins link:http://mirrors.jenkins-ci.org/[1.482]
* LTS users should upgrade to link:http://mirrors.jenkins-ci.org/[1.466.2]

To patch vulnerabilities in the plugins, upgrade to the following versions. These plugins should be available in your Jenkins' plugin update center UI in up to a day.

* Users of the Violations plugin should upgrade to link:https://updates.jenkins-ci.org/download/plugins/violations/[0.7.11] or later
* Users of the CI game plugin should upgrade to link:https://repo.jenkins-ci.org/releases/org/jvnet/hudson/plugins/ci-game/1.19/[1.19] or later

== Other resources
* link:https://www.cloudbees.com/jenkins-advisory/jenkins-security-advisory-2012-09-17.cb[Corresponding security advisory on CloudBees regarding DEV@cloud and Jenkins Enterprise by CloudBees]
