---
layout: simplepage
title: Jenkins Security Advisory 2012-03-05
section: security
kind: core
---

This advisory announces a couple of critical security vulnerabilities that were found in Jenkins core.

The first vulnerability is a directory traversal vulnerability. This allows an anonymous attacker to read files in the file system that shouldn't be exposed. This vulnerability affects Jenkins that run on Windows, whether or not the access control in Jenkins is enabled. Those file reads are still subject to OS-level access control, and therefore an attacker will only gain access to files that are readable to the OS user that runs the Jenkins process. This is a vulnerability in the built-in servlet container (named Winstone), and therefore the only affected users are those who are running Jenkins via `java -jar jenkins.war` (this includes users of the Windows installer.) This vulnerability affects all versions of Jenkins up to and including 1.452, and LTS releases up to and including 1.424.3.

The second vulnerability is a cross-site scripting (XSS) vulnerability, which allows an attacker to inject malicious HTMLs to pages served by Jenkins. This allows an attacker to escalate his privileges by hijacking sessions of other users. This vulnerability affects all versions of Jenkins up to and including 1.452, and LTS releases up to and including 1.424.3, regardless of the security settings.

== Severity
We rate this vulnerability as critical, as it allows malicious users to gain unauthorized access to the information (in the case of the first vulnerability), and to impersonate the administrator of the system, gaining the full access to the system (in case of the second vulnerability), even though this attack can be only mounted passively.

== Fix
* Main line users should upgrade to Jenkins link:http://mirrors.jenkins-ci.org/[1.454].
* LTS users should upgrade to the upcoming link:http://mirrors.jenkins-ci.org/[1.424.6].

== Other resources
* link:https://www.cloudbees.com/jenkins-advisory/jenkins-security-advisory-2012-03-05.cb[Corresponding security advisory on CloudBees regarding DEV@cloud and Jenkins Enterprise by CloudBees]
