---
layout: simplepage
title: Jenkins Security Advisory 2015-10-12
section: security
kind: plugin
---

This advisory announces a vulnerability in the plugin:google-login[Google Login Plugin].

Jenkins issue: *SECURITY-208*

CVE ID: *CVE-2015-5298*

== Description

The Google Login Plugin (versions 1.0 and 1.1) allows malicious anonymous users to authenticate successfully against Jenkins instances that are supposed to be locked down to a particular Google Apps domain through client-side request modification.

== Severity

CVE-2015-5298 is rated *medium*. While the attacker will be able to successfully authenticate to any network-reachable Jenkins instance using the Google Login plugin, it will depend on the configuration of permissions, specifically the _authenticated_ group, what the impact on the system is.

== Fix

Update the Google Login Plugin to version 1.2 or higher. If it's not available in plugin manager, update it by pressing _Check Now_. Alternatively, download the plugin HPI file from link:https://updates.jenkins-ci.org/download/plugins/google-login/[the update site] or the link:https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/google-login/1.2/[repository] and install it by uploading in _Manage Jenkins » Manage Plugins »&nbsp;Advanced_.

== Credit

The Jenkins project would like to thank Wes Wineberg for reporting this security issue.