---
layout: simplepage
title: Jenkins Security Advisory 2016-11-16
section: security
kind: core
---

This advisory announces the fix for a previously disclosed zero-day vulnerability in Jenkins.

== Description


=== Remote code execution vulnerability in remoting module
*SECURITY-360 / CVE-2016-9299*

An unauthenticated remote code execution vulnerability allowed attackers to transfer a serialized Java object to the Jenkins CLI, making Jenkins connect to an attacker-controlled LDAP server, which in turn can send a serialized payload leading to code execution, bypassing existing protection mechanisms.

== Severity

* SECURITY-360 is considered *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H[critical]* as it allows unprivileged attackers to execute arbitrary code.

== Affected versions

* All Jenkins main line releases up to and including 2.31
* All Jenkins LTS releases up to and including 2.19.2

== Fix

* Jenkins main line users should update to 2.32
* Jenkins LTS users should update to 2.19.3

These versions include fixes to all the vulnerabilities described above. All prior versions are affected by these vulnerabilities.

== Notes

As part of this fix, a number of other so-called "gadgets" were reviewed and are now also being prohibited. We tracked this activity as SECURITY-317.

== Other resources

* link:/blog/2016/11/16/security-updates-addressing-zero-day/[November 16 blog post announcing the fixes]
* link:/blog/2016/11/12/addressing-remote-vulnerabilities-in-cli/[November 11 blog post with workaround after public disclosure of the vulnerability]
* link:/doc/upgrade-guide/2.19/#upgrading-to-jenkins-lts-2-19-3[LTS 2.19.3 upgrade guide for Jenkins administrators]
* link:https://www.cloudbees.com/jenkins-security-advisory-2016-11-16[Corresponding security advisory for CloudBees Jenkins Enterprise and CloudBees Jenkins Operations Center]
