---
layout: simplepage
title: Jenkins Security Advisory 2016-06-20
section: security
kind: plugins
---

This advisory announces vulnerabilities in these Jenkins plugins:

* plugin:async-http-client[Async Http Client Plugin]
* plugin:build-failure-analyzer[Build Failure Analyzer]
* plugin:image-gallery[Image Gallery Plugin]
* plugin:tap[TAP Plugin]


== Description

=== Path traversal vulnerability in TAP Plugin
*SECURITY-85 / CVE-2016-4986*

The plugin did not correctly filter a parameter and allowed reading arbitrary files on the file system.


=== Path traversal vulnerability in Image Gallery Plugin
*SECURITY-278 / CVE-2016-4987*

The plugin did not correctly validate form fields and allowed listing arbitrary directories and reading arbitrary files on the file system.


=== Cross-site scripting vulnerability in Build Failure Analyzer Plugin
*SECURITY-290 / CVE-2016-4988*

The plugin did not escape a parameter echoed on an HTML page, resulting in a reflected XSS vulnerability.


=== Async HTTP Client Plugin does not properly validate certificates
*SECURITY-305 / CVE-2013-7397 and CVE-2013-7398*

Async HTTP Client Plugin provides the Async HTTP Client Java library to other plugins. It is based on the 1.7.x line of AHC, which by default is vulnerable to link:https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-7397[CVE-2013-7397] and link:https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-7398[CVE-2013-7398], allowing man-in-the-middle attacks. The fixes for these vulnerabilities were backported. The system property `jenkins.plugins.asynchttpclient.AHC.acceptAnyCertificate` can temporarily be set to `true` to disable these new validity checks. link:https://wiki.jenkins-ci.org/display/JENKINS/Features+controlled+by+system+properties[Learn more about system properties in Jenkins].

== Severity

* SECURITY-85 is considered *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N[medium]*.
* SECURITY-278 is considered *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N[medium]*.
* SECURITY-290 is considered *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N[medium]*.
* SECURITY-305 is considered:
** *link:https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-7397[medium]* (CVE-2013-7397)
** *link:https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2013-7398[medium]* (CVE-2013-7398).


== Affected versions

* Async Http Client Plugin up to and including version 1.7.24.
* Build Failure Analyzer Plugin up to and including version 1.15.0.
* Image Gallery Plugin up to and including version 1.3.
* TAP Plugin up to and including version 1.24.


== Fix

* Users of Async Http Client Plugin should update it to version 1.7.24.1.
* Users of Build Failure Analyzer Plugin should update it to version 1.16.0.
* Users of Image Gallery Plugin should update it to version 1.4.
* Users of TAP Plugin should update it to version 1.25.

These versions include fixes to the vulnerabilities described above. All prior versions are affected by these vulnerabilities.

== Credit

The Jenkins project would like to thank the following people for discovering and link:/security/#reporting-vulnerabilities[reporting] these vulnerabilities:

* *Ben Walding, CloudBees, Inc.* for SECURITY-278
* *Jason Marzan* for SECURITY-290
* *Kishore Bhatia, CloudBees, Inc.* for SECURITY-305
