---
layout: simplepage
title: Jenkins Security Advisory 2016-07-27
section: security
kind: plugin
---

This advisory announces a vulnerability in the link:https://plugins.jenkins.io/cucumber-reports[Cucumber Reports Plugin].


== Description

=== Cucumber Reports Plugin disables Content-Security-Policy for archived and workspace files
*SECURITY-309*

Jenkins 1.641 and 1.625.3 introduced `Content-Security-Policy` HTTP headers as protection against Cross-Site Scripting attacks using workspace files and archived artifacts served using `DirectoryBrowserSupport` (link:/security/advisory/2015-12-09/[SECURITY-95]).

The Cucumber Reports Plugin disabled this XSS protection until Jenkins was restarted whenever a Cucumber Report was viewed by any user to work around the `Content-Security-Policy` limitations.

While disabling this protection mechanism temporarily may be necessary to make plugins work that haven't been adapted to work with the Content-Security-Policy restriction, this should only be done by administrators, as doing so may result in a security issue (see https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy[Configuring Content Security Policy]).


== Severity

* SECURITY-309 is considered *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:N[medium]*.


== Affected versions

* link:https://plugins.jenkins.io/cucumber-reports[Cucumber Reports Plugin] 1.3.0 to 2.5.1 (inclusive).


== Fix

* Users of link:https://plugins.jenkins.io/cucumber-reports[Cucumber Reports Plugin] should update it to version 2.6.0 or newer.
