---
layout: simplepage
title: Jenkins Security Advisory 2017-11-08
section: security
kind: core
---

This advisory announces multiple vulnerabilities in Jenkins.

== Description

=== Unsafe use of user names as directory names
*SECURITY-499 / CVE-2017-1000391*

Jenkins stores metadata related to _people_, which encompasses actual user accounts, as well as users appearing in SCM, in directories corresponding to the user ID on disk.
These directories used the user ID for their name without additional escaping.
This potentially resulted in a number of problems, such as the following:

. User names consisting of a single forward slash would have their user record stored in the parent directory; deleting this user deleted all user records.
. User names containing character sequences such as `..` could be used to clobber other configuration files in Jenkins.
. User names could consist of reserved names such as `COM` (on Windows).

This is not limited to the _Jenkins user database_ security realm, other security realms such as LDAP may allow users to create user names that result in problems in Jenkins.

User names are now transformed into a filesystem-safe representation that is used as directory name.

=== Persisted XSS vulnerability in autocompletion suggestions
*SECURITY-641 / CVE-2017-1000392*

Autocompletion suggestions for text fields were not escaped, resulting in a persisted cross-site scripting vulnerability if the source for the suggestions allowed specifying text that includes HTML metacharacters like less-than and greater-than characters.

Known previously unsafe sources for these suggestions include the names of loggers in the log recorder condition, and agent labels.

Autocompletion suggestions are now escaped and can no longer contain HTML-based formatting.


== Severity

* SECURITY-499: Various, the highest of which is *link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:L/A:L[low]*
* SECURITY-641: *link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N[low]*



== Affected versions

* Jenkins weekly up to and including 2.88
* Jenkins LTS up to and including 2.73.2


== Fix

* Jenkins weekly should be updated to 2.89
* Jenkins LTS should be updated to 2.73.3

These versions include fixes to the vulnerabilities described above.
All prior versions are affected by these vulnerabilities unless otherwise indicated.


== Credit

The Jenkins project would like to thank the reporters for discovering and link:/security/#reporting-vulnerabilities[reporting] these vulnerabilities:

* *Darren Zhao* for SECURITY-499
* *Viktor Gazdag of NCC Group* for SECURITY-641



== Other Resources

* link:/blog/2017/11/08/security-updates/[Announcement blog post]
