---
layout: advisory
title: Jenkins Security Advisory 2017-11-08
section: security
kind: core
core:
  lts:
    previous: 2.73.2
    fixed: 2.73.3
  weekly:
    previous: 2.88
    fixed: 2.89
issues:
- id: SECURITY-499
  cvss:
    severity: low
    vector: CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:U/C:N/I:L/A:L
  reporter: Darren Zhao
- id: SECURITY-641
  reporter: Viktor Gazdag of NCC Group
  cvss:
    severity: low
    vector: CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:U/C:L/I:L/A:N
resources:
- url: /blog/2017/11/08/security-updates/
  title: Announcement blog post
---

== Description

[#SECURITY-499]
=== Unsafe use of user names as directory names
*SECURITY-499 / CVE-2017-1000391*

Jenkins stores metadata related to _people_, which encompasses actual user accounts, as well as users appearing in SCM, in directories corresponding to the user ID on disk.
These directories used the user ID for their name without additional escaping.
This potentially resulted in a number of problems, such as the following:

. User names consisting of a single forward slash would have their user record stored in the parent directory; deleting this user deleted all user records.
. User names containing character sequences such as `..` could be used to clobber other configuration files in Jenkins.
. User names could consist of reserved names such as `COM` (on Windows).

This is not limited to the _Jenkins user database_ security realm, other security realms such as LDAP may allow users to create user names that result in problems in Jenkins.

User names are now transformed into a filesystem-safe representation that is used as directory name.

[#SECURITY-641]
=== Persisted XSS vulnerability in autocompletion suggestions
*SECURITY-641 / CVE-2017-1000392*

Autocompletion suggestions for text fields were not escaped, resulting in a persisted cross-site scripting vulnerability if the source for the suggestions allowed specifying text that includes HTML metacharacters like less-than and greater-than characters.

Known previously unsafe sources for these suggestions include the names of loggers in the log recorder condition, and agent labels.

Autocompletion suggestions are now escaped and can no longer contain HTML-based formatting.
