---
layout: simplepage
title: Jenkins Security Advisory 2017-09-27
section: security
kind: core
---

This advisory announces a vulnerability in Jenkins.

== Description

=== Unprotected startup
*JENKINS-47139*

Jenkins 2.80 did not correctly initialize the setup wizard on the first startup.
This resulted in security settings like authentication and authorization not being set to a strict default.
Affected instances allow anonymous administrator access and need to be configured to restrict access.

Jenkins instances upgraded from 2.79 or earlier to 2.80 without completing the setup wizard will no longer show the setup wizard, but are locked and need the initial administrator password to unlock.

== Severity

* JENKINS-47139: link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H[high]


== Affected versions

* Jenkins 2.80 only
* Jenkins LTS releases are unaffected


== Fix

* Users of Jenkins 2.80 should review all the options of the _Configure Global Security_ dialog.
* Jenkins 2.81 contains a fix for this issue, so an initial startup is protected.
