---
layout: simplepage
title: Jenkins Security Advisory 2017-03-09
section: security
kind: plugin
---

This advisory announces a vulnerability in the plugin:pipeline-maven[Maven Pipeline Plugin] 0.6.

== Description

=== Maven Pipeline Plugin allows reading arbitrary files from the Jenkins controller
*SECURITY-441*

Due to an improperly performed plugin release, version 0.6 of the Maven Pipeline Plugin is still affected by the vulnerability originally announced in the link:/security/advisory/2017-03-07/[2017-03-07] security advisory:

____
The Maven Pipeline Plugin allowed users to copy and read arbitrary files accessible from the Jenkins controller process in a Pipeline script by specifying that file's path on the Jenkins controller as `mavenSettingsFilePath` or `globalMavenSettingsFilePath`.
____

== Severity

* SECURITY-441: *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N[high]*.

== Affected versions

* Maven Pipeline Plugin version 0.6 and earlier, and 2.0-beta-5 and earlier. 2.0-beta-6 has been released correctly.

== Fix

* Users of Maven Pipeline Plugin 0.6 or earlier should update it to version 0.7.
