---
layout: simplepage
title: Jenkins Security Advisory 2017-08-08
section: security
kind: plugin
---

This advisory announces a vulnerability in the plugin:saml[SAML Plugin].

== Description

=== SAML Plugin stored keystore and private key passwords in plain text
*JENKINS-46007*

The SAML Plugin stored passwords unencrypted as part of its configuration.
This allowed users with Jenkins controller local file system access and Jenkins administrators to retrieve the stored password.
The latter could result in exposure of the passwords through browser extensions, cross-site scripting vulnerabilities, and similar situations.

The SAML Plugin now stores passwords encrypted, and only transfers encrypted values as part of the configuration form after the initial configuration.

== Severity

* JENKINS-46007: *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N[low]*

== Affected versions

* JENKINS-46007: SAML Plugin up to and including 1.0.2.

== Fix

* Users of SAML Plugin should update it to version 1.0.3 or newer.
