---
layout: simplepage
title: Jenkins Security Advisory 2017-12-06
section: security
kind: plugin
---

This advisory announces a vulnerability in this Jenkins plugin:

* plugin:ec2[EC2]

== Description


=== Arbitrary shell command execution on master by users with Agent-related permissions in EC2 Plugin
*SECURITY-643 / CVE-2017-1000502*

Users with permission to create or configure agents in Jenkins could configure an EC2 agent to run arbitrary shell commands on the master node whenever the agent was supposed to be launched.

Configuration of these agents now requires the _Run Scripts_ permission typically only granted to administrators.


== Severity

* SECURITY-643: link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H[high]


== Affected versions
* EC2 Plugin up to and including 1.37

== Fix
* EC2 Plugin should be updated to version 1.38

These versions include fixes to the vulnerabilities described above.
All prior versions are considered to be affected by these vulnerabilities unless otherwise indicated.

== Credit

The Jenkins project would like to thank the reporter for discovering and link:/security/#reporting-vulnerabilities[reporting] this vulnerability:

* *Jesse Glick, CloudBees Inc.* for SECURITY-643
