---
layout: simplepage
title: Jenkins Security Advisory 2017-12-11
section: security
kind: plugin
---

This advisory announces a vulnerability in this Jenkins plugin:

* plugin:script-security[Script Security]

== Description


=== Arbitrary file read vulnerability in Script Security Plugin
*SECURITY-663 / CVE-2017-1000505*

Users with the ability to configure sandboxed Groovy and Pipeline scripts, including those from SCM, are able to use a type coercion feature in Groovy to create new `File` objects from strings. This allowed reading arbitrary files on the Jenkins master file system.

Such a type coercion is now subject to sandbox protection and considered to be a call to the `new File(String)` constructor for the purpose of in-process script approval.

== Severity

* SECURITY-663: link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N[medium]

== Affected versions
* Script Security Plugin up to and including 1.36

== Fix
* Script Security Plugin should be updated to version 1.37

These versions include fixes to the vulnerabilities described above.
All prior versions are considered to be affected by these vulnerabilities unless otherwise indicated.

== Credit

The Jenkins project would like to thank the reporter for discovering and link:/security/#reporting-vulnerabilities[reporting] this vulnerability:

* *Gregory Draperi* for SECURITY-663
