---
layout: simplepage
title: Jenkins Security Advisory 2017-03-07
section: security
kind: plugin
---

This advisory announces a vulnerability in the plugin:pipeline-maven[Maven Pipeline Plugin].

== Description

=== Maven Pipeline Plugin allows reading arbitrary files from the Jenkins controller
*SECURITY-441*

The Maven Pipeline Plugin allowed users to copy and read arbitrary files accessible from the Jenkins controller process in a Pipeline script by specifying that file's path on the Jenkins controller as `mavenSettingsFilePath` or `globalMavenSettingsFilePath`.

== Severity

* SECURITY-441: *link:https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N[high]*.

== Affected versions

* Maven Pipeline Plugin up to 0.5 and 2.0-beta-5. All previous versions are affected.

== Fix

* Users of Maven Pipeline Plugin should update it to version 0.6 or newer, or 2.0-beta-6 or newer.

== Credit

The Jenkins project would like to thank the reporter for discovering and link:/security/#reporting-vulnerabilities[reporting] this vulnerability:

* *Jesse Glick, CloudBees, Inc.* for SECURITY-441
