---
layout: advisory
title: Jenkins Security Advisory 2018-02-05
section: security
kind: plugins
issues:
- id: SECURITY-521
  reporter: James Nord, CloudBees, Inc.
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: junit
      fixed: 1.24
      previous: 1.23
- id: SECURITY-659
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: ccm
      fixed: 3.2
      previous: 3.1
- id: SECURITY-660
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: android-lint
      fixed: 2.6
      previous: 2.5
- id: SECURITY-698
  cvss:
    severity: low
    vector: CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N
  plugins:
    - name: credentials-binding
      fixed: 1.15
      previous: 1.14
- id: SECURITY-699
  reporter: Aleksandr Kazakov
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H
  plugins:
    - name: workflow-support
      fixed: 2.18
      previous: 2.17
resources:
- url: /blog/2018/02/05/security-updates/
  title: Announcement blog post
---

== Description


=== XXE vulnerabilities in multiple static analysis plugins

* *SECURITY-659 / CVE-2018-1000054* (CCM)
* *SECURITY-660 / CVE-2018-1000055* (Android Lint)

Multiple plugins based on plugin:analysis-core[Static Analysis Utilities] plugin are affected by an XML External Entity (XXE) processing vulnerability.
This allows an attacker to configure build processes such that one of these plugins parses a maliciously crafted file that uses external entities for extraction of secrets from the Jenkins controller, server-side request forgery, or denial-of-service attacks.

External entity resolution has been disabled for these plugins.

[#junit]
=== XXE vulnerability in JUnit plugin

*SECURITY-521 / CVE-2018-1000056*

JUnit plugin is affected by an XML External Entity (XXE) processing vulnerability.
This allows an attacker to configure build processes such that JUnit plugin parses a maliciously crafted file that uses external entities for extraction of secrets from the Jenkins controller, server-side request forgery, or denial-of-service attacks.

External entity resolution has been adjusted to avoid XXE and still satisfy the existing features.

[#credentials-binding]
=== Credentials Binding plugin did not mask the secret actually provided to the build in rare circumstances
// That title took a lot of work, but in the end it doesn't matter that the actual password is masked if that's not what's used in the build

*SECURITY-698 / CVE-2018-1000057*

Credentials Binding plugin allows specifying passwords and other secrets as environment variables, and will hide them from console output in builds.

However, since Jenkins will try to resolve references to other environment variables in environment variables passed to a build, this can result in other values than the one specified being provided to a build.
For example, the value `+++p4$$w0rd+++` would result in Jenkins passing on `+++p4$w0rd+++`, as `+++$$+++` is the escape sequence for a single `$`.

Credentials Binding plugin does not prevent such a transformed value (e.g. `p4$w0rd`) from being shown on the build log, allowing users to reconstruct the actual password value from the transformed one.

Credentials Binding plugin will now escape any `$` characters in password values so they are correctly passed to the build.

This issue did apply to freestyle and other classic job types, but does not apply to Pipelines.

[#workflow-support]
=== Arbitrary code execution due to incomplete sandbox protection in Pipeline: Supporting APIs Plugin

*SECURITY-699 / CVE-2018-1000058*

Pipelines are subject to _script security_:
Either the entire Pipeline needs to be approved, or it runs in a sandbox, with only approved methods etc. allowed to be called.

Methods related to Java deserialization like `readResolve` implemented in Pipeline scripts were not subject to sandbox protection, and could therefore execute arbitrary code.
This could be exploited e.g. by regular Jenkins users with the permission to configure Pipelines in Jenkins, or by trusted committers to repositories containing Jenkinsfiles.

Deserialization of objects in Pipeline is now also subject to sandbox protection.

This change may cause existing scripts relying on the incomplete sandbox protection to start failing, and requiring additional script approval.

NOTE: This change requires that Pipeline: Groovy plugin is also updated to version 2.44, otherwise Pipeline builds using untrusted (folder-scoped) libraries will not be able to resume after a Jenkins controller restart.
