---
layout: simplepage
title: Jenkins Security Advisory 2018-02-14
section: security
kind: core
---

This advisory announces multiple vulnerabilities in Jenkins.

== Description

=== Improperly secured form validation for proxy configuration allowed Server-Side Request Forgery
*SECURITY-506 / CVE pending*

The form validation for the proxy configuration form did not check the permission of the user accessing it, allowing anyone with Overall/Read access to Jenkins to cause Jenkins to send a GET request to a specified URL, optionally with a specified proxy configuration.

If that request's HTTP response code indicates success, the form validation is returning a generic success message, otherwise the HTTP status code is returned.
It was not possible to reuse an existing proxy configuration to send those requests; that configuration had to be provided by the attacker.

The form validation now properly requires the Overall/Administer permission.


=== Path traversal vulnerability allows access to files outside plugin resources
*SECURITY-705 / CVE-2018-6356*

Jenkins did not properly prevent specifying relative paths that escape a base directory for URLs accessing plugin resource files.
This allowed users with Overall/Read permission to download files from the Jenkins master they should not have access to.

On Windows, any file accessible to the Jenkins master process could be downloaded.
On other operating systems, any file within the Jenkins home directory accessible to the Jenkins master process could be downloaded.

Jenkins now prevents specifying paths containing `..` and other character sequences that could be used to access files outside the plugins resource directory.


=== Improper input validation allows unintended access to plugin resource files on case-insensitive file systems
*SECURITY-717 / CVE pending*

Jenkins did not take into account case-insensitive file systems when preventing access to plugin resource files that should not be accessible.
This allowed users with Overall/Read permission to download plugin resource files in +META-INF+ and +WEB-INF+ directories, such as the plugins' JAR files, which could contain hardcoded secrets.

This was caused by an incomplete fix to link:../2014-10-01/#SECURITY-155[SECURITY-155].



== Severity

* SECURITY-506: link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N[medium]
* SECURITY-705: link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:N/A:N[medium]
* SECURITY-717: link:http://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N[medium]

== Affected versions

* All Jenkins main line releases up to and including 2.106
* All Jenkins LTS releases up to and including 2.89.3


== Fix

* Jenkins main line users should update to 2.107
* Jenkins LTS users should update to 2.89.4

These versions include fixes to all the vulnerabilities described above.
All prior versions are affected by these vulnerabilities unless otherwise indicated.



== Credit

The Jenkins project would like to thank the reporters for discovering and link:/security/#reporting-vulnerabilities[reporting] these vulnerabilities:

* *Daniel Beck, CloudBees, Inc.* for SECURITY-506 and SECURITY-717
* *Kapil Kulkarni* for SECURITY-705

== Other Resources

* link:/blog/2017/02/14/security-update/[Announcement blog post]

