---
layout: advisory
title: Jenkins Security Advisory 2018-01-22
section: security
kind: plugins
issues:
- id: SECURITY-507
  reporter: Oleg Nenashev, CloudBees, Inc.
  cvss:
    severity: low
    vector: CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:N/I:L/A:N
  plugins:
    - name: translation
      fixed: 1.16
      previous: 1.15
- id: SECURITY-607
  reporter: Jesse Glick, CloudBees, Inc.
  cvss:
    severity: medium
    vector: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N
  plugins:
    - name: release
      fixed: 2.10
      previous: 2.9
- id: SECURITY-655
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: pmd
      fixed: 1.8
      previous: 1.7
- id: SECURITY-656
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: checkstyle
      fixed: 3.50
      previous: 3.49
- id: SECURITY-657
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: dry
      fixed: 2.50
      previous: 2.49
- id: SECURITY-658
  reporter: Adith Sudhakar
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: findbugs
      fixed: 4.72
      previous: 4.71
- id: SECURITY-695
  cvss:
    severity: medium
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  plugins:
    - name: warnings
      fixed: 4.65
      previous: 4.64
- id: SECURITY-694
  cvss:
    severity: medium
    vector: CVSS:3.0/AV:N/AC:L/PR:H/UI:R/S:C/C:L/I:L/A:N
  plugins:
    - name: ant
      fixed: 1.8
      previous: 1.7
- id: SECURITY-675
  cvss:
    severity: high
    vector: CVSS:3.0/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:L/A:L
  reporter: Jesse Glick, CloudBees, Inc.
  plugins:
    - name: workflow-durable-task-step
      fixed: 2.18
      previous: 2.17
---

== Description


=== XXE vulnerabilities in multiple static analysis plugins

* *SECURITY-655 / CVE-2018-1000008* (PMD)
* *SECURITY-656 / CVE-2018-1000009* (Checkstyle)
* *SECURITY-657 / CVE-2018-1000010* (DRY)
* *SECURITY-658 / CVE-2018-1000011* (FindBugs)
* *SECURITY-695 / CVE-2018-1000012* (Warnings)

Multiple plugins based on plugin:analysis-core[Static Analysis Utilities] plugin are affected by an XML External Entity (XXE) processing vulnerability.
This allows attacker to configure build processes such that one of these plugins parses a maliciously crafted file that uses external entities for extraction of secrets from the Jenkins master, server-side request forgery, or denial-of-service attacks.

External entity resolution has been disabled for these plugins.

=== CSRF vulnerability in Release plugin
*SECURITY-607 / CVE-2018-1000013*

Release plugin did not require form submissions to be submitted via POST, resulting in a CSRF vulnerability allowing attackers to trigger release builds.

Access to the form action URL now requires POST.

=== CSRF vulnerability in Translation Assistance plugin
*SECURITY-507 / CVE-2018-1000014*

Translation Assistance plugin did not require form submissions to be submitted via POST, resulting in a CSRF vulnerability allowing attackers to override localized strings displayed to all users on the current Jenkins instance if the victim is a Jenkins administrator.

Access to the form action URL now requires POST.

=== Incorrect permission checks in Pipeline: Nodes and Processes plugin allows executing builds on agents while lacking Computer/Build permission
*SECURITY-675 / CVE-2018-1000015*

On instances with plugin:authorize-project[Authorize Project plugin], the authentication associated with a build may lack the Computer/Build permission on some agents.
This did not prevent the execution of `node` blocks on those agents due to incorrect permissions checks in Pipeline: Nodes and Processes plugin.

Build permissions on agents are now properly enforced for `node` steps.

=== XSS vulnerability in job configuration forms in Ant plugin
*SECURITY-624 and SECURITY-694*

Ant plugin failed to escape tool names it shows on job configuration screens, resulting in a cross-site scripting (XSS) vulnerability that is exploitable only by Jenkins administrators.

This is the same vulnerability that was announced without a fix on link:/security/advisory/2017-12-05/[2017-12-05].
Contrary to what we wrote in that security advisory, Ant Plugin shows both the JDK and Ant tools on the configuration screen, and the vulnerability in Ant plugin was responsible for both problems we confirmed in the previous advisory.

Ant plugin now correctly escapes tool names shown on the job configuration screen.
