---
layout: gsocproject
title: "Conventional Commits plugin for Jenkins"
goal: "Automatically determine the next semantic version for a repository"
category: Plugins
year: 2021
sig: cloud-native
tags:
- gsoc2021
- cloudnative
status: "Completed"
student: adi10hero
mentors:
- "garethjevans"
- "kwhetstone"
- "olblak"
- "dohbedoh"
links:
  gitter: "jenkinsci_conventional-commits-plugin:gitter.im"
  draft: https://docs.google.com/document/d/1E0FdxdXP1JZb88-sDqmilmz2gJ0qp4BANCTLlXJOaTQ/edit#
  idea: /projects/gsoc/2021/project-ideas/semantic-release-version
---

=== Background

As the CI/CD world is moving more towards automation and minimal human interaction, the ability to fully automate a release, including the determination of the "next" release version becomes desirable.

Semantic/Conventional commits is one way of programmatically understanding the changes made between releases 

For an existing project released at `1.0.0`, the following commit messages would bump the version as follows:

|===
|Commit Message|Next Version 

|`chore: improve logging`
|`1.0.1`
|`fix: minor bug fix`
|`1.0.1`
|`feat: add a new feature`
|`1.1.0`
|`BREAKING CHANGE: reimplement`
|`2.0.0`
|===

==== Project Details

The conventional commits plugin is a Jenkins plugin to automatically determine the next semantic version for a git repository using the Conventional Commits (C.C) system.

Taking in various sources of input, like the commit history of the repository, the latest tagged version, and the version information read from various configuration files of the project, the plugin outputs the next semantic version.

The plugin is best used in a Jenkins Pipeline Project.

For example:

```
pipeline {
    agent any

    environment {
        NEXT_VERSION = nextVersion()
    }

    stages {
        stage('Hello') {
            steps {
                echo "next version = ${NEXT_VERSION}"
            }
        }
    }
}
```

More examples for the Declarative and the Scripted Pipeline can be found in the project's link:https://github.com/jenkinsci/conventional-commits-plugin[README].

For more details please see the following Resources section.

=== Resources

  . Blog
  - link:/blog/2021/07/30/introducing-conventional-commits-plugin-for-jenkins[Mid-term report]
  . Demo
  - link:https://youtu.be/_D0hiA1Cgz8?t=3218[Mid-term demo]

=== Getting the Code

The code for Conventional Commits Plugin can be found link:https://github.com/jenkinsci/conventional-commits-plugin/[here on Github].
_Note: The project is under active development._

=== Roadmap 

The roadmap for the future can be found link:https://github.com/jenkinsci/conventional-commits-plugin/projects/1[here].

=== References

* link:https://semver.org/[Semantic Versioning]
* link:https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits]
* link:https://github.com/jenkins-x-plugins/jx-release-version[JX Release Version]
