---
layout: simplepage
title: "docker-workflow"
---
:doctitle: docker-workflow
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== docker-workflow

=== +dockerFingerprintFrom+: Record trace of a Docker image used in FROM
====
Normally used implicitly by method calls on the docker global variable.
    Records the fact that a Docker image was built from another.
====
+dockerfile+::
+
Workspace-relative path of a Dockerfile which will be parsed for its FROM instruction.
*Type:* String


+image+::
+
ID or tag of the image which was just built, like --tag of docker build.
*Type:* String


+toolName+ (optional)::
+
*Type:* String



=== +dockerFingerprintRun+: Record trace of a Docker image run in a container
====
Normally used implicitly by method calls on the docker global variable.
    Records the fact that a Docker image was used by this build.
====
+containerId+::
+
*Type:* String


+toolName+ (optional)::
+
*Type:* String



=== +withDockerContainer+: Run build steps inside a Docker container
====
Normally used implicitly by method calls on the docker global variable.
    Takes an image ID or symbolic name which must already have been pulled locally
    and starts a container based on that image.
    Runs all nested sh steps inside that container.
    The workspace is mounted read-write into the container.
====
+image+::
+
*Type:* String


+args+ (optional)::
+
Any other arguments to pass to docker run.
*Type:* String


+toolName+ (optional)::
+
*Type:* String



