---
layout: simplepage
title: "hipchat"
---
:doctitle: hipchat
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== hipchat

=== +hipchatSend+: Send HipChat Message
====
Simple step for sending a HipChat message to designated room.
    Use the advanced settings to override the HipChat Plugin global configuration to include: HipChat Server, API Token, API Version (1 or 2) and Send As (v1 API only).
    Please see the HipChat Plugin global configuration for more details on the fields.

    Usage Example:
    
        hipchatSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (Open)"
====
+message+::
+
REQUIRED The message body
    Valid length range: 1 - 10000.
    Message may include global variables, for example environment and currentBuild variables:
    
        hipchatSend "${env.JOB_NAME} ${env.BUILD_NUMBER} status: ${currentBuild.result} (Open)"

        *Type:* String


+color+ (optional)::
+
OPTIONAL Background color for message.
    Valid values: YELLOW, GREEN, RED, PURPLE, GRAY, RANDOM.
    Defaults to 'GRAY'.
    hipchatSend color: "YELLOW", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
+
*Values:*

* +YELLOW+
* +GREEN+
* +RED+
* +PURPLE+
* +GRAY+
* +RANDOM+


+failOnError+ (optional)::
+
If set to true, then the step will abort the Workflow run as a failure if there is an error sending message.
    hipchatSend failOnError: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* boolean


+notify+ (optional)::
+
OPTIONAL Whether this message should trigger a user notification (change the tab color, play a sound, notify mobile phones, etc). Each recipient's notification preferences are taken into account.
    Defaults to false.
    hipchatSend notify: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* boolean


+room+ (optional)::
+
Allows overriding the HipChat Plugin default room.
    hipchatSend room: "room-name", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* String


+sendAs+ (optional)::
+
Allows overriding the HipChat Plugin default Send As value (v1 API only).
*Type:* String


+server+ (optional)::
+
Allows overriding the HipChat Plugin default HipChat Server.
*Type:* String


+textFormat+ (optional)::
+
Enable this setting to send the notification in text format.
*Type:* boolean


+token+ (optional)::
+
Allows overriding the HipChat Plugin default API Token.
*Type:* String


+v2enabled+ (optional)::
+
Allows overriding the HipChat Plugin default API Version to use - v1 or v2.
    hipchatSend Workflow step defaults to v2 API
*Type:* boolean



