---
layout: simplepage
title: "integrity-plugin"
---
:doctitle: integrity-plugin
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== integrity-plugin

=== +siaddprojectlabel+: Integrity SCM Label
+serverConfig+::
+
*Type:* String


+checkpointLabel+ (optional)::
+
A valid Integrity Checkpoint label string.  No groovy pre-processing is applied.
*Type:* String


+configPath+ (optional)::
+
*Type:* String


+password+ (optional)::
+
*Type:* String


+userName+ (optional)::
+
*Type:* String



=== +sicheckpoint+: Integrity SCM Checkpoint
+serverConfig+::
+
*Type:* String


+checkpointDesc+ (optional)::
+
*Type:* String


+checkpointLabel+ (optional)::
+
A valid Integrity Checkpoint label string.  No groovy pre-processing is applied.
*Type:* String


+configPath+ (optional)::
+
*Type:* String


+password+ (optional)::
+
*Type:* String


+userName+ (optional)::
+
*Type:* String



=== +sici+: Integrity SCM Checkin
+serverConfig+::
+
*Type:* String


+configPath+ (optional)::
+
*Type:* String


+excludes+ (optional)::
+
Ant-style filter for an excludes pattern.  Example: **/*.class
*Type:* String


+includes+ (optional)::
+
Ant-style filter for an includes pattern.  Example: **/*.java
*Type:* String


+itemID+ (optional)::
+
Integrity Lifecycle Manager Item ID designation.  Acceptable values include:
	&nbsp;&nbsp;:none    // Indicates no change packages are used for check in
	&nbsp;&nbsp;:bypass  // Assumes that the user has administrative privileges to bypass change package policies configured for the Integrity Project
	&nbsp;&nbsp;0        // Same as :none above
	&nbsp;&nbsp;12345    // An actual valid Integrity Item ID that the plugin will use to create a change package
*Type:* String


+password+ (optional)::
+
*Type:* String


+userName+ (optional)::
+
*Type:* String



