---
layout: simplepage
title: "openshift-pipeline"
---
:doctitle: openshift-pipeline
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== openshift-pipeline

=== +openShiftBuild+: Trigger OpenShift Build
+bldCfg+::
+
The name of the BuildConfig to trigger
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+buildName+ (optional)::
+
Specify the name of a build which should be re-run
*Type:* String


+checkForTriggeredDeployments+ (optional)::
+
Verify whether any deployments triggered by this build's output fired
*Type:* String


+commitID+ (optional)::
+
Specify the commit hash the build should be run from
*Type:* String


+namespace+ (optional)::
+
The name of the project the BuildConfig is stored in
*Type:* String


+showBuildLogs+ (optional)::
+
Pipe the build logs from OpenShift to the Jenkins console
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String


+waitTime+ (optional)::
+
Build wait time
*Type:* String




=== +openShiftCreateResource+: Create OpenShift Resource(s)
+jsonyaml+::
+
The JSON or YAML that defines the OpenShift resource(s) to create
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project to create the resources in
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String




=== +openShiftDeleteResourceByJsonYaml+: Delete OpenShift Resource(s) from JSON/YAML
+jsonyaml+::
+
The JSON or YAML that defines the OpenShift resource(s) to delete
*Type:* String


+apiURL+ (optional)::
+
The JSON or YAML that defines the OpenShift resource(s) to delete
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project to delete the resources from
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String




=== +openShiftDeleteResourceByKey+: Delete OpenShift Resource(s) by Key
+types+::
+
The type(s) of OpenShift resource(s) to delete
*Type:* String


+keys+::
+
The key(s) of the OpenShift resource(s) to delete
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project to delete the resources from
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String




=== +openShiftDeleteResourceByLabels+: Delete OpenShift Resource(s) using Labels
+types+::
+
The type(s) of OpenShift resource(s) to delete
*Type:* String


+keys+::
+
The key(s) of the OpenShift resource(s) to delete
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project to delete the resources from
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String




=== +openShiftDeploy+: Trigger OpenShift Deployment
+depCfg+::
+
The name of the DeploymentConfig to trigger a deployment for
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project the DeploymentConfig is stored in
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String


+waitTime+ (optional)::
+
*Type:* String




=== +openShiftScale+: Scale OpenShift Deployment
+depCfg+::
+
The name of the DeploymentConfig to scale
*Type:* String


+replicaCount+::
+
The number of replicas to scale the deployment to
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project the DeploymentConfig is stored in
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String


+verifyReplicaCount+ (optional)::
+
Verify whether the specified number of replicas are up
*Type:* String


+waitTime+ (optional)::
+
*Type:* String




=== +openShiftTag+: Tag OpenShift Image
+srcStream+::
+
The name of the ImageStream for the current image tag.
*Type:* String


+srcTag+::
+
The name of the current image tag or actual image ID.
*Type:* String


+destStream+::
+
The ImageStream for the new tag.
*Type:* String


+destTag+::
+
The name of the new image tag.
*Type:* String


+alias+ (optional)::
+
Update destination tag whenever the source tag changes.
*Type:* String


+apiURL+ (optional)::
+
The name of the project to host the destinationStream:destinationTag.
*Type:* String


+authToken+ (optional)::
+
The authorization token for the default service account of the project for the current tag
*Type:* String


+destinationAuthToken+ (optional)::
+
The authorization token for the default service account of the project for the new tag (only needed if the new tag is targeted for a different project than the project containing the current tag)
*Type:* String


+destinationNamespace+ (optional)::
+
The name of the project for the new image tag.
*Type:* String


+namespace+ (optional)::
+
The name of the project for the current image tag.
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in.
*Type:* String




=== +openShiftVerifyBuild+: Verify OpenShift Build
+bldCfg+::
+
The name of the BuildConfig to verify
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+checkForTriggeredDeployments+ (optional)::
+
Verify whether any deployments triggered by this build's output fired
*Type:* String


+namespace+ (optional)::
+
The name of the project the BuildConfig is stored in
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String


+waitTime+ (optional)::
+
*Type:* String




=== +openShiftVerifyDeployment+: Verify OpenShift Deployment
+depCfg+::
+
The name of the DeploymentConfig to validate
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project the DeploymentConfig is stored in
*Type:* String


+replicaCount+ (optional)::
+
The number of replicas you expect the deployment to scale to
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String


+verifyReplicaCount+ (optional)::
+
erify whether the specified number of replicas are up
*Type:* String


+waitTime+ (optional)::
+
*Type:* String




=== +openShiftVerifyService+: Verify OpenShift Service
+svcName+::
+
The name of the Service to verify
*Type:* String


+apiURL+ (optional)::
+
URL of the OpenShift api endpoint
*Type:* String


+authToken+ (optional)::
+
The authorization token for interacting with OpenShift
*Type:* String


+namespace+ (optional)::
+
The name of the project the DeploymentConfig is stored in
*Type:* String


+retryCount+ (optional)::
+
*Type:* String


+verbose+ (optional)::
+
Allow for verbose logging during this build step plug-in
*Type:* String




