---
layout: simplepage
title: "pipeline-input-step"
---
:doctitle: pipeline-input-step
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== pipeline-input-step

=== +input+: Wait for interactive input
====
This step pauses Pipeline execution and allows the user to interact and control the flow of the build.
Only a basic "process" or "abort" option is provided in the stage view.


You can optionally request information back, hence the name of the step. 
The parameter entry screen can be accessed via a link at the bottom of the build console log or
via link in the sidebar for a build.
====
+message+::
+
This parameter gives a prompt which will be shown to a human:
        Ready to go?
    Proceed or Abort
    


If you click "Proceed" the build will proceed to the next step, if you click "Abort" the build will be aborted.
*Type:* String


+id+ (optional)::
+
Every input step has an unique ID. It is used in the generated URL to proceed or abort.


A specific ID could be used, for example, to mechanically respond to the input from some external process/tool.
*Type:* String


+ok+ (optional)::
+
*Type:* String


+parameters+ (optional)::
+
Request that the submitter specify one or more parameter values when approving.
If just one parameter is listed, its value will become the value of the input step.
If multiple parameters are listed, the return value will be a map keyed by the parameter names.
If parameters are not requested, the step returns nothing if approved.


On the parameter entry screen you are able to enter values for parameters that are defined in this field.
*Array/List*
Nested Choice of Objects

+$class: 'BooleanParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* boolean


+description+:::
+
*Type:* String


+$class: 'ChoiceParameterDefinition'+

+name+:::
+
*Type:* String


+choices+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'FileParameterDefinition'+

+name+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'PasswordParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'RunParameterDefinition'+

+name+:::
+
*Type:* String


+projectName+:::
+
*Type:* String


+description+:::
+
*Type:* String


+filter+:::
+
*Values:*

* +ALL+
* +STABLE+
* +SUCCESSFUL+
* +COMPLETED+


+$class: 'StringParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'TextParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String




+submitter+ (optional)::
+
User ID or external group name of person or people permitted to respond to the input.
*Type:* String




