---
layout: simplepage
title: "pipeline-build-step"
---
:doctitle: pipeline-build-step
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== pipeline-build-step

=== +build+: Build a job
====
Triggers a new build for a given job.
====
+job+::
+
Name of a downstream job to build.
May be another Pipeline job, but more commonly a freestyle or other project.
Use a simple name if the job is in the same folder as this upstream Pipeline job;
otherwise can use relative paths like ../sister-folder/downstream
or absolute paths like /top-level-folder/nested-folder/downstream.
*Type:* String


+parameters+ (optional)::
+
*Array/List*
Nested Choice of Objects

+$class: 'BooleanParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* boolean


+$class: 'FileParameterValue'+

+name+:::
+
*Type:* String


+file+:::
+
Nested Choice of Objects


+$class: 'PasswordParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'RunParameterValue'+

+name+:::
+
*Type:* String


+runId+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'StringParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String


+$class: 'TextParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String




+propagate+ (optional)::
+
If set, then if the downstream build is anything but successful (blue ball), this step fails.
If disabled, then this step succeeds even if the downstream build is unstable, failed, etc.;
use the result property of the return value as needed.
*Type:* boolean


+quietPeriod+ (optional)::
+
Optional alternate quiet period (in seconds) before building.
If unset, defaults to the quiet period defined by the downstream project
(or finally to the system-wide default quiet period).
*Type:* int


+wait+ (optional)::
+
You may ask that this Pipeline build wait for completion of the downstream build.
In that case the return value of the step is an object on which you can obtain the following read-only properties:
so you can inspect its result and so on.


    number
    result (typically SUCCESS, UNSTABLE, or FAILED)
    displayName
    description
    id
    timeInMillis
    startTimeInMillis
    duration
    building
    inProgress
    previousBuild (another similar object)
    nextBuild
    absoluteUrl


For a non-Pipeline downstream build, the buildVariables property offers access to a map of defined build variables.
For a Pipeline downstream build, this property gives access to any variables set globally on env.


Administrator-approved scripts outside the sandbox can use the rawBuild property to get access to a hudson.model.Run with further APIs.
You will generally need to do so inside a method marked @NonCPS to avoid storing intermediate values.


If you do not wait, this step succeeds so long as the downstream build can be added to the queue (it will not even have been started).
In that case there is currently no return value.
*Type:* boolean




