---
layout: simplepage
title: "slack"
---
:doctitle: slack
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== slack

=== +slackSend+: Send Slack Message
====
Simple step for sending a Slack message to specified channel.
Use the advanced settings to override the Slack Plugin global configuration to include: token and channel.
Please see the Slack Plugin global configuration for more details on the fields.

Usage Example:
    
        slackSend "Build Started - ${env.JOB_NAME} ${env.BUILD_NUMBER}  ()"
====
+message+::
+
This is the main text in a message attachment, and can contain standard message markup.
The content will automatically collapse if it contains 700+ characters or 5+ linebreaks, and will display a "Show more..." link to expand the content.
Message may include global variables, for example environment and currentBuild variables:
    
        slackSend "started ${env.JOB_NAME} ${env.BUILD_NUMBER} ()"
*Type:* String


+channel+ (optional)::
+
Allows overriding the Slack Plugin channel specified in the global configuration.
    slackSend channel: "#channel-name", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* String


+color+ (optional)::
+
An optional value that can either be one of good, warning, danger, or any hex color code (eg. #439FE0).
This value is used to color the border along the left side of the message attachment.
slackSend color: "#439FE0", message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* String


+failOnError+ (optional)::
+
If set to true, then the step will abort the Workflow run if there is an error sending message.
    hipchatSend failOnError: true, message: "Build Started: ${env.JOB_NAME} ${env.BUILD_NUMBER}"
*Type:* boolean


+teamDomain+ (optional)::
+
Allows overriding the Slack Plugin Integration Team Domain specified in the global configuration.
*Type:* String


+token+ (optional)::
+
Allows overriding the Slack Plugin Integration Token specified in the global configuration.
*Type:* String




