---
layout: simplepage
title: "workflow-multibranch"
---
:doctitle: workflow-multibranch
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== workflow-multibranch

=== +properties+: Set job properties
====
Updates the properties of the job which runs this step.
    Mainly useful from multibranch Pipelines, so that Jenkinsfile itself can encode what would otherwise be static job configuration.
====
+properties+::
+
*Array/List*
Nested Choice of Objects

+$class: 'BuildDiscarderProperty'+
====
This controls the disk consumption of Jenkins by managing how long you'd like to keep
  records of the builds (such as console output, build artifacts, and so on.)
  Jenkins offers two criteria:

  
    
      Driven by age. You can have Jenkins delete a record if it reaches a certain age
      (for example, 7 days old.)
    
      Driven by number. You can have Jenkins make sure that it only maintains up to
      N build records. If a new build is started, the oldest record will
      be simply removed.
  

Jenkins also allows you to mark an individual build as 'Keep this log forever', to
exclude certain important builds from being discarded automatically.
The last stable and last successful build are always kept as well.
====
+strategy+:::
+
Nested Choice of Objects

+$class: 'LogRotator'+
+daysToKeepStr+::::
+
*Type:* String


+numToKeepStr+::::
+
*Type:* String


+artifactDaysToKeepStr+::::
+
*Type:* String


+artifactNumToKeepStr+::::
+
*Type:* String




+$class: 'ParametersDefinitionProperty'+
====
When you are using Jenkins for various automations, it's sometimes convenient
    to be able to "parameterize" a build, by requiring a set of user inputs to
    be made available to the build process. For example, you might be setting up
    an on-demand test job, where the user can submit a zip file of the binaries to be tested.

    
This section configures what parameters your build takes. Parameters are distinguished
by their names, and so you can have multiple parameters provided that they have different names.


See the Wiki topic
for more discussions about this feature.
====
+parameterDefinitions+:::
+
*Array/List*
Nested Choice of Objects

+$class: 'BooleanParameterDefinition'+

+name+::::
+
*Type:* String


+defaultValue+::::
+
*Type:* boolean


+description+::::
+
*Type:* String


+$class: 'ChoiceParameterDefinition'+

+name+::::
+
*Type:* String


+choices+::::
+
*Type:* String


+description+::::
+
*Type:* String


+$class: 'FileParameterDefinition'+

+name+::::
+
*Type:* String


+description+::::
+
*Type:* String


+$class: 'PasswordParameterDefinition'+

+name+::::
+
*Type:* String


+defaultValue+::::
+
*Type:* String


+description+::::
+
*Type:* String


+$class: 'RunParameterDefinition'+

+name+::::
+
*Type:* String


+projectName+::::
+
*Type:* String


+description+::::
+
*Type:* String


+filter+::::
+
*Values:*

* +ALL+
* +STABLE+
* +SUCCESSFUL+
* +COMPLETED+


+$class: 'StringParameterDefinition'+

+name+::::
+
*Type:* String


+defaultValue+::::
+
*Type:* String


+description+::::
+
*Type:* String


+$class: 'TextParameterDefinition'+

+name+::::
+
*Type:* String


+defaultValue+::::
+
*Type:* String


+description+::::
+
*Type:* String







=== +readTrusted+: Read trusted file from SCM
====
From a multibranch Pipeline project, reads a file from the associated SCM and returns its contents. Unlike the readFile step, no workspace is required. If the associated branch is not trusted, yet the file has been modified from its trusted version, an error is thrown. Thus this step is useful for loading scripts or other files which might otherwise be used to run malicious commands. 
====
+path+::
+
Relative (slash-separated) path to the file from the SCM root. Thus readTrusted 'subdir/file' is similar to node {checkout scm; readFile 'subdir/file'}
*Type:* String