---
layout: simplepage
title: "workflow-durable-task-step"
---
:doctitle: workflow-durable-task-step
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== workflow-durable-task-step

=== +bat+: Windows Batch Script
====
Executes a Batch script. Multiple lines allowed.
====
+script+::
+
*Type:* String




=== +node+: Allocate node
====
Allocates an executor on a node (typically a slave) and runs further code in the context of a workspace on that slave.
====
+label+::
+
Computer name, label name, or any other label expression like linux && 64bit to restrict where this step builds.
May be left blank, in which case any available executor is taken.

Valid Operators

The following operators are supported, in the order of precedence.
    
        (expr)
        parenthesis

        !expr
        negation

        expr&amp;&amp;expr
        
            and
        

        expr||expr
        
            or
        

        a -> b
        
            "implies" operator. Equivalent to !a|b.
            For example, windows->x64 could be thought of as "if run on a Windows slave,
            that slave must be 64bit." It still allows Jenkins to run this build on linux.
        

        a &lt;-> b
        
            "if and only if" operator. Equivalent to a&amp;&amp;b || !a&amp;&amp;!b.
            For example, windows&lt;->sfbay could be thought of as "if run on a Windows slave,
            that slave must be in the SF bay area, but if not on Windows, it must not be in the bay area."
        
    
    
All operators are left-associative (i.e., a->b->c &lt;-> (a->b)->c )
An expression can contain whitespace for better readability, and it'll be ignored.


Label names or slave names can be quoted if they contain unsafe characters. For example,
"jenkins-solaris (Solaris)" || "Windows 2008"
*Type:* String




=== +sh+: Shell Script
====
Runs a Bourne shell script, typically on a Unix node. Multiple lines are accepted.
    

An interpreter selector may be used, for example: #!/usr/bin/perl


Otherwise the system default shell will be run, using the -xe flags
(you can specify set +e and/or set +x to disable those).
====
+script+::
+
*Type:* String




=== +ws+: Allocate workspace
====
Allocates a workspace.
Note that a workspace is automatically allocated for you with the node step.
====
+dir+::
+
A workspace is automatically allocated for you with the node step,
or you can get an alternate workspace with this ws step,
but by default the location is chosen automatically.
(Something like SLAVE_ROOT/workspace/JOB_NAME@2.)


You can instead specify a path here and that workspace will be locked instead.
(The path may be relative to the slave root, or absolute.)


If concurrent builds ask for the same workspace, a directory with a suffix such as @2 may be locked instead.
Currently there is no option to wait to lock the exact directory requested;
if you need to enforce that behavior, you can either fail (error) when pwd indicates that you got a different directory,
or you may enforce serial execution of this part of the build by some other means such as stage name: '…', concurrency: 1.


If you do not care about locking, just use the dir step to change current directory.
*Type:* String




