---
layout: simplepage
title: "workflow-basic-steps"
---
:doctitle: workflow-basic-steps
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== workflow-basic-steps

=== +archive+: Archive artifacts
====
Archives build output artifacts for later use.
====
+includes+::
+
Include artifacts matching this Ant style pattern.
Use a comma separated list to add more than one expression.
*Type:* String


+excludes+ (optional)::
+
Exclude artifacts matching this Ant-style pattern.
Use a comma-separated list to add more than one expression.
*Type:* String



=== +deleteDir+: Recursively delete the current directory from the workspace
====
Recursively deletes the current directory and its contents.
    Symbolic links and junctions will not be followed but will be removed.
    To delete a specific directory of a workspace wrap the deleteDir
    step in a dir step.
====

=== +dir+: Change current directory
====
Change current directory. Any step inside the dir block will 
    use this directory as current and any relative path will use it as base path.
====
+path+::
+
*Type:* String



=== +echo+: Print Message
+message+::
+
*Type:* String



=== +error+: Error signal
====
Signals an error.
    Useful if you want to conditionally abort some part of your program.
    You can also just throw new Exception(),
    but this step will avoid printing a stack trace.
====
+message+::
+
*Type:* String



=== +fileExists+: Verify if file exists in workspace
====
Checks if the given file (as relative path to current directory) exists.
    Returns true | false.
====
+file+::
+
Relative (/-separated) path to file within a workspace to verify its existence.
*Type:* String



=== +isUnix+: Checks if running on a Unix-like node
====
Returns true if enclosing node is running on a Unix-like system (such as Linux or Mac OS X), false if Windows.
====

=== +mail+: Mail
====
Simple step for sending email.
====
+subject+::
+
Email subject line.
*Type:* String


+body+::
+
Email body.
*Type:* String


+bcc+ (optional)::
+
BCC email address list. Comma separated list of email addresses.
*Type:* String


+cc+ (optional)::
+
CC email address list. Comma separated list of email addresses.
*Type:* String


+charset+ (optional)::
+
Email body character encoding. Defaults to UTF-8
*Type:* String


+from+ (optional)::
+
From email address. Defaults to the admin address globally configured for the Jenkins instance.
*Type:* String


+mimeType+ (optional)::
+
Email body MIME type. Defaults to text/plain.
*Type:* String


+replyTo+ (optional)::
+
Reploy-To email address. Defaults to the admin address globally configured for the Jenkins instance.
*Type:* String


+to+ (optional)::
+
To email address list. Comma separated list of email addresses.
*Type:* String



=== +pwd+: Determine current directory
====
Returns the current directory path as a string.
====
+tmp+ (optional)::
+
If selected, return a temporary directory associated with the workspace rather than the workspace itself.
    This is an appropriate place to put temporary files which should not clutter a source checkout;
    local repositories or caches; etc.
*Type:* boolean



=== +readFile+: Read file from workspace
====
Reads a file from a relative path (with root in current directory, usually workspace) and returns its content as a plain string.
====
+file+::
+
Relative (/-separated) path to file within a workspace to read.
*Type:* String


+encoding+ (optional)::
+
*Type:* String



=== +retry+: Retry the body up to N times
====
Retry the block (up to N times) if any exception happens during its body execution.
====
+count+::
+
*Type:* int



=== +sleep+: Sleep
====
Simply pauses the Pipeline build until the given amount of time has expired.
    Equivalent to (on Unix) sh 'sleep …'.
    May be used to pause one branch of parallel while another proceeds.
====
+time+::
+
*Type:* int


+unit+ (optional)::
+
*Values:*

* +NANOSECONDS+
* +MICROSECONDS+
* +MILLISECONDS+
* +SECONDS+
* +MINUTES+
* +HOURS+
* +DAYS+



=== +step+: General Build Step
====
This is a special step that allows to call builders or post-build actions (as in freestyle or similar projects), in general "build steps".
    Just select the build step to call from the dropdown list and configure it as needed.
    
    
    Note that only Pipeline-compatible steps will be shown in the list.
====
+delegate+::
+
Nested Choice of Objects
+$class: 'ArtifactArchiver'+
====
Archives the build artifacts (for example, distribution zip files or jar files)
  so that they can be downloaded later.
  Archived files will be accessible from the Jenkins webpage.


Normally, Jenkins keeps artifacts for a build as long as a build log itself is kept,
but if you don't need old artifacts and would rather save disk space, you can do so.



Note that the Maven job type automatically archives any produced Maven artifacts.
Any artifacts configured here will be archived on top of that.
Automatic artifact archiving can be disabled under the advanced Maven options.
====
+artifacts+:::
+
You can use wildcards like 'module/dist/**/*.zip'.
   See 
   the includes attribute of Ant fileset for the exact format.
   The base directory is the workspace.
   You can only archive files that are located in your workspace.
*Type:* String


+allowEmptyArchive+ (optional):::
+
Normally, a build fails if archiving returns zero artifacts.
    This option allows the archiving process to return nothing without failing the build.
    Instead, the build will simply throw a warning.
*Type:* boolean


+caseSensitive+ (optional):::
+
Artifact archiver uses Ant org.apache.tools.ant.DirectoryScanner which by default is case sensitive.
    For instance, if the job produces *.hpi files, pattern "**/*.HPI" will fail to find them.
    This option can be used to disable case sensitivity. When it's unchecked, pattern "/**/*.HPI" will match any *.hpi files, or pattern "**/cAsEsEnSiTiVe.jar" will match a file called caseSensitive.jar.
*Type:* boolean


+defaultExcludes+ (optional):::
+
*Type:* boolean


+excludes+ (optional):::
+
Optionally specify the 'excludes' pattern,
  such as "foo/bar/**/*". A file that matches this mask will not be archived even if it matches the
  mask specified in 'files to archive' section.
*Type:* String


+fingerprint+ (optional):::
+
*Type:* boolean


+onlyIfSuccessful+ (optional):::
+
*Type:* boolean


+$class: 'Fingerprinter'+
====
Jenkins can record the 'fingerprint' of files (most often jar files) to keep track
  of where/when those files are produced and used. When you have inter-dependent
  projects on Jenkins, this allows you to quickly find out answers to questions like:

  
    
      I have foo.jar on my HDD but which build number of FOO did it come from?
    
    
      My BAR project depends on foo.jar from the FOO project.
    
    
      
        Which build of foo.jar is used in BAR #51?
      
      
        Which build of BAR contains my bug fix to foo.jar #32?
      
    
  

  
To use this feature, all of the involved projects (not just the project
in which a file is produced, but also the projects in which the file
is used) need to use this and record fingerprints.


See this document
for more details.
====
+targets+:::
+
Can use wildcards like module/dist/**/*.zip
    (see the @includes of Ant fileset for the exact format).
    The base directory is the workspace.
*Type:* String





=== +timeout+: Enforce time limit
====
Executes the code inside the block with a determined time out limit.
    If the time limit is reached, an exception is thrown, which leads in aborting 
    the build (unless it is catched and processed somehow).
====
+time+::
+
*Type:* int


+unit+ (optional)::
+
*Values:*
* +NANOSECONDS+
* +MICROSECONDS+
* +MILLISECONDS+
* +SECONDS+
* +MINUTES+
* +HOURS+
* +DAYS+



=== +tool+: Use a tool from a predefined Tool Installation
====
Binds a tool installation to a variable (the tool home directory is returned).
    Only tools already configured in Configure System are available here. If the original tool installer
    has the auto-provision feature, then the tool will be installed as required.
====
+name+::
+
*Type:* String


+type+ (optional)::
+
*Type:* String



=== +waitUntil+: Wait for condition
====
Runs its body repeatedly until it returns true.
    If it returns false, waits a while and tries again.
    (Subsequent failures will slow down the delay between attempts.)
    There is no limit to the number of retries,
    but if the body throws an error that is thrown up immediately.
====

=== +withEnv+: Set environment variables
====
Sets one or more environment variables within a block.
These are available to any external processes spawned within that scope.
For example:

----
    node {
      withEnv(['MYTOOL_HOME=/usr/local/mytool']) {
        sh '$MYTOOL_HOME/bin/start'
      }
    }
----

(Note that here we are using single quotes in Groovy, so the variable expansion is being done by the Bourne shell, not Jenkins.)
See the documentation for the env singleton for more information on environment variables.
====
+overrides+::
+
A list of environment variables to set, each in the form VARIABLE=value
    or VARIABLE= to unset variables otherwise defined.
    You may also use the syntax PATH+WHATEVER=/something
    to prepend /something to $PATH.
*Array/List*
*Type:* String



=== +wrap+: General Build Wrapper
====
This is a special step that allows to call build wrappers (also called "Environment Configuration" in freestyle or similar projects).
    Just select the wrapper to use from the dropdown list and configure it as needed. Everything inside the wrapper block is under its effect.
    
    
    Note that only Pipeline-compatible wrappers will be shown in the list.
====
+delegate+::
+
Nested Choice of Objects



=== +writeFile+: Write file to workspace
====
Write the given content to a named file in the current directory.
====
+file+::
+
*Type:* String


+text+::
+
*Type:* String


+encoding+ (optional)::
+
*Type:* String




=== +catchError+: Catch error and set build result
====
If the body throws an exception, mark the build as a failure, but nonetheless
    continue to execute the Pipeline from the statement following the catchError step.
    This is only necessary when using certain post-build actions (notifiers)
    originally defined for freestyle projects which pay attention to the result of the ongoing build.
----
node {
    catchError {
        sh 'might fail'
    }
    step([$class: 'Mailer', recipients: 'admin@somewhere'])
}
----

If the shell step fails, the Pipeline build’s status will be set to failed, so that the subsequent mail step will see that this build is failed.
In the case of the mail sender, this means that it will send mail.
(It may also send mail if this build succeeded but previous ones failed, and so on.)
Even in that case, this step can be replaced by the following idiom:

node {
    try {
        sh 'might fail'
    } catch (err) {
        echo "Caught: ${err}"
        currentBuild.result = 'FAILURE'
    }
    step([$class: 'Mailer', recipients: 'admin@somewhere'])
}

For all other cases, use plain try-catch(-finally) blocks:

----
node {
    sh './set-up.sh'
    try {
        sh 'might fail'
        echo 'Succeeded!'
    } catch (err) {
        echo "Failed: ${err}"
    } finally {
        sh './tear-down.sh'
    }
    echo 'Printed whether above succeeded or failed.'
}
// …and the pipeline as a whole succeeds
----

See this document for background.
====

=== +unarchive+: Copy archived artifacts into the workspace
+mapping+ (optional)::
+
Type: Map



