---
layout: simplepage
title: "workflow-support"
---
:doctitle: workflow-support
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== workflow-support

=== +build+: Build a job
====
Triggers a new build for a given job.
====
+job+::
+
Name of a downstream job to build.
    May be another Pipeline job, but more commonly a freestyle or other project.
    Use a simple name if the job is in the same folder as this upstream Pipeline job;
    otherwise can use relative paths like ../sister-folder/downstream
    or absolute paths like /top-level-folder/nested-folder/downstream.
*Type:* String


+parameters+ (optional)::
+
*Array/List*
Nested Choice of Objects

+$class: 'BooleanParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* boolean


+$class: 'FileParameterValue'+

+name+:::
+
*Type:* String


+file+:::
+
Nested Choice of Objects


+$class: 'PasswordParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'RunParameterValue'+

+name+:::
+
*Type:* String


+runId+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'StringParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String


+$class: 'TextParameterValue'+

+name+:::
+
*Type:* String


+value+:::
+
*Type:* String




+propagate+ (optional)::
+
If set, then if the downstream build is anything but successful (blue ball), this step fails.
    If disabled, then this step succeeds even if the downstream build is unstable, failed, etc.;
    use the result property of the return value as needed.
*Type:* boolean


+quietPeriod+ (optional)::
+
Optional alternate quiet period (in seconds) before building.
    If unset, defaults to the quiet period defined by the downstream project
    (or finally to the system-wide default quiet period).
*Type:* int


+wait+ (optional)::
+
You may ask that this Pipeline build wait for completion of the downstream build.
    In that case the return value of the step is an object on which you can obtain the following read-only properties:
    so you can inspect its result and so on.


    number
    result (typically SUCCESS, UNSTABLE, or FAILED)
    displayName
    description
    id
    timeInMillis
    startTimeInMillis
    duration
    building
    inProgress
    previousBuild (another similar object)
    nextBuild
    absoluteUrl


For a non-Pipeline downstream build, the buildVariables property offers access to a map of defined build variables.
For a Pipeline downstream build, this property gives access to any variables set globally on env.


Administrator-approved scripts outside the sandbox can use the rawBuild property to get access to a hudson.model.Run with further APIs.
You will generally need to do so inside a method marked @NonCPS to avoid storing intermediate values.


If you do not wait, this step succeeds so long as the downstream build can be added to the queue (it will not even have been started).
In that case there is currently no return value.

*Type:* boolean



=== +input+: Wait for interactive input
====
This step pauses Pipeline execution and allows the user to interact and control the flow of the build.
    Only a basic "process" or "abort" option is provided in the stage view.
    
    
You can optionally request information back, hence the name of the step. 
The parameter entry screen can be accessed via a link at the bottom of the build console log or
via link in the sidebar for a build.
====
+message+::
+
This parameter gives a prompt which will be shown to a human:
        Ready to go?
    Proceed or Abort
    


If you click "Proceed" the build will proceed to the next step, if you click "Abort" the build will be aborted.
*Type:* String


+id+ (optional)::
+
Every input step has an unique ID. It is used in the generated URL to proceed or abort.

A specific ID could be used, for example, to mechanically respond to the input from some external process/tool.
*Type:* String


+ok+ (optional)::
+
*Type:* String


+parameters+ (optional)::
+
Request that the submitter specify one or more parameter values when approving.
    If just one parameter is listed, its value will become the value of the input step.
    If multiple parameters are listed, the return value will be a map keyed by the parameter names.
    If parameters are not requested, the step returns nothing if approved.
+
On the parameter entry screen you are able to enter values for parameters that are defined in this field.

*Array/List*
Nested Choice of Objects

+$class: 'BooleanParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* boolean


+description+:::
+
*Type:* String


+$class: 'ChoiceParameterDefinition'+

+name+:::
+
*Type:* String


+choices+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'FileParameterDefinition'+

+name+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'PasswordParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'RunParameterDefinition'+

+name+:::
+
*Type:* String


+projectName+:::
+
*Type:* String


+description+:::
+
*Type:* String


+filter+:::
+
*Values:*

* +ALL+
* +STABLE+
* +SUCCESSFUL+
* +COMPLETED+


+$class: 'StringParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String


+$class: 'TextParameterDefinition'+

+name+:::
+
*Type:* String


+defaultValue+:::
+
*Type:* String


+description+:::
+
*Type:* String




+submitter+ (optional)::
+
User ID or external group name of person or people permitted to respond to the input.
*Type:* String



=== +node+: Allocate node
====
Allocates an executor on a node (typically a slave) and runs further code in the context of a workspace on that slave.
====
+label+::
+
Computer name, label name, or any other label expression like linux && 64bit to restrict where this step builds.
    May be left blank, in which case any available executor is taken.
*Type:* String



=== +stage+: Stage
====
By default, Pipeline builds can run concurrently. 
    The stage command lets you mark certain sections of a build as being constrained by limited concurrency.
    Newer builds are always given priority when entering such a throttled stage; older builds will simply exit early if 
    they are preëmpted.
====
+name+::
+
*Type:* String


+concurrency+ (optional)::
+
Concurrency level.
+
A concurrency of one is useful to let you lock a singleton resource, such as deployment to a single target server. 
Only one build will deploy at a given time: the newest which passed all previous stages
*Type:* int



=== +stash+: Stash some files to be used later in the build
====
Saves a set of files for use later in the same build, generally on another node/workspace.
    Stashed files are not otherwise available and are generally discarded at the end of the build.
====
+name+::
+
Name of a stash.
    Should be a simple identifier akin to a job name.
*Type:* String


+excludes+ (optional)::
+
Optional set of "Ant-style exclude patterns.
    Use a comma separated list to add more than one expression.
    If blank, no file will be excluded.
*Type:* String


+includes+ (optional)::
+
Optional set of "Ant-style include patterns.
    Use a comma separated list to add more than one expression.
    If blank, treated like \**: all files.
    The current working directory is the base directory for the saved files,
    which will later be restored in the same relative locations,
    so if you want to use a subdirectory wrap this in dir.

*Type:* String


+useDefaultExcludes+ (optional)::
+
If selected, use the default excludes from Ant - see
    here for the list.
*Type:* boolean



=== +unstash+: Restore files previously stashed
====
Restores a set of files previously stashed into the current workspace.
====
+name+::
+
Name of a previously saved stash.
*Type:* String



=== +ws+: Allocate workspace
====
Allocates a workspace.
    Note that a workspace is automatically allocated for you with the node step.
====
+dir+::
+
A workspace is automatically allocated for you with the node step,
    or you can get an alternate workspace with this ws step,
    but by default the location is chosen automatically.
    (Something like SLAVE_ROOT/workspace/JOB_NAME@2.)
+
You can instead specify a path here and that workspace will be locked instead.
(The path may be relative to the slave root, or absolute.)


If concurrent builds ask for the same workspace, a directory with a suffix such as @2 may be locked instead.
Currently there is no option to wait to lock the exact directory requested;
if you need to enforce that behavior, you can either fail (error) when pwd indicates that you got a different directory,
or you may enforce serial execution of this part of the build by some other means such as stage name: '…', concurrency: 1.


If you do not care about locking, just use the dir step to change current directory.

*Type:* String



