---
layout: simplepage
title: "workflow-scm-step"
---
:doctitle: workflow-scm-step
:notitle:
:description:
:author: 
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

== workflow-scm-step

=== +checkout+: General SCM
====
This is a special step that allows to run checkouts using any configuration
    options offered by any Pipeline-compatible SCM plugin.
    To use a concrete SCM implementations, just install the corresponding plugin 
    and check if it is shown in the list below.
    Then select the SCM to use from the dropdown list and configure it as needed.
    
    
Any other specific step to run checkouts (like svn or git)
are simplistic options of this step.
====
+scm+::
+
Nested Choice of Objects


+changelog+ (optional)::
+
*Type:* boolean


+poll+ (optional)::
+
*Type:* boolean



=== +git+: Git
====
Git step. It performs a clone from the specified repository.
    
    
Note that this step is shorthand for the generic SCM step:

    checkout([$class: 'GitSCM', branches: [[name: '*/master']], userRemoteConfigs: [[url: 'http://git-server/user/repository.git']]])

====
+url+::
+
*Type:* String


+branch+ (optional)::
+
*Type:* String


+changelog+ (optional)::
+
*Type:* boolean


+credentialsId+ (optional)::
+
*Type:* String


+poll+ (optional)::
+
*Type:* boolean



=== +svn+: Subversion
====
SVN step. It performs a checkout from the specified repository.
    
    
Note that this step is shorthand for the generic SCM step:

    checkout([$class: 'SubversionSCM', remote: 'http://sv-server/repository/trunk']]])
====
+url+::
+
*Type:* String


+changelog+ (optional)::
+
*Type:* boolean


+poll+ (optional)::
+
*Type:* boolean



