---
layout: post
title: "Depreciated ruby-runtime and associated plugins"
tags:
- ruby
- plugins
authors:
- halkeye
---
Approximately
https://github.com/jenkinsci/ruby-runtime-plugin/commit/d368b087fadb3282c9b537f0fa6d9a150b080c73[10
years ago, ruby-runtime was first released]. It was an experiment to let
plugins to be written in ruby but still get integrated into the main
java jenkins process.

Over the years though, the experiment has stopped being maintained, the
dozen or so plugins that use it, take a lot of user effort to make work.
Specifically the last few years have been really hard on the Jenkins
core developers, as they still have to maintain all the hacks and
processes to keep the ruby runtime barely working.

So in one month from now, May 15th, 2021, we will stop distributing
ruby-runtime and its
https://plugins.jenkins.io/ruby-runtime/#dependencies[associated
plugins] in the update center.

== What does this mean for you?

If your one of the few users who are using the following plugins. The
only change will come for new installs. Suspended plugins can stay
installed, but can not be newly installed without manually downloading
releases.

* https://plugins.jenkins.io/capitomcat/[Capitomcat]
* https://plugins.jenkins.io/chef/[Chef]
* https://plugins.jenkins.io/ci-skip/[Ci Skip]
* https://plugins.jenkins.io/commit-message-trigger-plugin/[Commit Message Trigger]
* https://plugins.jenkins.io/cucumber/[Cucumber]
* https://plugins.jenkins.io/devstack/[DevStack]
* https://plugins.jenkins.io/gitlab-hook/[Gitlab Hook]
* https://plugins.jenkins.io/ikachan/[Ikachan]
* https://plugins.jenkins.io/jenkinspider/[Jenkinspider]
* https://plugins.jenkins.io/mysql-job-databases/[MySQL Job Databases]
* https://plugins.jenkins.io/pathignore/[Pathignore]
* https://plugins.jenkins.io/perl/[Perl]
* https://plugins.jenkins.io/perl-smoke-test/[Perl Smoke Test]
* https://plugins.jenkins.io/rvm/[Rvm]
* https://plugins.jenkins.io/singleuseslave/[Single Use Slave]
* https://plugins.jenkins.io/travis-yml/[Travis YML]
* https://plugins.jenkins.io/yammer/[Yammer]
* https://plugins.jenkins.io/buddycloud/[buddycloud]
* https://plugins.jenkins.io/git-notes/[git-notes]
* https://plugins.jenkins.io/pry/[pry]
* https://plugins.jenkins.io/pyenv/[pyenv]
* https://plugins.jenkins.io/rbenv/[rbenv]

== Suggested Workarounds

=== Gitlab-hook

* Recommendation is to switch to gitlab and gitlab-branch-source, which
not only has new features, but doesn't have large unaddressed security
issues

=== rvm

=== pry

=== Cucumber

* Writer recommends using cucumber bundled with ruby app, and output in
a junit format, then using the junit plugin process the results
