---
layout: gsocprojectidea
title: "Manage jenkinsci GitHub permissions as code"
goal: "Automating the management of GitHub permissions for the jenkinsci organization"
category: Tools
year: 2024
status: published
sig: infra
skills:
- Java
- Groovy
- git
- Maven
- SnakeYAML
- Data extraction from GitHub repositories
- GitHub user and team management
mentors:
- "notmyfault"
- "krisstern"
links:
  emailThread: https://community.jenkins.io/t/gsoc-2024-project-idea-manage-jenkinsci-github-permissions-as-code/11186
  gitter: gsoc2024-rpu:matrix.org
  meetings: /projects/gsoc/#office-hours
---

=== Background

To manage artifactory permission, diverge between Jira and GitHub issues, and activate automatic releases, the jenkinsci organization uses a tool called https://github.com/jenkins-infra/repository-permissions-updater/[repository permission updater (RPU)].

Despite the name containing "repository permission", the RPU can't update or manage repository permission at all.
Currently, all team modifications are done manually by the hosting team.

The RPU is a critical component in the jenkinsci infrastructure and is used daily to onboard new plugins and update release permission.

=== Quick Start

The project aims to build on top of the existing RPU logic and manage GitHub teams and individual users (for legacy reasons, we strive to use teams only), defined as a list in the pre-existing YAML file, which every repository within the jenkinsci GitHub organization has.

Every YAML file within the RPU is expected to have a team defined with a list of users, where the RPU updates the team membership to match the list of users defined in the YAML file in the jenkinsci organization.

Initially, we need to copy all teams and users added to every repository of the jenkinsci GitHub organization and add them to the permission files in the RPU.

Hosting new plugins adds an entry automatically to the new YAML file.

=== Skills to Study and Improve

* Java
* Groovy
* git
* Maven
* SnakeYAML
* https://github.com/hub4j/github-api[GitHub API]
* Data extraction from GitHub repositories
* GitHub user and team management

=== Project Difficulty Level

Beginner

=== Project Size

175 hours

=== Expected outcomes

A functional "as-code" version of the RPU to manage GitHub teams and users (for legacy reasons) within the jenkinsci organization.
If a filed pull request has been merged, the corresponding team should be updated to match the list of users defined in the YAML file.
If needed, an invitation should be sent to the user to join the team.
