---
layout: gsocprojectidea
title: "Building iOS Apps with Jenkins"
goal: "Describe best practices and provide architectural templates for building iOS applications with Jenkins"
category: Tools
year: 2024
status: draft
sig: platform
skills:
- Java
- YAML
- iOS development
- Command line tools
- Package management tool theory
mentors:
- "krisstern"
- "gounthar"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-ios-apps-with-jenkins/4799
---

=== Background

Topics such as _how to proceed_, _what are the successful patterns_, and _what are the pitfalls_ are poorly documented. 
It very often requires potential users and Jenkins Administrators to "reinvent the wheel".

The project idea is to have a clear status of what can be done with Jenkins for iOS app builds now.
There are only a few articles here and there about iOS.


=== Skills to Study and Improve

- Jenkins technical architecture
- iOS application development
- CI principle and practice


=== Project Difficulty Level

Beginner to Intermediate


=== Expected outcomes

* A working iOS application CI build with Jenkins from a public GitHub public repository (Proof of Concept).
* A proposed architecture that would work for almost anyone (so Docker whenever it’s possible, or virtual machines) using a public GitHub repo.
* The required additional tooling to make it all work.
* At least one blog post explaining how to replicate the POC, preferably a full documentation to be integrated in Jenkins.io


Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase.
