---
layout: gsocprojectidea
title: "Building Android Apps with Jenkins"
goal: "Describe best practices and provide architectural templates for building Android applications with Jenkins"
category: Tools
year: 2024
status: draft
sig: platform
skills:
- Java
- YAML
- Android development
- Command line tools
- Package management tool theory
mentors:
- "gounthar"
links:
    emailThread: https://community.jenkins.io/t/gsoc-2023-project-idea-building-android-apps-with-jenkins/4798
---
//   gitter: "jenkinsci_plugin-installation-manager-cli-tool:gitter.im"
//   draft: https://docs.google.com/document/d/1s-dLUfU1OK-88bCj-GKaNuFfJQlQNLTWtacKkVMVmHc

=== Background

Applying CI principles when building IOS applications brings its own challenges, different from those of more classical applications.
Topics such as _how to proceed_, _what are the successful patterns_, and _what are the pitfalls_ are poorly documented. 
It very often requires potential users and Jenkins Administrators to "reinvent the wheel".

Some experiments are link:https://github.com/gounthar/MyFirstAndroidAppBuiltByJenkins[available] and were link:https://www.youtube.com/watch?v=fmTdT4Y-uCw&ab_channel=JeanQuinze[presented publicly].

The proof of concept could be docker-compose based.
It would work under Windows, Linux, Vagrant, macOS (x86 and ARM), and _mostly_ on Gitpod.
It should be easily transposable to a production environment.
The demo/proof-of-concept would be composed of a Jenkins controller (configured with JCasc), an Android agent, a generic Docker agent, an Android emulator, and an Android device farm (link:https://github.com/DeviceFarmer[STF]).

The idea is to have a more precise status of what can be done now with Jenkins.
We could then amend the existing link:/solutions/android/[Android documentation] and describe architectures for:

* Standalone Android projects
* Android apps building farms
* Android distro building (customized AOSP)

//
// === Quick Start
// TBD
//
=== Skills to Study and Improve

- Jenkins technical architecture
- Android application development
- CI principle and practice
- Docker

=== Project Difficulty Level

Beginner to Intermediate

=== Project Size

175 hours

=== Expected outcomes

Details to be clarified interactively, together with the mentors, during the Contributor Application drafting phase. 

// === Newbie Friendly Issues
