---
layout: gsocprojectidea
title: "CloudEvents plugin for Jenkins"
goal: "Build a plugin able to listen to and emit CloudEvents from Jenkins"
category: Plugins
year: 2024
status: published
sig: cloud-native
skills:
- Java
- Go
- CloudEvents SDK
- Networking
mentors:
- "krisstern"
- "berviantoleo"
- "iamrajiv"
links:
  draft: https://docs.google.com/document/d/1xsI6nkEPzXId5npXLrjz3Ydj7jx9Rf8g7SWnTldpeQc/edit#heading=h.f09or9ek462l
  meetings: /projects/gsoc/#office-hours
---

=== Background
As the CI/CD world is moving more towards interoperability between multiple platforms, Jenkins should also be compatible with the same interoperability standards. Some of these standards with respect to communication between different CI/CD platforms are put forth by the CloudEvents specification. This spec outlines the structure of CloudEvents, which are produced or consumed by entities which support it, hence making those entities compatible with other CI/CD platforms which also support them allowing them to work together.

Jenkins currently does not support CloudEvents, making it hard for users to use it with other platforms which support them.


==== Project Details
This project idea proposes to implement a Jenkins plugin which extends the Jenkins to make CloudEvents both discoverable and subscribable. Users should be able to set a global configuration to allow users to subscribe and discover CloudEvents.

The project requires the student to start with plugin development from scratch and then work with understanding how to use the CloudEvents Java SDK to create and read events.

In the beginning, the student can work on understanding the Jenkins plugin development by writing code for creating a simple Build Step which creates a CloudEvent, and from there we can move to the GlobalPluginConfiguration on how Jenkins should listen to the CloudEvents.


=== Project Size
This project is of medium size and is expected to be completed in ~175 hours.


=== Project Difficulty
Intermediate to Advanced


=== Links
There are many examples of such documentation on the web:

* link:https://CloudEvents.io/[CloudEvents website]
* link:https://github.com/CloudEvents/sdk-java[CloudEvents Java SDK]


=== Study Links
* link:https://en.wikipedia.org/wiki/Event-driven_architecture[Event-driven architecture]
* link:https://www.youtube.com/watch?v=STKCRSUsyP0&t=944s[The many meanings of event driven architecture by Martin Fowler]


=== Quick-start

The project requires the student to start with plugin development from scratch and then work with understanding how to use the CloudEvents Java SDK to create and read events.

In the beginning, the student can work on understanding the Jenkins plugin development by writing code for creating a simple Build Step which creates a CloudEvent, and from there we can move to the GlobalPluginConfiguration on how Jenkins should listen to the CloudEvents.


=== Skills to improve/study
* Java
* Go
* Networking
* Jenkins
