---
layout: gsocprojectidea
title: "Enhancing an Existing LLM Model with Domain-specific Jenkins Knowledge"
goal: "To develop an app using an existing open-source LLM model with data collected for domain-specific Jenkins knowledge one can fine-tune locally and set up with a proper UI for the user to interact with"
category: AI/ML
year: 2024
status: published
sig: infra
skills:
- Python
- React.js
- LLM
- AI/ML
- Jenkins
- Ollama
- LangChain
- UI
mentors:
- "krisstern"
- "harsh-ps-2003"
- "shivaylamba"
- "gounthar"
- "laulopezreal"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Background

This full-stack project focuses on a proof-of-concept (PoC) idea to fine-tune an existing open-source LLM model (such as Llama 2) with domain-specific Jenkins data to be compiled, wrangled, and processed by the contributor as a part of an AI-driven application, to develop a minimalistic UI for the user to interact with the LLM as a complete end-to-end product.
This product is to be installed and run locally on the user's laptop, with tools such as link:https://ollama.com/[Ollama] for setting up and running LLMs locally, and link:https://www.langchain.com/[LangChain] to be used as a framework to construct the LLM-powered app.
The contributor will get to be involved in every step of the application development process, from data collection, wrangling, and processing to fine-tuning the model and developing the UI.
They may also get exposed to how to package software to be distributed as a standalone application to be consumed by the end user.


=== Project Size
This project is of medium size and is expected to be completed in ~175 hours.


=== Project Difficulty
Intermediate to Advanced


=== Links

* link:https://www.datacamp.com/tutorial/fine-tuning-llama-2[DataCamp tutorial on how to fine-tune Llama 2]
* link:https://www.datacamp.com/tutorial/how-to-build-llm-applications-with-langchain[How to Build LLM Applications with LangChain Tutorial]
