---
layout: gsocprojectidea
title: "Implementing UI for Jenkins Infra Statistics"
goal: "To build upon the current GitHub Pages based UI into a user-friendly and full-featured website for showcasing Jenkins Infra Statistics"
category: UI/UX
year: 2024
status: published
sig: infra
skills:
- Javascript/Typescript
- HTML
- CSS
- Dashboard
- Data Visualization
- UI/UX Design
mentors:
- "krisstern"
- "vandit1604"
- "hlemeur"
links:
  meetings: /projects/gsoc/#office-hours
---

=== Abstract

This project is suited for a contributor who has had some prior exposure to frontend web development who would like to build a web app with dashboards for data visualisation, using data already presented at an existing GitHub Pages site at https://stats.jenkins.io/.

We aim to divide the project into four main components:

- Statistics in detail
- Plugin Installation Trend
- Plugin Versions by Jenkins Version
- Jenkins plugin dependency graph

The preferred frontend framework for the website would be React, using Gatsby.js or Vite.js preferably.
However, it could also be implemented with Angular or Vue.
Other plotting libraries that will be adopted may include Plotly.js (link:https://plotly.com/javascript/[]) and Apache ECharts (link:https://echarts.apache.org/en/index.html[]).


== Rationale

The current GitHub Pages site at https://stats.jenkins.io/ is fairly basic. The creator would like a proper UI to be implemented for better a better user experience.


=== Implementation

The contributor will get to design the look and feel of the website, and implement the UI using a frontend framework they would agree to explore.
The contributor will also get to explore the interplay between data and its presentation.
We aim for a final product that is both visually pleasing and informative.


=== Project Size
This project is of the medium size and is expected to be completed in ~175 hours.


=== Project Difficulty
Intermediate


== Links

* link:https://stats.jenkins.io/[Reference Site]
* link:https://github.com/jenkins-infra/infra-statistics/[Reference Site Code]
