---
layout: chapter
---
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:notitle:

= Getting Started with Jenkins

This chapter is intended for new users unfamiliar with Jenkins or those without experience with recent versions of Jenkins.

This chapter will lead you through installing an instance of Jenkins on a
system for learning purposes and understanding basic Jenkins concepts.  It will provide
simple step-by-step tutorials on how to do a number common tasks.  Each section is intended
to be completed in order, with each building on knowledge from the previous section.
When you are done you should have enough experience with the core of Jenkins to continue
exploring on your own.

If you are already familiar with Jenkins basics and would like to delve deeper into how to use specific features, see
<<using#,Using Jenkins>>.

If you are a Jenkins administrator and want to know more about managing Jenkins nodes and instances, see
<<managing#,Managing Jenkins>>.

If you are a system administrator and want learn how to back-up, restore, maintain as Jenkins servers and nodes, see
<<system-administration#,Jenkins System Administration>>.
