---
layout: chapter
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
:notitle:
endif::[]

= User Handbook Overview

This page provides an overview of the documentation in the Jenkins User
Handbook.

If you want to get up and running with Jenkins, see
link:../installing[Installing Jenkins] for procedures on how to install Jenkins
on your supported platform of choice.

If you are a typical Jenkins user (of any skill level) who wants to know more
about Jenkins usage, see link:../using[Using Jenkins]. Also refer to the
separate link:../pipeline[Pipeline] and link:../blueocean[Blue Ocean] chapters
for more information about these core Jenkins features.

If you are a Jenkins administrator and want to know more about managing Jenkins
nodes and instances, see link:../managing[Managing Jenkins].

If you are a system administrator and want to learn how to back-up, restore,
maintain as Jenkins servers and nodes, see
link:../system-administration[Jenkins System Administration].
