---
layout: section
---
:doctitle: Installing Jenkins
:notitle:
:description:
:author: Liam Newman
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

[NOTE]
====
This is still very much a work in progress
====

[IMPORTANT]
====
This section is part of _Getting Started_.
It provides a golden path for a *basic* jenkins configuration on a number of platforms.
It *DOES NOT* cover the full range of considerations or options for installing Jenkinks.
See link:/doc/book/appendix/advanced-installation/[Advanced Jenkins Installation]
====

== Overview


== Pre-install

=== System Requirements

WARNING: These are *starting points*.  For a full discussion of factors see: link:/doc/book/hardware-recommendations/[Discussion of hardware recommendations]

Minimum configuration:

* Java 7
* 512MB free memory
* 5GB free disk space

Recommended Initial Configuration:

* Java 8
* 1GB free memory
* 50GB free disk space

=== Experimentation, Staging, or Production?

How you configure Jenkins will differ significantly depending on

See link:/doc/book/appendix/advanced-installation/[Advanced Jenkins Installation]

=== Stand-alone or Servlet?

See link:/doc/book/appendix/advanced-installation/[Advanced Jenkins Installation]


== Installation

[WARNING]
====
These are *clean install* instructions for *non-Production* environments.
If you have a Jenkins server already running on a system and want to upgrade, see link:/doc/book/getting-started/upgrading/[Upgrading Jenkins].
If you are setting up a production Jenkins server, see link:/doc/book/appendix/advanced-installation/[Advanced Jenkins Installation].
====

=== Unix/Linux

==== Debian/Ubuntu
On Debian-based distributions, such as Ubuntu, you can install Jenkins through `apt-get`.

Recent versions are available in link:http://jenkins-ci.org/debian/[an apt repository]. Older but stable LTS versions are in link:http://pkg.jenkins-ci.org/debian-stable/[this apt repository].

You need to have a JDK and JRE installed. openjdk-7-jre and openjdk-7-jdk are suggested.

WARNING: GCJ is known to be problematic. It is used on ubuntu systems.  - see link:https://issues.jenkins-ci.org/browse/JENKINS-743[JENKINS-743].

[source,bash]
----
wget -q -O - https://jenkins-ci.org/debian/jenkins-ci.org.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins-ci.org/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

This package installation will:
* Setup Jenkins as a daemon launched on start. See `/etc/init.d/jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/etc/default/jenkins` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If your `/etc/init.d/jenkins` file fails to start jenkins, edit the `/etc/default/jenkins` to replace the line
`----HTTP_PORT=8080----` with `----HTTP_PORT=8081----`
Here, "8081" was chosen but you can put another port available.
====

=== OS X

To install from the website, using a package:

* link:http://mirrors.jenkins-ci.org/osx/latest[Download the latest package]
* Open the package and follow the instructions

Jenkins can also be installed using `brew`:

[source,bash]
----
brew cask install jenkins
----


=== Windows

To install from the website, using the installer:
* link:http://mirrors.jenkins-ci.org/windows/latest[Download the latest package]
* Open the package and follow the instructions


=== Docker
You must have [Docker|http://docker.io] properly installed on your machine.
See the ﻿link:https://www.docker.io/gettingstarted/#h_installation[Docker installation guide] for details.


First, pull the official link:https://hub.docker.com/_/jenkins/[jenkins] image from Docker repository.

[source,bash]
----
docker pull jenkins
----

Next, run a container using this image and map data directory from the container to the host; e.g in the example below {{/var/jenkins_home}} from the container is mapped to {{jenkins/}} directory from the current path on the host. Jenkins {{8080}} port is also exposed to the host as {{49001}}.

[source,bash]
----
docker run -d -p 49001:8080 -v $PWD/jenkins:/var/jenkins_home -t jenkins
----

=== Other
See link:/doc/book/appendix/advanced-installation/[Advanced Jenkins Installation]


== Post-install (Setup Wizard)

=== Create Admin User and Password for Jenkins

Jenkins is initially configured to be secure on first launch.
Jenkins can no longer be accessed without a username and
password and open ports are limited. During the initial run of
Jenkins a security token is generated and printed in the console
log:

----
*************************************************************
*************************************************************
*************************************************************

Jenkins initial setup is required. A security token is required to proceed.
Please use the following security token to proceed to installation:

41d2b60b0e4cb5bf2025d33b21cb

*************************************************************
*************************************************************
*************************************************************
----

The install instructions for each of the platforms above includes the default location for when you can find this log output.
This token must be entered in the "Setup Wizard" the first time you open the Jenkins UI.
This token will also serve as the default password for the user 'admin' if you skip the user-creation step in the Setup Wizard.

=== Initial Plugin Installation

The Setup Wizard will also install the initial plugins for this Jenkins server.
The recommended set of plugins available are based on the most common use cases.
You are free to add more during the Setup Wizard or install them later as needed.
