---
layout: post
title: "GSoC Project Update: Alpha release of Remoting Kafka Plugin"
tags:
- plugins
- gsoc
- gsoc2018
- remoting
- alpha-release
author: pvtuan10
---

I am happy to announce that we have recently released an alpha version of https://github.com/jenkinsci/remoting-kafka-plugin[Remoting Kafka Plugin] to the link:/doc/developer/publishing/releasing-experimental-updates/#configuring-jenkins-to-use-experimental-update-center[Experimental Update Center]. You can check the https://github.com/jenkinsci/remoting-kafka-plugin/blob/master/CHANGELOG.md[CHANGELOG] to see the features included in this initial release.

=== Overview
Current versions of Jenkins Remoting are based on the TCP protocol. If it fails, the agent connection and the build fails as well. There are also issues with traffic prioritization and multi-agent communications, which impact Jenkins stability and scalability.

https://github.com/jenkinsci/remoting-kafka-plugin[Remoting Kafka Plugin] is a plugin developed under link:/projects/gsoc/[Jenkins Google Summer of Code 2018]. The plugin is developed to add support of a popular message queue/bus technology (Kafka) as a fault-tolerant communication layer in Jenkins. A quick introduction of the project can be found in this  link:/blog/2018/06/18/remoting-over-message-bus/[introduction blogpost].

=== How to use the plugin?
The instructions to run the plugin in alpha version are written https://github.com/jenkinsci/remoting-kafka-plugin#how-to-use-the-plugin-in-alpha-version[here]. Feel free to have a try and let us know your feedback on https://app.gitter.im/#/room/#jenkinsci_remoting:gitter.im[Gitter] or the https://groups.google.com/forum/?nomobile=true#!forum/jenkinsci-dev[mailing list].

=== Links

* https://github.com/jenkinsci/remoting-kafka-plugin/blob/master/CHANGELOG.md#100-alpha-1[Alpha Changelog]
* link:/blog/2018/06/18/remoting-over-message-bus/[Introduction Blogpost]
* https://app.gitter.im/#/room/#jenkinsci_remoting:gitter.im[image:https://badges.gitter.im/jenkinsci/remoting.svg[title: "Gitter"]]
* https://github.com/jenkinsci/remoting-kafka-plugin[GitHub Repository]
* link:/projects/gsoc/2018/remoting-over-message-bus/[Project Page]
* https://youtu.be/qWHM8S0fzUw[Phase 1 Presentation Video]
* https://docs.google.com/presentation/d/1GxkI17lZYQ6_pyAOR9sXNXq1K3LwkqjigXdxxf81VkE/edit?usp=sharing[Phase 1 Presentation Slides]
