---
layout: post
title: "Join us at the Jenkins Contributor Summit"
tags:
- community
- event
- jenkins-world
author: tracymiranda
---

The Jenkins Contributor summit is where the current and future contributors of the Jenkins project get together.
This summit will be on Monday, September 17th 2018 in San Francisco, just before link:https://www.cloudbees.com/devops-world/san-francisco[DevOpsWorld | Jenkins World].
The summit brings together community members to learn, meet and help shape the future of Jenkins. 
In the Jenkins commmunity we value all types and sizes of contributions and love to welcome new participants.

== Topics
There are plenty of exciting developments happening in the Jenkins community. 
The summit will feature a 'State of the Project' update including updates from the Jenkins officers. 
We will also have updates on the 'Big 5' projects in active development:
* Jenkins Essentials
* Jenkins X
* Configuration as Code
* Jenkins Pipeline
* Cloud Native Jenkins Architecture

Plus we will also have updates from our Google Summer of Code students, and more!

== Agenda
The agenda is shaping up well and here is the outline so far.

*  9:00am Kickoff & Welcome with coffee/pastries
* 10:00am Project Updates
* 12:00pm Lunch
*  1.00pm BoF/Unconference
*  3.00pm Break
*  3.30pm Ignite Talks
*  5.00pm Wrap-up
*  6.00pm Contributor Dinner

Join in, hear the latest and get involved in any project during the BoF sessions.
If you want to share anything there will be an opportunity to do a 5-min ignite talk at the end.
Attending is free, and no DevOpsWorld | JenkinsWorld ticket is needed, but RSVP if you are going to attend to help us plan.

See you there!