---
layout: post
title: "Managing Jenkins with jcli"
tags:
- general
- jcli
author: linuxsuren
---

As a developer, I usually use Jenkins like this:

* Find a job which is related with your current work
* Trigger that job
* Check the output of log

Sometimes, I might need to check the update center. Maybe a new plugin is needed, or update an exists plugin.
Or, I want to upload a plugin from my computer. For all these cases, I just don't need a UI or even a browse.
I like to use a CLI to complete most of my tasks. For example, I use `kubectl` to manage my Kubernetes cluster,
to create or modify the kubernetes resources. So, I start to think that why not using a CLI to manage my Jenkins.

That's the story of creating `jcli`.

== Features

* Easy to maintain config file for jcli
* Multiple Jenkins support
* Plugins management (list, search, install, upload)
* Job management (search, build, log)
* Open your Jenkins with a browse
* Restart your Jenkins
* Connection with proxy support

== How to get it?

You can find `jcli` from this repo https://github.com/linuxsuren/jenkins-cli/[jenkins-cli]. For now, we support 
these three most popular os platform.

=== MacOS

You can use brew to install jcli.

```
brew tap linuxsuren/jcli
brew install jcli
```

=== Linux

It's very simple to install jcli into your Linux OS. Just need to execute a command line at below:

```
curl -L https://github.com/linuxsuren/jenkins-cli/releases/latest/download/jcli-linux-amd64.tar.gz|tar xzv
sudo mv jcli /usr/local/bin/
```

=== Windows

You can find the latest version by click https://github.com/linuxsuren/jenkins-cli/releases/latest/download/jcli-windows-386.tar.gz[here]. Then download the tar file, cp the uncompressed `jcli` directory into your system path.

=== How to get started?

It's very simple to use this. Once you got `jcli` in your computer. One thing is needed, use below cmd to generate and 
modify you Jenkins configuration:

```
jcli config generate
```

This cmd will help to you generate a sample config file. In most cases, you should modify the `url`, `username` and `token`. OK, I believe you're ready. Please check whether you install the `github` plugin in your Jenkins:

`jcli plugin list --filter name=github`

At the end. It's still under very early develope time. Any contribution is welcome.
