---
layout: gsocproject2
title: "Complete build retooling of jenkins.io"
goal: "Using alternative tooling with Gatsby and Antora to build the Jenkins static site and provide versioned Jenkins documentation"
category: Tools
year: 2025
sig: documentation
tags:
- gsoc2025
status: "Selected"
student: "biru-codeastromer"
mentors:
- "krisstern"
- "gounthar"
- "kmartens27"
- "iamrajiv"
links:
  gitter: "https://gitter.im/jenkinsci/gsoc-sig"
  draft: https://summerofcode.withgoogle.com/media/user/77e3b8323a5f/proposal/gAAAAABn9W4OrTJ_TFxHvMSVoAsMxEQFsDnw-raoBHX5qmzCUiYYmACJ80DxLSRc9UNXdwuH7DwOS6I319_A7sPSKTmcEDDzicG_eVIUhwy60yPthGdsDFs=.pdf
  idea: /projects/gsoc/2025/project-ideas/complete-alternative-jenkins-io-build-retooling
  meetings: "/projects/gsoc/2025/projects/complete-alternative-jenkins-io-build-retooling/#office-hours"
---

=== Abstract
This project aims to completely retool the Jenkins static site (https://jenkins.io) using alternative tooling, specifically Gatsby and Antora. The goal is to provide a more modern, efficient, and maintainable build process for the Jenkins documentation and website, while also enabling versioned documentation for different Jenkins releases.


=== Rationale
The current Jenkins static site is built using a Ruby-based `awestruct`, which does not offer a lot of the modern frontend features nowadays readily available to single-page applications like the ones made with React. By transitioning to Gatsby, a modern React-based framework, we can leverage its powerful features for static site generation, such as optimized performance, plugin ecosystem, and better developer experience. Antora will be used to manage versioned documentation, allowing users to access documentation for specific Jenkins versions easily.

=== Implementation
The project will involve the following key steps:

* **Gatsby Migration**: Migrate the existing Jenkins static site from `awestruct` to Gatsby, ensuring that all existing content is preserved and enhanced with modern frontend capabilities.
* **Antora Integration**: Integrate Antora to manage versioned documentation, allowing users to switch between different Jenkins versions seamlessly.
* **Documentation Enhancement**: Improve the existing documentation structure and content, ensuring it is clear, concise, and easy to navigate.
* **UI/UX Improvements**: Enhance the user interface and user experience of the Jenkins static site, making it more visually appealing and user-friendly.


=== Office hours

* Weekly project office hours: Tuesdays 14:30 UTC on Google Meet (link:https://meet.google.com/qvx-xuct-hxp/[Video call link])
