---
layout: gsocproject2
title: "Improving Plugin Modernizer"
goal: "Improving the Jenkins Plugin Modernizer tool and provide integrations with Jenkins ecosystem"
category: Tools
year: 2025
sig: platform
tags:
- gsoc2025
status: "Selected"
student: CodexRaunak
mentors:
- "gounthar"
- "jonesbusy"
- "sridamul"
- "TheMeinerLP"
links:
  slack: "https://cdeliveryfdn.slack.com/archives/C071YTZ807N"
  draft: https://docs.google.com/document/d/1QaEa4lvjdMi3JRXBOAN2eD2cjJkJ1-bfU-XHg4dlI0s/edit?tab=t.0
  idea: /projects/gsoc/2025/project-ideas/plugin-modernizer-improvements
  meetings: "/projects/gsoc/2025/projects/plugin-modernizer-improvements/#office-hours"
---


=== Abstract

This project idea is a continuation of the link:/projects/gsoc/2024/projects/using-openrewrite-recipes-for-plugin-modernization-or-automation-plugin-build-metadata-updates[GSoC 2024 Using OpenRewrite Recipes for Plugin Modernization].
The current link:https://github.com/jenkins-infra/plugin-modernizer-tool[Plugin Modernizer] will need to be enhanced to support more modernization recipes and provide integrations with the Jenkins ecosystem.


=== Rationale

The Jenkins ecosystem combines a monolithic core with a modular plugin system.
True, this design provides a great degree of flexibility and robustness, yet also it poses challenges to propagating large-scale changes throughout the ecosystem.
The lack of automation has led to many plugins falling behind with regard to ecosystem-wide migrations.
This project proposes the creation of a new tool to apply generic transformations across the Jenkins ecosystem.

=== Implementation

Improvements and integration could include:

- Store metadata about the modernization process on link:https://reports.jenkins.io[Jenkins reports site]
- Provide APIs to access the modernization metadata in addition to the existing CLI module (or even run the modernization recipes as a service)
- Generate metadata regularly (using Jenkins infrastructure or GitHub Actions depending on the research done during the project)
- Better integration with the Plugin Health Score to automatically run modernization recipes on plugins with low scores
- Visualize the modernization metadata on link:https://stats.jenkins.io[Jenkins statistics site]
- Any recipe improvements or new recipes that could be added to the tool to improve plugins health
- ...

=== Office hours

* (Project-based) Weekly project based office hours: Tuesdays 14:00 UTC (link:meet.google.com/gmf-pmvt-xru[Direct link])

=== Links

* link:https://docs.openrewrite.org/recipes/jenkins/[OpenRewrite Jenkins recipes]
* link:https://docs.openrewrite.org/concepts-explanations/lossless-semantic-trees[OpenRewrite LST]
