---
layout: chapter
---
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left

= Jenkins Use-Cases

An alternate title for this chapter would be "Jenkins for X".
Each section of this chapter focuses on how to to use Jenkins in a specific area.

The audience for each section in this chapter is any user interested in working
with Jenkins in that area.  Sections are completely independent, knowledge from
any one section is not required to understand any other.

If you are not yet familiar with basic Jenkins terminology and features, start with
<<getting-started#,Getting Started with Jenkins>>.

If you are already familiar with Jenkins basics and would like to delve deeper
into generally how to use various features, see
<<using#,Using Jenkins>>.

If you are a system administrator and want learn how to back-up, restore, maintain as Jenkins servers and nodes, see
<<operating#,Operating Jenkins>>.


[WARNING]
====
*To Contributors*:
For this chapter, topics which apply to multiple areas and thus would repeated in multiple sections,
should instead be covered in other chapters and cross-referenced.
For example, a general discussion of how to deploy artifacts would go in the chapter "<<using#,Using Jenkins>>",
while language-specific examples of how to deploy artifacts in Java, Python, and Ruby,
would go in the appropriate sections in this chapter.
====
