---
layout: post
title: "Testing Jenkins 2.249.1 on Windows"
tags:
- windows
- platform-sig
- installers
- announcement
authors:
- markewaite
- vsilverman
---

This article describes our observations during testing of a new Jenkins 2.249.1 release on Windows.

== Upgrade testing

In general link:https://www.jenkins.io/blog/2020/07/23/windows-support-updates/#upgrade-guidelines[Upgrade Guidelines] instructions describe major things to consider while making decision for upgrade and chosing the upgrade process.

=== Upgrade approaches

In our case we had sanity tested upgrades from Jenkins 2.235.X to 2.249.1 on Windows, while using link:https://www.jenkins.io/blog/2020/08/12/windows-installers-upgrade/#next-steps[Inside Jenkins Upgrade] approach.

=== Upgrade process

Our upgrade process was the following:

- download 2.249 version of jenkins.war from Jenkns update center
- stop running 2.235.X Windows service
- replace in <JENKINS_HOME> folder 2.235.X version of jenkins.war with new 2.249 version
- restart the Windows service

=== Testing reults

- The issue with link:https://issues.jenkins-ci.org/browse/JENKINS-63198[Restarting Windows service], observed in the previous release, had been fixed.

- Confirmed that we can provide for this release link:https://www.jenkins.io/blog/2020/07/23/windows-support-updates/#new-policy[Level 2 support policy].
