---
layout: post
title: "Jenkins at DevOps World 2020"
tags:
- events
- conference
- cicd
- talks
- workshops
author: alyssat
description: "Learn the latest and greatest Jenkins news and best practices at DevOps World 2020"
---

The annual link:https://www.cloudbees.com/devops-world[DevOps World], formerly known as DevOps World | Jenkins World is next week - Sept 22-24, with workshops on Sept 25. Just like other events this year, DevOps World pivoted to a virtual event but that doesn’t mean there is a shortage of sessions or networking opportunities. There will be over 50 Jenkins/open source sessions and opportunities to virtually connect with over 20,000+ attendees on the event platform. Below are just a few sessions, the full agenda can be found link:https://sessions.devopsworld.com/sessions[HERE]: 

== Jenkins: Where It Is and Where It is Going
Date: Tuesday, September 22, 7:00 a.m.-7:30 a.m (PDT)

Speaker: link:https://github.com/oleg-nenashev[Oleg Nenashev] 

Jenkins keeps evolving to address demands from its users and contributors: configuration as code, better support of cloud-native technologies, etc. Recently, we have introduced a public roadmap for the project, and there are many key initiatives in development and preview phases. This session will cover the current state of Jenkins and what’s next for the project.

== Managing DevSecOps Pipelines at Scale with Jenkins Templating Engine
Date: Tuesday, September 22, 11:30 a.m.-12:00 p.m. (PDT)

Speaker: link:https://github.com/steven-terrana/steven-terrana[Steven Terrana]

Are you currently helping build or maintain a Jenkins pipeline for more than one application or team? Are you tired of copying and pasting Jenkinsfiles and tweaking them to fit each team's specific needs? This session will feature a live demonstration of getting up and running with the Jenkins Templating Engine (JTE). Attendees will learn how to stop creating bespoke pipelines on a per-application basis and, instead, create tool-agnostic pipeline templates that multiple teams can inherit - regardless of tech stack.

== eBay’s Journey Building CI at Scale
Date: Tuesday, September 22, 12:30 p.m.-1:00 p.m.(PDT)

Speakers: Ravi Kiran Rao Bukka & Vasumathy Seenuvasan

A scalable CI platform with 6,000+ Jenkins instances serving around 43,000 builds per day on multi-cluster Kubernetes. A system built with metrics, key resource tuning, remediation's and security in place. Join this session to hear from eBay on their journey of best practices and learnings about open source.

== Machine Learning Plugins for Data Science in Jenkins
Date: Wednesday, September 23, 11:00 a.m.-11:15 a.m.(PDT)

Speaker: Loghi Perinpanayagam

Machine Learning has evolved rapidly in the software industry for recent years. Jenkins CI/CD can be a good practice to deliver a high reliable product in the end. We have done an initial startup on this plugin that can be used to build Jupyter Notebooks, Python files and JSON files in Zeppelin format. In addition, the build wrappers could be used to convert Jupyter Notebooks to Python/JSON and/or copy the files to the workspace for more actions.  This Machine Learning plugin will endeavor to satisfy the data science community together with the help of other plugins. Success of this plugin will definitely serve much benefits to the community and Jenkins.

== Jenkins UI Gets a Makeover
Date: Thursday, September 24, 7:30 a.m.-8:00 a.m.(PDT)

Speakers: link:https://github.com/fqueiruga[Felix Queiruga] & Jeremy Hartley

An overview of the Jenkins UI overhaul. We are taking an iterative approach to gradually refresh the Jenkins UI. This approach will make Jenkins look fresh and modern, without changing the way users are accustomed to working with Jenkins or require plugins to be rewritten to render properly in the new Jenkins UI. Join this session to learn the changes we've made and how you can help to improve the Jenkins UI.

The event is free to everyone and recordings will be available on-demand. link:https://experience.cloudbees.com/e/DevOpsWorld[Registration] is required to access the on-demand recordings. And don't forget to visit the CDF booth in the expo hall for one on one Q&A's with Jenkins experts. 
  
