---
layout: sig
title: "Platform"
section: sigs
sigId: "platform"
logo: /images/logos/formal/256.png
tags:
  - java
  - windows
  - docker
  - linux
  - platform_sig
  - platform-sig
  - platform
leads:
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
  irc: "oleg_nenashev"
  twitter: "oleg_nenashev"
- name: "Mark Waite"
  id: "markewaite"
  github: "markewaite"
- name: "Baptiste Mathus"
  id: "batmat"
  github: "batmat"
participants:
- name: "Tracy Miranda"
  id: "tracymiranda"
  github: "tracymiranda"
  irc: "tracymiranda"
- name: "Samuel Van Oort"
  id: "svanoort"
  github: "svanoort"
- name: "Nicolas De Loof"
  id: "ndeloof"
  github: "ndeloof"
- name: "Devin Nusbaum"
  id: "dnusbaum"
  github: "dwnusbaum"
- name: "Alex Earl"
  id: "slide"
  github: "slide"
- name: "Durgadas Kamath"
  github: "imdurgadas"
- name: "Robert Sandell"
  id: "rsandell"
  github: "rsandell"
- name: "Liam Newman"
  id: "bitwiseman"
  github: "bitwiseman"
- name: "David Currie"
  id: "dcurrie"
  github: "davidcurrie"
- name: "Adrien Lecharpentier"
  id: "alecharp"
  github: "alecharp"
- name: "Ramon Leon"
  id: "MRamonLeon"
  github: "MRamonLeon"
links:
  gitter: "jenkinsci/platform-sig"
  googlegroup: "jenkins-platform-sig"
meetings:
  text: Thursdays at 2PM UTC, every 2 weeks
overview: >
  This special interest group offers a venue for all kinds of platform support discussions:
  Java, Operating Systems, Architectures, Docker, Packaging, Web Containers, etc.
  The SIG works on defining platform support policies,
  coordinating platform support efforts with contributors and external communities,
  and reviewing proposals in the area.
---

The special interest group offers a venue for all kinds of platform support discussions:
Java, Operating Systems, Architectures, Docker, Packaging, Web Containers, etc.

The group focuses on technologies used in Jenkins:

* Java Virtual Machines: versions, compatibility and optmizations
* Operating Systems: native components, packaging
* Architectures and platforms
* Web Containers

Platform SIG may be cooperating with other groups.
For example, we will be cooperating with the link:/sigs/cloud-native[Cloud-Native Jenkins group]
if the topics related to Cloud-Native platforms like Kubernetes or Docker.

=== Topics

* Defining platform support policies (e.g. “defining Windows support policy”)
* Coordinating effort on new platform support (e.g. jep:211[Java 11 Support in Jenkins])
* Working with external communities on better platform support and packaging
(e.g. improving support of IBM Java, enabling OpenIndiana packaging,
ARM architecture support, adapting RedHat packaging to best practices, etc.)
* Reviewing JEPs submitted in the area

=== Ongoing projects

* Java 11 support in Jenkins (jep:211[])
* Multi-architecture Docker images
** Enabling official images to run on Arm, IBM s390x, and other platforms
* Rework of Windows installers
** New version of installers for 64bit platforms
** Removal of Java bundling
** Creating an official link:https://chocolatey.org/packages/jenkins[Jenkins Chocolatey package]
* Enabling continuous delivery for Jenkins packaging
** Experimental DockerHub organization and deployments from ci.jenkins.io (jep:217[])

See the SIG meeting notes for more information about the ongoing projects.

=== Meetings

We have regular meetings on Thursdays every two weeks, at *2PM UTC*.
See the link:/event-calendar/[Jenkins Event Calendar] for the schedule.
At these meetings we discuss project statuses and do presentations/demos.
You can find and contribute to the agenda for the incoming meetings
link:https://docs.google.com/document/d/1bDfUdtjpwoX0HO2PRnfqns_TROBOK8tmP6SgVhubr2Y/edit?usp=sharing[here].

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.
Participant links will be posted in the SIG Gitter Chat within 10 minutes before the meeting starts.

==== 2018-12-04

Java 11 preview availability sign-off and Docker packaging

* link:https://docs.google.com/document/d/1s4XhfmhgVa6ZHcwGhOIrwL-6wc9v9qXhym96BiwWUrQ/edit?usp=sharing[Meeting notes]
* link:https://www.youtube.com/watch?v=RohXaGiDViw[Youtube recording]

==== 2018-11-19. Project sync-up

Project sync-ups: Windows Installers, Java 11 packaging, Multi-architecture Docker images.

* link:https://docs.google.com/document/d/1FARi55vDjsdzi6Nj9ZB9e1wh2dU8nyWK6mq_cge0ceg/edit?usp=sharing[Meeting notes]
* link:https://youtu.be/Rv-KvlGvnio[Youtube recording]
* link:https://docs.google.com/presentation/d/1lw4unaFhsQk7a8HzhxhgTK4X2X2ocv_W_VW7aoH2WkM/edit?usp=sharing[Slides: Java 11 Status update]

==== 2018-09-27. Project sync-up

Project sync-ups: Java 11 packaging, Multi-architecture Docker images.

* link:https://docs.google.com/document/d/1nIz1STmwOVMJ3vx68m6Xc4pv2oEKDRdyeYUNI8zZJsg/edit?usp=sharing[Meeting notes]
* link:https://www.youtube.com/watch?v=JmOnJopFix0[Video recording]

==== 2018-08-29. Multi-architecture Docker images

Sync-up call about jira:52785[Support of Multi-Architecture Docker images in Jenkins].
We discussed ways to get these images built and/or hosted within Jenkins project.

* link:https://docs.google.com/document/d/1YofL2uhy7xAa1mx_qFdDvDg4P-molmhDwFD0-8xX8mI/edit?usp=sharing[Meeting notes]
* link:https://www.youtube.com/watch?v=6SeDJXgzUCA[Youtube video]

==== 2018-08-23. Eclipse OpenJ9 and Jenkins

This online meetup is about Eclipse OpenJ9 and Jenkins.
The discussion will be led by Steve Poole (Eclipse Openj9), and Tracy Miranda where they aim to shed light on some questions.
Can Jenkins stand to gain any performance boosts by taking advantage of Eclipse OpenJ9 and its optimizations?
How can the two open source communities collaborate to drive improvements for Jenkins running in the cloud?

* link:https://www.meetup.com/Jenkins-online-meetup/events/253769950/[Jenkins Online Meetup page]
* link:https://docs.google.com/document/d/1RuD5f78bpakBmWy0bwap424IysxV1B3uj2-NbkTC9E0/edit#[Meeting notes]

==== 2018-08-15. Status meeting

Status sync-up: Java 10+ support in Jenkins (JEP-211),
64-bit Windows installers, Chocolatey packaging, and other topics.

* link:https://www.youtube.com/watch?v=bbWO89HPMUM[Youtube video]
* link:https://docs.google.com/document/d/1OgQCeyHNEV2GVx6phsNX_RtzpAiJWtKLUdAm1NDF6vY/edit[Meeting Agenda and Notes]
