---
layout: sig
title: "Platform"
section: sigs
sigId: "platform"
logo: /images/user.gif
tags:
  - java
  - windows
  - linux
  - platform_sig
leads:
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
  irc: "oleg_nenashev"
  twitter: "oleg_nenashev"
participants:
- name: "Tracy Miranda"
  id: "tracymiranda"
  github: "tracymiranda"
  irc: "tracymiranda"
links:
  gitter: "jenkinsci/platform-sig"
  googlegroup: "jenkins-platform-sig"
meetings:
  text: Every month, to be announced
  link: TODO
overview: >
  This special interest group offers a venue for all kinds of platform support discussions:
  Java, Operating Systems, Architectures, Docker, Packaging, Web Containers, etc.
  The SIG works on defining platform support policies,
  coordinating platform support efforts with contributors and external communities,
  and reviewing proposals in the area.
---

The special interest group offers a venue for all kinds of platform support discussions:
Java, Operating Systems, Architectures, Docker, Packaging, Web Containers, etc.

The group focuses on technologies used in Jenkins:

* Java Virtual Machines: versions, compatibility and optmizations
* Operating Systems: native components, packaging
* Architectures and platforms
* Web Containers

Platform SIG may be cooperating with other groups.
For example, we will be cooperating with the link:/sigs/cloud-native[Cloud-Native Jenkins group]
if the topics related to Cloud-Native platforms like Kubernetes or Docker.

=== Topics

* Defining platform support policies (e.g. “defining Windows support policy”)
* Coordinating effort on new platform support (e.g. Java 10 in JEP-TODO)
* Working with external communities on better platform support and packaging
(e.g. improving support of IBM Java, enabling OpenIndiana packaging,
ARM Support in Jenkins, adapting RedHat packaging to best practices, etc.)
* Reviewing JEPs submitted in the area

=== Meetings

There will be regular SIG meetings scheduled.
Initially the meetings will be conducted once per month,
then they may be adapted according to the activity.

Meetings will be conducted and recorded via Jenkins Hangouts-on-Air.
Participant links will be posted in the SIG Gitter Chat within 10 minutes before the meeting starts.

==== 2018-08-15. Status meeting

Status sync-up: Java 10+ support in Jenkins (JEP-211),
64-bit Windows installers, and other topics.

* link:https://www.youtube.com/watch?v=bbWO89HPMUM[Youtube video]
* link:https://docs.google.com/document/d/1OgQCeyHNEV2GVx6phsNX_RtzpAiJWtKLUdAm1NDF6vY/edit[Meeting Agenda and Notes]
