---
layout: post
title: "Pipeline Development Tools"
tags:
- blueocean
- pipeline
- tutorial

author: lnewman
---

NOTE: This is a guest post by link:https://github.com/bitwiseman[Liam Newman],
Technical Evangelist at link:https://cloudbees.com[CloudBees].

== Pipeline as code, made easier

I've only been working with Pipeline for about a year.
Pipeline in and of itself is a huge improvement over old style Jenkins projects.
As a developer, it has been so great be able work with Jenkins projects
using the same tools I use for writing any other kind of code.

I've also found a number of tools that are super helpful specifically
for developing pipelines. Some were easy to find like the
<</doc/book/pipeline/getting-started#built-in-documentation, built-in documentation>>
and the
<</doc/book/pipeline/getting-started#snippet-generator, Snippet Generator>>.
Others were not as obvious or were only recently released.
In this post, I'll show how a few of those tools make working with Pipelines
even better.


== The Blue Ocean Pipeline Editor

The best way to start this list is with the most recent and coolest
arrival in this space: the Blue Ocean Pipeline Editor.  The editor only works
with Declarative Pipelines, but it brings a sleek new user experience to writing
Pipelines.  My recent screencast, released as part of the Blue Ocean Launch,
gives good sense of how useful the editor is:

video::5Nct-jrZBbM[youtube]

== Command-line Pipeline Linter

One of the neat features of the Blue Ocean Pipeline Editor is that it does basic
validation on our Declarative Pipelines before they are even committed or Run.
This feature is based on the
"link:https://en.wikipedia.org/wiki/Lint_(software)[Declarative Pipeline Linter]",
which can be accessed from the command-line even if you don't have Blue Ocean
installed.

// TODO: Show two examples using the linter

== Replay

I love being able to use source control to track changes to my Pipelines
right alongside the rest of the code in a project.  There are also times,
when prototyping or debugging, that I need to iterate quickly on a series
of possible Pipeline changes.
The Replay feature let's me do that and see the results,
without committing those changes to source control.

// TODO: Example where I used Replay to debug an issue in a Pipeline


Now that I've worked all the bugs out of my Pipeline,
I'll use Replay to view the Pipeline for the last run and copy it back to my
`Jenkinsfile` and create a commit for that change.


== Conclusion

This is far from a complete list of the tools out there for working with Pipeline.
There are many more and the number is growing.
For example, one tool  I just recently heard about and haven't had a chance to delve into
is the
link:https://github.com/lesfurets/JenkinsPipelineUnit[Pipeline Unit Testing Framework],
which promises the ability to test Pipelines before running them.
It's been a fun year and I can't wait to see what the next year holds for Pipeline.


====
Do you have a tool that you feel has greatly improved your development experience
with Pipeline?  I'm interested in hear about others Jenkins user's favorite ways
of working with Pipeline.  Drop me a email or join the discussion on IRC.
====
