usecase: "Continuous Delivery"
jumbotron:
  image: '/images/full-pipeline.jpg'
blog_tags:
  - cd
  - pipeline
  - cicd
articles:
-
  - http://udaypal.com/jenkins-workflow-getting-started/
  - "Getting started with Jenkins Workflow"
-
  - https://jenkins-ci.org/content/pipeline-code-multibranch-workflows-jenkins
  - "Multibranch Workflows in Jenkins"
plugins:
-
  - "https://wiki.jenkins-ci.org/display/JENKINS/Workflow+Plugin"
  - "Pipeline plugin"
  - "allows creating Pipeline scripts for defining build/test/deploy stages of a delivery pipeline"
-
  - 'https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Utility+Steps+Plugin'
  - 'Pipeline Utility Steps plugin'
  - 'provides a number of addition, useful, steps to the Pipeline DSL'
-
  - "https://wiki.jenkins-ci.org/display/JENKINS/Job+DSL+Plugin"
  - "Job DSL plugin"
  - "creates a DSL to orchestrate job creation"
