---
layout: project
title: "Jenkins at FOSDEM 2019"
sigId: "advocacy-and-outreach"
tags:
  - outreach-programs
  - community
  - events
  - fosdem
links:
  gitter: jenkinsci_fosdem:gitter.im
---

NOTE: This is an archive page. See link:/events/fosdem[this page] for the recent and incoming FOSDEM events.

Jenkins did not have a stand at https://fosdem.org/2019/[FOSDEM 2019,
in Brussels, on February 2 & 3, 2019].

However, the following Jenkins activities are being planned as FOSDEM
Fringe 

[[FOSDEM2019-Activities]]
== Activities

* Friday, February 1 from 9am - 5pm: Jenkins Office Hours  +
** https://www.meetup.com/jenkinsmeetup/events/257871603/[meetup page] 
** location: Hilton Brussels Grand Place, meeting room: BTA +
Carrefour de l'Europe 3 +
1000 Brussels +
Belgium +

* Friday, February 1 evening : pre-FOSDEM happy hour (Cafe Le Roy
d'Espagne)
** https://www.meetup.com/jenkinsmeetup/events/257871603/[meetup page ]

* Friday, February 1 - Workshops. There will be two Jenkins
tutorials/workshops:
** https://www.eventbrite.com/e/jenkins-pipeline-fundamentals-training-tickets-54626761113[Jenkins
Pipeline Fundamentals]
** https://www.eventbrite.com/e/workshop-continuous-deployment-with-jenkins-x-kubernetes-and-friends-tickets-54562126790[CD
with Jenkins X, K8s, and Friends]

* Saturday & Sunday, February 2 & 3:  attend sessions @ FOSDEM
** Kohsuke is speaking on Sunday, Feb
3 https://fosdem.org/2019/schedule/event/community_hackers_gotta_eat/

* Monday, February 4: all day
https://www.meetup.com/jenkinsmeetup/events/257810396/[contributor
summit and or hackathon]  +
 +
 +

Who's attending:

* @link:/blog/authors/kohsuke/[
(kohsuke)] (attendance, organizing)
* link:/blog/authors/alyssat[(atong)]
(attendance, organizing)
* link:/blog/authors/daniel-beck/[(danielbeck)]
* link:/blog/authors/batmat[(batmat)]
* link:/blog/authors/olblak[
(olblak)] (attendance, organizing)
