---
layout: project
title: "Jenkins at FOSDEM 2020"
sigId: "advocacy-and-outreach"
tags:
  - outreach-programs
  - community
  - events
  - fosdem
links:
  gitter: jenkinsci_fosdem:gitter.im
---

Jenkins project has participated in FOSDEM 2020.
This event is coordinated by the link:/sigs/advocacy-and-outreach/[Jenkins Advocacy and Outreach SIG].
Current plan:

* **Jan 30** - Jenkins Pipeline Fundamentals training led by link:/blog/authors/markewaite/[Mark Waite] (link:https://www.eventbrite.com/e/jenkins-pipeline-fundamentals-training-tickets-87080214265[Register here])
* **Jan 31** - Jenkins Contributor Summit (link:https://www.meetup.com/jenkinsmeetup/events/267684785/[RSVP here])
** This is a small event for active contributors and those who are interested in working on foundation projects: key architecture changes (UX, JCasC, Cloud native Jenkins, etc.), governance and infrastructure
* **Feb 01-02** - Conference dates (no registration needed)
** We will have a link:https://fosdem.org/2020/stands/[Jenkins stand] during the entire conference
** On Sunday there will be a link:https://fosdem.org/2020/schedule/track/continuous_integration_and_continuous_deployment/[Continuous Integration and Continuous Deployment devroom] led by link:https://github.com/olblak[Olivier Vernin].
   There will be talks about Jenkins there 
** See the full agenda link:https://fosdem.org/[here]

==== FOSDEM 2020 Details

The detailed agenda is available in this Google Doc:

++++
<iframe src="https://docs.google.com/document/d/1AqmosxJ-HiUsiw9IhObA4sdFF5xBVOXEP5dDmanXRdw?embedded=true" width="100%" height="600px"></iframe>
++++

Also see link:https://groups.google.com/forum/#!topic/jenkinsci-dev/PUgV5xxHMwg[this thread] in the developer mailing list.
