---
layout: sig
title: "Pipeline Authoring"
section: sigs
sigId: "pipeline-authoring"
logo: /images/user.gif
tags:
- pipeline
- ux
- authoring
leads:
- name: "Andrew Bayer"
  id: "abayer"
  github: "abayer"
participants:
- name: "Liam Newman"
  id: "bitwiseman"
  github: "bitwiseman"
- name: "Austin Witt"
  id: "awitt"
  github: "awittha"
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
- name: "Devin Nusbaum"
  id: "dnusbaum"
  github: "dwnusbaum"
- name: "Zhao Xiaojie"
  id: "surenpi"
  github: "linuxsuren"
- name: "Michael Werner"
  id: "xaseron"
  github: "xaseron"
- name: "Marky Jackson"
  id: "jequals5"
  github: "markyjackson-taulia"
- name: "Rob Pickerill"
  id: "rbpckr"
  github: "robpickerill"
- name: "Christian Chavez"
  id: "x10an14"
  github: "x10an14"
- name: "Sam Van Oort"
  id: "svanoort"
  github: "svanoort"
- name: "David Chwalisz"
  id: "dchwalisz"
  github: "dcfsc"
- name: "Jon Brohauge"
  id: "jnz_topdanmark"
  github: "jonbrohauge"
- name: "Christian Rasp"
  id: "crasp"
  github: "crasp"
- name: "Peter Salvatore"
  id: "psftw"
  github: "psftw"
- name: "Mauro Ferratello"
  id: "ferratello"
  github: "ferratello"

organizations:
- name: "CloudBees"
  github: "cloudbees"

links:
  gitter: jenkinsci/pipeline-authoring-sig
  googlegroup: jenkins-pipeline-authoring-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  This special interest group aims to improve and curate the
  experience of authoring Jenkins Pipelines. This includes the syntax
  of `Jenkinsfile`s and shared libraries, code sharing and reuse,
  testing of Pipelines and shared libraries, IDE integration and other
  development tools, documentation, best practices, and examples.

---

This special interest group focuses on improving Jenkins Pipelines and the experience of authoring a Jenkins Pipeline.

=== Focus Areas
* Syntax - How `Jenkinsfile`s and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of `Jenkinsfile`s and shared libraries.
* IDE integration, editors, and other development tools - IDE plugins,
  visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evanglizing best
  practices in Jenkins Pipeline.
* Examples - Real-world `Jenkinsfile`s and shared libraries
  demonstrating how to utilize various features of Pipeline, as well as
  basic or starter `Jenkinsfile`s for common patterns that can be used
  as jumping-off points by new users.

=== Communications
The target aduience are anyone who are interested to join the effort of improving and/or curating the experience of writing Jenkins Pipelines.
As such, anyone with interest to either (or both) join our SIG meetings or our Gitter channel are welcome to participate!

==== Gitter channel (gitter: jenkinsci/pipeline-authoring-sig)
While any and all with questions wrt. writing a Jenkins Pipeline are welcome in our Gitter channel, we ask that the question has been researched _some_ before it's brought to us.
Indeed, there are multiple blog posts and guides on the internet discussing how both to _ask_ a question in a constructive manner, and how to _reply_ constructively.

Some examples of such posts/guides:

* http://www.catb.org/esr/faqs/smart-questions.html (Short & sweet blog post/tutorial)
* https://www.biostars.org/p/75548/ (A more comprehensive blog post/tutorial)
* https://docs.plone.org/askforhelp.html (A documentation guide exemplifying how to ask help wrt. to a specific tool - like Jenkins Pipelines)

**The below FAQ lists typical issues and answers that it would be greatly appreciated any inquisitive person headed for our Gitter channel checks out before asking their question.**

===== FAQ
TODOs:

* Fill out with suggestions from SIG

==== Pipeline Authoring SIG meetings
TODOs:

* Write up frequency and dates (2nd wednesday every month - 16:00 UTC?)
* List up minutes from previous meetings
