---
layout: sig
title: "Pipeline Authoring"
section: sigs
sigId: "pipeline-authoring"
logo: /images/user.gif
tags:
- pipeline
- ux
- authoring
leads:
- name: "Andrew Bayer"
  id: "abayer"
  github: "abayer"
participants:
- name: "Liam Newman"
  id: "bitwiseman"
  github: "bitwiseman"
  
organizations:
- name: "CloudBees"
  github: "cloudbees"

links:
  gitter: jenkinsci/pipeline-authoring-sig
  googlegroup: jenkins-pipeline-authoring-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  This special interest group aims to improve and curate the
  experience of authoring Jenkins Pipelines. This includes the syntax
  of `Jenkinsfile`s and shared libraries, code sharing and reuse,
  testing of Pipelines and shared libraries, IDE integration,
  documentation, best practices, and examples.

---

This special interest group aims to improve and curate the experience
of authoring Jenkins Pipelines. This includes the syntax of
`Jenkinsfile`s and shared libraries, code sharing and reuse, testing
of Pipelines and shared libraries, IDE integration, documentation,
best practices, and examples.

=== Focus Areas

* Syntax - How `Jenkinsfile`s and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of `Jenkinsfile`s and shared libraries.
* IDE integration and editors - IDE plugins, visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evanglizing best
  practices in Jenkins Pipeline.
* Examples - Real-world `Jenkinsfile`s and shared libraries
  demonstrating how to utilize various features of Pipeline, as well as
  basic or starter `Jenkinsfile`s for common patterns that can be used
  as jumping-off points by new users.

