---
layout: sig
title: "Pipeline Authoring"
section: sigs
sigId: "pipeline-authoring"
logo: /images/user.gif
tags:
- pipeline
- ux
- authoring
leads:
- "abayer"
participants:
- "lnewman"
- "awitt"
- "oleg_nenashev"
- "dwnusbaum"
- "linuxsuren"
- "xaseron"
- "markyjackson-taulia"
- "robpickerill"
- "x10an14"
- "svanoort"
- "dchwalisz"
- "jonbrohauge"
- "crasp"
- "psftw"
- "ferratello"
- "steven-terrana"

organizations:
- name: "CloudBees"
  github: "cloudbees"
- name: "Booz Allen Hamilton" 
  github: "boozallen" 

links:
  gitter: jenkinsci/pipeline-authoring-sig
  googlegroup: jenkins-pipeline-authoring-sig
  meetings: "/sigs/pipeline-authoring/#meetings"

overview: >
  This special interest group aims to improve and curate the
  experience of authoring Jenkins Pipelines. This includes the syntax
  of `Jenkinsfile`s and shared libraries, code sharing and reuse,
  testing of Pipelines and shared libraries, IDE integration and other
  development tools, documentation, best practices, and examples.

---

This special interest group focuses on improving Jenkins Pipelines and the experience of authoring a Jenkins Pipeline.

=== Focus Areas
* Syntax - How `Jenkinsfile`s and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of `Jenkinsfile`s and shared libraries.
* IDE integration, editors, and other development tools - IDE plugins,
  visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evanglizing best
  practices in Jenkins Pipeline.
* Examples - Real-world `Jenkinsfile`s and shared libraries
  demonstrating how to utilize various features of Pipeline, as well as
  basic or starter `Jenkinsfile`s for common patterns that can be used
  as jumping-off points by new users.

=== Communications
The target aduience are anyone who are interested to join the effort of improving and/or curating the experience of writing Jenkins Pipelines.
As such, anyone with interest to either (or both) join our SIG meetings or our Gitter channel are welcome to participate!

==== Gitter channel (gitter: jenkinsci/pipeline-authoring-sig)
While any and all with questions wrt. writing a Jenkins Pipeline are welcome in our Gitter channel, we ask that the question has been researched _some_ before it's brought to us.
Indeed, there are multiple blog posts and guides on the internet discussing how both to _ask_ a question in a constructive manner, and how to _reply_ constructively.

Some examples of such posts/guides:

* https://www.catb.org/esr/faqs/smart-questions.html (Short & sweet blog post/tutorial)
* https://www.biostars.org/p/75548/ (A more comprehensive blog post/tutorial)
* https://docs.plone.org/askforhelp.html (A documentation guide exemplifying how to ask help wrt. to a specific tool - like Jenkins Pipelines)

**The below FAQ lists typical issues and answers that it would be greatly appreciated any inquisitive person headed for our Gitter channel checks out before asking their question.**

==== FAQ

WARNING: Coming soon...

=== Meetings

Meetings are held on the second Wednesday of each month at 4:00pm UTC.  
Links to the SIG meetings are announced in the Gitter channel and in the mailing list.

* **2018-12-12**:
  link:https://www.youtube.com/watch?v=VEaAJrV3RYs[Video] -
  link:https://docs.google.com/document/d/1R8tR7HzD9eFUELy4K7J5hnZ5AuoEaPNBddAU0qL9g60/edit?usp=sharing[Notes]
