---
layout: sig
title: "Pipeline Authoring"
section: sigs
sigId: "pipeline-authoring"
logo: /images/user.gif
tags:
- pipeline
- ux
- authoring
leads:
- name: "Andrew Bayer"
  id: "abayer"
  github: "abayer"
participants:
- name: "Liam Newman"
  id: "bitwiseman"
  github: "bitwiseman"
- name: "Austin Witt"
  id: "awitt"
  github: "awittha"
- name: "Oleg Nenashev"
  id: "oleg_nenashev"
  github: "oleg-nenashev"
- name: "Devin Nusbaum"
  id: "dnusbaum"
  github: "dwnusbaum"
- name: "Zhao Xiaojie"
  id: "surenpi"
  github: "linuxsuren"
- name: "Michael Werner"
  id: "xaseron"
  github: "xaseron"
- name: "Marky Jackson"
  id: "jequals5"
  github: "markyjackson-taulia"
- name: "Rob Pickerill"
  id: "rbpckr"
  github: "robpickerill"
- name: "Christian Chavez"
  id: "x10an14"
  github: "x10an14"
- name: "Sam Van Oort"
  id: "svanoort"
  github: "svanoort"
- name: "David Chwalisz"
  id: "dchwalisz"
  github: "dcfsc"
- name: "Jon Brohauge"
  id: "jnz_topdanmark"
  github: "jonbrohauge"

organizations:
- name: "CloudBees"
  github: "cloudbees"

links:
  gitter: jenkinsci/pipeline-authoring-sig
  googlegroup: jenkins-pipeline-authoring-sig
meetings:
  text: To be announced
  link: TODO
overview: >
  This special interest group aims to improve and curate the
  experience of authoring Jenkins Pipelines. This includes the syntax
  of `Jenkinsfile`s and shared libraries, code sharing and reuse,
  testing of Pipelines and shared libraries, IDE integration and other
  development tools, documentation, best practices, and examples.

---

This special interest group aims to improve and curate the experience
of authoring Jenkins Pipelines. This includes the syntax of
`Jenkinsfile`s and shared libraries, code sharing and reuse, testing
of Pipelines and shared libraries, IDE integration, documentation,
best practices, and examples.

=== Focus Areas

* Syntax - How `Jenkinsfile`s and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of `Jenkinsfile`s and shared libraries.
* IDE integration, editors, and other development tools - IDE plugins,
  visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evanglizing best
  practices in Jenkins Pipeline.
* Examples - Real-world `Jenkinsfile`s and shared libraries
  demonstrating how to utilize various features of Pipeline, as well as
  basic or starter `Jenkinsfile`s for common patterns that can be used
  as jumping-off points by new users.

