---
layout: sig
title: "Pipeline Authoring"
section: sigs
sigId: "pipeline-authoring"
logo: /images/user.svg
tags:
- pipeline
- authoring
leads:
- "lnewman"
participants:
- "awitt"
- "oleg_nenashev"
- "dwnusbaum"
- "linuxsuren"
- "xaseron"
- "robpickerill"
- "x10an14"
- "svanoort"
- "dchwalisz"
- "jonbrohauge"
- "crasp"
- "ferratello"
- "steven-terrana"

organizations:
- name: "Anchore"
  github: "anchore"
- name: "Booz Allen Hamilton"
  github: "boozallen"
- name: "CloudBees"
  github: "cloudbees"


links:
  gitter: "jenkinsci_pipeline-authoring-sig:gitter.im"
  googlegroup: jenkins-pipeline-authoring-sig
  meetings: "/sigs/pipeline-authoring/#meetings"

overview: >
  This special interest group aims to improve and curate the
  experience of authoring Jenkins Pipelines. This includes the syntax
  of `Jenkinsfile`s and shared libraries, code sharing and reuse,
  testing of Pipelines and shared libraries, IDE integration and other
  development tools, documentation, best practices, and examples.

---

This special interest group focuses on improving Jenkins Pipelines and the experience of authoring a Jenkins Pipeline.

=== Focus Areas
* Syntax - How Jenkinsfiles and shared libraries are written.
* Code sharing and reuse - Shared libraries and future improvements.
* Testing - Unit and functional testing of Jenkinsfiles and shared libraries.
* IDE integration, editors, and other development tools - IDE plugins,
  visual editors, etc.
* Documentation - Reference documentation, tutorials, and more.
* Best practices - Defining, maintaining, and evangelizing best
  practices in Jenkins Pipeline.
* Examples - Real-world Jenkinsfiles and shared libraries
  demonstrating how to utilize various features of Pipeline, as well as
  basic or starter Jenkinsfiles for common patterns that can be used
  as jumping-off points by new users.

=== Communications
The target audience are anyone who are interested to join the effort of improving and/or curating the experience of writing Jenkins Pipelines.
As such, anyone with interest to either (or both) join our SIG meetings or our Gitter channel are welcome to participate!

==== Gitter Channel
While any and all with questions regarding writing a Jenkins Pipeline are welcome in our link:https://app.gitter.im/#/room/#jenkinsci_pipeline-authoring-sig:gitter.im[Gitter channel], we ask that the question has been researched before it is posted.
Indeed, there are multiple blog posts and guides on the internet discussing how both to _ask_ a question in a constructive manner, and how to _reply_ constructively.

Some examples of such posts/guides:

* https://www.catb.org/esr/faqs/smart-questions.html (Short & sweet blog post/tutorial)
* https://www.biostars.org/p/75548/ (A more comprehensive blog post/tutorial)
* https://docs.plone.org/askforhelp.html (A documentation guide exemplifying how to ask help wrt. to a specific tool - like Jenkins Pipelines)



=== Meetings

Meetings are held every Friday at 9:00 AM PST. You can find more details by visiting the link:/event-calendar/[community calendar]
Prior to each meeting a link to the meeting and meeting notes are provided in the link:https://app.gitter.im/#/room/#jenkinsci_pipeline-authoring-sig:gitter.im[Jenkins Pipeline-Authoring Gitter]
The last Friday of every month, the meeting is dedicated to link:/project/roadmap/[roadmap] discussions and statuses.

=== Code of Conduct

This SIG adheres to the link:/project/conduct/[Jenkins Code of Conduct]
