---
title: Access Control
layout: section
---
:toc:
:toclevels: 4

Jenkins access control is split into two parts:

* Authentication (users prove who they are) is done using a _security realm_.
  The security realm determines user identity and group memberships.
* Authorization (users are permitted to do something) is done by an _authorization strategy_.
  This controls whether a user (directly or through group memberships) has a permission.

These can be independent, or work in combination.
An independent configuration would be plugin:active-directory[Active Directory] or plugin:ldap[LDAP] as security realm, and something like plugin:matrix-auth[Matrix Authorization Strategy] as authorization strategy.
An example for related security realm and authorization strategy configuration is plugin:github-oauth[GitHub Authentication]:
While its security realm can be used with a generic authorization strategy, it also provides an authorization strategy that looks up a user's repository permissions on GitHub, and grants or denies permissions to related jobs in Jenkins based on that.

[NOTE]
====
Jenkins could be set up to have basic access control happen outside of it.
Some examples:

* The built-in https://github.com/jenkinsci/winstone[Winstone/Jetty servlet container wrapper] provides options that implement a basic security realm outside Jenkins.
* If Jenkins is running behind a reverse proxy like Nginx or Apache, those can limit access to Jenkins.

An advantage of these approaches is that they do not allow any access to Jenkins unless a user is authorized, reducing the impact of security issues in Jenkins or plugins especially when accessible from the internet.
A disadvantage is the lack of integration with Jenkins access controls and potentially even interfering with it (e.g. when trying to authenticate scripted clients).
====

== Common Configuration Mistakes

When configuring authentication and authorization in Jenkins, it is easy to accidentally allow far more access than intended.
See link:/doc/book/security/access-control/permissions/#administer[the documentation on the access given to administrators] about the impact of unintentionally granting Administer permission.

Anyone can do anything::
The *anyone can do anything* authorization strategy is very rarely a good choice, as it allows even anonymous users to administer Jenkins.
As a rule of thumb, it should not be used.
Never rely on the Jenkins URL to not be known outside your team or organization alone for security.

Logged-in users can do anything::
Using the *logged-in users can do anything* authorization strategy can be a sensible choice as long as only fully trusted users have accounts to access Jenkins.
This is the default with Jenkins's single admin user when setting up Jenkins with the setup wizard.
+
Switching to an authentication realm that allows untrusted users to have an account later will result in those users getting administrative access to Jenkins if you keep this authorization strategy.
The default behavior enables account signup for the _Jenkins user database_, which is recommended for most production systems. Other authorization realms can be specified here, although note that many of these (such as GitHub, Google, GitLab) allow anyone to sign up for an account.

Anonymous and authenticated users::
Similar to the previous items, you should generally not grant significant permissions to `anonymous` (the anonymous user) or authenticated (any authenticated user) when using an authorization strategy that allows finer-grained control (like plugin:matrix-auth[Matrix Authorization Strategy]).
Granting Overall/Administer permission to _anonymous_ is similar to _Anyone can do anything_, while granting that permission to _authenticated_ is essentially the same as _Logged-in users can do anything_.

Built-in node::
Users with limited permissions link:/doc/book/security/controller-isolation/[must not be able to configure jobs that run on the built-in node].
When setting up a new Jenkins instance, adding users and switching authorization strategies, it is important to also set up distributed builds and limit what jobs are able to run on the built-in node.

//In addition to the above items that discuss who may (effectively) be granted administrative access to Jenkins, you should be careful who you give any read access to Jenkins.
//See link:/doc/book/security/access-control/permissions/#overall-read[the documentation of the level of access that granting basic read access gives].

== Permissions

At a very basic level, the _Overall/Read_ permission provides users some basic access to Jenkins.
This permission is a prerequisite for more substantial access to Jenkins.
Without this permission, only very few features explicitly intended to be used without authentication are available.

The highest level of permissions is _Overall/Administer_.
With this permission, users can upload and install plugins and have access to the link:/doc/book/managing/script-console/[Script Console].

Between these two extremes is finer-grained permission control involving other permissions.
Permissions in Jenkins have a _scope_: They can be granted globally, on an item (like a folder or job), on a build, etc.
Whenever a user attempts to do something that is protected by permissions, the authorization strategy is checked for whether the current user has the specific permission (e.g., _Job/Read_) on the specific object (e.g., a job).
Exactly how permissions are assigned and whether and how they're inherited is controlled by the specific authorization strategy.

As an example, plugin:matrix-auth[Matrix Authorization Strategy] provides two different authorization strategies:

* One provides a single global configuration of all permissions.
  A user granted _Item/Read_ will be granted that permission everywhere.
* One provides a project-based configuration.
  In this model, permissions can be granted globally (as in the previous strategy), or only on specific folders, jobs, or agents.
  Permissions are by default inherited, but that can be customized as well, so that users granted _Item/Read_ globally or on a parent folder may be excluded from access to a job.

For more details about the various permissions in Jenkins and the level of access they grant, see link:/doc/book/security/access-control/permissions/[Permissions].

== Disabling Access Control

See link:/doc/book/security/access-control/disable/[Disable Access Control].
