---
title: Background Concepts
layout: section
---

To properly manage the security of your Jenkins instance, you should be familiar with:

* Security principles that should guide all your decisions
* How Jenkins executes a Freestyle or Pipeline job
If you understand the vulnerabilities that an intrusion could exploit, you can better understand how to protect against those intrusions.

## Security Principles

Security principles should guide the practices and tools used to fight and prevent threats.
The major principles for security are:

* *Least privilege:*
Give people the privileges required to do their jobs but do not give everyone permission to do everything and do not open ports that are not required for your work.

* *Know the system:*
The more you understand about how your system works, the more you are prepared to protect the integrity of your system.

* *Defense in depth:*
Systems are layered.
Put security on all layers.

* *Prevention is good, but detection is better:*
Monitor your Jenkins installation constantly so that you quickly detect signs of a security breach.

* *Keep your system current:*
Pay attention to link:/security/advisories/[Security Advisories] and apply link:/security/for-administrators/#how-quickly-should-i-apply-security-updates[Security Updates] as soon as possible.
Keeping the Jenkins software and all plugins current also helps ensure that your system is secure.

* *Revisit your security configuration periodically:*
Most Jenkins environments grow over time, requiring their trust models to evolve as the environment grows.
Schedule regular "check-ups" of your security settings to ensure that they are still appropriate for your instance.
In particular, if you had to disable some of the default protections that Jenkins provides,
perhaps because you were using a plugin that had not been updated to support that protection, you may be able to re-enable that protection to increase the security of your instance.


== How Jenkins Executes Jobs

A simple overview of how Jenkins executes a Freestyle or Pipeline job helps to understand the security considerations.

By default, a job executes with the full privileges of the Jenkins administrator, although you can configure Jenkins to execute jobs with fewer privileges.
All of the job's logic, the Groovy conditionals, loops, and so forth execute on the controller.

When the job runs:

* Jenkins creates a _workspace_ on the controller for each build that runs.
Files for that build are stored in the workspace.
* The job calls a series of _steps_, each of which is a script or command that does the real work and mostly executes using an _executor_ on an _agent_.

The agent:

* Writes some files to the local node.
* Sends data back to the controller.
* May also request information from the controller.

Many different people have some control over the commands that are executed during a build:

* Jenkins users with Job/Configure permission
* Authors of build scripts such as `pom.xml` and `Makefile`
* Authors of code, such as test suites that are executed during a build

Any of these could introduce security issues, either deliberately or accidentally.
In addition, supply chain attacks can occur on build dependencies, whereby attackers take over control of NPM or Maven packages and insert malicious code.

You can see the complexity of keeping your Jenkins instance secure.
In the following sections we discuss specific protections that Jenkins provides and practices that you can implement to protect Jenkins from intrusions.



