---
title: Credentials
layout: section
---
ifdef::backend-html5[]
:toc:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
:hide-uri-scheme:
endif::[]

Use credentials to secure access to
external sites and applications that can interact with Jenkins such as artifact repositories, cloud-based storage systems and services, and databases.
This is both more secure and more convenient that hard coding username and password or other authentication devices in each Pipeline.

== Working with Credentials

Implementing credentials has two elements:

* Configure the credential. See
link:/doc/book/using/using-credentials/#configuring-credentials[Configuring Credentials]
on the
link:/doc/book/using/using-credentials/[Using Credentials]
page.

* Call credentials in the Pipeline to gain access to an external resource.
See
link:/doc/book/pipeline/jenkinsfile/#handling-credentials[Handling Credentials
on the
link:/doc/book/pipeline/jenkinsfile/[Using a Jenkinsfile]
page.

== Best Practices for Credentials

Need some good advice added here.
I have listed some possible topics as a start but feel free to override.

* Limit number of people with *Credentials > Create* permissions.
* Modify the underlying credentials (username/password, secret text, etc) frequently.
* Restrict access to each credential to the project, item, or user as appropriate.

