---
layout: chapter
title: Securing Jenkins
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
endif::[]

Jenkins is used everywhere -- from workstations on corporate intranets
to high-powered servers connected to the public internet.
It is critically important to keep your Jenkins instance secure,
both to protect your information and to avoid executing malicious code from your Jenkins instance.

Your Jenkins environment is a fully-distributed build system.
Each network connection is a potential point of entry.
Remember that the code that runs your builds can be perverted to run anything!

Jenkins and the Pipelines it runs must be able to do almost anything.
This means that a malicious Pipeline could reconfigure the Jenkins instance,
delete files, or launch various forms of mischief
such as a DDoS attack pr a bot.
In addition to deliberate and direct attacks on your environment,
a trusted user could visit an infected web site
and accidentally introduce malicious code into the Jenkins instance.

Jenkins includes configurable features to secure your Jenkins instance
against the various security and threat profiles.
The setup wizard enables many of the security options by default,
to ensure that Jenkins is secure.
Other security options involve environment-specific setup and trade-offs
and depend on specific use cases supported for individual Jenkins instances.
Configuration options allow you to enable, customize, or disable security features.

This chapter introduces the various security options available to Jenkins administrators and users,
explaining the protections offered, and trade-offs to disabling some of them.

== Security Principles

Security principles should guide the practices and tools used to fight and prevent threats.
The major principles for security are:

* *Least privilege:*
Give people the privileges required to do their jobs
but do not give everyone permission to do everything
and do not open ports that are not required for your work.

* *Know the system:*
The more you understand about how your system works,
the more you are prepared to protect the integrity of your system.

* *Defense in depth:*
Systems are layered.
Put security on all layers.

* *Prevention is good, but detection is better:*
Monitor your Jenkins installation constantly
so that you quickly detect signs of a security breach.

* *Keep your system current:*
Pay attention to
link:https://www.jenkins.io/security/advisories/[Security Advisories]
and apply
link:https://www.jenkins.io/security/for-administrators/#how-quickly-should-i-apply-security-updates[Security Updates]
as soon as possible!
Keeping the Jenkins software and all plugins current
also helps ensure that your system is secure.

== How Jenkins Executes a Pipeline

A simple overview of how Jenkins executes a Pipeline
helps to understand the security considerations.

By default, a Pipeline executes with the full privileges of the Jenkins administrator,
although you can configure Jenkins to execute Pipelines with fewer privileges.
All of the Pipeline logic, the Groovy conditionals, loops, and so forth execute on the controller.

When a Pipeline runs:

* Jenkins creates a _workspace_ on the controller
for each build that runs.
Files for that build are stored in the workspace..
* The Pipeline calls a series of _steps_,
each of which is a script or command that does the real work
and mostly executes using an _executor_ on an _agent_.

The agent:

* Writes some files to the local node.
* Sends data back to the controller.
* May also request information from the controller.

Many different people have some control over
the commands that are executed during a build:

* Jenkins users with Job/Configure permission
* Authors of build scripts such as `pom.xml` and `Makefile`
* Authors of code, such as test suites that are executed during a build

Any of these could introduce security issues, either deliberately or accidentally.
In addition, supply chain attacks can occur on build dependencies,
whereby attackers take over control of NPM or Maven packages and insert malicious code.

You can see the complexity of keeping your Jenkins instance secure.
In the following sections we discuss specific protections that Jenkins provides
and practices that you can implement to protect Jenkins from intrusions.

== Agents and Security

To ensure the stability of the Jenkins controller,
builds should be executed on other nodes than the built-in node.
This concept is called _distributed builds_ in Jenkins;
you can learn more about this https://wiki.jenkins.io/display/JENKINS/Distributed+builds[here].
Setting up distributed builds in Jenkins is a great start
for protecting the Jenkins controller from malicious (or just broken) build scripts,
but care needs to be taken for protections to be effective.

Never run builds on the Jenkins controller in production environments.
A build job that uses an agent running on the built-in controller node
has access to Jenkins controller files and configuration, which poses a security risk.
Configuring Jenkins as a distributed system,
where builds execute on agents that are separate from the controller
instead of the built-in node on the controller,
enhances the security of your Jenkins instance
as well as improving its performance and making it more stable.

An agent that executes on the Jenkins controller
may be able to access Jenkins configuration files and the workspaces of other builds.
An agent could also request information
that belongs to other teams or organizations that share the controller.

An agent can also write malicious code to its local disk so that the node is tainted.
For maximum security, run all builds on ephemeral agents in the cloud
that are destroyed at the end of each build job.

NOTE: A job that performs administrative tasks such as backups may run on the controller,
but be sure to label the executor and only allow it to be used by jobs that specify that label.

// TODO the following only makes sense on the web site, not the PDF. Can it be disabled there?
// TODO the material below should be moved to other sections in this chapter.

== Basic Setup

link:controller-isolation[Controller Isolation]::
Builds should not be executed on the built-in node, but that is just the beginning:
This section discusses what other steps can be taken to protect the controller from being impacted by running builds. +
*This needs to be configured according to the needs of your environment.*

link:access-control[Access Control]::
By default, Jenkins does not allow anonymous access, and a single admin user exists.
This chapter discusses which level of access is provided by permissions and how to safely grant access to more users. +
_This is set up securely by the setup wizard. If the setup wizard is disabled on first launch, this may not be configured securely by default._


== Build Behavior

link:build-authorization[Access Control for Builds]::
Learn how to restrict what individual builds can do in Jenkins once they're running. +
*This needs to be configured according to the needs of your environment.*

link:environment-variables[Handling Environment Variables]::
Improperly written build scripts may be tricked into behaving differently than intended due to special environment variable names or values being injected as build parameters.
This section discusses how to protect your builds. +
*This needs to be configured according to the needs of your environment.*


== User Interface

link:csrf-protection[CSRF Protection]::
Jenkins protects from cross-site request forgery (CSRF) by default.
This chapter explains how to work around any problems this may cause. +
_This is set up securely by default._
// TODO Confirm that skipping the setup wizard in 2.222 does no longer disable CSRF protection

link:markup-formatter[Markup Formatter]::
The default markup formatter renders text as entered (i.e. escaping HTML metacharacters).
This chapter explains how to switch to a different markup formatter and explains what admins need to be aware of. +
_This is set up securely by default._

link:user-content[Rendering User Content]::
By default, Jenkins strictly limits the features useable in user content (files from workspaces, archived artifacts, etc.) it serves.
This chapter discusses how to customize this and make HTML reports and similar content both functional and safe to view. +
_This is set up securely by default._
