---
layout: gsocproject
title: "Jenkins X: Consolidate the use of Apps / Addons"
goal: "Consolidate Apps and Addons inside Jenkins X"
category: Jenkins X
year: 2020
status: "Active"
student: nodece
mentors:
- "marckk"
- "jstrachan"
- "nehagup"
- "sharepointoscar"
- "nikhildarocha"
- "sahilrkalra"
tags:
- gsoc2020
- jenkins-x
links:
  chat: https://jenkins-x.io/community/#slack
  draft: https://docs.google.com/document/d/1Ph-Jo8KGYzTLMXLIDJQB6XbVcnILETfXEMXXczrxb4s/edit?usp=sharing
  idea: /projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation
---

The current CLI supports `apps` and `addons`. `Addons` were either generic helm charts or a combination of helm chart plus some custom go code to install and integrate them with the Jenkins X platform. `Apps` framework which provided a more generic way of adding charts chatting to Jenkins X such that anybody could create an app without having to modify the underlying jx code. But now left developers with confusion over what an APP is. Developers think the `apps` is they are developing.

=== Deliverables

The main aim of the project would be to consolidate `Apps` and `Addons` inside Jenkins X to avoid confusion. Everything as an `App` and deprecate the use of the word `Addon`.

`App` includes system charts like knative, gloo, nginx-controller, flagger, prometheus, external-dns, cert-manager.

Implement `jx add app` and `jx delete app` to update the `App`.

=== Phase 1

I'll add new commands to jx by transfer the `add addon` command to the `add app`.

The following commands will be supported:

* jx add app kubeless
* jx add app anchore
* jx add app owasp-zap
* jx add app gitea 
* jx add app environment 
* jx add app flagger
* jx add app gloo
* jx add app ingress
* jx add app istio
* jx add app ambassador 
* jx add app pipeline-events
* jx add app prometheus
* jx add app prow

=== Phase 2

I'll add new commands to jx by transfer the `delete addon` command to the `delete app`.

The following commands will be supported:

* jx delete app environment 
* jx delete app flagger
* jx delete app gitea 
* jx delete app ingress
* jx delete app istio

=== Phase 3
* Resolve the issues and bugs in development
* Write users documentation
* Write developer documentation
* Submit my work to the mentor and ask for feedback then resolve the feedback

=== Issues

* https://github.com/jenkins-x/jx/issues/6096

=== References
* https://jenkins.io/projects/gsoc/2020/project-ideas/jenkins-x-apps-consolidation/