---
layout: gsocproject
title: "Machine Learning Plugins for Data Science"
goal: "Create a new plugin for integrating Jenkins with one of Machine Learning tools (e.g. Jupyter Python, TensorBoard, or Sacred)"
category: Plugins
year: 2020
status: "Completed"
sig: pipeline-authoring
student: loghijiaha
mentors:
- "kinow"
- "imoutsatsos"
 - "markyjackson-taulia"
- "shivaylamba"
tags:
- gsoc2020
- machine-learning
- data-science
links:
  gitter: "jenkinsci_gsoc-machine-learning-project:gitter.im"
  draft: /projects/gsoc/2020/projects/machine-learning-draft.pdf
  idea: /projects/gsoc/2020/project-ideas/machine-learning
---

The main goal of this project is integrating Machine Learning workflow including Data preprocessing, Model Training, Evaluation and Prediction with Jenkins build tasks. This plugin will be capable of executing code fragments via IPython kernel as currently supported by Jupyter Notebook. Version control will be handled as an added advantage of this project.

More details are in the link:/projects/gsoc/2020/projects/machine-learning-draft.pdf[draft project idea].

=== Deliverables

* An IPython plugin with pipeline compatible
* Improved config.jelly for the plugin
* File parsers for ipynb, py and text(containing python code) files
* Code segment extractor
* Implement a code editor
* Output console with static visual components

=== Community Bonding

The community bonding period is all about, well, community bonding. Rather than jumping straight into coding, I've got some time to learn about Jenkins's processes - release and otherwise - developer interactions, codes of conduct, etc.

- Blog post
** link:/blog/2020/06/03/machine-learning-plugin-community-bonding/[Community Bonding summary]

=== Phase 1

* Implement the configuration part of Ipython kernel interpreter
* Implement file parser
* Improve current config.jelly
* Improve form validations
* Increase the test coverage and documentation

* Blog post
** link:/blog/2020/06/30/machine-learning-plugin-coding-phase1/[Coding Phase 1 summary]

* Change log
** link:https://github.com/jenkinsci/machine-learning-plugin/blob/master/CHANGELOG.md#machine-learning-01-alpha-1-2020-06-30[Change log for alpha 1 release]

=== Phase 2

* Implement code editor
* Extend the editor for test purposes with pre-tested codelets
* Testing and bug fixing
* Improve the documentation
* Discuss with mentors about phase 3 coding

* Blog post
** link:/blog/2020/07/27/machine-learning-plugin-coding-phase2/[Coding Phase 2 summary]

* Change log
** link:https://github.com/jenkinsci/machine-learning-plugin/blob/master/CHANGELOG.md#machine-learning-01-alpha-2-2020-07-24[Change log for alpha 2 release]

=== Phase 3

* Design and implement code extractor
* Multiple language kernel support
* Implement Visual generator for the results
* Integrate whole previous work and testing
* Git integration for code segments (optional)
* User documentation and examples

* Blog post
** link:/blog/2020/08/27/machine-learning-plugin-coding-phase3/[Coding Phase 3 summary]

* Change log
** link:https://github.com/jenkinsci/machine-learning-plugin/blob/master/CHANGELOG.md#machine-learning-101-2020-08-24[Change log for v1.0.1 release]

=== Future Improvements

* Improving performance of the plugin
* Try to implement jira:JENKINS-63377[]
* Support parameterized definitions in Notebooks jira:JENKINS-63478[]
* Increasing testing code coverage
* Implementing Interactive visualizer for data sets and results.

=== Final Demo Presentation Slides and Video

https://docs.google.com/presentation/d/10ai1DNsMroEr-QeZfIarp0_oDzhgONGnq6BsAciBwb0/edit?usp=sharing[Final Machine Learning Plugin slides]

https://www.youtube.com/watch?v=IL4a_uQNV5o&t=229s[Final GSoC Demo]

=== Articles

https://medium.com/analytics-vidhya/embed-jupyter-notebook-into-static-webpages-locally-79e8a6f9f987[Jupyter Notebook Integration ] +

=== Weekly Meeting Sync

  * Monday
  * Time - 03:00 am (UTC)

=== Other links
https://github.com/jenkinsci/machine-learning-plugin.git[Github] +
https://plugins.jenkins.io/machine-learning/[Plugin page] +
https://docs.google.com/document/d/1Y-BDKJHRCo5OvmAdiwgCqUsqZoxsh6Vsw8i-Ps2mb8E/edit?usp=sharing_eil&ts=5eb5cfb0[Meeting Notes] +
https://docs.google.com/document/d/1ASVMOO-dGG52p18XiKNLHqcIQHjY1iGJTeQ4BZdnqw8/edit?usp=sharing[GSoC Proposal] +
https://docs.google.com/spreadsheets/d/1QNJR0eXEdIV7PtqRP5vbR2qCWw-3geIfApmb9V0nJQ4/edit?usp=sharing[Timeline] +
https://docs.google.com/document/d/10FjktNmWpdjgbGg3tEViadV_JNevn9W0sMOu-bF8m-o/edit?usp=sharing[Design Document] +
