---
layout: gsocproject
title: "Machine Learning Plugins for Data Science"
goal: "Create a new plugin for integrating Jenkins with one of Machine Learning tools (e.g. Jupyter Python, TensorBoard, or Sacred)"
category: Plugins
year: 2020
status: "Active"
sig: pipeline-authoring
student: loghijiaha
mentors:
- "kinow"
- "imoutsatsos"
- "markyjackson-taulia"
- "shivaylamba"
tags:
- gsoc2020
- machine-learning
- data-science
links:
  gitter: "jenkinsci/gsoc-machine-learning-project"
  draft: https://docs.google.com/document/d/1YaQfzvYV2G-wby2jcOzITKveaowTXMN77fkMq5hBe6E/edit?usp=sharing
  idea: /projects/gsoc/2020/project-ideas/machine-learning
---

The main goal of this project is integrating Machine Learning workflow including Data preprocessing, Model Training, Evaluation and Prediction with Jenkins build tasks. This plugin will be capable of executing code fragments via IPython kernel as currently supported by Jupyter Notebook. Version control will be handled as an added advantage of this project.

=== Deliverables

* An IPython plugin with pipeline compatible
* Improved config.jelly for the plugin
* File parsers for ipynb, py and text(containing python code) files
* Code segment extractor 
* Implement a code editor
* Output console with static visual components

=== Comunity Bonding

The community bonding period is all about, well, community bonding. Rather than jumping straight into coding, I've got some time to learn about Jenkins's processes - release and otherwise - developer interactions, codes of conduct, etc.

- Blog post 
** link:/content/blog/2020/05/2020-05-31-machine-learning-plugin-community-bonding.adoc[Community Bonding summary]

=== Phase 1

* Implement the configuration part of Ipython kernel interpreter
* Implement file parser
* Improve current config.jelly
* Improve form validations
* Increase the test coverage and documentation

=== Phase 2

* Implement code editor 
* Extend the editor for test purposes with pre-tested codelets
* Testing and bug fixing
* Improve the documentation
* Discuss with mentors about phase 3 coding

=== Phase 3

* Design and implement code segment extractor 
* Implement JSON generator for the results
* Integrate whole previous work and testing
* Git integration for code segments (optional)
* User documentation and examples

=== Future Improvements

* Writing developer documentation
* Git integration on plugin if not implemented during coding phase.
* Implementing Interactive visualizer for data sets and results.
* Community discussions and design to integrate other kernels with Jenkins 

=== Articles

https://medium.com/analytics-vidhya/embed-jupyter-notebook-into-static-webpages-locally-79e8a6f9f987[Jupyter Notebook Integration ] +

=== Weekly Meeting Sync

  * Monday
  * Time - 03:00 am (UTC)

=== Other links

https://docs.google.com/document/d/1Y-BDKJHRCo5OvmAdiwgCqUsqZoxsh6Vsw8i-Ps2mb8E/edit?usp=sharing_eil&ts=5eb5cfb0[Meeting Notes] +
https://docs.google.com/document/d/1ASVMOO-dGG52p18XiKNLHqcIQHjY1iGJTeQ4BZdnqw8/edit?usp=sharing[GSoC Proposal] +
https://docs.google.com/spreadsheets/d/1QNJR0eXEdIV7PtqRP5vbR2qCWw-3geIfApmb9V0nJQ4/edit?usp=sharing[Timeline] +
https://docs.google.com/document/d/10FjktNmWpdjgbGg3tEViadV_JNevn9W0sMOu-bF8m-o/edit?usp=sharing[Design Document] +
