---
layout: gsocproject
title: "Jenkins Windows Services: YAML Configuration Support"
goal: "Enhance Jenkins master and agent service management on Windows by offering new configuration file formats and improving settings validation"
category: Core, Tools
year: 2020
status: "Active"
sig: platform
student: buddhikac96
mentors:
- "oleg_nenashev"
- "mikecirioli"
- "nextturn"
tags:
- gsoc2020
- windows
- windows-services
links:
  draft: https://drive.google.com/file/d/1G2cOaRb-Mle_Fl7YVAzlVITDgrN6eCbE/view?usp=sharing
  gitter: winsw/winsw
  idea: /projects/gsoc/2020/project-ideas/winsw-yaml-config-support
---

// TODO: add details here, cannot embed draft due to wrong format

On Windows machines, Jenkins master and agents can be installed as Windows Services in order to get better robustness and manageability within the system.
This is a functionality bundled into the Jenkins core directly.
When installed as a service, Jenkins uses the Windows Service Wrapper executable (.NET, written in C#) which is being configured by XML config files.
Currently, there are only a few configuration checks there (no XML Schema, limited validation, etc.),
and it’s often that the service wrapper is misconfigured by Jenkins users.

In this project we propose to update Windows Service Wrapper to support YAML files as configuration inputs and to introduce better configuration validation during the service installation and startup.
Usage of YAML should simplify configuration management in Jenkins, especially when automated tools are used.

=== Deliverables

* Service Descriptor : YAML Support
* Validations for Configs
* Schema validation for YAML (JSON)
* Unit Test for Validations
* Project Guideline Documentation
* Informative logger
* Sample YAML config files
** Sample-alloption.yaml
** Sample-minimal.yaml

=== Phase 1
* YAML service Descriptor
* Start implementing configurations verification on startup
* Project Guideline documentation
* Blog Post 1

=== Phase 2
* Finish configurations verification on startup
* Start implementing YAML schema validation
* Minimal Viable Product will be released
* Blog Post 2

=== Phase 3
* Finish YAML schema validation
* Sample YAML config files
* Blog Post 3

During each phases respective unit test will be added to existing Unit Test library.

=== Future Improvements
* Complete developer guide for YAML support service descriptor.
* Complete user documentation for Config validations. + 

If time allows both will be delivered in Phase 3

=== Articles
* https://medium.com/runtimeerror/path-to-gsoc-2021-e6a81e62308d[Path to GSoC2021 @ *Medium*]


=== Office hours

Office hours are scheduled every Tuesday at *13:30 UTC* in the project's Gitter chat.
Meeting notes are available https://docs.google.com/document/d/1eq1M1buaEMmRQ3XLFRFnTbJpRnHu1fnqxmTHPKm8WjU/edit?usp=sharing[here] to read.

See the link:https://drive.google.com/file/d/1G2cOaRb-Mle_Fl7YVAzlVITDgrN6eCbE/view?usp=sharingp[GSoC Project application draft] for more details.
