---
layout: subsection
---

ifdef::backend-html5[]
ifndef::env-github[:imagesdir: ../../../resources/managing]
:notitle:
:description:
:author:
:email: jenkinsci-users@googlegroups.com
:sectanchors:
:toc: left
endif::[]

= Java

[pass]
++++
<!-- Redirect anchor references with Javascript -->
<!-- This is ONLY for anchor references like installing/#windows. -->
<!-- Use redirects as described in the contributing guide for page level redirects. -->
<!-- https://stackoverflow.com/questions/1305211/javascript-to-redirect-from-anchor-to-a-separate-page/21198129#21198129 -->
<script>
(function () {
    var anchorMap = {
        "ji-toolbar" : "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/", /* Algolia search redirect to stay on same page */

        "running-jenkins-behind-apache": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-apache/",
        "running-jenkins-behind-haproxy": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-haproxy/",
        "running-jenkins-behind-iis": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iis/",
        "running-jenkins-behind-iptables": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-iptables/",
        "running-jenkins-behind-nginx": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-nginx/",
        "running-jenkins-behind-squid": "/doc/book/system-administration/reverse-proxy-configuration-with-jenkins/reverse-proxy-configuration-squid/",
        "troubleshooting": "/doc/book/system-administration/reverse-proxy-configuration-troubleshooting/",
        "jenkins-says-my-reverse-proxy-setup-is-broken": "/doc/book/system-administration/reverse-proxy-configuration-troubleshooting/",
    }
    /*
    * Best practice for extracting hashes:
    * https://stackoverflow.com/a/10076097/151365
    */
    var hash = window.location.hash.substring(1);
    if (hash) {
        /*
        * Best practice for javascript redirects:
        * https://stackoverflow.com/a/506004/151365
        */
        window.location.replace(anchorMap[hash]);
    }
})();
</script>
++++

Jenkins has Java requirements and guides on how to upgrade your Java version:

* link:/doc/book/platform-information/java/java[Java requirements]
* link:/doc/book/platform-information/java/upgrade-java-guidelines[Upgrade Java from 8 to 11]
* link:/doc/book/platform-information/java/upgrade-java-to-17[Upgrade Java from 11 to 17]
