---
layout: project
title: "Contributor Summit"
sigId: "advocacy-and-outreach"
tags:
  - outreach-programs
  - community
  - events
links:
  gitter: jenkinsci/jenkins
---

The Jenkins Contributor Summit brings together current and future contributors to the Jenkins project.
The summit brings together community members to learn, meet, and help shape the future of Jenkins.

=== Online Contributor Summit on June 25, 2021

The next contributor summit will take place on June 25, 2020.
This will be an online event, full schedule will be published later.
See link:https://groups.google.com/u/1/g/jenkinsci-dev/c/Tg3_pmHd5dE[this discussion] for more information and the draft agenda.

=== Previous events

* link:/blog/2021/02/16/contributor-summit-online/[Online Contributor Summit on Feb 23-25, 2011] 
* link:https://www.meetup.com/jenkinsmeetup/events/267684785/[2020 contributor summit at FOSDEM]
* link:/blog/2019/08/25/jenkinsworld-contrib-summit-ask-the-expert-booth/[2019 contributor summit blog post]
* link:/blog/2018/10/18/contributor-summit-summary/[2018 contributor summit summary]
* link:https://www.meetup.com/jenkinsmeetup/events/236370750/[2017 contributor hackathon]
* link:https://www.meetup.com/jenkinsmeetup/events/227463345/[2016 contributor summit at FOSDEM]
