name: CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        #!/usr/bin/env bash
        set -o errexit
        set -o nounset
        set -o pipefail
        set -o xtrace
        make all
        illegal_htaccess_content="$( find content -name '.htaccess' -type f -exec grep --extended-regexp --invert-match '^(#|ErrorDocument)' {} \; )"
        if [[ -n "$illegal_htaccess_content" ]] ; then
          echo "Failing build due to illegal content in .htaccess files, only ErrorDocument is allowed:" >&2
          echo "$illegal_htaccess_content" >&2
          exit 1
        fi
