name: "Label conflicting PRs"
on:
  push:
  pull_request_target:
    types: [synchronize]

permissions:
  pull-requests: write

jobs:
  main:
    if: github.event.pull_request.user.login != 'dependabot[bot]' && github.event.pull_request.user.login != 'jenkins-infra-changelog-generator' && github.repository_owner == 'jenkins-infra'
    runs-on: ubuntu-latest
    steps:
      - name: Label conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@1df065ebe6e3310545d4f4c4e862e43bdca146f0 # v3.0.3
        with:
          dirtyLabel: "unresolved-merge-conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Please take a moment and address the merge conflicts of your pull request. Thanks!"
          continueOnMissingPermissions: true
