////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the _run-jenkins-in-docker.adoc page used in the tutorials.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker.adoc (used in index.adoc).
////


==== On macOS and Linux

. Open up a terminal window.
. Customise official Jenkins Docker image, by executing below two steps:
.. Create Dockerfile with the folloing content:
+
[source]
----
FROM jenkins/jenkins:2.249.1-lts
USER root
RUN apt-get update && apt-get install -y \
       apt-transport-https \
       ca-certificates \
       curl \
       gnupg2 \
       software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable"
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN /usr/local/bin/install-plugins.sh blueocean:1.24.0

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
----
.. Build a new docker image from this Dockerfile and assign the image meaningful name, e.g. "myjenkins:1.0":
+
[source]
----
docker build -t "myjenkins:1.0" .
----
Keep in mind that described above process will automatically download official Jenkins Docker image 
if this hasn't been done before.

. Run your own `myjenkins:1.0` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/run/[`docker run`]
  command:
+
[source]
----
docker run --rm -u root --name jenkins-tutorial \
  --volume jenkins-data:/var/jenkins_home \ # <1>
  --volume "$HOME":/home \ # <2>
  --volume /var/run/docker.sock:/var/run/docker.sock \ # <3>
  --publish 8080:8080 myjenkins:1.0
----
<1> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`.
<2> Maps the `$HOME` directory on the host (i.e. your local) machine (usually
the `/Users/<your-username>` directory) to the `/home` directory in the
container.
<3> Enables socket communication for the docker image.

+
*Note:* If copying and pasting the command snippet above doesn't work, try
copying and pasting this annotation-free version here:
+
[source]
----
docker run --rm -u root --name jenkins-tutorial \
  --volume jenkins-data:/var/jenkins_home \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume "$HOME":/home --publish 8080:8080 myjenkins:1.0
----
. Proceed to the <<setup-wizard,Setup wizard>>.


==== On Windows

The Jenkins project provides a Linux container image, not a Windows container image.
Be sure that your Docker for Windows installation is configured to run `Linux Containers` rather than `Windows Containers`.
See the Docker documentation for instructions to link:https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers[switch to Linux containers].
Once configured to run `Linux Containers`, the steps are:

. Open up a command prompt window.
. Customise official Jenkins Docker image using the <<on-macos-and-linux,macOS
and Linux>> instructions above.

. Run your own `myjenkins:1.0` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/run/[`docker run`]
  command:
+
[source]
----
docker run --rm -u root --name jenkins-tutorial ^
  --volume jenkins-data:/var/jenkins_home ^
  --volume "%HOMEDRIVE%%HOMEPATH%":/home ^
  --volume /var/run/docker.sock:/var/run/docker.sock ^
  --publish 8080:8080 myjenkins:1.0
----
. Proceed to the <<setup-wizard,Setup wizard>>.


==== Accessing the Docker container

If you have some experience with Docker and you wish or need to access your
Docker container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`]
command, you can add an option like `--name jenkins-tutorial` to the `docker exec` command.
That will access the Jenkins Docker container named "jenkins-tutorial".

This means you could access your docker container (through a separate
terminal/command prompt window) with a `docker exec` command like:

`docker exec -it jenkins-tutorial bash`
