////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the index.adoc page used in the general 'Installing Jenkins'
page.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker-for-tutorials.adoc (used in
_run-jenkins-in-docker.adoc).
////


===== On macOS and Linux

. Open up a terminal window.
. Download the `jenkinsci/blueocean` image and run it as a container in Docker
  using the following
  link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
  command:
+
[source,bash]
----
docker run \
  -u root \
  --rm \  # <1>
  -d \ # <2>
  -p 8080:8080 \ # <3>
  -v jenkins-data:/var/jenkins_home \ # <4>
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkinsci/blueocean # <5>
----
<1> ( _Optional_ ) Automatically removes the Docker container (which is the
instantiation of the `jenkinsci/blueocean` image below) when it is shut down.
This keeps things tidy if you need to quit Jenkins.
<2> ( _Optional_ ) Runs the `jenkinsci/blueocean` container in the background
(i.e. "detached" mode) and outputs the container ID. If you do not specify this
option, then the running Docker log for this container is output in the terminal
window.
<3> Makes (i.e. "publishes") port 8080 of the `jenkinsci/blueocean` container to
port 8080 on the host machine. The 1st number represents the port on the host
while the 2nd represents the container's port. Therefore, if you specified `-p
49001:8080` for this option, you would be accessing Jenkins on your host machine
through port 49001.
<4> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`. If this volume does not exist, then this `docker run` command
will automatically create the volume for you. +
*Notes:*
This volume could also be created independently using the
link:https://docs.docker.com/engine/reference/commandline/volume_create/[`docker
volume create`] command: +
`docker volume create jenkins-data` +
Instead of mapping the `/var/jenkins_home` directory to a Docker volume, you
could also map this directory to one on your machine's local file system. For
example, specifying the option +
`-v $HOME/jenkins:/var/jenkins_home` would map the container's
`/var/jenkins_home` directory to the `jenkins` subdirectory within the `$HOME`
directory on your local machine, which would typically be
`/Users/<your-username>/jenkins` or `/home/<your-username>/jenkins`.
<5> The `jenkinsci/blueocean` Docker image itself. If this image has not already
been downloaded, then this `docker run` command will automtically download the
image for you. Furthermore, if any updates to this image were published since
you last ran this command, then running this command again will automatically
download these published image updates for you. +
*Note:* This Docker image could also be downloaded (or updated) independently
using the
link:https://docs.docker.com/engine/reference/commandline/pull/[`docker pull`]
command: +
`docker pull jenkinsci/blueocean`
+
*Note:* If copying and pasting the command snippet above does not work, try
copying and pasting this annotation-free version here:
+
[source,bash]
----
docker run \
  -u root \
  --rm \
  -d \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkinsci/blueocean
----
. Proceed to the <<setup-wizard,Post-installation setup wizard>>.


===== On Windows

. Open up a command prompt window.
. Download the `jenkinsci/blueocean` image and run it as a container in Docker
  using the following
  link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
  command:
+
[source]
----
docker run ^
  -u root ^
  --rm ^
  -d ^
  -p 8080:8080 ^
  -v jenkins-data:/var/jenkins_home ^
  -v /var/run/docker.sock:/var/run/docker.sock ^
  jenkinsci/blueocean
----
For an explanation of each of these options, refer to the <<on-macos-and-linux,
macOS and Linux>> instructions above.
. Proceed to the <<setup-wizard,Post-installation setup wizard>>.


==== Accessing the Jenkins/Blue Ocean Docker container

If you have some experience with Docker and you wish or need to access the
`jenkinsci/blueocean` container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`]
command, you can add an option like `--name jenkins-blueocean` (with the
link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
above), which would give the `jenkinsci/blueocean` container the name
"jenkins-blueocean".

This means you could access the container (through a separate terminal/command
prompt window) with a `docker exec` command like:

`docker exec -it jenkins-blueocean bash`


==== Accessing the Jenkins console log through Docker logs

There is a possibility you may need to access the Jenkins console log, for
instance, when <<unlocking-jenkins,Unlocking Jenkins>> as part of the
<<setup-wizard,Post-installation setup wizard>>.

If you did not specify the detached mode option `-d` with the `docker run ...`
command <<downloading-and-running-jenkins-in-docker,above>>, then the Jenkins
console log is easily accessible through the terminal/command prompt window from
which you ran this Docker command.

Otherwise, you can access the Jenkins console log through the
link:https://docs.docker.com/engine/reference/commandline/logs/[Docker logs] of
the `jenkinsci/blueocean` container using the following command:

`docker logs <docker-container-name>`

Your `<docker-container-name>` can be obtained using the
link:https://docs.docker.com/engine/reference/commandline/ps/[`docker ps`]
command. If you specified the +
`--name jenkins-blueocean` option in the `docker run ...` command above (see
also
<<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue
Ocean Docker container>>), you can simply use the `docker logs` command:

`docker logs jenkins-blueocean`


==== Accessing the Jenkins home directory

There is a possibility you may need to access the Jenkins home directory, for
instance, to check the details of a Jenkins build in the `workspace`
subdirectory.

If you mapped the Jenkins home directory (`/var/jenkins_home`) to one on your
machine's local file system (i.e. in the `docker run ...` command
<<downloading-and-running-jenkins-in-docker,above>>), then you can access the
contents of this directory through your machine's usual terminal/command prompt.

Otherwise, if you specified the `-v jenkins-data:/var/jenkins_home` option in
the `docker run ...` command, you can access the contents of the Jenkins home
directory through the `jenkinsci/blueocean` container's terminal/command prompt
using the
link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`]
command:

`docker exec -it <docker-container-name> bash`

As mentioned <<accessing-the-jenkins-console-log-through-docker-logs,above>>,
your `<docker-container-name>` can be obtained using the
link:https://docs.docker.com/engine/reference/commandline/ps/[`docker ps`]
command. If you specified the +
`--name jenkins-blueocean` option in the `docker run ...`
command above (see also
<<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue
Ocean Docker container>>), you can simply use the `docker exec` command:

`docker exec -it jenkins-blueocean bash`

////
Might wish to add explaining the `docker run -t` option, which was covered in
the old installation instructions but not above.

Also mention that spinning up a container of the `jenkinsci/blueocean` Docker
image can be done so with all the same
https://github.com/jenkinsci/docker#usage[configuration options] available to
the other images published by the Jenkins project.

Explain colon syntax on Docker image references like
`jenkinsci/blueocean:latest'.
////
