////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the index.adoc page used in the general 'Installing Jenkins'
page.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker-for-tutorials.adoc (used in
_run-jenkins-in-docker.adoc).
////


=== On macOS and Linux

. Open up a terminal window.
. Customise official Jenkins Docker image, by executing below two steps:
.. Create Dockerfile with the following content:
+
[source]
----
FROM jenkins/jenkins:2.249.1-lts
USER root
RUN apt-get update && apt-get install -y \
       apt-transport-https \
       ca-certificates \
       curl \
       gnupg2 \
       software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/debian \
       $(lsb_release -cs) \
       stable"
RUN apt-get update && apt-get install -y docker-ce-cli
USER jenkins
RUN /usr/local/bin/install-plugins.sh blueocean:1.24.0

ENTRYPOINT ["/sbin/tini", "--", "/usr/local/bin/jenkins.sh"]
----
.. Build a new docker image from this Dockerfile and assign the image meaningful name, e.g. "myjenkins:1.0":
+
[source]
----
docker build -t "myjenkins:1.0" .
----
Keep in mind that the process described above will automatically download the official Jenkins Docker image 
if this hasn't been done before.

. Run your own `myjenkins:1.0` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/run/[`docker run`]
  command:
+
[source]
----
docker run --rm -u root --name jenkins-dkr-blueocean \
  --volume jenkins-data:/var/jenkins_home \# <1>
  --volume "$HOME":/home \# <2>
  --volume /var/run/docker.sock:/var/run/docker.sock \# <3>
  --publish 8080:8080 \# <4>
  --publish 50000:50000 \# <5>
  myjenkins:1.0
----
<1> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`.
<2> Maps the `$HOME` directory on the host (i.e. your local) machine (usually
the `/Users/<your-username>` directory) to the `/home` directory in the
container.
<3> Enables socket communication for the docker image.
<4> Maps (i.e. "publishes") port 8080 on the host machine (1st parameter) 
to access port 8080 of your docker container (2nd parameter).
<5> ( _Optional_ ) Maps port 50000 on the host machine to port 50000 of 
your docker container. This is only necessary if you have set up one or
more inbound Jenkins agents on other machines, which in turn interact with
your container (the Jenkins "controller"). Inbound Jenkins agents communicate 
with the Jenkins controller through TCP port 50000 by default. You can change 
this port number on your Jenkins controller by accessing the 
<<managing/security#,Configure Global Security>> page. 
Note that WebSocket agents in Jenkins 2.217 do not need this configuration.
+
*Note:* If copying and pasting the command snippet above doesn't work, try
copying and pasting this annotation-free version here:
+
[source]
----
docker run --rm -u root --name jenkins-dkr-blueocean \
  --volume jenkins-data:/var/jenkins_home \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --volume "$HOME":/home \
  --publish 8080:8080 \
  --publish 50000:50000 \
  myjenkins:1.0
----
. Proceed to the <<setup-wizard,Setup wizard>>.


<<<<<<< HEAD
==== On Windows
=======
=== On Windows
>>>>>>> 5052f30cd796cd8f63f245e0a97449a6c4855308

The Jenkins project provides a Linux container image, not a Windows container image.
Be sure that your Docker for Windows installation is configured to run `Linux Containers` rather than `Windows Containers`.
See the Docker documentation for instructions to link:https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers[switch to Linux containers].
Once configured to run `Linux Containers`, the steps are:

. Open up a command prompt window.
. Customise official Jenkins Docker image using the <<on-macos-and-linux,macOS
and Linux>> instructions above.

. Run your own `myjenkins:1.0` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/run/[`docker run`]
  command:
+
[source]
----
docker run --rm -u root --name jenkins-tutorial ^
  --volume jenkins-data:/var/jenkins_home ^
  --volume "%HOMEDRIVE%%HOMEPATH%":/home ^
  --volume /var/run/docker.sock:/var/run/docker.sock ^
  --publish 8080:8080 myjenkins:1.0
----
. Proceed to the <<setup-wizard,Setup wizard>>.
. Proceed to the <<setup-wizard,Post-installation setup wizard>>.

[[accessing-the-jenkins-blue-ocean-docker-container]]
<<<<<<< HEAD
==== Accessing the Docker container
=======
== Accessing the Jenkins/Blue Ocean Docker container
>>>>>>> 5052f30cd796cd8f63f245e0a97449a6c4855308

If you have some experience with Docker and you wish or need to access your
Docker container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`]
command, you can add an option like `--name jenkins-tutorial` to the `docker exec` command.
That will access the Jenkins Docker container named "jenkins-tutorial".

This means you could access your docker container (through a separate
terminal/command prompt window) with a `docker exec` command like:

`docker exec -it jenkins-tutorial bash`


== Accessing the Jenkins console log through Docker logs

There is a possibility you may need to access the Jenkins console log, for
instance, when <<unlocking-jenkins,Unlocking Jenkins>> as part of the
<<setup-wizard,Post-installation setup wizard>>.

The Jenkins console log is easily accessible through the terminal/command 
prompt window from which you executed the `docker run ...` command.
In case if needed you can also access the Jenkins console log through the
link:https://docs.docker.com/engine/reference/commandline/logs/[Docker logs] of
your container using the following command:

`docker logs <docker-container-name>`

Your `<docker-container-name>` can be obtained using the `docker ps` command.


== Accessing the Jenkins home directory

There is a possibility you may need to access the Jenkins home directory, for
instance, to check the details of a Jenkins build in the `workspace`
subdirectory.

If you mapped the Jenkins home directory (`/var/jenkins_home`) to one on your
machine's local file system (i.e. in the `docker run ...` command
<<downloading-and-running-jenkins-in-docker,above>>), then you can access the
contents of this directory through your machine's usual terminal/command prompt.

Otherwise, if you specified the `--volume jenkins-data:/var/jenkins_home` option in
the `docker run ...` command, you can access the contents of the Jenkins home
directory through your container's terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/container_exec/[`docker container exec`]
command:

`docker container exec -it <docker-container-name> bash`

As mentioned <<accessing-the-jenkins-console-log-through-docker-logs,above>>,
your `<docker-container-name>` can be obtained using the
link:https://docs.docker.com/engine/reference/commandline/container_ls/[`docker container ls`]
command. If you specified the +
`--name jenkins-blueocean` option in the `docker container run ...`
command above (see also
<<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue
Ocean Docker container>>), you can simply use the `docker container exec` command:

`docker container exec -it jenkins-blueocean bash`

////
Might wish to add explaining the `docker run -t` option, which was covered in
the old installation instructions but not above.

Also mention that spinning up a container of the `jenkins/jenkins` Docker
image can be done so with all the same
https://github.com/jenkinsci/docker#usage[configuration options] available to
the other images published by the Jenkins project.

Explain colon syntax on Docker image references like
`jenkins/jenkins:latest'.
////
