////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the index.adoc page used in the general 'Installing Jenkins' page.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker-for-tutorials.adoc (used in _run-jenkins-in-docker.adoc).
////

=== On macOS and Linux

. Open a terminal window.
. Create a link:https://docs.docker.com/network/bridge/[bridge network] in Docker using the following link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create`] command:
+
[source,bash]
-------------

## docker network create jenkins

. To execute Docker commands inside Jenkins nodes, download and run the `docker:dind` Docker image using the following link:https://docs.docker.com/engine/reference/run/[`docker run`] command:
+
[source,bash]
-------------

docker run 
--name jenkins-docker # <1>
--rm # <2>
--detach # <3>
--privileged # <4>
--network jenkins # <5>
--network-alias docker # <6>
--env DOCKER_TLS_CERTDIR=/certs # <7>
--volume jenkins-docker-certs:/certs/client # <8>
--volume jenkins-data:/var/jenkins_home # <9>
--publish 2376:2376 # <10>
docker:dind # <11>
--storage-driver overlay2 # <12>
--------------------------------

<1> ( *Optional* ) Specifies the Docker container name to use for running the image.
By default, Docker generates a unique name for the container.
<2> ( *Optional* ) Automatically removes the Docker container when it is shut down.
<3> ( *Optional* ) Runs the Docker container in the background.
You can stop this process by running `docker stop jenkins-docker`.
<4> Running Docker in Docker currently requires privileged access to function properly.
This requirement may be relaxed with newer Linux kernel versions.
<5> This corresponds with the network created in the earlier step.
<6> Makes the Docker in Docker container available as the hostname `docker` within the `jenkins` network.
<7> Enables the use of TLS in the Docker server.
Due to the use of a privileged container, this is recommended, though it requires the use of the shared volume described below.
<8> Maps the `/certs/client` directory inside the container to a Docker volume named `jenkins-docker-certs`.
<9> Maps the `/var/jenkins_home` directory inside the container to the Docker volume named `jenkins-data`.
<10> ( *Optional* ) Exposes the Docker daemon port on the host machine.
<11> The `docker:dind` image itself.
<12> The storage driver for the Docker volume.

*

NOTE: If you have problems copying and pasting the above command snippet, use the annotation-free version below:
+
[source,bash]
-------------

docker run --name jenkins-docker --rm --detach 
--privileged --network jenkins --network-alias docker 
--env DOCKER_TLS_CERTDIR=/certs 
--volume jenkins-docker-certs:/certs/client 
--volume jenkins-data:/var/jenkins_home 
--publish 2376:2376 
docker:dind --storage-driver overlay2
-------------------------------------

. Customize the official Jenkins Docker image by executing the following steps:
.. Create a Dockerfile with the following content:
+
[source,subs="attributes+"]
---------------------------

FROM jenkins/jenkins:{jenkins-stable}-jdk21
USER root
RUN apt-get update && apt-get install -y lsb-release ca-certificates curl && 
install -m 0755 -d /etc/apt/keyrings && 
curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc && 
chmod a+r /etc/apt/keyrings/docker.asc && 
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] 
https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" 
| tee /etc/apt/sources.list.d/docker.list > /dev/null && 
apt-get update && apt-get install -y docker-ce-cli && 
apt-get clean && rm -rf /var/lib/apt/lists/*
USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean docker-workflow json-path-api"
--------------------------------------------------------------------------

.. Build a new Docker image and assign a meaningful name:
+
[source,bash,subs="attributes+"]
--------------------------------

## docker build -t myjenkins-blueocean:{jenkins-stable}-1 .

. Run your custom Jenkins image:
+
[source,bash,subs="attributes+"]
--------------------------------

docker run 
--name jenkins-blueocean # <1>
--restart=on-failure # <2>
--detach # <3>
--network jenkins # <4>
--env DOCKER_HOST=tcp://docker:2376 # <5>
--env DOCKER_CERT_PATH=/certs/client 
--env DOCKER_TLS_VERIFY=1 
--publish 8080:8080 # <6>
--publish 50000:50000 # <7>
--volume jenkins-data:/var/jenkins_home # <8>
--volume jenkins-docker-certs:/certs/client:ro # <9>
myjenkins-blueocean:{jenkins-stable}-1 # <10>
---------------------------------------------

. Proceed to the <<setup-wizard,Post-installation setup wizard>>.

=== On Windows

The Jenkins project provides a Linux container image, not a Windows container image.
Ensure Docker Desktop is configured to use Linux containers.

. Open a command prompt window.
. Create a bridge network:
+
[source,bash]
-------------

## docker network create jenkins

. Run Docker-in-Docker:
+
[source,bash]
-------------

docker run --name jenkins-docker --rm --detach ^
--privileged --network jenkins --network-alias docker ^
--env DOCKER_TLS_CERTDIR=/certs ^
--volume jenkins-docker-certs:/certs/client ^
--volume jenkins-data:/var/jenkins_home ^
--publish 2376:2376 ^
docker:dind
-----------

. Build your Jenkins image and run it similarly as above.

== Accessing the Docker container

`docker exec -it jenkins-blueocean bash`

== Accessing logs

`docker logs <docker-container-name>`

== Accessing Jenkins home

`docker container exec -it jenkins-blueocean bash`
