////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the _run-jenkins-in-docker.adoc page used in the tutorials.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker.adoc (used in index.adoc).
////


==== On macOS and Linux

. Open up a terminal window.
. Run the `jenkins/jenkins` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
  command (bearing in mind that this command automatically downloads the image
  if this hasn't been done):
+
[source]
----
docker run \
  --rm \
  -u root \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \ # <1>
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$HOME":/home \ # <2>
  jenkins/jenkins
----
<1> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`. If this volume does not exist, then this `docker run` command
will automatically create the volume for you.
<2> Maps the `$HOME` directory on the host (i.e. your local) machine (usually
the `/Users/<your-username>` directory) to the `/home` directory in the
container.
+
*Note:* If copying and pasting the command snippet above doesn't work, try
copying and pasting this annotation-free version here:
+
[source]
----
docker run \
  --rm \
  -u root \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v "$HOME":/home \
  jenkins/jenkins
----
. Proceed to the <<setup-wizard,Setup wizard>>.


==== On Windows

. Open up a command prompt window.
. Run the `jenkins/jenkins` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
  command (bearing in mind that this command automatically downloads the image
  if this hasn't been done):
+
----
docker run ^
  --rm ^
  -u root ^
  -p 8080:8080 ^
  -v jenkins-data:/var/jenkins_home ^
  -v /var/run/docker.sock:/var/run/docker.sock ^
  -v "%HOMEPATH%":/home ^
  jenkins/jenkins
----
For an explanation of these options, refer to the <<on-macos-and-linux,macOS
and Linux>> instructions above.
. Proceed to the <<setup-wizard,Setup wizard>>.


==== Accessing the Jenkins Docker container

If you have some experience with Docker and you wish or need to access the
Jenkins Docker container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/exec/[`docker exec`]
command, you can add an option like `--name jenkins-tutorials` (with the
link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
above), which would give the Jenkins Docker container the name
"jenkins-tutorials".

This means you could access the Jenkins container (through a separate
terminal/command prompt window) with a `docker exec` command like:

`docker exec -it jenkins-tutorials bash`
