////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the index.adoc page used in the general 'Installing Jenkins'
page.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker-for-tutorials.adoc (used in
_run-jenkins-in-docker.adoc).
////


===== On macOS and Linux

. Open up a terminal window.
. Create a link:https://docs.docker.com/network/bridge/[bridge network] in
  Docker using the following
  link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create`]
  command:
+
[source,bash]
----
docker network create jenkins
----
. Create the following link:https://docs.docker.com/storage/volumes/[volumes] to
  share the Docker client TLS certificates needed to connect to the Docker
  daemon and persist the Jenkins data using
  the following
  link:https://docs.docker.com/engine/reference/commandline/volume_create/[`docker volume create`]
  commands:
+
[source,bash]
----
docker volume create jenkins-docker-certs
docker volume create jenkins-data
----
. In order to execute Docker commands inside Jenkins nodes, download and run
  the `docker:dind` Docker image using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source,bash]
----
docker container run \
  --name jenkins-docker \# <1>
  --rm \# <2>
  --detach \# <3>
  --privileged \# <4>
  --network jenkins \# <5>
  --network-alias docker \# <6>
  --env DOCKER_TLS_CERTDIR=/certs \# <7>
  --volume jenkins-docker-certs:/certs/client \# <8>
  --volume jenkins-data:/var/jenkins_home \# <9>
  --publish 2376:2376 \# <10>
  docker:dind# <11>
----
<1> ( _Optional_ ) Specifies the Docker container name to use for running the
image. By default, Docker will generate a unique name for the container.
<2> ( _Optional_ ) Automatically removes the Docker container (the instance of
the Docker image) when it is shut down. This contains the Docker image cache
used by Docker when invoked from the `jenkinsci/blueocean` container described
below.
<3> ( _Optional_ ) Runs the Docker container in the background. This instance
can be stopped later by running `docker container stop jenkins-docker` and
started again with `docker container start jenkins-docker`. See
link:https://docs.docker.com/engine/reference/commandline/container/[`docker container`]
for more container management commands.
<4> Running Docker in Docker currently requires privileged access to function
properly. This requirement may be relaxed with newer Linux kernel versions.
// TODO: what versions of Linux?
<5> This corresponds with the network created in the earlier step.
<6> Makes the Docker in Docker container available as the hostname `docker`
within the `jenkins` network.
<7> Enables the use of TLS in the Docker server. Due to the use
of a privileged container, this is recommended, though it requires the use of
the shared volume described below. This environment variable controls the root
directory where Docker TLS certificates are managed.
<8> Maps the `/certs/client` directory inside the container to
a Docker volume named `jenkins-docker-certs` as created above.
<9> Maps the `/var/jenkins_home` directory inside the container to the Docker
volume named `jenkins-data` as created above. This will allow for other Docker
containers controlled by this Docker container's Docker daemon to mount data
from Jenkins.
<10> ( _Optional_ ) Exposes the Docker daemon port on the host machine. This is
useful for executing `docker` commands on the host machine to control this
inner Docker daemon.
<11> The `docker:dind` image itself. This image can be downloaded before running
by using the command: `docker image pull docker:dind`.
+
*Note:* If copying and pasting the command snippet above does not work, try
copying and pasting this annotation-free version here:
+
[source,bash]
----
docker container run --name jenkins-docker --rm --detach \
  --privileged --network jenkins --network-alias docker \
  --env DOCKER_TLS_CERTDIR=/certs \
  --volume jenkins-docker-certs:/certs/client \
  --volume jenkins-data:/var/jenkins_home \
  --publish 2376:2376 docker:dind
----
. Download the `jenkinsci/blueocean` image and run it as a container in Docker
  using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source,bash]
----
docker container run \
  --name jenkins-blueocean \# <1>
  --rm \# <2>
  --detach \# <3>
  --network jenkins \# <4>
  --env DOCKER_HOST=tcp://docker:2376 \# <5>
  --env DOCKER_CERT_PATH=/certs/client \
  --env DOCKER_TLS_VERIFY=1 \
  --publish 8080:8080 \# <6>
  --publish 50000:50000 \# <7>
  --volume jenkins-data:/var/jenkins_home \# <8>
  --volume jenkins-docker-certs:/certs/client:ro \# <9>
  jenkinsci/blueocean# <10>
----
<1> ( _Optional_ ) Specifies the Docker container name for this instance of
the `jenkinsci/blueocean` Docker image. This makes it simpler to reference
by subsequent `docker container` commands.
<2> ( _Optional_ ) Automatically removes the Docker container (which is the
instantiation of the `jenkinsci/blueocean` image below) when it is shut down.
This keeps things tidy if you need to quit Jenkins.
<3> ( _Optional_ ) Runs the `jenkinsci/blueocean` container in the background
(i.e. "detached" mode) and outputs the container ID. If you do not specify this
option, then the running Docker log for this container is output in the terminal
window.
<4> Connects this container to the `jenkins` network defined in the earlier
step. This makes the Docker daemon from the previous step available to this
Jenkins container through the hostname `docker`.
<5> Specifies the environment variables used by `docker`, `docker-compose`, and
other Docker tools to connect to the Docker daemon from the previous step.
<6> Maps (i.e. "publishes") port 8080 of the `jenkinsci/blueocean` container to
port 8080 on the host machine. The first number represents the port on the host
while the last represents the container's port. Therefore, if you specified `-p
49000:8080` for this option, you would be accessing Jenkins on your host machine
through port 49000.
<7> ( _Optional_ ) Maps port 50000 of the `jenkinsci/blueocean` container to
port 50000 on the host machine. This is only necessary if you have set up one or
more inbound Jenkins agents on other machines, which in turn interact with
the `jenkinsci/blueocean` container (acting as the "master" Jenkins server, or
simply "Jenkins master"). inbound Jenkins agents communicate with the Jenkins
master through TCP port 50000 by default. You can change this port number on
your Jenkins master through the <<managing/security#,Configure Global Security>>
page. If you were to change your Jenkins master's *TCP port for inbound Jenkins agents*
value to 51000 (for example), then you would need to re-run Jenkins (via this
`docker run ...` command) and specify this "publish" option with something like
`--publish 52000:51000`, where the last value matches this changed value on the
Jenkins master and the first value is the port number on the Jenkins master's
host machine through which the inbound Jenkins agents communicate (to the
Jenkins master) - i.e. 52000.
Note that WebSocket agents in Jenkins 2.217 do not need this configuration.
<8> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`. Instead of mapping the `/var/jenkins_home` directory to a Docker
volume, you could also map this directory to one on your machine's local file
system. For example, specifying the option +
`--volume $HOME/jenkins:/var/jenkins_home` would map the container's
`/var/jenkins_home` directory to the `jenkins` subdirectory within the `$HOME`
directory on your local machine, which would typically be
`/Users/<your-username>/jenkins` or `/home/<your-username>/jenkins`.
Note that if you change the source volume or directory for this, the volume
from the `docker:dind` container above needs to be updated to match this.
<9> Maps the `/certs/client` directory to the previously created
`jenkins-docker-certs` volume. This makes the client TLS certificates needed
to connect to the Docker daemon available in the path specified by the
`DOCKER_CERT_PATH` environment variable.
<10> The `jenkinsci/blueocean` Docker image itself. If this image has not already
been downloaded, then this `docker container run` command will automatically download the
image for you. Furthermore, if any updates to this image were published since
you last ran this command, then running this command again will automatically
download these published image updates for you. +
*Note:* This Docker image could also be downloaded (or updated) independently
using the
link:https://docs.docker.com/engine/reference/commandline/image_pull/[`docker image pull`]
command: +
`docker image pull jenkinsci/blueocean`
+
*Note:* If copying and pasting the command snippet above does not work, try
copying and pasting this annotation-free version here:
+
[source,bash]
----
docker container run --name jenkins-blueocean --rm --detach \
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
  --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 \
  --volume jenkins-data:/var/jenkins_home \
  --volume jenkins-docker-certs:/certs/client:ro \
  --publish 8080:8080 --publish 50000:50000 jenkinsci/blueocean
----
. Proceed to the <<setup-wizard,Post-installation setup wizard>>.


===== On Windows

The Jenkins project provides a Linux container image, not a Windows container image.
Be sure that your Docker for Windows installation is configured to run `Linux Containers` rather than `Windows Containers`.
See the Docker documentation for instructions to link:https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers[switch to Linux containers].
Once configured to run `Linux Containers`, the steps are:

. Open up a command prompt window.
. Create a link:https://docs.docker.com/network/bridge/[bridge network] in
  Docker using the following
  link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create`]
  command:
+
[source]
----
docker network create jenkins
----
. Create the following link:https://docs.docker.com/storage/volumes/[volumes] to
  share the Docker client TLS certificates needed to connect to the Docker
  daemon and persist the Jenkins data using the following
  link:https://docs.docker.com/engine/reference/commandline/volume_create/[`docker volume create`]
  commands:
+
[source]
----
docker volume create jenkins-docker-certs
docker volume create jenkins-data
----
. In order to execute Docker commands inside Jenkins nodes, download and run
  the `docker:dind` Docker image using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source]
----
docker container run --name jenkins-docker --rm --detach ^
  --privileged --network jenkins --network-alias docker ^
  --env DOCKER_TLS_CERTDIR=/certs ^
  --volume jenkins-docker-certs:/certs/client ^
  --volume jenkins-data:/var/jenkins_home ^
  docker:dind
----
. Download the `jenkinsci/blueocean` image and run it as a container in Docker
  using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source]
----
docker container run --name jenkins-blueocean --rm --detach ^
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 ^
  --env DOCKER_CERT_PATH=/certs/client --env DOCKER_TLS_VERIFY=1 ^
  --volume jenkins-data:/var/jenkins_home ^
  --volume jenkins-docker-certs:/certs/client:ro ^
  --publish 8080:8080 --publish 50000:50000 jenkinsci/blueocean
----
For an explanation of each of these options, refer to the <<on-macos-and-linux,
macOS and Linux>> instructions above.
. Proceed to the <<setup-wizard,Post-installation setup wizard>>.

[[accessing-the-jenkins-blue-ocean-docker-container]]
==== Accessing the Jenkins/Blue Ocean Docker container

If you have some experience with Docker and you wish or need to access the
`jenkinsci/blueocean` container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/container_exec/[`docker container exec`]
command, you can add an option like `--name jenkins-blueocean` (with the
link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
above), which would give the `jenkinsci/blueocean` container the name
"jenkins-blueocean".

This means you could access the container (through a separate terminal/command
prompt window) with a `docker container exec` command like:

`docker container exec -it jenkins-blueocean bash`


==== Accessing the Jenkins console log through Docker logs

There is a possibility you may need to access the Jenkins console log, for
instance, when <<unlocking-jenkins,Unlocking Jenkins>> as part of the
<<setup-wizard,Post-installation setup wizard>>.

If you did not specify the detached mode option `--detach` with the
`docker container run ...` command
<<downloading-and-running-jenkins-in-docker,above>>, then the Jenkins
console log is easily accessible through the terminal/command prompt window from
which you ran this Docker command.

Otherwise, you can access the Jenkins console log through the
link:https://docs.docker.com/engine/reference/commandline/container_logs/[Docker logs] of
the `jenkinsci/blueocean` container using the following command:

`docker container logs <docker-container-name>`

Your `<docker-container-name>` can be obtained using the
link:https://docs.docker.com/engine/reference/commandline/container_ls/[`docker container ls`]
command. If you specified the +
`--name jenkins-blueocean` option in the `docker container run ...` command above (see
also
<<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue
Ocean Docker container>>), you can simply use the `docker container logs` command:

`docker container logs jenkins-blueocean`


==== Accessing the Jenkins home directory

There is a possibility you may need to access the Jenkins home directory, for
instance, to check the details of a Jenkins build in the `workspace`
subdirectory.

If you mapped the Jenkins home directory (`/var/jenkins_home`) to one on your
machine's local file system (i.e. in the `docker container run ...` command
<<downloading-and-running-jenkins-in-docker,above>>), then you can access the
contents of this directory through your machine's usual terminal/command prompt.

Otherwise, if you specified the `--volume jenkins-data:/var/jenkins_home` option in
the `docker container run ...` command, you can access the contents of the Jenkins home
directory through the `jenkinsci/blueocean` container's terminal/command prompt
using the
link:https://docs.docker.com/engine/reference/commandline/container_exec/[`docker container exec`]
command:

`docker container exec -it <docker-container-name> bash`

As mentioned <<accessing-the-jenkins-console-log-through-docker-logs,above>>,
your `<docker-container-name>` can be obtained using the
link:https://docs.docker.com/engine/reference/commandline/container_ls/[`docker container ls`]
command. If you specified the +
`--name jenkins-blueocean` option in the `docker container run ...`
command above (see also
<<accessing-the-jenkins-blue-ocean-docker-container,Accessing the Jenkins/Blue
Ocean Docker container>>), you can simply use the `docker container exec` command:

`docker container exec -it jenkins-blueocean bash`

////
Might wish to add explaining the `docker run -t` option, which was covered in
the old installation instructions but not above.

Also mention that spinning up a container of the `jenkinsci/blueocean` Docker
image can be done so with all the same
https://github.com/jenkinsci/docker#usage[configuration options] available to
the other images published by the Jenkins project.

Explain colon syntax on Docker image references like
`jenkinsci/blueocean:latest'.
////
