////
This file is only meant to be included as a snippet in other documents.
There is a version of this file for the general 'Installing Jenkins' page
(index.adoc) and another for tutorials (_run-jenkins-in-docker.adoc).
This file is for the _run-jenkins-in-docker.adoc page used in the tutorials.
If you update content on this page, please ensure the changes are reflected in
the sibling file _docker.adoc (used in index.adoc).
////


==== On macOS and Linux

. Open up a terminal window.
. Create a link:https://docs.docker.com/network/bridge/[bridge network] in
  Docker using the following
  link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create`]
  command:
+
[source,bash]
----
docker network create jenkins
----
. Create the following link:https://docs.docker.com/storage/volumes/[volumes] to
  share the Docker client TLS certificates needed to connect to the Docker
  daemon and persist the Jenkins data using the following
  link:https://docs.docker.com/engine/reference/commandline/volume_create/[`docker volume create`]
  commands:
+
[source,bash]
----
docker volume create jenkins-docker-certs
docker volume create jenkins-data
----
. In order to execute Docker commands inside Jenkins nodes, download and run
  the `docker:dind` Docker image using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source,bash]
----
docker container run --name jenkins-docker --rm --detach \
  --privileged --network jenkins --network-alias docker \
  --env DOCKER_TLS_CERTDIR=/certs \
  --volume jenkins-docker-certs:/certs/client \
  --volume jenkins-data:/var/jenkins_home \
  --publish 2376:2376 docker:dind
----
. Run the `jenkinsci/blueocean` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command (bearing in mind that this command automatically downloads the image
  if this hasn't been done):
+
[source]
----
docker container run --name jenkins-tutorial --rm --detach \
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
  --env DOCKER_TLS_VERIFY=1 \
  --volume jenkins-data:/var/jenkins_home \ # <1>
  --volume jenkins-docker-certs:/var/jenkins_home/.docker:ro \
  --volume "$HOME":/home \ # <2>
  --publish 8080:8080 jenkinsci/blueocean
----
<1> Maps the `/var/jenkins_home` directory in the container to the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data`. If this volume does not exist, then this `docker container run`
command will automatically create the volume for you.
<2> Maps the `$HOME` directory on the host (i.e. your local) machine (usually
the `/Users/<your-username>` directory) to the `/home` directory in the
container.
+
*Note:* If copying and pasting the command snippet above doesn't work, try
copying and pasting this annotation-free version here:
+
[source]
----
docker container run --name jenkins-tutorial --rm --detach \
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 \
  --env DOCKER_TLS_VERIFY=1 \
  --volume jenkins-data:/var/jenkins_home \
  --volume jenkins-docker-certs:/var/jenkins_home/.docker:ro \
  --volume "$HOME":/home --publish 8080:8080 jenkinsci/blueocean
----
. Proceed to the <<setup-wizard,Setup wizard>>.


==== On Windows

. Open up a command prompt window.
. Create a link:https://docs.docker.com/network/bridge/[bridge network] in
  Docker using the following
  link:https://docs.docker.com/engine/reference/commandline/network_create/[`docker network create`]
  command:
+
[source]
----
docker network create jenkins
----
. Create the following link:https://docs.docker.com/storage/volumes/[volumes] to
  share the Docker client TLS certificates needed to connect to the Docker
  daemon and persist the Jenkins data using the following
  link:https://docs.docker.com/engine/reference/commandline/volume_create/[`docker volume create`]
  commands:
+
[source]
----
docker volume create jenkins-docker-certs
docker volume create jenkins-data
----
. In order to execute Docker commands inside Jenkins nodes, download and run
  the `docker:dind` Docker image using the following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command:
+
[source]
----
docker container run --name jenkins-docker --rm --detach \
  --privileged --network jenkins --network-alias docker \
  --env DOCKER_TLS_CERTDIR=/certs \
  --volume jenkins-docker-certs:/certs/client \
  --volume jenkins-data:/var/jenkins_home \
  --publish 2376:2376 docker:dind
----
. Run the `jenkinsci/blueocean` image as a container in Docker using the
  following
  link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
  command (bearing in mind that this command automatically downloads the image
  if this hasn't been done):
+
[source]
----
docker container run --name jenkins-blueocean --rm --detach ^
  --network jenkins --env DOCKER_HOST=tcp://docker:2376 ^
  --env DOCKER_TLS_VERIFY=1 ^
  --volume jenkins-data:/var/jenkins_home ^
  --volume jenkins-docker-certs:/var/jenkins_home/.docker:ro ^
  --volume "%HOMEDRIVE%%HOMEPATH%":/home ^
  --publish 8080:8080 --publish 50000:50000 jenkinsci/blueocean
----
For an explanation of these options, refer to the <<on-macos-and-linux,macOS
and Linux>> instructions above.
. Proceed to the <<setup-wizard,Setup wizard>>.


==== Accessing the Jenkins/Blue Ocean Docker container

If you have some experience with Docker and you wish or need to access the
Jenkins/Blue Ocean Docker container through a terminal/command prompt using the
link:https://docs.docker.com/engine/reference/commandline/container_exec/[`docker container exec`]
command, you can add an option like `--name jenkins-tutorials` (with the
link:https://docs.docker.com/engine/reference/commandline/container_run/[`docker container run`]
above), which would give the Jenkins/Blue Ocean Docker container the name
"jenkins-tutorials".

This means you could access the Jenkins/Blue Ocean container (through a separate
terminal/command prompt window) with a `docker container exec` command like:

`docker container exec -it jenkins-tutorial bash`
