---
layout: section
title: Docker
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

= Docker

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the
'_prerequisites.adoc' file, which is used in the Guided Tour of the
Jenkins Documentation.
////

link:https://docs.docker.com/engine/docker-overview/[Docker] is a platform for
running applications in an isolated environment called a "container" (or Docker
container). Applications like Jenkins can be downloaded as read-only "images"
(or Docker images), each of which is run in Docker as a container. A Docker
container is in effect a "running instance" of a Docker image. From this
perspective, an image is stored permanently more or less (i.e. insofar as image
updates are published), whereas containers are stored temporarily. Read more
about these concepts in the Docker documentation's
link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation
and setup] page.

Docker's fundamental platform and container design means that a single Docker
image (for any given application like Jenkins) can be run on any supported
operating system (macOS, Linux and Windows) or cloud service (AWS and Azure)
which is also running Docker.

==== Installing Docker

To install Docker on your operating system, follow "prerequisits" section of the
link:/doc/pipeline/tour/getting-started/#prerequisites[Guided Tour page]

As an alternative solution you can visit the
link:https://store.docker.com/search?type=edition&offering=community[Docker
store] website and click the *Docker Community Edition* box which is suitable
for your operating system or cloud service. Follow the installation instructions
on their website.

Jenkins can also run on Docker Enterprise Edition, which you can access through
*Docker EE* on the Docker store website.

[CAUTION]
====
If you are installing Docker on a Linux-based operating system, ensure
you configure Docker so it can be managed as a non-root user. Read more about
this in Docker's
link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
steps for Linux] page of their documentation. This page also contains
information about how to configure Docker to start on boot.
====

==== Downloading and running Jenkins in Docker

There are several Docker images of Jenkins available.

The recommended Docker image to use is the
link:https://hub.docker.com/r/jenkinsci/blueocean/[`jenkinsci/blueocean` image]
(from the link:https://hub.docker.com/[Docker Hub repository]). This image
contains the current link:/download[Long-Term Support (LTS) release of Jenkins]
(which is production-ready) bundled with all Blue Ocean plugins and features.
This means that you do not need to install the Blue Ocean plugins separately.

[NOTE]
====
A new `jenkinsci/blueocean` image is published each time a new release of Blue
Ocean is published. You can see a list of previously published versions of the
`jenkinsci/blueocean` image on the
link:https://hub.docker.com/r/jenkinsci/blueocean/tags/[tags] page.

There are also other Jenkins Docker images you can use (accessible through
link:https://hub.docker.com/r/jenkins/jenkins/[`jenkins/jenkins`] on Docker
Hub). However, these do not come with Blue Ocean, which would need to be
installed via the link:../managing[*Manage Jenkins*] >
link:../managing/plugins[*Manage Plugins*] page in Jenkins. Read more
about this in link:../blueocean/getting-started[Getting started with Blue Ocean].
====

include::doc/book/installing/_docker.adoc[]

include::doc/book/installing/_setup-wizard.adoc[]
