---
layout: section
title: Docker
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the
'tutorials/_prerequisites.adoc' file, which is used in the Guided Tour of the
Jenkins Documentation.
////

link:https://docs.docker.com/get-started/overview/[Docker] is a platform for
running applications in an isolated environment called a "container" (or Docker
container). Applications like Jenkins can be downloaded as read-only "images"
(or Docker images), each of which is run in Docker as a container. A Docker
container is in effect a "running instance" of a Docker image. From this
perspective, an image is stored permanently more or less (i.e. insofar as image
updates are published), whereas containers are stored temporarily. Read more
about these concepts in the Docker documentation's
link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation
and setup] page.

Docker's fundamental platform and container design means that a single Docker
image (for any given application like Jenkins) can be run on any supported
operating system (macOS, Linux and Windows) or cloud service (AWS and Azure)
which is also running Docker.

=== Installing Docker

To install Docker on your operating system, follow "prerequisites" section of the
link:/doc/pipeline/tour/getting-started/#prerequisites[Guided Tour page]

As an alternative solution you can visit the
link:https://hub.docker.com/search?type=edition&offering=community[Dockerhub]
and select the *Docker Community Edition* suitable
for your operating system or cloud service. Follow the installation instructions
on their website.

[CAUTION]
====
If you are installing Docker on a Linux-based operating system, ensure
you configure Docker so it can be managed as a non-root user. Read more about
this in Docker's
link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
steps for Linux] page of their documentation. This page also contains
information about how to configure Docker to start on boot.
====

include::doc/book/installing/_installation_requirements.adoc[]

=== Downloading and running Jenkins in Docker

There are several Docker images of Jenkins available.

The recommended Docker image to use is the Official
link:https://hub.docker.com/r/jenkins/jenkins/[`jenkins/jenkins` image]
(from the link:https://hub.docker.com/[Docker Hub repository]). This image
contains the current link:/download[Long-Term Support (LTS) release of Jenkins]
(which is production-ready). However this image doesn't have docker CLI inside it 
and is not bundled with frequently used Blue Ocean plugins and features.
This means that if you want to use the full power of Jenkins and Docker you may want
to go through described below installation process.

[NOTE]
====
A new `jenkins/jenkins` image is published each time a new release of Jenkins Docker is published. 
You can see a list of previously published versions of the `jenkins/jenkins` image on the
link:https://hub.docker.com/r/jenkins/jenkins/tags/[tags] page.
====

include::doc/book/installing/_docker.adoc[]

include::doc/book/installing/_setup-wizard.adoc[]
