---
layout: chapter
title: Installing Jenkins
---
ifdef::backend-html5[]
:notitle:
:description:
:sectanchors:
:toc:
:toclevels: 4
:imagesdir: ../resources
endif::[]


= Installing Jenkins

The procedures on this page are for new installations of Jenkins on a
single/local machine.

Jenkins is typically run as a standalone application in its own process with the
built-in
link:https://stackoverflow.com/questions/7213541/what-is-java-servlet[Java servlet] container/application server
(link:https://www.eclipse.org/jetty/[Jetty]).

Jenkins can also be run as a servlet in different Java servlet containers such
as link:https://tomcat.apache.org/[Apache Tomcat] or
link:https://javaee.github.io/glassfish/[GlassFish]. However, instructions for
setting up these types of installations are beyond the scope of this page.

*Note:* Although this page focuses on local installations of Jenkins, this
content can also be used to help set up Jenkins in production environments.


== Prerequisites

Minimum hardware requirements:

* 256 MB of RAM
* 1 GB of drive space (although 10 GB is a recommended minimum if running
  Jenkins as a Docker container)

Recommended hardware configuration for a small team:

* 1 GB+ of RAM
* 50 GB+ of drive space

Comprehensive hardware recommendations:

* Hardware: see the link:/doc/book/hardware-recommendations/#hardware-recommendations[Hardware Recommendations] page

Software requirements:

* Java: see the link:/doc/administration/requirements/java[Java Requirements] page
* Web browser: see the link:/doc/administration/requirements/web-browsers[Web Browser Compatibility] page
* For Windows operating system: link:/doc/administration/requirements/windows[Windows Support Policy]

== Installation platforms

This section describes how to install/run Jenkins on different platforms and
operating systems.

=== Docker

See the link:docker[Docker] installation section.

=== Kubernetes

See the link:kubernetes[Kubernetes] installation section.

=== WAR file

See the link:war-file[WAR file] installation section.

=== macOS

See the link:macos[macOS] installation section.

=== Linux

See the link:linux[linux] installation section.

=== Windows

See the link:windows[Microsoft Windows] installation section.

=== Other operating systems

See the link:other[other operating systems] installation section.

=== Offline installations

See the link:offline[offline installation] section.

[[jenkins-parameters]]
== Initial settings

See the link:initial-settings[initial settings] section.
