---
layout: chapter
title: Installing Jenkins
---
ifdef::backend-html5[]
:notitle:
:description:
:sectanchors:
:toc:
:toclevels: 4
:imagesdir: ../resources
endif::[]


= Installing Jenkins

The procedures on this page are for new installations of Jenkins on a
single/local machine.

Jenkins is typically run as a standalone application in its own process with the
built-in
link:https://stackoverflow.com/questions/7213541/what-is-java-servlet[Java
servlet] container/application server
(link:https://www.eclipse.org/jetty/[Jetty]).

Jenkins can also be run as a servlet in different Java servlet containers such
as link:https://tomcat.apache.org/[Apache Tomcat] or
link:https://javaee.github.io/glassfish/[GlassFish]. However, instructions for
setting up these types of installations are beyond the scope of this page.

*Note:* Although this page focuses on local installations of Jenkins, this
content can also be used to help set up Jenkins in production environments.


== Prerequisites

Minimum hardware requirements:

* 256 MB of RAM
* 1 GB of drive space (although 10 GB is a recommended minimum if running
  Jenkins as a <<docker,Docker>> container)

Recommended hardware configuration for a small team:

* 1 GB+ of RAM
* 50 GB+ of drive space

Comprehensive hardware recommendations:

* Hardware: see the link:/doc/book/hardware-recommendations/#hardware-recommendations[Hardware Recommendations] page

Software requirements:

* Java: see the link:/doc/administration/requirements/java[Java Requirements] page
* Web browser: see the link:/doc/administration/requirements/web-browsers[Web Browser Compatibility] page
* For Windows operating system: link:/doc/administration/requirements/windows[Windows Support Policy]

== Installation platforms

This section describes how to install/run Jenkins on different platforms and
operating systems.


=== Docker

////
IMPORTANT: If you update content in this section, please ensure you check these
changes against the procedures documented in the
'_prerequisites.adoc' file, which is used in the Guided Tour of the
Jenkins Documentation.
////

link:https://docs.docker.com/engine/docker-overview/[Docker] is a platform for
running applications in an isolated environment called a "container" (or Docker
container). Applications like Jenkins can be downloaded as read-only "images"
(or Docker images), each of which is run in Docker as a container. A Docker
container is in effect a "running instance" of a Docker image. From this
perspective, an image is stored permanently more or less (i.e. insofar as image
updates are published), whereas containers are stored temporarily. Read more
about these concepts in the Docker documentation's
link:https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation
and setup] page.

Docker's fundamental platform and container design means that a single Docker
image (for any given application like Jenkins) can be run on any supported
operating system (macOS, Linux and Windows) or cloud service (AWS and Azure)
which is also running Docker.


==== Installing Docker

To install Docker on your operating system, follow "prerequisits" section of the 
link:/doc/pipeline/tour/getting-started/#prerequisites[Guided Tour page]

As an alternative solution you can visit the
link:https://store.docker.com/search?type=edition&offering=community[Docker
store] website and click the *Docker Community Edition* box which is suitable
for your operating system or cloud service. Follow the installation instructions
on their website.

Jenkins can also run on Docker Enterprise Edition, which you can access through
*Docker EE* on the Docker store website.

[CAUTION]
====
If you are installing Docker on a Linux-based operating system, ensure
you configure Docker so it can be managed as a non-root user. Read more about
this in Docker's
link:https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
steps for Linux] page of their documentation. This page also contains
information about how to configure Docker to start on boot.
====


==== Downloading and running Jenkins in Docker

There are several Docker images of Jenkins available.

The recommended Docker image to use is the
link:https://hub.docker.com/r/jenkinsci/blueocean/[`jenkinsci/blueocean` image]
(from the link:https://hub.docker.com/[Docker Hub repository]). This image
contains the current link:/download[Long-Term Support (LTS) release of Jenkins]
(which is production-ready) bundled with all Blue Ocean plugins and features.
This means that you do not need to install the Blue Ocean plugins separately.

[NOTE]
====
A new `jenkinsci/blueocean` image is published each time a new release of Blue
Ocean is published. You can see a list of previously published versions of the
`jenkinsci/blueocean` image on the
link:https://hub.docker.com/r/jenkinsci/blueocean/tags/[tags] page.

There are also other Jenkins Docker images you can use (accessible through
link:https://hub.docker.com/r/jenkins/jenkins/[`jenkins/jenkins`] on Docker
Hub). However, these do not come with Blue Ocean, which would need to be
installed via the link:../managing[*Manage Jenkins*] >
link:../managing/plugins[*Manage Plugins*] page in Jenkins. Read more
about this in link:../blueocean/getting-started[Getting started with Blue Ocean].
====

include::doc/book/installing/_docker.adoc[]


=== WAR file

The Web application ARchive (WAR) file version of Jenkins can be installed on
any operating system or platform that supports Java.

*To download and run the WAR file version of Jenkins:*

. Download the
  link:http://mirrors.jenkins.io/war-stable/latest/jenkins.war[latest stable
  Jenkins WAR file] to an appropriate directory on your machine.
. Open up a terminal/command prompt window to the download directory.
. Run the command `java -jar jenkins.war`.
. Browse to `\http://localhost:8080` and wait until the *Unlock Jenkins* page
  appears.
. Continue on with the <<setup-wizard,Post-installation setup wizard>> below.

*Notes:*

* Unlike downloading and running Jenkins with Blue Ocean in Docker
  (<<docker,above>>), this process does not automatically install the Blue Ocean
  features, which would need to installed separately via the
  link:../../book/managing[**Manage Jenkins**] >
  link:../../book/managing/plugins/[**Manage Plugins**] page in Jenkins. Read
  more about the specifics for installing Blue Ocean on the
  link:../../book/blueocean/getting-started/[Getting started with Blue Ocean]
  page.
* You can change the port by specifying the `--httpPort` option when you run the
  `java -jar jenkins.war` command. For example, to make Jenkins accessible
  through port 9090, then run Jenkins using the command: +
  `java -jar jenkins.war --httpPort=9090`


=== macOS

* link:/download/lts/macos[Installing Jenkins LTS on macOS]
* link:/download/weekly/macos[Installing Jenkins Weekly on macOS]

=== Linux

Jenkins installers are available for several Linux distributions.

* <<Debian/Ubuntu>>
* <<Fedora>>
* <<Red Hat / CentOS>>

==== Debian/Ubuntu

On Debian and Debian-based distributions like Ubuntu you can install Jenkins through `apt`.

===== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/debian-stable/[`debian-stable` apt repository].

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

===== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/debian/[`debian` apt repository].

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

[NOTE]
====
If an error is reported, "`jenkins : Depends: daemon but it is not installable`", add the link:https://help.ubuntu.com/community/Repositories/Ubuntu["universe" apt repository] of community maintained free and open source software for Ubuntu by executing this command after `sudo apt-get update`:
[source,bash]
----
sudo add-apt-repository universe
----
====

This package installation will:

* Setup Jenkins as a daemon launched on start. See `/etc/init.d/jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/etc/default/jenkins` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If your `/etc/init.d/jenkins` file fails to start Jenkins, edit the `/etc/default/jenkins` to replace the line
`----HTTP_PORT=8080----` with `----HTTP_PORT=8081----`
Here, "8081" was chosen but you can put another port available.
====

===== Installation of Java

Jenkins requires Java in order to run, yet certain distributions don't include this by default and  link:/doc/administration/requirements/java/[some Java versions are incompatible] with Jenkins.

There are multiple Java implementations which you can use. link:https://openjdk.java.net/[OpenJDK] is the most popular one at the moment, we will use it in this guide.

To install the Open Java Development Kit (OpenJDK) run the following:

* Update the repositories 
[source,bash]
----
sudo apt update
----
* search of all available packages:
[source,bash]
----
sudo apt search openjdk
----
* Pick one option and install it: 
[source,bash]
----
sudo apt install openjdk-8-jdk
----
* Confirm installation:
[source,bash]
----
sudo apt install openjdk-8-jdk 
----
* checking installation:
[source,bash]
----
java -version
----
* the result must be something like:
[source,bash]
----
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
----

[NOTE]
====
Why use `apt` and not `apt-get` or another command?
The apt command has been available since 2014.
It has a command structure that is similar to `apt-get` but was created to be a more pleasant experience for typical users.
Simple software management tasks like install, search and remove are easier with `apt`.
====

==== Fedora

You can install Jenkins through `dnf`. You need to add the Jenkins repository from the Jenkins website to the package manager first.

===== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo dnf upgrade
sudo dnf install jenkins java-devel
----

===== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    http://pkg.jenkins-ci.org/redhat/jenkins.repo
sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
sudo dnf upgrade
sudo dnf install jenkins java-devel
----

===== Start Jenkins

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/etc/rc.d/init.d/jenkins; generated)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

==== Red Hat / CentOS

You can install Jenkins through `yum` on Red Hat Enterprise Linux, CentOS, and other Red Hat based distributions.
You need to choose either the Jenkins Long Term Support release or the Jenkins weekly release.

===== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-1.8.0-openjdk-devel
----

===== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-1.8.0-openjdk-devel
----

===== Start Jenkins

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/etc/rc.d/init.d/jenkins; generated)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
...
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

=== Windows

To install from the website, using the installer:

* link:http://mirrors.jenkins.io/windows/latest[Download the latest package]
* Open the package and follow the instructions


=== Other operating systems


==== FreeBSD

Jenkins can be installed on FreeBSD using the standard FreeBSD package manager, `pkg`.

[IMPORTANT]
====
Disclaimer: The link:https://www.freebsd.org/[FreeBSD project] maintains the Jenkins packaging for FreeBSD.
The Jenkins package for FreeBSD is NOT officially supported by the Jenkins project,
but it is actively used by the link:https://www.freebsd.org/[FreeBSD project] at https://ci.freebsd.org/ .
====

===== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the FreeBSD `pkg` package manager.

[source,bash]
----
# pkg install jenkins-lts
----

===== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the FreeBSD `pkg` package manager.

[source,bash]
----
# pkg install jenkins
----

The long term support package `jenkins-lts` and the weekly package installation `jenkins` will:

* Configure Jenkins as a daemon which may optionally be launched on start. See `/etc/rc.conf` for more details
* Create a '`jenkins`' user to run the service
* Direct console log output to the file `/var/log/jenkins.log`. Check this file when troubleshooting Jenkins
* Set Jenkins to listen on port 8180 from the path `/jenkins`.  Open \http://localhost:8180/jenkins to login to Jenkins

===== Start Jenkins

You can start the Jenkins service with the command:

[source,bash]
----
# service jenkins onestart
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
# service jenkins status
----

You can stop the Jenkins service with the command:

[source,bash]
----
# service jenkins stop
----

===== Enable Jenkins

Add the following to `/etc/rc.conf` to start Jenkins automatically on system boot:

[source,bash]
----
jenkins_enable="YES"
----

Once Jenkins is enabled, it can be started with:

[source,bash]
----
# service jenkins start
----

Other configuration values that can be set in `/etc/rc.conf` or in `/etc/rc.conf.d/jenkins` are described in `/usr/local/etc/rc.d/jenkins`.
Refer to the link:https://wiki.freebsd.org/Jenkins[Jenkins page] on the link:https://wiki.freebsd.org/[FreeBSD wiki] for more information specific to Jenkins on FreeBSD.


==== OpenIndiana Hipster

On a system running link:https://www.openindiana.org/[OpenIndiana Hipster]
Jenkins can be installed in either the local or global zone using the
link:https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging
System] (IPS).

[IMPORTANT]
====
Disclaimer: This platform is NOT officially supported by the Jenkins team,
use it at your own risk. Packaging and integration described in this section
is maintained by the OpenIndiana Hipster team, bundling the generic `jenkins.war`
to work in that operating environment.
====

For the common case of running the newest packaged weekly build as a standalone (Jetty) server, simply execute:

[source,bash]
----
pkg install jenkins
svcadm enable jenkins
----

The common packaging integration for a standalone service will:

* Create a `jenkins` user to run the service and to own the directory structures under `/var/lib/jenkins`.
* Pull the OpenJDK8 and other packages required to execute Jenkins, including
  the `jenkins-core-weekly` package with the latest `jenkins.war`.
+
CAUTION: Long-Term Support (LTS) Jenkins releases currently do not support OpenZFS-based
systems, so no packaging is provided at this time.
* Set up Jenkins as an SMF service instance (`svc:/network/http:jenkins`) which
  can then be enabled with the `svcadm` command demonstrated above.
* Set up Jenkins to listen on port 8080.
* Configure the log output to be managed by SMF at `/var/svc/log/network-http:jenkins.log`.

Once Jenkins is running, consult the log
(`/var/svc/log/network-http:jenkins.log`) to retrieve the generated
administrator password for the initial set up of Jenkins, usually it will be
found at `/var/lib/jenkins/home/secrets/initialAdminPassword`. Then navigate to
link:http://localhost:8080[localhost:8080] to <<setup-wizard, complete configuration of the
Jenkins instance>>.


To change attributes of the service, such as environment variables like `JENKINS_HOME`
or the port number used for the Jetty web server, use the `svccfg` utility:

[source,bash]
----
svccfg -s svc:/network/http:jenkins editprop
svcadm refresh svc:/network/http:jenkins
----

You can also refer to `/lib/svc/manifest/network/jenkins-standalone.xml` for more
details and comments about currently supported tunables of the SMF service.
Note that the `jenkins` user account created by the packaging is specially privileged
to allow binding to port numbers under 1024.

The current status of Jenkins-related packages available for the given release
of OpenIndiana can be queried with:

[source,bash]
----
pkg info -r '*jenkins*'
----

Upgrades to the package can be performed by updating the entire operating
environment with `pkg update`, or specifically for Jenkins core software with:

[source,bash]
----
pkg update jenkins-core-weekly
----

[CAUTION]
====
Procedure for updating the package will restart the currently running Jenkins
process. Make sure to prepare it for shutdown and finish all running jobs
before updating, if needed.
====


==== Solaris, OmniOS, SmartOS, and other siblings

Generally it should suffice to install Java 8 and link:/download[download] the
`jenkins.war` and run it as a standalone process or under an application server
such as link:https://tomcat.apache.org[Apache Tomcat].


Some caveats apply:

* Headless JVM and fonts: For OpenJDK builds on minimalized-footprint systems,
  there may be
  link:https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem[issues
  running the headless JVM], because Jenkins needs some fonts to render certain
  pages.
* ZFS-related JVM crashes: When Jenkins runs on a system detected as a `SunOS`,
  it tries to load integration for advanced ZFS features using the bundled
  `libzfs.jar` which maps calls from Java to native `libzfs.so` routines
  provided by the host OS. Unfortunately, that library was made for binary
  utilities built and bundled by the OS along with it at the same time, and was
  never intended as a stable interface exposed to consumers. As the forks of
  Solaris legacy, including ZFS and later the OpenZFS initiative evolved, many
  different binary function signatures were provided by different host
  operating systems - and when Jenkins `libzfs.jar` invoked the wrong
  signature, the whole JVM process crashed. A solution was proposed and
  integrated in `jenkins.war` since weekly release 2.55 (and not yet in any LTS
  to date) which enables the administrator to configure which function
  signatures should be used for each function known to have different variants,
  apply it to their application server initialization options and then run and
  update the generic `jenkins.war` without further workarounds. See
  link:https://github.com/kohsuke/libzfs4j[the libzfs4j Git repository] for
  more details, including a script to try and "lock-pick" the configuration
  needed for your particular distribution (in particular if your kernel updates
  bring a new incompatible `libzfs.so`).

Also note that forks of the OpenZFS initiative may provide ZFS on various
BSD, Linux, and macOS distributions. Once Jenkins supports detecting ZFS
capabilities, rather than relying on the `SunOS` check, the above caveats for
ZFS integration with Jenkins should be considered.

include::doc/book/installing/_setup-wizard.adoc[]

== Offline Jenkins Installation

This section describes how to install Jenkins on a machine
that does not have an internet connection.

To install Jenkins itself, download the appropriate war file and
transfer it to your machine.

Plugins are a different matter, due to dependency requirements. 

The recommended approach is to use link:https://github.com/jenkinsci/plugin-installation-manager-tool[Plugin Installation Manager Tool].

If you want to transfer the individual plugins, you'll need to retrieve
all dependencies as well. There are several dependency retrieval scripts and tools
on Github. For example:

* link:https://github.com/jenkinsci/docker/blob/master/install-plugins.sh[install-plugins.sh] - Bash script for managing plugins from the official Docker image for Jenkins
* link:https://github.com/samrocketman/jenkins-bootstrap-shared[samrocketman/jenkins-bootstrap-shared] - Java is
required; packages Jenkins and plugins into an immutable package
installer.  Supported formats include: RPM, DEB, Docker.  Can proxy
Jenkins and plugins through Nexus or Artifactory since Gradle is used to
assemble plugins.

== Jenkins Parameters

Jenkins initialization can also be controlled by run time parameters passed as arguments.
Command line arguments can adjust networking, security, monitoring, and other settings.

include::doc/book/installing/_jenkins-command-parameters.adoc[]
