---
layout: chapter
title: Installing Jenkins
---
////
:notitle:
:description:
////
:sectanchors:
:toc:


= Installing Jenkins

The procedures on this page are for new installations of Jenkins on a
single/local machine.

Jenkins is typically run as a standalone application as its own process with the
built-in
link:https://stackoverflow.com/questions/7213541/what-is-java-servlet[Java
servlet] container/application server
(link:http://www.eclipse.org/jetty/[Jetty]).

Jenkins can also be run as a servlet in different Java servlet containers such
as link:http://tomcat.apache.org/[Apache Tomcat] or
link:https://javaee.github.io/glassfish/[GlassFish]. However, these types of
installations are beyond the scope of this page.

*Note:* Although this page focusses on local installations of Jenkins, this
content can also be used to set up Jenkins in production environments.


== Prerequisites

Minimum hardware requirements:

* 256 MB of RAM
* 1 GB of drive space (although 10 GB is a recommended minimum if running
  Jenkins as a <<docker,Docker>> container)

Recommended hardware configuration for a small team:

* 1 GB+ of RAM
* 50 GB+ of drive space

Sofware requirements:

* Java 8 - either a Java Runtime Environment (JRE) or a Java Development Kit
  (JDK) is fine +
  *Note:* This is not a requirement if running Jenkins as a <<docker,Docker>>
  container.


== Installation platforms

This section describes how to install Jenkins on different platforms or
operating systems.


=== Docker

As described on the https://docs.docker.com/engine/docker-overview/[Docker
overview] page, Docker is a platform for running applications in an isolated
environment called a Docker "container". Applications like Jenkins can be
downloaded as a read-only "Docker image", which in turn are run in Docker as a
Docker container. A container is in effect a "running instance" of a Docker
image. From this perspective, an image is stored semi-permanently (i.e. insofar
as image updates are published), whereas containers are stored temporarily. Read
more about these concepts in the Docker documentation's
https://docs.docker.com/get-started/[Getting Started, Part 1: Orientation and
setup] page.

Docker's fundamental platform and container design means that a single Docker
image (for any given application like Jenkins) can be run on any operating
system (e.g. macOS, Linux and Windows) which is also running Docker.


==== Installing Docker

To install Docker on your operating system, visit the
link:https://www.docker.com/[Docker] website and navigate to *Get Docker* at
the top of their site to begin accessing the Docker download that's suitable
for your operating system. Follow the installation instructions on their
website.

*Note:* If you are installing Docker on a Linux-based operating system, ensure
you configure Docker so it can be managed as a non-root user. Read more about
this in Docker's
https://docs.docker.com/engine/installation/linux/linux-postinstall/[Post-installation
steps for Linux] page of their documentation. This page also contains
information about how to configure Docker to start on boot.


==== Which Docker image of Jenkins?

There are several Docker images of Jenkins available.

However, the recommended Docker image to use is the
link:https://hub.docker.com/r/jenkinsci/blueocean/[`jenkinsci/blueocean` image].
This image contains the current link:/download[Long-Term Support (LTS) release
of Jenkins] (which is production-ready) bundled with all Blue Ocean plugins and
features. This means that you do not need to install the Blue Ocean plugins
separately.

*Note:* A new `jenkinsci/blueocean` image is published each time a new release
of Blue Ocean is published.


*To download and run Jenkins with Blue Ocean in Docker:*

. Open up a terminal/command prompt window.
. Download the `jenkinsci/blueocean` image and run it as a container in Docker
  using the following
  link:https://docs.docker.com/engine/reference/commandline/run/[`docker run`]
  command:
** *On macOS and Linux:*
+
[source,bash]
----
docker run \
  --rm \  # <1>
  -d \ # <2>
  -p 8080:8080 \ # <3>
  -v jenkins-data:/var/jenkins_home \ # <4>
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkinsci/blueocean # <5>
----
<1> Automatically removes the Docker container (which is the instantiation of
the `jenkinsci/blueocean` image below) when it is shut down. This keeps things
tidy if you need to quit Jenkins.
<2> ( _Optional_ ) Runs the `jenkinsci/blueocean` container in the background
(i.e. "detached" mode) and outputs the container ID. If you do not specify this
option, then the running Docker log for this container is output in the terminal
window.
<3> Makes (i.e. "publishes") port 8080 of the `jenkinsci/blueocean` container to
port 8080 on the host machine. The 1st number represents the port on the host
while the 2nd represents the container's port. Therefore, if you specified `-p
49001:8080` for this option, you would be accessing Jenkins on your host machine
through port 49001.
<4> Maps the Docker
link:https://docs.docker.com/engine/admin/volumes/volumes/[volume] with the name
`jenkins-data` to the `/var/jenkins_home` directory in the container. If this
volume does not exist, then this `docker run` command will automatically create
the volume for you. +
*Note:* This volume could also be created independently using the
https://docs.docker.com/engine/reference/commandline/volume_create/[`docker
volume create`] command: +
`docker volume create jenkins-data`
<6> The `jenkinsci/blueocean` Docker image itself. If this image has not already
been downloaded, then this `docker run` command will automtically download the
image for you. Furthermore, if any updates to this image were published since
you last ran this command, then running this command again will automatically
download these published image updates for you. +
*Note:* This Docker image could also be downloaded (or updated) independently
using the https://docs.docker.com/engine/reference/commandline/pull/[`docker
pull`] command: +
`docker pull jenkinsci/blueocean`
+
*Note:* If copying and pasting the command snippet above doesn't work, try
copying and pasting this annotation-free version here:
+
[source,bash]
----
docker run \
  --rm \
  -d \
  -p 8080:8080 \
  -v jenkins-data:/var/jenkins_home \
  -v /var/run/docker.sock:/var/run/docker.sock \
  jenkinsci/blueocean
----

+
** *On Windows:* +
   The following command is effectively the same command shown for macOS/Linux
   above but if you're using the Windows command prompt, replace the backslash
   symbols `\` at the end of each line with carat symbols instead `^`, which
   gives you:
+
[source]
----
docker run ^
  --rm ^
  -d ^
  -p 8080:8080 ^
  -v jenkins-data:/var/jenkins_home ^
  -v /var/run/docker.sock:/var/run/docker.sock ^
  jenkinsci/blueocean
----

+
*Tip:* If you have some experience with Docker, you can add an option to the
`docker run` command like `--name jenkins-blueocean`, which would give the
`jenkinsci/blueocean` container the name "jenkins-blueocean". This would make it
easier to refer to the container if, for instance you needed to access the
container through a terminal/command prompt.

////
First, pull the official link:https://hub.docker.com/r/jenkins/jenkins[jenkins]
image from Docker repository.

[source,bash]
----
docker pull jenkins/jenkins
----

Next, run a container using this image and map data directory from the container
to the host; e.g in the example below `/var/jenkins_home` from the container is
mapped to `jenkins/` directory from the current path on the host. Jenkins `8080`
port is also exposed to the host as `49001`.

[source,bash]
----
docker run
  -d \
  -p 49001:8080 \
  -v $PWD/jenkins:/var/jenkins_home
  -t \
  jenkins/jenkins
----
////


=== macOS

To install from the website, using a package:

* link:http://mirrors.jenkins.io/osx/latest[Download the latest package]
* Open the package and follow the instructions

Jenkins can also be installed using `brew`:

* Install the latest release version
[source,bash]
----
brew install jenkins
----

* Install the LTS version
[source,bash]
----
brew install jenkins-lts
----


=== Linux

==== Debian/Ubuntu

On Debian-based distributions, such as Ubuntu, you can install Jenkins through `apt`.

Recent versions are available in link:https://pkg.jenkins.io/debian/[an apt repository]. Older but stable LTS versions are in link:https://pkg.jenkins.io/debian-stable/[this apt repository].

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

This package installation will:

* Setup Jenkins as a daemon launched on start. See `/etc/init.d/jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/etc/default/jenkins` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If your `/etc/init.d/jenkins` file fails to start Jenkins, edit the `/etc/default/jenkins` to replace the line
`----HTTP_PORT=8080----` with `----HTTP_PORT=8081----`
Here, "8081" was chosen but you can put another port available.
====


=== Windows

To install from the website, using the installer:

* link:http://mirrors.jenkins.io/windows/latest[Download the latest package]
* Open the package and follow the instructions


=== Other operating systems


==== OpenIndiana Hipster

On a system running link:http://www.openindiana.org/[OpenIndiana Hipster]
Jenkins can be installed in either the local or global zone using the
link:https://en.wikipedia.org/wiki/Image_Packaging_System[Image Packaging
System] (IPS).

[NOTE]
====
Disclaimer: This platform is NOT officially supported by the Jenkins team,
use it at your own risk. Packaging and integration described in this section
is maintained by the OpenIndiana Hipster team, bundling the generic `jenkins.war`
to work in that operating environment.
====

For the common case of running the newest packaged weekly build as a standalone (Jetty) server, simply execute:

[source,bash]
----
pkg install jenkins
svcadm enable jenkins
----

The common packaging integration for a standalone service will:

* Create a `jenkins` user to run the service and to own the directory structures under `/var/lib/jenkins`.
* Pull the OpenJDK8 and other packages required to execute Jenkins, including
  the `jenkins-core-weekly` package with the latest `jenkins.war`.
+
CAUTION: Long-Term Support (LTS) Jenkins releases currently do not support OpenZFS-based
systems, so no packaging is provided at this time.
* Set up Jenkins as an SMF service instance (`svc:/network/http:jenkins`) which
  can then be enabled with the `svcadm` command demonstrated above.
* Set up Jenkins to listen on port 8080.
* Configure the log output to be managed by SMF at `/var/svc/log/network-http:jenkins.log`.

Once Jenkins is running, consult the log
(`/var/svc/log/network-http:jenkins.log`) to retrieve the generated
administrator password for the initial set up of Jenkins, usually it will be
found at `/var/lib/jenkins/home/secrets/initialAdminPassword`. Then navigate to
link:http://localhost:8080[localhost:8080] to <<setupwizard, complete configuration of the
Jenkins instance>>.


To change attributes of the service, such as environment variables like `JENKINS_HOME`
or the port number used for the Jetty web server, use the `svccfg` utility:

[source,bash]
----
svccfg -s svc:/network/http:jenkins editprop
svcadm refresh svc:/network/http:jenkins
----

You can also refer to `/lib/svc/manifest/network/jenkins-standalone.xml` for more
details and comments about currently supported tunables of the SMF service.
Note that the `jenkins` user account created by the packaging is specially privileged
to allow binding to port numbers under 1024.

The current status of Jenkins-related packages available for the given release
of OpenIndiana can be queried with:

[source,bash]
----
pkg info -r '*jenkins*'
----

Upgrades to the package can be performed by updating the entire operating
environment with `pkg update`, or specifically for Jenkins core software with:

[source,bash]
----
pkg update jenkins-core-weekly
----

[CAUTION]
====
Procedure for updating the package will restart the currently running Jenkins
process. Make sure to prepare it for shutdown and finish all running jobs
before updating, if needed.
====



==== Solaris, OmniOS, SmartOS, and other siblings

Generally it should suffice to install Java 8 and link:/download[download] the
`jenkins.war` and run it as a standalone process or under an application server
such as link:http://tomcat.apache.org[Apache Tomcat].


Some caveats apply:

* Headless JVM and fonts: For OpenJDK builds on minimalized-footprint systems,
  there may be
  link:https://wiki.jenkins.io/display/JENKINS/Jenkins+got+java.awt.headless+problem[issues
  running the headless JVM], because Jenkins needs some fonts to render certain
  pages.
* ZFS-related JVM crashes: When Jenkins runs on a system detected as a `SunOS`,
  it tries to load integration for advanced ZFS features using the bundled
  `libzfs.jar` which maps calls from Java to native `libzfs.so` routines
  provided by the host OS. Unfortunately, that library was made for binary
  utilities built and bundled by the OS along with it at the same time, and was
  never intended as a stable interface exposed to consumers. As the forks of
  Solaris legacy, including ZFS and later the OpenZFS initiative evolved, many
  different binary function signatures were provided by different host
  operating systems - and when Jenkins `libzfs.jar` invoked the wrong
  signature, the whole JVM process crashed. A solution was proposed and
  integrated in `jenkins.war` since weekly release 2.55 (and not yet in any LTS
  to date) which enables the administrator to configure which function
  signatures should be used for each function known to have different variants,
  apply it to their application server initialization options and then run and
  update the generic `jenkins.war` without further workarounds. See
  link:https://github.com/kohsuke/libzfs4j[the libzfs4j Git repository] for
  more details, including a script to try and "lock-pick" the configuration
  needed for your particular distribution (in particular if your kernel updates
  bring a new incompatible `libzfs.so`).

Also note that forks of the OpenZFS initiative may provide ZFS on various
BSD, Linux, and macOS distributions. Once Jenkins supports detecting ZFS
capabilities, rather than relying on the `SunOS` check, the above caveats for
ZFS integration with Jenkins should be considered.


[[setupwizard]]
== Post-install (Setup Wizard)

=== Create Admin User and Password for Jenkins

Jenkins is initially configured to be secure on first launch.
Jenkins can no longer be accessed without a username and
password and open ports are limited. During the initial run of
Jenkins a security token is generated and printed in the console
log:

----
*************************************************************

Jenkins initial setup is required. A security token is required to proceed.
Please use the following security token to proceed to installation:

41d2b60b0e4cb5bf2025d33b21cb

*************************************************************
----

The install instructions for each of the platforms above includes the default location for when you can find this log output.
This token must be entered in the "Setup Wizard" the first time you open the Jenkins UI.
This token will also serve as the default password for the user 'admin' if you skip the user-creation step in the Setup Wizard.

=== Initial Plugin Installation

The Setup Wizard will also install the initial plugins for this Jenkins server.
The recommended set of plugins available are based on the most common use cases.
You are free to add more during the Setup Wizard or install them later as needed.
