== Java Requirement

Jenkins requires Java 17 or Java 21 (64-bit).  
Install Java before proceeding.  
Refer to the [_Installation Requirements_](./_installation_requirements.adoc) page for details.


---
layout: chapter
title: Installing Jenkins
---
ifdef::backend-html5[]
:notitle:
:description:
:sectanchors:
:toc:
:toclevels: 4
:imagesdir: ../resources
endif::[]

[pass]
++++
<!-- Redirect anchor references with Javascript -->
<!-- This is ONLY for anchor references like installing/#windows. -->
<!-- Use redirects as described in the contributing guide for page level redirects. -->
<!-- https://stackoverflow.com/questions/1305211/javascript-to-redirect-from-anchor-to-a-separate-page/21198129#21198129 -->
<script>
(function () {
    var anchorMap = {
        "ji-toolbar" : "/doc/book/installing/", /* Algolia search redirect to stay on same page */

        "accessing-the-jenkins-blue-ocean-docker-container": "/doc/book/installing/docker#accessing-the-jenkins-blue-ocean-docker-container",
        "accessing-the-jenkins-console-log-through-docker-logs": "/doc/book/installing/docker#accessing-the-jenkins-console-log-through-docker-logs",
        "accessing-the-jenkins-home-directory": "/doc/book/installing/docker/#accessing-the-jenkins-home-directory",
        "docker": "/doc/book/installing/docker/",
        "downloading-and-running-jenkins-in-docker": "/doc/book/installing/docker/",
        "installing-docker": "/doc/book/installing/docker/",
        "prerequisites-2": "/doc/book/installing/docker/#prerequisites",

        "configuring-http": "/doc/book/installing/initial-settings/#configuring-http",
        "miscellaneous-parameters": "/doc/book/installing/initial-settings/#miscellaneous-parameters",
        "networking-parameters": "/doc/book/installing/initial-settings/#networking-parameters",
        "using-http2": "/doc/book/installing/initial-settings/#using-http2",

        "creating-the-first-administrator-user": "/doc/book/installing/linux/#creating-the-first-administrator-user",
        "customizing-jenkins-with-plugins": "/doc/book/installing/linux/#customizing-jenkins-with-plugins",
        "debianubuntu": "/doc/book/installing/linux/#debianubuntu",
        "fedora": "/doc/book/installing/linux/#fedora",
        "linux": "/doc/book/installing/linux/",
        "prerequisites": "/doc/book/installing/linux/#prerequisites",
        "red-hat-centos": "/doc/book/installing/linux/#red-hat-centos",
        "setup-wizard": "/doc/book/installing/linux/#setup-wizard",
        "unlocking-jenkins": "/doc/book/installing/linux/#unlocking-jenkins",

        "freebsd": "/doc/book/installing/other/#freebsd",
        "openindiana-hipster": "/doc/book/installing/other/#openindiana-hipster",
        "other-operating-systems": "/doc/book/installing/other/",
        "solaris-omnios-smartos-and-other-siblings": "/doc/book/installing/other/#solaris-omnios-smartos-and-other-siblings",

        "https-certificates-with-windows": "/doc/book/installing/initial-settings/#https-certificates-with-windows",
        "https-with-an-existing-certificate": "/doc/book/installing/initial-settings/#https-with-an-existing-certificate",
        "jenkins-parameters": "/doc/book/installing/initial-settings/#jenkins-parameters",
        "jenkins-properties": "/doc/book/installing/initial-settings/#jenkins-properties",

        "kubernetes": "/doc/book/installing/kubernetes/",

        "macos": "/doc/book/installing/macos/",

        "offline-jenkins-installation": "/doc/book/installing/offline/",

        "war-file": "/doc/book/installing/war-file/",
        "war-files": "/doc/book/installing/war-file/",

        "windows": "/doc/book/installing/windows/",
    }
    /*
    * Best practice for extracting hashes:
    * https://stackoverflow.com/a/10076097/151365
    */
    var hash = window.location.hash.substring(1);
    if (hash) {
        /*
        * Best practice for javascript redirects:
        * https://stackoverflow.com/a/506004/151365
        */
        window.location.replace(anchorMap[hash]);
    }
})();
</script>
++++

The procedures in this chapter are for new installations of Jenkins.

Jenkins is typically run as a standalone application in its own process.
The Jenkins WAR file bundles link:https://github.com/jenkinsci/winstone[Winstone],
a link:https://www.eclipse.org/jetty/[Jetty] servlet container wrapper,
and can be started on any operating system or platform with a version of Java supported by Jenkins.

Theoretically, Jenkins can also be run as a servlet in a traditional servlet container
like link:https://tomcat.apache.org/[Apache Tomcat] or link:https://www.wildfly.org/[WildFly],
but in practice this is largely untested and there are many caveats.
In particular, support for WebSocket agents is only implemented for the Jetty servlet container.
See the link:/doc/book/platform-information/support-policy-servlet-containers[Servlet Container Support Policy] page for details.
