

== Java Requirement

Jenkins requires Java 17 or Java 21 (64-bit).  
Install Java before proceeding.  
Refer to the [_Installation Requirements_](./_installation_requirements.adoc) page for details.


---
layout: section
title: Kubernetes
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Kubernetes (K8s) is an open-source system for automating deployment, scaling,
and management of containerized applications.

A Kubernetes cluster adds a new automation layer to Jenkins.
Kubernetes makes sure that resources are used effectively and that your servers
and underlying infrastructure are not overloaded.
Kubernetes' ability to orchestrate container deployment ensures that Jenkins always
has the right amount of resources available.

Hosting Jenkins on a Kubernetes Cluster is beneficial for Kubernetes-based
deployments and dynamic container-based scalable Jenkins agents.

Several strategies for such setup and maintenance are explored below, including:

* Direct use of `kubectl` and YAML files to configure certain aspects of
  the deployment.
* Use of the `helm` tool and Helm Chart files to manage a whole ecosystem.
  For example, both the controller AND a population of agents where actual work
  happens.
* Further use of the Jenkins Operator to manage operations for Jenkins
  on Kubernetes in the cluster.

'''

Here, we see a step-by-step process for setting up Jenkins on a Kubernetes Cluster.

== Setup Jenkins On Kubernetes

For setting up a Jenkins Cluster on Kubernetes, we will do the following:

[arabic]
. <<create-a-namespace,Create a Namespace>>
. <<create-a-service-account,Create a service account>> with Kubernetes admin permissions.
. <<create-a-volume,Create local persistent volume>> for persistent Jenkins data on Pod restarts.
. <<create-a-deployment,Create a deployment YAML>> and deploy it.
. <<create-a-service,Create a service YAML>> and deploy it.

NOTE: This guide doesn’t use local persistent volume as this is a generic guide. 
For using persistent volume for your Jenkins data, you need to create volumes of relevant cloud or on-prem data center and configure it.

=== Jenkins Kubernetes Manifest Files

All the Jenkins Kubernetes manifest files used here are hosted on GitHub.
Please clone the repository if you have trouble copying the manifest from the document.

[source,bash]
----
git clone https://github.com/scriptcamp/kubernetes-jenkins
----

Use the GitHub files for reference and follow the steps in the next sections.

=== Kubernetes Jenkins Deployment

Let’s get started with deploying Jenkins on Kubernetes.

[#create-a-namespace]
*Step 1*: Create a Namespace for Jenkins.
It is good to categorize all the DevOps tools as a separate namespace from other applications.

[source,bash]
----
kubectl create namespace devops-tools
----

[#create-a-service-account]
*Step 2:* Create a 'jenkins-01-serviceAccount.yaml' file and copy the following admin service account manifest.
[source,yaml]
----
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-admin
  namespace: devops-tools
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jenkins-admin
subjects:
- kind: ServiceAccount
  name: jenkins-admin
  namespace: devops-tools
----

The 'jenkins-01-serviceAccount.yaml' creates a 'jenkins-admin' clusterRole, 'jenkins-admin' ServiceAccount and binds the 'clusterRole' to the service account.

The 'jenkins-admin' cluster role has all the permissions to manage the cluster components.
You can also restrict access by specifying individual resource actions.

Now create the service account using kubectl.

[source,bash]
----
kubectl apply -f jenkins-01-serviceAccount.yaml
----

[#create-a-volume]
**Step 3: **Create 'jenkins-02-volume.yaml' and copy the following persistent volume manifest.

[source,yaml]
----
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-storage
  claimRef:
    name: jenkins-pv-claim
    namespace: devops-tools
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker-node01
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pv-claim
  namespace: devops-tools
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
----

*Important Note:* Replace 'worker-node01' with any one of your cluster worker nodes hostname.

You can get the worker node hostname using the kubectl.

[source,bash]
----
kubectl get nodes
----

For volume, we are using the 'local' storage class for the purpose of demonstration. 
Meaning, it creates a 'PersistentVolume' volume in a specific node under the '/mnt' location.

As the 'local' storage class requires the node selector, you need to specify the worker node name correctly for the Jenkins pod to get scheduled in the specific node.

If the pod gets deleted or restarted, the data will get persisted in the node volume. 
However, if the node gets deleted, you will lose all the data.

Ideally, you should use a persistent volume using the available storage class with the cloud provider, or the one provided by the cluster administrator to persist data on node failures.

Let’s create the volume using kubectl

[source,bash]
----
kubectl create -f jenkins-02-volume.yaml
----

[#create-a-deployment]
*Step 4:* Create a Deployment file named 'jenkins-03-deployment.yaml' and copy the following deployment manifest.

[source,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins-server
    spec:
      securityContext:
            # Note: fsGroup may be customized for a bit of better
            # filesystem security on the shared host
            fsGroup: 1000 
            runAsUser: 1000
            ### runAsGroup: 1000
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          # OPTIONAL: check for new floating-tag LTS releases whenever the pod is restarted:
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home         
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim
----

In this Jenkins Kubernetes deployment we have used the following:

[arabic]
. The Jenkins container version is referenced in the example YAML above by a floating tag `lts`, so the optional `imagePullPolicy: Always` line is added to pull and deploy a new LTS image release (if it exists) *whenever* the pod is restarted. Otherwise, the currently deployed version is used after restart (and there's no other way to tell Kubernetes to pull a newer image, short of locating and deleting the old one from the node's cache).
  * Note that "whenever the pod is restarted" includes events such as a server reboot or the restart requested in Web-UI to apply downloaded plugin updates.
  * Kubernetes automatically uses this policy by default if the `:latest` image tag is specified, or none is specified at all (then the `:latest` image tag is automatically defaulted).
  * For predictable and deterministic updates, use the version-based image tags instead. Search https://hub.docker.com/r/jenkins/jenkins/tags for the ones currently served.
  * Consider an image tag like `lts-jdk21` to avoid surprises when the Jenkins core switches to using a newer JDK (usually they are backwards compatible, but...) or stay with `lts` for indefinite hands-off maintenance approach.
. The `spec:/strategy:/type: Recreate` requires that Kubernetes first stops the old container instance, then starts a new one a few seconds later, whenever a restart is requested such as pulling in a new Jenkins version.
. 'securityContext' for Jenkins pod to be able to write to the local persistent volume.
  * Note that `fsGroup` specifies the group ID used for mounted filesystem access,
    while `runAsUser` and `runAsGroup` specify the account IDs all process runs as
    (as seen by both the host OS and the container guest operating environment).
    There is no `fsUser` equivalent.
  * One caveat is that the Jenkins container has ID 1000 defined in its `/etc/passwd`
    and `/etc/group` files, and e.g. `git` program requires that the identifier of
    the user it runs as is resolvable.  While it is trivial to define desired accounts
    in a derived container (made `FROM jenkins:lts` for example) and run as accounts
    according to your site preferences, it is clumsy out of the box.
. Liveness and readiness probe to monitor the health of the Jenkins pod.
. Local persistent volume based on local storage class that holds the Jenkins data
  path '/var/jenkins_home'. You may have to prepare it with:
+
----
runAsUser=1000
fsGroup=1000   # Or custom ID, per above
mkdir -p /var/jenkins_home
chown -R $runAsUser:$fsGroup /var/jenkins_home
chmod -R g+rwX /var/jenkins_home
----

NOTE: The deployment file uses local storage class persistent volume for Jenkins data. 
For production use cases, you should add a cloud-specific storage class persistent volume for your Jenkins data.

If you don’t want the local storage persistent volume, you can replace the volume definition in the deployment with the host directory as shown below.

[source,yaml]
----
volumes:
- name: jenkins-data
  emptyDir: \{}
----

Create the deployment using kubectl.

[source,bash]
----
kubectl apply -f jenkins-03-deployment.yaml
----

Check the deployment status.

[source,bash]
----
kubectl get deployments -n devops-tools
----

Now, you can get the deployment details using the following command.

[source,bash]
----
kubectl describe deployments --namespace=devops-tools
----

[#create-a-service]
=== Accessing Jenkins Using Kubernetes Service

We have now created a deployment. 
However, it is not accessible to the outside world.
For accessing the Jenkins deployment from the outside world, we need to create a service and map it to the deployment.

Create 'jenkins-04-service.yaml' and copy the following service manifest:

[source,yaml]
----
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-server
  type: NodePort  
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32000
----

NOTE: Here, we are using the type as 'NodePort' which will expose Jenkins on all kubernetes node IPs on port 32000.
If you have an ingress setup, you can create an ingress rule to access Jenkins. 
Also, you can expose the Jenkins service as a Loadbalancer if you are running the cluster on AWS, Google, or Azure cloud.

Create the Jenkins service using kubectl.

[source,bash]
----
kubectl apply -f jenkins-04-service.yaml
---- 

Now, when browsing to any one of the Node IPs on port 32000, you will be able to access the Jenkins dashboard.

[source]
----
http://<node-ip>:32000
----

Jenkins will ask for the initial Admin password when you access the dashboard for the first time.

You can get that from the pod logs either from the Kubernetes dashboard or CLI.
You can get the pod details using the following CLI command.

[source,bash]
----
kubectl get pods --namespace=devops-tools
----

With the pod name, you can get the logs as shown below. 
Replace the pod name with your pod name.

[source,bash]
----
kubectl logs jenkins-deployment-2539456353-j00w5 --namespace=devops-tools
----

The password can be found at the end of the log.

[NOTE]
======
You can watch the Jenkins server logs (posted to `stdout` or `stderr` of the JVM and collected by Kubernetes) with the following loop to handle Jenkins restarts as well:

----
while sleep 0.1 ; do kubectl logs -f -l app=jenkins-server -n devops-tools ; done &
----

(The label `jenkins-server` is defined in `jenkins-03-deployment.yaml`)

Alternatively, link:https://github.com/stern/stern[stern] tool can be used to watch multiple pods' logs.
======

Alternatively, you can run the exec command to get the password directly from the location as shown below.

* Using the first (normally only) instance of the application pod:
+
[source,bash]
----
kubectl exec -it "deployment.apps/jenkins" cat /var/jenkins_home/secrets/initialAdminPassword -n devops-tools
----

* ...or, using a specific container instance:
+
[source,bash]
----
kubectl exec -it jenkins-559d8cd85c-cfcgk cat /var/jenkins_home/secrets/initialAdminPassword -n devops-tools
----

Once you enter the password, proceed to install the suggested plugins and create an admin user.
All of these steps are self-explanatory from the Jenkins dashboard.

'''

Below we will explore further deployment strategies.

include::doc/book/installing/_kubernetes.adoc[]

include::doc/book/installing/_setup-wizard.adoc[]

== Conclusion

When you host Jenkins on Kubernetes for production workloads, you need to consider setting up a highly available persistent volume, to avoid data loss during pod or node deletion.

A pod or node deletion could happen anytime in Kubernetes environments.
It could be a patching activity or a downscaling activity.

Hopefully, this step-by-step guide helps you learn and understand the components involved in setting up a Jenkins server on a Kubernetes cluster.
