---
layout: section
title: Linux
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Jenkins installers are available for several Linux distributions.

* <<Debian/Ubuntu>>
* <<Fedora>>
* <<Red Hat / CentOS>>

include::doc/book/installing/_installation_requirements.adoc[]

== Debian/Ubuntu

On Debian and Debian-based distributions like Ubuntu you can install Jenkins through `apt`.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/debian-stable/[`debian-stable` apt repository].

[source,bash]
----
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins
----

The LTS package installation will:

* Setup Jenkins as a daemon launched on start. See `/etc/init.d/jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/etc/default/jenkins` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If your `/etc/init.d/jenkins` file fails to start Jenkins, edit the `/etc/default/jenkins` to replace the line
`HTTP_PORT=8080` with `HTTP_PORT=8081`
Here, "8081" was chosen but you can put another port available.
====

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/debian/[`debian` apt repository].

[source,bash]
----
curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins
----

Beginning with Jenkins 2.335, the weekly package is configured with systemd rather than the older System V init.
See the link:https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units[DigitalOcean community systemd tutorial] to better understand the benefits of `systemd` and the `systemctl` command.

The weekly package installation will:

* Setup Jenkins as a daemon launched on start. See `/lib/systemd/system/jenkins.service` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/lib/systemd/system/jenkins.service` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If Jenkins fails to start because a port is in use,
add the following to `/etc/systemd/system/jenkins.service.d/override.conf`:

[source]
----
[Service]
Environment="JENKINS_PORT=8081"
----

Here, "8081" was chosen but you can put another port available.
====

=== Installation of Java

Jenkins requires Java in order to run, yet certain distributions don't include this by default and  link:/doc/administration/requirements/java/[some Java versions are incompatible] with Jenkins.

There are multiple Java implementations which you can use. link:https://openjdk.java.net/[OpenJDK] is the most popular one at the moment, we will use it in this guide.

Update the Debian apt repositories, install OpenJDK 11, and check the installation with the commands:
[source,bash]
----
$ sudo apt update
$ sudo apt install openjdk-11-jdk
$ java -version
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.12+7-post-Debian-2, mixed mode, sharing)
----

[NOTE]
====
Why use `apt` and not `apt-get` or another command?
The apt command has been available since 2014.
It has a command structure that is similar to `apt-get` but was created to be a more pleasant experience for typical users.
Simple software management tasks like install, search and remove are easier with `apt`.
====

== Fedora

You can install Jenkins through `dnf`. You need to add the Jenkins repository from the Jenkins website to the package manager first.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo dnf upgrade
# Add required dependencies for the jenkins package
sudo dnf install chkconfig java-devel
sudo dnf install jenkins
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo dnf upgrade
sudo dnf install java-devel jenkins
----

=== Start Jenkins

Register the Jenkins service with the command:

[source,bash]
----
sudo systemctl daemon-reload
----

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/lib/systemd/system/jenkins.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

== Red Hat / CentOS

You can install Jenkins through `yum` on Red Hat Enterprise Linux, CentOS, and other Red Hat based distributions.

.How To Install Jenkins on CentOS 7
video::g7CnQnDQwuU[youtube, width=682, height=384]

You need to choose either the Jenkins Long Term Support release or the Jenkins weekly release.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade
sudo yum install java-11-openjdk-devel jenkins
sudo systemctl daemon-reload
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum upgrade
sudo yum install java-11-openjdk-devel jenkins
sudo systemctl daemon-reload
----

=== Start Jenkins

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/lib/systemd/system/jenkins.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
...
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

include::doc/book/installing/_setup-wizard.adoc[]
