---
layout: section
title: Linux
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Jenkins installers are available for several Linux distributions.

* <<Debian/Ubuntu>>
* <<Fedora>>
* <<red-hat-centos,Red Hat/Alma/Rocky>>

include::doc/book/installing/_installation_requirements.adoc[]

== Debian/Ubuntu

On Debian and Debian-based distributions like Ubuntu you can install Jenkins through `apt`.

NOTE: With the release of link:https://www.debian.org/News/2023/20230610[Debian 12], OpenJDK 11 is *no longer* included.
It has been replaced with link:https://openjdk.org/projects/jdk/17/[OpenJDK 17], which is reflected in the instructions below.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/debian-stable/[`debian-stable` apt repository].

[source,bash]
----
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/debian/[`debian` apt repository].

[source,bash]
----
curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null
sudo apt-get update
sudo apt-get install jenkins
----

Beginning with Jenkins 2.335 and Jenkins 2.332.1, the package is configured with `systemd` rather than the older System V `init`.
See the link:https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units[DigitalOcean community `systemd` tutorial] to better understand the benefits of `systemd` and the `systemctl` command.

The package installation will:

* Setup Jenkins as a daemon launched on start. Run `systemctl cat jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to `systemd-journald`. Run `journalctl -u jenkins.service` if you are troubleshooting Jenkins.
* Populate `/lib/systemd/system/jenkins.service` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If Jenkins fails to start because a port is in use,
run `systemctl edit jenkins` and add the following:

[source]
----
[Service]
Environment="JENKINS_PORT=8081"
----

Here, "8081" was chosen but you can put another port available.
====

=== Installation of Java

Jenkins requires Java to run, yet not all Linux distributions include Java by default.
Additionally, link:/doc/book/platform-information/support-policy-java/[not all Java versions are compatible] with Jenkins.

There are multiple Java implementations which you can use.
link:https://openjdk.java.net/[OpenJDK] is the most popular one at the moment, we will use it in this guide.

Update the Debian apt repositories, install OpenJDK 17, and check the installation with the commands:
[source,bash]
----
sudo apt update
sudo apt install fontconfig openjdk-17-jre
java -version
openjdk version "17.0.8" 2023-07-18
OpenJDK Runtime Environment (build 17.0.8+7-Debian-1deb12u1)
OpenJDK 64-Bit Server VM (build 17.0.8+7-Debian-1deb12u1, mixed mode, sharing)
----

[NOTE]
====
Why use `apt` and not `apt-get` or another command?
The apt command has been available since 2014.
It has a command structure that is similar to `apt-get` but was created to be a more pleasant experience for typical users.
Simple software management tasks like install, search and remove are easier with `apt`.
====

== Fedora

You can install Jenkins through `dnf`. You need to add the Jenkins repository from the Jenkins website to the package manager first.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo dnf upgrade
# Add required dependencies for the jenkins package
sudo dnf install fontconfig java-17-openjdk
sudo dnf install jenkins
sudo systemctl daemon-reload
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io-2023.key
sudo dnf upgrade
# Add required dependencies for the jenkins package
sudo dnf install fontconfig java-17-openjdk
sudo dnf install jenkins
----

=== Start Jenkins

You can enable the Jenkins service to start at boot with the command:

[source,bash]
----
sudo systemctl enable jenkins
----

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/lib/systemd/system/jenkins.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

[#red-hat-centos]
== Red Hat/Alma/Rocky

You can install Jenkins through `yum` on Red Hat Enterprise Linux, Alma Linux, Rocky Linux, Oracle Linux, and other Red Hat based distributions.

.How To Install Jenkins on Rocky Linux 9
video::2-L0WohfsqY[youtube, width=640, height=360]

You need to choose either the Jenkins Long Term Support release or the Jenkins weekly release.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
sudo yum upgrade
# Add required dependencies for the jenkins package
sudo yum install fontconfig java-17-openjdk
sudo yum install jenkins
sudo systemctl daemon-reload
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io-2023.key
sudo yum upgrade
# Add required dependencies for the jenkins package
sudo yum install fontconfig java-17-openjdk
sudo yum install jenkins
----

=== Start Jenkins

You can enable the Jenkins service to start at boot with the command:

[source,bash]
----
sudo systemctl enable jenkins
----

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/lib/systemd/system/jenkins.service; enabled; vendor preset: enabled)
Active: active (running) since Tue 2023-06-22 16:19:01 +03; 4min 57s ago
...
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

include::doc/book/installing/_setup-wizard.adoc[]
