---
layout: section
title: Linux
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Jenkins installers are available for several Linux distributions.

* <<Debian/Ubuntu>>
* <<Fedora>>
* <<Red Hat / CentOS>>

include::doc/book/installing/_installation_requirements.adoc[]

== Debian/Ubuntu

On Debian and Debian-based distributions like Ubuntu you can install Jenkins through `apt`.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/debian-stable/[`debian-stable` apt repository].

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/debian/[`debian` apt repository].

[source,bash]
----
wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -
sudo sh -c 'echo deb https://pkg.jenkins.io/debian binary/ > \
    /etc/apt/sources.list.d/jenkins.list'
sudo apt-get update
sudo apt-get install jenkins
----

[NOTE]
====
If an error is reported, "`jenkins : Depends: daemon but it is not installable`", add the link:https://help.ubuntu.com/community/Repositories/Ubuntu["universe" apt repository] of community maintained free and open source software for Ubuntu by executing this command after `sudo apt-get update`:
[source,bash]
----
sudo add-apt-repository universe
----
====

This package installation will:

* Setup Jenkins as a daemon launched on start. See `/etc/init.d/jenkins` for more details.
* Create a '`jenkins`' user to run this service.
* Direct console log output to the file `/var/log/jenkins/jenkins.log`. Check this file if you are troubleshooting Jenkins.
* Populate `/etc/default/jenkins` with configuration parameters for the launch, e.g `JENKINS_HOME`
* Set Jenkins to listen on port 8080. Access this port with your browser to start configuration.

[NOTE]
====
If your `/etc/init.d/jenkins` file fails to start Jenkins, edit the `/etc/default/jenkins` to replace the line
`----HTTP_PORT=8080----` with `----HTTP_PORT=8081----`
Here, "8081" was chosen but you can put another port available.
====

=== Installation of Java

Jenkins requires Java in order to run, yet certain distributions don't include this by default and  link:/doc/administration/requirements/java/[some Java versions are incompatible] with Jenkins.

There are multiple Java implementations which you can use. link:https://openjdk.java.net/[OpenJDK] is the most popular one at the moment, we will use it in this guide.

To install the Open Java Development Kit (OpenJDK) run the following:

* Update the repositories
[source,bash]
----
sudo apt update
----
* search of all available packages:
[source,bash]
----
sudo apt search openjdk
----
* Pick one option and install it:
[source,bash]
----
sudo apt install openjdk-11-jdk
----
* Confirm installation:
[source,bash]
----
sudo apt install openjdk-11-jdk
----
* checking installation:
[source,bash]
----
java -version
----
* the result must be something like:
[source,bash]
----
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
----

[NOTE]
====
Why use `apt` and not `apt-get` or another command?
The apt command has been available since 2014.
It has a command structure that is similar to `apt-get` but was created to be a more pleasant experience for typical users.
Simple software management tasks like install, search and remove are easier with `apt`.
====

== Fedora

You can install Jenkins through `dnf`. You need to add the Jenkins repository from the Jenkins website to the package manager first.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo dnf upgrade
# Add required dependencies for the jenkins package
sudo dnf install chkconfig java-devel
sudo dnf install jenkins
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo dnf upgrade
sudo dnf install chkconfig java-devel
sudo dnf install jenkins
----

=== Start Jenkins

Register the Jenkins service with the command:

[source,bash]
----
sudo systemctl daemon-reload
----

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/etc/rc.d/init.d/jenkins; generated)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

== Red Hat / CentOS

You can install Jenkins through `yum` on Red Hat Enterprise Linux, CentOS, and other Red Hat based distributions.
You need to choose either the Jenkins Long Term Support release or the Jenkins weekly release.

=== Long Term Support release

A link:/download/lts/[LTS (Long-Term Support) release] is chosen every 12 weeks from the stream of regular releases as the stable release for that time period.
It can be installed from the link:https://pkg.jenkins.io/redhat-stable/[`redhat-stable`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat-stable/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-1.8.0-openjdk-devel
sudo systemctl daemon-reload
----

=== Weekly release

A new release is produced weekly to deliver bug fixes and features to users and plugin developers.
It can be installed from the link:https://pkg.jenkins.io/redhat/[`redhat`] yum repository.

[source,bash]
----
sudo wget -O /etc/yum.repos.d/jenkins.repo \
    https://pkg.jenkins.io/redhat/jenkins.repo
sudo rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
sudo yum upgrade
sudo yum install jenkins java-1.8.0-openjdk-devel
sudo systemctl daemon-reload
----

=== Start Jenkins

You can start the Jenkins service with the command:

[source,bash]
----
sudo systemctl start jenkins
----

You can check the status of the Jenkins service using the command:

[source,bash]
----
sudo systemctl status jenkins
----

If everything has been set up correctly, you should see an output like this:

[source,bash]
----
Loaded: loaded (/etc/rc.d/init.d/jenkins; generated)
Active: active (running) since Tue 2018-11-13 16:19:01 +03; 4min 57s ago
...
----

[NOTE]
====
If you have a firewall installed, you must add Jenkins as an exception.
You must change `YOURPORT` in the script below to the port you want to use.
Port `8080` is the most common.

[source,bash]
----
YOURPORT=8080
PERM="--permanent"
SERV="$PERM --service=jenkins"

firewall-cmd $PERM --new-service=jenkins
firewall-cmd $SERV --set-short="Jenkins ports"
firewall-cmd $SERV --set-description="Jenkins port exceptions"
firewall-cmd $SERV --add-port=$YOURPORT/tcp
firewall-cmd $PERM --add-service=jenkins
firewall-cmd --zone=public --add-service=http --permanent
firewall-cmd --reload
----

====

include::doc/book/installing/_setup-wizard.adoc[]
