---
layout: section
title: Offline Installations
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

This section describes how to install Jenkins on a machine
that does not have an internet connection.

To install Jenkins itself, download the appropriate war file and
transfer it to your machine.

include::doc/book/installing/_installation_requirements.adoc[]

=== Offline plugin installation

Offline plugin installations require additional effort due to dependency requirements.

The link:https://github.com/jenkinsci/plugin-installation-manager-tool[Plugin Installation Manager Tool] is the recommended tool for offline plugin installation.
It downloads user specified plugins and all dependencies of the user specified plugins.
The link:https://github.com/jenkinsci/plugin-installation-manager-tool[Plugin Installation Manager Tool] also reports available plugin updates and plugin security warnings.
It is included in the official link:https://github.com/jenkinsci/docker/blob/master/README.md#preinstalling-plugins[Jenkins Docker images].
It is also used to install plugins as part of the link:/doc/book/installing/docker/[Docker install instructions].
Refer to the link:https://app.gitter.im/#/room/#jenkinsci_plugin-installation-manager-cli-tool:gitter.im[Gitter chat channel] for questions and answers

If you want to transfer the individual plugins, you'll need to retrieve
all dependencies as well. There are several dependency retrieval scripts and tools
on Github. For example:

* link:https://github.com/jenkinsci/plugin-installation-manager-tool/blob/master/README.md[Plugin installation manager tool] - Java command line utility to install Jenkins plugins and their dependencies.
* link:https://github.com/samrocketman/jenkins-bootstrap-shared[samrocketman/jenkins-bootstrap-shared] - Java is
required; packages Jenkins and plugins into an immutable package
installer.  Supported formats include: RPM, DEB, Docker. Can proxy
Jenkins and plugins through Nexus or Artifactory since Gradle is used to
assemble plugins.

include::doc/book/installing/_setup-wizard.adoc[]
