---
layout: section
title: Offline Installations
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

This section describes how to install Jenkins on a machine
that does not have an internet connection.

To install Jenkins itself, download the appropriate war file and
transfer it to your machine.

include::doc/book/installing/_installation_requirements.adoc[]

=== Offline plugin installation

Plugins are a different matter, due to dependency requirements. 

The recommended approach is to use link:https://github.com/jenkinsci/plugin-installation-manager-tool[Plugin Installation Manager Tool].

If you want to transfer the individual plugins, you'll need to retrieve
all dependencies as well. There are several dependency retrieval scripts and tools
on Github. For example:

* link:https://github.com/jenkinsci/docker/blob/master/install-plugins.sh[install-plugins.sh] - Bash script for managing plugins from the official Docker image for Jenkins
* link:https://github.com/samrocketman/jenkins-bootstrap-shared[samrocketman/jenkins-bootstrap-shared] - Java is
required; packages Jenkins and plugins into an immutable package
installer.  Supported formats include: RPM, DEB, Docker. Can proxy
Jenkins and plugins through Nexus or Artifactory since Gradle is used to
assemble plugins.

include::doc/book/installing/_setup-wizard.adoc[]
