---
layout: section
title: Other Servlet Containers
---
ifdef::backend-html5[]
:description:
:author:
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

Jenkins is typically run as a standalone application in its own process.
The Jenkins WAR file bundles link:https://github.com/jenkinsci/winstone[Winstone],
a link:https://www.eclipse.org/jetty/[Jetty] servlet container wrapper,
and can be started on any operating system or platform with a version of Java supported by Jenkins.
This is the preferred way to deploy Jenkins and is fully supported.

Theoretically, Jenkins can also be run as a servlet in a traditional servlet container
like link:https://tomcat.apache.org/[Apache Tomcat] or link:https://www.wildfly.org/[WildFly],
but in practice this is largely untested and there are many caveats.
In particular, support for WebSocket agents is only implemented for the Jetty servlet container.
See the link:/doc/book/platform-information/support-policy-servlet-containers[Servlet Container Support Policy] page for details.

WARNING: Support for traditional servlet containers may be discontinued in the future.

== Requirements
* **Jenkins 2.492.3 and later requires Servlet API 5.0 (Jakarta EE 9)**
* Compatible containers:
  * **Tomcat 10.1.x** (Tested with 10.1.40 - latest version)
  * WildFly version needs verification (minimum 30+ recommended)
* Requires JDK 17 or later for full compatibility

== Tomcat 10
### Deployment
[source,bash]
----
# Download Tomcat 10.1.x
wget https://archive.apache.org/dist/tomcat/tomcat-10/v10.1.40/bin/apache-tomcat-10.1.40.tar.gz

# Extract and deploy
tar xzf apache-tomcat-10.1.40.tar.gz
export CATALINA_HOME=$(pwd)/apache-tomcat-10.1.40
cp jenkins.war $CATALINA_HOME/webapps/
----

### Configuration
**Set Jenkins home:**
[source,bash]
----
mkdir /var/lib/jenkins
echo "export CATALINA_OPTS=-DJENKINS_HOME=/var/lib/jenkins" > $CATALINA_HOME/bin/setenv.sh
chmod +x $CATALINA_HOME/bin/setenv.sh
----

[source,xml]
----
<Valve className="org.apache.catalina.valves.RemoteIpValve"
       remoteIpHeader="X-Forwarded-For"
       protocolHeader="X-Forwarded-Proto" />
----

== WildFly
*Minimum version needs community verification*
* WildFly 26 and earlier are incompatible
* WildFly 30 or later recommended for JDK 17 support

NOTE: Running multiple Jenkins controllers within a single Java process is unsupported.
