---
layout: section
title: WAR files
---
ifdef::backend-html5[]
:description:
:author:
:email: jenkinsci-docs@googlegroups.com
:sectanchors:
:toc:
:toclevels: 4
:hide-uri-scheme:
ifdef::env-github[:imagesdir: ../resources]
ifndef::env-github[:imagesdir: ../../resources]
endif::[]

The Web application ARchive (WAR) file version of Jenkins can be installed on
any operating system or platform that runs a version of Java supported by Jenkins.
See the link:/doc/administration/requirements/java[Java Requirements] page for details.

include::doc/book/installing/_installation_requirements.adoc[]

== Run the WAR file

The Jenkins Web application ARchive (WAR) file can be started from the command line like this:

. Download the
  link:/download[latest stable
  Jenkins WAR file] to an appropriate directory on your machine.
. Open up a terminal/command prompt window to the download directory.
. Run the command `java -jar jenkins.war`.
. Browse to `\http://localhost:8080` and wait until the *Unlock Jenkins* page
  appears.
. Continue on with the <<setup-wizard,Post-installation setup wizard>> below.

*Notes:*

* Unlike downloading and running Jenkins with Blue Ocean in Docker
  (<<docker,above>>), this process does not automatically install the Blue Ocean
  features, which would need to installed separately via the
  link:../../book/managing[**Manage Jenkins**] >
  link:../../book/managing/plugins/[**Manage Plugins**] page in Jenkins. Read
  more about the specifics for installing Blue Ocean on the
  link:/doc/book/blueocean/getting-started/[Getting started with Blue Ocean]
  page.
* You can change the port by specifying the `--httpPort` option when you run the
  `java -jar jenkins.war` command. For example, to make Jenkins accessible
  through port 9090, then run Jenkins using the command: +
  `java -jar jenkins.war --httpPort=9090`

include::doc/book/installing/_setup-wizard.adoc[]
