---
layout: security
title: "Jenkins Security"
section: security
---

The Jenkins project takes security seriously.
We make every possible effort to ensure users can adequately secure their automation infrastructure.
To that end, we work with Jenkins core and plugin developers, as well as security researchers, to fix security vulnerabilities in Jenkins in a timely manner, and to improve the security of Jenkins in general.

Learn more about link:/doc/book/security/[Securing Jenkins] in the Jenkins User Handbook.

[[advisories]]
== Security Advisories

Security advisories are the primary way to publicly inform Jenkins users about security issues in Jenkins and Jenkins plugins.
You can find all past security advisories in our link:/security/advisories/[security advisories archive].

We announce the publication of a new security advisory through multiple channels:

* We send an email notification to the public link:https://groups.google.com/g/jenkinsci-advisories[`jenkinsci-advisories`] Google group with a short overview of affected components and a link to the security advisory. Only Jenkins security team members can post. You can link:mailto:jenkinsci-advisories+subscribe@googlegroups.com[subscribe] and link:mailto:jenkinsci-advisories+unsubscribe@googlegroups.com[unsubscribe] via email.
* We send an email notification to the link:https://oss-security.openwall.org/wiki/mailing-lists/oss-security[`oss-security`] mailing list with excerpts of the security advisory.
* We publish an link:/security/advisories/rss.xml[RSS feed for the jenkins.io/security/advisories/] page.

Additionally, Jenkins administrators are informed about published security issues directly in Jenkins if they have affected versions of Jenkins or plugins installed.

Finally, the Jenkins project is a link:/security/cna[CVE Numbers Authority], and we submit CVE metadata simultaneously with the publication of security advisories, allowing automated security tools using CVE information to identify vulnerable installations.

[IMPORTANT]
====
Even if you run Jenkins on a private network and trust everyone in your team, security issues in Jenkins can still impact you:

- https://en.wikipedia.org/wiki/Cross-site_request_forgery[CSRF vulnerabilities] are a risk even if attackers have no direct access to Jenkins.
- Does Jenkins build source code you haven't audited, using build scripts someone else wrote, displaying generated reports on its web UI?
  All of these are potential security concerns.
====


[[reporting-vulnerabilities]]
== How to Report a Security Vulnerability

If you find a vulnerability in Jenkins, please link:https://issues.jenkins.io/secure/CreateIssueDetails!init.jspa?pid=10180&issuetype=10103[report it in the issue tracker under the SECURITY project].
This project is configured in such a way that only the reporter, the maintainers, and the Jenkins security team can see the details.
Restricting access to this potentially sensitive information allows core and plugin maintainers to develop effective security fixes that are safe to apply.
We provide issue reporting guidelines and an overview of our process on link:reporting[Reporting Security Vulnerabilities].

If you are unable to report using our issue tracker, you can also send your report to the private Jenkins Security Team mailing list:
`jenkinsci-cert@googlegroups.com`

NOTE: From late 2025 to late 2026, a bug bountry program accepts reports of security vulnerabilities in Jenkins core, components, and some plugins.
For more details please see link:/blog/2025/12/10/jenkins-bug-bounty-program-yeswehack-european-commission/[the announcement blog post] and link:https://yeswehack.com/programs/jenkins-bug-bounty-program/[the program on YesWeHack].

IMPORTANT: Do not contact the Jenkins security team asking us for compliance documents, certifications, or to fill out a questionnaire.
We will not respond to such queries.
If we consider it necessary to provide a statement in response to incidents such as link:/blog/2021/12/10/log4j2-rce-CVE-2021-44228/[log4shell] or link:/blog/2022/03/31/spring-rce-CVE-2022-22965/[SpringShell], you will find a response in our link:/blog/[blog].


== Learn More

link:plugins[How We Handle Vulnerabilities in Plugins]::
We strive to fix all security vulnerabilities in Jenkins and plugins in a timely manner.
However the number and diversity of plugins and maintainers' autonomy make this impossible to guarantee.

link:scheduling[How We Schedule Security Advisories]::
Information about how we schedule security advisories and security updates.

link:fixing[How We Fix Security Issues]::
Guidelines for developing security fixes in the Jenkins project.

link:for-maintainers[Information for Plugin Maintainers]::
The Jenkins security team contacted me about a security vulnerability. Now what?

link:for-administrators[Information for Administrators]::
This page explains everything Jenkins users and administrators need to know about the Jenkins security process.

link:cna[Jenkins CVE Numbers Authority]::
The Jenkins project is a CVE Numbers Authority (CNA) for Jenkins and Jenkins plugins published by the Jenkins project.

link:team[About the Jenkins Security Team]::
The Jenkins Security Team is a group of volunteers led by the Jenkins Security Officer who triage and fix security vulnerabilities.

link:improvements[Improvements by the Security Team]::
These are some contributions by members of the Jenkins security team that weren't delivered as security fixes, but still are security-related.
