---
layout: simplepage
title: "Jenkins Security"
section: security
---

The Jenkins project takes security seriously.
We make every possible effort to ensure users can adequately secure their automation infrastructure.
To that end, we work with core developers and security researchers to fix security vulnerabilities in Jenkins in a timely manner, and to improve the security of Jenkins in general.

link:/doc/book/operating/security/[Learn more about securing Jenkins] in the Jenkins User Handbook.

== Security Advisories

See our link:/security/advisories/[archive of past security advisories] for previously published security advisories.

== Security Notifications

We use the +jenkinsci-advisories+ Google group to inform users about upcoming, scheduled security updates:

- link:https://groups.google.com/forum/#!forum/jenkinsci-advisories[+jenkinsci-advisories+ list archive]
- link:https://feeds.feedburner.com/jenkins-security-advisories[+jenkinsci-advisories+ RSS feed]

Once a security update has been released, we inform the +jenkinsci-advisories+ and link:http://oss-security.openwall.org/wiki/mailing-lists/oss-security[+oss-security+] mailing lists.

We recommend you subscribe to link:https://groups.google.com/forum/#!forum/jenkinsci-advisories[+jenkinsci-advisories+] even if your Jenkins instance is not publicly accessible to receive timely notifications on security updates.

== How to Report an Issue

If you find a vulnerability in Jenkins, please report it in the issue tracker under the link:https://issues.jenkins-ci.org/browse/SECURITY[SECURITY project].
This project is configured in such a way that only the reporter and the security team can see the details.
By restricting access to this potentially sensitive information we can work on a fix and deliver it before the method of attack becomes well-known.

To show our appreciation for your help, we offer link:https://wiki.jenkins-ci.org/display/JENKINS/Rewards+for+reporting+security+issues[a small reward] for your report.

== Jenkins Security Team

The Jenkins Security Team is a group of volunteers lead by the link:https://wiki.jenkins-ci.org/display/JENKINS/Team+Leads[Jenkins Security Officer] who triage and fix security vulnerabilities.

Membership is generally open to anyone with a history of positive contributions to the Jenkins project and subject to approval by the Jenkins Security Officer.
If you want to contribute, be sure to have link:https://help.github.com/articles/securing-your-account-with-two-factor-authentication-2fa/[two-factor authentication enabled on GitHub], link:https://github.com/jenkinsci/infra-cla/[a CLA] in place, a link:https://freenode.net/faq.shtml#userregistration[registered nickname on IRC].
Then, just contact us on the link:/content/mailing-lists[developers mailing list] with your GitHub, Freenode, and Jenkins community user names.

Security vulnerabilities in core are typically resolved by members of this team, while vulnerabilities in plugins are generally resolved in collaboration with the plugin maintainer(s).
To that end, plugin maintainers are granted access to issues involving their plugin in our issue tracker, and we create private repositories link:https://github.com/jenkinsci-cert/[in the +jenkinsci-cert+ GitHub organization] for collaboration and PR review.

== Vulnerabilities in Plugins

We strive to fix all security vulnerabilities in Jenkins and plugins in a timely manner.
However, the structure of the Jenkins project and the number of plugins make this impossible:

- Plugins are often independently maintained by developers we may have no direct contact with, or may not have an active maintainer at all.
- The number of plugins in existence exceeds the security team's capacity to fix them.

In case of a plugin vulnerability, we try to contact the plugin maintainer(s) to inform them of it.
If they decline (or otherwise fail) to fix the vulnerability, or don't respond in a timely manner, and the security team doesn't have the capacity to fix it, we follow the process outlined below in the interest of our users:

. Publish a security advisory about the plugin, describing the nature of the vulnerability, but noting that there is no fix other than no longer using the plugin.
  If there are workarounds, explain them.
. Depending on the nature of the vulnerability, stop publishing the vulnerable plugin on the Jenkins update site.
. Add metadata to the plugin site indicating vulnerable plugins to inform administrator who may already have the plugin installed.
  Displaying these warnings is supported from Jenkins 2.40 and LTS 2.32.2.

